Repository centreon/centreon, pull requests merged in 2018-06, with the labels that each got.

#6265 enh(pdo): do not manage pdo exception on lowest level of application
  www/class/centreonDB.class.php
Labels: area/install, kind/enhancement

#6365 Cp7 m53 ongoing fixes
  www/class/centreonPurgeEngine.class.php
  www/include/configuration/configObject/contact/ldapImportContact.php
  www/include/home/customViews/rename.php
Labels: area/engine, area/ldap, area/widgets

#6381 fix(db): insert meta service with single quotes
  www/include/configuration/configObject/meta_service/DB-Func.php
Labels: area/database

#6380 fix(api): timeperiod API response without HTML encoding
  www/api/class/centreon_configuration_timeperiod.class.php
  www/api/class/webService.class.php
Labels: area/api

#6250 fix(sec): Fix SQL injection in dashboard
  www/include/reporting/dashboard/xmlInformations/GetXmlHost.php
  www/include/reporting/dashboard/xmlInformations/GetXmlHostGroup.php
  www/include/reporting/dashboard/xmlInformations/GetXmlService.php
  www/include/reporting/dashboard/xmlInformations/GetXmlServiceGroup.php
Labels: area/security

#6251 fix(sec): Fix SQL injection on graphs
  www/class/centreonCommand.class.php
  www/include/configuration/configObject/command/formArguments.php
  www/include/configuration/configObject/command/javascript/commandJs.php
Labels: area/security

#6263 fix(sec): Fix execution command by rrdtool command line
  www/class/centreonGraph.class.php
Labels: area/security

#6255 fix(sec): Fix SQL Injection in administration logs
  www/include/Administration/configChangelog/viewLogs.ihtml
  www/include/Administration/configChangelog/viewLogs.php
Labels: area/security

#6379 Add Centreon web 2.8.24 release note
  doc/en/release_notes/centreon-2.8/centreon-2.8.24.rst
  doc/fr/release_notes/centreon-2.8/centreon-2.8.24.rst
Labels: kind/documentation
