Repository centreon/centreon, pull requests merged in 2018-07, with the labels that each got.

#6420 fix(cron): remove useless include to avoid warning in acl cron
  cron/centAcl.php
Labels: area/acl, kind/bug

#6438 feat(conf): add JS validation of Time Range Exceptions
  www/include/common/javascript/jquery/plugins/centreon/jquery.centreonValidate.js
  www/include/configuration/configObject/timeperiod/formTimeperiod.php
  www/include/configuration/configObject/timeperiod/timeperiod_JS.php
Labels: area/configuration

#6439 fix(admin): fix PHP warnings in Administration > Parameters > Data an…
  www/include/Administration/performance/viewData.php
  www/include/views/virtualMetrics/listVirtualMetrics.php
Labels: area/administration

#6443 fix(report): missing colors color_maintenance and color_undetermined …
  www/include/reporting/dashboard/ajaxReporting_js.php
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/reporting/dashboard/viewServicesLog.php
Labels: area/reporting

#6446 fix(ux): the mass selection doesn't work the second time
  www/include/common/javascript/tool.js
Labels: area/ux

#6448 fix(cv): issue with moving of widgets
  www/class/centreonWidget.class.php
Labels: area/custom-views

#6410 fix(README): Adding Stéphane Chapron to dev team
  README.md
Labels: area/install

#6253 Adding Mr Baldo to Dev Team.
  README.md
Labels: area/install

#6382 fix(reporting): avoid bug on partitioned tables
  www/include/reporting/dashboard/xmlInformations/GetXmlHost.php
  www/include/reporting/dashboard/xmlInformations/GetXmlService.php
Labels: area/reporting, kind/bug

#6456 fix(ux): make an immediately check_session request
  www/include/core/autologout/autologout.php
Labels: area/ux

#6473 feat(cv): upgrade library a jquery jeditable to version 2.0.5
  www/include/common/javascript/jquery/plugins/jeditable/jquery.jeditable-min.js
Labels: area/custom-views
