Repository centreon/centreon, pull requests merged in 2018-10, with the labels that each got.

#6684 fix(admin): after install/upgrade all reload parent page
  www/include/options/oreon/modules/modulesAction.tpl
  www/include/options/oreon/widgets/list.php
Labels: area/administration

#6685 fix(admin): Inception when saving a modification in a Parameters -> C…
  www/include/Administration/parameters/css/form.ihtml
  www/include/Administration/parameters/css/form.php
Labels: area/administration

#6686 fix(ux): wording issue in header menu host's drop-down
  www/front_src/src/components/hostMenu/index.js
Labels: area/ux

#6689 fix(admin): reload parent window when the module is updated or installed
  www/include/options/oreon/modules/installForm.php
  www/include/options/oreon/modules/listModules.php
  www/include/options/oreon/modules/reload.ihtml
Labels: area/administration

#6696 fix(widget): Errors when saving preferences of widget
  www/include/home/customViews/widgetParam.html
Labels: area/widgets

#6707 fix(ux): the centreon message box hide part of a filter form
  www/Themes/Centreon-2/style.css
  www/main.get.php
Labels: area/ux

#6706 fix(ux): add base path of links in header
  www/front_src/src/components/hostMenu/index.js
  www/front_src/src/components/pollerMenu/index.js
  www/front_src/src/components/serviceStatusMenu/index.js
  www/front_src/src/components/userMenu/index.js
  www/front_src/src/config/index.js
Labels: area/ux

#6678 Add chapter to describe the new main banner
  doc/en/_static/images/exploitation/header/Profil.png
  doc/en/_static/images/exploitation/header/full_header.png
  doc/en/_static/images/exploitation/header/hosts_state.png
  doc/en/_static/images/exploitation/header/hosts_state_details.png
  doc/en/_static/images/exploitation/header/hosts_state_pending.png
  doc/en/_static/images/exploitation/header/pollers_state.png
  doc/en/_static/images/exploitation/header/services_state.png
  doc/en/_static/images/exploitation/header/services_state_details.png
  doc/en/_static/images/exploitation/header/services_state_pending.png
  doc/en/exploitation_guide/header.rst
  doc/en/exploitation_guide/index.rst
  doc/fr/_static/images/exploitation/header/Profil.png
  doc/fr/_static/images/exploitation/header/full_header.png
  doc/fr/_static/images/exploitation/header/hosts_state.png
  doc/fr/_static/images/exploitation/header/hosts_state_details.png
  doc/fr/_static/images/exploitation/header/hosts_state_pending.png
  doc/fr/_static/images/exploitation/header/pollers_state.png
  doc/fr/_static/images/exploitation/header/services_state.png
  doc/fr/_static/images/exploitation/header/services_state_details.png
  doc/fr/_static/images/exploitation/header/services_state_pending.png
  doc/fr/exploitation_guide/header.rst
  doc/fr/exploitation_guide/index.rst
Labels: kind/documentation

#6694 Doc migration to 18.10
  doc/en/_static/images/upgrade/web_update_1.png
  doc/en/_static/images/upgrade/web_update_2.png
  doc/en/_static/images/upgrade/web_update_3.png
  doc/en/_static/images/upgrade/web_update_4.png
  doc/en/_static/images/upgrade/web_update_5.png
  doc/en/index.rst
  doc/en/migration/index.rst
  doc/en/migration/upgradetoCentreon18.10.rst
  doc/en/upgrade/from_packages.rst
  doc/fr/_static/images/upgrade/web_update_1.png
  doc/fr/_static/images/upgrade/web_update_2.png
  doc/fr/_static/images/upgrade/web_update_3.png
  doc/fr/_static/images/upgrade/web_update_4.png
  doc/fr/_static/images/upgrade/web_update_5.png
  doc/fr/index.rst
  doc/fr/migration/index.rst
  doc/fr/migration/upgradetoCentreon18.10.rst
  doc/fr/upgrade/from_packages.rst
Labels: kind/documentation

#6736 fix(mon): using of undefined variable
  www/include/monitoring/common-Func.php
Labels: area/monitoring

#6745 fix(ux): remove warning icon v2
  www/main.get.php
Labels: area/ux

#6766 fix(mon): syntax error in monitoring status pages
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/monitoring

#6726 fix(doc): update Rest syntax for a code block
  doc/en/configuration_guide/process_description/managetraps.rst
Labels: kind/documentation

#6765 enh(doc): Add CEIP program chapter
  doc/en/ceip.rst
  doc/en/index.rst
  doc/fr/ceip.rst
  doc/fr/index.rst
Labels: area/install, kind/documentation

#6769 fix(report): the datepicker drop selected date after form submission
  www/include/common/javascript/datepicker/localizedDatepicker.js
Labels: area/reporting

#6782 fix(ux): exclude services started by BA from BAM UI notification style
  www/include/monitoring/status/Notifications/notifications.php
Labels: area/ux, kind/bug

#6771 fix(doc): Update admin configure distributed architecture
  doc/en/administration_guide/poller/install_remote_server.rst
  doc/en/administration_guide/poller/wizard_add_poller.rst
  doc/en/images/poller/wizard_add_poller_2.png
  doc/en/images/poller/wizard_add_poller_3.png
  doc/en/images/poller/wizard_add_poller_4.png
  doc/en/images/poller/wizard_add_poller_5.png
  doc/en/images/poller/wizard_add_remote_2a.png
  doc/en/images/poller/wizard_add_remote_3.png
  doc/en/images/poller/wizard_add_remote_4.png
  doc/en/images/poller/wizard_add_remote_5.png
  doc/en/migration/index.rst
  doc/fr/administration_guide/poller/install_remote_server.rst
  doc/fr/administration_guide/poller/wizard_add_poller.rst
  doc/fr/images/poller/wizard_add_poller_2.png
  doc/fr/images/poller/wizard_add_poller_3.png
  doc/fr/images/poller/wizard_add_poller_4.png
  doc/fr/images/poller/wizard_add_poller_5.png
  doc/fr/images/poller/wizard_add_remote_2a.png
  doc/fr/images/poller/wizard_add_remote_3.png
  doc/fr/images/poller/wizard_add_remote_4.png
  doc/fr/images/poller/wizard_add_remote_5.png
Labels: area/install, kind/documentation

#6805 fix(style): Add missing style for button in svc ack form
  www/include/monitoring/acknowlegement/serviceAcknowledge.php
Labels: area/ux, kind/bug

#6806 add localization to pt-BR (Portuguese Brazil)
  lang/pt_BR/LC_MESSAGES/help.po
  lang/pt_BR/LC_MESSAGES/messages.po
  www/include/common/javascript/datepicker/datepicker-pt.js
Labels: area/install, area/ux

#6795 fix(doc): add missing services to add manually in autostart of systemd
  doc/en/installation/from_packages.rst
  doc/fr/installation/from_packages.rst
Labels: kind/documentation

#6813 enh(Remote Server): add a new field in poller form to attach a poller to a Remote Server
  www/api/class/centreon_configuration_poller.class.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.ihtml
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/help.php
  www/include/configuration/configServers/listServers.php
Labels: area/configuration, kind/enhancement

#6811 Add translation to spanish
  lang/es/LC_MESSAGES/help.po
  lang/es/LC_MESSAGES/messages.po
  www/include/common/javascript/datepicker/datepicker-es.js
Labels: area/install, area/ux

#6797 fix(centreontrapd): use centcore directory instead of command file
  lib/perl/centreon/script/centreontrapd.pm
Labels: area/monitoring, kind/enhancement

#6758 enh(centcore): Use Remote Server to send conf and external commands
  lib/perl/centreon/script.pm
  lib/perl/centreon/script/centcore.pm
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
Labels: area/install, kind/enhancement

#6824 Updates to remote
  .gitignore
  filesGeneration/export/.keep
  lib/perl/centreon/script/centcore.pm
  libinstall/CentWeb.sh
  src/Centreon/Domain/Entity/Command.php
  src/Centreon/Domain/Repository/CfgResourceRepository.php
  src/Centreon/Infrastructure/Service/CentcoreConfigService.php
  src/Centreon/ServiceProvider.php
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
  src/CentreonRemote/Domain/Exporter/PollerExporter.php
  src/CentreonRemote/Domain/Service/PollerDefaultsOverwriteService.php
  src/CentreonRemote/Infrastructure/Export/ExportCommitment.php
  src/CentreonRemote/Infrastructure/Export/ExportManifest.php
  src/CentreonRemote/Infrastructure/Export/ExportParserInterface.php
  src/CentreonRemote/Infrastructure/Export/ExportParserYaml.php
  src/CentreonRemote/Infrastructure/Service/ExportService.php
  src/CentreonRemote/Infrastructure/Service/ExporterServiceAbstract.php
  src/CentreonRemote/ServiceProvider.php
Labels: area/remote-server

#6827 fix(ux): when label is missing from navigation menu API react transla…
  www/front_src/src/components/navigation/index.js
Labels: area/ux

#6830 fix(ux): click event on the link that has attribute onload must be no…
  www/include/core/footer/footerPart.php
Labels: area/ux

#6757 enh(about): update centreon list of developers & contributors
  www/include/Administration/about/about.php
Labels: area/install

#6836 fix(remote-server) Minor fixes for remote server worker
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
Labels: area/remote-server, kind/enhancement

#6823 enh(doc): Add chapter to migrate Poller Display to Remote Server
  doc/en/administration_guide/poller/wizard_add_poller.rst
  doc/en/migration/index.rst
  doc/en/migration/pollerdisplaytoremoteserver.rst
  doc/en/migration/upgradetoCentreon18.10.rst
  doc/en/upgrade/from_packages.rst
  doc/en/upgrade/index.rst
  doc/fr/administration_guide/poller/wizard_add_poller.rst
  doc/fr/migration/index.rst
  doc/fr/migration/pollerdisplaytoremoteserver.rst
  doc/fr/migration/upgradetoCentreon18.10.rst
  doc/fr/upgrade/from_packages.rst
  doc/fr/upgrade/index.rst
Labels: area/remote-server, kind/documentation

#6849 Bam export bam 361
  src/Centreon/Domain/Repository/ServiceRepository.php
  src/Centreon/Infrastructure/Provider/AutoloadServiceProvider.php
  src/CentreonRemote/Domain/Exporter/CommandExporter.php
  src/CentreonRemote/Domain/Exporter/DowntimeExporter.php
  src/CentreonRemote/Domain/Exporter/GraphExporter.php
  src/CentreonRemote/Domain/Exporter/HostExporter.php
  src/CentreonRemote/Domain/Exporter/MediaExporter.php
  src/CentreonRemote/Domain/Exporter/MetaServiceExporter.php
  src/CentreonRemote/Domain/Exporter/PollerExporter.php
  src/CentreonRemote/Domain/Exporter/ServiceExporter.php
  src/CentreonRemote/Domain/Exporter/TimePeriodExporter.php
  src/CentreonRemote/Domain/Exporter/TrapExporter.php
  src/CentreonRemote/Infrastructure/Service/ExporterService.php
  src/CentreonRemote/Infrastructure/Service/ExporterServiceAbstract.php
  src/CentreonRemote/Infrastructure/Service/ExporterServiceInterface.php
Labels: area/remote-server

#6699 fix(trap): fix regexp for trap argument ending by backslash
  lib/perl/centreon/trapd/lib.pm
Labels: area/configuration, kind/bug, priority/minor

#6860 fix(remote): export BA hosts
  src/Centreon/Domain/Repository/HostTemplateRelationRepository.php
  src/CentreonRemote/Domain/Exporter/HostExporter.php
Labels: area/remote-server

#6475 Fix wording of ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: kind/bug

#6855 fix(acl): Host number calculation with ACL is not correct in HG summary
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
Labels: area/acl, kind/bug, priority/major

#6436 fix(acl): Host number calculation with ACL is not correct in HG summary
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
Labels: area/acl, kind/bug, priority/major

#6850 enh(remote-server): Add light form to edit contact on a Remote Server
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/formContactLight.ihtml
Labels: area/configuration, area/remote-server

#6870 fix(remote): empty bam broker config on new remote server
  src/CentreonRemote/Domain/Resources/remote_config/bam_broker_cfg_info.php
Labels: area/remote-server

#6873 fix(remote): BAM output configuration will be not add to remote server
  src/CentreonRemote/Domain/Service/ConfigurationWizard/RemoteConnectionConfigurationService.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
Labels: area/remote-server

#6900 enh(doc): Improve FAQ chapter
  doc/en/ceip.rst
  doc/en/faq/administration.rst
  doc/en/faq/gdpr_compliance.rst
  doc/en/faq/general.rst
  doc/en/faq/index.rst
  doc/en/faq/performance.rst
  doc/fr/ceip.rst
  doc/fr/faq/administration.rst
  doc/fr/faq/general.rst
  doc/fr/faq/index.rst
  doc/fr/faq/performance.rst
Labels: kind/documentation

#6896 Improve doc
  doc/en/installation/architecture/03e.rst
  doc/en/installation/prerequisites.rst
  doc/fr/installation/architecture/03e.rst
  doc/fr/installation/prerequisites.rst
Labels: kind/documentation

#6907 fix(doc) Migration 1810: moove the installDir FR
  doc/fr/migration/upgradetoCentreon18.10.rst
Labels: kind/documentation

#6917 fix(typo) - fix warning
  www/class/centreon-clapi/centreonService.class.php
Labels: area/configuration, kind/bug, priority/minor

#6918 fix(warning) - remove duplicate() method in children classes so no PH…
  lib/Centreon/Object/Host/Extended.php
  lib/Centreon/Object/Host/Macro/Custom.php
  lib/Centreon/Object/Service/Extended.php
  lib/Centreon/Object/Service/Macro/Custom.php
  lib/Centreon/Object/Timeperiod/Exception.php
Labels: priority/minor

#6916 Update procedure should include all centreon* packages.
  doc/en/upgrade/from_packages.rst
  doc/fr/upgrade/from_packages.rst
Labels: area/install, kind/documentation

#6920 fix(doc): spelling correction
  doc/fr/migration/pollerdisplaytoremoteserver.rst
Labels: kind/documentation
