Repository centreon/centreon, pull requests merged in 2018-03, with the labels that each got.

#6086 fix(doc): add a remote poller
  doc/en/configuration_guide/poller/01installation.rst
  doc/en/configuration_guide/poller/02configuration.rst
  doc/en/images/user/configuration/10advanced_configuration/07_Addbroker.png
  doc/en/images/user/configuration/10advanced_configuration/07_Addbroker_output.png
  doc/en/images/user/configuration/10advanced_configuration/07addengine.png
  doc/en/images/user/configuration/10advanced_configuration/07addpoller.png
  doc/en/images/user/configuration/10advanced_configuration/07addpoller_neb.png
  doc/fr/configuration_guide/poller/01installation.rst
  doc/fr/configuration_guide/poller/02configuration.rst
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/07_Addbroker.png
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/07_Addbroker_output.png
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/07addengine.png
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/07addpoller.png
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/07addpoller_neb.png
Labels: kind/bug, kind/documentation, priority/major

#6098 fix(config) set default poller
  www/install/php/Update-2.8.19_to_2.8.20.php
  www/install/var/baseconf/centreon-engine.sql
Labels: area/install, kind/enhancement

#6099 fix(clapi) link host with default poller if unknown poller
  lib/Centreon/Object/Instance/Instance.php
  www/class/centreon-clapi/centreonHost.class.php
Labels: area/api, area/configuration, kind/enhancement

#6100 fix(clapi) export specific service, add host before service
  www/class/centreon-clapi/centreonService.class.php
Labels: area/api, area/configuration, kind/bug, priority/major

#6101 Add notice for 64bits support only
  doc/en/installation/prerequisites.rst
  doc/fr/installation/prerequisites.rst
Labels: area/install, kind/documentation

#5995 Php deprecated
  www/class/centreonUser.class.php
  www/class/centreonXML.class.php
  www/class/config-generate/engine.class.php
  www/include/Administration/configChangelog/viewLogs.php
  www/include/configuration/configKnowledge/pagination.php
  www/include/configuration/configObject/command/listCommand.php
  www/include/eventLogs/xml/data.php
  www/include/monitoring/comments/AddSvcComment.php
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/recurrentDowntime/json.php
  www/install/index.php
Labels: kind/enhancement

#6129 fix (doc): Remote Poller documentation
  doc/en/configuration_guide/poller/01installation.rst
  doc/en/configuration_guide/poller/02configuration.rst
  doc/fr/configuration_guide/poller/01installation.rst
  doc/fr/configuration_guide/poller/02configuration.rst
Labels: kind/documentation

#6122 Update style.css
  www/Themes/Centreon-2/style.css
Labels: area/ux, kind/bug, priority/trivial

#6128 fix(ldap): allow nested groups filter in ldap configuration
  www/class/centreonLDAP.class.php
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/administration, kind/enhancement

#6146 Missing screenshot
  doc/en/configuration_guide/poller/02configuration.rst
Labels: kind/documentation

#6155 fix(clapi):Add missing SC
  tests/clapi_export/clapi-configuration.txt
Labels: kind/bug, kind/enhancement

#6152 correct screenshot path
  doc/en/configuration_guide/poller/02configuration.rst
Labels: kind/documentation
