Repository centreon/centreon, pull requests merged in 2018-05, with the labels that each got.

#6262 fix(centAcl.php): Dead code removed
  cron/centAcl.php
Labels: area/install

#6270 Cp7 m15 fix php warnings
  www/class/centreonLogAction.class.php
  www/class/centreonSession.class.php
  www/include/Administration/parameters/parameters.php
  www/include/core/menu/menu.php
  www/include/home/customViews/views.php
  www/include/options/accessLists/actionsACL/DB-Func.php
  www/include/options/accessLists/groupsACL/DB-Func.php
  www/include/options/accessLists/menusACL/DB-Func.php
  www/include/options/accessLists/reloadACL/reloadACL.php
  www/include/options/accessLists/resourcesACL/DB-Func.php
  www/include/options/media/images/DB-Func.php
  www/include/options/session/connected_user.php
  www/include/views/graphTemplates/formGraphTemplate.php
  www/lib/HTML/QuickForm/advmultiselect.php
Labels: area/acl, area/install

#6271 Cp7m10 validate views post smarty update
  .gitignore
  www/api/class/centreon_administration_widget.class.php
  www/api/class/centreon_clapi.class.php
  www/api/class/centreon_configuration_objects.class.php
  www/api/class/centreon_configuration_servicecategory.class.php
  www/api/class/centreon_home_customview.class.php
  www/api/class/centreon_keepalive.class.php
  www/api/class/centreon_metric.class.php
  www/api/class/centreon_proxy.class.php
  www/api/class/centreon_realtime_base.class.php
  www/api/class/centreon_wiki.class.php
  www/img/media/.keep
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/service/formService.php
  www/include/home/customViews/views.php
  www/include/monitoring/status/TopCounter/xml/statusCounter.php
  www/include/options/media/images/DB-Func.php
Labels: area/install

#6298 Add information regarding GDPR
  doc/en/faq/gdpr_compliance.rst
  doc/en/faq/index.rst
  doc/fr/faq/gdpr_compliance.rst
  doc/fr/faq/index.rst
Labels: area/security

#6309 fix(front): fix acl actions checkboxes (check all / uncheck all)
  www/include/options/accessLists/actionsACL/formActionsAccess.ihtml
Labels: kind/bug
