Repository centreon/centreon, pull requests merged in 2018-12, with the labels that each got.

#7018 enh(instlal): Update to 18.10.1
  doc/en/release_notes/centreon-18.10/centreon-18.10.1.rst
  doc/en/release_notes/centreon-18.10/index.rst
  doc/fr/release_notes/centreon-18.10/centreon-18.10.1.rst
  doc/fr/release_notes/centreon-18.10/index.rst
  install.sh
  www/install/insertBaseConf.sql
  www/install/sql/centreon/Update-DB-18.10.0_to_18.10.1.sql
Labels: area/install

#6976 fix(ui): manage fullscreen even with iframe navigation
  www/front_src/src/App.js
  www/front_src/src/route-components/module/index.js
Labels: kind/bug, priority/minor

#6974 fix(mysql) fix mysql bug on partitioned tables
  doc/en/faq/administration.rst
  doc/en/installation/prerequisites.rst
  doc/fr/faq/administration.rst
  doc/fr/installation/prerequisites.rst
  www/include/reporting/dashboard/DB-Func.php
Labels: area/install, kind/bug, priority/major

#6962 Mon 2803 acl resources access
  lang/fr/LC_MESSAGES/messages.po
  www/include/configuration/configObject/hostgroup/formHostGroup.ihtml
  www/include/configuration/configObject/hostgroup/formHostGroup.php
  www/include/configuration/configObject/hostgroup/hostGroup.php
  www/include/monitoring/recurrentDowntime/formDowntime.html
  www/include/monitoring/recurrentDowntime/formDowntime.php
  www/include/monitoring/recurrentDowntime/templates/monthly_basis.html
  www/include/monitoring/recurrentDowntime/templates/specific_date.html
  www/include/monitoring/recurrentDowntime/templates/weekly_basis.html
Labels: area/acl, area/monitoring, kind/enhancement

#6965 fix(doc): correct typo in RS architecture FR chapter
  doc/fr/installation/architecture/03e.rst
Labels: area/documentation

#7026 Doc correct vm description
  doc/en/installation/downloads.rst
  doc/en/installation/from_VM.rst
  doc/fr/installation/downloads.rst
  doc/fr/installation/from_VM.rst
Labels: area/documentation, kind/bug, priority/minor

#6961 Fix SQL injection and duplicate action
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host/host.php
  www/include/configuration/configObject/host/listHost.ihtml
  www/include/configuration/configObject/host/listHost.php
Labels: kind/bug, kind/security

#7024 fix(conf): prevent timeperiod to call itself via templates
  src/Centreon/Domain/Repository/TimePeriodRepository.php
  www/api/class/centreon_configuration_timeperiod.class.php
  www/include/configuration/configObject/timeperiod/DB-Func.php
  www/include/configuration/configObject/timeperiod/formTimeperiod.php
Labels: area/configuration

#7063 Remote server add multiple authorized master
  doc/en/administration_guide/poller/enable_remote.rst
  doc/fr/administration_guide/poller/enable_remote.rst
  src/Centreon/Domain/Repository/InformationsRepository.php
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
Labels: area/remote-server, kind/enhancement

#7064 clear /var/lib/mysql + correct rsync
  doc/fr/migration/upgradetoCentreon18.10.rst
Labels: kind/documentation

#6982 enh(poller): Fix the XSS vulnerability on poller resource
  behat.yml
  features/PollerResourceConfiguration.feature
  features/bootstrap/PollerResourceConfigurationContext.php
  www/include/configuration/configResources/DB-Func.php
  www/include/configuration/configResources/formResources.php
  www/include/configuration/configResources/listResources.php
  www/include/configuration/configResources/resources.php
Labels: kind/security

#7055 fix(doc) FR Filter on only one object
  doc/fr/exploitation_guide/01customview.rst
Labels: kind/documentation, kind/enhancement

#7056 fix(doc) EN: Filter on only one object
  doc/en/exploitation_guide/01customview.rst
Labels: kind/documentation

#7020 #MON-3260 fix macro password in clear
  www/class/centreonHost.class.php
Labels: area/configuration, kind/bug, kind/security

#7076 [DOC] Correction commande incorrecte
  doc/fr/administration_guide/partitioning/user/exploitation.rst
Labels: area/install, kind/documentation, kind/enhancement

#7075 fix(UI): french translation misspelling
  lang/fr/LC_MESSAGES/messages.po
Labels: area/translation

#7069 fix(trap_snmp): Fix SQL injection and duplicate feature
  www/class/centreonTraps.class.php
  www/class/centreonUtils.class.php
  www/include/configuration/configObject/traps/formTraps.php
  www/include/configuration/configObject/traps/listTraps.ihtml
  www/include/configuration/configObject/traps/listTraps.php
  www/include/configuration/configObject/traps/traps.php
Labels: area/configuration, kind/security

#7057 fix(auth): add sync with ldap groups upon login
  www/class/centreonAuth.LDAP.class.php
  www/class/centreonLDAP.class.php
Labels: area/administration, area/ldap, kind/bug

#7067 test(unit): add unit tests to remote server
  .gitignore
  build.xml
  composer.json
  phpunit.xml
  src/Centreon/Infrastructure/Service/Traits/ServiceContainerTrait.php
  src/Centreon/ServiceProvider.php
  src/Centreon/Tests/AppKeyGeneratorServiceTest.php
  src/Centreon/Tests/Domain/Repository/TopologyRepositoryTest.php
  src/Centreon/Tests/ServiceProviderTest.php
  src/CentreonRemote/Infrastructure/Export/ExportManifest.php
  src/CentreonRemote/Infrastructure/Export/ExportParserInterface.php
  src/CentreonRemote/Infrastructure/Export/ExportParserYaml.php
  src/CentreonRemote/Infrastructure/Service/ExporterService.php
  src/CentreonRemote/Infrastructure/Service/ExporterServiceAbstract.php
  src/CentreonRemote/Tests/.keep
  src/CentreonRemote/Tests/Infrastructure/Export/ExportCommitmentTest.php
  src/CentreonRemote/Tests/Infrastructure/Export/ExportManifestTest.php
  src/CentreonRemote/Tests/Infrastructure/Export/ExportParserYamlTest.php
  src/CentreonRemote/Tests/Infrastructure/Service/ExportServiceTest.php
  src/CentreonRemote/Tests/Infrastructure/Service/ExporterCacheServiceTest.php
  src/CentreonRemote/Tests/Infrastructure/Service/ExporterServiceTest.php
  src/CentreonRemote/Tests/ServiceProviderTest.php
  tests/php/bootstrap.php
  www/class/centreonDB.class.php
  www/class/centreonDBInstance.class.php
  www/class/centreonDBStatement.class.php
  www/class/centreonExternalCommand.class.php
  www/class/centreonGMT.class.php
  www/class/config-generate/backend.class.php
  www/class/config-generate/generate.class.php
Labels: area/tests, build/jenkins
