Repository centreon/centreon, pull requests merged in 2018-08, with the labels that each got.

#6485 enh(doc): Improve Centreon IMP chapter
  doc/en/_static/images/configuration/imp5.png
  doc/en/_static/images/configuration/imp6.png
  doc/en/configuration_guide/imp/index.rst
  doc/fr/_static/images/configuration/imp5.png
  doc/fr/_static/images/configuration/imp6.png
  doc/fr/configuration_guide/imp/index.rst
Labels: kind/documentation

#6540 fix(doc): Incrase Centreon web version number for PDF generation
  doc/en/conf.py
  doc/fr/conf.py
Labels: area/documentation, kind/bug, priority/trivial

#6453 fix(doc): correct typo
  doc/en/configuration_guide/imp/index.rst
  doc/fr/configuration_guide/imp/index.rst
  www/install/sql/centreon/Update-DB-2.8.24_to_2.8.25.sql
Labels: kind/documentation

#6432 fix(doc): fix images for db replication
  doc/en/images/architecture/dschema.png
  doc/en/images/architecture/eschema.png
  doc/fr/images/architecture/dschema.png
  doc/fr/images/architecture/eschema.png
Labels: kind/documentation

#6430 Fix doc architecture
  doc/en/installation/architecture/03d.rst
  doc/en/installation/architecture/03e.rst
  doc/fr/installation/architecture/03d.rst
  doc/fr/installation/architecture/03e.rst
Labels: kind/documentation

#6393 clean(code): remove dead code from escalation page
  www/include/configuration/configObject/escalation/formEscalation.php
Labels: area/install

#6511 fix(front): Standardization of the selector "$" to "jQuery" in the fo…
  www/include/core/footer/footer.php
Labels: area/install

#6416 fix(conf): trap generation reindexing pollers id
  www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/configuration, kind/bug, priority/trivial

#6513 fix(Status Details) display true inheritance relation
  www/include/monitoring/common-Func.php
Labels: area/monitoring, kind/bug, priority/minor

#6538 Remove old lib js
  www/include/common/javascript/color_picker_mb.js
  www/include/common/javascript/topCounterStatus/ajaxStatusCounter.js
  www/include/core/header/htmlHeader.php
  www/include/views/componentTemplates/formComponentTemplate.php
  www/include/views/graphTemplates/formGraphTemplate.php
Labels: area/install

#6543 fix(Header): user localisation setting wasn't saved
  www/include/core/menu/templates/BlockHeader.ihtml
Labels: area/ux, kind/bug

#6552 Update centreon doc to 18.9
  doc/en/images/user/module_installation.png
  doc/en/installation/from_iso.rst
  doc/en/installation/from_packages.rst
  doc/fr/images/guide_utilisateur/module_installation.png
  doc/fr/installation/from_iso.rst
  doc/fr/installation/from_packages.rst
Labels: area/documentation, area/install

#6551 fix(topology): Add topology url option when loading default page
  www/class/centreonAuth.class.php
Labels: area/configuration, kind/bug, priority/minor

#6547 fix(monitoring): Sort hosts by name ASC in serviceGridByHGXML
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
Labels: area/monitoring, kind/bug, priority/minor

#6484 fix(acl): do not get severity of parents if present on actual object
  cron/centAcl-Func.php
Labels: area/acl, kind/bug

#6541 fix(doc): correct link references in IMP chapter
  doc/en/configuration_guide/imp/index.rst
  doc/fr/configuration_guide/imp/index.rst
Labels: area/administration, kind/bug, priority/trivial

#6210 remove old and unused file in order to avoid problems with ACL
  www/include/common/quickSearch.ihtml
  www/include/common/quickSearch.php
  www/include/options/accessLists/define/DB-Func.php
  www/include/options/accessLists/define/formLCA.ihtml
  www/include/options/accessLists/define/formLCA.php
  www/include/options/accessLists/define/index.html
  www/include/options/accessLists/define/lca.php
  www/include/options/accessLists/define/listLCA.ihtml
  www/include/options/accessLists/define/listLCA.php
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-2.8.25_to_2.8.26.sql
Labels: area/install

#6495 enh(perf): Optimize acl filter calculation
  cron/centAcl-Func.php
  cron/centAcl.php
Labels: area/acl, area/configuration, kind/performance
