Repository centreon/centreon, pull requests merged in 2019-02, with the labels that each got.

#7171 fix(security): fix unauthorized file upload
  www/include/options/oreon/modules/licenseUpload.php
Labels: area/security

#7194 fix(UI): correct comments date in host and svc detail pages
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: kind/enhancement

#5969 fix(reporting): add downtimes information in CSV export of dashboard
  www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
  www/include/reporting/dashboard/csvExport/csv_HostLogs.php
  www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php
  www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Labels: area/reporting, kind/enhancement

#7191 Mon 3291 minor fixes on page load
  www/include/views/componentTemplates/formComponentTemplate.php
  www/include/views/graphTemplates/listGraphTemplates.php
  www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: kind/enhancement

#7016 fix(kb): correct documentation link
  www/include/configuration/configKnowledge/functions.php
Labels: kind/bug, priority/trivial

#7184 Rework Jenkinsfile to handle release builds
  Jenkinsfile
Labels: build/jenkins

#7200 security(remove) clean dead code
  www/include/configuration/configObject/escalation/ViewEscalation.ihtml
  www/include/configuration/configObject/escalation/ViewEscalation.php
  www/include/configuration/configObject/escalation/img_gantt.php
Labels: kind/security

#7208 enh(host templates): change host template dropdown to be select2 inst…
  www/class/centreonHost.class.php
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: kind/enhancement

#7187 Mon 3317 clapi ack
  doc/en/api/clapi/objects/realtime_acknowledgement.rst
  doc/fr/api/clapi/objects/realtime_acknowledgement.rst
  doc/fr/api/clapi/objects/realtime_downtimes.rst
  lib/Centreon/Object/Acknowledgement/RtAcknowledgement.php
  tests/rest_api/realtime_rest_api.postman_collection.json
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreon-clapi/centreonRtAcknowledgement.class.php
  www/class/centreonExternalCommand.class.php
Labels: area/api, area/monitoring, kind/enhancement

#7229 fix(xss): fix SQL injection for GET parameter
  www/include/views/graphs/common/makeXML_ListServices.php
Labels: area/security

#7238 enh(doc): improved English documentation, thanks to jefestyler
  doc/en/administration_guide/poller/add_manually_a_poller.rst
  doc/en/administration_guide/poller/advanced_configuration_broker.rst
  doc/en/administration_guide/poller/enable_remote.rst
  doc/en/administration_guide/poller/index.rst
  doc/en/administration_guide/poller/install_poller.rst
  doc/en/administration_guide/poller/install_poller_iso.rst
  doc/en/administration_guide/poller/install_poller_packages.rst
  doc/en/administration_guide/poller/install_remote_server.rst
  doc/en/administration_guide/poller/pollersstats.rst
  doc/en/administration_guide/poller/ssh_key.rst
  doc/en/administration_guide/poller/wizard_add_poller.rst
  doc/en/administration_guide/poller/wizard_add_remote.rst
  doc/en/installation/common/install_iso.rst
  doc/en/installation/common/install_packages.rst
  doc/en/installation/common/post_install.rst
  doc/en/installation/common/web_install.rst
  doc/en/installation/from_VM.rst
  doc/en/installation/prerequisites.rst
  doc/en/life_cycle.rst
  doc/en/migration/index.rst
  doc/en/migration/pollerdisplaytoremoteserver.rst
  doc/en/migration/upgradetoCentreon18.10.rst
  doc/en/upgrade/from_packages.rst
  doc/en/upgrade/from_sources.rst
  doc/en/upgrade/index.rst
Labels: kind/documentation, kind/enhancement
