Repository centreon/centreon, pull requests merged in 2019-05, with the labels that each got.

#7523 enh(ISSUE_TEMPLATE.md): enhance GitHub information for issues
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
Labels: kind/documentation

#7341 fix(graph): no-unit series now trigger a second axis
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/chart, kind/bug

#7539 enh(install): prepare Centreon web 2.8.28 version
  Update-DB-2.8.27_to_2.8.28.sql
  doc/en/conf.py
  doc/en/release_notes/centreon-2.8/centreon-2.8.28.rst
  doc/en/release_notes/centreon-2.8/index.rst
  doc/fr/conf.py
  doc/fr/release_notes/centreon-2.8/centreon-2.8.28.rst
  doc/fr/release_notes/centreon-2.8/index.rst
  www/install/insertBaseConf.sql
Labels: area/install

#7545 Mon 3859 correct administration parameters monitoring modify form redirect
  www/include/Administration/parameters/engine/form.php
Labels: kind/bug

#7544 (fix) MySQL strict mode issues
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/parameters/DB-Func.php
  www/include/configuration/configCentreonBroker/DB-Func.php
  www/include/configuration/configGenerate/DB-Func.php
  www/include/configuration/configObject/command/DB-Func.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contactgroup/DB-Func.php
  www/include/configuration/configObject/escalation/DB-Func.php
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/host_categories/DB-Func.php
  www/include/configuration/configObject/host_dependency/DB-Func.php
  www/include/configuration/configObject/hostgroup/DB-Func.php
  www/include/configuration/configObject/hostgroup_dependency/DB-Func.php
  www/include/configuration/configObject/meta_service/DB-Func.php
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/service_categories/DB-Func.php
  www/include/configuration/configObject/service_dependency/DB-Func.php
  www/include/configuration/configObject/servicegroup/DB-Func.php
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
  www/include/configuration/configObject/timeperiod/DB-Func.php
  www/include/configuration/configObject/traps-groups/DB-Func.php
  www/include/configuration/configObject/traps-manufacturer/DB-Func.php
  www/include/configuration/configResources/DB-Func.php
  www/include/configuration/configServers/DB-Func.php
  www/include/options/accessLists/actionsACL/DB-Func.php
  www/include/options/accessLists/groupsACL/DB-Func.php
  www/include/options/accessLists/resourcesACL/DB-Func.php
  www/include/options/media/images/DB-Func.php
  www/include/reporting/dashboard/DB-Func.php
  www/include/views/componentTemplates/DB-Func.php
  www/include/views/graphTemplates/DB-Func.php
  www/include/views/virtualMetrics/DB-Func.php
Labels: area/database, kind/enhancement

#7536 enh(remote-server): enable https for 18.10.x
  doc/en/administration_guide/poller/enable_remote.rst
  doc/en/administration_guide/poller/install_remote_server_iso.rst
  doc/en/administration_guide/poller/wizard_add_remote.rst
  doc/en/images/poller/wizard_add_remote_2a.png
  doc/en/images/poller/wizard_add_remote_2b.png
  doc/en/installation/architecture/network.rst
  doc/fr/administration_guide/poller/enable_remote.rst
  doc/fr/administration_guide/poller/install_remote_server_iso.rst
  doc/fr/administration_guide/poller/wizard_add_remote.rst
  doc/fr/images/poller/wizard_add_remote_2a.png
  doc/fr/images/poller/wizard_add_remote_2b.png
  doc/fr/installation/architecture/network.rst
  doc/fr/installation/common/install_packages.rst
  doc/fr/installation/common/post_install.rst
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  src/CentreonRemote/Domain/Service/NotifyMasterService.php
  src/CentreonRemote/Domain/Service/TaskService.php
  www/class/centreonRestHttp.class.php
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.ihtml
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/help.php
  www/install/createTables.sql
  www/install/react_translation.php
  www/install/sql/centreon/Update-DB-18.10.4_to_18.10.5.sql
Labels: area/remote-server, kind/enhancement

#7537 enh(remote-server): enable https for 19.04.x/master
  doc/en/administration_guide/poller/enable_remote.rst
  doc/en/administration_guide/poller/install_remote_server_iso.rst
  doc/en/administration_guide/poller/wizard_add_remote.rst
  doc/en/administration_guide/ui_access.rst
  doc/en/images/poller/wizard_add_remote_2a.png
  doc/en/images/poller/wizard_add_remote_2b.png
  doc/en/installation/architecture/network.rst
  doc/fr/administration_guide/poller/enable_remote.rst
  doc/fr/administration_guide/poller/install_remote_server_iso.rst
  doc/fr/administration_guide/poller/wizard_add_remote.rst
  doc/fr/administration_guide/ui_access.rst
  doc/fr/images/poller/wizard_add_remote_2a.png
  doc/fr/images/poller/wizard_add_remote_2b.png
  doc/fr/installation/architecture/network.rst
  doc/fr/installation/common/install_packages.rst
  doc/fr/installation/common/post_install.rst
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  src/CentreonRemote/Domain/Service/NotifyMasterService.php
  src/CentreonRemote/Domain/Service/TaskService.php
  www/class/centreonRestHttp.class.php
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.ihtml
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/help.php
  www/install/createTables.sql
  www/install/react_translation.php
  www/install/sql/centreon/Update-DB-19.04.1.sql
Labels: area/remote-server, kind/enhancement
