Repository centreon/centreon, pull requests merged in 2019-10, with the labels that each got.

#7849 Mon 4046 poller attached to multiple remote servers
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  lib/perl/centreon/script/centcore.pm
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConfigurationRequestBridge.php
  www/api/class/centreon_configuration_poller.class.php
  www/front_src/src/components/breadcrumbWrapper/__snapshots__/index.test.jsx.snap
  www/front_src/src/components/form-fields/hoc.js
  www/front_src/src/components/forms/poller/PollerFormStepTwo.js
  www/front_src/src/components/forms/poller/PollerFormStepTwo.jsx
  www/front_src/src/components/forms/poller/PollerFormStepTwo.test.jsx
  www/front_src/src/components/forms/poller/__snapshots__/PollerFormStepTwo.test.jsx.snap
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepTwo.js
  www/front_src/src/route-components/pollerStep2/index.js
  www/front_src/src/styles/partials/form/_form.scss
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.ihtml
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/help.php
  www/install/createTables.sql
  www/install/react_translation.php
  www/install/sql/centreon/Update-DB-19.10.0-beta.3.sql
Labels: area/remote-server, kind/feature

#7892 Mon 3204 enable session cookie strict mode
  www/class/centreonSession.class.php
  www/include/core/login/login.php
  www/include/core/login/processLogin.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/index.php
Labels: area/security, kind/security

#7893 Mon 3204 enable session cookie strict mode for 2 8 x
  www/class/centreonSession.class.php
  www/include/core/login/login.php
  www/include/core/login/processLogin.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/index.php
Labels: area/security, kind/security

#7884 fix(security): remove command test execution for 2.8.x - CVE 2019-16405
  www/include/configuration/configObject/command/command.php
  www/include/configuration/configObject/command/formCommand.ihtml
  www/include/configuration/configObject/command/formCommand.php
  www/include/configuration/configObject/command/minCommand.ihtml
  www/include/configuration/configObject/command/minCommand.php
  www/include/configuration/configObject/command/minHelpCommand.php
  www/include/configuration/configObject/command/minPlayCommand.ihtml
  www/include/configuration/configObject/command/minPlayCommand.php
Labels: area/configuration, kind/security

#7864 fix(security): remove command test execution - CVE 2019-16405
  www/include/configuration/configObject/command/command.php
  www/include/configuration/configObject/command/formCommand.ihtml
  www/include/configuration/configObject/command/formCommand.php
  www/include/configuration/configObject/command/help.php
  www/include/configuration/configObject/command/minCommand.ihtml
  www/include/configuration/configObject/command/minCommand.php
  www/include/configuration/configObject/command/minHelpCommand.php
  www/include/configuration/configObject/command/minPlayCommand.ihtml
  www/include/configuration/configObject/command/minPlayCommand.php
Labels: area/configuration, kind/security

#7825 Mon 4134 ldap add okta template
  doc/en/administration_guide/parameters.rst
  doc/fr/administration_guide/parameters.rst
  www/include/Administration/parameters/ldap/javascript/ldapJs.php
Labels: area/administration, area/ldap, kind/enhancement

#7896 fix(secu): the ini_set session duration param has been moved in php.ini
  www/api/internal.php
  www/include/core/header/header.php
Labels: inactive/duplicate, kind/enhancement

#7904 enh(doc): update mysql prerequisites for master
  doc/en/installation/prerequisites.rst
  doc/fr/installation/prerequisites.rst
Labels: area/install, kind/documentation

#7897 doc(secu): add php mandatory params info in source installation - latest doc
  doc/en/installation/from_sources.rst
  doc/fr/installation/from_sources.rst
Labels: area/documentation, area/security, kind/documentation, kind/security

#7898 doc(secu): add php mandatory param info for source installation - 19.04
  doc/en/installation/from_sources.rst
  doc/fr/installation/from_sources.rst
Labels: area/documentation, area/security, kind/documentation, kind/security

#7905 fix(install): move SQL update to Centreon 19.10 RC.1
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-19.10.0-beta.3.sql
  www/install/sql/centreon/Update-DB-19.10.0-rc.1.sql
Labels: area/install, kind/bug

#7547 fix(front): do not display round values in detailed top counter
  www/front_src/src/components/hostMenu/index.js
  www/front_src/src/components/serviceStatusMenu/index.js
Labels: area/ux, kind/enhancement

#7811 fix(security): Escape script and input tags by default
  www/class/centreonUtils.class.php
Labels: kind/security

#6985 fix(externalcmd): Create centcore file by action
  www/class/centreonExternalCommand.class.php
Labels: area/monitoring, kind/enhancement

#7883 fix(status details): Fix hide password in command line for 2.8.x (#7414)
  www/include/monitoring/objectDetails/common-func.php
Labels: area/monitoring, kind/bug, kind/security

#7781 Doc correct migration using nagios reader
  doc/en/migration/nagiostocentreon.rst
  doc/fr/migration/nagiostocentreon.rst
Labels: area/install, kind/documentation

#7919 Mon 3204 add rule for max session duration for 18 10
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
  www/install/php/Update-18.10.7_to_18.10.8.php
Labels: area/administration, area/ux

#7922 Mon 4190 issue with multiple rs
  www/class/config-generate-remote/Generate.php
  www/include/configuration/configServers/formServers.php
Labels: area/remote-server, kind/bug

#7918 enh(secu): add rule for max session duration - for master
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
  www/install/php/Update-19.10.0-rc.1.php
  www/install/php/Update-19.10.0-rc.2.php
Labels: area/administration, area/ux

#7913 enh(secu): add rule for max session duration for 19 04
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
  www/install/php/Update-19.04.5.php
Labels: area/administration, area/ux

#7928 fix(remote-server): add missing host poller relation in export
  www/class/config-generate-remote/Abstracts/AbstractHost.php
  www/class/config-generate-remote/Generate.php
  www/class/config-generate-remote/Host.php
  www/class/config-generate-remote/Relations/HostPollerRelation.php
Labels: area/configuration, area/remote-server, kind/bug

#7929 fix(ui): rename contact template titles properly
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
Labels: area/configuration, area/translation, kind/enhancement

#7935 fix(widget): undefined pagination variable when editing custom view
  www/class/centreonWidget.class.php
Labels: kind/enhancement

#7955 fix(downtimes): apply dt on resources linked to a poller
  www/include/monitoring/downtime/AddDowntime.php
Labels: area/monitoring, kind/bug

#7931 Telemetry ceip improvements
  cron/centreon-send-stats.php
  doc/en/ceip.rst
  doc/fr/ceip.rst
  www/install/step_upgrade/step5.php
  www/install/step_upgrade/templates/content.tpl
  www/install/steps/templates/content.tpl
  www/install/steps/templates/step9.tpl
Labels: area/install, kind/enhancement

#7954 fix(doc): Disable SQL strict mode
  doc/en/installation/common/install_packages.rst
  doc/en/installation/common/sql_strict_mode.rst
  doc/en/release_notes/centreon-19.10/centreon-19.10.0-beta.1.rst
  doc/fr/installation/common/install_packages.rst
  doc/fr/installation/common/sql_strict_mode.rst
  doc/fr/release_notes/centreon-19.10/centreon-19.10.0-beta.1.rst
Labels: area/documentation, area/install, kind/bug

#7902 enh(doc): add how to quickly test centreon
  doc/en/installation/index.rst
  doc/fr/installation/index.rst
Labels: area/install, kind/documentation

#7979 enh(doc) remove Centreon 19.10 beta warning
  doc/en/index.rst
  doc/en/release_notes/index.rst
  doc/fr/index.rst
  doc/fr/release_notes/index.rst
Labels: area/documentation

#7997 fix(install/update): replace remane by copy + delete
  www/install/step_upgrade/process/process_step5.php
  www/install/steps/process/process_step9.php
Labels: area/install, kind/bug

#8026 fix(BE): correct the call of checkSession static method
  www/class/centreonSession.class.php
  www/include/core/header/header.php
Labels: kind/bug, kind/enhancement

#8025 fix(BE): correct the call of checkSession static method
  www/class/centreonSession.class.php
  www/include/core/header/header.php
Labels: kind/bug, kind/enhancement

#8027 fix(BE): correct the call of checkSession static method
  www/class/centreonSession.class.php
  www/include/core/header/header.php
Labels: kind/bug, kind/enhancement

#8013 fix(secu): remove unused http parameters in hostXML.php file for PHP5
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/security, kind/security

#8014 fix(secu): protect from SQL injections hostXML.php for 2.8
  www/class/centreonSession.class.php
  www/class/centreonXMLBGRequest.class.php
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/security, kind/security

#8006 fix(secu): protect from SQL injections hostXML.php for 18 10
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/security, kind/security

#8010 fix(secu): remove unused http parameters in hostXML.php file for PHP7
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/security, kind/security

#8030 fix(secu) remove unused params or sanitize them in service by hostgroup
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
Labels: area/security, kind/security

#8038 fix(secu) remove unused params or sanitize them in hostgroups page
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
Labels: area/security, kind/security

#8051 fix(secu): correct sql flaws in common xml.php
  www/include/monitoring/status/Common/xml/modelXML.php
Labels: area/security, kind/security

#8040 fix(secu) remove unused params or sanitize them in service pages
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
Labels: area/security, kind/security

#8044 fix(acl): calculate acl extension all time
  cron/centAcl.php
Labels: area/acl, kind/bug

#8009 fix(ldap): Fix security on LDAP page
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/javascript/ldapJs.php
  www/include/Administration/parameters/ldap/xml/additionalRowXml.php
  www/include/Administration/parameters/ldap/xml/ldap_host.php
  www/include/Administration/parameters/ldap/xsl/additionalRow.xsl
  www/include/Administration/parameters/ldap/xsl/ldap_host.xsl
Labels: area/security, kind/security

#8008 fix(ldap): Fix SQL injection on LDAP page
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/javascript/ldapJs.php
  www/include/Administration/parameters/ldap/xml/additionalRowXml.php
  www/include/Administration/parameters/ldap/xml/ldap_host.php
  www/include/Administration/parameters/ldap/xsl/additionalRow.xsl
  www/include/Administration/parameters/ldap/xsl/ldap_host.xsl
Labels: area/security, kind/security

#8070 enh(perf): set LDAP contactgroup synchronization every hour
  cron/centAcl-Func.php
  cron/centAcl.php
Labels: area/ldap, area/performance, kind/performance

#8052 fix(doc): update FAQ to install RRDCacheD on el7
  doc/en/faq/performance.rst
  doc/en/images/faq/rrdcached_config.png
  doc/fr/faq/performance.rst
  doc/fr/images/faq/rrdcached_config.png
  tmpl/install/redhat/rrdcached.systemd
Labels: area/chart, area/configuration, kind/documentation

#8039 fix(chart): curves in graph not synchronized on display
  www/class/centreonGraph.class.php
  www/class/centreonGraphNg.class.php
  www/class/centreonGraphStatus.class.php
  www/include/Administration/parameters/rrdtool/form.ihtml
Labels: area/chart, kind/bug
