Repository centreon/centreon, pull requests merged in 2019-11, with the labels that each got.

#8068 fix(install): check mariaDB version before using ALTER USER
  www/install/steps/process/createDbUser.php
Labels: area/install, priority/blocker

#8029 fix(secu): Avoid SQL injections in multiple monitoring pages - for 2.8
  www/class/centreonSession.class.php
  www/class/centreonXMLBGRequest.class.php
  www/include/monitoring/status/Common/xml/modelXML.php
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  www/include/monitoring/status/TopCounter/xml/statusCounter.php
Labels: area/security, kind/security

#8088 fix(UI): replace popin z-index
  www/Themes/Centreon-2/style.css
Labels: kind/enhancement

#8087 fix(secu): prevent from sql injections in host page
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/security, kind/security

#8083 fix(secu): prevent from sql injections from common xml model
  www/include/monitoring/status/Common/xml/modelXML.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
Labels: area/security, kind/security

#8082 fix(secu): prevent from sql injections in services pages
  www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  www/include/monitoring/status/Services/xml/makeXMLForOneService.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
Labels: area/security, kind/security

#8094 enh(BE): replace order filter's regexp using whitelist
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
Labels: kind/enhancement

#8077 fix(api): Unable to set host notification to None through the API
  www/class/centreon-clapi/centreonHost.class.php
Labels: area/api, kind/enhancement

#8063 fix(secu): Avoid SQL injections in multiple monitoring pages - for master
  www/include/monitoring/status/Common/xml/modelXML.php
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
  www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  www/include/monitoring/status/Services/xml/makeXMLForOneService.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  www/include/monitoring/status/TopCounter/xml/statusCounter.php
Labels: area/security, kind/security

#8113 fix(ldap): ldap users using the auto-import cannot login - for 19.04
  www/class/centreonAuth.LDAP.class.php
  www/include/Administration/parameters/ldap/form.php
  www/install/php/Update-19.04.5.php
Labels: area/authentication, area/ldap

#8111 fix(ldap): ldap users using the auto-import cannot login - for master
  www/class/centreonAuth.LDAP.class.php
  www/include/Administration/parameters/ldap/form.php
Labels: area/authentication, area/ldap

#8112 fix(ldap): ldap users using the auto-import cannot login - for 19.10
  www/class/centreonAuth.LDAP.class.php
  www/include/Administration/parameters/ldap/form.php
  www/install/php/Update-19.10.2.php
Labels: area/authentication, area/ldap

#8125 fix(sql) add missing column for engine configuration
  www/install/sql/centreon/Update-DB-18.10.7_to_18.10.8.sql
Labels: area/configuration, area/engine, priority/blocker

#8118 Fix traps regression with same oid
  lib/perl/centreon/trapd/lib.pm
Labels: area/monitoring, kind/bug

#8134 fix(filter) fix host name filter history
  www/include/configuration/configObject/host/listHost.ihtml
Labels: area/configuration, kind/bug

#8135 fix(remote-export): hostgroup and servicegroup not exported
  www/class/config-generate-remote/HostGroup.php
  www/class/config-generate-remote/ServiceGroup.php
Labels: area/configuration, kind/bug

#8032 fix(macro): Fix call of host macros list without authentication
  www/class/centreonSession.class.php
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/refreshMacroAjax.php
Labels: area/security, kind/security

#8035 fix(macro): Fix call of service macros list without authentication
  www/class/centreonSession.class.php
  www/include/common/common-Func.php
  www/include/configuration/configObject/service/formService.ihtml
  www/include/configuration/configObject/service/refreshMacroAjax.php
Labels: area/security, kind/security

#8145 fix(api): Fix the API dowtime after the Broker modifications
  doc/API/centreon-api-v2.html
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Infrastructure/Downtime/DowntimeRepositoryRDB.php
Labels: area/api, area/documentation, kind/bug

#8121 fix(ldap): correct double slashes in the saved DN - for 19.04.x
  www/class/centreonAuth.LDAP.class.php
  www/install/php/Update-19.04.5.php
Labels: area/authentication, area/ldap

#8122 fix(ldap): correct double slashes in the saved DN - for master
  www/class/centreonAuth.LDAP.class.php
  www/install/php/Update-19.10.2.php
Labels: area/authentication, area/ldap

#8120 enh(BE): remove ACL notice on lvl3 calculation
  www/class/centreonACL.class.php
Labels: kind/enhancement

#8149 fix(UI): revert popin z-index value from #8088
  www/Themes/Centreon-2/style.css
Labels: area/configuration, area/widgets

#8150 fix(upgrade): move update script to next minor
  www/install/php/Update-19.10.2.php
  www/install/php/Update-19.10.3.php
Labels: area/ldap

#8148 fix(ldap): correct double slashes in the saved DN - for 19.10.x
  www/class/centreonAuth.LDAP.class.php
  www/install/php/Update-19.10.2.php
  www/install/php/Update-19.10.3.php
Labels: area/authentication, area/ldap

#8146 fix(acl): fix calculation of acls on services
  cron/centAcl-Func.php
  cron/centAcl.php
Labels: area/acl, kind/bug

#8153 fix(upgrade): move LDAP fix upgrade script to next minor
  doc/en/release_notes/centreon-19.04/centreon-19.04.6.rst
  doc/fr/release_notes/centreon-19.04/centreon-19.04.6.rst
  www/install/php/Update-19.04.5.php
  www/install/php/Update-19.04.6.php
Labels: area/install, area/ldap

#8141 fix(js) define new error file template
  www/include/home/customViews/layouts/column_0.ihtml
  www/include/home/customViews/views.php
Labels: area/custom-views, kind/security

#8140 feat(broker): add connections_count parameter in form
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/class/centreonConfigCentreonBroker.php
  www/include/common/javascript/centreon/brokerConfig.js
  www/include/configuration/configCentreonBroker/help.php
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.0-beta.1.php
Labels: area/broker, area/configuration, kind/feature

#8143 enh(config): fix performance regression from 19.10.x notification system
  www/class/config-generate/abstract/host.class.php
  www/class/config-generate/abstract/object.class.php
  www/class/config-generate/abstract/service.class.php
  www/class/config-generate/contact.class.php
  www/class/config-generate/contactgroup.class.php
  www/class/config-generate/host.class.php
  www/class/config-generate/hosttemplate.class.php
  www/class/config-generate/service.class.php
  www/class/config-generate/servicetemplate.class.php
  www/include/monitoring/common-Func.php
Labels: area/configuration, kind/enhancement

#8147 fix(remote-server): Host and service templates not properly imported
  src/CentreonRemote/Domain/Exporter/ConfigurationExporter.php
Labels: area/configuration, area/remote-server, kind/bug

#8161 fix(widget): fix double quote in widget title
  www/class/centreonWidget.class.php
Labels: area/custom-views, kind/bug
