Repository centreon/centreon, pull requests merged in 2019-01, with the labels that each got.

#7047 Normalize names of lang directories
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/install, area/translation

#7043 fix(conf): protect hostname resolver from XSS
  www/include/configuration/configObject/host/listHost.ihtml
  www/include/configuration/configObject/host/resolveHostName.php
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/configuration, kind/bug, kind/security

#7072 MON-3298 enhance utf-8 check
  www/class/centreonXML.class.php
Labels: area/configuration, kind/enhancement
