Repository centreon/centreon, pull requests merged in 2019-06, with the labels that each got.

#7579 fix(CI): correct coding style and psr2
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Domain/Service/TaskService.php
  www/class/centreonRestHttp.class.php
  www/include/configuration/configServers/help.php
Labels: build/jenkins

#7573 fix(base): change license identifier with a valid SPDX license identifier
  composer.json
Labels: kind/bug

#7575 fix(base): change license identifier with a valid SPDX license identi…
  composer.json
Labels: kind/bug

#7574 fix(base): change license identifier with a valid SPDX license identi…
  composer.json
Labels: kind/bug

#7582 fix(front): expose properly react router dom
  www/front_src/src/index.js
Labels: kind/bug

#7434 fix(update): re execute missing PHP update from 2.8.27
  www/install/php/Update-18.10.5_to_18.10.6.php
Labels: area/install, kind/bug

#7591 fix(engine): add possibility to save service_interleave_factor
  www/include/configuration/configNagios/DB-Func.php
Labels: area/configuration, area/engine, kind/bug

#7636 enh(about): update Centreon developers list
  www/include/Administration/about/about.php
Labels: area/install

#7624 fix(url) use variables with urlencode
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
Labels: area/monitoring, kind/bug

#7607 Mon 3864 event log export
  www/include/eventLogs/viewLog.php
Labels: area/monitoring, kind/bug

#7623 fix(sql) fix strict mode
  composer.lock
  www/class/centreonTraps.class.php
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-19.10.0.sql
Labels: build/jenkins

#7610 enh(traps): increase trap special command field size
  bin/generateSqlLite
  doc/en/release_notes/centreon-18.10/centreon-18.10.6.rst
  doc/fr/release_notes/centreon-18.10/centreon-18.10.6.rst
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-18.10.5_to_18.10.6.sql
Labels: area/configuration, kind/enhancement

#7641 fix(widget) fix preference
  www/class/centreonCustomView.class.php
  www/class/centreonWidget.class.php
Labels: area/widgets
