Repository centreon/centreon, pull requests merged in 2019-03, with the labels that each got.

#7239 Doc improve install chapters
  doc/en/installation/common/post_install.rst
  doc/fr/installation/common/post_install.rst
  doc/fr/quick_start/index.rst
Labels: kind/documentation, kind/enhancement

#7202 fix(front): manage properly session expiration + avoid login inception
  www/front_src/src/App.js
  www/front_src/src/route-components/module/index.js
  www/include/core/header/header.php
  www/include/core/login/template/login.ihtml
Labels: area/administration, kind/bug

#7196 API for commands arguments descriptions
  doc/en/api/clapi/objects/commands.rst
  doc/fr/api/clapi/objects/commands.rst
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonCommand.class.php
Labels: area/api, kind/enhancement

#7199 Add showinstance CLAPI command to Host
  doc/en/api/clapi/objects/hosts.rst
  doc/fr/api/clapi/objects/hosts.rst
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonHost.class.php
Labels: area/api, kind/enhancement

#6509 MON-3518-filter-correction-recurrent-downtime-form
  www/class/centreonDowntime.class.php
Labels: area/monitoring, kind/bug, status/in-backlog

#7244 Doc improce prerequisites
  doc/en/files/Centreon_platform_sizing.xlsx
  doc/en/installation/prerequisites.rst
  doc/fr/files/Centreon_platform_sizing.xlsx
  doc/fr/installation/prerequisites.rst
Labels: area/install, kind/documentation, kind/enhancement

#7249 Add missing release notes (2.8.26 & 2.8.27)
  doc/en/release_notes/centreon-2.8/centreon-2.8.26.rst
  doc/en/release_notes/centreon-2.8/centreon-2.8.27.rst
  doc/en/release_notes/centreon-2.8/index.rst
  doc/fr/release_notes/centreon-2.8/centreon-2.8.26.rst
  doc/fr/release_notes/centreon-2.8/centreon-2.8.27.rst
  doc/fr/release_notes/centreon-2.8/index.rst
Labels: area/install, kind/documentation

#7116 enh(doc): improve poller configuration
  doc/en/administration_guide/poller/wizard_add_poller.rst
  doc/fr/administration_guide/poller/wizard_add_poller.rst
Labels: area/broker, area/configuration, kind/documentation, kind/enhancement

#7048 Improve doc traps snmp
  doc/en/configuration_guide/advanced_configuration/traps.rst
  doc/en/images/user/configuration/10advanced_configuration/06importmibs.png
  doc/en/images/user/configuration/10advanced_configuration/SNMP_Traps_management_general_view.png
  doc/fr/configuration_guide/advanced_configuration/traps.rst
  doc/fr/images/guide_utilisateur/configuration/10advanced_configuration/SNMP_Traps_management_general_view.png
Labels: area/configuration, kind/documentation

#7027 fix(doc): enable services after remote server installation
  doc/en/administration_guide/poller/enable_services.rst
  doc/en/administration_guide/poller/install_remote_server_iso.rst
  doc/en/administration_guide/poller/install_remote_server_packages.rst
  doc/fr/administration_guide/poller/enable_services.rst
  doc/fr/administration_guide/poller/install_remote_server_iso.rst
  doc/fr/administration_guide/poller/install_remote_server_packages.rst
Labels: area/remote-server, kind/documentation

#6934 fix(doc) Update upgradetoCentreon18.10.rst
  doc/en/migration/upgradetoCentreon18.10.rst
  doc/fr/migration/upgradetoCentreon18.10.rst
Labels: kind/documentation

#7203 enh(doc): describe directory of XML files for partitioning
  doc/en/administration_guide/partitioning/user/configuration.rst
  doc/fr/administration_guide/partitioning/user/configuration.rst
Labels: kind/documentation, kind/enhancement

#7251 enh(ui) : indent third level menu
  www/front_src/src/styles/partials/_side-nav.scss
Labels: area/ux

#7201 enh(DT): fix search filter for recurrent downtimes
  www/Themes/Centreon-2/style.css
  www/class/centreonDowntime.class.php
  www/include/monitoring/recurrentDowntime/listDowntime.php
Labels: area/monitoring, kind/enhancement

#7160 Mon 3112 fix source install
  composer.json
  doc/en/installation/from_sources.rst
  doc/fr/installation/from_sources.rst
  install.sh
  libinstall/CentCore.sh
  libinstall/CentPlugins.sh
  libinstall/CentPluginsTraps.sh
  libinstall/CentStorage.sh
  libinstall/CentWeb.sh
  libinstall/functions
  tmpl/vardistrib/centos-7
  tmpl/vardistrib/defaults
  varinstall/vars
Labels: build/jenkins

#7261 Fix wording related to downtimes
  doc/en/exploitation_guide/04realtime.rst
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/monitoring/downtime/listDowntime.php
Labels: kind/documentation, kind/enhancement

#7262 refacto(webservice): refacto top counter webservice
  www/api/class/centreon_topcounter.class.php
Labels: area/api, kind/enhancement

#7266 enh(doc): Add FAQ for known issues about Remote Server
  doc/en/faq/index.rst
  doc/en/faq/remote_server.rst
  doc/fr/faq/index.rst
  doc/fr/faq/remote_server.rst
Labels: area/remote-server, kind/documentation, kind/enhancement

#7084 fix(secu): Type juggling can lead to authentication bypass in (very) …
  www/class/centreonAuth.class.php
Labels: area/authentication, kind/security

#7258 enh(ui) : tooltip in folded menu hover ok
  www/front_src/src/App.js
  www/front_src/src/components/navigation/index.js
  www/front_src/src/components/tooltip/index.js
  www/front_src/src/redux/actions/tooltipActions.js
  www/front_src/src/redux/reducers/index.js
  www/front_src/src/redux/reducers/tooltipReducer.js
  www/front_src/src/styles/_main.scss
  www/front_src/src/styles/partials/_tooltip.scss
Labels: area/ux, kind/enhancement

#7290 Fix rest acceptance 18.10
  tests/rest_api/rest_api.postman_collection.json
Labels: build/jenkins

#7284 fix(doc): add enable systemctl for centreon
  doc/en/installation/common/install_packages.rst
  doc/en/installation/common/post_install.rst
  doc/fr/installation/common/install_packages.rst
  doc/fr/installation/common/post_install.rst
Labels: area/documentation, kind/bug

#7274 enh(doc): Doc improve partitioning
  doc/en/administration_guide/index.rst
  doc/en/administration_guide/partitioning.rst
  doc/en/administration_guide/partitioning/index.rst
  doc/en/administration_guide/partitioning/user/configuration.rst
  doc/en/administration_guide/partitioning/user/exploitation.rst
  doc/en/administration_guide/partitioning/user/index.rst
  doc/en/administration_guide/partitioning/user/monitoring.rst
  doc/en/images/guide_exploitation/Global-DB-Information.png
  doc/en/images/guide_exploitation/partitioning-state.png
  doc/en/images/guide_exploitation/partitioning_conf.png
  doc/fr/administration_guide/index.rst
  doc/fr/administration_guide/partitioning.rst
  doc/fr/administration_guide/partitioning/index.rst
  doc/fr/administration_guide/partitioning/user/configuration.rst
  doc/fr/administration_guide/partitioning/user/exploitation.rst
  doc/fr/administration_guide/partitioning/user/index.rst
  doc/fr/administration_guide/partitioning/user/monitoring.rst
  doc/fr/images/guide_exploitation/Global-DB-Information.png
  doc/fr/images/guide_exploitation/partitioning-state.png
  doc/fr/images/guide_exploitation/partitioning_conf.png
Labels: area/administration, area/partitioning, kind/documentation, kind/enhancement

#7276 enh(doc): describe how to enable user audit log in doc
  doc/en/administration_guide/logs.rst
  doc/en/images/guide_exploitation/fobjectmodif.png
  doc/en/images/guide_exploitation/logs_audit_enable.png
  doc/fr/administration_guide/logs.rst
  doc/fr/images/guide_exploitation/fobjectmodif.png
  doc/fr/images/guide_exploitation/logs_audit_enable.png
Labels: area/administration, kind/documentation, kind/enhancement

#7287 enh(doc): add missing documentation about PR #7206
  doc/en/administration_guide/parameters.rst
  doc/en/images/guide_exploitation/ecentcore.png
  doc/fr/administration_guide/parameters.rst
  doc/fr/images/guide_exploitation/ecentcore.png
Labels: kind/documentation, kind/enhancement

#7269 enh(doc): Add EN & FR chapters for data retention
  doc/en/administration_guide/data_retention.rst
  doc/en/administration_guide/index.rst
  doc/en/images/guide_exploitation/data_retention.png
  doc/fr/administration_guide/data_retention.rst
  doc/fr/administration_guide/index.rst
  doc/fr/images/guide_exploitation/data_retention.png
  www/include/Administration/parameters/centstorage/help.php
Labels: area/administration, kind/documentation, kind/enhancement

#7301 fix(doc): add missing part of PR #7284
  doc/en/administration_guide/poller/enable_services.rst
  doc/fr/administration_guide/poller/enable_services.rst
Labels: kind/documentation

#7247 7228 delete non existing topology_JS entries from install
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-18.10.3_to_18.10.4.sql
  www/install/sql/centreon/Update-DB-18.10.4_to_18.10.5.sql
Labels: area/install, kind/bug

#7278 fix(ldap): sql errors in the log on authentication
  www/class/centreonAuth.LDAP.class.php
  www/class/centreonAuth.class.php
  www/class/centreonContactgroup.class.php
  www/class/centreonLDAP.class.php
  www/include/configuration/configGenerate/xml/generateFiles.php
Labels: kind/bug, kind/enhancement

#7294 Mon 3522 remove excess menu levels
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-19.04.0.sql
Labels: area/ux, kind/enhancement

#7295 enh(UI) Color the open level 2 and 3 menus
  www/front_src/src/styles/partials/_side-nav.scss
Labels: area/ux, kind/enhancement

#7226 fix(security): fix vulnerability for file loading
  www/include/Administration/brokerPerformance/brokerPerformance.php
Labels: kind/security

#7250 feat(remote-server): allow usage of domain names
  src/Centreon/Domain/Repository/InformationsRepository.php
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
  src/CentreonRemote/Application/Validator/WizardConfigurationRequestValidator.php
  src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php
  src/CentreonRemote/Domain/Service/NotifyMasterService.php
  www/front_src/src/helpers/validators.js
Labels: area/remote-server, kind/enhancement

#7275 fix(secu): sql injections in the service by hostgroups and servicegroups pages
  www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php
  www/include/monitoring/status/ServicesHostGroups/serviceSummaryByHG.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
Labels: kind/security

#7267 fix(secu): sql injections in the service by hostgroups and servicegroups pages
  www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php
  www/include/monitoring/status/ServicesHostGroups/serviceGridByHGJS.php
  www/include/monitoring/status/ServicesHostGroups/templates/serviceGrid.ihtml
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
Labels: kind/bug, kind/enhancement, kind/security
