Repository centreon/centreon, pull requests merged in 2019-07, with the labels that each got.

#7650 fix(centcore): do not overwrite commands
  lib/perl/centreon/script/centcore.pm
Labels: area/remote-server, kind/bug

#7633 fix(remote-server): update only properties of selected poller
  www/include/configuration/configServers/DB-Func.php
Labels: area/remote-server, kind/bug, priority/major

#7638 fix(remote-server): do not compare bugfix version on task import
  src/CentreonRemote/Infrastructure/Export/ExportManifest.php
Labels: area/remote-server, kind/bug

#7637 fix(remote-server): store FQDN
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-19.10.0.sql
Labels: area/remote-server, kind/bug

#7584 enh(ui): improve mail bin help tooltip
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  www/include/Administration/parameters/engine/help.php
Labels: area/administration, area/ux

#7592 add centreontrapd @HOSTID@ macro
  lib/perl/centreon/script/centreontrapd.pm
Labels: area/monitoring, kind/enhancement, status/in-backlog

#7634 fix(remote-server): set task in failed status if an error appears
  src/Centreon/Domain/Entity/Task.php
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
Labels: area/remote-server, kind/bug, priority/major

#7679 Mon 3509 add trap regexp match 2
  bin/generateSqlLite
  doc/en/configuration_guide/advanced_configuration/traps.rst
  doc/en/configuration_guide/process_description/managetraps.rst
  doc/fr/configuration_guide/advanced_configuration/traps.rst
  doc/fr/configuration_guide/process_description/managetraps.rst
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lib/perl/centreon/script/centreontrapd.pm
  lib/perl/centreon/trapd/lib.pm
  tests/clapi_export/clapi-configuration.txt
  www/class/centreonTraps.class.php
  www/include/configuration/configObject/traps/formTraps.ihtml
  www/include/configuration/configObject/traps/formTraps.php
  www/include/configuration/configObject/traps/help.php
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-19.04.0.sql
Labels: area/monitoring, kind/enhancement

#7613 MON-3381 #comment adding cursor pointer to icons
  www/Themes/Centreon-2/style.css
Labels: area/chart, area/ux

#7694 add escapeshellarg to nagios_bin binary passed to shell_exec
  www/include/configuration/configGenerate/xml/generateFiles.php
Labels: kind/security, status/in-backlog

#7695 fix(remote-server): filter output to master on NEB category only
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputForwardMaster.php
Labels: area/configuration, area/remote-server, kind/bug, priority/major

#7678 enh(api): update output of getparam command on host object
  doc/en/api/api_rest/index.rst
  doc/en/api/clapi/objects/hosts.rst
  doc/fr/api/api_rest/index.rst
  doc/fr/api/clapi/objects/hosts.rst
  www/class/centreon-clapi/centreonHost.class.php
Labels: area/api, kind/enhancement

#7577 Change backup path for httpd24-httpd
  cron/centreon-backup.pl
Labels: area/backup, kind/enhancement, status/in-backlog

#7526 Update documentation to support 19.04 version (httpd24 mainly)
  doc/en/installation/from_sources.rst
  doc/fr/installation/from_sources.rst
Labels: kind/documentation, kind/enhancement, status/in-backlog

#7677 Mon 3936 use correct ssh port
  lib/perl/centreon/script/centcore.pm
  lib/perl/centreon/script/centreonSyncArchives.pm
  lib/perl/centreon/script/centreonSyncPlugins.pm
Labels: area/configuration, kind/enhancement

#7617 Move filesGeneration directory to /var/cache/centreon
  filesGeneration/export/.keep
  libinstall/CentWeb.sh
  libinstall/functions
  tmpl/vardistrib/defaults
  varinstall/vars
  www/include/options/media/images/DB-Func.php
Labels: area/install, kind/enhancement

#7640 fix(remote-server): check bam on remote server is http only
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Domain/Value/ServerWizardIdentity.php
Labels: area/remote-server, kind/bug

#7658 Update Host.rst FR
  doc/fr/api/clapi/objects/hosts.rst
Labels: kind/documentation, kind/enhancement

#7639 fix(doc): correct SSH exchange notice #7620
  doc/en/administration_guide/poller/ssh_key.rst
  doc/en/installation/from_VM.rst
  doc/fr/administration_guide/poller/ssh_key.rst
  doc/fr/installation/from_VM.rst
Labels: area/documentation, kind/bug

#7711 fix(remote): fix enableremote parameters parsing and setting
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
Labels: area/api, area/remote-server, kind/bug, status/in-backlog

#7676 Mon 3477 improve chart performance
  www/Themes/Centreon-2/style.css
  www/api/class/centreon_metric.class.php
  www/class/centreonGraph.class.php
  www/class/centreonGraphNg.class.php
  www/class/centreonGraphPoller.class.php
  www/class/centreonGraphService.class.php
  www/class/centreonGraphStatus.class.php
  www/include/common/javascript/jquery/jquery.cookie.js
  www/include/common/javascript/jquery/tourbus/jquery-tourbus.min.css
  www/include/common/javascript/jquery/tourbus/jquery-tourbus.min.js
  www/include/views/componentTemplates/DB-Func.php
  www/include/views/graphs/common/makeJS_formMetricsList.php
  www/include/views/graphs/exportData/ExportXMLServiceData.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/include/views/graphs/generateGraphs/generateMetricImage.php
  www/include/views/graphs/graph-periods.php
  www/include/views/graphs/graph-split.html
  www/include/views/graphs/graphStatus/displayServiceStatus.php
  www/include/views/graphs/graphs.html
  www/include/views/graphs/graphs.php
  www/include/views/graphs/javascript/centreon-graph.js
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-19.10.0.sql
Labels: area/chart, kind/enhancement, kind/performance

#7664 Fix creating user with admin rights
  www/include/configuration/configObject/contact/formContact.php
Labels: kind/security, status/in-backlog
