Repository centreon/centreon, pull requests merged in 2019-09, with the labels that each got.

#7687 fix(front): redirect to login page when user is unauthorized
  www/front_src/src/translations/index.js
Labels: area/ux, kind/bug

#7819 enh(dropdowns): style default select to be as much like select2 as possible
  www/Themes/Centreon-2/style.css
Labels: area/ux

#7842 enh(api): improve performance of clapi call through REST API
  www/api/class/centreon_clapi.class.php
Labels: area/api, kind/bug

#7751 refactor(core): centAcl optimize memory and time execution
  cron/centAcl-Func.php
  cron/centAcl.php
Labels: area/acl, kind/performance

#7712 enh(remote-server): improve centreonworker logging
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
Labels: area/remote-server, kind/enhancement, status/in-backlog

#7764 match metric name with metric value #5959 #7477
  www/include/views/graphs/exportData/ExportCSVServiceData.php
Labels: area/chart, kind/bug, priority/minor, status/in-backlog

#7791 core(rrd) move global rrd cache option
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreonConfigCentreonBroker.php
  www/class/config-generate/broker.class.php
  www/include/Administration/parameters/rrdtool/form.ihtml
  www/include/Administration/parameters/rrdtool/form.php
  www/include/common/javascript/centreon/brokerConfig.js
  www/install/insertBaseConf.sql
  www/install/php/Update-19.10.0-beta.3.php
  www/install/sql/centreon/Update-DB-19.10.0-beta.3.sql
Labels: area/chart, area/configuration, kind/enhancement

#7340 fix(ui): do not display autologin shortcut when disabled
  www/api/class/centreon_topcounter.class.php
  www/front_src/src/components/userMenu/index.js
Labels: area/acl, kind/bug, status/in-backlog

#7877 fix(secu): escape persistent and reflected XSS in my account - for 18.10.x
  www/class/centreonUtils.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/listContact.php
Labels: kind/security

#7876 fix(secu): escape persistent and reflected XSS in my account - for 2.8.x
  www/class/centreonUtils.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/listContact.php
Labels: kind/security

#7865 fix(sec): remove xss injection of service output in host form
  www/include/monitoring/objectDetails/hostDetails.php
Labels: kind/security

#7880 fix(security): sanitize host_id and service_id - 2.8.x
  www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  www/include/monitoring/status/Services/xml/makeXMLForOneService.php
Labels: kind/security

#7862 fix(security): sanitize host_id and service_id
  www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  www/include/monitoring/status/Services/xml/makeXMLForOneService.php
Labels: kind/security
