Repository centreon/centreon, pull requests merged in 2020-06, with the labels that each got.

#8755 feat(ui): Add Downtime and Acknowledge comments in Events view details panel
  www/front_src/src/Resources/Details/Body/tabs/Details/StateCard.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
Labels: area/ui

#8749 fix(ui): Prevent disabled actions resulting from limited ACL to be clickable
  www/front_src/src/Resources/ActionButton.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
Labels: area/ui

#8759 Remove initial state for AjaxTimeReloadMonitoring
  www/front_src/src/redux/reducers/refreshReducer.js
Labels: area/ui

#8761 fix(ui): Fix lower value display of Event view performance graph
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
Labels: area/ui

#8756 fix(sec): set Access-Control-Allow-Credentials response header to false
  config/packages/nelmio_cors.yaml
Labels: area/api, area/backend, area/security

#8762 enh(api): update iconNormalizer to make it generic
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Normalizer/IconUrlNormalizer.php
Labels: area/api, area/backend

#8766 fix(api): fix acl on endpoints to find acks and downtimes
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Security/ContactBySession.php
  src/Security/SessionAPIAuthenticator.php
Labels: area/api, area/backend

#8770 fix(backup): keep mount option only for xfs partition type
  cron/centreon-backup-mysql.sh
Labels: area/backend, area/backup, pr/internal-rd, priority/critical

#8767 fix(trap): remove default value when options configured
  lib/perl/centreon/script/centreon_trap_send.pm
Labels: area/backend, pr/internal-ps, status/needs-attention

#8779 fix(acl): fix acl on ack and downtime using APIv2
  config/packages/validator/validation.yaml
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Monitoring/Resource.php
Labels: area/backend

#8780 fix(ui): disable service checkbox when not allowed
  package-lock.json
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/index.test.tsx
Labels: area/acl, area/ui

#8776 fix(reporting): fix host availability related to broker changes
  lib/perl/centreon/reporting/CentreonLog.pm
  www/include/eventLogs/xml/data.php
Labels: area/backend, area/reporting

#8775 fix(reporting): fix reporting issues related to downtime cancellation
  lib/perl/centreon/reporting/CentreonDownTime.pm
Labels: area/backend, area/reporting

#8782 fix(security): remove dead code
  www/include/views/graphs/exportData/ExportXMLServiceData.php
Labels: area/backend

#8784 fix(api): fix acknowledgement validation group
  config/packages/validator/validation.yaml
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Domain/Monitoring/Resource.php
Labels: area/backend

#8772 fix(security) gorgone popup check session and id
  www/include/configuration/configServers/popup/popup.php
Labels: area/backend, area/security

#8763 fix(security) sanitize host geo coords
  features/bootstrap/HostConfigurationContext.php
  features/bootstrap/HostGroupConfigurationContext.php
  features/bootstrap/HostGroupServiceConfigurationContext.php
  features/bootstrap/MassiveChangeHostsContext.php
  features/bootstrap/MassiveChangeServicesContext.php
  features/bootstrap/MetaServiceConfigurationContext.php
  features/bootstrap/ServiceConfigurationContext.php
  features/bootstrap/ServiceGroupConfigurationContext.php
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonHostGroup.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/class/centreon-clapi/centreonServiceGroup.class.php
  www/class/centreon-clapi/centreonUtils.class.php
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/hostgroup/formHostGroup.php
  www/include/configuration/configObject/meta_service/formMetaService.php
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/servicegroup/formServiceGroup.php
Labels: area/backend

#8758 fix(security) fix sql injection on getServiceXML
  www/include/common/javascript/centreon/serviceFilterByHost.js
  www/include/configuration/configObject/host_dependency/formHostDependency.php
  www/include/configuration/configObject/service_dependency/formServiceDependency.php
  www/include/configuration/configObject/service_dependency/getServiceXml.php
  www/include/configuration/configObject/servicegroup/formServiceGroup.php
  www/include/configuration/configObject/servicegroup/getServiceXml.php
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-20.04.4.sql
Labels: area/backend

#8783 fix(config): change check_meta_host_alive command line to use dummy check
  www/class/config-generate/meta_command.class.php
Labels: area/configuration, kind/fix, priority/major, status/needs-attention

#8787 fix(secu): secure graph template page
  www/include/views/graphTemplates/DB-Func.php
  www/include/views/graphTemplates/formGraphTemplate.php
  www/include/views/graphTemplates/graphTemplates.php
Labels: area/backend, area/security

#8752 fix(secu): avoid privilege escalation on DB backup script
  cron/centreon-backup-mysql.sh
  cron/centreon-backup.pl
Labels: area/backend, area/backup

#8757 fix(security) fix sql injection on loadServiceFromHost
  www/include/home/customViews/triggers/loadServiceFromHost.php
Labels: area/backend

#8792 fix(test): Increase jest timeout to 10000
  setupTest.js
Labels: area/ui

#8790 fix(secu): sanitize service grid history inputs
  www/include/monitoring/status/Common/setHistory.php
Labels: area/backend, area/monitoring

#8789 fix(proxy): Fix bad serialization of proxy
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Proxy/Proxy.php
  tests/php/Centreon/Domain/Proxy/ProxyTest.php
Labels: area/api, area/backend

#8796 fix(geocoords) fix geo coords regex
  www/class/centreon-clapi/centreonUtils.class.php
  www/include/common/common-Func.php
Labels: area/backend

#8794 fix(api): acknowledge more than 10 first services
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringRepositoryInterface.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/api, area/backend

#8424 enh(web): centreon compatibility with http2
  www/include/common/javascript/xslt.js
Labels: area/performance, kind/beta-test, kind/enhancement, pr/external, status/in-backlog, status/needs-attention

#8795 feat(api): add endpoint to list configuration icons
  config/Modules/Centreon.yaml
  config/packages/serializer/Centreon/Configuration.Icon.Icon.yml
  config/routes/Centreon/configuration/icon.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/Configuration/IconController.php
  src/Centreon/Application/Normalizer/IconUrlNormalizer.php
  src/Centreon/Domain/Configuration/Icon/Icon.php
  src/Centreon/Domain/Configuration/Icon/IconService.php
  src/Centreon/Domain/Configuration/Icon/Interfaces/IconRepositoryInterface.php
  src/Centreon/Domain/Configuration/Icon/Interfaces/IconServiceInterface.php
  src/Centreon/Infrastructure/Icon/IconRepositoryRDB.php
Labels: area/api, area/backend

#8804 fix(ExportCSVServiceData): wrong variable name used during export
  www/include/views/graphs/exportData/ExportCSVServiceData.php
Labels: area/backend

#8798 fix(security) admin access
  www/include/configuration/configServers/popup/popup.php
Labels: area/backend

#8802 security(CustomView): add access rights to CustomViews actions
  www/class/centreonCustomView.class.php
  www/class/centreonWidget.class.php
  www/include/home/customViews/action.php
Labels: area/backend, area/security

#8803 fix(secu): secure host and service sendCommand actions
  www/class/centreonHost.class.php
  www/class/centreonService.class.php
  www/include/monitoring/objectDetails/xml/hostSendCommand.php
  www/include/monitoring/objectDetails/xml/serviceSendCommand.php
Labels: area/backend, area/security

#8793 test(api): add structure to test api endpoints
  Jenkinsfile
  composer.json
  composer.lock
  symfony.lock
  tests/api/Context/HostMonitoringContext.php
  tests/api/Context/ResourceMonitoringContext.php
  tests/api/Context/ServiceMonitoringContext.php
  tests/api/behat.yml
  tests/api/features/HostMonitoring.feature
  tests/api/features/ResourceMonitoring.feature
  tests/api/features/ServiceMonitoring.feature
Labels: area/api, area/backend

#8806 enh(chore): update gitignore
  .gitignore
Labels: area/backend

#8808 fix(chore): correct wrong encoding on UTF-8 characters
  www/include/common/common-Func.php
  www/include/common/javascript/color_picker.html
  www/include/common/javascript/color_picker.php
  www/include/common/javascript/color_picker_mb.js
  www/include/common/javascript/colpick.html
  www/include/common/javascript/functions.js
Labels: area/backend

#8811 fix(icon): change ppm folder creation rights
  www/class/centreonMedia.class.php
Labels: area/backend, kind/fix, pr/internal-rd

#8812 fix(chore): correct rights of already created icon folder
  www/class/centreonMedia.class.php
Labels: area/backend, area/install, area/monitoring, area/plugin-packs

#8807 fix(reporting): fix reporting calculation when downtime end time is null
  lib/perl/centreon/reporting/CentreonDownTime.pm
Labels: area/backend, area/reporting

#8810 fix(centreonCustomView): use class constant correctly
  www/class/centreonCustomView.class.php
Labels: area/backend

#8817 fix(sendCommand): centreonUtils class was not loaded
  www/include/monitoring/objectDetails/xml/hostSendCommand.php
  www/include/monitoring/objectDetails/xml/serviceSendCommand.php
Labels: area/backend

#8819 fix(formGraphTemplate): bad variable name used
  www/include/views/graphTemplates/formGraphTemplate.php
Labels: area/backend
