Repository centreon/centreon, pull requests merged in 2020-03, with the labels that each got.

#8382 feat(ui): Implement Unified view search
  tsconfig.json
  www/front_src/src/Resources/SearchHelpTooltip.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/searchObjects.ts
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8386 fix(lint): Fix ESLint warnings (frontend)
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/header/index.js
  www/front_src/src/helpers/dynamicImport.js
Labels: area/ui

#8376 doc(api): document how to use search parameter with API
  doc/API/centreon-api-v2.html
  doc/API/centreon-api-v2.yaml
Labels: area/api, kind/documentation, pr/internal-rd, status/needs-attention

#8390 fix(configuration): export hosts geo_coords to remote server
  www/class/config-generate-remote/Abstracts/AbstractHost.php
Labels: area/configuration, kind/fix, pr/internal-rd

#8287 fix(ldap): use define user member_attribute var
  www/class/centreonLDAP.class.php
Labels: area/ldap, kind/fix, pr/internal-rd, status/needs-merge

#8385 feat(ui): Implement Unified view downtime and acknowledge tooltips
  jest.config.js
  package-lock.json
  package.json
  setupTest.js
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/columns/icons/__mocks__/Downtime.tsx
  www/front_src/src/Resources/columns/icons/downtime.icon.svg
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/Resources/useCancelTokenSource.ts
Labels: area/ui, kind/feature, pr/internal-rd

#8285 fix(code): Clean switch case service monitoring
  www/include/monitoring/status/monitoringService.php
Labels: area/monitoring, kind/enhancement, pr/internal-rd, status/needs-merge

#7944 fix(remote-server): fix import with strict mode
  src/CentreonRemote/Domain/Exporter/ConfigurationExporter.php
Labels: area/remote-server, kind/fix, pr/internal-rd, status/needs-attention

#8394 doc(api): document how to generate html api documentation
  .gitignore
  doc/API/README.MD
  doc/API/centreon-api-v2.html
Labels: area/api, kind/documentation, kind/enhancement, pr/internal-rd

#8393 feat(doc): update the API documentation
  doc/API/centreon-api-v2.html
  doc/API/centreon-api-v2.yaml
Labels: area/api, kind/documentation, pr/internal-rd

#8189 fix(topcounter): use session cache to store top counter hosts/services results
  www/api/class/centreon_topcounter.class.php
  www/class/centreon.class.php
  www/class/centreonCache.class.php
  www/class/centreonGMT.class.php
  www/class/centreonSession.class.php
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/core/header/header.php
  www/include/views/graphs/graphStatus/displayServiceStatus.php
Labels: area/performance, kind/enhancement, pr/internal-ps, status/needs-attention

#8321 enh(config): prepare anomalydetection module
  www/class/config-generate/service.class.php
Labels: area/configuration, kind/feature, pr/internal-rd

#8396 fix(core): source install
  install.sh
  libinstall/CentWeb.sh
  libinstall/functions
  varinstall/vars
Labels: area/install, pr/internal-rd

#8388 feat(api): Be able to search based on current standard parameters
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  config/routes/dev/profiler/twig.yaml
  config/routes/dev/profiler/web_profiler.yaml
  doc/API/centreon-api-v2.html
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/Interfaces/ResourceRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
Labels: area/api, kind/feature, pr/internal-rd

#8387 feat(api): allow to bulk external commands
  config/Modules/Centreon.yaml
  config/json_validator/default/Downtimes.yaml
  config/packages/serializer/Centreon/Acknowledgement.Acknowledgement.yml
  config/packages/serializer/Centreon/Check.Check.yml
  config/packages/serializer/Centreon/Check.Checks.yml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  config/packages/serializer/Centreon/Monitoring.ResourceId.yml
  config/packages/validator/validation.yaml
  config/routes/Centreon/acknowledgement.yaml
  config/routes/Centreon/check.yaml
  config/routes/Centreon/downtime.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/CheckController.php
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Acknowledgement/Acknowledgement.php
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
  src/Centreon/Domain/Check/Check.php
  src/Centreon/Domain/Check/CheckService.php
  src/Centreon/Domain/Downtime/Downtime.php
  src/Centreon/Domain/Downtime/DowntimeService.php
  src/Centreon/Domain/Downtime/Interfaces/DowntimeServiceInterface.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineServiceInterface.php
  src/Centreon/Domain/Entity/EntityValidator.php
  src/Centreon/Domain/Monitoring/ResourceId.php
  src/Centreon/Domain/Service/JsonValidator/Validator.php
  src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
  src/Centreon/Infrastructure/Engine/EngineRepositoryFile.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  tests/php/Centreon/Domain/Acknowledgement/AcknowledgementServiceTest.php
  tests/php/Centreon/Domain/Check/CheckServiceTest.php
  www/front_src/src/__mocks__/axios.ts
Labels: area/api, kind/feature, pr/internal-rd

#8397 feat(ci): integrate phpstan to jenkins
  .gitignore
  Jenkinsfile
  build.xml
  composer.json
  composer.lock
  phpstan.neon
  ruleset.xml
  src/Centreon/Application/Webservice/OpenApiWebservice.php
  src/Centreon/Domain/Repository/TopologyRepository.php
  src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
  src/Centreon/Infrastructure/Provider/AutoloadServiceProvider.php
  src/Centreon/ServiceProvider.php
  www/class/centreonDB.class.php
  www/class/centreonExternalCommand.class.php
  www/class/centreonGraphNg.class.php
  www/class/centreonHost.class.php
  www/class/centreonService.class.php
Labels: area/tests, build/jenkins, pr/internal-rd

#8401 enh(admin): page titles, fields name, translations and help
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/gorgone/gorgone.ihtml
  www/include/Administration/parameters/gorgone/gorgone.php
  www/include/Administration/parameters/gorgone/help.php
Labels: area/administration, kind/enhancement, pr/internal-rd

#8405 feat(api): set in Resource some properties as vritual and skip executing of the query if the filters are in conflict
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/api, kind/documentation, kind/enhancement, kind/feature

#8398 enh(apiv2): add downtime and ack info to service and host details
  config/packages/serializer/Centreon/Monitoring.Host.yml
  config/packages/serializer/Centreon/Monitoring.Service.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/MonitoringHostsController.php
  src/Centreon/Domain/Monitoring/Host.php
  src/Centreon/Domain/Monitoring/Service.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/api, kind/enhancement, pr/internal-rd

#8399 feat(ui): Implement Unfied view standard filters
  package-lock.json
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/api/searchObjects.ts
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/__mocks__/axios.js
Labels: area/ui, kind/feature, pr/internal-rd

#8406 fix(centreonACL): return all services linked to a servicegroup
  www/class/centreonACL.class.php
Labels: area/acl, area/monitoring, kind/bug, pr/internal-rd

#8400 fix(core): manage the gorgone configuration files
  LICENSE.md
  install.sh
  libinstall/CentWeb.sh
  libinstall/functions
  varinstall/vars
Labels: area/install, kind/feature, pr/internal-rd

#8421 fix(core): duplicate SSH key on source upgrade
  doc/en/installation/from_sources.rst
  doc/fr/installation/from_sources.rst
  install.sh
  libinstall/CentWeb.sh
  libinstall/functions
Labels: area/install

#8407 enh(centcore): move external command processing loop
  lib/perl/centreon/script/centcore.pm
Labels: area/monitoring, area/performance, kind/enhancement, pr/internal-rd

#8410 enh(ui): Remove Switcher and replace it with @material-ui switch in Extensions manager page
  package-lock.json
  www/front_src/src/route-components/administration/extensions/manager/index.js
Labels: area/ui

#8417 feat(ui): Implement Unified view graph
  package-lock.json
  package.json
  webpack.config.js
  webpack.config.prod.js
  www/front_src/src/Resources/SearchHelpTooltip.tsx
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8281 fix(configuration): export "NULL" values correctly to remote server
  www/class/config-generate-remote/Abstracts/AbstractObject.php
  www/class/config-generate-remote/Manifest.php
Labels: area/remote-server, kind/fix, pr/internal-ps

#8428 fix(api): prevent smart grouping of the services related to host with status down
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/api, kind/bug

#8416 enh(install): add dependency mechanism to fresh installation
  www/install/steps/process/process_step8.php
  www/install/steps/templates/step8.tpl
Labels: area/install, kind/feature, pr/internal-rd

#8434 feat(ui): Implement Acknowledge action
  config/packages/serializer/Centreon/Monitoring.ResourceStatus.yml
  doc/API/centreon-api-v2.yaml
  jest.config.js
  package-lock.json
  package.json
  src/Centreon/Domain/Monitoring/ResourceStatus.php
  www/front_src/src/Resources/Actions.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/forms/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/forms/Acknowledge/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/components/pollerMenu/index.js
  www/front_src/src/components/progressBar/index.js
Labels: area/ui

#8419 fix(dashboard): sanitize uri params
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/reporting/dashboard/viewServicesLog.php
  www/include/reporting/dashboard/xmlInformations/GetXmlHost.php
  www/include/reporting/dashboard/xmlInformations/GetXmlHostGroup.php
  www/include/reporting/dashboard/xmlInformations/GetXmlService.php
  www/include/reporting/dashboard/xmlInformations/GetXmlServiceGroup.php
Labels: area/reporting, kind/security, pr/internal-rd

#8449 fix(npm): Fix centreon-ui dependency
  package-lock.json
  package.json
  webpack.config.dev.js
  webpack.config.js
Labels: area/ui

#8422 enh(dynamic import): Hook component can import multiple hook components
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/route-components/administration/extensions/manager/index.js
Labels: area/ui

#8435 fix(secu): exploit on graphs
  www/api/class/centreon_metric.class.php
  www/include/views/graphs/graphStatus/displayServiceStatus.php
Labels: area/security, kind/security

#8457 fix(install): wrong value used for checkboxes refresh
  www/install/steps/templates/step8.tpl
Labels: area/install, pr/internal-rd

#8467 fix(secu): exploit on graphs
  www/include/views/graphs/graphStatus/displayServiceStatus.php
Labels: area/security, kind/security

#8450 fix(config): fix gorgone config generation for poller not using remote as proxy
  www/include/configuration/configServers/popup/popup.php
Labels: area/configuration, kind/fix, pr/internal-rd

#8460 feat(ui): allow to set downtime in events view
  config/json_validator/default/Downtimes.yaml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  package-lock.json
  package.json
  symfony.lock
  webpack.config.dev.js
  www/front_src/src/Resources/Actions.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/columns/icons/__mocks__/Downtime.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/forms/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/forms/Acknowledge/index.tsx
  www/front_src/src/Resources/forms/Downtime/Dialog.tsx
  www/front_src/src/Resources/forms/Downtime/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8448 fix(api): Sanitize arguments in API request
  www/api/class/centreon_home_customview.class.php
Labels: area/api, kind/security, pr/internal-rd

#8404 Mon 4940 check poller ip address validity master
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  www/class/centreon-clapi/centreonInstance.class.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.php
Labels: area/api, area/configuration, area/engine, kind/security

#8452 refacto(ui): Add Breadcrumb Component from @centreon-ui
  package-lock.json
  package.json
  www/front_src/src/components/breadcrumbWrapper/Breadcrumb.jsx
  www/front_src/src/components/breadcrumbWrapper/Link.jsx
Labels: area/ui

#8478 fix(listing): set events view listing to empty on api error
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8486 fix(web): correctly compute localized downtime's datepickers
  www/class/centreonUser.class.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/common/javascript/centreon/dateMoment.js
  www/include/common/javascript/datepicker/localizedDatepicker.js
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/downtime/common-Func.php
  www/include/monitoring/downtime/downtime.php
  www/include/monitoring/downtime/template/AddDowntime.ihtml
  www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
  www/include/monitoring/external_cmd/cmd.php
  www/include/monitoring/external_cmd/cmdPopup.php
  www/include/monitoring/external_cmd/popup/massive_downtime.php
  www/include/monitoring/external_cmd/popup/popup.php
  www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
  www/include/monitoring/recurrentDowntime/templates/specific_date.html
  www/include/monitoring/status/Hosts/hostJS.php
  www/include/monitoring/status/Services/serviceJS.php
  www/include/views/graphs/graphs.php
  www/main.get.php
Labels: area/monitoring, area/ux, kind/bug

#8484 enh(ui): Refacto Breadcrumb via TypeScript
  package-lock.json
  package.json
  www/front_src/src/BreadcrumbTrail/Breadcrumb.tsx
  www/front_src/src/BreadcrumbTrail/index.tsx
  www/front_src/src/BreadcrumbTrail/models.ts
  www/front_src/src/BreadcrumbTrail/selector/index.test.tsx
  www/front_src/src/BreadcrumbTrail/selector/index.ts
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/breadcrumbWrapper/Breadcrumb.jsx
  www/front_src/src/components/breadcrumbWrapper/Link.jsx
  www/front_src/src/components/breadcrumbWrapper/index.jsx
Labels: area/ui

#8495 enh(ui): improve events view search tooltip
  www/front_src/src/Resources/SearchHelpTooltip.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8497 enh(ui): search resources when pressing enter key
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/index.test.tsx
Labels: area/ui

#8481 feat(ui): Implement Unified view Resource details panel
  package-lock.json
  package.json
  tsconfig.json
  www/front_src/src/Resources/Actions.tsx
  www/front_src/src/Resources/Chip/Acknowledge.tsx
  www/front_src/src/Resources/Chip/Downtime.tsx
  www/front_src/src/Resources/Chip/Graph.tsx
  www/front_src/src/Resources/Chip/index.tsx
  www/front_src/src/Resources/Details/Body/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/Body/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/Body/DetailsTab.tsx
  www/front_src/src/Resources/Details/Body/ExpandableCard.tsx
  www/front_src/src/Resources/Details/Body/StateCard.tsx
  www/front_src/src/Resources/Details/Body/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/colors.ts
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/dateTime.ts
  www/front_src/src/Resources/icons/Downtime.tsx
  www/front_src/src/Resources/icons/__mocks__/Downtime.tsx
  www/front_src/src/Resources/icons/downtime.icon.svg
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/Resources/useCancelTokenSource.ts
  www/front_src/src/Resources/useGet.ts
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/footer/footer.scss
  www/front_src/src/components/pollerMenu/index.js
Labels: area/ui

#8474 feat(ui): allow to schedule check in events view
  package-lock.json
  www/front_src/src/Resources/Actions/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Downtime/index.tsx
  www/front_src/src/Resources/Actions/index.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8487 enh(ui): update style of events view page
  package-lock.json
  www/front_src/src/Resources/Chip/Acknowledge.tsx
  www/front_src/src/Resources/Chip/Downtime.tsx
  www/front_src/src/Resources/Chip/Graph.tsx
  www/front_src/src/Resources/Chip/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/colors.ts
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/icons/Downtime.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8429 fix(ui): Fix install and update buttons label
  www/front_src/src/route-components/administration/extensions/manager/index.js
  www/install/tools/migration/logsMigration.pl
Labels: area/ui
