Repository centreon/centreon, pull requests merged in 2020-07, with the labels that each got.

#8814 Fix #8813
  www/class/config-generate/host.class.php
Labels: pr/internal-ps, status/more-info-needed, status/needs-attention

#8820 chore(update): Adapt to latest centreon-ui changes
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/locale/fr_FR.UTF-8/LC_MESSAGES/messages.ser
Labels: area/ui

#8818 fix(reporting): manage reporting calcuation on host/service rename
  lib/perl/centreon/reporting/CentreonAck.pm
  lib/perl/centreon/reporting/CentreonDashboard.pm
  lib/perl/centreon/reporting/CentreonDownTime.pm
  lib/perl/centreon/reporting/CentreonHost.pm
  lib/perl/centreon/reporting/CentreonHostStateEvents.pm
  lib/perl/centreon/reporting/CentreonLog.pm
  lib/perl/centreon/reporting/CentreonProcessStateEvents.pm
  lib/perl/centreon/reporting/CentreonService.pm
  lib/perl/centreon/reporting/CentreonServiceStateEvents.pm
  lib/perl/centreon/script/dashboardBuilder.pm
  lib/perl/centreon/script/eventReportBuilder.pm
Labels: area/backend, area/reporting

#8815 fix(secu): correct vulnerabilities in Knowledge Base pages
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
  www/include/configuration/configKnowledge/search.php
Labels: area/backend

#8791 enh(api): Move the symfony configuration files
  config/packages/prod/Centreon.yaml
  config/packages/test/Centreon.yaml
  config/services.yaml
  phpunit.xml
Labels: area/api, area/backend

#8809 enh(serialization): Updating the serialization files for the host configuration context
  config/packages/serializer/Centreon/HostConfiguration.ExtendedHost.yml
  config/packages/serializer/Centreon/HostConfiguration.Host.yml
  config/packages/serializer/Centreon/MonitoringServer.MonitoringServer.yml
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#8821 Wrong initial broker endpoints indexes in database
  tests/clapi_export/clapi-configuration.txt
  www/install/var/baseconf/centreon-broker.sql
Labels: area/backend

#8827 feat(api): add endpoints to manage user filters
  config/Modules/Centreon.yaml
  config/json_validator/latest/Centreon/AddOrUpdateFilter.json
  config/packages/serializer/Centreon/Filter.Filter.yml
  config/routes/Centreon/filter.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/FilterController.php
  src/Centreon/Domain/Filter/Filter.php
  src/Centreon/Domain/Filter/FilterException.php
  src/Centreon/Domain/Filter/FilterService.php
  src/Centreon/Domain/Filter/Interfaces/FilterRepositoryInterface.php
  src/Centreon/Domain/Filter/Interfaces/FilterServiceInterface.php
  src/Centreon/Infrastructure/Filter/FilterRepositoryRDB.php
  tests/php/Centreon/Application/Controller/FilterControllerTest.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.5.php
  www/install/sql/centreon/Update-DB-20.04.5.sql
Labels: area/api, area/backend

#8800 fix(security) post cmd execute by centcore
  lib/perl/centreon/script/centcore.pm
  www/include/configuration/configGenerate/xml/postcommand.php
Labels: area/backend

#8828 fix(security) post cmd execute by gorgone
  www/include/configuration/configGenerate/xml/postcommand.php
Labels: area/backend

#8836 fix(cmd) execute post cmd on central
  www/include/configuration/configGenerate/xml/postcommand.php
Labels: area/backend

#8829 fix(security): fix sql injection vulnerabilities in traps
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonTraps.class.php
  www/include/configuration/configObject/traps/formTraps.php
Labels: area/backend

#8822 enh(EventView) :Improve the button consistency with verbs in french translation on the Event view
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
Labels: area/ui

#8823 fix(secu): upgrade kind-of dependency
  package-lock.json
  package.json
Labels: area/security

#8824 fix(secu): upgrade kind-of dependency
  package-lock.json
  package.json
Labels: area/security

#8825 fix(secu): upgrade kind-of dependency
  package-lock.json
  package.json
Labels: area/security

#8826 fix(secu): upgrade kind-of dependency
  package-lock.json
  package.json
Labels: area/security

#8839 chore(npm): Update packages and fix resulting errors
  package-lock.json
  package.json
  webpack.config.js
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#8830 fix(chore): remove errors and improve LDAP logs message
  www/class/centreonLDAP.class.php
Labels: area/backend

#8781 enh(security): Using the new algorithm to hide the password in the service command line
  config/packages/prod/Centreon.yaml
  config/packages/test/Centreon.yaml
  src/Centreon/Domain/Contact/ContactService.php
  src/Centreon/Domain/Contact/Interfaces/ContactServiceInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Domain/ServiceConfiguration/Service.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/MonitoringServiceTest.php
  www/include/monitoring/objectDetails/common-func.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#8788 enh(http) change get to post for more action cmd popup
  composer.lock
  features/bootstrap/AcknowledgementContext.php
  features/bootstrap/AcknowledgementTimeoutContext.php
  www/include/monitoring/external_cmd/cmdPopup.php
  www/include/monitoring/external_cmd/functionsPopup.php
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
  www/include/monitoring/objectDetails/xml/hostSendCommand.php
  www/include/monitoring/objectDetails/xml/serviceSendCommand.php
  www/include/monitoring/status/Hosts/hostJS.php
  www/include/monitoring/status/Services/serviceJS.php
Labels: area/backend

#8841 fix(di): fix dependency injection in user filter repository
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/Filter.Filter.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/FilterController.php
  src/Centreon/Domain/Filter/FilterService.php
  src/Centreon/Domain/Filter/Interfaces/FilterRepositoryInterface.php
  src/Centreon/Domain/Filter/Interfaces/FilterServiceInterface.php
  src/Centreon/Infrastructure/Filter/FilterRepositoryRDB.php
  tests/php/Centreon/Application/Controller/FilterControllerTest.php
Labels: area/api, area/backend, area/documentation

#8832 Mon 5519 sql injection
  www/include/Administration/performance/viewData.ihtml
  www/include/Administration/performance/viewData.php
  www/include/Administration/performance/viewMetrics.php
Labels: area/backend, area/security

#8843 fix(clapi) fix geo_coords
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonService.class.php
Labels: area/backend

#8220 Convert LDAP attributes names to lowercase, fixes #8219
  www/class/centreonLDAP.class.php
Labels: area/administration, pr/external, status/in-backlog, status/needs-attention

#8845 enh(config): Improve message to use Remote Server as proxy, fix #8835
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/help.php
Labels: area/configuration, kind/enhancement

#8846 Fix(monitoring_server): Fixed method to find the local monitoring server
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Labels: area/backend

#8842 feat(ui): Implement Event-view custom filters
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  webpack.config.dev.js
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  www/front_src/src/Resources/Filter/Save/index.test.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/adapters.ts
  www/front_src/src/Resources/Filter/api/decoders.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources.ts
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/searchObjects.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8857 Enh(Webpack) : add an error when AssetSize and EntrypointSize are to bigger
  webpack.config.js
Labels: area/ui

#8856 fix(widget): do not delete preferences when a user delete a shared view
  www/class/centreonCustomView.class.php
Labels: area/backend, area/widgets

#8864 enh(logs): display correctly ACK events on eventLogs page
  www/Themes/Centreon-2/style.css
  www/include/eventLogs/xml/data.php
Labels: area/backend

#8860 feat(ui): Edit Events view custom filters
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/adapters.ts
  www/front_src/src/Resources/Filter/api/decoders.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#8866 enh(chore): optimize sonarqube conf file
  sonar-project.properties
Labels: area/security, area/tests, kind/experimental, pr/internal-rd

#8869 fix(serializer): return id property when calling acknowledgement endp…
  config/packages/serializer/Centreon/Acknowledgement.Acknowledgement.yml
Labels: area/backend

#8867 feat(ui): Reorder Events view custom filters
  package-lock.json
  package.json
  webpack.config.analyze.js
  webpack.config.js
  webpack.config.prod.js
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources.ts
  www/front_src/src/Resources/index.tsx
Labels: area/ui, need-assignee

#8850 fix(security): check mib name in comment
  lib/perl/centreon/script/centFillTrapDB.pm
Labels: area/backend, area/security

#8879 feat(ui): Refresh the panel when the list is refreshed
  doc/API/centreon-api-v2.yaml
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
Labels: area/ui

#8865 feat(api): manage renamed or removed filter criterias objects
  composer.lock
  config/json_validator/latest/Centreon/Filter/AddOrUpdate.json
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/Filter.Filter.yml
  config/packages/serializer/Centreon/Filter.FilterCriteria.yml
  config/packages/test/Centreon.yaml
  src/Centreon/Application/Controller/FilterController.php
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Domain/Filter/Filter.php
  src/Centreon/Domain/Filter/FilterCriteria.php
  src/Centreon/Domain/Filter/FilterService.php
  src/Centreon/Domain/Filter/Interfaces/FilterServiceInterface.php
  src/Centreon/Domain/Monitoring/HostGroup/HostGroupException.php
  src/Centreon/Domain/Monitoring/HostGroup/HostGroupService.php
  src/Centreon/Domain/Monitoring/HostGroup/Interfaces/HostGroupRepositoryInterface.php
  src/Centreon/Domain/Monitoring/HostGroup/Interfaces/HostGroupServiceInterface.php
  src/Centreon/Domain/Monitoring/ServiceGroup/Interfaces/ServiceGroupRepositoryInterface.php
  src/Centreon/Domain/Monitoring/ServiceGroup/Interfaces/ServiceGroupServiceInterface.php
  src/Centreon/Domain/Monitoring/ServiceGroup/ServiceGroupException.php
  src/Centreon/Domain/Monitoring/ServiceGroup/ServiceGroupService.php
  src/Centreon/Infrastructure/Filter/FilterRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/HostGroup/HostGroupRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/ServiceGroup/ServiceGroupRepositoryRDB.php
  src/Utility/StringConverter.php
  tests/api/Context/UserFilterContext.php
  tests/api/features/UserFilter.feature
  tests/php/Centreon/Application/Controller/FilterControllerTest.php
  tests/php/Centreon/Domain/Filter/FilterServiceTest.php
  tests/php/Utility/StringConverterTest.php
Labels: area/api, area/backend

#8876 fix(security): use user id instead of session id in session page
  www/api/class/centreon_ldap_synchro.class.php
  www/include/options/session/connected_user.php
Labels: area/backend

#8883 fix(session): use userId instead of sessionId
  www/include/options/session/connected_user.php
Labels: area/backend

#8875 fix(wiki): sanitize db test connection
  www/api/class/centreon_wiki.class.php
Labels: area/backend

#8882 fix(sec): avoid xss in widget rename webservice
  www/class/centreonWidget.class.php
  www/include/home/customViews/rename.php
Labels: area/backend, area/security
