Repository centreon/centreon, pull requests merged in 2020-09, with the labels that each got.

#8948 fix(secu): correct ACL on returned user list
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonCustomView.class.php
  www/include/configuration/configObject/contact/contact.php
  www/include/home/customViews/action.php
Labels: area/backend, area/security

#8950 fix(servicegroup) add remove servicegroup method
  www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#8951 fix(secu): correct ACL on returned group list
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonCustomView.class.php
  www/include/configuration/configObject/contactgroup/contactGroup.php
Labels: area/backend, area/security

#8956 enh(cron): Adds a cron library to allow checking cron expressions
  composer.json
  composer.lock
  symfony.lock
Labels: area/backend

#8941 enh(host): Allows to create host services according to host templates
  config/packages/prod/Centreon.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/AccessControlList/Interfaces/AccessControlListRepositoryInterface.php
  src/Centreon/Domain/Engine/EngineConfiguration.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/ServiceConfiguration/ExtendedService.php
  src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
  src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationRepositoryInterface.php
  src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationServiceInterface.php
  src/Centreon/Domain/ServiceConfiguration/Service.php
  src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
  src/Centreon/Infrastructure/AccessControlList/AccessControlListRepositoryTrait.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
Labels: area/backend

#8961 enh(host): Allows to create host services according to host templates
  config/Modules/Centreon.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/AccessControlList/Interfaces/AccessControlListRepositoryInterface.php
  src/Centreon/Domain/Engine/EngineConfiguration.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/ServiceConfiguration/ExtendedService.php
  src/Centreon/Domain/ServiceConfiguration/HostTemplateService.php
  src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationRepositoryInterface.php
  src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationServiceInterface.php
  src/Centreon/Domain/ServiceConfiguration/Service.php
  src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
  src/Centreon/Infrastructure/AccessControlList/AccessControlListRepositoryTrait.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
Labels: area/backend

#8962 fix(graph): avoid B unit in y axis
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/backend, area/chart

#8942 feat(event-view): Add shortcuts tab
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/Shortcuts.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/ShortcutsSection.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/hasDefinedValues.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8973 Mon 5946
  composer.lock
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#8974 fix(security): fix xss injection in widget rename
  composer.json
  composer.lock
  www/include/home/customViews/rename.php
  www/index.html
  www/static/icomoon.0a8cb044.eot
  www/static/icomoon.17e97f56.eot
  www/static/icomoon.3096ac26.woff
  www/static/icomoon.32b797da.woff
  www/static/icomoon.3e2481e2.svg
  www/static/icomoon.779e9525.ttf
  www/static/icomoon.94a9bf88.svg
  www/static/icomoon.98bdd93b.ttf
  www/static/icomoon.a1e1e52f.svg
  www/static/icomoon.ed06b521.svg
  www/static/main.10c2882b.chunk.css
  www/static/main.3f175070.chunk.js
  www/static/roboto-bold-webfont.6cffc9d0.ttf
  www/static/roboto-bold-webfont.d2384aba.woff
  www/static/roboto-bold-webfont.f75e8272.woff2
  www/static/roboto-light-webfont.c3d6af26.woff2
  www/static/roboto-light-webfont.ce61b8b6.ttf
  www/static/roboto-light-webfont.d6e4384c.woff
  www/static/roboto-medium-webfont.2784ad66.ttf
  www/static/roboto-medium-webfont.b71ad717.woff2
  www/static/roboto-medium-webfont.ef363b82.woff
  www/static/roboto-regular-webfont.6bede58e.ttf
  www/static/roboto-regular-webfont.a018746c.woff2
  www/static/roboto-regular-webfont.e3b6ff3e.woff
  www/static/runtime~main.7c144927.js
  www/static/slider-default-image-widget.cdfe6839.png
  www/static/vendors~external.7dade248.chunk.js
  www/static/vendors~main.2f3d2383.chunk.css
  www/static/vendors~main.faf9a9cc.chunk.js
Labels: area/backend, area/security, area/tests

#8967 fix(resources-status): Fix Timeline infinite scroll showing incoherent results
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: area/ui, need-assignee

#8953 fix(sec): avoid sql injection in downtimes page
  www/include/common/autoNumLimit.php
  www/include/monitoring/downtime/listDowntime.php
Labels: area/backend, area/security

#8952 fix(sec): avoid sql injection in downtimes page
  www/include/common/autoNumLimit.php
  www/include/monitoring/downtime/listDowntime.php
Labels: area/backend, area/security

#8958 fix(security) fix hotlink on media
  www/img/media/.htaccess
Labels: area/backend, area/security

#8954 fix(secu): correct ACL on returned users and groups list
  .gitignore
  lang/fr/LC_MESSAGES/messages.po
  www/class/centreonCustomView.class.php
  www/include/configuration/configObject/contactgroup/contactGroup.php
Labels: area/backend, area/security

#8969 enh(api): add possibility to see anomaly detection services
  www/api/class/centreon_configuration_service.class.php
Labels: area/backend

#8970 feat(remote): add form to store central's API credential
  bin/registerServerTopology.php
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Infrastructure/Resources/sql/disablemenus.sql
  src/Centreon/Infrastructure/Resources/sql/enablemenus.sql
  www/class/centreonUUID.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/parameters.php
  www/include/Administration/parameters/remote/formRemote.ihtml
  www/include/Administration/parameters/remote/formRemote.php
  www/include/Administration/parameters/remote/help.php
  www/include/Administration/parameters/remote/index.html
  www/include/core/errors/alt_error.php
  www/install/createTables.sql
  www/install/insertTopology.sql
  www/install/php/Update-20.10.0.php
  www/install/php/Update-20.10.0.post.php
  www/install/sql/centreon/Update-DB-20.10.0.sql
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#8972 enh(api): refactor resource details endpoints
  config/packages/serializer/Centreon/Monitoring.Host.yml
  config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsHost.yml
  config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsService.yml
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceLinks.yml
  config/packages/serializer/Centreon/Monitoring.ResourceLinksEndpoints.yml
  config/packages/serializer/Centreon/Monitoring.ResourceLinksUris.yml
  config/packages/serializer/Centreon/Monitoring.Service.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Controller/Router.php
  src/Centreon/Domain/Monitoring/Host.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/ResourceRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
  src/Centreon/Domain/Monitoring/Model/ImportTrait.php
  src/Centreon/Domain/Monitoring/Model/ResourceDetailsHost.php
  src/Centreon/Domain/Monitoring/Model/ResourceDetailsService.php
  src/Centreon/Domain/Monitoring/Model/ResourceDetailsTrait.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Domain/Monitoring/ResourceLinks.php
  src/Centreon/Domain/Monitoring/ResourceLinksEndpoints.php
  src/Centreon/Domain/Monitoring/ResourceLinksUris.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
  src/Centreon/Domain/Monitoring/Service.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  tests/api/features/ResourceMonitoring.feature
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
  tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/models.ts
Labels: area/backend

#8985 fix(upgrade): correct query
  www/install/php/Update-20.10.0.post.php
Labels: area/backend

#8946 fix(security): don't display password value as plain text in Administration Logs menu
  www/class/centreonLogAction.class.php
Labels: area/backend

#8982 enh(acl): give access to resource status page on existing acl
  www/install/php/Update-20.10.0.post.php
Labels: area/backend

#8981 fix(filter): update filter on save with returned data
  src/Centreon/Domain/Filter/FilterService.php
  tests/php/Centreon/Domain/Filter/FilterServiceTest.php
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/Save/index.test.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/index.ts
Labels: area/ui

#8991 fix(test): match hostgroup filter criteria properly
  tests/api/Context/UserFilterContext.php
Labels: area/backend

#8990 feat(upgrade): platform topology for remote
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Domain/PlatformTopology/PlatformTopology.php
  www/include/Administration/parameters/remote/formRemote.php
  www/install/php/Update-20.10.0.post.php
Labels: area/backend

#8992 enh(api): set resource status entity to service
  config/packages/serializer/Centreon/Monitoring.ResourceStatus.yml
  config/packages/serializer/Centreon/Monitoring.Service.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/Monitoring/Service.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/api, area/backend

#8993 enh(platformstatus): allow script automation with template
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
  bin/registerServerTopologyTemplate
Labels: area/backend

#8984 enh(uri): build host and service details uri from controller
  src/Centreon/Application/Controller/AbstractController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/backend

#8998 fix(filter): initialize filter criterias when given in url
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/useFilter.ts
Labels: area/ui

#8955 feat(api): add submit result endpoint
  config/json_validator/latest/Centreon/SubmitResult/SubmitResult.json
  config/json_validator/latest/Centreon/SubmitResult/SubmitResultResources.json
  config/packages/validator/validation.yaml
  config/routes/Centreon/monitoring/submit_result.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/Monitoring/SubmitResultController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineServiceInterface.php
  src/Centreon/Domain/Monitoring/SubmitResult/Interfaces/SubmitResultServiceInterface.php
  src/Centreon/Domain/Monitoring/SubmitResult/SubmitResult.php
  src/Centreon/Domain/Monitoring/SubmitResult/SubmitResultException.php
  src/Centreon/Domain/Monitoring/SubmitResult/SubmitResultService.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  tests/api/Context/SubmitResultContext.php
  tests/api/behat.yml
  tests/api/features/SubmitResult.feature
  tests/php/Centreon/Application/Controller/Monitoring/SubmitResultControllerTest.php
  tests/php/Centreon/Domain/Engine/EngineServiceTest.php
Labels: area/api, area/backend, area/monitoring

#9001 enh(ui): add possibility to build resource uri with given tab name
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/MonitoringResourceController.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/api, area/backend

#9003 feat(api): refacto of massive resource disacknowledgement endpoint
  config/json_validator/latest/Centreon/Acknowledgement/DisacknowledgeResources.json
  config/routes/Centreon/acknowledgement.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
  src/Centreon/Domain/Acknowledgement/Interfaces/AcknowledgementServiceInterface.php
  tests/api/behat.yml
  tests/api/features/Acknowledgement.feature
  tests/php/Centreon/Application/Controller/AcknowledgementControllerTest.php
  tests/php/Centreon/Domain/Engine/EngineServiceTest.php
Labels: area/api, area/backend

#9005 enh(uri): enhance regexp to get full uri
  src/Centreon/Application/Controller/AbstractController.php
Labels: area/backend

#8996 feat(resource-status): Implement services tab
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Services/api/decoders.ts
  www/front_src/src/Resources/Details/tabs/Services/api/index.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/models.ts
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/decoders.ts
  www/front_src/src/Resources/Details/tabs/Timeline/models.ts
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/decoders.ts
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8997 enh(platformstatus) insert topology in new table
  www/install/php/Update-20.10.0.post.php
Labels: area/backend

#9002 feat(resource-status): Add disacknowledge action
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  www/front_src/src/Provider/UserContext.ts
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/ActionButton.tsx
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/api/index.ts
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Actions/useActions.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9008 fix(resource-status): Fix disacknowledge call
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
Labels: area/ui

#9007 enh(uri): enhance regexp to handle api v1 rest call
  src/Centreon/Application/Controller/AbstractController.php
Labels: area/backend

#9004 enh(monitoring): add deprecation link in deprecated monitoring pages
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Services/service.php
Labels: area/backend

#9006 enh(topCounter): Redirect top counter links to the resource status page
  behat.yml
  features/TopCounterHosts.feature
  features/TopCounterServices.feature
  features/bootstrap/TopCounterHostsContext.php
  features/bootstrap/TopCounterServicesContext.php
  package-lock.json
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/adapters.ts
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/components/header/clock/index.js
  www/front_src/src/components/header/getResourcesUrl.ts
  www/front_src/src/components/header/hostMenu/index.js
  www/front_src/src/components/header/hostMenu/index.test.tsx
  www/front_src/src/components/header/index.js
  www/front_src/src/components/header/pollerMenu/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.test.tsx
  www/front_src/src/components/header/userMenu/index.js
Labels: area/ui, need-assignee

#9012 fix(api): fix timeline for non admin users
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
Labels: area/api, area/backend

#9015 enh(resource-tatus): Change Resource link copy icon
  www/front_src/src/Resources/Details/Header.tsx
Labels: area/ui

#9014 enh(resource-status): Translate status chip labels
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/locale/fr_FR.UTF-8/LC_MESSAGES/messages.ser
Labels: area/ui

#9009 feat(web): register / edit poller in platformtopology via poller form
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/formServers.php
Labels: area/backend

#9019 fix(api): fix severity display & filtering in monitoring pages
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/backend

#9018 enh(resource-status): Make details tab URL query parameters interpretation more robust
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9017 enh(ui): redirect links to resource status listing & panel
  www/include/eventLogs/xml/data.php
  www/include/eventLogs/xsl/log.xsl
  www/include/monitoring/comments/listComment.php
  www/include/monitoring/comments/template/comments.ihtml
  www/include/monitoring/downtime/listDowntime.php
  www/include/monitoring/downtime/template/listDowntime.ihtml
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  www/include/monitoring/status/HostGroups/xsl/hostGroup.xsl
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xsl/serviceGrid.xsl
  www/include/monitoring/status/Services/xsl/serviceSummary.xsl
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceGridByHG.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceSummaryByHG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceGridBySG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceSummaryBySG.xsl
Labels: area/backend

#8988 fix(clapi): avoid duplicated export of contact and contactgroup
  www/class/centreon-clapi/centreonService.class.php
Labels: area/backend

#9024 fix(resource-status/timeline): trigger selectedTypes reload only when timeline is defined
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: area/ui

#9016 fix(symfony): Fixed the bad configuration of Symfony services
  config/packages/prod/Centreon.yaml
Labels: area/backend

#9013 feat(resource-status): Implement Submit status action
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  www/front_src/src/Provider/UserContext.ts
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/Resource/SubmitStatus/api/index.ts
  www/front_src/src/Resources/Actions/Resource/SubmitStatus/index.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9023 fix(api): fix timeline with recurrent downtime (no contact id)
  config/packages/serializer/Centreon/Monitoring.Timeline.TimelineContact.yml
  src/Centreon/Domain/Monitoring/Timeline/TimelineContact.php
  src/Centreon/Domain/Monitoring/Timeline/TimelineEvent.php
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
Labels: area/backend

#9026 fix(log): skip empty lvl3 on topology acl
  www/class/centreonACL.class.php
Labels: area/backend

#9020 fix(select2): fix cancellation of selectAll popin
  features/bootstrap/SelectAllSelect2Context.php
  www/include/common/javascript/centreon/centreon-select2.js
Labels: area/backend

#9029 fix(ui): display shortcuts tab if at least one shortcut is displayed
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Contact/Contact.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
  www/front_src/src/Resources/hasDefinedValues.ts
Labels: area/backend, area/ui

#8994 enh(platformstatus) convert central to remote
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
Labels: area/backend

#9035 fix(platformstatus): correct requirement
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
Labels: area/backend

#9022 enh(resource-status): Reset page when searching
  package-lock.json
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
Labels: area/ui

#9034 fix(ui): force default page to resource status to avoid confusion
  www/class/centreonUser.class.php
  www/include/common/common-Func.php
  www/install/sql/centreon/Update-DB-20.10.0-beta.1.sql
Labels: area/backend

#9033 fix(backup): remove warning messages
  cron/centreon-backup.pl
  www/class/config-generate-remote/Engine.php
Labels: area/backend, area/backup

#9032 fix(remote): remove configuration links in service details page
  www/include/monitoring/objectDetails/serviceDetails.php
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#9036 fix(submit): wrong variable used for resources authorization
  src/Centreon/Application/Controller/Monitoring/SubmitResultController.php
Labels: area/backend

#9031 enh(monitoring): redirection link leads to Resource Status with basic…
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Services/service.php
Labels: area/backend

#9021 enh(proxy): rename test proxy button
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/general/form.php
Labels: area/administration, area/backend

#9041 fix(test): remove legacy apiV2 tests (random fails)
  behat.yml
  features/APIv2/Monitoring/HostApi.feature
  features/APIv2/Monitoring/ServiceApi.feature
  features/bootstrap/APIv2Context.php
Labels: area/backend

#9037 enh(resource-status/perf): Improve Listing performance
  package-lock.json
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph/index.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#9042 fix(clapi): avoid duplicate contact export
  www/class/centreon-clapi/centreonContactGroup.class.php
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonHostGroupService.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/backend

#9038 fix(resource-status/Graph): Fix base 1024 formatting
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.test.ts
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
Labels: area/ui

#9028 enh(platformstatus) export platform topology for remote
  www/class/config-generate-remote/Generate.php
  www/class/config-generate-remote/PlatformTopology.php
Labels: area/backend

#9048 fix(acl): fix access to resources status page
  www/include/common/common-Func.php
  www/install/php/Update-20.10.0-beta.1.post.php
  www/main.get.php
Labels: area/backend

#9030 enh(host): Check for illegal characters when creating hosts
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Labels: area/backend

#9051 fix(test): upgrade centreon-test-lib to fix random fails (20.04)
  composer.lock
Labels: area/backend

#9043 enh(wizard): Register informations from Wizard into platform_topology table
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/PlatformTopology/PlatformTopology.php
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  www/front_src/src/components/forms/poller/PollerFormStepOne.js
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
  www/front_src/src/route-components/pollerStep1/index.js
Labels: area/backend, area/ui

#9040 enh(platformstatus): Save API Credentials and Proxy Options into remote database
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
Labels: area/backend

#9039 enh(host): Check for illegal characters when creating hosts
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  src/Centreon/Domain/Repository/RepositoryException.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Labels: area/backend

#9050 fix(test): upgrade centreon-test-lib to fix random fails
  composer.lock
Labels: area/backend

#9047 enh(platform status) dont insert map by update to topology
  www/install/php/Update-20.10.0-beta.1.post.php
Labels: area/backend

#9045 enh(resource-status/Listing): Limit information character count to 180 characters
  package-lock.json
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/truncate.ts
Labels: area/ui

#9055 fix(media) fix hotlink on all files in media directory
  www/img/media/.htaccess
Labels: area/backend

#9049 enh(platform status) remote/central communication form
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/remote/formRemote.ihtml
  www/include/Administration/parameters/remote/formRemote.php
  www/include/Administration/parameters/remote/help.php
Labels: area/backend

#9056 fix(acl): manage top level menu acl on migration
  www/install/php/Update-20.10.0-beta.1.post.php
Labels: area/backend

#9058 fix(api): get properly icon path
  src/Centreon/Infrastructure/Icon/IconRepositoryRDB.php
Labels: area/backend
