Repository centreon/centreon, pull requests merged in 2020-12, with the labels that each got.

#9260 chore(API): Move PlatformJsonGraph to Infrastructure
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Infrastructure/PlatformTopology.Model.PlatformJsonGraph.yml
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Infrastructure/PlatformTopology/Model/PlatformJsonGraph.php
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
Labels: area/backend

#9257 fix(secu): enhance default http configuration when using sources
  libinstall/functions
Labels: area/install, area/security

#9258 fix(secu): enhance default http configuration when using sources
  libinstall/functions
Labels: area/install, area/security

#9266 enh(timeline): add filter on date
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
Labels: area/backend

#9267 fix(secu): check page_limit consistency on XHR
  www/api/class/centreon_administration_aclgroup.class.php
  www/api/class/centreon_administration_widget.class.php
  www/api/class/centreon_configuration_command.class.php
  www/api/class/centreon_configuration_contact.class.php
  www/api/class/centreon_configuration_contactgroup.class.php
  www/api/class/centreon_configuration_graphcurve.class.php
  www/api/class/centreon_configuration_graphtemplate.class.php
  www/api/class/centreon_configuration_host.class.php
  www/api/class/centreon_configuration_hostcategory.class.php
  www/api/class/centreon_configuration_hostgroup.class.php
  www/api/class/centreon_configuration_hosttemplate.class.php
  www/api/class/centreon_configuration_manufacturer.class.php
  www/api/class/centreon_configuration_meta.class.php
  www/api/class/centreon_configuration_poller.class.php
  www/api/class/centreon_configuration_service.class.php
  www/api/class/centreon_configuration_service_severity.class.php
  www/api/class/centreon_configuration_servicecategory.class.php
  www/api/class/centreon_configuration_servicegroup.class.php
  www/api/class/centreon_configuration_servicetemplate.class.php
  www/api/class/centreon_configuration_timeperiod.class.php
  www/api/class/centreon_configuration_timezone.class.php
  www/api/class/centreon_configuration_trap.class.php
  www/api/class/centreon_metric.class.php
  www/api/class/centreon_monitoring_poller.class.php
  www/api/class/centreon_performance_service.class.php
Labels: area/backend, area/security

#9269 fix(ACL): sanitize ACL search parameters
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
  www/include/options/accessLists/groupsACL/listGroupConfig.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
Labels: area/backend

#9263 fix(CLAPI): APPLYCFG Sync Task for Remote Servers
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#9271 fix(ACL): sanitize ACL search parameters
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
  www/include/options/accessLists/groupsACL/listGroupConfig.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
Labels: area/backend

#9270 enh(api): user and global parameters endpoints
  config/routes/Centreon/administration/parameters.yaml
  config/routes/Centreon/user.yaml
  doc/API/centreon-api-v2.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/Administration/ParametersController.php
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Option/OptionService.php
  tests/api/Context/UserParametersContext.php
  tests/api/behat.yml
  tests/api/features/UserParameters.feature
Labels: area/backend

#9245 feat(api): add endpoints to API to add comment on resources
  config/json_validator/latest/Centreon/Comment/Comment.json
  config/json_validator/latest/Centreon/Comment/CommentResources.json
  config/packages/validator/validation.yaml
  config/routes/Centreon/monitoring/comments.yaml
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/Monitoring/CommentController.php
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineServiceInterface.php
  src/Centreon/Domain/Monitoring/Comment/Comment.php
  src/Centreon/Domain/Monitoring/Comment/CommentException.php
  src/Centreon/Domain/Monitoring/Comment/CommentService.php
  src/Centreon/Domain/Monitoring/Comment/Interfaces/CommentServiceInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  tests/api/Context/CommentContext.php
  tests/api/behat.yml
  tests/api/features/Comment.feature
  tests/php/Centreon/Application/Controller/Monitoring/CommentControllerTest.php
  tests/php/Centreon/Domain/Engine/EngineServiceTest.php
Labels: area/backend

#9235 fix(Resources status/Downtime): Incorrect default downtime duration
  package-lock.json
  package.json
  www/front_src/src/Provider/endpoint.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
Labels: area/ui

#9255 enh(api) remove pagination object in meta data of monitoring server API
  src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
Labels: area/backend

#9279 fix(api): add resource comments for host issue fixed
  src/Centreon/Domain/Monitoring/Comment/CommentService.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#9286 fix(poller configuration): Don't override Central IP in platform_topology.
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#9291 fix(media): check if temporary directory exist
  www/include/options/media/images/DB-Func.php
Labels: area/backend

#9292 fix(media): check if temporary directory exist
  www/include/options/media/images/DB-Func.php
Labels: area/backend

#9280 enh(assert): Add new asserts
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  tests/php/Centreon/Domain/Common/AssertionTest.php
Labels: area/backend

#9274 feat(API): Delete a platform from topology
  config/routes/Centreon/platform.yaml
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
  tests/api/features/PlatformTopology.feature
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#9295 feat(resource-status/Graph): Display downtime on performance graph
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Area.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Line.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Area/Downtime.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/EventAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Events/Annotation.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Events/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Acknowledgement.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Comments.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/icons/__mocks__/Downtime.tsx
Labels: area/ui

#9259 fix(configuration): improve access to the list of collectors
  www/api/class/centreon_topcounter.class.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/listServers.php
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-20.10.3.sql
Labels: area/backend

#9301 enh(ci): add codeowners file
  .github/CODEOWNERS
Labels: area/backend

#9288 enh(api) remove pagination object in meta data of DT and ACK API
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/DowntimeController.php
Labels: area/backend

#9308 fix(ci): split lines in codeowners file
  .github/CODEOWNERS
Labels: area/backend

#9296 feat(Resource-status/Graph): Add tooltip to add a comment in a Resource performance graph
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Actions/api/endpoint.ts
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Acknowledgement.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Comments.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/DialogAddComment/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/DialogAddComment/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9313 feat(Resource-status/Graph): Allow to export graph and trigger annotations
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Graph/exportToPng.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9318 fix(test): remove phpunit warnings
  Jenkinsfile
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#9311 fix(forms): Fixed the macros on service, service template, host and host template forms
  www/include/common/common-Func.php
  www/include/common/templates/cloneMacro.ihtml
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host/host.php
  www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  www/include/configuration/configObject/host_template_model/hostTemplateModel.php
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/service/serviceByHost.php
  www/include/configuration/configObject/service/serviceByHostGroup.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Labels: area/backend

#9320 fix(api): handle unit for default downtime duration
  src/Centreon/Application/Controller/Administration/ParametersController.php
Labels: area/backend

#9298 fix(password): Remove the display of the password in HTML file in forms of service, service template, host and host template
  www/class/centreonHost.class.php
  www/include/common/common-Func.php
  www/include/common/templates/cloneMacro.ihtml
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host/host.php
  www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  www/include/configuration/configObject/host_template_model/hostTemplateModel.php
  www/include/configuration/configObject/service/formService.ihtml
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/service/serviceByHost.php
  www/include/configuration/configObject/service/serviceByHostGroup.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Labels: area/backend

#9290 enh(api): add groups property to resources details endpoints
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceGroup.yml
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceGroup.php
  src/Centreon/Domain/Monitoring/ResourceService.php
Labels: area/backend

#9324 fix(security): Correctly evaluate centreon_token
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
  www/include/reporting/dashboard/template/viewServicesLog.ihtml
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/reporting/dashboard/viewServicesLog.php
Labels: area/backend

#9329 fix(security): Correctly evaluate centreon_token
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
  www/include/reporting/dashboard/template/viewServicesLog.ihtml
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/reporting/dashboard/viewServicesLog.php
Labels: area/backend

#9331 enh(ci): separate analyse of checkstyle results
  Jenkinsfile
Labels: area/backend

#9335 fix(ci): use delta to detect coding style errors
  Jenkinsfile
Labels: area/backend

#9332 fix(clapi) Fix the RTACKNOWLEDGEMENT CLAPI listing for hosts and services
  lib/Centreon/Object/Acknowledgement/RtAcknowledgement.php
  www/class/centreon-clapi/centreonRtAcknowledgement.class.php
Labels: area/backend

#9319 feat(Resource-status/Actions): Add possibility to add comments in the listing
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
Labels: area/ui

#9326 fix(CLAPI) take account of encoding language
  www/class/centreon-clapi/centreonContact.class.php
Labels: area/backend
