Repository centreon/centreon, pull requests merged in 2020-11, with the labels that each got.

#9175 fix(platformstatus): fix multiflag usage and improve messages formatting
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
Labels: area/backend

#9176 enh(ui): disable UI notification mechanism if not needed by user
  www/include/monitoring/status/Notifications/notifications.php
Labels: area/backend

#8598 MON-2988: fix myAccount special characters update
  www/include/Administration/myAccount/DB-Func.php
Labels: area/backend, area/configuration, kind/fix, pr/internal-ps, status/in-backlog

#9165 fix(graph): update extra legend when timeperiod is changed
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/backend, area/chart

#9179 fix(chore): rename 21.04 upgrade script
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend

#9184 chore(install): update to version 19.10.17.
  www/install/insertBaseConf.sql
  www/install/php/Update-19.10.17.php
Labels: area/backend

#9181 chore(install): update to version 20.10.1.
  www/install/insertBaseConf.sql
  www/install/php/Update-20.10.1.php
Labels: area/backend

#9185 fix(configuration): move session_expire validation rule after required
  www/include/Administration/parameters/general/form.php
Labels: area/backend

#9164 enh(chore): Use dayjs instead of moment to save up bundle space and enhance locale handling
  package-lock.json
  package.json
  setupTest.js
  tsconfig.json
  webpack.config.dev.js
  webpack.config.js
  www/front_src/src/Provider/UserContext.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/useAcl.ts
  www/front_src/src/Provider/useUser.ts
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Status/index.tsx
  www/front_src/src/Resources/Graph/Status/models.ts
  www/front_src/src/Resources/Graph/Status/timeSeries.ts
  www/front_src/src/Resources/Graph/format.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/dateTime.ts
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
  www/front_src/src/components/header/clock/index.js
  www/front_src/src/components/header/clock/index.tsx
  www/front_src/src/components/header/header.scss
Labels: area/ui, need-assignee

#9188 feat(api): add external links to the resource
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceExternalLinks.yml
  config/packages/serializer/Centreon/Monitoring.ResourceLinks.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/ResourceExternalLinks.php
  src/Centreon/Domain/Monitoring/ResourceLinks.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9191 fix(engine configuration): Correctly set debug verbosity
  www/include/configuration/configNagios/DB-Func.php
Labels: area/backend

#9192 fix(engine configurations): Correctly set macro_filters
  www/include/configuration/configNagios/DB-Func.php
Labels: area/backend

#9193 fix(resource): wrong property names used in serializer for external l…
  config/packages/serializer/Centreon/Monitoring.ResourceExternalLinks.yml
Labels: area/backend

#9187 fix(sec): fix 'reach centreon frontend' option management
  www/class/centreonAuth.class.php
Labels: area/backend

#9196 fix(admin): retrieve 'show deprecated pages' option management
  www/include/Administration/myAccount/DB-Func.php
Labels: area/backend

#9199 enh(kb): optimize kb performance
  www/class/centreon-knowledge/procedures.class.php
  www/class/centreon-knowledge/procedures_Proxy.class.php
  www/class/centreon-knowledge/wikiApi.class.php
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
  www/include/configuration/configKnowledge/popup.php
  www/include/configuration/configKnowledge/popup_form.php
  www/include/configuration/configKnowledge/proxy/proxy.php
Labels: area/backend

#9186 enh(api): get alias and fqdn on resources
  composer.lock
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9128 feat(api): Get Platform Topology
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Application/PlatformTopology.PlatformJsonGraph.yml
  config/packages/serializer/Centreon/PlatformTopology.Platform.yml
  config/routes/Centreon/platform.yaml
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Application/PlatformTopology/PlatformJsonGraph.php
  src/Centreon/Domain/Broker/BrokerConfiguration.php
  src/Centreon/Domain/Broker/BrokerException.php
  src/Centreon/Domain/Broker/Interfaces/BrokerRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRegisterRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  src/Centreon/Domain/PlatformTopology/Platform.php
  src/Centreon/Domain/PlatformTopology/PlatformConflictException.php
  src/Centreon/Domain/PlatformTopology/PlatformException.php
  src/Centreon/Domain/PlatformTopology/PlatformRelation.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Infrastructure/Broker/BrokerRepositoryRDB.php
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRegisterRepositoryAPI.php
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  tests/api/features/PlatformTopology.feature
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
  www/class/config-generate-remote/PlatformTopology.php
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#9194 feat(resource-status/Listing): Add an URL column
  www/front_src/src/Resources/Listing/columns/Url.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9198 chore(npm): Re-generate package-lock to include latest centreon-ui changes
  package-lock.json
  package.json
  www/front_src/src/App.tsx
  www/front_src/src/BreadcrumbTrail/Breadcrumb.tsx
  www/front_src/src/BreadcrumbTrail/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Services/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/models.ts
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/api/index.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/hasDefinedValues.ts
  www/front_src/src/Resources/icons/Downtime.tsx
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/form-fields/hoc.js
Labels: area/ui

#9205 fix(deps): use proper version of stack-utils
  package.json
Labels: area/ui

#9218 fix(documentation): remove route redeclaration in API Documentation
  doc/API/centreon-api-v2.yaml
Labels: area/backend

#9189 enh(resource-status/Graph): Replace recharts with visx for performance graph
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/Y.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
Labels: area/ui, need-assignee

#9204 feat(resource-status/Details): Add FQDN and Alias tiles in the details panel
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9210 fix(external): Add @centreon/ui-context in external chunk
  www/front_src/src/index.js
Labels: area/ui

#9207 enh(security): Using new algorithm to hide password in service command line
  config/Modules/Centreon.yaml
  src/Centreon/Domain/Contact/ContactService.php
  src/Centreon/Domain/Contact/Interfaces/ContactServiceInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Domain/ServiceConfiguration/Service.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/MonitoringServiceTest.php
  www/include/monitoring/objectDetails/common-func.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#9222 fix(resource): set same order for SQL query
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9209 enh(chore): homogenize gitignore
  .gitignore
Labels: area/backend

#9208 enh(chore): homogenize gitignore
  .gitignore
Labels: area/backend

#9203 fix(security): check MIMEType of images and archives of images
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonImageManager.php
  www/include/options/media/images/DB-Func.php
  www/include/options/media/images/formImg.php
Labels: area/backend

#9162 enh(broker) add pool size conf
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-clapi/centreonCentbrokerCfg.class.php
  www/class/centreonConfigCentreonBroker.php
  www/class/config-generate-remote/Broker.php
  www/class/config-generate/broker.class.php
  www/include/configuration/configCentreonBroker/DB-Func.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
  www/install/createTables.sql
  www/install/php/Update-20.10.2.php
  www/install/sql/centreon/Update-DB-20.10.2.sql
Labels: area/backend

#9224 fix(clapi): Correctly Export/Import LDAP ContactGroup
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-clapi/centreonContactGroup.class.php
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#9201 enh(api): remove impact_resources_count property in resources listing
  composer.lock
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9231 fix(security): check MIMEType of images and archives of images
  lang/fr/LC_MESSAGES/messages.po
  www/class/centreonImageManager.php
  www/include/options/media/images/DB-Func.php
  www/include/options/media/images/formImg.php
Labels: area/backend

#9232 chore(documentation): add monitoring resources host details to API Doc
  doc/API/centreon-api-v2.yaml
Labels: area/backend, area/documentation

#9226 enh(Resources Status/Graph): Manage stacking curve option
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/StackedLines.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
Labels: area/ui, need-assignee

#9202 fix(password): Remove the display of the password in HTML file in forms of service, service template, host and host template
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonHost.class.php
  www/class/centreonService.class.php
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host/host.php
  www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  www/include/configuration/configObject/host_template_model/hostTemplateModel.php
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/service/formService.ihtml
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/service/serviceByHost.php
  www/include/configuration/configObject/service/serviceByHostGroup.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Labels: area/backend

#9244 enh(resource-status): Make FQDN tile bigger
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
Labels: area/ui

#9243 fix(ldap): correctly set bind_pass value
  www/class/centreonLDAP.class.php
Labels: area/backend

#9246 fix(secu): sanitize filter's XHR parameters
  www/include/monitoring/status/Common/updateContactParam.php
  www/include/monitoring/status/Common/updateContactParamHostGroups.php
  www/include/monitoring/status/Common/updateContactParamServiceGroups.php
Labels: area/backend, area/security

#9220 fix(security) sanitize contact groups
  www/include/configuration/configObject/contactgroup/DB-Func.php
Labels: area/backend

#9248 fix(secu): sanitize filter's XHR parameters
  www/include/monitoring/status/Common/updateContactParam.php
  www/include/monitoring/status/Common/updateContactParamHostGroups.php
  www/include/monitoring/status/Common/updateContactParamServiceGroups.php
Labels: area/backend, area/security

#9228 fix(security) sanitize connector form
  www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend

#9249 fix(clapi): Fix incorrect error messages for contact group and contact template
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#9247 fix(apache): update AllowOverride Rule to properly display icon
  libinstall/functions
Labels: area/backend

#9251 enh(assert): Add assertions
  composer.json
  composer.lock
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Common/Assertion/Assertion.php
  symfony.lock
  tests/php/Centreon/Domain/Common/TestAssertion.php
Labels: area/backend

#9237 chore(documentation): add monitoring resources service details to API Doc
  doc/API/centreon-api-v2.yaml
Labels: area/backend, area/documentation

#9214 feat(test): Add 1ft impl. E2E tests (cypress.io)
  tests/end_to_end/.gitignore
  tests/end_to_end/cypress.json
  tests/end_to_end/cypress/.eslintrc.json
  tests/end_to_end/cypress/README.md
  tests/end_to_end/cypress/build-docker-compose.js
  tests/end_to_end/cypress/fixtures/users/admin.json
  tests/end_to_end/cypress/integration/Login.feature
  tests/end_to_end/cypress/integration/Login/login.ts
  tests/end_to_end/cypress/plugins/index.ts
  tests/end_to_end/cypress/start-env.sh
  tests/end_to_end/cypress/stop-env.sh
  tests/end_to_end/cypress/support/commands.ts
  tests/end_to_end/cypress/support/index.ts
  tests/end_to_end/cypress/tsconfig.json
  tests/end_to_end/cypress/webpack.config.js
  tests/end_to_end/package-lock.json
  tests/end_to_end/package.json
Labels: area/ui, need-assignee

#9253 chore(documentation): Add Gorgone endpoints to API Documentation
  doc/API/centreon-api-v2.yaml
Labels: area/backend, area/documentation

#9254 feat(cypress): upgrade to 6.0.0
  tests/end_to_end/package-lock.json
  tests/end_to_end/package.json
Labels: area/ui
