Repository centreon/centreon, pull requests merged in 2020-04, with the labels that each got.

#8459 fix(UI): Poller and Remote server wizard render looks broken
  www/front_src/src/components/forms/baseWizard.tsx
  www/front_src/src/route-components/pollerStep1/index.js
  www/front_src/src/route-components/pollerStep2/index.js
  www/front_src/src/route-components/pollerStep3/index.js
  www/front_src/src/route-components/remoteServerStep1/index.js
  www/front_src/src/route-components/remoteServerStep2/index.js
  www/front_src/src/route-components/remoteServerStep3/index.js
  www/front_src/src/route-components/serverConfigurationWizard/index.js
Labels: area/ui

#8504 enh(ui): allow to filter on events view 3 first columns
  config/packages/serializer/Centreon/Monitoring.ResourceStatus.yml
  package-lock.json
  src/Centreon/Domain/Monitoring/ResourceStatus.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  tests/php/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslatorTest.php
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8505 fix(conf): add broker stat to remote conf
  www/include/configuration/configServers/popup/remote.yaml
Labels: area/configuration, kind/bug, pr/internal-rd

#8480 enh(generation): add grpc port in generation for engine & broker
  www/class/config-generate/broker.class.php
  www/class/config-generate/engine.class.php
Labels: area/broker, area/configuration, area/engine, kind/enhancement

#8338 enh(ui): fix translations
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
Labels: area/translation, kind/bug, kind/enhancement, status/needs-attention

#8440 enh(api): add new method to list only metrics name from a selected svc
  www/api/class/centreon_metric.class.php
Labels: area/api, kind/enhancement

#8446 Mon 4703 improve performance service internal api
  www/api/class/centreon_performance_service.class.php
Labels: area/api, kind/enhancement

#8506 fix(UI): Wrong label in Top Counter Host (Critical instead of Down)
  www/front_src/src/components/hostMenu/index.js
Labels: area/ui

#8518 feat(ui): add refresh and autorefresh buttons in events view page
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/redux/reducers/refreshReducer.js
Labels: area/ui

#8522 fix(graph): fix missing session
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/authentication, kind/bug

#8524 enh(ui): Improve Details panel and graph display
  www/front_src/src/Resources/Details/Body/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8329 enh(UI): Hide empty graphs from service details
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/monitoring, kind/enhancement, pr/external, status/in-backlog

#8469 enh(API): Add API to retrieve all modules and widgets version
  config/packages/security.yaml
  config/routes/Centreon/platform.yaml
  src/Centreon/Application/Controller/PlatformController.php
  src/Centreon/Domain/Platform/Interfaces/PlatformRepositoryInterface.php
  src/Centreon/Domain/Platform/Interfaces/PlatformServiceInterface.php
  src/Centreon/Domain/Platform/PlatformException.php
  src/Centreon/Domain/Platform/PlatformService.php
  src/Centreon/Infrastructure/Platform/PlatformRepositoryRDB.php
Labels: area/acl, kind/feature, pr/internal-rd

#8527 enh(ui): Fix the width of tries/last check/duration columns, make graph chip as button and fix clear all filters
  package-lock.json
  www/front_src/src/Resources/ActionButton.tsx
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Chip/Graph.tsx
  www/front_src/src/Resources/Chip/index.tsx
  www/front_src/src/Resources/Details/Body/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/Body/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/Body/DetailsTab.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8537 fix(update): add missing db conf for gorgone on a remote"
  www/install/php/Update-20.04.0-beta.1.php
  www/install/steps/process/configFileSetup.php
  www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: area/configuration, area/database, kind/bug, pr/internal-rd

#8536 fix(ui): fix pagination and autocomplete search
  package-lock.json
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/api/searchObjects.ts
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8541 feat(ui): Keep Filter context in localStorage
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/storedFilter.ts
Labels: area/ui

#8542 enh(endpoint): Adapt Downtime and Acknowledgement to new endpoints
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/index.test.tsx
Labels: area/ui

#8546 enh(ui): Fix column widths and display first part of information column only
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.test.tsx
Labels: area/ui

#8550 fix(ui): Prevent details panel display when clicking on Tooltip / Prevent graph tab display when Resource has no Graph
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/index.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8554 fix(ui/api): manage every kind of centreon base URI
  config/routes/centreon.yaml
  doc/en/administration_guide/ui_access.rst
  doc/fr/administration_guide/ui_access.rst
  libinstall/CentWeb.sh
  libinstall/functions
  src/EventSubscriber/CentreonEventSubscriber.php
  www/front_src/src/Resources/ApiNotFoundMessage.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/store/index.js
  www/index.php
Labels: area/ui

#8560 enh(ui): add shadow on events view right panel
  www/front_src/src/Resources/Details/index.tsx
Labels: area/ui

#8561 fix(ui): allow to order events view by duration
  www/front_src/src/Resources/columns/index.tsx
Labels: area/ui

#8556 enh(ui): Enhance Performance graph display and fix Status graph gradient
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Status/index.tsx
  www/front_src/src/Resources/Graph/Status/timeSeries.ts
  www/front_src/src/Resources/Graph/format.ts
  www/front_src/src/Resources/columns/index.tsx
Labels: area/ui

#8557 fix(ui): use timezone in downtime popin
  www/api/class/centreon_topcounter.class.php
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/components/clock/index.js
Labels: area/ui

#8564 enh(ui): Fixes to details panel
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/ExpandableCard.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8439 enh(anomalydetection): add lua parameters from options table
  www/class/config-generate/broker.class.php
Labels: area/broker, area/configuration, kind/enhancement

#8575 enh(ui): Fixes to Events view Listing / Details / Graph
  www/front_src/src/Resources/Details/Body/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/clipboard.ts
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8579 enh(ui): move filter collapse icon to the left
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#8578 enh(ui): Add delay to HoverChip tooltips and allow display of all results in DetailsTable
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/index.test.tsx
Labels: area/ui

#8580 enh(ui): improve search help tooltip in events view
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/SearchHelpTooltip.tsx
  www/front_src/src/Resources/columns/State/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8584 fix(ui): improve ack and downtime popin in events view
  package-lock.json
  package.json
  src/Centreon/Application/Controller/MonitoringResourceController.php
  www/front_src/src/Resources/columns/HoverChip.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
Labels: area/ui

#8587 enh(ui): toggle events view panel only on icon click
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#8585 enh(ui): Improve Graph display when no data are available and legend is large / fix clear all command
  package-lock.json
  www/front_src/src/Resources/Details/Body/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
  www/front_src/src/Resources/columns/Graph/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8586 fix(ui): use last value of search field when a filter triggers a listing search
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8596 fix(generation): correct broker empty lua parameters generation
  www/class/config-generate/broker.class.php
Labels: area/broker, area/configuration, kind/bug

#8588 feat(i18n): Translate Events view page labels
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8607 enh(ui): Improve Event views Performance graph legend and tooltip
  package-lock.json
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/LoadingSkeleton.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/columns/Graph/index.tsx
Labels: area/ui

#8608 fix(ui): Fix column widths for ACK and DT Details tables
  www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
Labels: area/ui

#8609 chore(npm): Update package-lock
  package-lock.json
Labels: area/ui

#8611 fix(ui): Remove legacy pages bottom margin
  www/front_src/src/route-components/legacyRoute/index.js
Labels: area/ui

#8614 chore(npm): Update centreon-ui
  package-lock.json
Labels: area/ui

#8599 MON-5234: fix unitialized values
  www/api/class/centreon_topcounter.class.php
Labels: area/configuration, kind/fix, pr/internal-ps, status/in-backlog

#8632 fix(ui): Fix bottom gap in fullscreen mode
  www/front_src/src/route-components/legacyRoute/index.js
Labels: area/ui

#8642 fix(api): fix acknowledgements endpoint on hosts and services
  config/packages/validator/validation.yaml
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
Labels: area/api

#8649 fix(ui): manage timezone in details panel
  config/Modules/Centreon.yaml
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/EventSubscriber/CentreonEventSubscriber.php
  src/Security/ContactBySession.php
  www/front_src/src/Resources/dateTime.ts
Labels: area/api, area/ui

#8651 enh(ui): Improve resource name and parent resource name display in Event view page
  www/front_src/src/Resources/columns/index.tsx
Labels: area/ui

#8650 fix(ui): Mount Event view Acknowledge and Downtime components only when necessary
  .gitignore
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
Labels: area/ui

#8628 chore(dev): Setup webpack-dev-server with HMR
  babel.config.js
  package-lock.json
  package.json
  webpack.config.dev.js
  webpack.config.js
  www/front_src/src/App.tsx
Labels: area/ui

#8661 enh(ui): Highlight row with open details and adapt to latest @centreon-ui
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Status/index.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/useGet.ts
Labels: area/ui

#8653 enh(install): harden gorgone config generation
  www/install/php/Update-20.04.0-beta.1.php
  www/install/php/Update-20.04.1.php
  www/install/steps/process/configFileSetup.php
  www/install/var/databaseTemplate.yaml
  www/install/var/gorgone/gorgoneCentralTemplate.yaml
  www/install/var/gorgone/gorgoneRemoteTemplate.yaml
Labels: area/configuration, area/install, pr/internal-rd

#8671 fix(ci): Increase temporarily jest timeout
  setupTest.js
Labels: area/ui

#8660 fix(graph): manage timezone in events view graph
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/Monitoring/MetricController.php
  tests/php/Centreon/Application/Controller/Monitoring/MetricControllerTest.php
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Status/index.tsx
  www/front_src/src/Resources/Graph/format.ts
  www/front_src/src/Resources/dateTime.ts
Labels: area/api, area/ui

#8672 fix(build): fix buildof svg components
  webpack.config.js
Labels: area/ui

#8589 MON-5112: fix select2 service templates linked to a servicegroup
  www/class/centreonServicegroups.class.php
Labels: area/configuration, kind/fix, pr/internal-ps, status/in-backlog

#8665 enh: escape specific characters from database password
  www/install/php/Update-20.04.1.php
  www/install/steps/process/configFileSetup.php
  www/install/var/databaseTemplate.yaml
Labels: area/configuration, area/install, pr/internal-rd

#8529 fix(monitoring): change SQL Request to get ServiceGroups as non-admin user
  www/include/monitoring/status/Common/commonJS.php
Labels: area/configuration, kind/fix, pr/internal-rd, status/needs-attention

#8674 fix(security): correct PR #8404
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  www/class/centreon-clapi/centreonInstance.class.php
  www/include/configuration/configServers/DB-Func.php
Labels: area/configuration, area/security, kind/bug

#8592 Fix #8237: centreontrapd messages from error to info
  lib/perl/centreon/script/centreontrapd.pm
Labels: area/monitoring, kind/fix, pr/internal-ps, status/in-backlog
