Repository centreon/centreon, pull requests merged in 2020-10, with the labels that each got.

#9057 MON-6061: gorgone user can apply cfg + enhance security files
  www/class/config-generate-remote/Abstracts/AbstractObject.php
  www/class/config-generate-remote/Backend.php
  www/class/config-generate/abstract/object.class.php
  www/class/config-generate/backend.class.php
Labels: area/backend

#9061 enh(platformstatus): add hostname to platform topology
  bin/registerServerTopology.php
  www/class/config-generate-remote/PlatformTopology.php
  www/install/createTables.sql
  www/install/php/Update-20.10.0-beta.2.php
  www/install/php/Update-20.10.0-beta.2.post.php
  www/install/sql/centreon/Update-DB-20.10.0-beta.2.sql
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#9063 fix(lang): translate snackbar when adding downtime
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
Labels: area/ui

#9060 fix(platform status) fix login credentials
  bin/registerServerTopology.php
Labels: area/backend

#9054 enh(host): Log actions when adding hosts
  composer.json
  config/packages/prod/Centreon.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/ActionLog/ActionLog.php
  src/Centreon/Domain/ActionLog/ActionLogException.php
  src/Centreon/Domain/ActionLog/ActionLogService.php
  src/Centreon/Domain/ActionLog/Interfaces/ActionLogRepositoryInterface.php
  src/Centreon/Domain/ActionLog/Interfaces/ActionLogServiceInterface.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/RequestParameters/Interfaces/RequestParametersInterface.php
  src/Centreon/Domain/RequestParameters/RequestParameters.php
  src/Centreon/Infrastructure/ActionLog/ActionLogRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
Labels: area/backend

#9065 fix(resource-status/Listing): Update Severity, Status, Resource, Parent resource and Graph columns on Resource update
  www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#9064 fix(ui): fix ack & downtime tooltips on hover
  www/front_src/src/Resources/Details/tabs/Shortcuts/Shortcuts.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/models.ts
Labels: area/ui

#9067 fix(resource-status/Graph): convert base to Number before formatting
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
Labels: area/ui

#9025 enh(auth): replace sso keycloak by openid connect
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonAuth.SSO.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
  www/include/core/login/login.php
  www/include/core/login/processLogin.php
  www/include/core/login/template/login.ihtml
  www/install/index.php
  www/install/php/Update-20.10.0-beta.1.php
  www/install/php/Update-20.10.0-beta.2.php
  www/locale/fr_FR.UTF-8/LC_MESSAGES/messages.ser
Labels: area/backend

#9068 enh(config): use gorgone to export/import conf of Remote Server
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#9071 fix(platformstatus): remove PHP notice while using template file
  bin/registerServerTopology.php
  bin/registerServerTopologyTemplate
Labels: area/backend

#9072 fix(upgrade): correct typo
  www/install/php/Update-20.10.0-beta.2.php
Labels: area/backend

#9073 fix(graph): manage null values
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.test.ts
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#9075 fix(version): Allows to compare API versions using the comma separator of a floating number.
  src/Centreon/Domain/VersionHelper.php
  tests/php/Centreon/Domain/VersionHelperTest.php
Labels: area/backend

#9076 fix(engine): fix default illegal characters of centreon-engine
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  www/install/sql/centreon/Update-DB-20.10.0-beta.2.sql
  www/install/var/baseconf/centreon-engine.sql
Labels: area/backend

#9078 fix(upgrade): correct beta2 script
  www/install/php/Update-20.10.0-beta.2.php
  www/install/php/Update-20.10.0-beta.2.post.php
  www/install/sql/centreon/Update-DB-20.10.0-beta.2.sql
Labels: area/backend

#9079 fix(resource-status/Filter): change Filter local storage key to avoid schema incoherence
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/storedFilter.ts
Labels: area/ui

#9087 fix(resource-status/Graph): Fix invalid date with null lower limit
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
Labels: area/ui

#9091 fix(API): fix register a remote on a central and refacto service
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/PlatformInformationController.php
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#9089 fix(api): fix api response when regex is not well formatted
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9092 fix(resource-status/Filter): Fix error when typing a special character in the search bar
  package-lock.json
Labels: area/ui

#9082 enh(API): manage hostname in topology endpoint
  config/json_validator/latest/Centreon/PlatformTopology/Register.json
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/PlatformInformationController.php
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  src/Centreon/Domain/PlatformTopology/PlatformTopology.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
  tests/api/features/PlatformTopology.feature
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#9088 fix(api): fix tries getter for soft states
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9093 fix(openId): improve authentication
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/class/centreonAuth.SSO.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
Labels: area/backend

#9096 fix(export) remote parent id null
  www/class/config-generate-remote/PlatformTopology.php
Labels: area/backend

#9101 fix(platformstatus): correct script response message
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
Labels: area/backend

#9098 fix(openid): fix form missing right braces
  www/include/Administration/parameters/general/form.ihtml
Labels: area/backend

#9100 fix(lang): detect browser locale when needed
  www/front_src/src/Provider/index.tsx
Labels: area/ui

#9094 fix(translation): translate redirection label on deprecated pages
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Services/service.php
Labels: area/backend

#9095 fix(resource-status): Avoid double details refresh and prevents auto refresh from loading the wrong details
  package-lock.json
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
Labels: area/ui

#9097 enh(api): improve perfomance of entityCreator (cache)
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9102 fix(pollerform): Re assign parent id when deleting remote
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#9103 fix(form) fix checkbox default value
  www/include/Administration/parameters/remote/formRemote.php
Labels: area/backend

#9105 fix(API): manage disabled https peer_validation
  src/Centreon/Domain/PlatformInformation/PlatformInformation.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  tests/api/features/PlatformTopology.feature
Labels: area/backend

#9104 fix(links): redirect to resources status page in the current tab
  www/include/core/footer/footerPart.php
  www/include/monitoring/comments/template/comments.ihtml
  www/include/monitoring/downtime/template/listDowntime.ihtml
  www/include/monitoring/status/HostGroups/xsl/hostGroup.xsl
  www/include/monitoring/status/Services/xsl/serviceGrid.xsl
  www/include/monitoring/status/Services/xsl/serviceSummary.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceGridByHG.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceSummaryByHG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceGridBySG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceSummaryBySG.xsl
Labels: area/backend

#9107 fix(resource-status/URLqueryParameters): encode URL parameters and override search when redirecting from top counter
  package-lock.json
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/components/header/getResourcesUrl.ts
  www/front_src/src/components/header/hostMenu/index.test.tsx
  www/front_src/src/components/header/serviceStatusMenu/index.test.tsx
Labels: area/ui

#9108 fix(platformstatus): use FQDN and handle correctly Proxy Usage in Template case
  bin/registerServerTopology-Func.php
  bin/registerServerTopologyTemplate
Labels: area/backend

#9111 enh(API): remove useless import in interface
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
Labels: area/backend

#9110 fix(wizard): initialize message thrown variable
  src/CentreonRemote/Application/Validator/WizardConfigurationRequestValidator.php
Labels: area/backend

#9113 fix(register) fix port location
  bin/registerServerTopology.php
Labels: area/backend

#9114 fix(timeline): avoid duplicated events on engine restart
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
Labels: area/backend

#9109 revert(API): remove information endpoint
  config/packages/serializer/Centreon/PlatformInformation.PlatformInformation.yml
  config/routes/Centreon/configuration.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/PlatformInformationController.php
Labels: area/backend

#9115 fix(platformstatus): default apiPort value in remote form
  bin/registerServerTopology.php
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/parameters/remote/DB-Func.php
  www/include/Administration/parameters/remote/formRemote.php
Labels: area/backend

#9116 fix(API): correct message thrown on inconsistant port value
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/PlatformInformation/PlatformInformation.php
Labels: area/backend

#9121 fix(i18n): Fix warning translation
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#9119 fix(proxy): Fixed an error during the serialization of the Proxy entity
  config/packages/serializer/Centreon/Proxy.Proxy.yml
Labels: area/backend

#9117 fix(register): set default value on https
  bin/registerServerTopology.php
  www/include/Administration/parameters/remote/formRemote.ihtml
  www/include/Administration/parameters/remote/formRemote.php
Labels: area/backend

#9122 fix(db) Update authorize master by script
  bin/registerServerTopology-Func.php
Labels: area/backend

#9120 fix(ui): remove useless poller wizard step
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
  src/CentreonRemote/Domain/Service/TaskService.php
  www/front_src/src/components/wizardFormInstallingStatus/index.js
  www/front_src/src/route-components/pollerStep3/index.js
  www/front_src/src/route-components/remoteServerStep3/index.js
  www/install/react_translation.php
Labels: area/backend

#9125 fix(resource-status/Timeline): Do not display downtime end date if not available
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
Labels: area/ui

#9118 enh(script): increase help and displayed message of script
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
  bin/registerServerTopologyTemplate
Labels: area/backend

#9127 enh(script): Select IP and better Proxy handling
  bin/registerServerTopology.php
Labels: area/backend

#9129 fix(i18n): Add pending translation
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#9123 MON-6152: partitioning starts at epoch
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#9130 fix(openid): remove php warning
  www/class/centreonAuth.SSO.class.php
Labels: area/backend

#9131 fix(upgrade): improve beta1 script
  www/install/php/Update-20.10.0-beta.1.post.php
  www/install/php/Update-20.10.0-beta.2.php
  www/install/php/Update-20.10.0-beta.2.post.php
Labels: area/backend

#9133 enh(API): thrown message on transport exception
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
Labels: area/backend

#9132 fix(script): correction of misstypo
  bin/registerServerTopology.php
Labels: area/backend

#9135 fix(openid): fix PHP warning
  www/class/centreonAuth.SSO.class.php
Labels: area/backend

#9137 fix(resource-status/Timeline): replace fragments by divs
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
Labels: area/ui

#9126 fix(logs): use properly filters during logs export
  www/include/eventLogs/viewLog.php
Labels: area/backend

#9124 fix(broker): fix broker configuration of influxdb output
  www/class/centreonConfigCentreonBroker.php
Labels: area/backend

#9143 fix(resource-status/Timeline): fix duplicated timeline events
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: area/ui, need-assignee

#9136 enh(script): add missing spaces
  bin/registerServerTopology.php
Labels: area/backend

#9146 fix(resource-status/Services): Fix services tab inconsistencies
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
Labels: area/ui, need-assignee

#9154 fix(chore): add missing 20.10.0 stable upgrade script
  www/install/php/Update-20.10.0.php
Labels: area/backend, area/install

#9155 fix(chore): correct hostcategory duplication query
  www/include/configuration/configObject/host_categories/DB-Func.php
  www/include/configuration/configObject/service_categories/DB-Func.php
Labels: area/backend, kind/bug

#9157 fix(web): remove service category massive change options
  www/include/configuration/configObject/service_categories/listServiceCategories.php
  www/include/configuration/configObject/service_categories/serviceCategories.php
Labels: area/backend, kind/bug

#9156 fix(web): remove service category massive change options
  www/include/configuration/configObject/service_categories/listServiceCategories.php
  www/include/configuration/configObject/service_categories/serviceCategories.php
Labels: area/backend, kind/bug

#9142 fix(api): fix search of servicegroups by name
  doc/API/centreon-api-v2.yaml
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/api, area/backend, area/monitoring

#9141 fix(reporting): fix reporting of services by hostgroup
  lib/perl/centreon/reporting/CentreonService.pm
Labels: area/backend

#9160 fix(sql): avoid to get empty options table
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
Labels: area/backend

#9112 MON-5552: too much rows in extended_service_informations
  www/class/config-generate-remote/Relations/ExtendedHostInformation.php
  www/class/config-generate-remote/Relations/ExtendedServiceInformation.php
Labels: area/backend

#9158 fix(resource-status/filter/search): encode listing parameters
  package-lock.json
  www/front_src/src/Resources/Filter/index.test.tsx
Labels: area/ui

#9163 fix(chore): sonarqube configuration file
  sonar-project.properties
Labels: area/backend, build/jenkins

#9166 fix(install): set version to 20.10.0
  www/install/insertBaseConf.sql
Labels: area/backend, area/install

#9167 chore(install): update version to 20.04.7
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.7.php
Labels: area/backend, area/install

#9170 fix(install): set version to 20.10.0 (#9166)
  www/install/insertBaseConf.sql
Labels: area/backend, area/install

#9171 chore(version): update to 21.04.0
  Jenkinsfile
  composer.json
  composer.lock
  package-lock.json
  package.json
  unattended.sh
  www/front_src/src/Resources/Listing/ApiNotFoundMessage.tsx
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0.php
Labels: area/backend
