Repository centreon/centreon, pull requests merged in 2020-08, with the labels that each got.

#8873 fix(acl) check template category acl
  cron/centAcl-Func.php
Labels: area/backend

#8889 fix(clapi) fix services dependencies comment export
  www/class/centreon-clapi/centreonDependency.class.php
Labels: area/backend

#8891 fix(stats): get stats even if a module fails
  cron/centreon-send-stats.php
  www/class/centreonStatistics.class.php
  www/class/centreonStatsModules.class.php
Labels: area/backend

#8892 enh(configuration): improve message to use remote server as proxy
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/configuration/configServers/formServers.php
Labels: area/configuration

#8878 fix(security) hide password value
  www/class/centreonAuth.class.php
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.php
Labels: area/backend, area/security

#8888 feat(api): rework timeline endpoints
  composer.lock
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/Contact.Contact.yml
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.Timeline.TimelineEvent.yml
  config/packages/serializer/Centreon/Monitoring.TimelineEvent.yml
  config/routes/Centreon/monitoring.yaml
  config/routes/Centreon/monitoring/timeline.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/Monitoring/TimelineController.php
  src/Centreon/Application/Controller/MonitoringHostsController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Controller/MonitoringServicesController.php
  src/Centreon/Domain/Monitoring/Entity/AckEventObject.php
  src/Centreon/Domain/Monitoring/Entity/CommentEventObject.php
  src/Centreon/Domain/Monitoring/Entity/DowntimeEventObject.php
  src/Centreon/Domain/Monitoring/Entity/LogEventObject.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Domain/Monitoring/Model/Log.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceStatus.php
  src/Centreon/Domain/Monitoring/Timeline/Interfaces/TimelineRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Timeline/Interfaces/TimelineServiceInterface.php
  src/Centreon/Domain/Monitoring/Timeline/TimelineEvent.php
  src/Centreon/Domain/Monitoring/Timeline/TimelineService.php
  src/Centreon/Domain/Monitoring/TimelineEvent.php
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/TimelineRepositoryRDB.php
  tests/api/Context/MonitoringTimelineContext.php
  tests/api/behat.yml
  tests/api/features/MonitoringTimeline.feature
  tests/php/Centreon/Application/Controller/Monitoring/TimelineControllerTest.php
Labels: area/api, area/backend

#8885 feat(api): add resource check endpoint
  config/json_validator/latest/Centreon/Check/AddChecks.json
  config/packages/serializer/Application/Request.CheckRequest.yml
  config/routes/Centreon/check.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/CheckController.php
  src/Centreon/Application/Request/CheckRequest.php
  src/Centreon/Domain/Check/Check.php
  src/Centreon/Domain/Check/CheckException.php
  src/Centreon/Domain/Check/CheckService.php
  src/Centreon/Domain/Check/Interfaces/CheckServiceInterface.php
  tests/api/Context/CheckContext.php
  tests/api/behat.yml
  tests/api/features/Check.feature
  tests/php/Centreon/Application/Controller/CheckControllerTest.php
  tests/php/Centreon/Domain/Check/CheckServiceTest.php
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/api/index.ts
Labels: area/backend

#8887 fix(broker): Extract correctly IP adress of a proxy configuration
  www/class/config-generate/broker.class.php
Labels: area/backend, area/broker, area/configuration, kind/bug

#8899 fix(build): temporary disable of centos 8 pipeline
  Jenkinsfile
Labels: area/backend

#8895 feat(ui): Implement Events view timeline tab
  composer.lock
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  setupTest.js
  www/front_src/src/Resources/Details/Body/tabs/Timeline/Chip/Event.tsx
  www/front_src/src/Resources/Details/Body/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/Body/tabs/Timeline/api/decoders.ts
  www/front_src/src/Resources/Details/Body/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/Body/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Timeline/models.ts
  www/front_src/src/Resources/Details/Body/tabs/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8861 doc(release): prepare 19.10.16 release notes
  doc/en/release_notes/centreon-19.10.rst
  doc/fr/release_notes/centreon-19.10.rst
Labels: area/documentation

#8906 enh(api): allow to search in information from resource listing
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Filter/SearchHelpTooltip.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/api/endpoint.ts
Labels: area/api, area/backend, area/monitoring, area/ui

#8911 fix(monitoring): do not encode output in service details page
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend, area/monitoring

#8898 doc(api): fix acknowledgement wording
  doc/API/centreon-api-v2.yaml
Labels: area/api, area/backend, area/documentation

#8909 fix(api): remove hard coded centreon db name in performance_service
  www/api/class/centreon_performance_service.class.php
Labels: area/api, area/backend, area/chart

#8859 fix(api): Update v2 API Definitions
  config/packages/serializer/Centreon/MonitoringServer.MonitoringServer.yml
  config/packages/serializer/Centreon/Proxy.Proxy.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/AuthenticationController.php
  src/Centreon/Application/Controller/Configuration/ProxyController.php
  src/Centreon/Domain/MonitoringServer/MonitoringServer.php
  src/Centreon/Domain/Proxy/Proxy.php
  tests/api/Context/AuthenticationContext.php
  tests/api/behat.yml
  tests/api/features/Authentication.feature
Labels: area/api, area/documentation

#8903 fix(service categories): Sanitize inputs
  www/include/configuration/configObject/service_categories/DB-Func.php
  www/include/configuration/configObject/service_categories/serviceCategories.php
Labels: area/backend

#8900 feat(api): add shortcuts to resource listing endpoint
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/AbstractController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Normalizer/IconUrlNormalizer.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/api, area/backend, area/monitoring

#8908 fix(graph): use base configured in graph template
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/backend, area/chart

#8901 enh(ui): Refactor the Events view page using @centreon-ui's ListingPage
  package-lock.json
  package.json
  www/front_src/src/Resources/ActionButton.tsx
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/api/endpoint.ts
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/Body/ExpandableCard.tsx
  www/front_src/src/Resources/Details/Body/StateCard.tsx
  www/front_src/src/Resources/Details/Body/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/ExpandableCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/StateCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/clipboard.ts
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/tabs/Timeline/Chip/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/decoders.ts
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/models.ts
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/api/index.ts
  www/front_src/src/Resources/Listing/columns/Graph/index.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/api/endpoint.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8904 fix(remote): use URL list instead of IP list to keep scheme and port
  src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
Labels: area/backend, area/configuration, area/remote-server

#8912 fix(service categories): Sanitize Inputs
  www/include/configuration/configObject/service_categories/DB-Func.php
  www/include/configuration/configObject/service_categories/serviceCategories.php
Labels: area/backend

#8849 fix(snmptraps): Unable to import SNMP traps MIBs, fix #8816
  lib/perl/centreon/script/centFillTrapDB.pm
Labels: area/configuration, kind/bug

#8571 Extend clapi
  lib/Centreon/Object/Relation/Service/Template/Host.php
  www/class/centreon-clapi/centreonCommand.class.php
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonHostGroup.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/class/centreon-clapi/centreonServiceGroup.class.php
  www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/api, area/backend, kind/enhancement, pr/external, status/in-backlog

#8917 fix(event-view): Fix acknowledge form empty comment provoking infinite load
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
Labels: area/ui

#8914 fix(security): Sanitize host categories inputs
  www/include/configuration/configObject/host_categories/DB-Func.php
  www/include/configuration/configObject/host_categories/hostCategories.php
Labels: area/backend

#8920 remove broken link and add examples
  CONTRIBUTING.md
Labels: area/backend

#8915 fix(notification) delete dependencies
  lib/Centreon/Object/Dependency/DependencyHostParent.php
  lib/Centreon/Object/Dependency/DependencyHostgroupParent.php
  lib/Centreon/Object/Dependency/DependencyServiceParent.php
  lib/Centreon/Object/Dependency/DependencyServicegroupParent.php
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonHostGroup.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/class/centreon-clapi/centreonServiceGroup.class.php
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/hostgroup/DB-Func.php
  www/include/configuration/configObject/meta_service/DB-Func.php
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#8919 fix(security): Sanitize servicegroups Inputs
  www/class/centreonHostgroups.class.php
  www/class/centreonUtils.class.php
  www/include/configuration/configObject/servicegroup/DB-Func.php
  www/include/configuration/configObject/servicegroup/serviceGroup.php
Labels: area/backend

#8921 fix(security): sanitize host categories input
  www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend

#8928 fix(event-view): Fix time values displayed as invalid
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
Labels: area/ui

#8932 fix(widget): correct widget and view relation
  www/class/centreonWidget.class.php
Labels: area/backend

#8934 fix(typo): correct method name
  www/class/centreonWidget.class.php
  www/include/home/customViews/action.php
Labels: area/backend

#8931 enh(configuration): add contact email in form template for remote server
  www/include/configuration/configObject/contact/formContactLight.ihtml
Labels: area/configuration

#8937 fix(event-view): Fix 1024 base metrics value formatting in performance graph
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.test.ts
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#8939 enh(chore): improve sonar conf to match with new plugins
  sonar-project.properties
Labels: area/backend, build/jenkins

#8913 feat(events-view): Add event type filter to the Timeline tab
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/LoadingSkeleton.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/models.ts
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8945 enh(chore): remove old moment lib and update sonar conf
  sonar-project.properties
  www/include/common/javascript/moment-with-locales.js
Labels: area/backend, area/security

#8947 fix(security): don't display password value as plain text in Administration Logs menu 2.8.x
  www/class/centreonLogAction.class.php
Labels: area/backend

#8940 fix(event-view): Send search as empty string instead of undefined when saving a filter
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/api/adapters.ts
Labels: area/ui

#8905 fix(install): fix timezone getter in unattended script
  unattended.sh
Labels: area/backend, area/install

#8949 fix(api): fix timeline namespace in autowiring config
  config/Modules/Centreon.yaml
Labels: area/api, area/backend
