Repository centreon/centreon, pull requests merged in 2020-05, with the labels that each got.

#8675 fix(ui): do not display filter background when search field is focused
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#7817 doc(dev): move php coding style from PSR2 to PSR12
  doc/coding-style/php/README.md
Labels: pr/external, status/needs-attention

#8595 fix(kb): store kb cookie in memory and manage new version
  www/class/centreon-knowledge/wikiApi.class.php
Labels: area/configuration, area/knowledge-base, kind/fix, pr/internal-ps, status/in-backlog

#8673 enh(ui): display link to regex101 in search tooltip
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/SearchHelpTooltip.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8677 enh(refacto): Refactor Resources to suppress test warnings
  package-lock.json
  package.json
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/components/forms/poller/PollerFormStepTwo.test.jsx
  www/front_src/src/components/forms/poller/__snapshots__/PollerFormStepTwo.test.jsx.snap
Labels: area/ui

#8682 enh(ui): Use legend name in performance chart tooltip
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
Labels: area/ui

#8690 fix(engine): fix schedule check latency
  src/Centreon/Domain/Engine/EngineService.php
Labels: area/api, area/engine, area/monitoring

#8679 doc(database): move mariadb prerequisite version to 10.1.x (19.10.x)
  doc/en/installation/prerequisites.rst
  doc/fr/installation/prerequisites.rst
Labels: area/documentation, area/install, pr/internal-ps

#8695 fix: undefined variable and avoid PDO exception on altered requests
  www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
  www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
Labels: area/monitoring, area/security, kind/fix, kind/security, pr/internal-rd

#8694 enh(refacto): Use context to split up resource components
  package-lock.json
  package.json
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.tsx
  www/front_src/src/Resources/Actions/useActions.ts
  www/front_src/src/Resources/Context/__mocks__/index.ts
  www/front_src/src/Resources/Context/index.ts
  www/front_src/src/Resources/Details/Body/tabs/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/SearchHelpTooltip.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/ApiNotFoundMessage.tsx
  www/front_src/src/Resources/Listing/columns/Graph/index.tsx
  www/front_src/src/Resources/Listing/columns/HoverChip.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/Listing/useLoadResources.ts
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#8710 enh(BE): add Asia/Yangon to the timezone list
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.2.php
Labels: area/configuration, php, pr/internal-rd

#8712 enh(BE): add Asia/Yangon to the timezone list
  www/install/insertBaseConf.sql
  www/install/php/Update-19.10.12.php
Labels: area/configuration, php, pr/internal-rd

#8711 enh(BE): add Asia/Yangon to the timezone list
  doc/en/release_notes/centreon-19.04/centreon-19.04.15.rst
  doc/fr/release_notes/centreon-19.04/centreon-19.04.15.rst
  www/install/insertBaseConf.sql
  www/install/php/Update-19.04.15.php
Labels: area/configuration, php, pr/internal-rd

#8701 enh(refacto): Improve test running time by splitting them up
  setupTest.js
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/icons/__mocks__/Downtime.tsx
  www/front_src/src/Resources/index.test.tsx
  www/front_src/src/Resources/testUtils/index.ts
Labels: area/ui

#8709 fix(BE): remove popup errors in logs when altering http request
  www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
  www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
Labels: area/monitoring, kind/bug, php, pr/internal-rd

#8708 fix(BE): remove popup errors in logs when altering http request
  www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
  www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
Labels: area/monitoring, kind/bug, php, pr/internal-rd

#8704 fix(DT): correct DT set between 10pm and noon
  www/include/common/javascript/datepicker/localizedDatepicker.js
  www/include/monitoring/downtime/template/AddDowntime.ihtml
  www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
Labels: area/monitoring, area/ui, area/ux, area/widgets, kind/bug, pr/internal-rd

#8703 fix(ui): Lazy load internal Components
  package-lock.json
  webpack.config.js
  www/front_src/src/route-maps/reactRoutes.js
Labels: area/ui

#8693 enh(api): get user's allowed actions in resources endpoint metadata
  config/routes/Centreon/user.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/UserController.php
Labels: area/api, area/backend, area/monitoring

#8713 fix(ldap) fix authentication fallback to use local
  www/class/centreonAuth.LDAP.class.php
Labels: area/backend

#8717 fix(DT): replace end date when set in the past
  www/include/common/javascript/datepicker/localizedDatepicker.js
Labels: area/backend, area/monitoring, kind/bug

#8604 MON-3082: cannot generate trap or configuration for non allowed users
  www/include/configuration/configGenerate/formGenerateFiles.php
  www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/configuration, kind/fix, pr/internal-ps, status/in-backlog

#8697 fix(APIv1): fix authorize check on webservices added directly in container
  src/Centreon/Infrastructure/Webservice/WebserviceAutorizeRestApiInterface.php
  www/api/class/webService.class.php
Labels: area/api, area/backend

#8716 feat(ui): Hide / show graph line in Event details view
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries.ts
Labels: area/ui

#8719 fix(ui): fix user default page with options
  features/AutologinOptions.feature
  features/bootstrap/AutologinOptionsContext.php
  www/include/common/common-Func.php
Labels: area/backend

#8702 enh(secu): sanitize and cast parameters to int
  www/include/eventLogs/xml/data.php
Labels: area/security, pr/external, priority/major, status/in-backlog

#8723 fix(UI): Fix very small frame view on Safari
  www/front_src/src/App.tsx
  www/front_src/src/styles/_main.scss
  www/front_src/src/styles/partials/_content.scss
Labels: area/ui, kind/bug

#8728 feat(ui): Use Context API to provide userContext and add ACL
  features/bootstrap/LanguageSelectionContext.php
  package-lock.json
  package.json
  www/front_src/src/Provider.js
  www/front_src/src/Provider/UserContext.ts
  www/front_src/src/Provider/endpoint.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/models.ts
  www/front_src/src/Provider/useAcl.ts
  www/front_src/src/Provider/useUser.ts
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#8730 fix(secu): avoid RCE using command helper
  www/include/configuration/configObject/command/minHelpCommand.php
Labels: area/backend, area/security

#8720 chore(install): upgrade version to 20.04.3
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.3.php
Labels: area/backend

#8732 fix: create media folder when inserting an old plugin
  www/class/centreonMedia.class.php
Labels: area/backend, kind/bug

#8741 enh(TA): increase timeout to 60 sec
  features/bootstrap/LanguageSelectionContext.php
Labels: area/backend, area/tests

#8743 fix(security): add missing IP validation in server form
  www/include/configuration/configServers/formServers.php
Labels: area/backend, area/security, kind/bug

#8736 feat(ui): Use user context in resources to handle ACL
  features/bootstrap/LanguageSelectionContext.php
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/api/index.ts
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#8745 enh(install): upgrade to 19.10.13
  www/install/insertBaseConf.sql
  www/install/php/Update-19.10.13.php
Labels: area/backend, area/install

#8744 enh(install): upgrade to 19.04.16
  doc/en/release_notes/centreon-19.04/centreon-19.04.16.rst
  doc/fr/release_notes/centreon-19.04/centreon-19.04.16.rst
  www/install/insertBaseConf.sql
  www/install/php/Update-19.04.16.php
Labels: area/backend, area/install

#8746 fix(api): Avoid any exceptions by replacing command line with the error message
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
Labels: area/backend

#8751 enh(ui): Enhance graph unit formatting and Tooltip display in Event view
  package-lock.json
  package.json
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#8754 fix(gorgone) fix display button for central
  www/include/configuration/configServers/listServers.ihtml
Labels: area/backend, pr/internal-rd
