Repository centreon/centreon, pull requests merged in 2021-07, with the labels that each got.

#9952 fix(ci): quality gate timeout management
  Jenkinsfile
Labels: area-ci

#9938 Fix(UI): Manage long pollers list
  www/front_src/src/components/header/header.scss
  www/front_src/src/components/header/pollerMenu/index.js
Labels: area/ui

#9939 Fix(UI): Parse graph dates following the locale
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/format.ts
  www/front_src/src/Resources/dateTime.ts
Labels: area/ui

#9942 fix(conf/service group) Fix blank page on service group dashboard
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
Labels: area/backend

#9964 fix(web): Undefined variables and LDAP's myAccount issue - @alfredosilvestre-natixis
  www/class/centreon-clapi/centreonHost.class.php
  www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend, kind/bug, pr/external

#9949 fix(generateImage): statement reliable only if chartId is well formatted
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#9962 Enh(UI): Add tooltips on short label columns
  package-lock.json
Labels: area/ui

#9948 enh(UI): Move shortcuts to the panel header
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/Shortcuts.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/ShortcutsSection.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/hasDefinedValues.ts
Labels: area/ui

#9940 Fix(UI): Remove vertical scroll bar graph preview
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/Listing/columns/HoverChip.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9846 enh(auth/openid): improve authentication
  www/class/centreonAuth.SSO.class.php
  www/class/centreonRestHttp.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
Labels: area/backend

#9947 Fix(UI): Adapt UI clock to match with the user language
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#9974 enh(chore): remove CI's timeout workaround
  Jenkinsfile
Labels: area-ci, area/security

#9975 enh(chore): increase timeout value
  Jenkinsfile
  www/class/centreonLog.class.php
Labels: area-ci

#9976 fix(ci): Sonar quality gate fix
  Jenkinsfile
Labels: area-ci

#9957 enh(UI): Make groups chips clickable
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/Groups.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/decoders.ts
  www/front_src/src/Resources/models.ts
Labels: area/ui

#9966 fix(clapi): insert poller into platform_topology
  lib/Centreon/Object/Instance/Instance.php
  tests/api/features/PlatformInformation.feature
  tests/api/features/PlatformTopology.feature
Labels: area/backend

#9946 fix(Resource-status/Filter): Fix sorting discarding criterias and autocomplete infinite scroll
  package-lock.json
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
Labels: area/ui

#9981 fix(API): fix platform topology schema validation
  src/Centreon/Application/Controller/PlatformTopologyController.php
  tests/api/features/PlatformTopology.feature
Labels: area/backend

#9732 fix(typo): fix FR typo
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#9969 fix(downtimes) Enable the support for downtimes until 2100
  config/json_validator/latest/Centreon/Downtime/Downtime.json
  config/json_validator/latest/Centreon/Downtime/Downtimes.json
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Centreon/Domain/Downtime/Downtime.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/downtime/template/AddDowntime.ihtml
  www/install/installBroker.sql
  www/install/sql/centstorage/Update-CSTG-21.10.0-beta.1.sql
Labels: area/backend

#9933 enh(conf/clapi) Export multiple services with the same name
  lib/Centreon/Object/Object.php
  lib/Centreon/Object/Relation/Relation.php
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreon-clapi/centreonObject.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/backend

#9986 enh(CI): Remove sleep 120 from quality gate stage
  Jenkinsfile
Labels: area-ci

#9987 fix(build): Update dependencies and fix build
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/Zone.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/index.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/components/MenuLoader.tsx
  www/include/common/javascript/jquery/plugins/buzz/buzz.min.js
  www/include/common/javascript/tooltipster/jquery.tooltipster.min.js
  www/lib/wz_tooltip/wz_tooltip.js
Labels: area/ui

#9980 fix(conf): do not delete sg relations when editing service template
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend

#9979 fix(conf): export all servicegroups linked to a service template
  www/class/config-generate-remote/ServiceTemplate.php
  www/class/config-generate/servicetemplate.class.php
Labels: area/backend

#9951 Fix(UI): Fix service selection on services list
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
Labels: area/ui

#9985 fix(downtimes) Prevent the user from creating downtimes with start date, end date and duration after 2037
  config/json_validator/latest/Centreon/Downtime/Downtime.json
  config/json_validator/latest/Centreon/Downtime/Downtimes.json
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Centreon/Domain/Downtime/Downtime.php
  src/Centreon/Domain/Downtime/DowntimeService.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/downtime/template/AddDowntime.ihtml
Labels: area/backend

#9995 enh(CentreonUtils): Use option allowed_classes in unserialize
  www/class/centreonUtils.class.php
Labels: area/backend

#9996 fix(platform topology): remove unused variables
  bin/registerServerTopology.sh
Labels: area/backend

#10005 enh(chore): remove sleep step on 20.04
  Jenkinsfile
Labels: area-ci

#10006 enh(chore): remove sleep step on 21.04
  Jenkinsfile
Labels: area-ci

#10003 chore(lib): update centreon-test-lib version
  composer.json
  composer.lock
Labels: area/backend

#9999 fix(ldap): correct time reference used for LDAP sync
  www/class/centreonLDAP.class.php
Labels: area/backend

#10010 chore(quality): increase phpstan level from 4 to 6
  composer.json
  phpstan.neon
  tests/php/Centreon/Application/Controller/HostTemplateControllerTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplateResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplatesTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostGroup/FindHostGroupsResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostGroup/FindHostGroupsTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesTest.php
Labels: area/backend

#9994 enh(translation): remove useless gettext.sh
  install.sh
  libinstall/gettext.sh
Labels: area-ci, area/backend

#10012 fix(downtimes) Prevent the user from creating downtimes with start date, end date and duration after 2037 (#9985)
  composer.json
  composer.lock
  config/json_validator/latest/Centreon/Downtime/Downtime.json
  config/json_validator/latest/Centreon/Downtime/Downtimes.json
  config/packages/dev/jms_serializer.yaml
  config/packages/jms_serializer.yaml
  config/packages/prod/Centreon.yaml
  config/packages/prod/jms_serializer.yaml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Centreon/Domain/Downtime/Downtime.php
  src/Centreon/Domain/Downtime/DowntimeService.php
  src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
  symfony.lock
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/downtime/template/AddDowntime.ihtml
Labels: area/backend

#10013 chore(quality): increase phpstan level from 4 to 6
  composer.json
  phpstan.neon
  tests/php/Centreon/Application/Controller/HostTemplateControllerTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplateResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplatesTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostGroup/FindHostGroupsResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostGroup/FindHostGroupsTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesTest.php
Labels: area/backend

#10018 fix(UI): Add background color for submenu profile in the Header
  www/front_src/src/components/header/header.scss
  www/front_src/src/components/header/userMenu/index.js
Labels: area/ui

#9929 enh(UI): Add batch selection to resources status listing
  www/front_src/src/Resources/Listing/index.tsx
Labels: area/ui, need-assignee

#10029 chore(ci): set manually reference build
  Jenkinsfile
Labels: area-ci, area/backend

#10030 fix(ci): fix phpstan issues
  Jenkinsfile
  src/Centreon/Domain/Log/LoggerTrait.php
  tests/php/Centreon/Application/Controller/AuthenticationControllerTest.php
  tests/php/Security/Infrastructure/Authentication/API/Model_2110/ApiAuthenticationFactoryTest.php
  tests/php/Security/Infrastructure/Authentication/API/Model_2110/ProvidersConfigurationsFactoryTest.php
  tests/php/Security/Infrastructure/Authentication/Repository/Model/ProviderConfigurationFactoryRdbTest.php
Labels: area/backend

#10023 chore(php): add compatibility with php 7.4 + add migration script
  bin/migrate_php74.sh
  bootstrap.php
  src/Centreon/Domain/Monitoring/Resource.php
  www/class/centreonAuth.MySQL.class.php
  www/include/common/common-Func.php
  www/install/php/Update-18.10.1.php
  www/install/php/Update-18.10.2.php
  www/install/php/Update-18.10.3.php
  www/install/php/Update-18.10.4.php
  www/install/php/Update-18.10.5.php
  www/install/php/Update-19.04.2.php
  www/install/php/Update-19.10.0-beta.2.php
  www/install/php/Update-20.04.0-rc.1.php
  www/install/php/Update-20.04.0-rc.2.php
  www/install/php/Update-20.04.0-rc.3.php
  www/install/php/Update-20.04.0.php
  www/install/php/Update-20.04.3.php
  www/install/php/Update-20.04.5.php
  www/install/php/Update-20.04.6.php
  www/install/php/Update-20.10.0-beta.1.php
  www/install/step_upgrade/functions.php
  www/main.get.php
Labels: area/backend

#10035 fix(ui): Remove background color on submenu user edit
  www/front_src/src/components/header/header.scss
Labels: area/ui

#10025 fix(security): hide OpenId tokens in CentreonUI form
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
Labels: area/backend

#10038 chore(ci): set reference job in each recordIssues
  Jenkinsfile
Labels: area-ci, area/backend

#10022 enh(secu): add reporter name
  SECURITY_ACK.md
Labels: area/security

#10037 fix(security): hide Keycloak tokens in CentreonUI form
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.php
Labels: area/backend

#10016 fix(api): fix php compatibility of resource status endpoint
  config/packages/serializer/Centreon/Monitoring.Resources.yml
  src/Centreon/Domain/Monitoring/Interfaces/ResourceRepositoryInterface.php
  src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
  src/Centreon/Domain/Monitoring/Model/ResourceDetailsTrait.php
  src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#10015 chore(php): add script to upgrade php 7.2 to 7.3
  bin/migrate_php73.sh
Labels: area/backend

#10032 chore(php): add compatibility with php 7.4 + add migration script
  bin/migrate_php74.sh
  bootstrap.php
  www/install/php/Update-18.10.1.php
  www/install/php/Update-18.10.2.php
  www/install/php/Update-18.10.3.php
  www/install/php/Update-18.10.4.php
  www/install/php/Update-18.10.5.php
  www/install/php/Update-19.04.2.php
  www/install/php/Update-19.10.0-beta.2.php
  www/install/php/Update-20.04.0-rc.1.php
  www/install/php/Update-20.04.0-rc.2.php
  www/install/php/Update-20.04.0-rc.3.php
  www/install/php/Update-20.04.0.php
  www/install/php/Update-20.04.3.php
  www/install/php/Update-20.04.5.php
  www/install/php/Update-20.04.6.php
  www/install/php/Update-20.10.0-beta.1.php
  www/install/step_upgrade/functions.php
Labels: area/backend

#10034 fix(sql): fix compatibility with MySQL 8
  cron/centAcl.php
  lib/perl/centreon/common/lock.pm
Labels: area/backend

#10036 fix(contact): allow to massive change reach_api on remote server
  www/include/configuration/configObject/contact/formContactLight.ihtml
Labels: area/backend

#10027 fix(sec): validate page and limit api parameters
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/RequestParameters/RequestParametersException.php
  src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend
