Repository centreon/centreon, pull requests merged in 2021-10, with the labels that each got.

#10087 feat(conf/poller): Added APIs to generate and reload monitoring server configuration
  composer.json
  composer.lock
  config/packages/Centreon.yaml
  config/routes/Centreon/configuration.yaml
  config/routes/Centreon/configuration/monitoring_server.yaml
  doc/API/centreon-api-v21.10.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  src/Centreon/Domain/Authentication/Exception/AuthenticationException.php
  src/Centreon/Domain/Contact/ContactService.php
  src/Centreon/Domain/Contact/Exception/ContactServiceException.php
  src/Centreon/Domain/Contact/Interfaces/ContactRepositoryInterface.php
  src/Centreon/Domain/Contact/Interfaces/ContactServiceInterface.php
  src/Centreon/Domain/Exception/TimeoutException.php
  src/Centreon/Domain/Log/DebugFileHandler.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Domain/MonitoringServer/Exception/ConfigurationMonitoringServerException.php
  src/Centreon/Domain/MonitoringServer/Exception/MonitoringServerException.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerConfigurationRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Centreon/Infrastructure/MonitoringServer/Repository/Exception/MonitoringServerConfigurationRepositoryException.php
  src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
  src/Security/Domain/Authentication/AuthenticationService.php
  src/Security/Domain/Authentication/AuthenticationTokenService.php
  src/Security/Domain/Authentication/Exceptions/AuthenticationTokenException.php
  src/Security/Domain/Authentication/Interfaces/AuthenticationTokenRepositoryInterface.php
  src/Security/Domain/Authentication/Interfaces/AuthenticationTokenServiceInterface.php
  src/Security/Infrastructure/Repository/AuthenticationRepository.php
  symfony.lock
  tests/api/Context/MonitoringServerConfigurationContext.php
  tests/api/behat.yml
  tests/api/features/MonitoringServerConfiguration.feature
  tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
  tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
  tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadConfigurationTest.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
  www/include/configuration/configGenerate/xml/generateFiles.php
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend

#10211 Mon 7391 fix forbidden actions on remote server
  www/include/configuration/configCentreonBroker/centreon-broker.php
  www/include/configuration/configGenerate/generateFiles.php
  www/include/configuration/configNagios/nagios.php
  www/include/configuration/configResources/resources.php
  www/include/configuration/configServers/formServers.ihtml
  www/include/configuration/configServers/formServers.php
  www/include/configuration/configServers/listServers.ihtml
  www/include/configuration/configServers/listServers.php
  www/include/configuration/configServers/servers.php
  www/main.get.php
Labels: area/backend

#10080 feat(UI): Add an export button in poller's top counter
  package-lock.json
  www/front_src/src/Header/pollerMenu/ExportConfiguration/api/endpoints.ts
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.test.tsx
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Header/pollerMenu/index.js
  www/front_src/src/Header/pollerMenu/translatedLabels.ts
  www/front_src/src/Provider/decoder.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/index.tsx
Labels: area/ui

#10231 enh(UI): Reduce poller's wizard width by 50%
  www/front_src/src/components/forms/baseWizard.tsx
Labels: area/ui

#10226 fix(sql) move sql update to new file for 21.04.7
  www/install/insertBaseConf.sql
  www/install/sql/centreon/Update-DB-21.04.2.sql
  www/install/sql/centreon/Update-DB-21.04.7.sql
Labels: area/backend

#10234 fix(timeperiod): avoid js exception when saving timeperiod form
  www/include/configuration/configObject/timeperiod/formTimeperiod.ihtml
  www/include/configuration/configObject/timeperiod/formTimeperiod.php
Labels: area/backend

#10233 fix(UI): Fix crash issue on graphs on Firefox
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/RegularLine.tsx
Labels: area/ui

#10241 fix(contact) Fixed contact recovery by authentication token
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#10210 enh(UI): Add suggestions for dynamic criterias
  package-lock.json
  package.json
  webpack.config.js
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#10240 fix(ci): manage api doc delivery for reference build
  Jenkinsfile
Labels: area-ci

#10248 fix(statistics): fix endpoints to get user information
  www/include/core/footer/footerPart.php
Labels: area/backend

#10236 fix(sec): upgrade nelmio cors bundle (20.04)
  composer.json
  composer.lock
Labels: area/backend

#10239 fix(sec): upgrade nelmio cors bundle (21.10)
  composer.json
  composer.lock
Labels: area/backend

#10245 fix(upgrade): align upgrade scripts with versions < 21.10
  www/install/php/Update-20.10.7.php
  www/install/php/Update-20.10.8.php
  www/install/php/Update-20.10.9.php
  www/install/php/Update-21.04.4.php
  www/install/php/Update-21.04.5.php
  www/install/php/Update-21.04.6.php
Labels: area/backend

#10238 fix(sec): upgrade nelmio cors bundle (21.04)
  composer.json
  composer.lock
Labels: area/backend

#10237 fix(sec): upgrade nelmio cors bundle (20.10)
  composer.json
  composer.lock
Labels: area/backend

#10252 fix(conf/poller) Fix APIv2 using curl to force not to use a proxy
  src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
Labels: area/backend

#10250 fix(upgrade): check sql transaction before commit and rollback
  www/install/php/Update-21.04.1.php
  www/install/php/Update-21.04.2.php
  www/install/php/Update-21.04.5.php
  www/install/php/Update-21.04.7.php
Labels: area/backend
