Repository centreon/centreon, pull requests merged in 2021-09, with the labels that each got.

#10063 fix(api): fix serializer constructor call
  src/Centreon/Infrastructure/Serializer/Exception/SerializerException.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
Labels: area/backend

#10071 fix(downtimes) Prevent the user from creating downtimes with start date, end date and duration after 2037
  composer.json
  composer.lock
  config/Modules/Centreon.yaml
  config/json_validator/latest/Centreon/Downtime/Downtime.json
  config/json_validator/latest/Centreon/Downtime/Downtimes.json
  config/packages/dev/jms_serializer.yaml
  config/packages/jms_serializer.yaml
  config/packages/prod/jms_serializer.yaml
  config/packages/serializer/Centreon/Downtime.Downtime.yml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Centreon/Domain/Downtime/Downtime.php
  src/Centreon/Domain/Downtime/DowntimeService.php
  src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
  src/Centreon/Infrastructure/Serializer/Exception/SerializerException.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
  symfony.lock
  www/class/centreonExternalCommand.class.php
  www/include/monitoring/downtime/AddDowntime.php
  www/include/monitoring/downtime/template/AddDowntime.ihtml
  www/include/monitoring/external_cmd/popup/massive_downtime.php
  www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
Labels: area/backend

#10090 fix(clapi): add missing acl actions
  www/class/centreon-clapi/centreonACLAction.class.php
Labels: area/api, area/acl, area/backend

#10093 feat(Resource-status): Add Performance page button
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/include/views/graphs/graphs.php
Labels: area/ui

#10031 (fix): change daemon name and init script
  cron/centreon-backup-mysql.sh
Labels: area/backend

#10095 fix(configuration): set correct right for centreon.conf.php
  www/install/steps/process/configFileSetup.php
Labels: area/backend

#10097 fix(configuration): handle right of conf.pm
  www/install/steps/process/configFileSetup.php
Labels: area/backend

#10000 enh(UI): Allow detail tiles to be re-ordered
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Details/Card.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/AcknowledegmentCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/CommandLineCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DowntimesCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/Content.tsx
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/models.ts
  www/front_src/src/Resources/Details/tabs/Details/StateCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/storedDetailsCards.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
Labels: area/ui, need-assignee

#9878 enh(openid): Implement client_secret_basic as token_endpoint_auth_method
  www/class/centreonAuth.SSO.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
  www/include/Administration/parameters/general/help.php
Labels: kind/enhancement, status/in-backlog, area/authentication

#10076 enh(Resource-status/Details): Add Graph tab for hosts
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/HostGraph.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#10085 fix(openid): fixed http method for userinfo endpoint - #10044
  www/class/centreonAuth.SSO.class.php
Labels: area/authentication, area/backend

#10094 feat(Product Adoption): add user consent option to send plain or anonymised platform informations.
  cron/centAcl.php
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.ihtml
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/help.php
  www/install/createTables.sql
  www/install/php/Update-21.10.0-beta.1.php
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
Labels: area/backend

#10070 enh(Resource-status/Filter): Simplify autocompletion parameters
  package-lock.json
  package.json
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Resources/Filter/index.test.tsx
Labels: area/ui

#10100 fix(ui): Move Navigation from centreon-frontend and replace icomoon by material-ui icons
  package-lock.json
  www/front_src/src/App.tsx
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/centreon-logo-mini.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/index.js
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/logo-mini.scss
  www/front_src/src/Navigation/Sidebar/Logo/centreon.png
  www/front_src/src/Navigation/Sidebar/Logo/index.js
  www/front_src/src/Navigation/Sidebar/Logo/logo.scss
  www/front_src/src/Navigation/Sidebar/Menu/BoundingBox/helpers.js
  www/front_src/src/Navigation/Sidebar/Menu/BoundingBox/index.js
  www/front_src/src/Navigation/Sidebar/Menu/icons.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.js
  www/front_src/src/Navigation/Sidebar/Menu/menu.scss
  www/front_src/src/Navigation/Sidebar/index.js
  www/front_src/src/Navigation/Sidebar/sidebar.scss
  www/front_src/src/Navigation/global-sass-files/_helpers.scss
  www/front_src/src/Navigation/global-sass-files/_mixins.scss
  www/front_src/src/Navigation/global-sass-files/_variables.scss
  www/front_src/src/Navigation/index.js
  www/front_src/src/components/footer/footer.scss
  www/front_src/src/components/footer/index.js
  www/front_src/src/components/header/header.scss
  www/front_src/src/components/header/hostMenu/index.js
  www/front_src/src/components/header/pollerMenu/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.js
  www/front_src/src/components/header/userMenu/index.js
  www/front_src/src/styles/partials/_helpers.scss
Labels: area/ui

#10052 fix(doc): retrieve authentication api doc
  doc/API/centreon-api-v21.10.yaml
Labels: area/documentation, area/backend

#10107 fix(create table): remove parenthesis around default value
  www/install/createTables.sql
Labels: area/backend

#10106 fix(Poller/Wizzard): Replace icomoon by mui icons in Poller wizzard
  package-lock.json
  package.json
  www/front_src/src/Navigation/Sidebar/Menu/index.js
  www/front_src/src/Navigation/Sidebar/Menu/menu.scss
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/components/form-fields/CheckboxField.js
  www/front_src/src/components/form-fields/FieldMsg.js
  www/front_src/src/components/form-fields/InputField.js
  www/front_src/src/components/form-fields/PreselectedRadioField.js
  www/front_src/src/components/form-fields/RadioField.js
  www/front_src/src/components/form-fields/RadioGroupFields.js
  www/front_src/src/components/form-fields/SelectField.js
  www/front_src/src/components/form-fields/hoc.js
  www/front_src/src/components/forms/ServerConfigurationWizardForm.js
  www/front_src/src/components/forms/baseWizard.tsx
  www/front_src/src/components/forms/poller/PollerFormStepOne.js
  www/front_src/src/components/forms/poller/PollerFormStepTwo.jsx
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepTwo.js
  www/front_src/src/components/header/pollerMenu/index.js
  www/front_src/src/components/progressBar/index.js
  www/front_src/src/components/progressBar/progressbar.scss
  www/front_src/src/components/wizardFormInstallingStatus/index.js
  www/front_src/src/route-components/pollerStep3/index.js
  www/front_src/src/route-components/remoteServerStep3/index.js
  www/front_src/src/styles/partials/form/_form.scss
Labels: area/ui

#10114 enh(secu): update security ack
  .github/CODEOWNERS
  SECURITY_ACK.md
Labels: area/backend

#10113 enh(conf/poller) change pollers actions from select to buttons
  features/bootstrap/GeneratePollerContext.php
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/Themes/Centreon-2/style.css
  www/include/configuration/configServers/listServers.ihtml
  www/include/configuration/configServers/listServers.php
Labels: area/backend

#10111 fix(security): Delete session for non-existing contact 21.04
  www/install/createTables.sql
  www/install/php/Update-21.04.5.php
Labels: area/backend

#10112 fix(security): Delete session for non-existing contact 20.04
  www/install/createTables.sql
  www/install/php/Update-20.04.18.php
Labels: area/backend

#10110 fix(security): Delete session for non-existing contact 20.10
  www/install/createTables.sql
  www/install/php/Update-20.10.11.php
Labels: area/backend

#10108 fix(security): Delete session for non-existing contact
  www/include/Administration/parameters/general/form.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/install/createTables.sql
  www/install/php/Update-21.10.0-beta.1.php
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
Labels: area/backend

#10098 Mon 10862 allow to do not defined redirect url
  www/class/centreonAuth.SSO.class.php
  www/include/Administration/parameters/general/help.php
Labels: kind/enhancement, area/authentication, area/backend

#10101 enh(feature-switch): fully manage feature switch
  doc/API/centreon-api-v21.10.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/Administration/myAccount/help.php
  www/include/eventLogs/xml/data.php
  www/include/monitoring/comments/listComment.php
  www/include/monitoring/downtime/listDowntime.php
  www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  www/include/monitoring/status/monitoringService.php
Labels: area/backend

#10118 enh(UI): Make configure resource icon always visible
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Details/index.test.tsx
Labels: area/ui

#10088 fix(api): fix serializer constructor call
  src/Centreon/Infrastructure/Serializer/Exception/SerializerException.php
  src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
Labels: area/backend

#10117 Fix(UI): Fix pending services dot display
  package-lock.json
  package.json
  www/front_src/src/components/header/header.scss
  www/front_src/src/components/header/hostMenu/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.js
Labels: area/ui

#10119 enh(UI): Improve reloading on timeline and services graph
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
Labels: area/ui

#10122 enh(ci): more //lised pipeline workflow
  Jenkinsfile
Labels: area-ci

#10124 enh(ui): replace icomoon by mui icons in Extension manager
  package-lock.json
  package.json
  www/front_src/src/Extensions/ExtensionDeletePopup/index.js
  www/front_src/src/Extensions/ExtensionDetailsPopup/LoadingSkeleton.tsx
  www/front_src/src/Extensions/ExtensionDetailsPopup/index.js
  www/front_src/src/Extensions/ExtensionsHolder/index.js
  www/front_src/src/Extensions/TopFilters/index.js
  www/front_src/src/Extensions/Wrapper/index.js
  www/front_src/src/Extensions/index.js
  www/front_src/src/Navigation/Sidebar/Menu/menu.scss
  www/front_src/src/components/footer/footer.scss
  www/front_src/src/global-sass-files/_containers.scss
  www/front_src/src/global-sass-files/_grid.scss
  www/front_src/src/global-sass-files/_helpers.scss
  www/front_src/src/global-sass-files/_mixins.scss
  www/front_src/src/global-sass-files/_variables.scss
  www/front_src/src/img/checkbox-buttons-stripe.png
  www/front_src/src/img/icons/administration.svg
  www/front_src/src/img/icons/aside-menu-arrows.png
  www/front_src/src/img/icons/aside-menu-toggle-arrow.png
  www/front_src/src/img/icons/config.svg
  www/front_src/src/img/icons/copy.svg
  www/front_src/src/img/icons/home.svg
  www/front_src/src/img/icons/host.svg
  www/front_src/src/img/icons/icon-administration.svg
  www/front_src/src/img/icons/icon-configuration.svg
  www/front_src/src/img/icons/icon-copied.svg
  www/front_src/src/img/icons/icon-copy.svg
  www/front_src/src/img/icons/icon-error-message.png
  www/front_src/src/img/icons/icon-full-screen.png
  www/front_src/src/img/icons/icon-monitoring.svg
  www/front_src/src/img/icons/icon-reporting.svg
  www/front_src/src/img/icons/monitoring.svg
  www/front_src/src/img/icons/poller.svg
  www/front_src/src/img/icons/reporting.svg
  www/front_src/src/img/icons/services.svg
  www/front_src/src/img/icons/submenu-arrows-stripe.png
  www/front_src/src/img/radio-buttons-stripe.png
  www/front_src/src/route-maps/reactRoutes.js
Labels: area/ui

#10136 feat(Product Adoption): revert commit
  cron/centAcl.php
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.ihtml
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/help.php
  www/install/createTables.sql
  www/install/php/Update-21.10.0-beta.1.php
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
Labels: area/backend

#10144 fix(branch): fix conflict on develop
  cron/centAcl.php
  www/include/configuration/configObject/contact/formContact.php
  www/install/php/Update-21.10.0-beta.1.php
Labels: area/backend

#10145 fix(downtime): fix downtime set with fr locale
  www/include/monitoring/downtime/AddDowntime.php
Labels: area/backend

#10138 feat(Product Adoption): revert commit
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.ihtml
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/help.php
  www/install/createTables.sql
  www/install/php/Update-20.10.10.php
  www/install/php/Update-20.10.12.php
Labels: area/backend

#10121 feat(user profile) add feature-swith for one click export button
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
Labels: area/backend

#10137 feat(Product Adoption): revert commit
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.ihtml
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/help.php
  www/install/createTables.sql
  www/install/php/Update-21.04.4.php
  www/install/php/Update-21.04.6.php
Labels: area/backend

#10129 fix(upgrade): increment php upgrade version 20.04
  www/install/php/Update-20.04.18.php
  www/install/php/Update-20.04.19.php
Labels: area/backend

#10066 fix(kb): $templates array must be returned in reverse order
  www/class/centreon-knowledge/ProceduresProxy.class.php
Labels: kind/enhancement, status/in-backlog, area/knowledge-base, area/backend

#10140 feat(Platform Adoption): Integrate Pendo to Centreon
  doc/API/centreon-api-v21.10.yaml
  src/Centreon/Application/Controller/UserController.php
  www/front_src/public/index.html
  www/include/core/footer/footerPart.php
Labels: area/backend

#10123 fix(UI): When closing popup apply current filter
  www/front_src/src/Resources/Filter/Criterias/index.tsx
Labels: area/ui

#10156 deliver package before docker creation for develop branches
  Jenkinsfile
Labels: area-ci

#10157 fix(myAccount): SQL error fixed on update contact
  www/include/Administration/myAccount/DB-Func.php
Labels: area/backend

#10148 fix(upgrade): cast value for count
  www/install/php/Update-21.10.0-beta.1.php
Labels: area/backend

#10149 fix(style): Coding style develop
  www/include/core/footer/footerPart.php
Labels: area/backend

#10126 fix(UI/Graph): Improve performance on graphs
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useMousePosition.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/RegularLine.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui, need-assignee

#10164 fix(conf/host) fix enable/disable action anchor
  www/include/configuration/configObject/host/listHost.php
Labels: area/backend

#10153 fix(pollers) fix check-all enable/disable buttons, buttons alignment
  www/Themes/Centreon-2/style.css
  www/include/configuration/configServers/listServers.ihtml
Labels: area/backend

#10026 fix(clapi): downtime duration is not mandatory for fixed downtimes
  www/class/centreon-clapi/centreonDowntime.class.php
Labels: pr/internal-ps, area/backend, php

#10152 enh(UI): Clear filter by one click on close icon into search/filter bar
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#10142 Fix(UI): Fix negative Y scale and values
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
Labels: area/ui

#10198 chore(deps): update centreon-test-lib version
  Jenkinsfile
  composer.lock
Labels: area/backend

#10167 fix(TopCounter): redirect top counter to status detail pages
  package-lock.json
  www/front_src/src/App.tsx
  www/front_src/src/Header/Clock/index.tsx
  www/front_src/src/Header/StatusCounter/Host/index.test.tsx
  www/front_src/src/Header/StatusCounter/Host/index.tsx
  www/front_src/src/Header/StatusCounter/Service/index.test.tsx
  www/front_src/src/Header/StatusCounter/Service/index.tsx
  www/front_src/src/Header/StatusCounter/getResourcesUrl.ts
  www/front_src/src/Header/StatusCounter/index.tsx
  www/front_src/src/Header/header.scss
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/pollerMenu/index.js
  www/front_src/src/Header/userMenu/index.js
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/components/header/hostMenu/index.js
  www/front_src/src/components/header/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.js
  www/front_src/src/declaration.d.ts
  www/front_src/src/route-components/legacyRoute/index.js
Labels: area/ui

#10204 chore(libs): update phpunit
  composer.lock
Labels: area/backend

#10208 enh(ci): Fix reference build 20.10 for issue recording
  Jenkinsfile
Labels: area-ci

#10207 enh(ci): Fix reference build used for issue recording
  Jenkinsfile
Labels: area-ci

#10161 fix(conf) check if contact's notifications are enabled when exporting…
  www/class/config-generate/contact.class.php
Labels: area/backend

#10196 Mon 10852 add tls common name on broker config for 21.04.x
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/install/insertBaseConf.sql
  www/install/sql/centreon/Update-DB-21.04.2.sql
Labels: area/backend

#10195 Mon 10852 add tls common name on broker config
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/install/insertBaseConf.sql
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
Labels: area/backend

#10209 fix(test): fix clapi import/export acceptance test
  www/class/centreon-clapi/centreonContact.class.php
Labels: area/backend

#10163 enh(contact) Update the API endpoint returning the current user's settings
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#10218 fix(bam): retrieve constraints used by bam
  src/Centreon/Application/Validation/Constraints/RepositoryCallback.php
  src/Centreon/Application/Validation/Validator/RepositoryCallbackValidator.php
Labels: area/backend

#10197 enh(Filter): Allow Host group, Service group and Monitoring server criterions to be used using the name insteas of id
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/install/installBroker.sql
  www/install/sql/centstorage/Update-CSTG-21.10.0-beta.1.sql
Labels: area/ui

#10219 fix(sql): fix install of some monitoring tables
  www/install/installBroker.sql
Labels: area/backend

#10213 enh(UI): Add new tile with the last ok status
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v21.10.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui
