Repository centreon/centreon, pull requests merged in 2021-02, with the labels that each got.

#9443 fix(secu): delete empty getStats.php file
  www/include/Administration/corePerformance/getStats.php
Labels: area/backend, area/security

#9442 fix(secu): delete empty getStats.php file
  www/include/Administration/corePerformance/getStats.php
Labels: area/backend, area/security

#9444 fix(secu): delete empty getStats.php file
  www/include/Administration/corePerformance/getStats.php
Labels: area/backend, area/security

#9441 chore(build): update to php 7.3
  behat.yml
  composer.json
  composer.lock
  features/DowntimeDST/Recurrent.feature.old
  libinstall/functions
  tmpl/vardistrib/centos-7
  unattended.sh
  www/main.get.php
Labels: area/backend

#9429 fix(host category): Update Host category
  config/packages/prod/Centreon.yaml
  config/packages/serializer/Centreon/HostConfiguration.Host.yml
  config/packages/serializer/Centreon/HostConfiguration.Model.HostCategory.yml
  config/services.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/HostCategoryController.php
  src/Centreon/Domain/HostConfiguration/Exception/HostCategoryException.php
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Domain/HostConfiguration/HostCategoryService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryServiceInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryWriteRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Model/HostCategory.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostCategory/FindHostCategories.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostCategory/FindHostCategoriesResponse.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategory/HostCategoryV21.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategory/HostCategoryV21Factory.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostCategoryFactoryRdb.php
  src/EventSubscriber/CentreonEventSubscriber.php
  src/Security/SessionAPIAuthenticator.php
  src/Security/TokenAPIAuthenticator.php
  tests/php/Centreon/Domain/HostConfiguration/Exceptions/HostCategoryExceptionTest.php
  tests/php/Centreon/Domain/HostConfiguration/Model/HostCategoryTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategoriesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategoriesTest.php
Labels: area/backend

#9447 fix(downtime): manage daylight saving on recurrent downtimes
  behat.yml
  features/DowntimeDST/Recurrent.feature
  www/class/centreonDowntime.Broker.class.php
Labels: area/backend

#9448 fix(install): information printed during installation
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#9432 feat(engine) add heartbeat interval configuration
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  tests/clapi_export/clapi-configuration.txt
  www/class/config-generate/engine.class.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/configuration/configNagios/formNagios.ihtml
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/help.php
  www/install/createTables.sql
  www/install/php/Update-20.04.10.php
  www/install/php/Update-20.10.4.php
Labels: area/backend

#9451 fix(Resource-status/Downtime): Fix navigator default language
  package-lock.json
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
Labels: area/ui

#9454 fix(ui): restore status chip color in timeline
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
Labels: area/ui

#9456 enh(chore): Update eslintrc config to use new config from frontend-core
  .eslintrc.js
  package-lock.json
Labels: area/ui

#9458 fix(host template): Fix list of host template when SNMP version are not common
  src/Centreon/Domain/HostConfiguration/Model/HostTemplate.php
  tests/php/Centreon/Domain/HostConfiguration/Model/HostTemplateTest.php
Labels: area/backend

#9468 fix(clapi): retrieve default export order of acl menu relations
  www/class/centreon-clapi/centreonACLMenu.class.php
Labels: area/backend

#9466 fix(update) fix check column existence
  www/install/php/Update-20.04.10.php
  www/install/php/Update-20.10.4.php
Labels: area/backend

#9471 fix(clapi): remove inexistant platform_topology table
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#9473 fix(UI): Display confirmation popup before deleting an extension from the details modal
  www/front_src/src/route-components/administration/extensions/manager/index.js
Labels: area/ui

#9475 fix(sec): avoid xss injection in base uri
  www/index.php
Labels: area/backend, area/security

#9450 feat(Resource-status/Filter): implement dynamic filter display
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/storedDetails.ts
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/Criterias/default.ts
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/FilterLoadingSkeleton.tsx
  www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  www/front_src/src/Resources/Filter/Save/index.test.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/adapters.ts
  www/front_src/src/Resources/Filter/api/decoders.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/default.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Filter/useFilterModels.ts
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/models.ts
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9479 fix(downtime): cancel BA downtime from downtime page
  www/include/monitoring/downtime/listDowntime.php
Labels: area/backend

#9430 enh(UI): Add memoization on Resources Status
  package-lock.json
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/Fields/SelectFilter.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/memoizedComponent.tsx
Labels: area/ui

#9486 enh(UI): Replace loader component
  package-lock.json
  package.json
  www/front_src/src/App.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/MenuLoader.tsx
  www/front_src/src/components/PageLoader/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/header/hostMenu/index.js
  www/front_src/src/components/header/pollerMenu/index.js
  www/front_src/src/components/header/serviceStatusMenu/index.js
  www/front_src/src/components/header/userMenu/index.js
  www/front_src/src/components/loader/index.js
  www/front_src/src/components/loader/loader.scss
  www/front_src/src/components/mainRouter/index.js
  www/front_src/src/components/wizardFormInstallingStatus/index.js
  www/front_src/src/route-components/legacyRoute/index.js
Labels: area/ui

#9489 enh(Resource-status/Actions): Disables acknowledge action when resource has an OK or UP status
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#9491 fix(monitoring): handle macros in Resource Status
  src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  tests/api/features/ResourceMonitoring.feature
Labels: area/backend

#9494 fix(acl): fix query for non admin users on metric list
  www/api/class/centreon_metric.class.php
  www/include/Administration/parameters/ldap/form.php
Labels: area/backend

#9492 enh(reporting): optimize reporting dashboard for servicegroup
  www/include/common/javascript/Timeline/src/main/webapp/api/scripts/units.js
  www/include/common/javascript/Timeline/src/main/webapp/api/scripts/util/date-time.js
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/ajaxReporting_js.php
  www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/reporting/dashboard/viewServicesLog.php
Labels: area/backend

#9439 fix(Chart): Display metric legend with the same color as the corresponding curve
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/backend, area/chart

#9470 fix(host template): Taking into account the request parameters for the list of host template
  doc/API/centreon-api-v2.1.yaml
  src/Centreon/Application/Controller/HostTemplateController.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostTemplate/FindHostTemplates.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostTemplate/FindHostTemplatesResponse.php
  src/Centreon/Domain/Repository/RepositoryException.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostTemplateV21Factory.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostTemplateResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostTemplatesTest.php
  tests/php/Centreon/Infrastructure/HostConfiguration/API/Model/HostTemplateV21FactoryTest.php
Labels: area/backend

#9490 fix(Header/topCounter): Use new query parameter format for top counter resource-status links
  www/front_src/src/components/header/getResourcesUrl.ts
  www/front_src/src/components/header/hostMenu/index.test.tsx
  www/front_src/src/components/header/serviceStatusMenu/index.test.tsx
Labels: area/ui

#9485 feat(Resource-status/Filter): store expand parameter in url and storage & fix multi-select criterias display issues
  .gitignore
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/default.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/storage.ts
Labels: area/ui

#9481 fix(sec): Upgrade jQuery to 3.5.1 + ACL form toggle resources
  features/bootstrap/BrokerConfigurationContext.php
  www/include/common/javascript/jquery/jquery.js
  www/include/common/javascript/jquery/jquery.min.js
  www/include/options/accessLists/resourcesACL/formResourcesAccess.php
  www/lib/HTML/QuickForm/select2.php
Labels: area/security

#9482 fix(sec): Upgrade jQuery to 3.5.1 + ACL form toggle resources (before master)
  features/bootstrap/BrokerConfigurationContext.php
  www/include/common/javascript/jquery/jquery.js
  www/include/common/javascript/jquery/jquery.min.js
  www/include/options/accessLists/resourcesACL/formResourcesAccess.php
  www/lib/HTML/QuickForm/select2.php
Labels: area/security

#9508 fix(select2): avoid error 400 in hg & connector forms
  www/include/configuration/configObject/connector/formConnector.php
  www/include/configuration/configObject/hostgroup/formHostGroup.php
Labels: area/backend

#9484 fix(sec): avoid to display passwords in monitoring command line
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/HostConfiguration/Exception/HostCommandException.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/HostMacro.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/Macro/Interfaces/MacroInterface.php
  src/Centreon/Domain/Monitoring/CommandLineTrait.php
  src/Centreon/Domain/Monitoring/Exception/MonitoringServiceException.php
  src/Centreon/Domain/Monitoring/Interfaces/MonitoringServiceInterface.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Domain/ServiceConfiguration/Exception/ServiceCommandException.php
  src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationServiceInterface.php
  src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
  src/Centreon/Domain/ServiceConfiguration/ServiceMacro.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/CommandLineTraitTest.php
  tests/php/Centreon/Domain/Monitoring/MonitoringServiceTest.php
Labels: area/backend

#9516 enh(resource): handle monitoring server name in resource status
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9522 enh(chore): update copyrigth on login page
  www/include/core/login/template/login.ihtml
Labels: area/backend

#9523 enh(chore): update copyrigth on login page
  www/include/core/login/template/login.ihtml
Labels: area/backend

#9526 fix(monitoring): replace properly snmp macro values in command line
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
Labels: area/backend

#9504 feat(widgets): add regex filtering to widget compare field
  www/class/centreonUtils.class.php
  www/class/centreonWidget/Params/Compare.class.php
Labels: area/backend

#9529 fix(web): Adapt jQuery syntax to steps install folder
  www/install/step_upgrade/step5.php
  www/install/steps/templates/content.tpl
  www/install/steps/templates/install.tpl
  www/install/steps/templates/step3.tpl
  www/install/steps/templates/step4.tpl
  www/install/steps/templates/step5.tpl
  www/install/steps/templates/step6.tpl
  www/install/steps/templates/step7.tpl
  www/install/steps/templates/step8.tpl
  www/install/steps/templates/step9.tpl
Labels: area/backend
