Repository centreon/centreon, pull requests merged in 2021-12, with the labels that each got.

#10449 chore(apache): optimize apache configuration
  libinstall/functions
Labels: area/backend

#10441 enh(Resource Status/Filter): Add new status type filter
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  doc/API/centreon-api-v22.04.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/Criterias/default.ts
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, area/backend

#8299 Typos in log messages
  cron/centreon-backup.pl
Labels: status/needs-attention, area/backup, kind/fix, pr/internal-ps

#10447 enh(Topology): Add authentication page to the topology
  doc/API/centreon-api-v22.04.yaml
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-22.04.0-beta.1.sql
Labels: area/backend

#10452 fix(UI): Performane chart are not displayed reliably on Firefox
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#10459 fix(UI) : Remove graph unit displayed twice in rs and add metric's unit in Tooltip
  www/class/centreonGraphNg.class.php
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/include/views/graphs/javascript/centreon-graph.js
Labels: area/ui

#10464 MON-11738 refresh menus when enabling export conf btn
  www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#10466 enh(UI): Share Jotai context to modules
  www/front_src/src/Provider/index.tsx
  www/front_src/src/index.js
Labels: area/ui

#10465 Fix(tests): Fix UI tests
  www/front_src/src/Resources/Filter/Save/index.test.tsx
Labels: area/ui

#10435 enh(ui) : improved form in hostgroup and servicegroup reporting dashboards
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
Labels: area/backend

#10461 Mon 11698 update export reload conf for hostdisco
  config/packages/Centreon.yaml
  src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryFile.php
  src/Security/Domain/Authentication/Model/LocalProvider.php
  www/include/configuration/configGenerate/xml/generateFiles.php
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend

#10473 fix(chore): dependabot pipeline failure
  .github/workflows/dependabot_jira.yml
Labels: area/security, area-ci

#10442 fix(ui) : kept timeperiod selection ater refresh
  features/bootstrap/AutologinOptionsContext.php
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
Labels: area/backend

#10469 fix(export): export the contact template that was no longer exported with the contact
  www/class/config-generate/contact.class.php
Labels: area/backend

#10483 fix(ci): fix checkout of centreon-build
  Jenkinsfile
Labels: area-ci

#10488 chore(core): Fix centreon-frontend breaking changes
  package-lock.json
  package.json
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/useLoadDetails.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/api/index.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/useLoadDetails.ts
Labels: area/ui

#9506 NumberRows data is of a different type
  www/class/centreonDB.class.php
Labels: area/backend

#10494 fix(sql): retrieve contact_js_effects to avoid mbi generation failure
  tests/clapi_export/clapi-configuration.txt
  www/install/createTables.sql
  www/install/php/Update-21.10.2.php
Labels: area/backend

#10493 fix(session): update properly session last reload to avoid disconnect
  www/class/centreonSession.class.php
Labels: area/backend

#10484 fix(ui) : add default value to host groups and service groups
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/common-Func.php
Labels: area/backend

#10485 enh(UI): Add The Watch to the footer
  www/front_src/src/App.tsx
  www/front_src/src/Footer/Copyright.tsx
  www/front_src/src/Footer/Links.tsx
  www/front_src/src/Footer/index.tsx
  www/front_src/src/components/footer/footer.scss
  www/front_src/src/components/footer/index.js
Labels: area/ui

#10503 Fix infinite loop to get selectable criterias
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/filterAtoms.ts
Labels: area/ui

#10489 fix(resource): return instance information for metaservice
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
Labels: area/backend

#10504 fix(performances): issue when coming from Resource Status
  www/include/views/graphs/graphs.html
  www/include/views/graphs/graphs.php
Labels: area/backend

#10505 enh(tests): remove tests already done on centreon-engine
  behat.yml
  features/FirstNotificationDelay.feature
  features/RecoveryNotificationDelay.feature
  features/bootstrap/FirstNotificationDelayContext.php
  features/bootstrap/RecoveryNotificationDelayContext.php
Labels: area/backend

#10474 enh(UI): Refactoring Poller menu to Typescript
  www/front_src/src/Header/PollerMenu/ExportConfiguration/api/endpoints.ts
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.test.tsx
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Header/PollerMenu/PollerStatusIcon/index.tsx
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/PollerMenu/models.ts
  www/front_src/src/Header/PollerMenu/translatedLabels.ts
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/pollerMenu/index.js
  www/front_src/src/Header/pollerMenu/translatedLabels.ts
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
Labels: area/ui

#10478 fix(broker) : update broker retry interval default value and description (22.04)
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  www/include/configuration/configCentreonBroker/help.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10499 fix(broker) : update broker retry interval default value and description (21.10)
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  www/include/configuration/configCentreonBroker/help.php
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.2.php
Labels: area/backend

#10472 fix(log) : deleted old logger configuration (22.04)
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerBroker.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerModule.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerRrd.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBrokerInfo.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConnectionConfigurationService.php
  tests/clapi_export/clapi-configuration.txt
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonCentbrokerCfg.class.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10500 fix(log) : deleted old logger configuration (21.10)
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerBroker.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerModule.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerRrd.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBrokerInfo.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConnectionConfigurationService.php
  tests/clapi_export/clapi-configuration.txt
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonCentbrokerCfg.class.php
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.3.php
Labels: area/backend

#10501 fix(log) : deleted old logger configuration (21.04)
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerBroker.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerModule.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/LoggerRrd.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBrokerInfo.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConnectionConfigurationService.php
  tests/clapi_export/clapi-configuration.txt
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonCentbrokerCfg.class.php
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.11.php
Labels: area/backend

#10490 enh(UI): Import critical components lazily
  www/front_src/src/App.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/userMenu/index.js
  www/front_src/src/Resources/Actions/GlobalActionsSkeleton.tsx
  www/front_src/src/Resources/Actions/ResourceActionsSkeleton.tsx
  www/front_src/src/Resources/Actions/index.tsx
  www/front_src/src/Resources/Details/LoadingSkeleton.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/mouseTimeValueAtoms.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/components/MenuLoader.tsx
Labels: area/ui

#10495 enh(stats) : add exception for modules statistics (22.04)
  www/class/centreonStatsModules.class.php
  www/class/exceptions/StatisticException.php
Labels: area/backend

#10498 fix(resource): check name existance before updating filter
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Filter/FilterService.php
  tests/php/Centreon/Domain/Filter/FilterServiceTest.php
Labels: area/backend

#10516 enh(API): add default_page to current user parameters
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Menu/Model/Page.php
Labels: area/backend

#10453 [Administration] Define Security Policy for password
  Jenkinsfile
  composer.json
  composer.lock
  features/Clapi.feature
  features/bootstrap/AclAccessGroupsContext.php
  features/bootstrap/ClapiContext.php
  features/bootstrap/ContactConfigurationContext.php
  features/bootstrap/ControlLoginContext.php
  features/bootstrap/CustomViewsContext.php
  features/bootstrap/ModifyDefaultPageConnectionContext.php
  features/bootstrap/NonAdminContactCreationContext.php
  features/bootstrap/RestApiContext.php
  features/bootstrap/SpecialCharactersInContactContext.php
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lib/Centreon/Object/Contact/Contact.php
  puppeteer-script.js
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/CentreonLegacy/Core/Utils/Utils.php
  symfony.lock
  tests/clapi_export/clapi-configuration.txt
  tests/e2e/cypress/fixtures/users/admin.json
  tests/rest_api/rest_api.postman_environment.json
  www/class/CentreonLDAPAdmin.class.php
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreon-clapi/centreonContact.class.php
  www/class/centreonAuth.class.php
  www/class/centreonContact.class.php
  www/class/centreonDBStatement.class.php
  www/class/centreonLDAP.class.php
  www/class/centreonUser.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/ldap.php
  www/include/common/javascript/keygen.js
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.ihtml
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/formContactLight.ihtml
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.8.php
  www/install/php/Update-22.04.0-beta.1.php
  www/install/steps/process/process_step5.php
Labels: area/backend

#10522 enh(API): Interfaces for find web versions use case
  config/packages/Centreon.yaml
  config/packages/security.yaml
  config/routes/Centreon/platform.yaml
  doc/API/centreon-api-v22.04.yaml
  src/Core/Application/Platform/Service/PlatformVersionServiceInterface.php
  src/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersions.php
  src/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersionsPresenterInterface.php
  src/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersionsResponse.php
  src/Core/Infrastructure/Platform/Api/FindWebVersions/FindWebVersionsController.php
  tests/php/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersionsPresenterFake.php
  tests/php/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersionsTest.php
Labels: area/backend

#10519 enh(API): Interfaces for find security policy use case
  config/packages/Centreon.yaml
  config/routes/Centreon/security/security_policy.yaml
  src/Core/Application/Security/Repository/ReadSecurityPolicyRepositoryInterface.php
  src/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicy.php
  src/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicyPresenterInterface.php
  src/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicyResponse.php
  src/Core/Domain/Security/Model/SecurityPolicy.php
  src/Core/Infrastructure/Security/Api/FindSecurityPolicy/FindSecurityPolicyController.php
  tests/php/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicyPresenterFake.php
  tests/php/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicyTest.php
  tests/php/Core/Domain/Security/Model/SecurityPolicyTest.php
Labels: area/backend

#10525 enh(API): Interfaces for logout session use case
  config/routes/Centreon/security/authentication.yaml
  doc/API/centreon-api-v22.04.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Application/Security/Repository/WriteSessionRepositoryInterface.php
  src/Core/Application/Security/Service/TokenServiceInterface.php
  src/Core/Application/Security/UseCase/LogoutSession/LogoutSession.php
  src/Core/Application/Security/UseCase/LogoutSession/LogoutSessionRequest.php
  src/Core/Infrastructure/Security/Api/LogoutSession/LogoutSessionController.php
  tests/php/Core/Infrastructure/Security/Api/LogoutSession/LogoutSessionControllerTest.php
Labels: area/backend

#10515 enh(phpstan) : fix phpstan errors in centreon/src (part 1)
  composer.json
  composer.lock
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/DowntimeController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/DataRepresenter/Topology/NavigationList.php
  src/Centreon/Domain/Authentication/UseCase/Authenticate.php
  src/Centreon/Domain/Downtime/DowntimeService.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Entity/EntityCreator.php
  src/Centreon/Domain/Entity/Image.php
  src/Centreon/Domain/Entity/Task.php
  src/Centreon/Domain/Gorgone/Response.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/HostMacroService.php
  src/Centreon/Domain/Monitoring/MonitoringService.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/PlatformInformation/UseCase/V20/UpdatePartiallyPlatformInformation.php
  src/Centreon/Domain/PlatformTopology/Model/PlatformPending.php
  src/Centreon/Domain/PlatformTopology/Model/PlatformRegistered.php
  src/Centreon/Domain/Repository/ViewImgRepository.php
  src/Centreon/Domain/RequestParameters/RequestParameters.php
  src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
  src/Centreon/Infrastructure/Gorgone/CommandRepositoryAPI.php
  src/Centreon/Infrastructure/Gorgone/ResponseRepositoryAPI.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  src/CentreonUser/Application/Webservice/TimeperiodWebservice.php
  src/CentreonUser/Domain/Repository/ContactRepository.php
  src/CentreonUser/Domain/Repository/TimeperiodRepository.php
  src/CentreonUser/Tests/Application/Webservice/TimeperiodWebserviceTest.php
  src/CentreonUser/Tests/Domain/Repository/ContactRepositoryTest.php
  src/CentreonUser/Tests/Domain/Repository/TimeperiodRepositoryTest.php
  src/CentreonUser/Tests/ServiceProviderTest.php
  src/Kernel.php
  tests/php/Centreon/Domain/Monitoring/MonitoringServiceTest.php
Labels: area/backend

#10496 enh(resource): apply new architecture to host detail
  config/packages/Centreon.yaml
  config/routes/Centreon/monitoring_resource.yaml
  doc/API/ResourceHostDetail.yaml
  doc/API/centreon-api-v22.04.yaml
  phpstan.neon
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Domain/Log/LoggerTrait.php
  src/Core/Application/Common/UseCase/ErrorResponse.php
  src/Core/Application/Common/UseCase/NotFoundResponse.php
  src/Core/Application/Common/UseCase/PresenterInterface.php
  src/Core/Application/Common/UseCase/ResponseStatusInterface.php
  src/Core/Application/RealTime/Repository/ReadAcknowledgementRepositoryInterface.php
  src/Core/Application/RealTime/Repository/ReadDowntimeRepositoryInterface.php
  src/Core/Application/RealTime/Repository/ReadHostRepositoryInterface.php
  src/Core/Application/RealTime/Repository/ReadHostgroupRepositoryInterface.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHost.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHostPresenterInterface.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHostResponse.php
  src/Core/Application/RealTime/UseCase/FindHost/HostNotFoundResponse.php
  src/Core/Domain/RealTime/Model/Acknowledgement.php
  src/Core/Domain/RealTime/Model/Downtime.php
  src/Core/Domain/RealTime/Model/Host.php
  src/Core/Domain/RealTime/Model/HostStatus.php
  src/Core/Domain/RealTime/Model/Hostgroup.php
  src/Core/Domain/RealTime/Model/Icon.php
  src/Core/Domain/RealTime/Model/Status.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
  src/Core/Infrastructure/Common/Presenter/PresenterFormatterInterface.php
  src/Core/Infrastructure/Common/Repository/DbFactoryUtilitiesTrait.php
  src/Core/Infrastructure/RealTime/Api/FindHost/FindHostController.php
  src/Core/Infrastructure/RealTime/Api/FindHost/FindHostPresenter.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/HostHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/HypermediaProviderInterface.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/HypermediaProviderTrait.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/HypermediaService.php
  src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbAcknowledgementFactory.php
  src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbReadAcknowledgementRepository.php
  src/Core/Infrastructure/RealTime/Repository/Downtime/DbDowntimeFactory.php
  src/Core/Infrastructure/RealTime/Repository/Downtime/DbReadDowntimeRepository.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostStatusFactory.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
  src/Core/Infrastructure/RealTime/Repository/Hostgroup/DbHostgroupFactory.php
  src/Core/Infrastructure/RealTime/Repository/Hostgroup/DbReadHostgroupRepository.php
  src/Core/Infrastructure/RealTime/Repository/Icon/DbIconFactory.php
  tests/php/Core/Application/RealTime/UseCase/FindHost/FindHostPresenterStub.php
  tests/php/Core/Application/RealTime/UseCase/FindHost/FindHostTest.php
  tests/php/Core/Domain/RealTime/Model/HostTest.php
Labels: area/backend

#10527 enh(API): Implements Infrastructure layer for find security policy use case.
  src/Core/Application/Security/Repository/ReadSecurityPolicyRepositoryInterface.php
  src/Core/Infrastructure/Security/Repository/DbReadSecurityPolicyRepository.php
  src/Core/Infrastructure/Security/Repository/DbSecurityPolicyFactory.php
  tests/php/Core/Application/Security/UseCase/FindSecurityPolicy/FindSecurityPolicyTest.php
  tests/php/Core/Infrastructure/Security/Repository/DbSecurityPolicyFactoryTest.php
Labels: area/backend

#10526 fix(UI): Fix style to display poller details row in sub menu
  www/front_src/src/Header/PollerMenu/index.tsx
Labels: area/ui
