Repository centreon/centreon, pull requests merged in 2021-04, with the labels that each got.

#9637 fix(doc): openApi correction
  doc/API/centreon-api-v2.1.yaml
Labels: area/backend

#9636 fix(doc): openApi correction
  doc/API/centreon-api-v2.yaml
Labels: area/backend

#9622 fix(security): Sanitize and refactor contact creation and update request.
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#9621 fix(massive change) keep same variable data select structure from beginning to end
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend

#9585 feat(UI): Display metrics values in legend
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/Icon.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/Marker.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9590 feat(engine) remove aggressive_host_checking option from engine configuration
  features/bootstrap/ConfigurationWarningsContext.php
  features/bootstrap/GeneratePollerContext.php
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-config/centreonMainCfg.class.php
  www/class/config-generate-remote/Engine.php
  www/class/config-generate/engine.class.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/configuration/configNagios/comments.php
  www/include/configuration/configNagios/formNagios.ihtml
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/help.php
  www/install/createTables.sql
  www/install/php/Update-21.04.0-beta.1.php
  www/install/var/baseconf/centreon-engine.sql
Labels: area/backend

#9587 fix(security) sanitize notification dependency forms
  www/include/configuration/configObject/host_dependency/DB-Func.php
  www/include/configuration/configObject/hostgroup_dependency/DB-Func.php
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
  www/include/configuration/configObject/service_dependency/DB-Func.php
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
Labels: area/backend

#9645 fix(Resource-status): Various fixes
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Listing/columns/Checks.tsx
  www/front_src/src/Resources/Listing/columns/Notification.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9650 fix(form) check if a mandatory input is empty after sanitize.
  www/include/common/common-Func.php
  www/include/configuration/configObject/host_dependency/formHostDependency.php
  www/include/configuration/configObject/hostgroup_dependency/formHostGroupDependency.php
  www/include/configuration/configObject/service_dependency/formServiceDependency.php
  www/include/configuration/configObject/servicegroup_dependency/formServiceGroupDependency.php
Labels: area/backend

#9649 fix(SQL): Modify index_data.id type.
  www/install/createTablesCentstorage.sql
Labels: area/backend

#9651 fix(bug): fix sanitize string correctly
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#9615 enh(Graphs): Move graph options to Graph header
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#9617 enh(UI): Display Min, Max and Avg in legend
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9626 enh(UI): Limit timeline requests on graph and align export button
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui

#9646 feat(Resource-status): Add metaservice Resource
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Actions/Resource/SubmitStatus/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/SelectableResourceName.tsx
  www/front_src/src/Resources/Details/tabs/Details/ServiceCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/Metrics.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/api/decoders.ts
  www/front_src/src/Resources/Details/tabs/Metrics/api/index.ts
  www/front_src/src/Resources/Details/tabs/Metrics/index.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/models.ts
  www/front_src/src/Resources/Details/tabs/OutputInformation.tsx
  www/front_src/src/Resources/Details/tabs/Services/List.tsx
  www/front_src/src/Resources/Details/tabs/Services/Listing.tsx
  www/front_src/src/Resources/Details/tabs/Services/LoadingSkeleton.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Listing/columns/Resource.tsx
  www/front_src/src/Resources/Listing/columns/Severity.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/ShortTypeChip.tsx
  www/front_src/src/Resources/decoders.ts
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/Resources/truncate.ts
Labels: area/ui

#9655 fix(Resource-status): Fix layout on Safari and improve actions wrapping behaviour
  www/front_src/src/Resources/Actions/Resource/ResourceActionButton.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#9658 enh(Resource-status/Details): Redirect to parent resource when clicked in Details header
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/SelectableResourceName.tsx
Labels: area/ui

#9659 fix(pollers): Remove use aggressive hosts checking
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
Labels: area/backend

#9660 enh(register script): enhance displaying of remote protocol
  bin/registerServerTopology.sh
Labels: area/backend

#9661 Fix(UI): Details panel header is broken when display a severity level
  www/front_src/src/Resources/Details/Header.tsx
Labels: area/ui

#9664 fix(doc) fix api doc monitoring-server
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
Labels: area/backend

#9662 fix(apiv1): manage pagination on metrics listing
  www/api/class/centreon_monitoring_metric.class.php
Labels: area/backend

#9654 Fix(Resource Status/Graph): fix multiple issues on performance graphs
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/LoadingSkeleton.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#9663 fix(secu): Check user ACL on extensions' XHR
  src/CentreonModule/Application/Webservice/CentreonModuleWebservice.php
Labels: area/backend

#9665 fix(sql): update virtual metrics and curves column type
  www/install/createTables.sql
Labels: area/backend

#9666 fix(resource): various fixes for meta access under ACL
  src/Centreon/Application/Controller/Monitoring/CommentController.php
  src/Centreon/Application/Controller/Monitoring/SubmitResultController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Monitoring/Comment/CommentService.php
  src/Centreon/Infrastructure/MetaServiceConfiguration/Repository/MetaServiceConfigurationRepositoryRDB.php
Labels: area/backend

#9668 enh(registration script): Improve displaying and check type.
  bin/registerServerTopology.sh
Labels: area/backend

#9669 fix(API): remove all children platform from remote after reconversion
  src/Centreon/Domain/RemoteServer/RemoteServerService.php
Labels: area/backend

#9667 chore(npm): Re-generate package-lock
  package-lock.json
Labels: area/ui

#9670 fix(log); fix upgrade log to 20.04.10
  www/install/php/Update-20.04.10.php
Labels: area/backend

#9672 fix(hostconfiguration): Fix bad id in host configuration repository
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#9676 fix(conf): Fix Fatal Error in conf import.
  www/class/config-generate-remote/PlatformTopology.php
Labels: area/backend

#9677 Fix(UI): Graph options are not updated directly
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui

#9678 fix(test): avoid watchdog test fail
  features/Broker.feature
  features/bootstrap/BrokerContext.php
Labels: area/backend

#9679 fix(config): Add missing default log_directory
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBroker.php
Labels: area/backend

#9671 enh(Resource-status/Panel): reduce tab height
  package-lock.json
  www/front_src/src/Resources/Details/index.tsx
Labels: area/ui

#9680 fix(notice) dont cast before empty check
  src/Centreon/Domain/Gorgone/ConfigurationLoader.php
Labels: area/backend

#9683 enh(api): add metrics information in performance endpoint
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  www/class/centreonGraphNg.class.php
Labels: area/backend

#9681 Fix(UI): Selected values are not translated
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
Labels: area/ui

#9682 fix(broker configuration): empty broker output
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: area/backend

#9684 fix(UI): min max avg is always 1
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/models.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
Labels: area/ui

#9644 fix(security) sanitize host input
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/host/formHost.php
Labels: area/backend

#9685 fix(registration): Correctly concatenate scheme and port for Remote Token request
  bin/registerServerTopology.sh
Labels: area/backend

#9686 fix(web): correct undefined variable
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
Labels: area/backend

#9688 fix(resource): only display comments that are not deleted
  src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
Labels: area/backend

#9689 fix(registration): fix scheme and port fort Central
  bin/registerServerTopology.sh
Labels: area/backend

#9691 Fix(UI): Wrong legend name in graph
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
Labels: area/ui

#9692 fix(chore): fix broker form
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: area/backend

#9693 chore(version): upgrade to 21.04.0-beta.2
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0-beta.2.php
Labels: area/backend

#9695 revert(chore): broker logs
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBroker.php
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/DB-Func.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: area/backend

#9696 fix(remote): correct check before query bind
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
Labels: area/backend

#9699 Fix(UI): Exporting graph to png displays unwanted data
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/Icon.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#9606 fix non UTF-8 chars breaking sonarQ analysis
  www/include/common/javascript/xslt.js
Labels: area/backend

#9698 Fix(UI): Switching resources with the graph tab open displays the previous one for a short while
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#9701 fix(Resource-status/Filter): Fix monitoring server critera selection
  package-lock.json
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
Labels: area/ui

#9703 fix(bug): improve URL parsing from template and node-address flag
  bin/registerServerTopology.sh
  bin/registerServerTopologyTemplate
Labels: area/backend

#9702 Fix(UI): Improve legend layout
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/Marker.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui

#9624 fix(security): Sanitize and refactor contact creation and update request
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#9706 fix(registration): fix wrong parse of network interfaces
  bin/registerServerTopology.sh
Labels: area/backend

#9704 enh(help) Updated the help tooltip for the "Maximum Service Check Spread" option
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  www/include/configuration/configNagios/help.php
Labels: area/backend

#9709 enh(UI): Remove tooltips and add time tick above the graph
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  setupTest.js
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useMousePosition.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Graph/Performance/useGraphIntersection.ts
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9712 fix(ui): Re-generate package-lock to fix UTC time formatting
  package-lock.json
Labels: area/ui

#9713 fix(poller form): unable to replace localhost with real IP
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#9714 fix(resource): avoid error on Meta Service details
  src/Centreon/Domain/Monitoring/ResourceService.php
Labels: area/backend

#9715 enh(menu): remove deprecated notif from menu
  src/Centreon/Domain/Entity/Topology.php
Labels: area/backend

#9716 chore(version): upgrade to 21.04.0
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0.php
Labels: area/backend

#9722 fix(upgrade): correct default value on alter table
  www/install/php/Update-20.10.6.php
Labels: area/backend

#9727 fix(api): Array to Recursive when parsing request
  src/Centreon/Domain/PlatformInformation/Model/PlatformInformationDtoValidator.php
Labels: area/backend

#9723 fix(Resource-status/Graph): Fix graph export to PNG on Safari and Firefox
  package-lock.json
  package.json
  webpack.config.js
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/exportToPng.ts
Labels: area/ui

#9600 enh(sql): rewrite recursive request
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
Labels: area/backend

#9728 fix(filters): migrate properly personal filters (sort)
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.1.php
Labels: area/backend

#9705 enh(purge): fix drop partitions
  www/class/centreonPurgeEngine.class.php
Labels: area/backend, kind/bug

#9608 fix(sec): check resource acl before apply external command
  Update-DB-2.8.27_to_2.8.28.sql
  www/api/class/centreon_monitoring_externalcmd.class.php
Labels: area/backend, area/security

#9718 fix(config) fix broker log config for remote
  www/class/config-generate/broker.class.php
Labels: area/backend

#9734 fix(ui): Modification for the Downtime translation in Timeline
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#9602 MON-6867: rewrite recursive request (20.10.x)
  src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
Labels: area/backend

#9720 fix(ui): Missing french translations into messages.po for Acknowledgement
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#9735 sec(graph-periods): secure post entries
  www/include/views/graphs/graph-periods.php
Labels: area/backend

#9736 sec(graph-periods): secure post entries
  www/include/views/graphs/graph-periods.php
Labels: area/backend

#9738 sec(graph-split): secure request entries
  www/include/views/graphs/graph-split.php
Labels: area/backend

#9740 sec(graph-split): secure data from request
  www/include/views/graphs/graph-split.php
Labels: area/backend

#9741 fix(webpack): Keep only relevant moment locales in the webpack bundle
  webpack.config.js
Labels: area/ui

#9733 enh(UI): Click anywhere on metric tile to hightlight or hide it
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
Labels: area/ui

#9737 Fix(UI): Services graph are positioned in a mess
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui

#9750 fix(graph): correct graph split query
  www/include/views/graphs/graph-split.php
Labels: area/backend

#9730 fix(secu): Sanitize SVG files
  bin/centreon-sanitize-images.php
  composer.json
  composer.lock
  symfony.lock
  www/class/centreonImageManager.php
  www/include/options/media/images/DB-Func.php
Labels: area/backend

#9751 fix(notification): correct undefined variable
  www/include/monitoring/status/Notifications/notifications.php
Labels: area/backend

#9725 chore(version): prepare 21.10 serie
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile
  package-lock.json
  package.json
  tests/end_to_end/cypress/build-docker-compose.js
  tests/end_to_end/package.json
  unattended.sh
  www/front_src/src/Resources/Details/storedDetails.ts
  www/front_src/src/Resources/Listing/ApiNotFoundMessage.tsx
  www/front_src/src/Resources/storage.ts
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.0-beta.1.php
Labels: area/backend

#9754 chore(libs): upgrade centreon-test-lib
  composer.lock
Labels: area/backend

#9721 Fix(UI): Reduce Listing freeze
  package-lock.json
  www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#9747 Fix(UI): Units are not properly formatted
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
Labels: area/ui

#9756 Fix(UI): Fix graphs disposition
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
Labels: area/ui

#9755 fix(chore): define db extension files as SQL
  sonar-project.properties
Labels: area/backend

#9731 feat(engine) update default data
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-config/centreonMainCfg.class.php
  www/install/var/baseconf/centreon-engine.sql
Labels: area/backend
