Repository centreon/centreon, pull requests merged in 2021-05, with the labels that each got.

#9749 fix(security): remove dead code and sanitize data in CentreonWorker
  src/CentreonRemote/Application/Clapi/CentreonWorker.php
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
Labels: area/backend

#9752 fix(host) fix XSS in the alias field of host
  www/include/configuration/configObject/host/listHost.php
Labels: area/backend, area/security

#9762 sec(curveTemplates): secure page
  www/include/views/componentTemplates/DB-Func.php
  www/include/views/componentTemplates/componentTemplates.php
  www/include/views/componentTemplates/formComponentTemplate.php
Labels: area/backend

#9768 chore(libs): upgrade centreon-test-lib to optimize acceptance tests
  composer.lock
Labels: area/backend

#9770 fix(componentTemplate): retrieve function from previous PR
  www/include/views/componentTemplates/DB-Func.php
Labels: area/backend

#9775 sec(componentTemplate): secure the page
  www/include/views/componentTemplates/DB-Func.php
  www/include/views/componentTemplates/componentTemplates.php
  www/include/views/componentTemplates/formComponentTemplate.php
Labels: area/backend

#9769 chore(broker configuration): remove unused broker's wizard related code
  tests/clapi_export/clapi-configuration.txt
  tests/rest_api/rest_api.postman_collection.json
  www/include/configuration/configCentreonBroker/wizard.ihtml
  www/include/configuration/configCentreonBroker/wizard.php
  www/include/configuration/configCentreonBroker/wizard/css/style.css
  www/include/configuration/configCentreonBroker/wizard/error.ihtml
  www/include/configuration/configCentreonBroker/wizard/finish.ihtml
  www/include/configuration/configCentreonBroker/wizard/save.php
  www/include/configuration/configCentreonBroker/wizard/step1.ihtml
  www/include/configuration/configCentreonBroker/wizard/step2.php
  www/include/configuration/configCentreonBroker/wizard/step2Function.php
  www/include/configuration/configCentreonBroker/wizard/step2_central.ihtml
  www/include/configuration/configCentreonBroker/wizard/step2_poller.ihtml
  www/include/configuration/configCentreonBroker/wizard_ajax.php
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-20.04.14.sql
  www/install/sql/centreon/Update-DB-20.10.8.sql
  www/install/sql/centreon/Update-DB-21.04.2.sql
Labels: area/backend

#9781 sec(export): secure hostgroup log export
  www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Labels: area/backend

#9784 sec(export): secure hostgroup log export
  www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Labels: area/backend

#9780 fix(security): Handle invalid parameters in trap search
  www/include/configuration/configObject/traps/listTraps.php
Labels: area/backend

#9785 fix(bug): remove broker wizard CSS
  www/include/core/header/htmlHeader.php
Labels: area/backend

#9787 sec(generateImage): secure code
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#9788 fix(test): reload instead of restart in watchdog generation test
  features/bootstrap/BrokerContext.php
Labels: area/backend

#9786 fix(security): sanitize request parameters
  www/api/class/centreon_configuration_broker.class.php
  www/include/configuration/configCentreonBroker/blockConfig.php
  www/include/configuration/configCentreonBroker/centreon-broker.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
Labels: area/backend

#9773 enh(ui): Tooltip and Detail panel display the last 24h (from now to previous 24h) on graph
  www/front_src/src/Resources/Listing/columns/Graph.tsx
Labels: area/ui

#9790 fix(apache): avoid 404 redirection on react routes
  libinstall/functions
Labels: area/backend

#9791 fix(security): sanitize request parameters 2.8.x
  www/include/configuration/configCentreonBroker/blockConfig.php
Labels: area/backend

#9778 fix(sec): upgrade to smarty 3
  GPL_LIB/smarty-plugins/function.eval.php
  composer.json
  composer.lock
  symfony.lock
  www/api/class/centreon_configuration_broker.class.php
  www/api/class/centreon_home_customview.class.php
  www/include/common/common-Func.php
  www/include/configuration/configObject/command/formArguments.php
  www/include/configuration/configObject/command/formMacros.php
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  www/include/core/header/header.php
  www/include/core/login/login.php
  www/include/monitoring/recurrentDowntime/templates/general.html
  www/include/monitoring/recurrentDowntime/templates/monthly_basis.html
  www/include/monitoring/recurrentDowntime/templates/specific_date.html
  www/include/monitoring/recurrentDowntime/templates/weekly_basis.html
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/index.php
  www/install/steps/functions.php
Labels: area/backend

#9568 enh(chore): update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: area/backend

#9794 fix(componentTemplate): issue with bindParams
  www/include/views/componentTemplates/DB-Func.php
Labels: area/backend

#9760 enh(ci): refactor jenkins pipeline
  Jenkinsfile
  sonar-project.properties
Labels: area/backend

#9796 fix(security): sanitize KB request parameters
  www/class/centreon-knowledge/ProceduresProxy.class.php
  www/include/configuration/configKnowledge/proxy/proxy.php
Labels: area/backend

#9797 fix(ci): fix jenkins parallel os steps on stable builds
  Jenkinsfile
Labels: area/backend

#9798 sec(generateImage): secure entries
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#9800 fix(install): installation failure fixed
  www/install/steps/functions.php
Labels: area/backend

#9799 fix(security): sanitize kb request parameters
  www/class/centreon-knowledge/procedures_Proxy.class.php
  www/include/configuration/configKnowledge/proxy/proxy.php
Labels: area/backend

#9804 enh(ci): run some acceptance tests when frontend is updated
  features/TopCounterPollers.feature
  features/TopCounterProfileMenu.feature
Labels: area/backend

#9792 Fix(UI): Increase the font size of timestamp
  www/front_src/src/Resources/Graph/Performance/index.tsx
Labels: area/ui

#9759 fix(statistics): allow to see broker stats for pollers
  www/include/Administration/brokerPerformance/brokerPerformance.php
Labels: area/administration, area/backend, kind/bug

#9767 enh(configuration): link meta host to localhost poller
  www/include/configuration/configObject/meta_service/DB-Func.php
  www/install/sql/centreon/Update-DB-20.10.8.sql
Labels: area/backend, area/configuration

#9809 enh(reporting): enhance reporting for services
  www/include/reporting/dashboard/ajaxReporting_js.php
  www/include/reporting/dashboard/xmlInformations/GetXmlService.php
Labels: area/backend

#9810 fix(npm): re-generate package-lock and fix ESLint
  package-lock.json
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/api/index.ts
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/SubmitStatus/api/index.ts
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Actions/useActions.ts
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/api/index.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useMousePosition.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Area.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/Y.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Context.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/Zone.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
  www/front_src/src/Resources/Graph/Performance/useGraphIntersection.ts
  www/front_src/src/Resources/Listing/api/index.ts
Labels: area/ui

#9818 fix(test): fix random fail on api monitoring server test
  tests/api/features/RealTimeMonitoringServer.feature
Labels: area/backend

#9777 enh(Resource-status/Details): Format command line to make it better readable
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.test.ts
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.ts
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
Labels: area/ui

#9821 fix(test): avoid random fail on acl acceptance tests
  features/AclAccessGroups.feature
  features/bootstrap/AclAccessGroupsContext.php
Labels: area/backend

#9823 enh(chore): do not assign reviewers on translation files
  .github/CODEOWNERS
Labels: area/backend, area/ui

#9819 enh(Resource-status/Filter): Change criterias to PopoverAutocomplete and add a filter summary
  package-lock.json
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.tsx
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Fields/SelectFilter.tsx
  www/front_src/src/Resources/Filter/SearchHelpTooltip.tsx
  www/front_src/src/Resources/Filter/Summary.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#9708 enh(sql): optimize purge of index_data table
  www/class/centreonPurgeEngine.class.php
Labels: area/backend

#9711 Mon-7153: bulk inserts index_data during config generation
  www/class/config-generate/generate.class.php
Labels: area/backend

#9707 enh(acl): avoid to always recalculate ACLs for BV
  cron/centAcl.php
Labels: area/backend

#9828 Enh(deps): Update dependencies
  package-lock.json
  package.json
Labels: area/ui

#9830 fix(sec): avoid sql injection in trap manufacturer listing and form
  www/include/configuration/configObject/traps-manufacturer/formMnftr.php
  www/include/configuration/configObject/traps-manufacturer/listMnftr.php
  www/include/configuration/configObject/traps-manufacturer/mnftr.php
Labels: area/backend

#9829 fix(sec): avoid sql injection in engine configuration listing and form
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/listNagios.php
  www/include/configuration/configNagios/nagios.php
Labels: area/backend

#9831 fix(sec): avoid sql injection in acl action listing and form
  www/include/options/accessLists/actionsACL/DB-Func.php
  www/include/options/accessLists/actionsACL/actionsConfig.php
  www/include/options/accessLists/actionsACL/formActionsAccess.php
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
Labels: area/backend

#9833 fix(sec): avoid sql injection in reload acl listing
  www/class/centreonMsg.class.php
  www/include/options/accessLists/reloadACL/reloadACL.php
Labels: area/backend

#9832 fix(sec): avoid sql injection in acl resources
  www/include/options/accessLists/resourcesACL/formResourcesAccess.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
  www/include/options/accessLists/resourcesACL/resourcesAccess.php
  www/include/options/accessLists/resourcesACL/showUsersAccess.php
Labels: area/backend

#9834 fix(csv_HostGroupLogs): fix sql search on session
  www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Labels: area/backend

#9835 fix(externalCommands): retrieve APIv1 external commands mechanism
  www/api/class/centreon_monitoring_externalcmd.class.php
  www/class/centreonExternalCommand.class.php
Labels: area/backend

#9837 fix(traps): correctly use bind token in query
  www/include/configuration/configObject/traps-manufacturer/listMnftr.php
Labels: area/backend

#9836 fix(csv_HostGroupLogs): fix variable naming
  www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Labels: area/backend

#9838 fix(downtime): host downtime cancellation fix for APIv2
  src/Centreon/Domain/Downtime/DowntimeService.php
Labels: area/backend

#9840 fix(downtime): host downtime cancellation fix for APIv2 on engineservice
  src/Centreon/Domain/Engine/EngineService.php
Labels: area/backend

#9841 fix(Resource-status/Details): Fix wrong command line display when single argument with multiple characters is given
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.ts
Labels: area/ui

#9839 enh(Resource-status/Details): Improve the display of Check and Flapping tiles
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/ChecksIcon.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Filter/FilterLoadingSkeleton.tsx
  www/front_src/src/Resources/Listing/columns/Checks.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9854 fix(conf/broker) Fixed saving broker configuration
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
Labels: area/backend

#9843 chore(node): Upgrade to node 16 and npm 7
  package-lock.json
  package.json
Labels: area/ui

#9852 enh(logger) Add a Logger trait to be usable in classes
  config/packages/prod/Centreon.yaml
  config/packages/prod/monolog.yaml
  src/Centreon/Domain/Log/LoggerTrait.php
Labels: area/backend

#9869 fix(update): insert module meta relation if exist
  www/install/php/Update-21.04.2.php
  www/install/sql/centreon/Update-DB-20.10.8.sql
Labels: area/backend

#9853 fix(ldap): fix manual import when many ldap users
  www/include/common/javascript/ContactAjaxLDAP/ajaxLdapSearch.js
Labels: area/backend

#9870 fix(Conf/Command) Sanitize command line
  www/include/configuration/configObject/command/listCommand.php
  www/include/configuration/configObject/command/minHelpCommand.php
Labels: area/backend, area/security

#9874 fix(update): insert module meta relation if exist
  www/install/php/Update-20.10.8.php
  www/install/sql/centreon/Update-DB-20.10.8.sql
Labels: area/backend

#9875 fix(update): insert module meta relation if exist
  www/install/php/Update-20.04.14.php
Labels: area/backend

#9876 fix(formDowntime): add possibility to delete timeperiods in reccurren…
  www/Themes/Centreon-2/jquery-ui/jquery-ui-centreon.css
  www/include/monitoring/recurrentDowntime/formDowntime.html
Labels: area/backend

#9880 fix(login): Use correct database name for api login
  src/Centreon/Infrastructure/Security/AuthenticationRepositoryRDB.php
  www/class/centreonDB.class.php
Labels: area/backend
