Repository centreon/centreon, pull requests merged in 2021-03, with the labels that each got.

#9514 enh(Resource-status/Listing): Improve Listing responsiveness
  package-lock.json
  package.json
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
Labels: area/ui

#9520 enh(host): Add severities to host entity
  config/packages/serializer/Centreon/HostConfiguration.Host.yml
  config/packages/serializer/Centreon/HostConfiguration.Model.HostSeverity.yml
  src/Centreon/Domain/HostConfiguration/Exception/HostSeverityException.php
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Domain/HostConfiguration/HostSeverityService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostGroup/HostGroupReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostSeverity/HostSeverityReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostSeverity/HostSeverityServiceInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostSeverityRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostGroupFactoryRdb.php
Labels: area/backend

#9521 enh(chore): update about page
  www/include/Administration/about/about.php
Labels: area/backend

#9536 fix(eventLogs): export logs fixed when filtered on output
  www/include/eventLogs/xml/data.php
Labels: area/backend

#9534 fix(Resource-status/Graph/Services): Don’t display service graph tooltips when outside of the panel viewport
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
Labels: area/ui

#9543 enh(UI): Date display is centered on detail panel graph's tooltip
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
Labels: area/ui

#9533 fix(filters): adapt filter to new format
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend

#9538 fix(chore): set default value if unable to compare versions
  www/install/step_upgrade/step3.php
Labels: area/backend

#9537 feat(Resource-status/Listing): Implement action URL & notes label
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Listing/columns/Url.tsx
  www/front_src/src/Resources/Listing/columns/Url/Action.tsx
  www/front_src/src/Resources/Listing/columns/Url/Notes.tsx
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9547 fix(monitoring): Use new query parameter format for resource status l…
  www/include/monitoring/status/Hosts/host.php
  www/include/monitoring/status/Services/service.php
Labels: area/backend

#9545 chore(composer): add dependencies to enable Symfony Profiler
  composer.json
  composer.lock
  src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
Labels: area/backend

#9511 feat(install): Add apache configuration for /authentication match
  libinstall/functions
Labels: area/backend

#9550 [20.10.x] fix(Resource-status/Listing): Use the new URL path
  .eslintrc.js
  www/front_src/src/Resources/Listing/columns/Url.tsx
Labels: area/ui

#9554 fix(Resource-status/Details): Fix display more status information
  www/front_src/src/Resources/Details/tabs/Details/ExpandableCard.tsx
Labels: area/ui

#9561 fix(engine) revert postpone option
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  tests/clapi_export/clapi-configuration.txt
  www/class/config-generate/engine.class.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/configuration/configNagios/formNagios.ihtml
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/help.php
  www/install/createTables.sql
  www/install/php/Update-20.04.11.php
  www/install/php/Update-20.10.5.php
Labels: area/backend

#9564 fix(sec): avoid to display macro password in specific case
  src/Centreon/Domain/Monitoring/CommandLineTrait.php
  tests/php/Centreon/Domain/Monitoring/CommandLineTraitTest.php
Labels: area/backend

#9565 fix(platformtopology): enable to add a remote server
  bin/registerServerTopology.sh
  config/json_validator/latest/Centreon/PlatformInformation/Update.json
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Domain/PlatformInformation/Model/PlatformInformation.php
  src/Centreon/Domain/PlatformInformation/Model/PlatformInformationFactory.php
  src/Centreon/Domain/RemoteServer/RemoteServerService.php
Labels: area/backend

#9563 [20.04.x] fix(secu): Fix npm vulnerabilities
  package-lock.json
  package.json
  webpack.config.prod.js
  www/front_src/src/BreadcrumbTrail/Breadcrumb.tsx
  www/front_src/src/BreadcrumbTrail/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/clipboard.ts
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/api/adapters.ts
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/api/index.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/dateTime.ts
  www/front_src/src/Resources/hasDefinedValues.ts
  www/front_src/src/Resources/icons/Downtime.tsx
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/form-fields/hoc.js
Labels: area/ui

#9549 enh(UI): Improve annotations over graphs
  package-lock.json
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Area.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Line.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Area/Downtime.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/EventAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Acknowledgement.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Line/Comments.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Context.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
Labels: area/ui, need-assignee

#9567 [19.10.x] fix(secu): Update (production) vulnerable packages
  package-lock.json
  package.json
Labels: area/ui

#9562 enh(UI): Implement buttons to quickly pick timeframe
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriodSelect/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
Labels: area/ui

#9555 feat(Resource-status/Filter): Add monitoring server criteria
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  config/routes/Centreon/monitoring/real_time_monitoring_servers.yaml
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  src/Centreon/Application/Controller/Monitoring/RealTimeMonitoringServerController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Domain/MonitoringServer/Exception/RealTimeMonitoringServerException.php
  src/Centreon/Domain/MonitoringServer/Interfaces/RealTimeMonitoringServerRepositoryInterface.php
  src/Centreon/Domain/MonitoringServer/Interfaces/RealTimeMonitoringServerServiceInterface.php
  src/Centreon/Domain/MonitoringServer/Model/RealTimeMonitoringServer.php
  src/Centreon/Domain/MonitoringServer/RealTimeMonitoringServerService.php
  src/Centreon/Domain/MonitoringServer/UseCase/RealTimeMonitoringServer/FindRealTimeMonitoringServers.php
  src/Centreon/Domain/MonitoringServer/UseCase/RealTimeMonitoringServer/FindRealTimeMonitoringServersResponse.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  src/Centreon/Infrastructure/MonitoringServer/API/Model/RealTimeMonitoringServer.php
  src/Centreon/Infrastructure/MonitoringServer/API/Model/RealTimeMonitoringServerFactory.php
  src/Centreon/Infrastructure/MonitoringServer/Repository/Model/RealTimeMonitoringServerFactoryRdb.php
  src/Centreon/Infrastructure/MonitoringServer/Repository/RealTimeMonitoringServerRepositoryRDB.php
  tests/api/Context/RealTimeMonitoringServerContext.php
  tests/api/behat.yml
  tests/api/features/RealTimeMonitoringServer.feature
  tests/php/Centreon/Domain/MonitoringServer/Model/RealTimeMonitoringServerTest.php
  tests/php/Centreon/Domain/MonitoringServer/UseCase/FindRealTimeMonitoringServersResponseTest.php
  tests/php/Centreon/Domain/MonitoringServer/UseCase/FindRealTimeMonitoringServersTest.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/Criterias/default.ts
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
Labels: area/backend, area/ui

#9556 fix(Resource-status/Listing): Fix display of Resources with the same ID
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceSeverity.yml
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  package-lock.json
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceSeverity.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Services/List.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/models.ts
Labels: area/backend, area/ui

#9579 fix(ui): Adapt graph scale for b/s unit
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
Labels: area/ui

#9583 fix(sec): fix check command setter name
  src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: area/backend

#9541 enh(meta): use select2 for metric selection in META form
  www/api/class/centreon_metric.class.php
  www/api/class/centreon_monitoring_metric.class.php
  www/include/configuration/configObject/meta_service/formMetaService.php
Labels: area/backend

#9513 enh(broker) add configuration for broker logs
  tests/clapi_export/clapi-configuration.txt
  www/class/centreonConfigCentreonBroker.php
  www/class/config-generate/broker.class.php
  www/include/configuration/configCentreonBroker/DB-Func.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0-beta.1.php
  www/install/var/baseconf/centreon-broker.sql
Labels: area/backend

#9589 fix(ui): fix monitoring server multiselect
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
Labels: area/ui

#9584 [20.10.x] fix(secu): Update vulnerable packages
  package-lock.json
  package.json
  www/front_src/src/App.tsx
  www/front_src/src/BreadcrumbTrail/Breadcrumb.tsx
  www/front_src/src/BreadcrumbTrail/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/api/index.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Shortcuts/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/api/index.ts
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Filter/api/endpoint.ts
  www/front_src/src/Resources/Filter/api/index.ts
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/api/index.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/dateTime.ts
  www/front_src/src/Resources/hasDefinedValues.ts
  www/front_src/src/Resources/icons/Downtime.tsx
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
Labels: area/ui

#9580 fix(secu): Update vulnerable npm packages
  package-lock.json
  package.json
Labels: area/ui

#9570 enh(chore): integrate sonarQube dev edition
  Jenkinsfile
  sonar-project.properties
Labels: area/backend, area/security, build/jenkins

#9601 fix(chore): 19.10.x job
  Jenkinsfile
  sonar-project.properties
Labels: area/backend, area/security, build/jenkins

#9581 fix(ui): Missing french translations dt details panel
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Acknowledgement.tsx
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/Downtime.tsx
Labels: area/ui

#9599 enh(ui): manage uuid and optimize resources queries
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  config/packages/serializer/Centreon/Monitoring.ResourceSeverity.yml
  doc/API/centreon-api-v2.yaml
  package-lock.json
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceSeverity.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/models.ts
Labels: area/backend, area/ui

#9604 fix(register script): Fix wrong variables usage
  bin/registerServerTopology.sh
Labels: area/backend

#9605 fix(sql) fix log_max_size default value
  www/include/configuration/configCentreonBroker/formCentreonBroker.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend

#9610 chore(documentation): add missing routes in doc API 2.1
  doc/API/centreon-api-v2.1.yaml
Labels: area/backend

#9612 fix(sec): use openssl_random_pseudo_bytes to generate csrf token
  www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Labels: area/backend, area/security

#9614 fix(sec): check properly api configuration access
  src/Centreon/Domain/Contact/Contact.php
Labels: area/backend, area/security

#9571 feat(UI): Add datetime pickers
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui, need-assignee

#9578 fix(UI): Annotation are not updated when the time period is changed
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Area.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Line.tsx
Labels: area/ui, need-assignee

#9609 fix(service) fix total services in listing
  www/include/configuration/configObject/service/listServiceByHost.php
Labels: area/backend

#9618 MON-6759: fix sql problem breaking poller listing
  www/api/class/centreon_monitoring_poller.class.php
Labels: area/backend

#9594 enh(Resource-status): Improve details panel compactness
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/CompactStatusChip.tsx
  www/front_src/src/Resources/Details/tabs/Details/Card.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/ActiveLine.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DetailsLine.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/ExpandableCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/StateCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/OutputInformation.tsx
  www/front_src/src/Resources/Details/tabs/Services/List.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
Labels: area/ui

#9625 fix(test): return code 2 instead of 1 in api tests
  tests/api/features/Acknowledgement.feature
  tests/api/features/MonitoringTimeline.feature
Labels: area/backend

#9623 fix(timezone): update moment-timezone to manage new timezones
  features/bootstrap/ConfigurationWarningsContext.php
  features/bootstrap/DowntimeDSTContext.php
  features/bootstrap/GeneratePollerContext.php
  www/include/common/javascript/moment-timezone-with-data.min.js
Labels: area/backend

#9630 chore(install): update version to 20.04.12
  www/install/insertBaseConf.sql
  www/install/php/Update-20.04.12.php
Labels: area/backend

#9631 chore(install): update to version 20.10.6
  www/install/insertBaseConf.sql
  www/install/php/Update-20.10.5.php
  www/install/php/Update-20.10.6.php
Labels: area/backend

#9628 fix(resources): add uuid to build uris
  src/Centreon/Application/Controller/MonitoringResourceController.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/backend

#9629 chore(install): update to version 19.10.22
  composer.json
  composer.lock
  doc/en/release_notes/centreon-19.10.rst
  doc/fr/release_notes/centreon-19.10.rst
  symfony.lock
  www/install/insertBaseConf.sql
  www/install/php/Update-19.10.22.php
Labels: area/backend

#9638 fix(upgrade) create cfg_centreonbroker_log
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend

#9641 fix(pollers): Fatal error when deleting a poller.
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#9633 fix(chore) move optimization config to webpack.config.prod
  webpack.config.js
  webpack.config.prod.js
Labels: area/ui

#9639 feat(Resource-status/Listing): Add new column and allow to re-order them
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/columns/Checks.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/Listing/columns/IconColumn.tsx
  www/front_src/src/Resources/Listing/columns/Notification.tsx
  www/front_src/src/Resources/Listing/columns/Parent.tsx
  www/front_src/src/Resources/Listing/columns/Resource.tsx
  www/front_src/src/Resources/Listing/columns/Severity.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/columns/Status.tsx
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/columns/storedColumnIds.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee
