Repository centreon/centreon, pull requests merged in 2021-01, with the labels that each got.

#9346 fix(clapi): Correction of RTACKNOWLEDGEMENT cancellation for services
  www/class/centreon-clapi/centreonRtAcknowledgement.class.php
Labels: area/backend

#9339 fix(customViews): avoid injection when adding a widget
  www/class/centreonWidget.class.php
  www/include/home/customViews/action.php
Labels: area/backend

#9343 fix(kb): fix mediawiki url to templates
  www/class/centreon-knowledge/ProceduresProxy.class.php
  www/class/centreon-knowledge/procedures.class.php
  www/class/centreon-knowledge/wikiApi.class.php
  www/class/centreonHost.class.php
  www/include/common/common-Func.php
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
  www/include/configuration/configKnowledge/proxy/proxy.php
  www/include/configuration/configKnowledge/templates/display.ihtml
Labels: area/backend

#9351 enh(api): Add API endpoint to list host categories
  composer.lock
  config/packages/prod/Centreon.yaml
  config/routes/Centreon/host_category.yaml
  doc/API/centreon-api-v2.1.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  ruleset.xml
  src/Centreon/Application/Controller/HostCategoryController.php
  src/Centreon/Domain/HostConfiguration/Exception/HostCategoryException.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategoryReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Model/HostCategory.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategories.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategoriesResponse.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostTemplates.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategoryV21.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategoryV21Factory.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostTemplateV21.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostCategoryFactoryRdb.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostTemplateFactoryRdb.php
  symfony.lock
  tests/api/Context/HostCategoryContext.php
  tests/api/behat.yml
  tests/api/features/HostCategory.feature
  tests/php/Centreon/Domain/HostConfiguration/Model/HostCategoryTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategoriesResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/FindHostCategoriesTest.php
Labels: area/backend

#9359 enh(resource-status/Graph): Enhance comment in performance graphs
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph/index.tsx
Labels: area/ui

#9357 feat(resource-status/Details): add Resource group chips to details
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/models.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9360 enh(resource-status/Graph): Improve exported graph image timestamp in title
  www/front_src/src/Resources/Details/tabs/Graph/exportToPng.ts
Labels: area/ui

#9364 fix(clapi): Fix CLAPI command to list all hosts acknowledgements #9332
  lib/Centreon/Object/Acknowledgement/RtAcknowledgement.php
Labels: area/backend

#9363 fix(secu): only return resources that you are allowed to see
  www/api/class/centreon_metric.class.php
  www/api/class/centreon_monitoring_externalcmd.class.php
  www/api/class/centreon_monitoring_poller.class.php
Labels: area/backend

#9338 fix(clapi) Import fails on password type macros
  lib/Centreon/Object/Object.php
  www/class/centreon-clapi/centreonHost.class.php
  www/class/centreon-clapi/centreonService.class.php
  www/install/createTables.sql
  www/install/php/Update-20.10.3.php
Labels: area/backend

#9366 fix(secu): check ACL rights when sending externalcommands
  www/api/class/centreon_monitoring_externalcmd.class.php
  www/class/centreonExternalCommand.class.php
Labels: area/backend

#9367 fix(mediawiki): manage properly mediawiki url of host templates
  www/class/centreon-knowledge/ProceduresProxy.class.php
Labels: area/backend

#9349 fix(ui/acl): ACL config menu subgroups align with parent
  www/include/common/javascript/tool.js
  www/include/options/accessLists/menusACL/formMenusAccess.ihtml
Labels: area/backend

#9355 enh(chore): Migrate to webpack 5
  .eslintrc.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  webpack.config.dev.js
  webpack.config.js
  www/front_src/src/App.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/Y.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines.tsx
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.test.ts
  www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
  www/front_src/src/Resources/Listing/columns/State/DetailsTable/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/Resources/models.ts
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/form-fields/CheckboxField.js
  www/front_src/src/components/form-fields/utils.js
Labels: area/ui, need-assignee

#9368 fix(clapi) Import fails on password type macros
  www/install/php/Update-19.10.19.php
  www/install/php/Update-20.04.9.php
Labels: area/backend

#9314 enh(platform topology): Registration script rework
  bin/registerServerTopology-Func.php
  bin/registerServerTopology.php
  bin/registerServerTopology.sh
  bin/registerServerTopologyTemplate
Labels: area/backend

#9365 fix(Resource-status/Details): Handle long resource name in details panel
  package-lock.json
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/ActiveLine.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DetailsLine.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: area/ui

#9375 fix(chore): fix CI job
  www/api/class/centreon_metric.class.php
Labels: area/backend

#9325 feat(Resource-status/Services): Display graphs in the Services details tab
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/NoResultsMessage.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Graph/models.ts
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/List.tsx
  www/front_src/src/Resources/Details/tabs/Services/Listing.tsx
  www/front_src/src/Resources/Details/tabs/Services/LoadingSkeleton.tsx
  www/front_src/src/Resources/Details/tabs/Services/api/decoders.ts
  www/front_src/src/Resources/Details/tabs/Services/api/index.ts
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/models.ts
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/exportToPng.ts
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/LoadingSkeleton.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriodSelect/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriodSelect/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9369 enh(api): allow user to retrieve only resources with graphs
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Labels: area/backend

#9385 chore(ci): use discoverGitReferenceBuild instead of manually set reference build
  Jenkinsfile
Labels: area/backend

#9388 Update the public key (1Y extension)
  SECURITY.md
Labels: area/backend

#9391 fix(Resource-status/Downtime): Fix infinite loading when setting empty downtime comment
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
Labels: area/ui

#9390 fix(Resource-status/Timeline): Fix timeline events date ordering
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
Labels: area/ui

#9393 fix(secu): bump version of handlebars to 4.7.6
  sonar-project.properties
  www/include/Administration/corePerformance/nagiosStats.html
  www/include/common/javascript/handlebars-v4.7.6.js
  www/include/views/graphs/graphs.html
Labels: area/backend

#9381 fix(API): Register Children Pollers while converting a central to remote
  bin/registerServerTopology.sh
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/PlatformController.php
  src/Centreon/Domain/PlatformInformation/PlatformInformationService.php
  src/Centreon/Domain/RemoteServer/Interfaces/RemoteServerServiceInterface.php
  src/Centreon/Domain/RemoteServer/RemoteServerService.php
  tests/api/features/PlatformInformation.feature
  tests/php/Centreon/Domain/PlatformInformation/PlatformInformationServiceTest.php
Labels: area/backend

#9383 fix(hostDetails): correct comments that were no longer displayed
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
Labels: area/backend

#9392 enh(perf): improve poller performance list for 20.04.x
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/listServers.php
Labels: area/backend

#9370 enh(downtimes): use gorgone for localhost poller
  www/class/centreonDowntime.Broker.class.php
Labels: area/backend

#9384 fix(Resource-status/Services): only fetch services with graph data when in graph mode and fix tooltip position
  package-lock.json
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/api/endpoint.ts
Labels: area/ui

#9382 feat(Resource-status/Details): implement panel resize
  package.json
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/storedDetails.ts
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/LoadingSkeleton.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Graph/Performance/Graph/Axes/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriodSelect/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/storage.ts
Labels: area/ui

#9399 fix(configuration): "Conf changed" yes is green instead of red
  www/include/configuration/configServers/listServers.php
Labels: area/backend

#9405 fix(Typing): fix typing error
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
Labels: area/ui

#9396 fea(api): Add API endpoint to list host groups
  config/packages/prod/Centreon.yaml
  config/routes/Centreon/configuration/host_group.yaml
  config/services.yaml
  doc/API/centreon-api-v2.1.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/Configuration/HostGroupController.php
  src/Centreon/Domain/HostConfiguration/Exception/HostGroupException.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostGroup/HostGroupReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Model/HostGroup.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostGroup/FindHostGroups.php
  src/Centreon/Domain/HostConfiguration/UseCase/V21/HostGroup/FindHostGroupsResponse.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostGroup/HostGroupV21.php
  src/Centreon/Infrastructure/HostConfiguration/API/Model/HostGroup/HostGroupV21Factory.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostGroupFactoryRdb.php
  tests/api/Context/HostGroupContext.php
  tests/api/behat.yml
  tests/api/features/HostGroup.feature
  tests/php/Centreon/Application/Controller/Configuration/HostGroupControllerTest.php
  tests/php/Centreon/Domain/HostConfiguration/Model/HostGroupTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/HostGroup/FindHostGroupsResponseTest.php
  tests/php/Centreon/Domain/HostConfiguration/UseCase/V21/HostGroup/FindHostGroupsTest.php
  tests/php/Centreon/Infrastructure/HostConfiguration/API/Model/HostGroupV21FactoryTest.php
  tests/php/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostGroupFactoryRdbTest.php
Labels: area/backend

#9372 fix(secu): sanitize host dashboard
  www/include/reporting/dashboard/common-Func.php
Labels: area/backend

#9406 fix(secu): sanitize host dashboard
  www/include/reporting/dashboard/common-Func.php
Labels: area/backend

#9374 enh(topCounter): services from host acked, in downtime not displayed
  www/api/class/centreon_topcounter.class.php
Labels: area/backend

#9394 fix(security): Sanitize ACL Resource parameters
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/options/accessLists/resourcesACL/DB-Func.php
Labels: area/backend

#9408 fix(security): Sanitize ACL Resource parameters
  lang/fr/LC_MESSAGES/messages.po
  www/include/options/accessLists/resourcesACL/DB-Func.php
Labels: area/backend

#9412 enh(lib): remove handlebarjs lib
  sonar-project.properties
  www/include/common/javascript/handlebars-v4.7.6.js
  www/include/views/graphs/graphs.html
Labels: area/backend

#9410 enh(topology): add platform pending state
  www/install/createTables.sql
  www/install/php/Update-20.10.4.php
Labels: area/backend

#9407 enh(Resource-status/Graph): optimize lisibility of the Graphs
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/Marker.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
Labels: area/ui, need-assignee

#9416 fix(Resource-status/Filter): Fix Filter overflow by wrapping the fields in case of resize
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  webpack.config.dev.js
  www/front_src/src/Resources/Filter/FilterLoadingSkeleton.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, need-assignee

#9404 chore(documentation): add missing property in platform/topology documentation
  doc/API/centreon-api-v2.1.yaml
  doc/API/centreon-api-v2.yaml
Labels: area/backend

#9417 fix(api): Correct misstypo in Broker Domain and config file
  config/packages/prod/Centreon.yaml
  src/Centreon/Infrastructure/Broker/BrokerRepositoryRDB.php
  tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#9413 fix(security) fix host status default data filter
  www/include/configuration/configObject/host/listHost.php
Labels: area/backend

#9422 fix(chore): correct step5 undefined variable
  www/install/step_upgrade/process/process_step5.php
Labels: area/backend

#9419 fix(host) Fixed creating host and service with a non-admin user
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/service/formService.php
Labels: area/backend

#9418 fix(host) Fixed creating host and service with a non-admin user
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/service/formService.php
Labels: area/backend

#9420 fix(ACL): sanitize name in testExistence
  www/include/options/accessLists/resourcesACL/DB-Func.php
  www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend

#9421 enh(ui): increase timeline density
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
Labels: area/ui

#9168 enh(security): Using the new algorithm to hide the password in the se…
  www/include/monitoring/objectDetails/common-func.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#9345 enh(partitioning): performance improvements
  cron/centreon-partitioning.php
  www/class/centreon-partition/partEngine.class.php
  www/class/centreonPurgeEngine.class.php
Labels: area/backend

#9425 fix(secu): avoid injection in LDAP form
  www/class/centreonDB.class.php
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/javascript/ldapJs.php
  www/include/Administration/parameters/ldap/ldap.php
  www/include/Administration/parameters/ldap/list.php
  www/include/Administration/parameters/parameters.php
Labels: area/backend, area/security

#9427 fix(secu): avoid injection in LDAP form
  www/include/Administration/parameters/ldap/form.php
Labels: area/backend, area/security

#9428 fix(sec): avoid to display already logged in users
  www/include/core/login/login.php
  www/include/core/login/template/login.ihtml
Labels: area/backend

#9414 fix(select2): do not fetch default data if id is not set
  www/lib/HTML/QuickForm/select2.php
Labels: area/backend

#9431 fix(secu): remove expired sessions more globally
  www/api/class/centreon_keepalive.class.php
  www/api/internal.php
  www/class/centreonSession.class.php
  www/class/centreonXMLBGRequest.class.php
  www/include/core/header/header.php
  www/include/monitoring/status/Notifications/notifications.php
  www/index.php
  www/main.get.php
Labels: area/backend

#9424 feat(engine) add postpone notification configuration
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  tests/clapi_export/clapi-configuration.txt
  www/class/config-generate/engine.class.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/configuration/configNagios/formNagios.ihtml
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/help.php
  www/install/createTables.sql
  www/install/php/Update-20.04.10.php
  www/install/php/Update-20.10.4.php
Labels: area/backend

#9353 fix(CLAPI) fix clapi dependency duplicate insertion
  www/class/centreon-clapi/centreonDependency.class.php
  www/install/createTables.sql
  www/install/php/Update-20.04.10.php
  www/install/php/Update-20.10.4.php
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend
