Repository centreon/centreon, pull requests merged in 2021-08, with the labels that each got.

#9991 enh(Resource-status/Filter): Revamp Filter
  jest.config.js
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/Groups.tsx
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  www/front_src/src/Resources/Filter/Criterias/CriteriasMultiSelect.tsx
  www/front_src/src/Resources/Filter/Criterias/default.ts
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Save/index.test.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/SearchHelpTooltip.tsx
  www/front_src/src/Resources/Filter/Summary.tsx
  www/front_src/src/Resources/Filter/default.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Filter/storedFilter.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/Zone.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/index.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/components/MenuLoader.tsx
Labels: area/ui

#10033 enh(authentication): add default password security policy
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.0-beta.1.php
  www/install/sql/centreon/Update-DB-21.04.2.sql
  www/install/steps/process/process_step5.php
  www/install/steps/templates/step5.tpl
Labels: area/backend

#10042 fix(CI): Allow to build a docker image with centos8 tag on QA branches
  Jenkinsfile
Labels: area-ci

#10045 enh(UI): Integrate cloud services to the global context
  package-lock.json
  webpack.config.dev.js
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Disacknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/SubmitStatus/index.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
Labels: area/ui

#9983 enh(UI): Revamp the timeline
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  setupTest.js
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#10054 Fix(i18n): Fix the "Downtime" translation
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#10046 feat(Resource-status/Filter): Add autocompletion to the search bar
  package-lock.json
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
Labels: area/ui, need-assignee

#10057 fix(sec): compare lazy and greedy patterns to confirm password section
  src/Centreon/Domain/Monitoring/CommandLineTrait.php
Labels: area/security, area/backend

#10055 fix(php): fail on error when upgrading php
  bin/migrate_php74.sh
Labels: area/backend

#10056 fix(php): fail on error when upgrading php
  bin/migrate_php73.sh
Labels: area/backend

#10072 fix(tests/e2e): Make Cypress fixture initialization more resilient
  Jenkinsfile
  config/packages/Centreon.yaml
  config/packages/monolog.yaml
  config/packages/test/Centreon.yaml
  config/packages/test/validator.yaml
  config/packages/test/web_profiler.yaml
  tests/e2e/cypress/integration/Resources-status/01-listing.feature
  tests/e2e/cypress/integration/Resources-status/01-listing/index.ts
  tests/e2e/cypress/integration/Resources-status/02-actions.feature
  tests/e2e/cypress/integration/common/index.ts
  tests/e2e/cypress/plugins/index.ts
  tests/e2e/cypress/support/centreonData.ts
  tests/e2e/cypress/support/database.ts
  tests/e2e/cypress/support/index.ts
  www/api/class/centreon_results_acceptor.class.php
  www/api/class/centreon_submit_results.class.php
Labels: area/ui, area-ci

#10049 fix(platformTopology): fix IP assignement after fqdn resolve
  src/Centreon/Domain/PlatformTopology/Model/PlatformPending.php
Labels: area/backend

#10067 fix(forms) check key macroInput presence before foreach in form service
  www/include/configuration/configObject/service/formService.php
Labels: area/backend

#10068 enh(ci): adding QA branches as scheduled job
  Jenkinsfile
Labels: area-ci

#10075 enh(ci): play AT and IT only for reference, release and qa branches
  Jenkinsfile
  behat.yml
Labels: area/tests, area-ci

#10078 fix(test): adapt AT feature files listing
  Jenkinsfile
  behat.yml
Labels: area-ci

#10079 enh(ci): reintroduce api and e2e tests in PR
  Jenkinsfile
Labels: area/tests, area-ci

#10074 fix(form) remove php warning on host_register when sanitizing host fo…
  www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend
