Repository centreon/centreon, pull requests merged in 2021-11, with the labels that each got.

#10378 fix(login): fix login with custom uri
  www/include/core/login/template/login.ihtml
Labels: area/backend

#10377 fix(template) Delete the hard-coded name of the database
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#10325 fix(downtime): display only started downtimes
  www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
Labels: area/backend

#10358 Set Broker retry interval to 15 sec
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgCentreonBrokerInfo.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/InputBroker.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/InputRrd.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputModuleMaster.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputPerfdata.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputRrd.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputRrdMaster.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputSqlMaster.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/InputFlowOnePeerRetention.php
  www/install/var/baseconf/centreon-broker.sql
Labels: area/backend

#10077 enh(core) gitignore
  .gitignore
  www/img/icones/16x16/Thumbs.db
Labels: area-ci

#10362 enh(logs) : Display current ressource in admin logs details
  www/include/Administration/configChangelog/viewLogsDetails.ihtml
Labels: area/backend

#10348 fix(account): Removed animation effect option in account parameters
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreonUser.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configGenerate/xml/generateFiles.php
  www/include/configuration/configGenerate/xml/moveFiles.php
  www/include/configuration/configGenerate/xml/restartPollers.php
  www/include/monitoring/status/Common/commonJS.php
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-21.10.1.sql
Labels: area/backend

#10390 fix(authentication): correct PHP error
  www/class/centreonAuth.SSO.class.php
Labels: area/authentication, area/backend

#10347 fix(login): Fixed quotation mark
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#10389 fix(typology) : display submenu subsections for non admin users
  src/Centreon/Domain/Repository/TopologyRepository.php
Labels: area/backend

#10392 MON-6255-acl-dont-compute-when-services-added-by-clapi
  www/class/centreon-clapi/centreonObject.class.php
  www/class/centreon-clapi/centreonService.class.php
Labels: area/backend

#10396 chore(ci): update qa branch of serie 21.10
  Jenkinsfile
Labels: area/backend

#10400 Fix(Poller): Poller adding issue fixed
  src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
Labels: area/backend

#10401 MON-11557-broker-conf-form-issues
  www/class/centreonConfigCentreonBroker.php
Labels: area/backend

#10395 chore(version): prepare 22.04 serie
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile
  doc/API/centreon-api-v22.04.yaml
  features/CentreonModuleAPI.feature
  features/assets/centreon-test.conf.php
  features/bootstrap/CentreonModuleAPIContext.php
  features/bootstrap/ModuleContext.php
  tests/api/features/HostCategory.feature
  tests/api/features/HostGroup.feature
  tests/api/features/HostSeverity.feature
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10410 fix(sql): manage compatibility with mysql 8 on login
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#10412 fix(eventview): handle properties not in serializing groups
  src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
Labels: area/backend

#10411 fix(UI): Graph tooltip does not always dismiss
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/Listing/columns/HoverChip.tsx
Labels: area/ui

#10379 fix(ldap) : fixed issue with LDAP configuration ID
  www/class/centreon-clapi/CentreonLDAPContactRelation.class.php
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreon-clapi/centreonContact.class.php
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#10417 enh(parameters): handle default downtime options
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Application/Controller/Administration/ParametersController.php
Labels: area/backend

#10402 MON-11046-tooltips-not-working
  www/lib/wz_tooltip/wz_tooltip.js
Labels: area/backend

#10380 enh(context): Integrate Jotai to Resources Status Details
  package-lock.json
  package.json
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Context/index.ts
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/detailsAtoms.ts
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/storedDetails.ts
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/detailsCardsAtom.ts
  www/front_src/src/Resources/Details/tabs/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/storedDetailsCards.ts
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/Metrics.tsx
  www/front_src/src/Resources/Details/tabs/Metrics/index.tsx
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Details/tabs/Services/index.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Details/useLoadDetails.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/graphOptionsAtoms.ts
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Area.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/Line.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Annotation/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/EventAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Annotations/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Context.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/MetricsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/annotationsAtoms.ts
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/mouseTimeValueAtoms.ts
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/AnchorPoint/RegularAnchorPoint.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/AnchorPoint/StackedAnchorPoint.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/StackedLines.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/timePeriodAtoms.ts
  www/front_src/src/Resources/Graph/Performance/TimePeriods/useTimePeriod.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/memoizedComponent.tsx
Labels: area/ui

#10421 fix(ci): fix api doc version in jenkinsfile
  Jenkinsfile
Labels: area/backend

#10419 enh(resource): handle state type as filter criteria
  config/packages/serializer/Centreon/Monitoring.ResourceFilter.yml
  config/packages/validator/validation.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceFilter.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/MetaServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
Labels: area/backend

#10422 fix(conf): disable mod security rule 200003
  libinstall/functions
Labels: area/backend

#10434 fix(resource): correctly filter by hostgroup and servicegroup
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
Labels: area/backend

#10408 enh(Context): Integrate jotai about User context data
  package-lock.json
  www/front_src/src/App.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.test.tsx
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/Resource/aclQuery.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Filter/filterAtoms.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
  www/front_src/src/index.js
Labels: area/ui

#10432 fix(command/ack) Fix of the acknowledgment concerning the "sticky" option
  src/Centreon/Domain/Engine/EngineService.php
Labels: area/backend

#10399 enh(CI): Integrate Lighthouse CI
  .gitignore
  Jenkinsfile
  lighthouserc.js
  package-lock.json
  package.json
  puppeteer-script.js
Labels: area/ui

#10415 enh(UI): Filter popin improvement
  www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
Labels: area/ui

#10420 Mon 5666 anomaly service not renamed in graph listing
  www/class/config-generate/generate.class.php
Labels: area/backend

#10431 enh(UI): Add state_type as new criteria
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/Criterias/default.ts
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.test.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Filter/models.ts
  www/front_src/src/Resources/Listing/api/endpoint.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/testUtils/index.ts
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#10440 fix(resource): error when filering with ACL on monitoring server name
  src/Centreon/Infrastructure/MonitoringServer/Repository/RealTimeMonitoringServerRepositoryRDB.php
Labels: area/backend

#10428 enh(ui): improve performance of host reporting page (replace select by select2)
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/viewHostLog.php
Labels: area/backend

#10423 fix(trap): fix trap export when a service is linked to multiple hosts
  bin/generateSqlLite
Labels: area/backend

#9973 MON-11758 fix conf export fail because of centreontrapd
  lib/perl/centreon/script/centreontrapd.pm
Labels: area/backend

#10444 fix(api): allow api authentication even if reach frontend is disabled
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/AuthenticationController.php
  src/Centreon/Domain/Authentication/Exception/AuthenticationException.php
  src/Centreon/Domain/Authentication/UseCase/Authenticate.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/ContactService.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Domain/Contact/Interfaces/ContactServiceInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Security/Domain/Authentication/Model/LocalProvider.php
  tests/api/features/Authentication.feature
  tests/php/Centreon/Application/Controller/AuthenticationControllerTest.php
  tests/php/Centreon/Domain/Authentication/UseCase/AuthenticateTest.php
  www/Themes/Centreon-2/login.css
  www/class/centreonAuth.SSO.class.php
  www/class/centreonAuth.class.php
  www/class/centreonLog.class.php
  www/include/core/login/login.php
  www/include/core/login/processLogin.php
  www/include/core/login/template/login.ihtml
Labels: area/backend

#10446 enh(debug): add debug when user is not found during authentication
  src/Centreon/Domain/Authentication/UseCase/Authenticate.php
Labels: area/backend

#10456 fix(ui) : Display pie chart in host reporting
  www/include/reporting/dashboard/template/viewHostLog.ihtml
Labels: area/backend
