Repository centreon/centreon, pull requests merged in 2021-06, with the labels that each got.

#9849 fix(ui): Handle case when Note URL is empty but Note is defined
  www/front_src/src/Resources/Listing/columns/Url/Action.tsx
  www/front_src/src/Resources/Listing/columns/Url/Notes.tsx
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
Labels: area/ui

#9888 enh(resource): return NULL for next_check when service is passive
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/HostProvider.php
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
Labels: area/backend

#9899 chore(version): upgrade to 21.04.3
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.3.php
Labels: area/backend

#9890 fix(API): Check topology ACL on platform topology endpoints
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Domain/Contact/Contact.php
  tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
Labels: area/backend

#9903 fix(security): sanitize value before unserialize in centreonutils
  www/class/centreonUtils.class.php
Labels: area/backend

#9881 fix(conf/notification) Fixed SQL injection in host notification configuration
  www/include/configuration/configObject/host_dependency/hostDependency.php
Labels: area/backend, area/security

#9886 fix(conf/meta service) Fixed SQL injection in meta service configuration
  www/include/configuration/configObject/meta_service/listMetric.php
  www/include/configuration/configObject/meta_service/metaService.php
  www/include/configuration/configObject/meta_service/metric.php
Labels: area/backend, area/security

#9892 fix(conf/notification) Fix SQL injection in meta service notification configuration
  www/include/configuration/configObject/metaservice_dependency/MetaServiceDependency.php
  www/include/configuration/configObject/metaservice_dependency/formMetaServiceDependency.php
Labels: area/backend, area/security

#9893 fix(conf/service) Fix SQL injection in service category configuration
  www/include/configuration/configObject/service_categories/formServiceCategories.php
  www/include/configuration/configObject/service_categories/serviceCategories.php
Labels: area/backend, area/security

#9894 fix(conf/service) Fix SQL injection in service notification configuration
  www/include/configuration/configObject/service_dependency/formServiceDependency.php
  www/include/configuration/configObject/service_dependency/serviceDependency.php
Labels: area/backend, area/security

#9910 fix(remote): re-add missing function
  src/CentreonRemote/Application/Webservice/CentreonTaskService.php
Labels: area/backend, area/remote-server

#9898 fix(conf/timeperiod) Fix SQL injection in timeperiod configuration
  www/include/configuration/configObject/timeperiod/formTimeperiod.php
  www/include/configuration/configObject/timeperiod/timeperiod.php
Labels: area/backend, area/security

#9882 fix(conf/notification) Fixed SQL injection in host group notification configuration
  www/include/configuration/configObject/hostgroup_dependency/hostGroupDependency.php
Labels: area/backend, area/security

#9859 feat(web): add security acknowledgement
  README.md
  SECURITY_ACK.md
  www/front_src/src/components/footer/index.js
  www/include/Administration/about/about.php
Labels: area/security

#9907 fix (conf/command) Fix SQL injection in command check configuration
  www/include/configuration/configObject/command/command.php
  www/include/configuration/configObject/command/formCommand.php
Labels: area/backend, area/security

#9922 fix(conf/command) Fix XSS in command help page
  www/include/configuration/configObject/command/minHelpCommand.php
Labels: area/backend, area/security

#9883 Fix(UI): Anchor points does not follow line path for stacked curves
  www/front_src/src/Resources/Graph/Performance/Graph/AnchorPoints/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/AnchorPoint/RegularAnchorPoint.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/AnchorPoint/StackedAnchorPoint.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/AnchorPoint/index.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/RegularLine.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/StackedLines.tsx
  www/front_src/src/Resources/Graph/Performance/Lines/index.tsx
Labels: area/ui

#9879 enh(ui): Add diverses formats option to export the graphs
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/exportToPng.ts
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9906 enh(ui): Add in same tile icon flapping and percent state change
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DetailsLine.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/PercentStateChangeCard.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: area/ui

#9930 enh(ACK): add reporters
  SECURITY_ACK.md
Labels: area-ci, area/security

#9932 enh(Resource-status/Actions): Display tooltip for not permitted actions
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  package.json
  www/front_src/src/Resources/Actions/Resource/ActionMenuItem.tsx
  www/front_src/src/Resources/Actions/Resource/ResourceActionButton.tsx
  www/front_src/src/Resources/Actions/Resource/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useGraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/useMousePosition.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/Context.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/TimeShiftZones/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useAnnotations.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/useMetricsValue.tsx
  www/front_src/src/Resources/Graph/Performance/useGraphIntersection.ts
  www/front_src/src/Resources/Listing/columns/Status.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#9944 fix(ldap): correct url for search submission
  www/include/Administration/parameters/ldap/list.php
Labels: area/backend

#9926 enh(conf/engine) Add method to find engine configuration by monitoring server
  src/Centreon/Domain/Engine/EngineConfiguration.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Exception/EngineConfigurationException.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
Labels: area/backend

#9917 enh(Resource-status/Linsting): Add new property shortLabel for colums in index
  package-lock.json
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
Labels: area/ui
