Repository centreon/centreon, pull requests merged in 2022-12, with the labels that each got.

#290 fix (event logs) : pagination issue on event log page
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#289 Enh(Widget Service Monitoring) : Increase performance
  widgets/centreon-widget-service-monitoring/service-monitoring/configs.xml
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
Labels: area/backend

#370 chore(js-config version): Update package js-config version to 23.4.4
  centreon/packages/js-config/package.json
Labels: auto-merge

#361 chore(publish): Refactor npm publish process (js-config)
  .github/actions/check-package-version/action.yml
  .github/actions/npm-publish/action.yml
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config.yml
  centreon/packages/js-config/package.json
Labels: area/ui

#388 chore(js-config version): Update package js-config version to 23.4.5
  centreon/packages/js-config/package.json
Labels: area/ui, automerge

#396 chore(ui-context version): Update package ui-context version to 23.4.1
  centreon/packages/ui-context/package.json
Labels: automerge

#395 chore(ui version): Update package ui version to 23.4.1
  centreon/packages/ui/package.json
Labels: automerge

#394 chore(js-config version): Update package js-config version to 23.4.6
  centreon/packages/js-config/package.json
Labels: automerge

#176 chore(core): Clean up dependencies and improve bundle size
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-context-automerge.yml
  .github/workflows/ui-context.yml
  .github/workflows/ui.yml
  .gitignore
  centreon/.gitignore
  centreon/lighthouse/package.json
  centreon/package.json
  centreon/packages/js-config/webpack/base/index.js
  centreon/packages/ui/jest.config.js
  centreon/packages/ui/package.json
  centreon/pnpm-lock.yaml
  centreon/tests/e2e/package.json
  centreon/www/front_src/.gitignore
  centreon/www/front_src/src/helpers/dynamicImport.js
  centreon/www/front_src/src/helpers/extras/global.js
  centreon/www/front_src/src/helpers/validators.js
Labels: area/ui

#403 chore(ui version): Update package ui version to 23.4.2
  centreon/packages/ui/package.json
Labels: automerge

#337 enh(UI): Improve input hiding in Form
  centreon/packages/ui/src/Form/Inputs/Autocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/Radio.tsx
  centreon/packages/ui/src/Form/Inputs/Switch.tsx
  centreon/packages/ui/src/Form/Inputs/Text.tsx
  centreon/packages/ui/src/Form/Inputs/index.tsx
  centreon/packages/ui/src/Form/storiesData.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-collapsible-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-custom-button-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-horizontal-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-loading-form-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-loading-form-with-groups-1-snap.png
Labels: area/ui

#407 chore(ui version): Update package ui version to 23.4.3
  centreon/packages/ui/package.json
Labels: automerge

#109 feat(UI): Add e2e Tests on Autologin Feature
  centreon/features/Autologin.feature
  centreon/features/AutologinOptions.feature
  centreon/packages/ui/src/Button/Icon/index.tsx
  centreon/packages/ui/src/Button/Save/index.tsx
  centreon/packages/ui/src/Form/FormButtons.tsx
  centreon/packages/ui/src/Form/Inputs/Radio.tsx
  centreon/packages/ui/src/Form/Inputs/Switch.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/index.tsx
  centreon/packages/ui/src/InputField/Select/index.tsx
  centreon/packages/ui/src/InputField/Text/index.tsx
  centreon/packages/ui/src/utils/getNormalizedId.ts
  centreon/tests/e2e/cypress/commons.ts
  centreon/tests/e2e/cypress/e2e/Autologin/01-autologin.feature
  centreon/tests/e2e/cypress/e2e/Autologin/01-autologin/index.ts
  centreon/tests/e2e/cypress/e2e/Autologin/common.ts
  centreon/tests/e2e/cypress/e2e/Local-authentication/01-local-authentication.feature
  centreon/tests/e2e/cypress/e2e/Local-authentication/01-local-authentication/index.ts
  centreon/tests/e2e/cypress/e2e/Local-authentication/common.ts
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/autologin-configuration-acl-user.json
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/local-authentication-acl-user-non-admin.json
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/local-authentication-acl-user.json
  centreon/tests/e2e/cypress/fixtures/users/user-non-admin-for-local-authentication.json
  centreon/tests/e2e/cypress/fixtures/users/user-non-admin-with-wrong-password.json
  centreon/tests/e2e/cypress/fixtures/users/user.json
  centreon/tests/e2e/cypress/support/Commands.ts
  centreon/tests/e2e/cypress/test.ts
  centreon/tests/e2e/package.json
  centreon/www/front_src/src/Authentication/Local/Form/Attempts.tsx
  centreon/www/front_src/src/Authentication/Local/Form/CaseButtons/index.tsx
  centreon/www/front_src/src/Authentication/Local/Form/inputs.tsx
  centreon/www/front_src/src/Authentication/Local/TimeInputs/TimeInput.tsx
  centreon/www/front_src/src/Authentication/Local/index.test.tsx
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: area/ui

#414 chore(ui version): Update package ui version to 23.4.4
  centreon/packages/ui/package.json
Labels: automerge

#314 feat: add a SqlConcatenator utility
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/src/Utility/SqlConcatenator.php
  centreon/tests/php/Utility/SqlConcatenatorTest.php
Labels: area/backend

#338 feat: add a SqlConcatenator utility
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/src/Utility/SqlConcatenator.php
  centreon/tests/php/Utility/SqlConcatenatorTest.php
Labels: area/backend

#341 fix(build): Dissociate the test renderer file from the main file
  .github/workflows/web.yml
  centreon/.gitignore
  centreon/junit.xml
  centreon/package.json
  centreon/packages/ui/src/index.ts
  centreon/www/front_src/src/App/index.tsx
  centreon/www/front_src/src/Authentication/Local/TimeInputs/index.test.tsx
  centreon/www/front_src/src/Authentication/Local/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/WebSSO/index.test.tsx
  centreon/www/front_src/src/Header/PollerMenu/ExportConfiguration/index.test.tsx
  centreon/www/front_src/src/Header/RessourceStatusCounter/Host/index.test.tsx
  centreon/www/front_src/src/Header/RessourceStatusCounter/Service/index.test.tsx
  centreon/www/front_src/src/Header/UserMenu/index.test.tsx
  centreon/www/front_src/src/Login/index.test.tsx
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/ResetPassword/index.test.tsx
  centreon/www/front_src/src/Resources/Actions/index.test.tsx
  centreon/www/front_src/src/Resources/Details/index.test.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/index.test.tsx
  centreon/www/front_src/src/Resources/Filter/Save/index.test.tsx
  centreon/www/front_src/src/Resources/Filter/index.test.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.test.tsx
  centreon/www/front_src/src/Resources/Listing/index.test.tsx
  centreon/www/front_src/src/components/ReactRouter/index.test.tsx
Labels: area/ui

#135 feat(behat): Add Tests for Contact Groups
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ConfigurationContactsGroups.feature
Labels: area/backend

#454 fix(e2e): Fix local authentication random fails
  .github/actions/cypress-e2e-testing/action.yml
  centreon/tests/e2e/cypress/e2e/Local-authentication/01-local-authentication/index.ts
  centreon/tests/e2e/package.json
Labels: area/ui

#248 fix(security): Sanitized queries in the list of meta service
  centreon/www/include/configuration/configObject/meta_service/listMetaService.php
Labels: area/backend

#241 fix(security): Sanitize queries in the list of service groups
  centreon/www/include/configuration/configObject/servicegroup/listServiceGroup.php
Labels: area/backend

#274 fix(security): Fix path transversal to display images in configuration
  centreon/www/include/common/getHiddenImage.php
Labels: area/backend

#249 fix(security): Sanitize queries in the list of trap groups
  centreon/www/include/configuration/configObject/traps-groups/listGroups.php
Labels: area/backend

#462 fix(build): Remove useless swc plugin
  centreon/package.json
  centreon/packages/js-config/webpack/base/index.js
  centreon/pnpm-lock.yaml
Labels: area/ui

#342 fix(conf) fix broker conf export and form translation
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Labels: area/backend

#465 fix(conf) fix broker conf export and form translation (#342)
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Labels: area/backend

#224 enh(CI): Add action to publish beta packages
  .github/actions/check-package-version/action.yml
  .github/actions/clean-up-npm-tag/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/actions/publish-npm/action.yml
  .github/workflows/js-config-merge.yml
  .github/workflows/js-config.yml
  .github/workflows/ui-context-merge.yml
  .github/workflows/ui-context.yml
  .github/workflows/ui-merge.yml
  .github/workflows/ui.yml
  centreon/packages/js-config/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
Labels: area/ui

#311 fix (Resources/useDateTimePicker): Some months are missing ,some days are duplicates in the calendar
  centreon/cypress/plugins/index.ts
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-April-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-April-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-August-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-August-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-December-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-December-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-February-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-February-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-January-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-January-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-July-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-July-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-June-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-June-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-March-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-March-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-May-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-May-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-November-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-November-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-October-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-October-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-September-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-September-when-clicking-on-Previous month.snap.png
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  centreon/www/front_src/src/Resources/index.cypress.spec.tsx
  centreon/www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#511 chore(ui-context version): Update package ui-context version to 23.4.4-MON-fix-stable-npm-publish.0
  centreon/packages/ui-context/package.json
Labels: automerge

#513 chore(ui version): Update package ui version to 23.4.7-MON-fix-stable-npm-publish.0
  centreon/packages/ui/package.json
Labels: automerge

#515 chore(ui version): Update package ui version to 23.4.7-MON-fix-stable-npm-publish.1
  centreon/packages/ui/package.json
Labels: automerge

#507 Fix(security): vulnerabilities in common-Func.php
  centreon/www/include/common/common-Func.php
Labels: area/backend

#504 Fix(upgrade): Field 'app_key' doesn't have a default value QUERY : INSERT INTO remote_servers
  centreon/www/install/php/Update-22.04.8.php
Labels: area/backend

#239 Fix(security): Sanitize and binding queries
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend

#450 enh(Resources/AnomalyDetection): Refactor out Anomaly detection code in Resource status in order to cleanup and add tests
  centreon/.gitignore
  centreon/cypress/fixtures/resources/anomalyDetectionDetails.json
  centreon/cypress/fixtures/resources/anomalyDetectionPerformanceGraph.json
  centreon/cypress/fixtures/resources/resourceListing.json
  centreon/cypress/fixtures/resources/resourceListingWithAnomalyDetectionType.json
  centreon/cypress/fixtures/resources/updatedAnomalyDetectionDetails.json
  centreon/cypress/fixtures/resources/userFilter.json
  centreon/cypress/support/commands.tsx
  centreon/cypress/support/component-index.html
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Global -- displays resources of type anomaly-detection when  filters of anomaly detection are checked and search button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Global -- displays the Anomaly detection configuration modal when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Global -- displays the Anomaly detection criteria value on search proposition when user types type in the search bar.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Global -- displays the Anomaly detection criteria value when the type criteria chip is clicked and centreon-anomaly-detection is installed.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Global -- displays the wrench icon on graph actions when one row of a resource of anomaly-detection is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Graph -- displays the modal of confirmation when clicking on save button of slider.snap.png
  centreon/cypress/visual-testing-snapshots/Anomaly detection - Graph -- displays the threshold when add or minus buttons are clicked on Anomaly detection configuration modal slider.snap.png
  centreon/junit.xml~8f738728560a6ca6c4cec5b4ea0b17b487306d08
  centreon/www/front_src/src/Resources/Actions/Resource/Disacknowledge/api/index.ts
  centreon/www/front_src/src/Resources/Actions/Resource/SubmitStatus/api/index.ts
  centreon/www/front_src/src/Resources/Actions/api/index.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/Card.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/CommandLineCard.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Services/List.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Services/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/ExportToCsv.tsx
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionModalConfirmation.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionSlider.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/anomalyDetectionAtom.ts
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/AnomalyDetectionEnvelopeThreshold.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/AnomalyDetectionEstimatedEnvelopeThreshold.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/AnomalyDetectionGraphActions.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/AnomalyDetectionShapeCircle.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/helpers.ts
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/index.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/Axes/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Lines/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/models.ts
  centreon/www/front_src/src/Resources/Graph/Performance/timeSeries/index.ts
  centreon/www/front_src/src/Resources/Listing/columns/Graph.tsx
  centreon/www/front_src/src/Resources/Listing/columns/Parent.tsx
  centreon/www/front_src/src/Resources/Listing/columns/index.tsx
  centreon/www/front_src/src/Resources/decoders.ts
  centreon/www/front_src/src/Resources/models.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#502 fix(Resources/useDateTimePicker): some months are missing in the calendar
  centreon/cypress/plugins/index.ts
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-April-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-April-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-August-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-August-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-December-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-December-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-February-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-February-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-January-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-January-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-July-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-July-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-June-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-June-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-March-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-March-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-May-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-May-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-November-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-November-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-October-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-October-when-clicking-on-Previous month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-September-when-clicking-on-Next month.snap.png
  centreon/cypress/visual-testing-snapshots/calendar-Europe/Paris-September-when-clicking-on-Previous month.snap.png
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  centreon/www/front_src/src/Resources/index.cypress.spec.tsx
  centreon/www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#503 fix(Resources/useDateTimePicker):some months are missing in the calendar
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  centreon/www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#509 Fix(pipeline): Fix stable npm packages publication
  .github/actions/npm-publish-package/action.yml
  .github/actions/publish-npm/action.yml
  .github/workflows/js-config-merge.yml
  .github/workflows/js-config.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-context-merge.yml
  .github/workflows/ui-context.yml
  .github/workflows/ui-merge.yml
  .github/workflows/ui.yml
  centreon/packages/js-config/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
Labels: area/ui

#534 chore(ui version): Update package ui version to 23.4.8
  centreon/packages/ui/package.json
Labels: automerge

#532 chore(js-config version): Update package js-config version to 23.4.10
  centreon/packages/js-config/package.json
Labels: automerge

#533 chore(ui-context version): Update package ui-context version to 23.4.5
  centreon/packages/ui-context/package.json
Labels: automerge

#531 fix(vault): added check to SQL scripts
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.0-beta.1.sql
Labels: area/backend

#517 vault(fix): remove vault configuration endpoints from 22.10
  centreon/doc/API/centreon-api-v22.10.yaml
  centreon/src/Core/Security/Vault/Application/Exceptions/VaultConfigurationException.php
  centreon/src/Core/Security/Vault/Application/Exceptions/VaultException.php
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/Repository/WriteVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/NewVaultConfigurationFactory.php
  centreon/src/Core/Security/Vault/Application/UseCase/DeleteVaultConfiguration/DeleteVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/DeleteVaultConfiguration/DeleteVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationResponse.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurations.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurationsResponse.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Domain/Model/NewVaultConfiguration.php
  centreon/src/Core/Security/Vault/Domain/Model/Vault.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationSchema.json
  centreon/src/Core/Security/Vault/Infrastructure/API/DeleteVaultConfiguration/DeleteVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/DeleteVaultConfiguration/DeleteVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfiguration/FindVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfiguration/FindVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfigurations/FindVaultConfigurationsController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfigurations/FindVaultConfigurationsPresenter.php
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfigurations/FindVaultConfigurationsRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationSchema.json
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbVaultConfigurationFactory.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbVaultFactory.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbWriteVaultConfigurationRepository.php
  centreon/tests/api/features/VaultConfiguration.feature
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/NewVaultConfigurationFactoryTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/DeleteVaultConfiguration/DeleteVaultConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/DeleteVaultConfiguration/DeleteVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurationsPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurationsTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Domain/Model/NewVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Domain/Model/VaultTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-22.10.2.sql
Labels: area/backend

#529 fix(recurrentDowntime): remove trailing single quote on NOWDOC SQL re…
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#536 Fix(security): Sanitize and binding queries 22.10.x
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend

#340 Fix(security): handle path security in centreon broker statistics
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
Labels: area/backend

#365 fix(secu): Fix path transversal in centreon.Config.Poller.class.php
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#390 fix(security): Fix path transversal when exporting SNMP traps database to poller
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/backend

#467 Fix(security): Sanitize queries in the list of broker configurations
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#468 Fix(security): Sanitize queries in the list of broker configurations dev-22.04.x
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#469 Fix(security): Sanitize queries in the list of broker configurations dev-21.10.x
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#499 fix(ci): Use proper names for test reports
  .github/actions/cypress-e2e-testing/action.yml
Labels: area/ui

#535 fix (contact): Correction to correctly fill in the user's roles
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#543 fix (contact): Correction to correctly fill in the user's roles (#535)
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#542 fix(recurrentDowntime): remove trailing single quote on NOWDOC SQL re…
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#545 fix (contact): Correction to correctly fill in the user's roles (#535)
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#541 fix(recurrentDowntime): remove trailing single quote on NOWDOC SQL re…
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#557 chore(ui version): Update package ui version to 23.4.9
  centreon/packages/ui/package.json
Labels: automerge

#294 fix(security): Fix path transversal when user change default image directory
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#540 fix(UI): The size of login paper is different
  centreon/www/front_src/src/Login/index.tsx
Labels: area/ui

#562 fix(Resources/useDateTimePicker): some months are missing in the calendar
  centreon/package-lock.json
  centreon/package.json
  centreon/www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#501 fix: Fixed issue pagination not displayed in all legacy pages
  centreon/www/Themes/Generic-theme/style.css
Labels: area/backend

#330 Fix(security): fix path transversal for images management
  centreon/www/class/centreonImageManager.php
  centreon/www/class/centreonMedia.class.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#355 enh(resource-status): improve performances for users under ACL
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/HostACLProvider.php
  centreon/src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/MetaServiceACLProvider.php
  centreon/src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/ResourceACLProviderInterface.php
  centreon/src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/ServiceACLProvider.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
Labels: area/backend

#570 switch to lightmode on logout
  centreon/www/front_src/src/Header/UserMenu/index.tsx
Labels: area/ui

#581 feat(host): Save SNMP Community has password
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbVaultConfigurationFactory.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonRestHttp.class.php
  centreon/www/include/common/javascript/centreon/macroPasswordField.js
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.04.0-beta.1.php
Labels: area/backend

#589 chore(js-config version): Update package js-config version to 23.4.11
  centreon/packages/js-config/package.json
Labels: automerge
