Repository centreon/centreon, pull requests merged in 2022-04, with the labels that each got.

#10931 fix(config): do not shared same instance of statement collector
  config/services.yaml
Labels: area/backend

#10932 fix(install/upgrade): do not register websso event subscriber on fresh install and upgrade
  src/EventSubscriber/WebSSOEventSubscriber.php
Labels: area/backend

#10908 enh(chore): Remove sass-loader and unecessary files
  package-lock.json
  package.json
  webpack.config.js
  www/front_src/src/Header/header.scss
  www/front_src/src/components/button/button.scss
  www/front_src/src/global-sass-files/_containers.scss
  www/front_src/src/global-sass-files/_grid.scss
  www/front_src/src/global-sass-files/_helpers.scss
  www/front_src/src/global-sass-files/_mixins.scss
  www/front_src/src/global-sass-files/_variables.scss
  www/front_src/src/route-components/legacyRoute/index.tsx
  www/front_src/src/styles/partials/_helpers.scss
  www/front_src/src/styles/partials/_mixins.scss
  www/front_src/src/styles/partials/_typography.scss
  www/front_src/src/styles/partials/_variables.scss
Labels: area/ui

#10895 enh(UI): Replace react-beatiful-dnd by dnd-kit
  package-lock.json
  package.json
  www/front_src/src/App/useApp.ts
  www/front_src/src/Resources/Details/tabs/Details/SortableCards/index.tsx
  www/front_src/src/Resources/Filter/Edit/EditFilterCard.tsx
  www/front_src/src/Resources/Filter/Edit/SortableContent.tsx
  www/front_src/src/Resources/Filter/Edit/index.test.tsx
  www/front_src/src/Resources/Filter/Edit/index.tsx
Labels: area/ui

#10914 fix(resource): correctly display comments for DT and ACK
  src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
  src/Centreon/Infrastructure/Downtime/DowntimeRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#10928 enh(SVG): Displays the SVG file in HTML
  www/include/common/common-Func.php
Labels: area/backend

#10834 fix(install): fix el8 db user creation
  www/install/steps/process/createDbUser.php
Labels: area/backend

#10845 Refactoring dark mode
  features/bootstrap/ShowDisabledHostsServicesContext.php
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Centreon-Light/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/color.css
  www/Themes/Generic-theme/style.css
  www/include/Administration/parameters/ldap/list.ihtml
  www/include/Administration/performance/manageData.ihtml
  www/include/Administration/performance/viewData.ihtml
  www/include/common/javascript/charts/c3.min.css
  www/include/configuration/configObject/service/listService.ihtml
  www/include/home/customViews/widgetParam.html
  www/include/monitoring/external_cmd/popup/templates/massive_ack.ihtml
  www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
Labels: area/backend

#10944 fix(acceptances): fix php acceptances tests
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
  www/include/monitoring/recurrentDowntime/formDowntime.html
Labels: area/backend

#10943 fix(upgrade): fix alter table error on upgrade from <= 20.10 to 22.04
  www/install/createTables.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10949 fix(build): update symfony/flex
  composer.lock
Labels: area/backend

#10941 feat(api): add endpoint to get contact templates
  config/routes/Centreon/configuration/contact_template.yaml
  doc/API/centreon-api-v22.04.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Contact/Application/Repository/ReadContactTemplateRepositoryInterface.php
  src/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplates.php
  src/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplatesPresenterInterface.php
  src/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplatesResponse.php
  src/Core/Contact/Domain/Model/ContactTemplate.php
  src/Core/Contact/Infrastructure/Api/FindContactTemplates/FindContactTemplatesController.php
  src/Core/Contact/Infrastructure/Api/FindContactTemplates/FindContactTemplatesPresenter.php
  src/Core/Contact/Infrastructure/Repository/DbContactTemplateFactory.php
  src/Core/Contact/Infrastructure/Repository/DbReadContactTemplateRepository.php
  tests/php/Core/Contact/Application/UseCase/FindContactTemplatesPresenterStub.php
  tests/php/Core/Contact/Application/UseCase/FindContactTemplatesTest.php
  tests/php/Core/Contact/Infrastructure/Api/FindContactTemplates/FindContactTemplatesControllerTest.php
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10951 chore(install): update version to 20.10.17
  www/install/insertBaseConf.sql
  www/install/php/Update-20.10.17.php
Labels: area/backend

#10926 fix(broker/conf) change passwords in html forms
  www/class/centreonConfigCentreonBroker.php
Labels: area/backend

#10938 fix(UI): Fix missing properties on payload
  www/front_src/src/Authentication/WebSSO/index.test.tsx
  www/front_src/src/Authentication/api/adapters.ts
Labels: area/ui

#10936 fix(UI): Fix timezones following DST status
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/DateTimePickerInput.tsx
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#10956 fix(api) update total in meta data for configuration/icons
  src/Centreon/Infrastructure/Icon/IconRepositoryRDB.php
Labels: area/backend

#10918 Fix(form) : enable select box after clicking on activate/desactivate button on contact liste page
  www/include/configuration/configObject/contact/contact.php
Labels: area/backend

#10939 enh(UI): Improve labels on password policy form
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  lighthouse/pages/authentication.ts
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/Attempts.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/BlockingDuration.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/index.test.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/CaseButtons/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/index.test.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/CanReusePasswords.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/TimeBeforeNewPassword.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Local/index.test.tsx
  www/front_src/src/Authentication/Local/translatedLabels.ts
Labels: area/ui

#10961 feat(install): create gorgone user and exclude it from password policy
  src/CentreonLegacy/Core/Install/Step/AbstractStep.php
  src/CentreonLegacy/Core/Install/Step/Step7.php
  tests/php/www/install/steps/functionsTest.php
  www/install/insertBaseConf.sql
  www/install/steps/functions.php
  www/install/steps/process/configFileSetup.php
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#10856 enh(conf/broker) change broker outputs to unified sql on upgrade
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10902 fix(UI): Centreon is slowed down
  www/front_src/src/App/index.tsx
  www/front_src/src/App/initPendo.js
  www/front_src/src/App/models.ts
  www/front_src/src/App/useApp.ts
  www/front_src/src/App/usePendo.ts
Labels: area/ui

#10967 enh(resource): add new column to resources table for the listing
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-22.04.0-beta.1.sql
Labels: area/backend

#10966 enh(auth): exclude some users from password expiration policy on upgrade
  src/CentreonLegacy/Core/Install/Step/AbstractStep.php
  tests/php/www/install/functionsTest.php
  www/install/createTables.sql
  www/install/functions.php
  www/install/php/Update-22.04.0-beta.1.php
  www/install/steps/functions.php
  www/install/steps/process/configFileSetup.php
Labels: area/backend

#10947 enh(openid): re add old log mechanism
  src/Core/Domain/Security/Provider/OpenIdProvider.php
Labels: area/backend

#10959 fix(security): delete only expired tokens without refresh token
  src/Core/Infrastructure/Security/Repository/DbWriteTokenRepository.php
Labels: area/backend

#10942 enh(conf/host) add findHostByName method
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#10964 fix(UI): Fix labels on password policy form
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Authentication/FormInputs/Multiple.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/PasswordExpiration/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Local/translatedLabels.ts
Labels: area/ui

#10971 enh(api): add possibility to search contact-template
  src/Core/Contact/Infrastructure/Repository/DbReadContactTemplateRepository.php
Labels: area/backend

#10968 fix: graph tiles size constant in rs host graph panel
  www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
Labels: area/ui

#10975 fix(sql) fix upgrade to 22.04
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10979 enh(ci): remove usage of canary rpms
  Jenkinsfile
Labels: area/backend

#10933 style(Logo):update logo login
  www/front_src/src/Login/Logo.tsx
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Main/MainLoader.tsx
  www/front_src/src/assets/centreon-logo-white.svg
  www/front_src/src/assets/logo-centreon-colors.png
Labels: area/ui

#10982 enh(Translations): Add missing translations on Authentication forms
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
Labels: area/ui

#10960 feat : Mon 12668 switch mode
  www/front_src/src/Header/SwitchThemeMode /images/moon.svg
  www/front_src/src/Header/SwitchThemeMode /images/sun.svg
  www/front_src/src/Header/SwitchThemeMode /index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/userMenu/index.tsx
  www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
Labels: area/ui

#10974 fix : MON-12903-filter-translation
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#10977 enh(export) update export log parser
  www/include/configuration/configGenerate/common-Func.php
Labels: area/backend

#10988 fix(header/themeMode-switch): Make the themeMode switch non-blocking
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/SwitchThemeMode /index.tsx
Labels: area/ui

#10989 fix(upgrade): exclude CBIS user from password policy
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10984 fix(translation): remove duplicated translations
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#10992 fix(ci): retry checkout of centreon-build
  Jenkinsfile
Labels: area/backend

#10976 fix(UI): fully handle default ack options and downtime duration
  config/packages/serializer/Centreon/Acknowledgement.Acknowledgement.yml
  doc/API/centreon-api-v21.10.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  src/Centreon/Application/Controller/Administration/ParametersController.php
  src/Centreon/Domain/Acknowledgement/Acknowledgement.php
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineServiceInterface.php
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/include/Administration/parameters/engine/form.php
Labels: area/ui

#10987 refactor: Mon 12744 use clsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/userMenu/index.tsx
Labels: area/ui

#10986 fix(translations): Fix translations
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#10993 fix(UI): Fix pages topology
  www/front_src/src/route-components/legacyRoute/index.tsx
  www/include/core/footer/footerPart.php
Labels: area/ui, area/backend

#10985 enh(conf/export) tags and severity export for Ressource Status
  www/class/config-generate/abstract/host.class.php
  www/class/config-generate/abstract/object.class.php
  www/class/config-generate/abstract/service.class.php
  www/class/config-generate/engine.class.php
  www/class/config-generate/generate.class.php
  www/class/config-generate/host.class.php
  www/class/config-generate/hostcategory.class.php
  www/class/config-generate/hosttemplate.class.php
  www/class/config-generate/servicecategory.class.php
  www/class/config-generate/servicetemplate.class.php
  www/class/config-generate/severity.class.php
Labels: area/backend

#11007 fix(api): return 401 instead of 500 on login failed
  src/Centreon/Application/Controller/AuthenticationController.php
Labels: area/backend

#10998 fix(UI): Handle ack and dt default options
  config/packages/serializer/Centreon/Acknowledgement.Acknowledgement.yml
  doc/API/centreon-api-v2.1.yaml
  jest.config.js
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  src/Centreon/Application/Controller/Administration/ParametersController.php
  src/Centreon/Domain/Acknowledgement/Acknowledgement.php
  src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineServiceInterface.php
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
  www/include/Administration/parameters/engine/form.php
Labels: area/ui

#11009 enh(export) export service categories linked to services
  www/class/config-generate/abstract/service.class.php
  www/class/config-generate/service.class.php
  www/class/config-generate/servicetemplate.class.php
Labels: area/backend

#11004 fix(parameters): use correct default values from fresh install
  src/Centreon/Application/Controller/Administration/ParametersController.php
Labels: area/backend

#11008 fix(UI): Remove checkbox for default options sent for ack
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
Labels: area/ui

#10946 Changing more global style for dark mode implementation
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Centreon-Light/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/centreon-loading.css
  www/Themes/Generic-theme/color.css
  www/Themes/Generic-theme/jquery-ui/jquery-ui-centreon.css
  www/Themes/Generic-theme/jquery-ui/jquery-ui.css
  www/Themes/Generic-theme/login.css
  www/Themes/Generic-theme/markdown.css
  www/Themes/Generic-theme/style.css
  www/include/configuration/configServers/popup/popup.ihtml
  www/include/core/header/htmlHeader.php
  www/include/monitoring/status/Services/xsl/service.xsl
Labels: area/backend

#10999 enh(api): return service state in host listing
  config/packages/serializer/Centreon/Monitoring.Service.yml
Labels: area/backend

#10997 fix(sec): avoid sql injection in virtual metric form
  www/include/views/virtualMetrics/DB-Func.php
  www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend

#11021 enh(resources): add new columns to resources table
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-22.04.0-beta.1.sql
Labels: area/backend

#11023 fix(UI): Add checkboxs for persistent and sticky option for ACK
  www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
Labels: area/ui

#11024 fix(package-lock): fix the date locale in the header
  package-lock.json
Labels: area/ui

#11026 fix(tests): send full payload to acknowledgement endpoint
  tests/api/features/Acknowledgement.feature
Labels: area/backend

#11001 fix(UI): Issue with openid connect
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Core/Application/Security/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Domain/Security/ProviderConfiguration/OpenId/Model/OpenIdConfigurationFactory.php
  tests/php/Core/Application/Security/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  www/front_src/src/Authentication/FormInputs/Multiple.tsx
  www/front_src/src/Authentication/FormInputs/Text.tsx
  www/front_src/src/Authentication/FormInputs/index.tsx
  www/front_src/src/Authentication/FormInputs/models.ts
  www/front_src/src/Authentication/Openid/Form/index.tsx
  www/front_src/src/Authentication/Openid/Form/inputs.ts
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/Openid/models.ts
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
  www/front_src/src/Authentication/Openid/useValidationSchema.ts
  www/front_src/src/Authentication/WebSSO/index.test.tsx
  www/front_src/src/Authentication/translatedLabels.ts
  www/front_src/src/Login/index.tsx
Labels: area/ui, area/backend

#11028 fix(metrics): validate given thresholds as numeric
  www/include/views/virtualMetrics/DB-Func.php
  www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend

#11031 fix(metrics): allow zero thresholds for virtual metrics
  www/include/views/virtualMetrics/DB-Func.php
Labels: area/backend

#11032 fix(resources): add missing primary key to resources_tags table
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-22.04.0-beta.1.sql
Labels: area/backend

#11034 enh(conf): export icon_id for templates
  www/class/config-generate/hosttemplate.class.php
  www/class/config-generate/servicetemplate.class.php
Labels: area/backend

#11025 fix(install): avoid usage of chown and chmod on web install
  www/install/steps/process/configFileSetup.php
Labels: area/backend

#11030 fix(UI): Add missing translations
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#11033 chore(core): Improve the Webpack development configuration
  package.json
  webpack.config.dev.js
Labels: area/ui

#11037 chore(npm): Set centreon-frontend branch to develop
  package-lock.json
  package.json
Labels: area/ui

#10823 enh(notification): Add missing translations for notification policy
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui, area/backend

#11041 fix(translation): remove duplicate translation
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#11045 fix(translation): fix invalid character in translation file
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#11040 enh(resources): use new resources tables from monitoring
  config/packages/Centreon.yaml
  src/Centreon/Domain/Monitoring/Icon.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Domain/Monitoring/ResourceStatus.php
  src/Centreon/Infrastructure/Monitoring/Resource/DbReadResourceRepository.php
  src/Centreon/Infrastructure/Monitoring/Resource/DbResourceFactory.php
  src/Centreon/Infrastructure/Monitoring/Resource/ResourceRepositoryRDB.php
  tests/php/Centreon/Infrastructure/Monitoring/Resource/DbResourceFactoryTest.php
Labels: area/backend
