Repository centreon/centreon, pull requests merged in 2022-01, with the labels that each got.

#10491 chore(deps): upgrade to symfony 5 and fosrestbundle 3
  composer.json
  composer.lock
  config/packages/Centreon.yaml
  config/packages/fos_rest.yaml
  config/packages/framework.yaml
  config/packages/security.yaml
  config/services.yaml
  features/SpecialCharactersInContact.feature
  features/bootstrap/SpecialCharactersInContactContext.php
  src/Centreon/Application/Controller/AbstractController.php
  src/Centreon/Application/Controller/AcknowledgementController.php
  src/Centreon/Application/Controller/AuthenticationController.php
  src/Centreon/Application/Controller/Configuration/IconController.php
  src/Centreon/Application/Controller/Configuration/ProxyController.php
  src/Centreon/Application/Controller/Monitoring/CommentController.php
  src/Centreon/Application/Controller/Monitoring/MetricController.php
  src/Centreon/Application/Controller/Monitoring/SubmitResultController.php
  src/Centreon/Application/Controller/MonitoringHostsController.php
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Application/Controller/PlatformTopologyController.php
  src/Centreon/Application/Controller/Router.php
  src/Centreon/Application/Validation/CentreonValidatorTranslator.php
  src/Centreon/Domain/Authentication/UseCase/Authenticate.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Security/Domain/Authentication/Exceptions/AuthenticatorException.php
  src/Security/SessionAPIAuthenticator.php
  src/Security/TokenAPIAuthenticator.php
  symfony.lock
  tests/php/Centreon/Domain/Authentication/UseCase/AuthenticateTest.php
  tests/php/Security/EncryptionTest.php
  tests/php/Security/SessionAPIAuthenticatorTest.php
  tests/php/Security/TokenAPIAuthenticatorTest.php
Labels: area/backend

#10536 test(e2e): Refacto cypress tests and disable AT for frontend related continuous builds
  Jenkinsfile
  package-lock.json
  tests/e2e/cypress/fixtures/resources/clapi/service3/01-add.json
  tests/e2e/cypress/fixtures/resources/clapi/service3/02-set-max-check.json
  tests/e2e/cypress/fixtures/resources/clapi/service3/03-disable-active-check.json
  tests/e2e/cypress/fixtures/resources/clapi/service3/04-enable-passive-check.json
  tests/e2e/cypress/fixtures/resources/clapi/submit-results.json
  tests/e2e/cypress/fixtures/resources/filters.json
  tests/e2e/cypress/integration/Resources-status/01-listing.feature
  tests/e2e/cypress/integration/Resources-status/01-listing/index.ts
  tests/e2e/cypress/integration/Resources-status/02-actions.feature
  tests/e2e/cypress/integration/Resources-status/02-actions/index.ts
  tests/e2e/cypress/integration/Resources-status/common.ts
  tests/e2e/cypress/support/centreonData.ts
  tests/e2e/cypress/support/index.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: area/ui

#10517 enh(phpstan) : fix phpstan errors in centreon/src (part 2)
  src/CentreonCommand/Application/Webservice/CommandWebservice.php
  src/CentreonCommand/Domain/Entity/Command.php
  src/CentreonCommand/Tests/Application/Webservice/CommandWebserviceTest.php
  src/CentreonCommand/Tests/Domain/Repository/CommandRepositoryTest.php
  src/CentreonCommand/Tests/ServiceProviderTest.php
  src/CentreonNotification/Application/Webservice/EscalationWebservice.php
  src/CentreonNotification/Domain/Repository/EscalationRepository.php
  src/CentreonNotification/Tests/Application/Webservice/EscalationWebserviceTest.php
  src/CentreonNotification/Tests/Domain/Repository/DependencyRepositoryTest.php
  src/CentreonNotification/Tests/Domain/Repository/EscalationRepositoryTest.php
  src/CentreonNotification/Tests/ServiceProviderTest.php
Labels: area/backend

#10540 chore(backend): Bootstrap the new architecture
  config/packages/Centreon.yaml
  phpstan.neon
  src/Centreon/Domain/Log/LoggerTrait.php
  src/Core/Application/Common/UseCase/ErrorResponse.php
  src/Core/Application/Common/UseCase/NotFoundResponse.php
  src/Core/Application/Common/UseCase/PresenterInterface.php
  src/Core/Application/Common/UseCase/ResponseStatusInterface.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
  src/Core/Infrastructure/Common/Presenter/PresenterFormatterInterface.php
  src/Core/Infrastructure/Common/Repository/DbFactoryUtilitiesTrait.php
Labels: area/backend

#10534 enh(clapi): use password policy to insert/update contact password
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  tests/rest_api/rest_api.postman_collection.json
  www/class/centreon-clapi/centreonContact.class.php
  www/class/centreonAuth.class.php
  www/class/centreonContact.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#10543 enh(API): create NoContent and Created Response
  src/Core/Application/Common/UseCase/CreatedResponse.php
  src/Core/Application/Common/UseCase/NoContentResponse.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
Labels: area/backend

#10541 enh(conf) remove old broker logger mentions
  www/class/centreonConfigCentreonBroker.php
  www/class/config-generate-remote/Relations/BrokerInfo.php
  www/class/config-generate/broker.class.php
  www/include/configuration/configCentreonBroker/DB-Func.php
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/listCentreonBroker.ihtml
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10470 enh(UI): Update React Router
  package-lock.json
  package.json
  www/front_src/src/App.tsx
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/getResourcesUrl.ts
  www/front_src/src/Navigation/Sidebar/Menu/index.js
  www/front_src/src/Resources/Actions/ResourceActionsSkeleton.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/filterAtoms.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/components/forms/remoteServer/RemoteServerFormStepTwo.js
  www/front_src/src/components/mainRouter/index.js
  www/front_src/src/components/mainRouter/index.tsx
  www/front_src/src/components/progressBar/index.js
  www/front_src/src/components/progressBar/index.tsx
  www/front_src/src/reactRoutes/index.js
  www/front_src/src/reactRoutes/route-map.js
  www/front_src/src/redux/reducers/index.js
  www/front_src/src/route-components/legacyRoute/index.js
  www/front_src/src/route-components/legacyRoute/index.tsx
  www/front_src/src/route-components/pollerStep1/index.js
  www/front_src/src/route-components/pollerStep1/index.tsx
  www/front_src/src/route-components/pollerStep2/index.js
  www/front_src/src/route-components/pollerStep2/index.tsx
  www/front_src/src/route-components/pollerStep3/index.js
  www/front_src/src/route-components/pollerStep3/index.tsx
  www/front_src/src/route-components/remoteServerStep1/index.js
  www/front_src/src/route-components/remoteServerStep1/index.tsx
  www/front_src/src/route-components/remoteServerStep2/index.js
  www/front_src/src/route-components/remoteServerStep2/index.tsx
  www/front_src/src/route-components/remoteServerStep3/index.js
  www/front_src/src/route-components/remoteServerStep3/index.tsx
  www/front_src/src/route-components/serverConfigurationWizard/index.js
  www/front_src/src/route-components/serverConfigurationWizard/index.tsx
  www/front_src/src/route-maps/index.js
  www/front_src/src/store/index.js
  www/include/core/footer/footerPart.php
Labels: area/ui

#10542 enh(API): Interfaces for update security policy use case
  config/routes/Centreon/administration/security_policy.yaml
  src/Core/Application/Security/Repository/WriteSecurityPolicyRepositoryInterface.php
  src/Core/Application/Security/UseCase/UpdateSecurityPolicy/UpdateSecurityPolicy.php
  src/Core/Application/Security/UseCase/UpdateSecurityPolicy/UpdateSecurityPolicyPresenterInterface.php
  src/Core/Application/Security/UseCase/UpdateSecurityPolicy/UpdateSecurityPolicyRequest.php
  src/Core/Domain/Security/Model/SecurityPolicyFactory.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
  src/Core/Infrastructure/Security/Api/Exception/SecurityPolicyApiException.php
  src/Core/Infrastructure/Security/Api/UpdateSecurityPolicy/UpdateSecurityPolicyController.php
  src/Core/Infrastructure/Security/Api/UpdateSecurityPolicy/UpdateSecurityPolicySchema.json
  src/Core/Infrastructure/Security/Repository/DbReadSecurityPolicyRepository.php
  tests/php/Core/Application/Security/UseCase/UpdateSecurityPolicy/UpdateSecurityPolicyTest.php
  tests/php/Core/Infrastructure/Security/Api/UpdateSecurityPolicy/UpdateSecurityPolicyControllerTest.php
  tests/rest_api/realtime_rest_api.postman_collection.json
  tests/rest_api/rest_api.postman_collection.json
  tests/rest_api/rest_api.postman_environment.json
Labels: area/backend

#10530 enh(phpstan) : fix phpstan errors in centreon/src (part 4)
  src/CentreonModule/Application/DataRepresenter/ModuleDetailEntity.php
  src/CentreonModule/Application/DataRepresenter/ModuleEntity.php
  src/CentreonModule/Application/DataRepresenter/UpdateAction.php
  src/CentreonModule/Application/Webservice/CentreonModuleWebservice.php
  src/CentreonModule/Application/Webservice/CentreonModulesWebservice.php
  src/CentreonModule/Domain/Repository/ModulesInformationsRepository.php
  src/CentreonModule/Domain/Repository/WidgetModelsRepository.php
  src/CentreonModule/Infrastructure/Entity/Module.php
  src/CentreonModule/Infrastructure/Service/CentreonModuleService.php
  src/CentreonModule/Infrastructure/Source/ModuleSource.php
  src/CentreonModule/Infrastructure/Source/SourceAbstract.php
  src/CentreonModule/Infrastructure/Source/SourceInterface.php
  src/CentreonModule/Infrastructure/Source/WidgetSource.php
  src/CentreonModule/Tests/Application/DataRepresenter/ModuleDetailEntityTest.php
  src/CentreonModule/Tests/Application/DataRepresenter/ModuleEntityTest.php
  src/CentreonModule/Tests/Application/DataRepresenter/UpdateActionTest.php
  src/CentreonModule/Tests/Application/Webservice/CentreonModuleWebserviceTest.php
  src/CentreonModule/Tests/Application/Webservice/CentreonModulesWebserviceTest.php
  src/CentreonModule/Tests/Infrastructure/Service/CentreonModuleServiceTest.php
  src/CentreonModule/Tests/Infrastructure/Source/ModuleSourceTest.php
  src/CentreonModule/Tests/Infrastructure/Source/SourceAbstractTest.php
  src/CentreonModule/Tests/Infrastructure/Source/WidgetSourceTest.php
  src/CentreonModule/Tests/Resources/Traits/SourceDependencyTrait.php
  src/CentreonModule/Tests/ServiceProviderTest.php
Labels: area/backend

#10548 chore(api): Implement AbstractPresenter
  src/Core/Application/Common/UseCase/AbstractPresenter.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
Labels: area/backend

#10549 fix(api): add constructor to AbstractPresenter
  src/Core/Application/Common/UseCase/AbstractPresenter.php
Labels: area/backend

#10529 enh(UI): Take downtime options default value for set downtime in resource status
  doc/API/centreon-api-v21.10.yaml
  package-lock.json
  package.json
  src/Centreon/Application/Controller/Administration/ParametersController.php
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Provider/models.ts
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
  www/front_src/src/Resources/Actions/api/index.ts
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
Labels: area/ui

#10547 enh(API): Implements update security policy use case.
  config/routes/Centreon/administration/security_policy.yaml
  src/Core/Application/Security/UseCase/UpdateSecurityPolicy/UpdateSecurityPolicy.php
  src/Core/Infrastructure/Security/Api/UpdateSecurityPolicy/UpdateSecurityPolicyPresenter.php
  src/Core/Infrastructure/Security/Repository/DbWriteSecurityPolicyRepository.php
Labels: area/backend

#10462 feat(UI): Add password policy form
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  setupTest.js
  www/front_src/src/Authentication/Form/FormButtons.tsx
  www/front_src/src/Authentication/Form/PasswordBlockingPolicy/Attempts.tsx
  www/front_src/src/Authentication/Form/PasswordBlockingPolicy/BlockingDuration.tsx
  www/front_src/src/Authentication/Form/PasswordBlockingPolicy/index.test.tsx
  www/front_src/src/Authentication/Form/PasswordBlockingPolicy/index.tsx
  www/front_src/src/Authentication/Form/PasswordCasePolicy/CaseButtons/LabelWithTooltip.tsx
  www/front_src/src/Authentication/Form/PasswordCasePolicy/CaseButtons/index.tsx
  www/front_src/src/Authentication/Form/PasswordCasePolicy/index.test.tsx
  www/front_src/src/Authentication/Form/PasswordCasePolicy/index.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/CanReusePasswords.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/TimeBeforeNewPassword.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/index.tsx
  www/front_src/src/Authentication/Form/defaults.ts
  www/front_src/src/Authentication/Form/index.tsx
  www/front_src/src/Authentication/Form/utils.ts
  www/front_src/src/Authentication/LoadingSkeleton.tsx
  www/front_src/src/Authentication/StrengthProgress.tsx
  www/front_src/src/Authentication/TimeInputs/TimeInput.tsx
  www/front_src/src/Authentication/TimeInputs/index.test.tsx
  www/front_src/src/Authentication/TimeInputs/index.tsx
  www/front_src/src/Authentication/TimeInputs/options.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/api/endpoints.ts
  www/front_src/src/Authentication/api/index.ts
  www/front_src/src/Authentication/index.test.tsx
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Authentication/models.ts
  www/front_src/src/Authentication/timestamps.ts
  www/front_src/src/Authentication/translatedLabels.ts
  www/front_src/src/Authentication/useAuthentication.ts
  www/front_src/src/Authentication/useValidationSchema.ts
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/ResourceActionsSkeleton.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/route-maps/reactRoutes.js
  www/front_src/src/route-maps/route-map.js
  www/locale/fr_FR.UTF-8/LC_MESSAGES/messages.ser
Labels: area/authentication, kind/feature, area/ui

#10555 enh(API): Implements classes for find installation status use case
  config/packages/Centreon.yaml
  config/routes/Centreon/platform.yaml
  config/services.yaml
  doc/API/centreon-api-v22.04.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Application/Platform/Repository/ReadPlatformRepositoryInterface.php
  src/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatus.php
  src/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusPresenterInterface.php
  src/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusResponse.php
  src/Core/Application/Platform/UseCase/FindWebVersions/FindWebVersions.php
  src/Core/Infrastructure/Platform/Api/FindInstallationStatus/FindInstallationStatusController.php
  src/Core/Infrastructure/Platform/Api/FindInstallationStatus/FindInstallationStatusPresenter.php
  src/Core/Infrastructure/Platform/Repository/FileReadPlatformRepository.php
  tests/php/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusPresenterStub.php
  tests/php/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusTest.php
Labels: area/backend

#10557 feat(api): truly return severity level for Hosts and Services
  config/packages/serializer/Centreon/Monitoring.Host.yml
  src/Centreon/Domain/Monitoring/Service.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#10564 fix(myAccount): Fix password input type reset
  www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#10558 fix(UI): Resource Status is not filtered based on the clicked top counter status
  www/front_src/src/Resources/Filter/filterAtoms.ts
  www/front_src/src/Resources/Filter/useFilter.ts
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
Labels: area/ui

#10559 fix(ui) : resolve PHP warning when selecting an host without service
  www/include/reporting/dashboard/DB-Func.php
Labels: area/backend

#10565 enh(autologin): verify that autologin is different than password
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lib/Centreon/Object/Contact/Contact.php
  www/class/centreon-clapi/centreonContact.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#10574 fix(test): fix acceptance tests and remove failOnError directive
  Jenkinsfile
  features/bootstrap/ConfigurationWarningsContext.php
  features/bootstrap/DowntimeServiceContext.php
Labels: area/backend

#10578 fix(UI): Titles are cropped in tiles
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/index.tsx
Labels: area/ui

#10583 Fix(UI): Fix frontend critical error
  package-lock.json
  package.json
  setupTest.js
  www/front_src/src/Footer/Copyright.tsx
  www/front_src/src/Provider/index.tsx
Labels: area/ui

#10582 enh(resource): display only comments not deleted for ACK and DT
  src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
  src/Centreon/Infrastructure/Downtime/DowntimeRepositoryRDB.php
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#10584 fix(core): Adapt Webpack dev config
  webpack.config.dev.js
Labels: area/ui

#10588 fix(UI): Fix eslint issue on App.tsx
  www/front_src/src/App.tsx
Labels: area/ui

#10585 enh(autologin): verify that autologin is different than password (21.10,21.04,20.10)
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lib/Centreon/Object/Contact/Contact.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#10590 fix(conf/host) fix macro's inheritance on host
  www/class/centreonHost.class.php
Labels: area/backend

#10579 fix(ui) : resolved warnings after selecting a service groups in an inexistant timeperiod
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
  www/include/reporting/dashboard/template/viewHostLog.ihtml
  www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
Labels: area/backend

#10570 fix(UI): Fix path for centreon frontend
  .eslintrc.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.dev.js
  webpack.config.js
  www/front_src/src/App.tsx
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.test.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Provider/decoder.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/index.test.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/__mocks__/@centreon/ui-context.jsx
  www/front_src/src/components/MenuLoader.tsx
Labels: area/ui
