Repository centreon/centreon, pull requests merged in 2022-08, with the labels that each got.

#11376 fix(conf) fix broker conf name display in listing (#11372)
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#11477 fix(debian): reload symfony cache on pkg upgrade
  Jenkinsfile
  ci/debian/centreon-web.postinst
Labels: area/backend

#11138 fix(web): fix the comment deletion for host monitored by poller
  www/include/monitoring/comments/comments.php
  www/include/monitoring/comments/common-Func.php
Labels: area/backend

#11474 fix(cron): Escape database name in CentACL
  cron/centAcl.php
Labels: area/backend

#11459 fix(Resources/Graph): graph image after export to png when Central is in dark mode
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/exportToPng.ts
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
Labels: area/ui

#11498 fix(test): wait 8s before checking downtime is active in apiv1 test
  tests/rest_api/realtime_rest_api.postman_collection.json
Labels: area/backend

#11499 fix(git): resync 21.10.x to dev-21.10.x
  .github/CODEOWNERS
  Jenkinsfile
  composer.json
  composer.lock
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  lib/perl/centreon/script.pm
  package-lock.json
  package.json
  tests/e2e/cypress/.eslintrc.js
  tests/e2e/package-lock.json
  tests/e2e/package.json
  webpack.config.dev.js
  www/api/class/centreon_ceip.class.php
  www/class/centreon-clapi/centreonDowntime.class.php
  www/class/centreon-partition/partEngine.class.php
  www/class/centreonACL.class.php
  www/class/centreonAuth.class.php
  www/class/centreonHostgroups.class.php
  www/class/centreonTraps.class.php
  www/class/centreonUser.class.php
  www/front_src/src/Header/RessourceStatusCounter/index.tsx
  www/front_src/src/Header/pollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/Groups.tsx
  www/include/Administration/myAccount/formMyAccount.php
  www/include/Administration/parameters/general/form.php
  www/include/common/common-Func.php
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/host_dependency/DB-Func.php
  www/include/configuration/configObject/hostgroup_dependency/DB-Func.php
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/service/formService.ihtml
  www/include/configuration/configObject/service/formService.php
  www/include/configuration/configObject/service_dependency/DB-Func.php
  www/include/configuration/configObject/timeperiod/DB-Func.php
  www/include/configuration/configObject/traps/formTraps.php
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
  www/include/options/media/images/syncDir.php
  www/include/reporting/dashboard/viewHostGroupLog.php
  www/include/reporting/dashboard/viewHostLog.php
  www/include/reporting/dashboard/viewServicesGroupLog.php
  www/include/views/graphs/javascript/centreon-graph.js
  www/include/views/virtualMetrics/DB-Func.php
  www/install/install.css
  www/install/installBroker.sql
  www/install/php/Update-18.10.0.post.php
  www/install/php/Update-19.10.0-beta.3.php
  www/install/php/Update-2.8.0.php
  www/install/php/Update-2.8.5.post.php
  www/install/php/Update-21.04.0-beta.1.php
  www/install/sql/centreon/Update-DB-21.10.0-beta.1.sql
  www/install/sql/centstorage/Update-CSTG-21.10.7.sql
  www/install/steps/process/process_step6.php
Labels: area/ui, area/backend

#11505 fix(test): wait 8s before checking downtime is active in apiv1 test
  tests/rest_api/realtime_rest_api.postman_collection.json
Labels: area/backend

#11510 fix(cron): Escape database name in CentACL 22.04.x
  cron/centAcl.php
Labels: area/backend

#11520 fix(UI): Include host_id when selecting ServiceGroups on dashreports
  www/include/reporting/dashboard/DB-Func.php
Labels: area/backend

#11518 [SNYK] Sanitize and bind centreonGraph class queries (#11409) #11465
  www/class/centreonGraph.class.php
Labels: area/backend

#11515 [Snyk] Sanitize and bind ACL action access queries (#11385) #11470
  www/include/options/accessLists/menusACL/formMenusAccess.php
Labels: area/backend

#11509 fix(cron): Escape database name in CentACL 21.10.x
  cron/centAcl.php
Labels: area/backend

#11504 fix(test): wait 8s before checking downtime is active in apiv1 test
  tests/rest_api/realtime_rest_api.postman_collection.json
Labels: area/backend

#11519 fix(UI): Include host_id when selecting ServiceGroups on dashreports
  www/include/reporting/dashboard/DB-Func.php
Labels: area/backend

#11485 Fix[platform]: Clean AppKey usage by 22.10 upgrade script
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  www/install/php/Update-22.10.0-beta.1.php
  www/install/sql/centreon/Update-DB-22.10.0-beta.1.sql
Labels: area/backend

#11511 Fix(platform): Removing appkey key
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
Labels: area/backend

#11484 fix(pendo): correctly set locale when language is detection by browser
  www/api/class/centreon_ceip.class.php
Labels: area/backend

#11327 fix(trap): Removal of the restriction on the uniqueness of the OID of a trap
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonTraps.class.php
  www/include/configuration/configObject/traps/formTraps.php
Labels: area/backend

#11528 fix(pendo): correctly set locale when language is detection by browser (#11484)
  www/api/class/centreon_ceip.class.php
Labels: area/backend

#11529 fix(pendo): correctly set locale when language is detection by browser (#11484)
  www/api/class/centreon_ceip.class.php
Labels: area/backend

#11522 fix(test): fix random fails on virtual metric test
  composer.lock
  features/VirtualMetricHandle.feature
Labels: area/backend

#11523 fix(test): fix random fails on virtual metric test
  composer.lock
  features/VirtualMetricHandle.feature
Labels: area/backend

#11326 fix(trap): Removal of the restriction on the uniqueness of the OID of a trap
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonTraps.class.php
  www/include/configuration/configObject/traps/formTraps.php
Labels: area/backend

#11508 enh(platform): Use API to select metrics in virtual metrics configuration form 21.10.x
  features/bootstrap/VirtualMetricHandleContext.php
  www/include/views/componentTemplates/formComponentTemplate.ihtml
  www/include/views/componentTemplates/formComponentTemplate.php
  www/include/views/graphs/common/makeJS_formMetricsList.php
  www/include/views/graphs/common/makeXML_ListMetrics.php
  www/include/views/virtualMetrics/formVirtualMetrics.ihtml
  www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend

#11526 fix(git): sync dev-21.04.x with 21.04.x
  .github/CODEOWNERS
  Jenkinsfile
  composer.json
  composer.lock
  features/bootstrap/VirtualMetricHandleContext.php
  lib/perl/centreon/script.pm
  package-lock.json
  symfony.lock
  www/api/class/centreon_ceip.class.php
  www/class/centreon-partition/partEngine.class.php
  www/class/centreonAuth.SSO.class.php
  www/class/centreonAuth.class.php
  www/include/Administration/myAccount/formMyAccount.php
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/host/DB-Func.php
  www/include/configuration/configObject/hostgroup_dependency/DB-Func.php
  www/include/configuration/configObject/service/DB-Func.php
  www/include/configuration/configObject/service_dependency/DB-Func.php
  www/include/configuration/configObject/timeperiod/DB-Func.php
  www/include/monitoring/recurrentDowntime/formDowntime.html
  www/include/options/media/images/syncDir.php
  www/include/views/componentTemplates/formComponentTemplate.ihtml
  www/include/views/componentTemplates/formComponentTemplate.php
  www/include/views/graphs/common/makeJS_formMetricsList.php
  www/include/views/graphs/common/makeXML_ListMetrics.php
  www/include/views/virtualMetrics/DB-Func.php
  www/include/views/virtualMetrics/formVirtualMetrics.ihtml
  www/include/views/virtualMetrics/formVirtualMetrics.php
  www/install/install.css
  www/install/php/Update-18.10.0.post.php
  www/install/php/Update-19.10.0-beta.3.php
  www/install/php/Update-2.8.0.php
  www/install/php/Update-2.8.5.post.php
  www/install/php/Update-21.04.0-beta.1.php
  www/install/php/Update-21.04.7.php
  www/install/steps/process/process_step6.php
Labels: area/ui, area/backend

#11492 fix(autoload): Add classmap to fix autoload with legacy classes
  composer.json
Labels: area/backend

#11495 fix(api): allow api platform updates from installed 22.04.0
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/EventSubscriber/UpdateEventSubscriber.php
Labels: area/backend

#11521 [SNYK] Sanitize and bind ACL host dependency queries (#11389)
  www/include/configuration/configObject/host_dependency/DB-Func.php
Labels: area/backend

#11517 [SNYK] Sanitize and bind centreonGraph class queries (#11409) #11467
  www/class/centreonGraph.class.php
Labels: area/backend

#11516 removed old variable userCrypted and the use of it (#11334) #11469
  www/class/centreonUser.class.php
Labels: area/backend

#11506 fix(test): wait 8s before checking downtime is active in apiv1 test
  tests/rest_api/realtime_rest_api.postman_collection.json
Labels: area/backend

#11514 [Snyk] Sanitize and bind ACL action access queries (#11385) #11471
  www/include/options/accessLists/menusACL/formMenusAccess.php
Labels: area/backend

#11513 [SNYK] Sanitize and bind ACL class queries (#11392) #11473
  www/class/centreonACL.class.php
Labels: area/backend

#11422 fix(ldap): small refacto of ldap authentication and log failures
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreonAuth.LDAP.class.php
  www/class/centreonAuth.class.php
  www/class/centreonContactgroup.class.php
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/ldap/form.php
Labels: area/backend

#11532 fix(autoload): Add classmap to fix autoload with legacy classes #11492
  composer.json
Labels: area/backend

#11534 fix(ldap): small refacto of ldap authentication and log failures
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreonAuth.LDAP.class.php
  www/class/centreonAuth.class.php
  www/class/centreonContactgroup.class.php
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/ldap/form.php
Labels: area/backend

#11533 fix(api): allow api platform updates from installed 22.04.0 (#11495)
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/EventSubscriber/UpdateEventSubscriber.php
Labels: area/backend

#11536 fix(api): fix call to api on fresh install
  src/EventSubscriber/UpdateEventSubscriber.php
Labels: area/backend

#11537 fix(api): fix call to api on fresh install (#11536)
  src/EventSubscriber/UpdateEventSubscriber.php
Labels: area/backend

#11543 fix(api): do not init db connection in event subscriber
  doc/API/centreon-api-v22.10.yaml
  src/EventSubscriber/UpdateEventSubscriber.php
  tests/api/Context/PlatformInstallationStatusContext.php
  tests/api/behat.yml
  tests/api/features/PlatformInstallationStatus.feature
Labels: area/backend

#11501 SNYK: Sanitize and bind ACL actions queries
  www/include/options/accessLists/actionsACL/DB-Func.php
Labels: area/backend

#11525 SNYK: Sanitize and bind Broker listing queries
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#11545 fix(api): do not init db connection in event subscriber (#11543)
  doc/API/centreon-api-v22.04.yaml
  src/EventSubscriber/UpdateEventSubscriber.php
  tests/api/Context/PlatformInstallationStatusContext.php
  tests/api/behat.yml
  tests/api/features/PlatformInstallationStatus.feature
Labels: area/backend

#11549 SNYK: Sanitize and bind ACL actions queries 21.04.x
  www/include/options/accessLists/actionsACL/DB-Func.php
Labels: area/backend

#11553 SNYK: Sanitize and bind Broker listing queries 21.04.x
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#11556 fix(web): fix the comment deletion for host monitored by poller (#11138)
  www/include/monitoring/comments/comments.php
  www/include/monitoring/comments/common-Func.php
Labels: area/backend

#11557 fix(web): fix the comment deletion for host monitored by poller (#11138)
  www/include/monitoring/comments/comments.php
  www/include/monitoring/comments/common-Func.php
Labels: area/backend

#11558 fix(conf) fix encoding in template service listing
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11546 SNYK: Sanitize and bind generateImage queries
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#11547 SNYK: Sanitize and bind ACL actions queries 22.04
  www/include/options/accessLists/actionsACL/DB-Func.php
Labels: area/backend

#11550 SNYK: Sanitize and bind Broker listing queries 22.04.x
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#11551 SNYK: Sanitize and bind Broker listing queries 21.10.x
  www/include/configuration/configCentreonBroker/listCentreonBroker.php
Labels: area/backend

#11559 MON-14501 - sanitize query in centreonXmlbgRequest class
  www/class/centreonXMLBGRequest.class.php
Labels: area/backend

#11554 SNYK: Sanitize and bind Meta-Services dependency queries
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
Labels: area/backend

#11564 fix(conf) fix encoding in template service listing (#11558)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11565 fix(conf) fix encoding in template service listing (#11558)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11566 fix(conf) fix encoding in template service listing (#11558)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11562 SNYK: Sanitize and bind generateImage queries 21.10.x
  www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#11507 feat(conf) add new bbdo broker stream configurations
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/config-generate/broker.class.php
  www/include/common/javascript/centreon/brokerConfig.js
  www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11570 MON-14501 - sanitize query in centreonXmlbgRequest class
  www/class/centreonXMLBGRequest.class.php
Labels: area/backend

#11571 MON-14501 - sanitize query in centreonXmlbgRequest class
  www/class/centreonXMLBGRequest.class.php
Labels: area/backend

#11572 MON-14501 - sanitize query in centreonXmlbgRequest class
  www/class/centreonXMLBGRequest.class.php
Labels: area/backend

#11567 SNYK: Sanitize and bind Meta-Services dependency queries
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
Labels: area/backend

#11568 SNYK: Sanitize and bind Meta-Services dependency queries
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
Labels: area/backend

#11569 SNYK: Sanitize and bind Meta-Services dependency queries
  www/include/configuration/configObject/metaservice_dependency/DB-Func.php
Labels: area/backend

#11577 fix(sql): fix query to select contact during ldap import
  www/class/centreonAuth.class.php
Labels: area/backend

#11579 fix(sql): fix query to select contact during ldap import
  www/class/centreonAuth.class.php
Labels: area/backend

#11578 fix(sql): fix query to select contact during ldap import
  www/class/centreonAuth.class.php
Labels: area/backend

#11580 fix(sql): fix query to select contact during ldap import
  www/class/centreonAuth.class.php
Labels: area/backend

#11587 [SNYK] Sanitize and bind service arguments xml queries
  www/include/configuration/configObject/service/xml/argumentsXml.php
Labels: area/backend

#11586 [SNYK] Sanitized and bound queries in contactgroup file
  www/include/configuration/configObject/contactgroup/DB-Func.php
Labels: area/backend

#11588 [SNYK] Sanitize and bind listVirtualMetrics queries
  www/include/views/virtualMetrics/listVirtualMetrics.php
Labels: area/backend

#11591 [SNYK] Sanitize and bind host categories query
  www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend

#11575 [SNYK] : MON-14671-sanitize-and-bind-update-22-04-0-beta-1-queries
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#11573 SNYK: Sanitize and bind servicegroup dependency queries
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
Labels: area/backend

#11597 SNYK: Sanitize and bind listServiceCategories queries
  www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend

#11604 [Backport/need review] fix(UI): Fix layout for Safari and form validation
  www/front_src/src/Authentication/FormInputs/FieldsTable/Row.tsx
Labels: area/ui

#11576 enh(UI): add button CSV to export graph datas csv file
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#11609 fix(partition): adapt control of database version
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#11435 enh(Apache): Add text compression
  libinstall/functions
Labels: area/api

#11602 (fix)MON-14742 Escape database name in CentACL
  www/class/centreon-partition/mysqlTable.class.php
  www/class/centreon-partition/partEngine.class.php
  www/install/steps/process/createDbUser.php
  www/install/steps/process/insertBaseConf.php
  www/install/steps/process/installConfigurationDb.php
  www/install/steps/process/installStorageDb.php
Labels: area/backend

#11316 ft(UI): Add button to export timeline to csv
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  package-lock.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/ExportToCsv.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#11598 SNYK :Sanitize and bind in centreon connector queries
  www/class/centreonConnector.class.php
Labels: area/backend

#11478 enh(Resources/header): Display the 2 access pictograms logs and report on details panel
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/helpers.ts
Labels: area/ui

#11613 fix(openid): correctly set contact_location while creating session
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSession.php
Labels: area/backend

#11619 fix(platform): Fix database name with special chars
  www/api/class/centreon_performance_service.class.php
  www/api/class/centreon_topcounter.class.php
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#11620 fix(lang): Fixed FR typo
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#11610 fix(partition): adapt control of database version (22.04)
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#11614 fix(openid): correctly set contact_location while creating session 22.04 (#11613)
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSession.php
Labels: area/backend

#11621 fix(lang): Fixed FR typo
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/backend

#11410 enh(resource): prepare resource status to get external data
  config/packages/Centreon.yaml
  config/packages/validator/validation.yaml
  config/routes/Centreon/configuration/notification_policy.yaml
  config/services.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Domain/Monitoring/ResourceService.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHostResponse.php
  src/Core/Application/RealTime/UseCase/FindMetaService/FindMetaServiceResponse.php
  src/Core/Application/RealTime/UseCase/FindService/FindServiceResponse.php
  src/Core/Domain/RealTime/Model/ResourceTypes/AbstractResourceType.php
  src/Core/Domain/RealTime/Model/ResourceTypes/HostResourceType.php
  src/Core/Domain/RealTime/Model/ResourceTypes/MetaServiceResourceType.php
  src/Core/Domain/RealTime/Model/ResourceTypes/ServiceResourceType.php
  src/Core/Domain/RealTime/ResourceTypeInterface.php
  src/Core/Infrastructure/Configuration/NotificationPolicy/Api/FindMetaServiceNotificationPolicyController.php
  src/Core/Infrastructure/RealTime/Api/FindHost/FindHostPresenter.php
  src/Core/Infrastructure/RealTime/Api/FindMetaService/FindMetaServicePresenter.php
  src/Core/Infrastructure/RealTime/Api/FindService/FindServicePresenter.php
  src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Hypermedia/HypermediaCreator.php
  src/Core/Infrastructure/RealTime/Hypermedia/HypermediaProviderInterface.php
  src/Core/Infrastructure/RealTime/Hypermedia/MetaServiceHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
  src/Core/Resources/Application/Repository/ReadResourceRepositoryInterface.php
  src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
  src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/HostACLProvider.php
  src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/MetaServiceACLProvider.php
  src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/ResourceACLProviderInterface.php
  src/Core/Resources/Infrastructure/Repository/ResourceACLProviders/ServiceACLProvider.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
  tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
  tests/php/Core/Application/RealTime/UseCase/FindHost/FindHostTest.php
  tests/php/Core/Application/RealTime/UseCase/FindMetaService/FindMetaServiceTest.php
  tests/php/Core/Application/RealTime/UseCase/FindService/FindServiceTest.php
  tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
  tests/php/Core/Resources/Infrastructure/Repository/DbResourceFactoryTest.php
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/InfiniteScroll/index.tsx
  www/front_src/src/Resources/Details/detailsAtoms.ts
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/useDetails.ts
  www/front_src/src/Resources/Details/useLoadDetails.ts
  www/front_src/src/Resources/Graph/Performance/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.ts
  www/front_src/src/Resources/index.tsx
  www/front_src/src/Resources/testUtils/useLoadDetails.ts
Labels: area/backend

#11542 enh(UI): Add a “Parent alias“ column on the monitoring resources sta…
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  www/front_src/src/Resources/Listing/columns/ParentAlias.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#11631 fix(clapi): Check that user is admin to use clapi
  www/api/class/centreon_clapi.class.php
Labels: area/backend

#11632 Snyk : Sanitize and bind listServiceCategories queries
  www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend

#11634 Snyk : Sanitize and bind listServiceCategories queries
  www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend

#11633 Snyk : Sanitize and bind listServiceCategories queries
  www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend

#11637 SNYK :Sanitize and bind in centreon connector queries
  www/class/centreonConnector.class.php
Labels: area/backend

#11648 [SNYK] Sanitize and bind listVirtualMetrics queries
  www/include/views/virtualMetrics/listVirtualMetrics.php
Labels: area/backend

#11649 [SNYK] Sanitize and bind listVirtualMetrics queries
  www/include/views/virtualMetrics/listVirtualMetrics.php
Labels: area/backend

#11651 [SNYK] Sanitized and bound queries in contactgroup file
  www/include/configuration/configObject/contactgroup/DB-Func.php
Labels: area/backend

#11654 [SNYK] Sanitize and bind service arguments xml queries
  www/include/configuration/configObject/service/xml/argumentsXml.php
Labels: area/backend

#11644 [SNYK] Sanitize and bind host categories query
  www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend

#11652 [SNYK] Sanitized and bound queries in contactgroup file
  www/include/configuration/configObject/contactgroup/DB-Func.php
Labels: area/backend

#11655 [SNYK] Sanitize and bind service arguments xml queries
  www/include/configuration/configObject/service/xml/argumentsXml.php
Labels: area/backend

#11635 SNYK :Sanitize and bind in centreon connector queries
  www/class/centreonConnector.class.php
Labels: area/backend

#11650 [SNYK] Sanitized and bound queries in contactgroup file
  www/include/configuration/configObject/contactgroup/DB-Func.php
Labels: area/backend

#11664 feat(packaging): add php grpc, protobuf modules as dependencies
  ci/debian/control
Labels: area/backend

#11601 Mon 14651 integrate the new theme in centreon smarty
  cypress/support/commands.ts
  cypress/support/component.tsx
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- expands the popper when the user icon is clicked.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- expect the clock to not be visible for a width less than 648px.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- matches the current snapshot user menu.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- using the dark mode.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- using the light mode.snap.png
  cypress/visual-testing-snapshots/Navigation/Sidebar/index.cypress.spec.tsx/Navigation menu -- displays the direct child items and highlights the item when hovered.snap.png
  cypress/visual-testing-snapshots/Navigation/Sidebar/index.cypress.spec.tsx/Navigation menu -- expands the menu when the logo is clicked.snap.png
  cypress/visual-testing-snapshots/Navigation/Sidebar/index.cypress.spec.tsx/Navigation menu -- highlights the menu item when double clicked.snap.png
  cypress/visual-testing-snapshots/Navigation/Sidebar/index.cypress.spec.tsx/Navigation menu -- highlights the parent item when the item is clicked.snap.png
  cypress/visual-testing-snapshots/Navigation/Sidebar/index.cypress.spec.tsx/Navigation menu -- matches the current snapshot initial menu.snap.png
  package-lock.json
  package.json
  setupTest.js
  tests/e2e/cypress/integration/Resources-status/common.ts
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/color.css
  www/Themes/Generic-theme/style.css
  www/front_src/src/App/index.tsx
  www/front_src/src/App/usePendo.ts
  www/front_src/src/Authentication/Local/index.test.tsx
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Extensions/Listing/index.tsx
  www/front_src/src/Header/Clock/index.tsx
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Header/PollerMenu/PollerStatusIcon/index.tsx
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/userMenu/index.cypress.spec.tsx
  www/front_src/src/Header/userMenu/index.tsx
  www/front_src/src/Main/MainLoader.tsx
  www/front_src/src/Main/Provider.tsx
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Navigation/Sidebar/Logo/Centreon_Logo_Noir_RVB.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/Centreon_Logo_Noir_RVB_C.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/index.tsx
  www/front_src/src/Navigation/Sidebar/Logo/index.tsx
  www/front_src/src/Navigation/Sidebar/Menu/CollapsibleItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
  www/front_src/src/Navigation/Sidebar/index.tsx
  www/front_src/src/ResetPassword/index.tsx
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/Resources/Listing/columns/Parent.tsx
  www/front_src/src/Resources/Listing/columns/ParentAlias.tsx
  www/front_src/src/Resources/Listing/columns/Resource.tsx
  www/front_src/src/Resources/Listing/columns/index.tsx
  www/front_src/src/Resources/Listing/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/img/icones/7x7/sort_desc.gif
  www/img/icons/checked.png
Labels: area/ui
