Repository centreon/centreon, pull requests merged in 2022-03, with the labels that each got.

#10806 chore(webpack): Integrate MAP to static assets
  webpack.config.dev.js
Labels: area/ui

#10773 enh(UI): apply new theme for login page
  package-lock.json
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Login/index.tsx
  www/front_src/src/Main/MainLoader.tsx
  www/front_src/src/Navigation/Sidebar/Logo/index.js
  www/front_src/src/assets/centreon-wallpaper-lg.jpg
  www/front_src/src/assets/centreon-wallpaper-sm.jpg
  www/front_src/src/assets/centreon-wallpaper-xl.jpg
  www/front_src/src/assets/centreon.png
  www/front_src/src/components/Wallpaper/BackgroundImage.tsx
  www/front_src/src/components/Wallpaper/index.tsx
  www/front_src/src/components/Wallpaper/loadImageAtom.ts
  www/front_src/src/components/Wallpaper/translatedLabels.ts
  www/front_src/src/components/Wallpaper/useLoadWallpaper.ts
  www/front_src/src/declaration.d.ts
Labels: area/ui

#10783 Fix(UI): Fix time format and day + hour selection
  package-lock.json
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#10811 updating icons in custom view's widgets
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/jquery-ui/jquery-ui.css
  www/include/home/customViews/layouts/widgetScript.js
Labels: area/backend

#10812 fix(poller): Fix the modification of the poller resources
  www/include/configuration/configResources/DB-Func.php
Labels: area/backend

#10807 fix(secu) replace tabulation in command help display
  www/include/configuration/configObject/command/minHelpCommand.php
Labels: area/backend

#10764 Fix(CEIP): Avoid to duplicate pendo script node
  www/front_src/src/App/index.tsx
Labels: area/ui

#10798 enh(UI): Create form to configure OpenID Connect
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Authentication/Form/defaults.ts
  www/front_src/src/Authentication/FormButtons.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/Attempts.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/BlockingDuration.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/index.test.tsx
  www/front_src/src/Authentication/Local/Form/PasswordBlockingPolicy/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/CaseButtons/LabelWithTooltip.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/CaseButtons/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/index.test.tsx
  www/front_src/src/Authentication/Local/Form/PasswordCasePolicy/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/CanReusePasswords.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/PasswordExpiration/ExcludedUsers.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/PasswordExpiration/index.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/TimeBeforeNewPassword.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Local/Form/PasswordExpirationPolicy/index.tsx
  www/front_src/src/Authentication/Local/Form/defaults.ts
  www/front_src/src/Authentication/Local/Form/index.tsx
  www/front_src/src/Authentication/Local/Form/utils.ts
  www/front_src/src/Authentication/Local/LoadingSkeleton.tsx
  www/front_src/src/Authentication/Local/StrengthProgress.tsx
  www/front_src/src/Authentication/Local/TimeInputs/TimeInput.tsx
  www/front_src/src/Authentication/Local/TimeInputs/index.test.tsx
  www/front_src/src/Authentication/Local/TimeInputs/index.tsx
  www/front_src/src/Authentication/Local/TimeInputs/options.ts
  www/front_src/src/Authentication/Local/index.test.tsx
  www/front_src/src/Authentication/Local/index.tsx
  www/front_src/src/Authentication/Local/models.ts
  www/front_src/src/Authentication/Local/timestamps.ts
  www/front_src/src/Authentication/Local/translatedLabels.ts
  www/front_src/src/Authentication/Local/useAuthentication.ts
  www/front_src/src/Authentication/Local/useValidationSchema.ts
  www/front_src/src/Authentication/Openid/Form/Inputs.tsx
  www/front_src/src/Authentication/Openid/Form/LoadingSkeleton.tsx
  www/front_src/src/Authentication/Openid/Form/Multiple.tsx
  www/front_src/src/Authentication/Openid/Form/Radio.tsx
  www/front_src/src/Authentication/Openid/Form/Switch.tsx
  www/front_src/src/Authentication/Openid/Form/Text.tsx
  www/front_src/src/Authentication/Openid/Form/index.tsx
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/Openid/index.tsx
  www/front_src/src/Authentication/Openid/models.ts
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
  www/front_src/src/Authentication/Openid/useOpenid.ts
  www/front_src/src/Authentication/Openid/useValidationSchema.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/api/endpoints.ts
  www/front_src/src/Authentication/api/index.ts
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Authentication/models.tsx
  www/front_src/src/Authentication/useAuthentication.ts
Labels: area/ui

#10805 fix(conf/export) fix getSeverity when a host template is disabled
  www/class/config-generate/host.class.php
Labels: area/backend

#10824 fix(Security): Replace Math.random by Crypto API
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
Labels: area/ui

#10821 enh(build): enable alma 8
  Jenkinsfile
Labels: area/backend

#10768 enh(ceip): add IT-100 Edition
  www/api/class/centreon_ceip.class.php
Labels: area/backend

#10822 fix(conf) fix multiple pollers conf export and host update (monitoring server)
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryFile.php
  www/include/configuration/configGenerate/common-Func.php
  www/include/configuration/configGenerate/xml/generateFiles.php
Labels: area/backend

#10832 fix(conf/traps) fix SQL injection
  www/class/centreonTraps.class.php
Labels: area/backend

#10831 fix(conf/traps) fix SQL injection
  www/class/centreonTraps.class.php
Labels: area/backend

#10826 Applying dark mode to services by Hostgroups
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
Labels: area/backend

#10836 fix(monitoring): fix regression on command line obfuscation
  src/Core/Application/RealTime/UseCase/FindService/FindService.php
Labels: area/backend

#10837 enh(graph): improve multiselect performance in graph page
  www/api/class/centreon_performance_service.class.php
Labels: area/backend

#10829 Mon 12129 identify cloud platform
  www/api/class/centreon_ceip.class.php
Labels: area/backend

#10839 fix(poller): Fixed SQL and added access rights checking
  src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#10842 fix(apiv1) Fixed wrong path on classes called
  www/api/class/centreon_configuration_objects.class.php
Labels: area/backend

#10840 fix(bug): Fix KB configuration
  www/include/Administration/parameters/DB-Func.php
Labels: area/backend

#10855 fix(ldap): Fix SQL request
  www/class/CentreonLDAPAdmin.class.php
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/list.php
Labels: area/backend

#10857 fix(ldap): Fix SQL queries
  www/class/centreonLDAP.class.php
  www/include/Administration/parameters/ldap/form.php
  www/include/Administration/parameters/ldap/list.php
Labels: area/backend

#10858 fix(ldap): Fix bad colomn name
  www/class/CentreonLDAPAdmin.class.php
Labels: area/backend

#10861 feat(api): manage metaservice notification policy
  config/routes/Centreon/configuration/notification_policy.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Engine/EngineService.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationRepositoryInterface.php
  src/Centreon/Domain/Engine/Interfaces/EngineConfigurationServiceInterface.php
  src/Centreon/Infrastructure/Engine/EngineConfigurationRepositoryRDB.php
  src/Core/Application/Configuration/Notification/Repository/ReadMetaServiceNotificationRepositoryInterface.php
  src/Core/Application/Configuration/NotificationPolicy/UseCase/FindMetaServiceNotificationPolicy.php
  src/Core/Domain/RealTime/Model/MetaService.php
  src/Core/Infrastructure/Configuration/NotificationPolicy/Api/FindMetaServiceNotificationPolicyController.php
  src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbReadMetaServiceNotificationRepository.php
  src/Core/Infrastructure/RealTime/Repository/MetaService/DbMetaServiceFactory.php
  src/Core/Infrastructure/RealTime/Repository/MetaService/DbReadMetaServiceRepository.php
  tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindMetaServiceNotificationPolicyTest.php
Labels: area/backend

#10862 doc(api): add api doc for notification policy endpoints
  doc/API/NotificationPolicy.yaml
  doc/API/centreon-api-v22.04.yaml
Labels: area/backend

#10863 enh(authentication): implement OpenID provider
  config/packages/Centreon.yaml
  config/routes/Centreon/security/authentication.yaml
  features/bootstrap/CustomViewsContext.php
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Authentication/UseCase/AuthenticateApi.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Contact/ContactService.php
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Centreon/Domain/Contact/Interfaces/ContactRepositoryInterface.php
  src/Centreon/Domain/Contact/Interfaces/ContactServiceInterface.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  src/Core/Application/Common/UseCase/AbstractPresenter.php
  src/Core/Application/Common/UseCase/PresenterInterface.php
  src/Core/Application/Security/UseCase/LoginOpenIdSession/LoginOpenIdSession.php
  src/Core/Application/Security/UseCase/LoginOpenIdSession/LoginOpenIdSessionPresenterInterface.php
  src/Core/Application/Security/UseCase/LoginOpenIdSession/LoginOpenIdSessionRequest.php
  src/Core/Application/Security/UseCase/LoginOpenIdSession/LoginOpenIdSessionResponse.php
  src/Core/Application/Security/UseCase/LoginSession/LoginSession.php
  src/Core/Domain/Security/Authentication/SSOAuthenticationException.php
  src/Core/Domain/Security/Provider/OpenIdProvider.php
  src/Core/Domain/Security/ProviderConfiguration/OpenId/Exceptions/OpenIdConfigurationException.php
  src/Core/Domain/Security/ProviderConfiguration/OpenId/Model/OpenIdConfiguration.php
  src/Core/Infrastructure/Security/Api/LoginOpenIdSession/LoginOpenIdSessionController.php
  src/Core/Infrastructure/Security/Api/LoginOpenIdSession/LoginOpenIdSessionPresenter.php
  src/Security/Domain/Authentication/Interfaces/LocalProviderInterface.php
  src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
  src/Security/Domain/Authentication/Interfaces/ProviderConfigurationInterface.php
  src/Security/Domain/Authentication/Interfaces/ProviderInterface.php
  src/Security/Domain/Authentication/Model/LocalProvider.php
  src/Security/Domain/Authentication/Model/ProviderConfiguration.php
  src/Security/Domain/Authentication/Model/ProviderFactory.php
  src/Security/Infrastructure/Repository/AuthenticationRepository.php
  tests/php/Centreon/Domain/Authentication/UseCase/AuthenticateApiTest.php
  tests/php/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusPresenterStub.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationPresenterFake.php
  tests/php/Core/Application/Security/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Application/Security/UseCase/LoginSession/LoginSessionTest.php
  tests/php/Security/Domain/Authentication/AuthenticationServiceTest.php
  www/class/centreonSession.class.php
  www/install/createTables.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10866 enh(api): Add interfaces for update web sso configuration use case
  config/routes/Centreon/administration/provider_configuration.yaml
  features/bootstrap/CustomViewsContext.php
  src/Centreon/Application/Controller/AbstractController.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/Repository/WriteWebSSOConfigurationRepositoryInterface.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/UpdateWebSSOConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/UpdateWebSSOConfigurationPresenterInterface.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/UpdateWebSSOConfigurationRequest.php
  src/Core/Domain/Security/ProviderConfiguration/WebSSO/Model/WebSSOConfiguration.php
  src/Core/Domain/Security/ProviderConfiguration/WebSSO/Model/WebSSOConfigurationFactory.php
  src/Core/Infrastructure/Security/Api/LoginSession/LoginSessionController.php
  src/Core/Infrastructure/Security/Api/RenewPassword/RenewPasswordController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/UpdateWebSSOConfiguration/UpdateWebSSOConfigurationController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/UpdateWebSSOConfiguration/UpdateWebSSOConfigurationSchema.json
  tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UpdateWebSSOConfiguration/UseCase/UpdateWebSSOConfigurationTest.php
  tests/php/Core/Infrastructure/Security/Api/RenewPassword/RenewPasswordControllerTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationControllerTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/UpdateWebSSOConfiguration/UpdateWebSSOConfigurationControllerTest.php
Labels: area/backend

#10869 fix(upgrade): add default openid configuration if no configuration was found
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10868 fix(ci): remove add widget from custom views tests
  features/bootstrap/CustomViewsContext.php
Labels: area/backend

#10872 fix(upgrade): use fetchAll in select openid query
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10819 enh(form) : removed centreon-cloud form on configuration > users > contact/user (MON-12218)
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/formContactCloud.ihtml
Labels: area/backend

#10867 fix(acl): use realtime calculated acl for notification policy
  src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  src/Core/Application/Configuration/NotificationPolicy/UseCase/FindMetaServiceNotificationPolicy.php
  src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  src/Core/Application/RealTime/Repository/ReadHostRepositoryInterface.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
  src/Core/Infrastructure/RealTime/Repository/Service/DbReadServiceRepository.php
  tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
  tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicyTest.php
Labels: area/backend

#10875 enh(api): add notification policy hypermedia
  config/packages/serializer/Centreon/Monitoring.ResourceLinksEndpoints.yml
  config/routes/centreon.yaml
  doc/API/ResourceHostDetail.yaml
  doc/API/ResourceServiceDetail.yaml
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Monitoring/ResourceLinksEndpoints.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/MetaServiceHyperMediaProvider.php
  tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/backend

#10874 fix(media): Fixed folder creation error when running simultaneously
  www/class/centreonMedia.class.php
Labels: area/backend

#10877 enh(api): add interfaces for get WebSSO configuration use case
  config/routes/Centreon/administration/provider_configuration.yaml
  phpstan.neon
  src/Core/Application/Security/ProviderConfiguration/WebSSO/Repository/ReadWebSSOConfigurationRepositoryInterface.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationPresenterInterface.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationResponse.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/FindWebSSOConfiguration/FindWebSSOConfigurationController.php
  tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationPresenterStub.php
  tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationTest.php
Labels: area/backend

#10878 enh(api): manage forbidden and payment required responses
  src/Core/Application/Common/UseCase/ForbiddenResponse.php
  src/Core/Application/Common/UseCase/PaymentRequiredResponse.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
Labels: area/backend

#10879 enh(api): implements infrastructure and response for find websso use case
  src/Centreon/Infrastructure/Repository/AbstractRepositoryDRB.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationResponse.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/FindWebSSOConfiguration/FindWebSSOConfigurationPresenter.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Repository/CustomConfigurationSchema.json
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Repository/DbReadWebSSOConfigurationRepository.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Repository/DbWebSSOConfigurationFactory.php
  tests/php/Core/Application/Security/ProviderConfiguration/WebSSO/UseCase/FindWebSSOConfiguration/FindWebSSOConfigurationTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Api/FindWebSSOConfiguration/FindWebSSOConfigurationControllerTest.php
Labels: area/backend

#10841 fix(poller): Fixed SQL and added access rights checking
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#10884 fix(install): allow centreon sql user to create view
  www/install/steps/process/createDbUser.php
Labels: area/backend

#10892 chore(install): update to version 21.04.13
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.13.php
Labels: area/backend

#10886 feat(UI): Login with openid connect
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Login/ExternalProviders.tsx
  www/front_src/src/Login/api/decoder.ts
  www/front_src/src/Login/api/endpoint.ts
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Login/index.tsx
  www/front_src/src/Login/models.ts
  www/front_src/src/Login/translatedLabels.ts
  www/front_src/src/Login/useLogin.ts
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Main/useMain.ts
  www/front_src/src/ResetPassword/index.test.tsx
Labels: area/authentication, kind/feature, area/ui, area/backend

#10887 Branch containing all changements for widgets
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/color.css
  www/class/centreonUser.class.php
Labels: area/backend

#10816 enh(Poller Wizard): refacto - poller Wizard
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/front_src/src/Extensions/translatedLabels.ts
  www/front_src/src/PollerWizard/forms/wizardButtons.tsx
  www/front_src/src/PollerWizard/models.ts
  www/front_src/src/PollerWizard/pollerAtoms.ts
  www/front_src/src/PollerWizard/pollerStep1/index.tsx
  www/front_src/src/PollerWizard/pollerStep2/index.tsx
  www/front_src/src/PollerWizard/pollerStep3/index.tsx
  www/front_src/src/PollerWizard/remoteServerStep1/index.tsx
  www/front_src/src/PollerWizard/remoteServerStep2/index.tsx
  www/front_src/src/PollerWizard/remoteServerStep3/index.tsx
  www/front_src/src/PollerWizard/serverConfigurationWizard/index.tsx
  www/front_src/src/PollerWizard/translatedLabels.ts
  www/front_src/src/components/WizardFormSetupStatus/index.tsx
  www/front_src/src/components/wizardFormInstallingStatus/index.js
  www/front_src/src/styles/partials/form/PollerWizardStyle.ts
Labels: area/ui

#10899 enh(api): add InvalidArgumentResponse to manage bad request
  src/Core/Application/Common/UseCase/InvalidArgumentResponse.php
  src/Core/Infrastructure/Common/Presenter/JsonPresenter.php
Labels: area/backend

#10897 enh(connectors): add the --log-file option for fresh installs
  www/install/insertBaseConf.sql
Labels: area/backend

#10901 fix(api): fix route generator
  config/services.yaml
  src/Core/Infrastructure/Common/Api/Router.php
Labels: area/backend

#10859 fix(sql) update files from 21.10.0 to 22.04.0
  www/install/php/Update-21.10.2.php
  www/install/php/Update-21.10.3.php
  www/install/php/Update-21.10.4.php
  www/install/php/Update-21.10.5.php
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10890 enh(useUser): consume theme api
  www/front_src/src/Main/useUser.ts
  www/front_src/src/api/decoders.ts
Labels: area/ui

#10896 fix(UI): Login form is blended with background on Firefox
  www/front_src/src/Login/index.tsx
Labels: area/ui

#10830 refactor(navigation): left menu
  composer.json
  composer.lock
  www/front_src/src/Header/userMenu/index.tsx
  www/front_src/src/Navigation/Sidebar/Logo/Centreon_Logo_Blanc.svg
  www/front_src/src/Navigation/Sidebar/Logo/Centreon_Logo_Noir_RVB.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/Centreon_Logo_Blanc_C.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/Centreon_Logo_Noir_RVB_C.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/centreon-logo-mini.svg
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/index.js
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/index.tsx
  www/front_src/src/Navigation/Sidebar/Logo/LogoMini/logo-mini.scss
  www/front_src/src/Navigation/Sidebar/Logo/index.js
  www/front_src/src/Navigation/Sidebar/Logo/index.tsx
  www/front_src/src/Navigation/Sidebar/Logo/logo.scss
  www/front_src/src/Navigation/Sidebar/Menu/ArrowIcon.tsx
  www/front_src/src/Navigation/Sidebar/Menu/BoundingBox/helpers.js
  www/front_src/src/Navigation/Sidebar/Menu/BoundingBox/index.js
  www/front_src/src/Navigation/Sidebar/Menu/CollapsibleItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.js
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
  www/front_src/src/Navigation/Sidebar/Menu/menu.scss
  www/front_src/src/Navigation/Sidebar/index.js
  www/front_src/src/Navigation/Sidebar/index.tsx
  www/front_src/src/Navigation/Sidebar/sideBarAtoms.ts
  www/front_src/src/Navigation/Sidebar/sidebar.scss
  www/front_src/src/Navigation/index.tsx
Labels: area/ui

#10889 fix(ui):Fixed some data-testid for pendo
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
Labels: area/ui

#10910 enh(pollerWizard): Delete unused js and scss files
  www/front_src/src/PollerWizard/forms/ServerConfigurationWizardForm.js
  www/front_src/src/PollerWizard/forms/poller/PollerFormStepOne.js
  www/front_src/src/PollerWizard/forms/poller/PollerFormStepTwo.jsx
  www/front_src/src/PollerWizard/forms/poller/PollerFormStepTwo.test.jsx
  www/front_src/src/PollerWizard/forms/remoteServer/RemoteServerFormStepOne.js
  www/front_src/src/PollerWizard/forms/remoteServer/RemoteServerFormStepTwo.js
  www/front_src/src/components/form-fields/CheckboxField.js
  www/front_src/src/components/form-fields/InputField.js
  www/front_src/src/components/form-fields/PreselectedRadioField.js
  www/front_src/src/components/form-fields/RadioField.js
  www/front_src/src/components/form-fields/RadioGroupFields.js
  www/front_src/src/components/form-fields/SelectField.js
  www/front_src/src/components/form-fields/getErrorMsg.js
  www/front_src/src/components/form-fields/hoc.js
  www/front_src/src/components/form-fields/utils.js
  www/front_src/src/styles/partials/form/_form.scss
Labels: area/ui

#10919 enh(resources status): Created new tables for resources status
  www/install/createTablesCentstorage.sql
  www/install/sql/centstorage/Update-CSTG-22.04.0-beta.1.sql
Labels: area/backend

#10917 fix(test): fix downtime acceptance tests
  features/bootstrap/DowntimeRecurrentContext.php
  features/bootstrap/DowntimeStartAndStopContext.php
Labels: area/backend

#10911 feat(auth): implements WebSSO authentication
  config/packages/Centreon.yaml
  config/routes/Centreon/security/authentication.yaml
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Domain/Security/Authentication/SSOAuthenticationException.php
  src/Core/Domain/Security/Provider/WebSSOProvider.php
  src/Core/Domain/Security/ProviderConfiguration/WebSSO/Model/WebSSOConfiguration.php
  src/Core/Infrastructure/Security/ProviderConfiguration/WebSSO/Repository/DbWebSSOConfigurationFactory.php
  src/EventSubscriber/WebSSOEventSubscriber.php
  src/Security/Domain/Authentication/Interfaces/WebSSOProviderInterface.php
  src/Security/Domain/Authentication/Model/ProviderFactory.php
  tests/php/EventSubscriber/WebSSOEventSubscriberTest.php
  www/include/core/header/header.php
  www/index.php
Labels: area/backend
