Repository centreon/centreon, pull requests merged in 2022-09, with the labels that each got.

#11662 enh(conf) migrate acls for pollers page actions
  www/install/insertTopology.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11658 fix(upgrade): Correctly Parse SQL Comments
  src/Core/Platform/Infrastructure/Repository/DbWriteUpdateRepository.php
Labels: area/backend

#11668 fix(upgrade): Correctly Parse SQL Comments (#11658)
  src/Core/Platform/Infrastructure/Repository/DbWriteUpdateRepository.php
Labels: area/backend

#11669 fix(upgrade): fix invalid values for index_data.special
  www/install/sql/centstorage/Update-CSTG-22.04.4.sql
Labels: area/backend

#11671 fix(conf) fix parent template display in service template listing
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11667 Sanitize and bind service group dependecies queries 21.04.x
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
Labels: area/backend

#11677 fix(conf) fix parent template display in service template listing (#11671)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11678 fix(conf) fix parent template display in service template listing (#11671)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11657 fix(partition): fix condition for database version
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#11256 [Snyk] Sanitize and bind "common/common-Func" queries
  www/include/common/common-Func.php
Labels: area/backend

#11479 [fix]MON-13067-install-remove-default-value-for-colors-in-options-table-for-develop
  www/class/centreonGraph.class.php
  www/class/centreonGraphNg.class.php
  www/include/monitoring/objectDetails/serviceDetails.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11672 fix(details): remove dead code
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#11641 fix(resource-status): add missing alias to Host detail factory
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
Labels: area/backend

#11675 fix(poller): fix remote server duplication (#11552)
  bin/registerServerTopology.sh
  config/json_validator/latest/Centreon/PlatformInformation/Update.json
  doc/API/centreon-api-v21.10.yaml
  src/Centreon/Application/ApiPlatform.php
  src/Centreon/Domain/PlatformInformation/Model/PlatformInformation.php
  src/Centreon/Domain/PlatformInformation/Model/PlatformInformationFactory.php
  src/Centreon/Domain/PlatformInformation/UseCase/V20/UpdatePartiallyPlatformInformation.php
  src/Centreon/Domain/PlatformTopology/Model/PlatformPending.php
  src/Centreon/Domain/PlatformTopology/Model/PlatformRegistered.php
  src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  src/Centreon/Domain/RemoteServer/Interfaces/RemoteServerRepositoryInterface.php
  src/Centreon/Domain/RemoteServer/RemoteServerService.php
  src/Centreon/Infrastructure/RemoteServer/RemoteServerRepositoryRDB.php
  src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php
  src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  src/EventSubscriber/CentreonEventSubscriber.php
  tests/api/features/PlatformTopology.feature
  www/api/class/centreon_configuration_poller.class.php
  www/class/centreonStatistics.class.php
  www/include/configuration/configServers/DB-Func.php
  www/include/configuration/configServers/popup/popup.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.10.php
Labels: area/backend

#11660 feat(select2): adds poller acl into the select2 list
  www/class/centreonInstance.class.php
Labels: area/backend

#11687 chore(ci): remove codesee from workflow
  .github/workflows/codesee-arch-diagram.yml
Labels: area-ci

#11684 fix(details): remove dead code (#11672)
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#11686 fix(details): remove dead code (#11672)
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#11676 fix(conf) fix parent template display in service template listing (#11671)
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11659 fix(ui): fix svg display in legacy monitoring pages for firefox
  www/include/monitoring/status/Services/xsl/serviceGrid.xsl
  www/include/monitoring/status/Services/xsl/serviceSummary.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceGridByHG.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceSummaryByHG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceGridBySG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceSummaryBySG.xsl
Labels: area/backend

#11640 fix(clapi): Check that user is admin to use clapi (#11631)
  www/api/class/centreon_clapi.class.php
Labels: area/backend

#11639 fix(clapi): Check that user is admin to use clapi (#11631)
  www/api/class/centreon_clapi.class.php
Labels: area/backend

#11638 fix(clapi): Check that user is admin to use clapi (#11631)
  www/api/class/centreon_clapi.class.php
Labels: area/backend

#11670 fix(upgrade): fix invalid values for index_data.special
  www/install/sql/Update-CSTG-22.04.4.sql
Labels: area/backend

#11653 [SNYK] Sanitize and bind service arguments xml queries
  www/include/configuration/configObject/service/xml/argumentsXml.php
Labels: area/backend

#11647 [SNYK] Sanitize and bind listVirtualMetrics queries
  www/include/views/virtualMetrics/listVirtualMetrics.php
Labels: area/backend

#11656 [SNYK] : MON-14671-sanitize-and-bind-update-22-04-0-beta-1-queries
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#11690 fix(ui): fix svg display in legacy monitoring pages (#11659)
  www/include/monitoring/status/Services/xsl/serviceGrid.xsl
  www/include/monitoring/status/Services/xsl/serviceSummary.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceGridByHG.xsl
  www/include/monitoring/status/ServicesHostGroups/xsl/serviceSummaryByHG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceGridBySG.xsl
  www/include/monitoring/status/ServicesServiceGroups/xsl/serviceSummaryBySG.xsl
Labels: area/backend

#11643 feat(php-cs-fixer)MON-14576 integrate php cs fixer to centreon web
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
Labels: area/backend

#11665 Sanitize and bind service group dependecies queries 22.04.x
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
Labels: area/backend

#11693 fix spelling of some words in french
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#11666 Sanitize and bind service group dependecies queries 21.10.x
  www/include/configuration/configObject/servicegroup_dependency/DB-Func.php
Labels: area/backend

#11618 enh(Resources/header): Display the 2 access pictograms logs and report on details panel
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/helpers.ts
Labels: area/ui

#11642 fix(resource-status): add missing alias to Host detail factory
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
Labels: area/backend

#11696 fix(widgets): retrieve possibility to not select poller in preferences
  www/class/centreonWidget/Params/Connector/Poller.class.php
Labels: area/backend

#11694 fix(install): fix source install with quiet mode related to gorgone vars
  install.sh
  tmpl/vardistrib/defaults
Labels: area/backend

#11698 fix(widgets): retrieve possibility to not select poller in pref (#11696)
  www/class/centreonWidget/Params/Connector/Poller.class.php
Labels: area/backend

#11699 fix(widgets): retrieve possibility to not select poller in pref (#11696)
  www/class/centreonWidget/Params/Connector/Poller.class.php
Labels: area/backend

#11700 fix(widgets): retrieve possibility to not select poller in pref (#11696)
  www/class/centreonWidget/Params/Connector/Poller.class.php
Labels: area/backend

#11701 fix(install): fix source install with quiet mode related to gorgone vars
  install.sh
  tmpl/vardistrib/defaults
Labels: area/backend

#11695 Fix: In Acces group the second select not working [ACL]
  www/include/options/accessLists/groupsACL/groupsConfig.php
Labels: area/backend

#11709 Fix: In Acces group the second select not working [ACL] 22.04.x
  www/include/options/accessLists/groupsACL/groupsConfig.php
Labels: area/backend

#11710 Fix: In Acces group the second select not working [ACL] 21.10.x
  www/include/options/accessLists/groupsACL/groupsConfig.php
Labels: area/backend

#11330 fix(web): enable the deletion of text parameters on contacts
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#11685 fix(details): remove dead code (#11672)
  www/include/monitoring/objectDetails/hostDetails.php
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#11718 fix(details): second part of code cleanup for "tools"
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11715 feat(generate): add platform uuid to lua parameters for AD
  www/class/config-generate/broker.class.php
Labels: area/backend

#11721 fix(details): second part of code cleanup for "tools" (#11718)
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11722 fix(details): second part of code cleanup for "tools" (#11718)
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11725 fix(details): second part of code cleanup for "tools"
  www/include/monitoring/objectDetails/template/hostDetails.ihtml
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11713 Fix: Sanitize and bind CLAPI poller configuration
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#10147 enh(comment): not empty
  src/Centreon/Domain/Monitoring/Comment/Comment.php
Labels: pr/external

#11723 FIX: Sanitize and bind graph configuration queries
  www/class/centreonGraph.class.php
Labels: area/backend

#11702 fix(resource): Fix bad SQL request
  www/include/configuration/configResources/DB-Func.php
Labels: area/backend

#11719 enh(enginecfg): some of engines informational messages are useful
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagiosLogger.php
  www/install/var/baseconf/centreon-engine.sql
Labels: area/backend

#11732 Fix: Sanitize and bind CLAPI poller configuration 21.10.x
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#11703 fix(ACL) update acl actions during user navigation
  config/packages/Centreon.yaml
  www/api/class/centreon_topcounter.class.php
  www/class/centreon-clapi/Repository/AclGroupRepository.php
  www/class/centreon-clapi/Repository/SessionRepository.php
  www/class/centreon-clapi/centreonACLAction.class.php
  www/class/centreon-clapi/centreonACLGroup.class.php
  www/include/core/header/header.php
  www/include/options/accessLists/actionsACL/DB-Func.php
  www/include/options/accessLists/actionsACL/actionsConfig.php
  www/include/options/accessLists/actionsACL/formActionsAccess.php
Labels: area/backend

#11726 fix(conf) broken translations in acl access page
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/options/accessLists/actionsACL/formActionsAccess.php
Labels: area/documentation, area/backend

#11727 update tss-react dependecy
  package-lock.json
  package.json
Labels: area/ui

#11734 FIX: Sanitize and bind Meta Service configuration 21.10.x
  www/class/centreonMeta.class.php
Labels: area/backend

#11697 Fix (UI): Fix lighthouse accessibility errors
  package-lock.json
  tests/e2e/cypress/integration/Resources-status/02-actions/index.ts
  www/front_src/src/Authentication/Local/StrengthProgress.tsx
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  www/front_src/src/Resources/Actions/Resource/ResourceActionButton.tsx
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/components/Wallpaper/BackgroundImage.tsx
Labels: area/ui

#11724 fix(Resources/details):white page shown when clicking host resource status
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: area/ui

#11729 FIX: Sanitize and bind graph configuration queries 22.04.x
  www/class/centreonGraph.class.php
Labels: area/backend

#11728 [Fix]:Sanitize and bind queries in template of service listing
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11745 [Fix]: Sanitize and bind queries in template of service listing
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11717 fix(Header): top counters are no longer collapsable
  package-lock.json
  package.json
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/userMenu/index.tsx
  www/front_src/src/federatedModules/Load/index.tsx
Labels: area/ui

#11735 FIX: Sanitize and bind command configuration queries
  www/include/common/javascript/commandGetArgs/cmdGetExample.php
Labels: area/backend

#11746 [Fix]:Sanitize and bind queries in template of service listing
  www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#11733 FIX: Sanitize and bind Meta Service configuration 22.04.x
  www/class/centreonMeta.class.php
Labels: area/backend

#11731 Fix: Sanitize and bind CLAPI poller configuration 22.04.x
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#11755 FIX: Sanitize and bind command configuration queries 21.10.x
  www/include/common/javascript/commandGetArgs/cmdGetExample.php
Labels: area/backend

#11754 FIX: Sanitize and bind command configuration queries 22.04.x
  www/include/common/javascript/commandGetArgs/cmdGetExample.php
Labels: area/backend

#11744 enh(openid): update configuration form to handle auth conditions
  src/Core/Security/AccessGroup/Infrastructure/Repository/DbReadAccessGroupRepository.php
  src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/AuthenticationConditions.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/OpenIdCustomConfigurationInterface.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11741 [Style]: MBI Widgets are not readable in dark mode
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
Labels: area/backend

#11080 fix(conf): fix disabling additive inheritance
  www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#11712 Export timelines for host
  config/routes/Centreon/monitoring/timeline.yaml
  src/Centreon/Application/Controller/Monitoring/TimelineController.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHost.php
  src/Core/Application/RealTime/UseCase/FindService/FindService.php
  src/Core/Infrastructure/RealTime/Api/FindHost/FindHostPresenter.php
  src/Core/Infrastructure/RealTime/Api/FindMetaService/FindMetaServicePresenter.php
  src/Core/Infrastructure/RealTime/Api/FindService/FindServicePresenter.php
  src/Core/Infrastructure/RealTime/Hypermedia/AbstractHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Hypermedia/MetaServiceHypermediaProvider.php
  src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
Labels: area/backend

#11767 fix(openid): Fix Authentications condition endpoint
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Exceptions/InvalidEndpointException.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/AuthenticationConditions.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/Endpoint.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  www/install/insertBaseConf.sql
Labels: area/backend

#11286 fix(web): display command with status$ in the command definition
  src/Centreon/Domain/Monitoring/CommandLineTrait.php
Labels: area/backend

#11704 feat(Resources/Timeline): export csv from timeline
  package-lock.json
  package.json
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/ExportToCsv.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  www/front_src/src/Resources/models.ts
Labels: area/ui

#11760 FIX: SQLi in poller's broker configuration
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/DB-Func.php
Labels: area/backend

#11772 Fix: Sanitize and bind Media import
  www/class/centreonMedia.class.php
Labels: area/backend

#11766 Fix: Remove obsolete code in ACL configuration listing
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
  www/include/options/accessLists/menusACL/listsMenusAccess.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
Labels: area/backend

#11758 [Fix]: Sanitize and bind service by hostgroups listing
  www/include/configuration/configObject/service/listServiceByHostGroup.php
Labels: area/backend

#11761 Fix : Sanitize and bind centreon hostgroups class
  www/class/centreonHostgroups.class.php
Labels: area/backend

#11780 Fix: Sanitize and bind CLAPI Centreon Hostgroup class
  www/class/centreon-clapi/centreonHostGroup.class.php
Labels: area/backend

#11706 fix(centreontrapd): check if conf file is not empty before to load it
  lib/perl/centreon/script.pm
Labels: area/backend

#11757 FIX: Sanitize and bind Centreon Notification class
  www/class/centreonNotification.class.php
Labels: area/backend

#11764 FIX: Sanitize and bind LDAP CLAPI listing
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#11769 FIX: Sanitize and bind service listing
  www/include/configuration/configObject/service/listServiceByHost.php
Labels: area/backend

#11759 enh(UI): Enhance lighthouse performance report
  lighthouse/lighthouseReport.ts
  package-lock.json
  package.json
  webpack.config.js
  www/front_src/src/App/index.tsx
  www/front_src/src/App/useApp.ts
  www/front_src/src/Header/index.tsx
  www/front_src/src/Login/Logo.tsx
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Login/index.tsx
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Main/useMain.ts
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
  www/front_src/src/Navigation/Sidebar/index.tsx
  www/front_src/src/Resources/Listing/columns/Graph.tsx
  www/front_src/src/Resources/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
Labels: area/ui

#11782 FIX: Sanitize and bind SNMP Traps groups configuration
  www/include/configuration/configObject/traps-groups/DB-Func.php
Labels: area/backend

#11748 FIX: Sanitize and bind default configuration queries
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#11737 feat: MON-13253 standardization of invalid license messages
  .gitignore
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- displays the direct child items and highlights the item when hovered.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- expands the menu when the logo is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- highlights the menu item when double clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- highlights the parent item when the item is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- matches the current snapshot initial menu.snap.png
  cypress/visual-testing-snapshots/All Specs/User Menu --  style change for darklight texts when switch is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/User Menu -- expands the popper when the user icon is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/User Menu -- matches the current snapshot user menu.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- expands the popper when the user icon is clicked.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- expect the clock to not be visible for a width less than 648px.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- matches the current snapshot user menu.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- using the dark mode.snap.png
  cypress/visual-testing-snapshots/Header/userMenu/index.cypress.spec.tsx/User Menu -- using the light mode.snap.png
  jest.config.js
  package-lock.json
  package.json
  www/front_src/src/FallbackPages/CommonFallback.tsx
  www/front_src/src/FallbackPages/NotAllowedPage/index.tsx
  www/front_src/src/FallbackPages/NotAllowedPage/translatedLabels.ts
  www/front_src/src/FallbackPages/NotFoundPage/index.tsx
  www/front_src/src/FallbackPages/NotFoundPage/translatedLabels.ts
  www/front_src/src/Header/userMenu/index.cypress.spec.tsx
  www/front_src/src/Navigation/useNavigation.ts
  www/front_src/src/components/ReactRouter/index.test.tsx
Labels: area/ui

#11814 Fix: Sanitize and bind SNMP Traps listing
  www/include/configuration/configObject/traps/listTraps.php
Labels: area/backend

#11810 Fix: Remove obsolete code in database partitioning functions
  www/class/centreon-partition/partEngine.class.php
Labels: area/backend

#11783 Fix: Remove obsolete code in Criticality class
  www/class/centreonCriticality.class.php
Labels: area/backend

#11815 Fix: Remove obsolete code in monitoring common functions
  www/include/monitoring/common-Func.php
Labels: area/backend

#11742 FIX: Removing unused code and fixing bug of generating csv in multiple periods graphs
  www/include/views/graphs/exportData/ExportCSVMetricData.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/include/views/graphs/graph-periods.html
Labels: area/backend

#11771 FIX: Remove unused mechanism for modules to add restart/reload actions after restart of pollers
  www/class/centreon.class.php
  www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend

#11823 enh(openid): enhance OpenID Configuration to handle groups mapping
  src/Core/Contact/Application/Repository/ReadContactGroupRepositoryInterface.php
  src/Core/Contact/Infrastructure/Repository/DbReadContactGroupRepository.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/Repository/ReadOpenIdConfigurationRepositoryInterface.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/ContactGroupRelation.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/Endpoint.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/GroupsMapping.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbReadOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  www/class/centreonUser.class.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
Labels: area/backend

#11831 fix(websso): Correctly set contact theme while authenticating with WebSSO
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
Labels: area/backend

#11818 fix(host) fix isActivated variable in updateHost
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#11830 fix(websso): Correctly set contact theme while authenticating with WebSSO 22.04.x
  src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  src/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSession.php
  src/EventSubscriber/WebSSOEventSubscriber.php
Labels: area/backend

#11793 Fix: Remove obsolete code in ACL configuration listing dev2210x
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
  www/include/options/accessLists/menusACL/listsMenusAccess.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
Labels: area/backend

#11795 [Fix]: Sanitize and bind service by hostgroups listing dev-22.10.x
  www/include/configuration/configObject/service/listServiceByHostGroup.php
Labels: area/backend

#11800 Fix : Sanitize and bind centreon hostgroups class dev-21.10.x
  www/class/centreonHostgroups.class.php
Labels: area/backend

#11803 Fix: Sanitize and bind CLAPI Centreon Hostgroup class dev-22.04.x
  www/class/centreon-clapi/centreonHostGroup.class.php
Labels: area/backend

#11805 Fix: Sanitize and bind host category listing dev-21.10.x
  www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend

#11762 feat(authentication): manage openid role mapping
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Core/Security/Authentication/Application/UseCase/Login/ErrorAclConditionsResponse.php
  src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  src/Core/Security/Authentication/Domain/Exception/AclConditionsException.php
  src/Core/Security/Authentication/Domain/Exception/SSOAuthenticationException.php
  src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Exceptions/ACLConditionsException.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/ACLConditions.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/AuthorizationRule.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/Endpoint.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/ProviderConfiguration/Domain/Model/ACLConditionsTest.php
  tests/php/Core/Security/ProviderConfiguration/Domain/Model/EndpointTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11833 fix(conf/export) broker RRDcacheD export (#11811)
  www/class/config-generate/broker.class.php
Labels: area/backend

#11834 fix(conf/export) broker RRDcacheD export (#11811)
  www/class/config-generate/broker.class.php
Labels: area/backend

#11835 fix(host) fix isActivated variable in updateHost (#11818)
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#11778 FIX: SQLi in poller's broker configuration 21.10.x
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/DB-Func.php
Labels: area/backend

#11779 FIX: SQLi in poller's broker configuration 21.04.x
  www/class/centreonConfigCentreonBroker.php
  www/include/configuration/configCentreonBroker/DB-Func.php
Labels: area/backend

#11787 FIX: Sanitize and bind default configuration queries 21.10.x
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#11786 FIX: Sanitize and bind default configuration queries 22.04.x
  www/install/steps/process/insertBaseConf.php
Labels: area/backend

#11792 FIX: Sanitize and bind Centreon Notification class 21.10.x
  www/class/centreonNotification.class.php
Labels: area/backend

#11790 FIX: Sanitize and bind Centreon Notification class 22.04.x
  www/class/centreonNotification.class.php
Labels: area/backend

#11797 FIX: Sanitize and bind LDAP CLAPI listing 21.10.x
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#11794 FIX: Sanitize and bind LDAP CLAPI listing 22.04.x
  www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#11799 FIX: Sanitize and bind service listing 22.04.x
  www/include/configuration/configObject/service/listServiceByHost.php
Labels: area/backend

#11801 FIX: Sanitize and bind service listing 21.10.x
  www/include/configuration/configObject/service/listServiceByHost.php
Labels: area/backend

#11807 FIX: Sanitize and bind SNMP Traps groups configuration 21.10.x
  www/include/configuration/configObject/traps-groups/DB-Func.php
Labels: area/backend

#11847 FIX: Sanitize and bind Knowledge Base host listing
  www/class/centreon-knowledge/procedures.class.php
Labels: area/backend

#11816 enh(resources): fetch ack / dt in detail only if needed
  src/Core/Application/RealTime/UseCase/FindHost/FindHost.php
  src/Core/Application/RealTime/UseCase/FindMetaService/FindMetaService.php
  src/Core/Application/RealTime/UseCase/FindService/FindService.php
  tests/php/Core/Application/RealTime/UseCase/FindHost/FindHostTest.php
  tests/php/Core/Application/RealTime/UseCase/FindMetaService/FindMetaServiceTest.php
  tests/php/Core/Application/RealTime/UseCase/FindService/FindServiceTest.php
Labels: area/backend

#11796 [Fix]: Sanitize and bind service by hostgroups listing dev-22.04.x
  www/include/configuration/configObject/service/listServiceByHostGroup.php
Labels: area/backend

#11842 Fix: Sanitize and bind SNMP Traps listing dev-21.10.x
  www/include/configuration/configObject/traps/listTraps.php
Labels: area/backend

#11843 Fix: Sanitize and bind SNMP Traps listing dev-22.04.x
  www/include/configuration/configObject/traps/listTraps.php
Labels: area/backend

#11840 Fix: Remove obsolete code in Criticality class dev-22.04.x
  www/class/centreonCriticality.class.php
Labels: area/backend

#11841 Fix: Remove obsolete code in Criticality class dev.21.10.x
  www/class/centreonCriticality.class.php
Labels: area/backend

#11854 FIX: Remove unused mechanism for modules to add restart/reload actions after restart of pollers 22.04.x
  www/class/centreon.class.php
  www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend

#11855 FIX: Remove unused mechanism for modules to add restart/reload actions after restart of pollers 21.10.x
  www/class/centreon.class.php
  www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend

#11806 FIX: Sanitize and bind SNMP Traps groups configuration 22.04.x
  www/include/configuration/configObject/traps-groups/DB-Func.php
Labels: area/backend

#11856 FIX: Removing unused code and fixing bug of generating csv in multiple periods graphs 22.04.x
  www/include/views/graphs/exportData/ExportCSVMetricData.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/include/views/graphs/graph-periods.html
Labels: area/backend

#11857 FIX: Removing unused code and fixing bug of generating csv in multiple periods graphs 21.10.x
  www/include/views/graphs/exportData/ExportCSVMetricData.php
  www/include/views/graphs/generateGraphs/generateImage.php
  www/include/views/graphs/graph-periods.html
Labels: area/backend

#11791 Fix: Remove obsolete code in ACL configuration listing dev2204x
  www/include/options/accessLists/actionsACL/listsActionsAccess.php
  www/include/options/accessLists/menusACL/listsMenusAccess.php
  www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
Labels: area/backend

#11859 FIX: Sanitize and bind Knowledge Base host listing 21.10.x
  www/class/centreon-knowledge/procedures.class.php
Labels: area/backend

#11822 FIX: Sanitize and bind Centreon Service class
  www/class/centreonService.class.php
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
Labels: area/backend

#11853 (fix) remove required parameters for openid
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
Labels: area/backend

#11849 fix(db): change type of notification_number column
  www/class/centreonDB.class.php
  www/install/installBroker.sql
  www/install/php/Update-22.10.0-beta.1.php
  www/install/sql/centstorage/Update-CSTG-22.04.4.sql
Labels: area/backend

#11861 (fix) fix openid roles mapping
  src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/OpenIdCustomConfigurationInterface.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
  tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  www/install/insertBaseConf.sql
Labels: area/backend

#11864 FIX: Sanitize and bind Centreon Service class 22.04.x
  www/class/centreonService.class.php
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
Labels: area/backend

#11865 FIX: Sanitize and bind Centreon Service class 21.10.x
  www/class/centreonService.class.php
  www/include/configuration/configKnowledge/display-hostTemplates.php
  www/include/configuration/configKnowledge/display-hosts.php
  www/include/configuration/configKnowledge/display-serviceTemplates.php
  www/include/configuration/configKnowledge/display-services.php
Labels: area/backend

#11862 fix(db): change type of notification_number column dev-22.04.x
  www/class/centreonDB.class.php
  www/install/installBroker.sql
  www/install/php/Update-22.04.6.php
Labels: area/backend

#11863 fix(db): change type of notification_number column dev-21.10.x
  www/class/centreonDB.class.php
  www/install/installBroker.sql
  www/install/php/Update-21.10.11.php
Labels: area/backend

#11850 fix(api): Fix warning message when calling the "platform/versions" API
  src/Centreon/Application/Controller/PlatformController.php
Labels: area/backend

#11867 fix(acl) add missing acl actions in clapi commands
  www/class/centreon-clapi/centreonACLAction.class.php
Labels: area/backend

#11804 Fix: Sanitize and bind host category listing dev-22.04.x
  www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend

#11860 FIX: Remove unused AppKey for Remote Server
  src/Centreon/Domain/Service/AppKeyGeneratorService.php
  src/Centreon/ServiceProvider.php
  src/Centreon/Tests/AppKeyGeneratorServiceTest.php
  src/Centreon/Tests/ServiceProviderTest.php
  src/CentreonRemote/Domain/Service/TaskService.php
  src/CentreonRemote/ServiceProvider.php
  www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#11773 improve authentication conditions and roles mapping
  lighthouse/package-lock.json
  lighthouse/pages/authentication.ts
  package-lock.json
  www/front_src/src/Authentication/Openid/Description.tsx
  www/front_src/src/Authentication/Openid/Form/index.tsx
  www/front_src/src/Authentication/Openid/Form/inputs.ts
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/Openid/models.ts
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
  www/front_src/src/Authentication/Openid/useValidationSchema.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Authentication/translatedLabels.ts
Labels: area/ui
