Repository centreon/centreon, pull requests merged in 2022-02, with the labels that each got.

#10602 enh(UI): Remove tooltip for action_URL and displaying label on tooltip for No…
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
Labels: area/ui

#10569 fix(UI): Change criteria name Resource by Type in resource status filter menu
  package-lock.json
  www/front_src/src/Resources/Filter/Criterias/models.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#10608 Revert "enh(UI): Remove tooltip for action_URL and displaying label on tooltip for No…"
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
Labels: area/ui

#10604 enh(sec): get excluded users from password expiration policy
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationResponse.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationRequest.php
  src/Core/Domain/Configuration/User/Model/User.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/Configuration.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/ConfigurationFactory.php
  src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/FindConfiguration/FindConfigurationPresenter.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/CustomConfigurationSchema.json
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbReadConfigurationRepository.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbWriteConfigurationRepository.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationTest.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactoryTest.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10646 fix(UI): Expand "Configure pollers" button to full width
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.test.tsx
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Provider/decoder.ts
  www/front_src/src/Provider/index.test.tsx
  www/front_src/src/Provider/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/storedDetailsCards.ts
Labels: area/ui

#10611 enh(install): allow installation to use existing database and database user
  src/CentreonLegacy/Core/Install/Step/AbstractStep.php
  www/install/steps/process/createDbUser.php
  www/install/steps/process/installConfigurationDb.php
  www/install/steps/process/installStorageDb.php
  www/install/steps/templates/content.tpl
Labels: area/backend

#10598 fix(upgrade): move upgrade script to 21.10.4
  www/install/php/Update-21.10.3.php
  www/install/php/Update-21.10.4.php
Labels: area/backend

#10596 fix(generateImage): set upper_limit only if it is set
  www/class/centreonGraph.class.php
Labels: area/backend

#10652 feat(api): implement find users endpoint
  config/routes/Centreon/user.yaml
  doc/API/centreon-api-v22.04.yaml
  src/Core/Application/Configuration/User/Repository/ReadUserRepositoryInterface.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsers.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersErrorResponse.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersPresenterInterface.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersResponse.php
  src/Core/Domain/Configuration/User/Model/User.php
  src/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersController.php
  src/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenter.php
  src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  tests/api/behat.yml
  tests/api/features/ConfigurationUsers.feature
  tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersControllerTest.php
  tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
Labels: area/backend

#10648 fix(ui) : kept timeperiod in service reporting page
  www/include/reporting/dashboard/DB-Func.php
  www/include/reporting/dashboard/template/viewServicesLog.ihtml
  www/include/reporting/dashboard/viewServicesLog.php
Labels: area/backend

#10610 enh(conf/host) Updating the host updates the host groups
  src/Centreon/Domain/HostConfiguration/Interfaces/HostGroup/HostGroupReadRepositoryInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
Labels: area/backend

#10651 chore(deps): Update dependencies
  jest.config.js
  package-lock.json
  package.json
  www/front_src/src/App.tsx
  www/front_src/src/Extensions/index.js
  www/front_src/src/Header/userMenu/index.js
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/filterAtoms.ts
  www/front_src/src/Resources/Listing/index.test.tsx
  www/front_src/src/axios/index.js
  www/front_src/src/redux/actions/externalComponentsActions.js
  www/front_src/src/redux/actions/navigationActions.js
  www/front_src/src/route-components/pollerStep1/index.js
  www/front_src/src/route-components/pollerStep2/index.js
  www/front_src/src/route-components/remoteServerStep1/index.js
  www/front_src/src/route-components/remoteServerStep2/index.js
  www/front_src/src/route-components/remoteServerStep3/index.js
Labels: area/ui

#10663 enh(stats) : improve centreon stats files
  cron/centreon-send-stats.php
  www/class/centreonStatsModules.class.php
Labels: area/backend

#10528 enh(UI): Rework detail panel chip to add action on hover Chip
  config/packages/serializer/Centreon/Monitoring.ResourceGroup.yml
  src/Centreon/Application/Controller/MonitoringResourceController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Domain/Monitoring/ResourceGroup.php
  www/front_src/src/Resources/Details/index.test.tsx
  www/front_src/src/Resources/Details/models.ts
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/GroupChip.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/Groups.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: area/ui

#10660 enh(api): update PUT provider configuration to exclude user
  src/Core/Application/Configuration/User/Repository/ReadUserRepositoryInterface.php
  src/Core/Application/Security/ProviderConfiguration/Local/Repository/WriteConfigurationRepositoryInterface.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationRequest.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/Configuration.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/ConfigurationFactory.php
  src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationSchema.json
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbReadConfigurationRepository.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbWriteConfigurationRepository.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationControllerTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactoryTest.php
Labels: area/backend

#10666 fix(resource): do not display cancelled downtimes
  src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#10594 fix(reporting): sanitize inputs on init
  www/include/reporting/dashboard/initReport.php
Labels: area/backend

#10679 fix(contact): fix password expiration message
  www/class/centreonContact.class.php
  www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#10678 Mon 12198 improve sql queries by escaping special character
  src/Centreon/Infrastructure/Monitoring/Resource/Provider/ServiceProvider.php
  www/api/class/centreon_performance_service.class.php
  www/api/class/centreon_realtime_hosts.class.php
  www/api/class/centreon_realtime_services.class.php
  www/api/class/centreon_topcounter.class.php
  www/class/centreonMonitoring.class.php
  www/class/centreonPerformanceService.class.php
  www/include/monitoring/status/Hosts/xml/hostXML.php
  www/include/monitoring/status/Notifications/notifications.php
  www/include/monitoring/status/Services/xml/serviceGridXML.php
  www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  www/include/monitoring/status/Services/xml/serviceXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
Labels: area/backend

#10683 Mon 11780 metaservice detail refacto implementation
  src/Core/Application/RealTime/UseCase/FindMetaService/FindMetaService.php
  src/Core/Application/RealTime/UseCase/FindMetaService/FindMetaServiceResponse.php
  src/Core/Domain/Configuration/Model/MetaService.php
  src/Core/Domain/RealTime/Model/MetaService.php
  src/Core/Infrastructure/Configuration/MetaService/Repository/DbMetaServiceFactory.php
  src/Core/Infrastructure/Configuration/MetaService/Repository/DbReadMetaServiceRepository.php
  src/Core/Infrastructure/RealTime/Api/FindMetaService/FindMetaServicePresenter.php
  src/Core/Infrastructure/RealTime/Api/Hypermedia/MetaServiceHyperMediaProvider.php
  src/Core/Infrastructure/RealTime/Repository/Downtime/DbReadDowntimeRepository.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostStatusFactory.php
  src/Core/Infrastructure/RealTime/Repository/MetaService/DbMetaServiceFactory.php
  src/Core/Infrastructure/RealTime/Repository/MetaService/DbReadMetaServiceRepository.php
  src/Core/Infrastructure/RealTime/Repository/Service/DbServiceStatusFactory.php
  tests/php/Core/Domain/Configuration/MetaServiceTest.php
  tests/php/Core/Domain/RealTime/Model/MetaServiceTest.php
Labels: area/backend

#10676 enh(legacy): move login logic into index.php
  www/include/core/footer/footer.php
  www/include/core/login/login.php
  www/include/core/login/processLogin.php
  www/include/core/login/template/login.ihtml
  www/index.php
Labels: area/backend

#10691 fix(MonitoringResourceController): re-add constants to the class
  src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: area/backend

#10658 refactor(header) : replace header scss module with material make styles service component
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/index.tsx
Labels: area/ui

#10689 enh(contactForm): Add a light contact form for Centreon Cloud
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.php
  www/include/configuration/configObject/contact/formContactCloud.ihtml
Labels: area/backend

#10690 enh(ldap): improve performance of ldap sync on login
  www/class/centreonAuth.LDAP.class.php
  www/class/centreonContactgroup.class.php
  www/class/centreonLDAP.class.php
  www/include/configuration/configObject/contact/ldapsearch.php
  www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend

#10694 fix(php): fix some existing warnings and adapt tests to default ldap configuration
  features/bootstrap/ClapiContext.php
  www/include/configuration/configObject/contact/DB-Func.php
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#10656 refactor(header): Mon 12220 replace header scss module with material make styles hedaer index
  www/front_src/src/Header/index.tsx
Labels: area/ui

#10695 fix(conf) fix contact update when user is not admin
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#10680 enh(Footer): Remove footer
  www/front_src/src/App.tsx
  www/front_src/src/Footer/Copyright.tsx
  www/front_src/src/Footer/Links.tsx
  www/front_src/src/Footer/index.tsx
Labels: area/ui

#10641 add selected theme to user informations endpoint
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#10649 add update script to clean host macros duplicated
  www/install/php/Update-21.10.4.php
Labels: area/backend

#10603 enh(host) handle templates in host update
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#10706 fix(conf) keep all acl groups when editing contact with non-admin user
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#10682 fix(serviceDetails): escape possible html tags in performance data
  www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#10719 inversing colors in widget tabs to be blue as active and white as pas…
  www/Themes/Centreon-Light/variables.css
Labels: area/backend

#10687 enh(log) improve session management
  www/class/centreonSession.class.php
  www/include/core/header/header.php
  www/include/home/customViews/action.php
  www/include/home/customViews/rename.php
  www/include/home/customViews/triggers/loadServiceFromHost.php
  www/include/home/customViews/views.php
Labels: area/backend

#10717 enh(clapi): handle login throttling and password expiration in CLAPI
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreonContact.class.php
Labels: area/backend

#10670 enh(logs): enhance php sql failures logging
  bin/centreon-partitioning.php
  cron/centreon-partitioning.php
  src/Centreon/Application/Webservice/AclGroupWebservice.php
  src/Centreon/Domain/Repository/TopologyRepository.php
  src/Centreon/Infrastructure/Monitoring/Metric/MetricRepositoryLegacy.php
  www/class/centreonDB.class.php
  www/class/centreonDBStatement.class.php
  www/install/step_upgrade/process/process_step4.php
Labels: area/backend

#10725 fix(sql) : deleted inexistant property
  www/class/centreonDBStatement.class.php
Labels: area/backend

#10723 fix(login clapi): add missing upgrade script
  www/install/createTables.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10650 enh(host) handle host categories in host update
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryReadRepositoryInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
Labels: area/backend

#10705 Fix(UI): Fix redirection on fresh install and upgrade
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Main/useMain.ts
  www/front_src/src/Main/useUser.ts
Labels: area/ui

#10728 enh(API): Interfaces for renew password use case
  config/routes/Centreon/security/authentication.yaml
  src/Core/Application/Security/UseCase/RenewPassword/RenewPassword.php
  src/Core/Application/Security/UseCase/RenewPassword/RenewPasswordPresenterInterface.php
  src/Core/Application/Security/UseCase/RenewPassword/RenewPasswordRequest.php
  src/Core/Application/User/Repository/ReadUserRepositoryInterface.php
  src/Core/Application/User/Repository/WriteUserRepositoryInterface.php
  src/Core/Domain/User/Model/User.php
  src/Core/Infrastructure/Security/Api/Exception/RenewPasswordApiException.php
  src/Core/Infrastructure/Security/Api/RenewPassword/RenewPasswordController.php
  src/Core/Infrastructure/Security/Api/RenewPassword/RenewPasswordSchema.json
  tests/php/Core/Application/Security/UseCase/RenewPassword/RenewPasswordTest.php
  tests/php/Core/Infrastructure/Security/Api/RenewPassword/RenewPasswordControllerTest.php
Labels: area/backend

#10731 fix(curves) Correction of some form errors and wrong characters displayed
  www/include/views/componentTemplates/DB-Func.php
  www/include/views/componentTemplates/componentTemplates.php
  www/include/views/componentTemplates/formComponentTemplate.ihtml
  www/include/views/componentTemplates/formComponentTemplate.php
  www/include/views/componentTemplates/listComponentTemplates.php
  www/include/views/graphs/common/makeJS_formMetricsList.php
Labels: area/backend

#10669 enh(UI): Add multiselect for excluded users
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration/ExcludedUsers.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration/index.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Form/defaults.ts
  www/front_src/src/Authentication/Form/utils.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/api/endpoints.ts
  www/front_src/src/Authentication/models.ts
  www/front_src/src/Authentication/translatedLabels.ts
  www/front_src/src/Authentication/useValidationSchema.ts
Labels: area/ui

#10699 enh(core): Add User flow
  .gitignore
  Jenkinsfile
  lighthouse/.eslintignore
  lighthouse/.eslintrc.js
  lighthouse/babel.config.js
  lighthouse/defaults.ts
  lighthouse/lighthouseReport.ts
  lighthouse/package-lock.json
  lighthouse/package.json
  lighthouse/pages/login.ts
  lighthouse/pages/resourceStatus.ts
  lighthouse/tsconfig.json
  lighthouserc.js
  package-lock.json
  package.json
  puppeteer-script.js
Labels: area/ui

#10733 enh(UI): Exclude accounts from password duration policy
  Jenkinsfile
  config/routes/Centreon/user.yaml
  doc/API/centreon-api-v22.04.yaml
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Core/Application/Configuration/User/Repository/ReadUserRepositoryInterface.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsers.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersErrorResponse.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersPresenterInterface.php
  src/Core/Application/Configuration/User/UseCase/FindUsers/FindUsersResponse.php
  src/Core/Application/Security/ProviderConfiguration/Local/Repository/WriteConfigurationRepositoryInterface.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationPresenterInterface.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationResponse.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfiguration.php
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationRequest.php
  src/Core/Domain/Configuration/User/Model/User.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/Configuration.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/ConfigurationFactory.php
  src/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersController.php
  src/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenter.php
  src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/FindConfiguration/FindConfigurationPresenter.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationController.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationSchema.json
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/CustomConfigurationSchema.json
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbReadConfigurationRepository.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbWriteConfigurationRepository.php
  tests/api/behat.yml
  tests/api/features/ConfigurationUsers.feature
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationTest.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationTest.php
  tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersControllerTest.php
  tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Api/UpdateConfiguration/UpdateConfigurationControllerTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactoryTest.php
  www/class/centreon-clapi/centreonAPI.class.php
  www/class/centreonContact.class.php
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration/ExcludedUsers.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration/index.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/index.test.tsx
  www/front_src/src/Authentication/Form/defaults.ts
  www/front_src/src/Authentication/Form/utils.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/api/endpoints.ts
  www/front_src/src/Authentication/models.ts
  www/front_src/src/Authentication/translatedLabels.ts
  www/front_src/src/Authentication/useValidationSchema.ts
  www/include/Administration/myAccount/formMyAccount.php
  www/install/createTables.sql
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: kind/enhancement, area/authentication, area/ui, area/backend

#10738 enh(core): Add user flow
  .gitignore
  Jenkinsfile
  lighthouse/.eslintignore
  lighthouse/.eslintrc.js
  lighthouse/babel.config.js
  lighthouse/defaults.ts
  lighthouse/lighthouseReport.ts
  lighthouse/package-lock.json
  lighthouse/package.json
  lighthouse/pages/resourceStatus.ts
  lighthouse/tsconfig.json
  lighthouserc.js
  package-lock.json
  package.json
  puppeteer-script.js
Labels: area/ui

#10739 enh(core): Add user flow
  .gitignore
  Jenkinsfile
  lighthouse/.eslintignore
  lighthouse/.eslintrc.js
  lighthouse/babel.config.js
  lighthouse/defaults.ts
  lighthouse/lighthouseReport.ts
  lighthouse/package-lock.json
  lighthouse/package.json
  lighthouse/pages/resourceStatus.ts
  lighthouse/tsconfig.json
  lighthouserc.js
  package-lock.json
  package.json
  puppeteer-script.js
Labels: area/ui

#10747 fix(install): correct regexp for existing user with privileges
  www/install/steps/process/createDbUser.php
Labels: area/backend

#10740 enh(theme): Create dark theme for background, tabs and buttons
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Centreon-Light/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/style.css
  www/include/core/header/htmlHeader.php
  www/include/home/customViews/index.ihtml
Labels: area/backend

#10748 Fix(UI): Fix UTC timezone
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#10746 fix(security): list only local users for password expiration policy
  src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/PasswordExpiration/ExcludedUsers.tsx
  www/front_src/src/Authentication/Form/PasswordExpirationPolicy/index.test.tsx
Labels: area/ui, area/backend

#10752 enh(api): finish implementation for renew password use case
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/Common/Assertion/Assertion.php
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Core/Application/Security/Exception/UserPasswordException.php
  src/Core/Application/Security/UseCase/RenewPassword/RenewPassword.php
  src/Core/Domain/Security/User/Model/UserPasswordFactory.php
  src/Core/Infrastructure/Security/User/Repository/DbReadUserRepository.php
  src/Core/Infrastructure/Security/User/Repository/DbWriteUserRepository.php
  tests/php/Core/Application/Security/UseCase/RenewPassword/RenewPasswordTest.php
Labels: area/backend

#10754 fix(UI): Fix pendo start
  www/front_src/public/index.html
  www/front_src/src/App/index.tsx
Labels: area/ui

#10756 enh(backend): Refactor configuration security policy
  src/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfiguration.php
  src/Core/Application/Security/UseCase/RenewPassword/RenewPassword.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/Configuration.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/ConfigurationFactory.php
  src/Core/Domain/Security/ProviderConfiguration/Local/Model/SecurityPolicy.php
  src/Core/Domain/Security/User/Model/UserPasswordFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactory.php
  src/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbWriteConfigurationRepository.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/FindConfiguration/FindConfigurationTest.php
  tests/php/Core/Application/Security/ProviderConfiguration/Local/UseCase/UpdateConfiguration/UpdateConfigurationTest.php
  tests/php/Core/Application/Security/UseCase/RenewPassword/RenewPasswordTest.php
  tests/php/Core/Infrastructure/Security/ProviderConfiguration/Local/Repository/DbConfigurationFactoryTest.php
  www/class/centreonContact.class.php
Labels: area/backend

#10758 Fix(UI): Fix all timezones
  www/front_src/src/Resources/Actions/index.test.tsx
  www/front_src/src/Resources/useDateTimePickerAdapter.ts
Labels: area/ui

#10749 fix(clapi): reset login attempts on login success
  www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#10761 enh(conf): add SameSite parameter to apache conf
  libinstall/functions
Labels: area/backend

#10765 enh(conf): Add Set Cookie to apache conf
  libinstall/functions
Labels: area/backend

#10734 enh(tests) : install pestphp
  composer.json
  composer.lock
  symfony.lock
  tests/php/Security/EncryptionTest.php
Labels: area/backend

#10772 fix(ci) : replace file_get_content by curl to disable allow_url_fopen (22.04 to 20.10)
  www/include/configuration/configKnowledge/functions.php
Labels: area/backend

#10759 enh(conf/host) handle groups/categories/templates/severity in host update
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  src/Centreon/Domain/HostConfiguration/Exception/HostMacroServiceException.php
  src/Centreon/Domain/HostConfiguration/Host.php
  src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
  src/Centreon/Domain/HostConfiguration/HostMacroService.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostGroup/HostGroupReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostMacro/HostMacroReadRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostMacro/HostMacroServiceInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostMacro/HostMacroWriteRepositoryInterface.php
  src/Centreon/Domain/HostConfiguration/Interfaces/HostSeverity/HostSeverityReadRepositoryInterface.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostMacroRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/HostSeverityRepositoryRDB.php
  src/Centreon/Infrastructure/HostConfiguration/Repository/Model/HostMacroFactoryRdb.php
Labels: area/backend

#10780 enh(api): implements infrastructure and model validation for update openid configuration use case
  src/Centreon/Domain/Common/Assertion/AssertionException.php
  src/Core/Domain/Security/ProviderConfiguration/OpenId/Model/OpenIdConfiguration.php
  src/Core/Infrastructure/Security/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationPresenter.php
  src/Core/Infrastructure/Security/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  tests/php/Core/Application/Security/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
Labels: area/backend

#10671 enh(ui): use css variables for colors
  www/Themes/Centreon-Light/Variables-css/color-variables.css
  www/Themes/Centreon-Light/Variables-css/variables.css
  www/Themes/Centreon-Light/centreon-loading.css
  www/Themes/Centreon-Light/color.css
  www/Themes/Centreon-Light/jquery-ui/jquery-ui-centreon.css
  www/Themes/Centreon-Light/jquery-ui/jquery-ui.css
  www/Themes/Centreon-Light/login.css
  www/Themes/Centreon-Light/markdown.css
  www/Themes/Centreon-Light/style.css
Labels: area/backend

#10781 fix(kb): fix kb links in resource status
  src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: area/backend

#10700 fix(monitoring): hide password when macro value contains spaces
  src/Centreon/Domain/Monitoring/CommandLineTrait.php
Labels: area/backend

#10791 fix(secu): sanitize ACL group enabling action
  www/include/options/accessLists/groupsACL/DB-Func.php
Labels: area/backend

#10782 enh(api): get password remaining time in legacy user endpoint
  www/api/class/centreon_topcounter.class.php
  www/class/centreonContact.class.php
Labels: area/backend

#10668 enh(UI): PENDO - Add a unique identifier for css objects
  package-lock.json
  www/front_src/src/Header/PollerMenu/ExportConfiguration/index.tsx
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/PollerMenu/translatedLabels.ts
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Resources/Actions/Refresh/index.tsx
  www/front_src/src/Resources/Actions/Resource/ResourceActionButton.tsx
  www/front_src/src/Resources/Details/Header.tsx
  www/front_src/src/Resources/Details/ShortcutsTooltip.tsx
  www/front_src/src/Resources/Details/index.tsx
  www/front_src/src/Resources/Details/tabs/Details/DetailsCard/CommandLineCard.tsx
  www/front_src/src/Resources/Details/tabs/Graph/index.tsx
  www/front_src/src/Resources/Details/tabs/index.tsx
  www/front_src/src/Resources/Details/tabs/models.ts
  www/front_src/src/Resources/Filter/Criterias/index.tsx
  www/front_src/src/Resources/Filter/Save/index.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/GraphOptions.tsx
  www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  www/front_src/src/Resources/Listing/columns/Status.tsx
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
  www/front_src/src/Resources/Listing/index.test.tsx
Labels: area/ui

#10799 feat(install/update): add fresh install and migration script for open id provider
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#10762 fix(login) : fix first ldap authentification error
  www/class/centreonAuth.class.php
  www/class/centreonContact.class.php
  www/class/centreonLDAP.class.php
Labels: area/backend

#10797 fix(perf/curves) sanitize data
  www/include/views/componentTemplates/componentTemplates.php
Labels: area/backend

#10801 Adding dark mode to Host's form
  www/Themes/Centreon-Dark/variables.css
  www/Themes/Generic-theme/Variables-css/color-variables.css
  www/Themes/Generic-theme/Variables-css/variables.css
  www/Themes/Generic-theme/color.css
  www/Themes/Generic-theme/style.css
  www/include/common/templates/cloneHost.ihtml
  www/include/common/templates/cloneMacro.ihtml
Labels: area/backend

#10769 enh(Extensions): Refacto Extension (code style) and adapt dark mode colors if needed
  www/front_src/src/Extensions/ExtensionDeletePopup/index.js
  www/front_src/src/Extensions/ExtensionDetailsPopup/index.js
  www/front_src/src/Extensions/Filter/Criterias/Criteria.tsx
  www/front_src/src/Extensions/Filter/Criterias/default.ts
  www/front_src/src/Extensions/Filter/Criterias/index.tsx
  www/front_src/src/Extensions/Filter/Criterias/models.ts
  www/front_src/src/Extensions/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Extensions/Filter/Criterias/searchQueryLanguage/models.ts
  www/front_src/src/Extensions/Filter/filterAtoms.ts
  www/front_src/src/Extensions/Filter/index.tsx
  www/front_src/src/Extensions/Listing/ExtensionDeleteDialog/index.tsx
  www/front_src/src/Extensions/Listing/ExtensionDetailsDialog/LoadingSkeleton.tsx
  www/front_src/src/Extensions/Listing/ExtensionDetailsDialog/index.tsx
  www/front_src/src/Extensions/Listing/ExtensionsHolder/index.tsx
  www/front_src/src/Extensions/Listing/api/endpoint.ts
  www/front_src/src/Extensions/Listing/api/index.ts
  www/front_src/src/Extensions/Listing/index.tsx
  www/front_src/src/Extensions/Listing/models.ts
  www/front_src/src/Extensions/TopFilters/index.js
  www/front_src/src/Extensions/Wrapper/index.js
  www/front_src/src/Extensions/index.js
  www/front_src/src/Extensions/index.tsx
  www/front_src/src/Extensions/translatedLabels.ts
Labels: area/ui

#10800 enh(openid): remove Configuration from legacy CentreonUI form
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
Labels: area/backend

#10796 Fix(UI): Fix install redirection
  www/front_src/src/Login/useLogin.ts
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Main/useMain.ts
  www/front_src/src/Main/useUser.ts
Labels: area/ui

#10763 fix(api): get correct method
  www/api/class/centreon_ceip.class.php
Labels: area/backend
