Repository centreon/centreon, pull requests merged in 2022-06, with the labels that each got.

#11177 Sanitize and bind "ACL group" list queries
  www/include/options/accessLists/groupsACL/DB-Func.php
Labels: area/backend

#11184 enh(dependencies): Update of some PHP libraries
  composer.json
  composer.lock
  symfony.lock
Labels: area/backend

#10745 enh(dependencies): Update of all PHP libraries
  composer.lock
Labels: area/backend

#11185 fix(parameters/monitoring): move the help text for resource status mode option
  www/include/Administration/parameters/engine/help.php
  www/include/Administration/parameters/general/help.php
Labels: area/backend

#11187 enh(parameters): return new parameter to indicate repository used by …
  src/Centreon/Application/Controller/Administration/ParametersController.php
Labels: area/backend

#11171 chore(install): update version to 21.04.15
  www/install/insertBaseConf.sql
  www/install/php/Update-21.04.15.php
Labels: area/backend

#11052 fix(api): fix duplicate columns name for downtime
  www/class/centreon-clapi/centreonDowntime.class.php
Labels: area/backend

#11073 fix(conf): fix substitution for host massive change
  www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#11194 chore(install): update version to 21.10.7
  www/install/insertBaseConf.sql
  www/install/php/Update-21.10.7.php
Labels: area/backend

#11192 enh(api): add endpoint to find access groups
  config/routes/Centreon/configuration/access_group.yaml
  src/Core/Security/Application/Repository/ReadAccessGroupRepositoryInterface.php
  src/Core/Security/Application/UseCase/FindLocalUserAccessGroups/FindLocalUserAccessGroups.php
  src/Core/Security/Application/UseCase/FindLocalUserAccessGroups/FindLocalUserAccessGroupsPresenterInterface.php
  src/Core/Security/Application/UseCase/FindLocalUserAccessGroups/FindLocalUserAccessGroupsResponse.php
  src/Core/Security/Domain/AccessGroup/Model/AccessGroup.php
  src/Core/Security/Infrastructure/Api/FindLocalUserAccessGroups/FindLocalUserAccessGroupsController.php
  src/Core/Security/Infrastructure/Api/FindLocalUserAccessGroups/FindLocalUserAccessGroupsPresenter.php
  src/Core/Security/Infrastructure/Repository/DbAccessGroupFactory.php
  src/Core/Security/Infrastructure/Repository/DbReadAccessGroupRepository.php
  tests/php/Core/Security/Application/UseCase/FindLocalUserAccessGroups/FindLocalUserAccessGroupsPresenterStub.php
  tests/php/Core/Security/Application/UseCase/FindLocalUserAccessGroups/FindLocalUserAccessGroupsTest.php
  tests/php/Core/Security/Domain/AccessGroup/Model/AccessGroupTest.php
  tests/php/Core/Security/Infrastructure/Api/FindUserAccessGroups/FindLocalUserAccessGroupsControllerTest.php
Labels: area/backend

#11203 fix(e2e): Fix Cypress tests
  tests/e2e/cypress/.eslintrc.js
  tests/e2e/cypress/tsconfig.json
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: area/ui

#11167 enh(Navigation):adding links to navigation menu
  www/front_src/src/Navigation/Sidebar/Menu/CollapsibleItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
  www/front_src/src/Navigation/Sidebar/helpers/getUrlFromEntry.ts
Labels: area/ui

#11200 enh(core): Use SWC as a loader in order to boost build speed
  jest.config.js
  package-lock.json
  package.json
  webpack.config.analyze.js
  webpack.config.dev.js
  webpack.config.js
  webpack.config.prod.js
  www/front_src/src/App/index.tsx
  www/front_src/src/Extensions/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Extensions/Listing/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/ResetPassword/index.tsx
  www/front_src/src/ResetPassword/useResetPassword.ts
  www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  www/front_src/src/Resources/Filter/index.test.tsx
  www/front_src/src/Resources/Listing/useLoadResources/index.test.tsx
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/WizardFormSetupStatus/index.tsx
  www/front_src/src/helpers/dynamicImport.js
  www/front_src/src/index.tsx
  www/front_src/src/redux/actions/pollerWizardActions.js
  www/front_src/src/redux/reducers/index.js
  www/front_src/src/redux/reducers/pollerWizardReducer.js
  www/front_src/src/store/index.js
Labels: area/ui

#11124 enh(install): check php & mariadb prerequisites
  config/centreon.config.php.template
  src/CentreonLegacy/Core/Install/Step/Step1.php
  tests/php/bootstrap.php
  www/install/step_upgrade/step1.php
  www/install/steps/functions.php
  www/install/steps/process/createDbUser.php
  www/install/steps/process/process_step6.php
  www/install/steps/templates/step1.tpl
Labels: area/backend

#11193 merge dev-20.10.x
  Jenkinsfile
  www/api/class/centreon_ceip.class.php
  www/front_src/src/Footer/Links.tsx
  www/front_src/src/Resources/Filter/index.tsx
  www/front_src/src/Resources/Listing/columns/State/index.tsx
  www/front_src/src/Resources/Listing/columns/Url/index.tsx
  www/front_src/src/Resources/Listing/useListing.ts
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#11211 enh(openid): check mandatory properties are not null when openid is active
  doc/API/centreon-api-v22.10.yaml
  src/Core/Security/Application/ProviderConfiguration/OpenId/Repository/ReadOpenIdConfigurationRepositoryInterface.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/Repository/WriteOpenIdConfigurationRepositoryInterface.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  src/Core/Security/Application/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
  src/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSession.php
  src/Core/Security/Domain/Provider/OpenIdProvider.php
  src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/Configuration.php
  src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/OpenIdConfigurationFactory.php
  src/Core/Security/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbOpenIdConfigurationFactory.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbReadOpenIdConfigurationRepository.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
  src/Security/Domain/Authentication/Model/ProviderFactory.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  tests/php/Core/Security/Domain/ProviderConfiguration/OpenId/Model/ConfigurationTest.php
Labels: area/backend

#11195 enh(Header): header and menu skeleton creates an unstable UI
  www/front_src/src/Header/PollerMenu/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Host/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
  www/front_src/src/Header/RessourceStatusCounter/index.tsx
  www/front_src/src/Header/SwitchThemeMode/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Header/userMenu/index.tsx
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/MenuLoader.tsx
Labels: area/ui

#11127 Sanitize and bind "hosts" queries
  www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#11183 enh(conf) remove obsolete engine parameters
  src/Centreon/Domain/Repository/CommandArgDescriptionRepository.php
  src/Centreon/Domain/Repository/CommandCategoryRelationRepository.php
  src/Centreon/Domain/Repository/CommandCategoryRepository.php
  src/Centreon/Domain/Repository/CommandRepository.php
  src/Centreon/Domain/Repository/ConnectorRepository.php
  src/Centreon/Domain/Repository/OnDemandMacroCommandRepository.php
  src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-clapi/centreonEngineCfg.class.php
  www/class/centreon-config/centreonMainCfg.class.php
  www/class/config-generate-remote/Engine.php
  www/class/config-generate/engine.class.php
  www/include/configuration/configNagios/DB-Func.php
  www/include/configuration/configNagios/comments.php
  www/include/configuration/configNagios/formNagios.ihtml
  www/include/configuration/configNagios/formNagios.php
  www/include/configuration/configNagios/help.php
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-22.10.0.sql
  www/install/var/baseconf/centreon-engine.sql
Labels: area/backend

#11197 [Snyk] Sanitize and bind "pollers" queries
  www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#11214 [Snyk] Sanitize and bind "contact" configuration queries
  www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#11215 [PoC] enh(core): Implement Module Federation dynamic containers
  babel.config.js
  package-lock.json
  webpack.config.js
  www/front_src/src/App/useApp.ts
  www/front_src/src/Extensions/Listing/index.tsx
  www/front_src/src/Header/index.tsx
  www/front_src/src/Login/api/decoder.ts
  www/front_src/src/Login/api/endpoint.ts
  www/front_src/src/Login/index.test.tsx
  www/front_src/src/Login/index.tsx
  www/front_src/src/Login/models.ts
  www/front_src/src/Login/useLogin.ts
  www/front_src/src/Main/InitializationPage/index.tsx
  www/front_src/src/Main/atoms/platformInstallationStatusAtom.ts
  www/front_src/src/Main/atoms/platformVersionsAtom.ts
  www/front_src/src/Main/index.test.tsx
  www/front_src/src/Main/index.tsx
  www/front_src/src/Main/useMain.ts
  www/front_src/src/Main/usePlatformVersions.ts
  www/front_src/src/ResetPassword/index.test.tsx
  www/front_src/src/api/decoders.ts
  www/front_src/src/api/endpoint.ts
  www/front_src/src/api/models.ts
  www/front_src/src/bootstrap.tsx
  www/front_src/src/components/FederatedComponents/index.tsx
  www/front_src/src/components/Hook/index.tsx
  www/front_src/src/components/ReactRouter/index.test.tsx
  www/front_src/src/components/ReactRouter/index.tsx
  www/front_src/src/externalComponents/atoms.ts
  www/front_src/src/externalComponents/index.test.ts
  www/front_src/src/externalComponents/mocks.ts
  www/front_src/src/externalComponents/models.ts
  www/front_src/src/externalComponents/useExternalComponents.ts
  www/front_src/src/federatedModules/Load/index.tsx
  www/front_src/src/federatedModules/Load/loadComponent.ts
  www/front_src/src/federatedModules/atoms.ts
  www/front_src/src/federatedModules/index.test.ts
  www/front_src/src/federatedModules/mocks.ts
  www/front_src/src/federatedModules/models.ts
  www/front_src/src/federatedModules/useFederatedModules.ts
  www/front_src/src/index.tsx
Labels: area/ui

#11165 test(Navigation/sidebar): visual regression test with cy
  ci/debian/rules
  cypress.json
  cypress/fixtures/menuData.json
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.tsx
  cypress/tsconfig.json
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- displays the direct child items and highlights the item when hovered.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- expands the menu when the logo is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- highlights the menu item when double clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- highlights the parent item when the item is clicked.snap.png
  cypress/visual-testing-snapshots/All Specs/Navigation menu -- matches the current snapshot initial menu.snap.png
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.js
  www/front_src/src/Navigation/Sidebar/Menu/CollapsibleItems.tsx
  www/front_src/src/Navigation/Sidebar/index.cypress.spec.tsx
Labels: area/ui

#11218 enh(Navigation): Close-menu-when-a-navigation-item-is-clicked
  www/front_src/src/Navigation/Sidebar/Menu/CollapsibleItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  www/front_src/src/Navigation/Sidebar/Menu/index.tsx
Labels: area/ui

#11238 enh(install): improve error message when database access failure
  www/install/install.css
  www/install/steps/process/process_step6.php
Labels: area/backend

#11240 fix(UI): Fix centreon-frontend
  package-lock.json
  package.json
Labels: area/ui

#11228 fix(acl) remove wizard poller steps options from acl menu
  www/install/insertTopology.sql
  www/install/sql/centreon/Update-DB-22.04.1.sql
Labels: area/backend

#11244 fix(php): manage compatibility 22.04 with extensions
  config/packages/Centreon.yaml
  src/Centreon/Domain/Security/AccessGroup.php
  src/Centreon/Domain/Security/Interfaces/AccessGroupRepositoryInterface.php
  src/Centreon/Infrastructure/Security/AccessGroupRepositoryRDB.php
  src/Core/Security/Infrastructure/Repository/DbReadAccessGroupRepository.php
Labels: area/backend

#11209 enh(upgrade): do not enable delay before password creation on upgrade
  www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#11219 enh(Resources/Details/TimeLine):Timeperiod-group-button-and-custom-period-selectors-have-different-heights
  www/front_src/src/Resources/Graph/Performance/TimePeriods/CustomTimePeriodPickers.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
Labels: area/ui

#11242 enh(Resources/legend): Do not display brackets when a metric does not have unit
  www/front_src/src/Resources/Graph/Performance/Legend/index.tsx
Labels: area/ui

#11250 fix(ci): sorry guys
  Jenkinsfile
Labels: area-ci

#11235 enh(acl) add poller access acl config
  lang/es_ES.UTF-8/LC_MESSAGES/help.po
  lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  www/include/configuration/configServers/listServers.ihtml
  www/include/configuration/configServers/listServers.php
  www/include/options/accessLists/actionsACL/DB-Func.php
  www/include/options/accessLists/actionsACL/formActionsAccess.ihtml
  www/include/options/accessLists/actionsACL/formActionsAccess.php
  www/include/options/accessLists/actionsACL/help.php
Labels: area/backend

#11249 fix(upgrade): check mariadb prerequisites only if db connection is up
  www/install/steps/process/process_step6.php
Labels: area/backend

#11027 Sanitizing and binding queries in "Updates" scripts
  www/install/php/Update-18.10.0.post.php
  www/install/php/Update-19.10.0-beta.3.php
  www/install/php/Update-2.8.0.php
  www/install/php/Update-2.8.5.post.php
  www/install/php/Update-21.04.0-beta.1.php
Labels: area/backend

#11247 fix(ui): Tooltip in PPM is not visible in dark mode
  www/Themes/Centreon-Dark/variables.css
Labels: area/backend

#11233 Sanitize and bind "timeperiod" configuration queries
  www/include/configuration/configObject/timeperiod/DB-Func.php
Labels: area/backend

#11272 fix(topology) fix wizard poller access
  src/Centreon/Application/Webservice/TopologyWebservice.php
  src/Centreon/Tests/Application/Webservice/TopologyWebserviceTest.php
Labels: area/backend

#11267 fix(UI): Fix width when federatedModule is in state not ready and not failed
  www/front_src/src/federatedModules/Load/index.tsx
Labels: area/ui

#11283 fix(ci): add inheritance to access group repository
  src/Core/Security/Infrastructure/Repository/DbReadAccessGroupRepository.php
Labels: area/backend

#11269 enh(E2E): Prevent random fails on end to end tests
  Jenkinsfile
  tests/e2e/cypress.json
  tests/e2e/cypress/commons.ts
  tests/e2e/cypress/integration/Login/01-login/index.ts
  tests/e2e/cypress/integration/Login/common.ts
  tests/e2e/cypress/integration/Resources-status/02-actions/index.ts
  tests/e2e/cypress/integration/Resources-status/common.ts
  tests/e2e/cypress/plugins/index.ts
  tests/e2e/cypress/support/index.ts
  tests/e2e/cypress/webpack.config.js
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: area/ui

#11281 enh(E2E): Prevent random fails on end to end tests (22.04.x)
  Jenkinsfile
  tests/e2e/cypress.json
  tests/e2e/cypress/commons.ts
  tests/e2e/cypress/integration/Login/01-login/index.ts
  tests/e2e/cypress/integration/Login/common.ts
  tests/e2e/cypress/integration/Resources-status/02-actions/index.ts
  tests/e2e/cypress/integration/Resources-status/common.ts
  tests/e2e/cypress/plugins/index.ts
  tests/e2e/cypress/support/index.ts
  tests/e2e/cypress/webpack.config.js
  tests/e2e/package-lock.json
  tests/e2e/package.json
Labels: area/ui

#11277 enh(conf) Enable the export button in topcounter for all users having sufficient privileges
  src/Centreon/Application/Controller/UserController.php
  src/Centreon/Domain/Contact/Contact.php
  src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  tests/clapi_export/clapi-configuration.txt
  www/class/centreon-clapi/centreonContact.class.php
  www/include/Administration/myAccount/DB-Func.php
  www/include/Administration/myAccount/formMyAccount.ihtml
  www/include/Administration/myAccount/formMyAccount.php
  www/install/createTables.sql
  www/install/sql/centreon/Update-DB-22.10.0.sql
Labels: area/backend

#11280 enh(openid): remove alias bind attribute and improve labels
  doc/API/centreon-api-v22.10.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilder.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/Domain/Provider/OpenIdProvider.php
  src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/Configuration.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilder.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilderTest.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilderTest.php
  www/front_src/src/Authentication/Openid/Form/inputs.ts
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/Openid/models.ts
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
  www/front_src/src/Authentication/Openid/useValidationSchema.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Authentication/translatedLabels.ts
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.1.php
Labels: area/ui, area/backend

#11290 enh(UI): Remove alias bind attribute and improve labels
  doc/API/centreon-api-v22.04.yaml
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  src/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilder.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  src/Core/Security/Domain/Provider/OpenIdProvider.php
  src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/Configuration.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilder.php
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/CustomConfigurationSchema.json
  src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilderTest.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationTest.php
  tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilderTest.php
  www/front_src/src/Authentication/Openid/Form/inputs.ts
  www/front_src/src/Authentication/Openid/index.test.tsx
  www/front_src/src/Authentication/Openid/models.ts
  www/front_src/src/Authentication/Openid/translatedLabels.tsx
  www/front_src/src/Authentication/Openid/useValidationSchema.ts
  www/front_src/src/Authentication/api/adapters.ts
  www/front_src/src/Authentication/api/decoders.ts
  www/front_src/src/Authentication/index.tsx
  www/front_src/src/Authentication/translatedLabels.ts
  www/install/insertBaseConf.sql
  www/install/php/Update-22.04.1.php
Labels: area/ui, area/backend

#11262 fix(conf) add warning when max length is exceeded for url, url action or notes
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/include/common/common-Func.php
  www/include/configuration/configObject/host/formHost.ihtml
  www/include/configuration/configObject/host/formHost.php
  www/include/configuration/configObject/service/formService.ihtml
  www/include/configuration/configObject/service/formService.php
Labels: area/backend

#11296 fix(serviceDetail): use correct value for last update time
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11257 Sanitize and bind queries in virtual metrics configuration
  www/include/views/virtualMetrics/DB-Func.php
Labels: area/backend

#11260 enh(platform): remove centreon web path option
  lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  www/class/centreonUtils.class.php
  www/include/Administration/parameters/DB-Func.php
  www/include/Administration/parameters/general/form.ihtml
  www/include/Administration/parameters/general/form.php
  www/install/insertBaseConf.sql
  www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#11298 fix(serviceDetail): use correct value for last update time
  www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Labels: area/backend

#11254 enh(Resources/Details/TimeLine/Events): rework timeline UI
  www/front_src/src/Resources/Details/tabs/CompactStatusChip.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
  www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
Labels: area/ui

#11294 feat(resources): add Severity to detail panel
  config/packages/serializer/Centreon/Monitoring.Resource.yml
  doc/API/ResourceHostDetail.yaml
  doc/API/ResourceServiceDetail.yaml
  doc/API/centreon-api-v22.10.yaml
  src/Centreon/Domain/Monitoring/Resource.php
  src/Centreon/Infrastructure/Monitoring/Resource/DbReadResourceRepository.php
  src/Core/Application/RealTime/Common/RealTimeResponseTrait.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHost.php
  src/Core/Application/RealTime/UseCase/FindHost/FindHostResponse.php
  src/Core/Application/RealTime/UseCase/FindService/FindService.php
  src/Core/Application/RealTime/UseCase/FindService/FindServiceResponse.php
  src/Core/Domain/RealTime/Model/Host.php
  src/Core/Domain/RealTime/Model/Service.php
  src/Core/Infrastructure/RealTime/Api/FindHost/FindHostPresenter.php
  src/Core/Infrastructure/RealTime/Api/FindService/FindServicePresenter.php
  src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  src/Core/Infrastructure/RealTime/Repository/Service/DbServiceFactory.php
  src/Core/Severity/RealTime/Application/Repository/ReadSeverityRepositoryInterface.php
  src/Core/Severity/RealTime/Infrastructure/Repository/DbReadSeverityRepository.php
  src/Core/Severity/RealTime/Infrastructure/Repository/DbSeverityFactory.php
  tests/api/Context/RealTimeSeverityContext.php
  tests/api/behat.yml
  tests/api/features/RealTimeSeverity.feature
  tests/php/Core/Application/RealTime/UseCase/FindHost/FindHostTest.php
  tests/php/Core/Application/RealTime/UseCase/FindService/FindServiceTest.php
  tests/php/Core/Domain/RealTime/Model/HostTest.php
  tests/php/Core/Domain/RealTime/Model/ServiceTest.php
  tests/php/Core/Severity/RealTime/Application/UseCase/FindSeverity/FindSeverityTest.php
Labels: area/backend
