Repository centreon/centreon, pull requests merged in 2023-03, with the labels that each got.

#1029 fix(exportServices): add missing severity field
  centreon/www/class/config-generate/service.class.php
Labels: area/backend

#1035 enh(vault): Add an abstract repository for vault transaction
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
Labels: area/backend

#1039 fix(acl): SQL queries with not escaped dbname (ex: hyphen) [22.10.next]
  centreon/www/class/centreonACL.class.php
  centreon/www/include/configuration/configObject/escalation/listEscalation.php
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
  centreon/www/include/configuration/configObject/meta_service/listMetric.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/service/listServiceByHostGroup.php
  centreon/www/include/configuration/configObject/service_dependency/listServiceDependency.php
Labels: area/backend

#1040 fix(abstractRepository): use correct typehint
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
Labels: area/backend

#899 fix(web): update query to get right acl groups and generate graph (22.10)
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#900 fix(web): update query to get right acl groups and generate graph (22.04)
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#925 fix(clapi) update the updated column when poller reload/restart (22.10)
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#926 fix(clapi) update the updated column when poller reload/restart (22.04)
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#995 fix(conf): improve performance querying service group relations with ACL (22.10)
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#996 fix(conf): improve performance querying service group relations with ACL (22.04)
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#1041 fix(web): do not convert a null value to date
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/MetaService/DbMetaServiceFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbServiceFactory.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
Labels: area/backend

#1042 fix(web): do not convert a null value to date (22.10)
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/MetaService/DbMetaServiceFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbServiceFactory.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
Labels: area/backend

#887 fix: assertion messages and tests
  centreon/src/Centreon/Domain/Common/Assertion/Assertion.php
  centreon/src/Centreon/Domain/Common/Assertion/AssertionException.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/AuthenticationConditions.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/WebSSO/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/WebSSO/Model/WebSSOConfiguration.php
  centreon/tests/php/Centreon/Domain/Common/AssertionTest.php
Labels: area/backend

#1034 fix(exportServices): add missing severity field
  centreon/www/class/config-generate/service.class.php
Labels: area/backend

#1054 fix(conf) allow removal of all notification options at contact update (#1046)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#1059 fix (repository): Update the defaut value of regexp
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
Labels: area/backend

#1062 fix(export): remove ssl verification
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
Labels: area/backend

#1051 fix(export): check if poller is activated before conf export via API
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/MonitoringServer/Exception/ConfigurationMonitoringServerException.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
Labels: area/backend

#1085 enh(UI): Add missing favicon
  centreon/www/img/favicon.ico
Labels: area/ui

#1067 chore(EventSubscriber): return a 404 status when route doesnt exist
  centreon/composer.lock
  centreon/features/bootstrap/URIContext.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#1069 enh(centreon): update the plugin packs term to monitoring connectors
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/install/menu_translation.php
Labels: area/backend

#1056 enh(resources): handle check / forced check in resource status
  centreon/config/json_validator/latest/Centreon/Check/AddChecks.json
  centreon/config/packages/serializer/Application/Request.CheckRequest.yml
  centreon/config/packages/serializer/Centreon/Monitoring.ResourceLinksEndpoints.yml
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Centreon/Application/Controller/CheckController.php
  centreon/src/Centreon/Application/Controller/MonitoringResourceController.php
  centreon/src/Centreon/Application/Controller/UserController.php
  centreon/src/Centreon/Domain/Check/Check.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Monitoring/ResourceLinksEndpoints.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/MetaServiceHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
  centreon/tests/api/features/Check.feature
  centreon/tests/php/Centreon/Application/Controller/CheckController/ResourcesTest.php
  centreon/tests/php/Centreon/Application/Controller/MonitoringResourceControllerTest.php
Labels: area/backend

#1101 enh(CI): Update Cypress actions and suppress summary
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/web-frontend-component-test/action.yml
Labels: area/ui

#1107 enh(CI): Improve eslint report
  .github/actions/frontend-lint/action.yml
  .github/actions/publish-lint-report/action.yml
  .github/actions/publish-lint-report/formJsonToMarkdown.js
  .github/actions/publish-report/action.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/web.yml
Labels: area/ui

#1073 enh (real-time): Optimisation of the number of SQL queries on the legacy service by hostgroup monitoring page
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
Labels: area/backend

#1095 enh (assertion): Add new assertion "range"
  centreon/src/Centreon/Domain/Common/Assertion/Assertion.php
  centreon/src/Centreon/Domain/Common/Assertion/AssertionException.php
  centreon/tests/php/Centreon/Domain/Common/AssertionTest.php
Labels: area/backend

#1114 enh(Image): Fix image blink
  centreon/packages/ui/src/Image/Image.tsx
Labels: area/ui

#852 fix(openTicket): missing centreon_path when using smarty function in ticket body
  centreon-open-tickets/www/modules/centreon-open-tickets/centreon-open-tickets.conf.php
Labels: bug, area/backend

#1123 fix(openTicket): missing centreon_path when using smarty function in ticket body [22.10]
  centreon-open-tickets/www/modules/centreon-open-tickets/centreon-open-tickets.conf.php
Labels: area/backend

#1120 enh (real-time): Optimisation of the number of SQL queries on the legacy service by hostgroup monitoring page
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
Labels: area/backend

#1121 enh (real-time): Optimisation of the number of SQL queries on the legacy service by hostgroup monitoring page
  .github/actions/publish-lint-report/formatJsonToMarkdown.js
  .github/workflows/web.yml
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
Labels: area/backend

#623 enh(php): use centreon-test-lib 22.04.x
  centreon/composer.json
  centreon/composer.lock
  centreon/features/bootstrap/DowntimeDSTContext.php
Labels: area/backend

#1138 fix(install/upgrade): remove constraint on table vault_configuration
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.0-beta.1.sql
Labels: area/backend

#1141 fix(install): add missing right on centreon user for mysql installation
  centreon/www/install/steps/process/createDbUser.php
Labels: area/backend

#1081 [enh]: configure mariadb with utf8mb4 by default
  centreon/tools/convert_db_charset_to_utfmb4.php
  centreon/www/install/installBroker.sql
Labels: area/backend

#1032 fix (Authentication): PHP error on authentication APIs
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/Local/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
Labels: area/backend

#1022 fix (Authentication): Make error messages generic
  centreon/src/Centreon/Application/Controller/AuthenticationController.php
  centreon/src/Core/Security/Authentication/Domain/Exception/AuthenticationException.php
  centreon/tests/api/features/LocalAuthentication.feature
  centreon/tests/e2e/cypress/e2e/Local-authentication/01-local-authentication/index.ts
  centreon/tests/php/Centreon/Application/Controller/AuthenticationControllerTest.php
  centreon/www/api/index.php
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1156 fix(requests): Handle 204 status code
  centreon/packages/ui/src/api/customFetch.ts
Labels: area/ui

#1139 fix(install): Fail to read a file during centreon-web install
  centreon/src/CentreonLegacy/Core/Install/Step/AbstractStep.php
Labels: area/backend

#1150 fix (Authentication): PHP error on authentication APIs
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/Local/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
Labels: area/backend

#886 adapt core code to bam
  centreon/config/packages/Centreon.yaml
  centreon/src/Centreon/Application/Validation/Validator/RepositoryCallbackValidator.php
  centreon/src/Centreon/Application/Validation/Validator/UniqueEntityValidator.php
  centreon/src/Centreon/Domain/Repository/AclGroupRepository.php
  centreon/src/Centreon/Domain/Repository/CommandRepository.php
  centreon/src/Centreon/Domain/Repository/ContactGroupRepository.php
  centreon/src/Centreon/Domain/Repository/HostRepository.php
  centreon/src/Centreon/Domain/Repository/ImagesRepository.php
  centreon/src/Centreon/Domain/Repository/NagiosServerRepository.php
  centreon/src/Centreon/Domain/Repository/ServiceRepository.php
  centreon/src/Centreon/Infrastructure/Service/CentreonPaginationService.php
  centreon/src/Centreon/Tests/Application/Validation/Validator/UniqueEntityValidatorTest.php
  centreon/src/Centreon/Tests/Domain/Repository/AclGroupRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/CommandRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/ContactGroupRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/ImagesRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/NagiosServerRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/ServiceRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/TopologyRepositoryTest.php
  centreon/src/Centreon/Tests/Domain/Repository/Traits/CheckListOfIdsTraitTest.php
  centreon/src/Centreon/Tests/Infrastructure/Service/CentreonPaginationServiceTest.php
  centreon/src/Centreon/Tests/ServiceProviderTest.php
  centreon/src/CentreonCommand/Application/Webservice/CommandWebservice.php
  centreon/src/CentreonCommand/Domain/Repository/CommandRepository.php
  centreon/src/CentreonCommand/Tests/Domain/Repository/CommandRepositoryTest.php
  centreon/src/CentreonNotification/Domain/Entity/Escalation.php
  centreon/src/CentreonNotification/Domain/Repository/DependencyRepository.php
  centreon/src/CentreonNotification/Domain/Repository/EscalationRepository.php
  centreon/src/CentreonNotification/Tests/Domain/Repository/DependencyRepositoryTest.php
  centreon/src/CentreonNotification/Tests/Domain/Repository/EscalationRepositoryTest.php
  centreon/src/CentreonUser/Domain/Repository/TimeperiodRepository.php
  centreon/src/CentreonUser/Tests/Domain/Repository/TimeperiodRepositoryTest.php
Labels: area/backend

#1154 fix (Authentication): Make error messages generic (dev-2210)
  centreon/src/Centreon/Application/Controller/AuthenticationController.php
  centreon/src/Core/Security/Authentication/Domain/Exception/AuthenticationException.php
  centreon/tests/api/features/LocalAuthentication.feature
  centreon/tests/php/Centreon/Application/Controller/AuthenticationControllerTest.php
  centreon/www/api/index.php
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1155 fix (Authentication): Make error messages generic (dev-2204)
  centreon/src/Centreon/Application/Controller/AuthenticationController.php
  centreon/src/Core/Security/Domain/Authentication/AuthenticationException.php
  centreon/tests/api/features/LocalAuthentication.feature
  centreon/tests/php/Centreon/Application/Controller/AuthenticationControllerTest.php
  centreon/www/api/index.php
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1162 fix (Authentication): PHP error on authentication APIs (dev-2204)
  centreon/src/Centreon/Domain/Common/Assertion/Assertion.php
  centreon/src/Core/Security/Infrastructure/Api/LoginOpenIdSession/LoginOpenIdSessionController.php
  centreon/src/Core/Security/Infrastructure/Api/LoginSession/LoginSessionController.php
Labels: area/backend

#1116 Fix[Installation]: error when accessing to installation wizard
  centreon/www/front_src/src/Main/useMain.ts
Labels: area/backend

#1167 feat(vault) replace http scheme by https
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
Labels: area/backend

#1166 feat(vault) replace http scheme by https
  centreon/lib/Centreon/Object/Host/Host.php
  centreon/www/class/centreon-clapi/centreonHost.class.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#1061 enh(generate): Generate Centreon Vault Storage options
  centreon/www/class/config-generate/abstract/host.class.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/abstract/objectJSON.class.php
  centreon/www/class/config-generate/command.class.php
  centreon/www/class/config-generate/generate.class.php
  centreon/www/class/config-generate/macro.class.php
  centreon/www/class/config-generate/meta_service.class.php
  centreon/www/class/config-generate/vault.class.php
Labels: area/backend

#1188 enh(OpenID): Trim extra spaces and slashes in endpoint definition
  centreon/src/Core/Security/ProviderConfiguration/Domain/Model/Endpoint.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/Model/EndpointTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfigurationTest.php
Labels: area/backend

#1189 enh(OpenID): Trim extra spaces and slashes in endpoint definition - 22.10.x
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/Endpoint.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/Model/EndpointTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfigurationTest.php
Labels: area/backend

#1194 enh(OpenID): Trim extra spaces and slashes in endpoint definition - 22.04.x
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilder.php
  centreon/tests/php/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilderTest.php
Labels: area/backend

#1180 enh(UI): Extend OpenID form
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Authentication/Openid/Form/inputs.ts
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/models.ts
  centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx
  centreon/www/front_src/src/Authentication/Openid/useValidationSchema.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
Labels: area/ui

#1201 refacto(auth) rework the log
  centreon/src/Security/Domain/Authentication/Model/LocalProvider.php
Labels: area/backend

#1203 enh(API): Modifies the CreateResponse ID so that it can handle different types.
  centreon/src/Core/Application/Common/UseCase/CreatedResponse.php
Labels: area/backend

#1207 fix(UI): Fix padding on textarea
  centreon/packages/ui/src/Form/storiesData.tsx
  centreon/packages/ui/src/ThemeProvider/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-collapsible-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-custom-button-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-basic-form-with-horizontal-groups-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-loading-form-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-form-loading-form-with-groups-1-snap.png
Labels: area/ui

#1205 update cypress commands file
  centreon/packages/js-config/cypress/component/commands.tsx
Labels: area/ui

#1217 fix(UI): Add missing decoder for redirect URL
  centreon/www/front_src/src/Authentication/api/decoders.ts
Labels: area/ui

#979 enh(Centreon UI): Reduce storyshots execution time and stabilize them
  centreon/packages/ui/jest.config.js
  centreon/packages/ui/package.json
  centreon/packages/ui/src/storyshots.test.js
  centreon/pnpm-lock.yaml
Labels: area/ui

#1220 fix(resource): error when opening detail panel of a resource in downtime
  centreon/src/Core/Application/RealTime/Common/RealTimeResponseTrait.php
Labels: area/backend

#1221 fix(resource): error when opening detail panel of a resource in downt…
  centreon/src/Core/Application/RealTime/Common/RealTimeResponseTrait.php
Labels: area/backend

#1197 fix(auth) decode the contact_ldap_dn before the authentication
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend

#1198 fix(auth) decode the contact_ldap_dn before the authentication (22.10)
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend

#1190 fix(gorgone): mbi unable to rebuild partial data with new scripts
  centreon-gorgone/gorgone/modules/centreon/mbi/etl/event/main.pm
  centreon-gorgone/gorgone/modules/centreon/mbi/etl/perfdata/main.pm
Labels: bug, area/backend

#1225 fix(clapi): warnings when using parameters with clapi RT downtimes
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
Labels: area/backend

#1170 enh(Packages/Listing/ActionsBar): Move the Resource status view mode in the Resource status page
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/Listing/ActionBar/index.tsx
  centreon/packages/ui/src/Listing/index.stories.tsx
  centreon/packages/ui/src/Listing/index.test.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-loading-with-data-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-loading-with-no-data-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-normal-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-normal-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-a-long-content-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-filter-details-and-open-panel-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-fixed-panel-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-open-panel-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-open-panel-and-tabs-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-page-with-responsive-pagination-table-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-playground-listing-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-with-actions-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-with-editable-columns-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-with-short-label-columns-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-with-specified-view-mode-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-with-view-mode-extended-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-without-checkboxes-1-snap.png
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/src/Centreon/Application/Controller/UserController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Application/Configuration/User/Exception/UserException.php
  centreon/src/Core/Application/Configuration/User/UseCase/PatchUser/PatchUser.php
  centreon/src/Core/Application/Configuration/User/UseCase/PatchUser/PatchUserRequest.php
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Domain/Configuration/User/Model/User.php
  centreon/src/Core/Infrastructure/Configuration/User/Api/PatchUser/PatchUserController.php
  centreon/src/Core/Infrastructure/Configuration/User/Api/PatchUser/PatchUserSchema.json
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/tests/e2e/cypress/e2e/Login/01-login/index.ts
  centreon/tests/php/Core/Application/Configuration/User/UseCase/PatchUser/PatchUserTest.php
  centreon/tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/Resources/Listing/Listing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
  centreon/www/front_src/src/Resources/Listing/useViewerMode.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/general/form.ihtml
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/Administration/parameters/general/help.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.0-beta.1.sql
Labels: area/ui

#1219 Fix[Installation]: error when accessing to installation wizard
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/useMain.ts
Labels: area/backend

#1232 Fix(UI): Fix anomaly detection type filter on save
  centreon/www/front_src/src/Resources/Filter/Criterias/Criteria.tsx
  centreon/www/front_src/src/Resources/Filter/filterAtoms.ts
  centreon/www/front_src/src/Resources/Filter/useFilterByModule.ts
Labels: area/ui
