Repository centreon/centreon, pull requests merged in 2023-01, with the labels that each got.

#580 fix(ui): avoid double call to userTimezone.php
  centreon/tests/e2e/cypress/e2e/Local-authentication/01-local-authentication/index.ts
  centreon/tests/e2e/cypress/support/Commands.ts
  centreon/www/include/core/header/htmlHeader.php
Labels: area/ui, area/backend

#568 enh(UI): Add the new Centreon logo
  centreon/packages/ui/assets/centreon-logo-dark.svg
  centreon/packages/ui/assets/centreon-logo-light.svg
  centreon/packages/ui/assets/centreon-logo-one-line-dark.svg
  centreon/packages/ui/assets/centreon-logo-one-line-light.svg
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Image/index.stories.tsx
  centreon/packages/ui/src/Image/index.test.tsx
  centreon/packages/ui/src/Logo/CentreonLogo.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-fallback-page-licence-invalid-licence-invalid-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-logo-centreon-logo-default-1-snap.png
  centreon/packages/ui/src/index.ts
  centreon/packages/ui/testRunner.js
Labels: area/ui

#599 chore(ui version): Update package ui version to 23.4.10
  centreon/packages/ui/package.json
Labels: automerge

#591 Style(media): Buttons are not well displayed in media image directory
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/options/media/images/formDirectory.php
  centreon/www/include/options/media/images/formImg.php
Labels: area/backend

#614 feat(host): Save SNMP Community has password (#581)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbVaultConfigurationFactory.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonRestHttp.class.php
  centreon/www/include/common/javascript/centreon/macroPasswordField.js
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.04.0-beta.1.php
Labels: area/backend

#628 fix(test): re-enable monitoring timeline test
  centreon/tests/api/features/MonitoringTimeline.feature
Labels: area/backend

#354 enh(conf) update FindHostCategories endpoint
  centreon/config/routes/Centreon/host_category.yaml
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Common/Infrastructure/RequestParameters/Normalizer/BoolToEnumNormalizer.php
  centreon/src/Core/Common/Infrastructure/RequestParameters/Normalizer/BoolToIntegerNormalizer.php
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategoriesResponse.php
  centreon/src/Core/HostCategory/Domain/Model/HostCategory.php
  centreon/src/Core/HostCategory/Domain/Model/NewHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategories/FindHostCategoriesController.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategories/FindHostCategoriesPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategories/FindHostCategoriesRoute.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/php/Core/Common/Infrastructure/RequestParameters/Normalizer/BoolToEnumNormalizerTest.php
  centreon/tests/php/Core/Common/Infrastructure/RequestParameters/Normalizer/BoolToIntegerNormalizerTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategoriesTest.php
  centreon/tests/php/Core/HostCategory/Domain/Model/HostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Domain/Model/NewHostCategoryTest.php
Labels: area/backend

#526 enh(api) remove old find host categories endpoint
  centreon/config/routes/Centreon/host_category.yaml
  centreon/src/Centreon/Application/Controller/HostCategoryController.php
  centreon/src/Centreon/Domain/HostConfiguration/HostCategoryService.php
  centreon/src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryReadRepositoryInterface.php
  centreon/src/Centreon/Domain/HostConfiguration/Interfaces/HostCategory/HostCategoryServiceInterface.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategories.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesResponse.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategory/HostCategoryV2110.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostCategory/HostCategoryV2110Factory.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/Repository/HostCategoryRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesResponseTest.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostCategory/FindHostCategoriesTest.php
  centreon/tests/php/Centreon/Domain/MetaServiceConfiguration/UseCase/V21/FindMetaServicesConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MetaServiceConfiguration/UseCase/V21/FindOneMetaServiceConfigurationTest.php
Labels: area/backend

#630 enh(host): remove password on SNMP Community
  centreon/src/Centreon/Domain/Log/LegacyLogger.php
  centreon/src/Centreon/Domain/Log/LoggerTrait.php
  centreon/www/class/centreonLog.class.php
  centreon/www/include/common/javascript/centreon/macroPasswordField.js
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/monitoring/objectDetails/serviceDetails.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.04.0-beta.1.php
Labels: area/backend

#639 fix(upgrade): Move alter table before transaction and add missing request
  centreon/www/install/php/Update-22.04.8.php
Labels: area/backend

#123 fix(web): update pending link on deprecated pages
  centreon/www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
Labels: area/backend

#392 enh(conf) add CreateHostCategory endpoint
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/Repository/WriteHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryRequest.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryResponse.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryRoute.yaml
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategorySchema.json
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/php/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryTest.php
Labels: area/backend

#653 fix(sql) remove intersect query in upgrade
  centreon/www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#662 fix(upgrade): redo missing upgrade script 22.10.2
  centreon/www/install/php/Update-22.10.2.php
  centreon/www/install/php/Update-22.10.4.php
Labels: area/backend

#656 fix(sql) remove intersect query in upgrade (#653)
  centreon/www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#646 enh(host): change SNMP Community input type to password
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/features/bootstrap/HostTemplateBasicsOperationsContext.php
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/www/include/common/javascript/centreon/macroPasswordField.js
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#643 chore(ui version): Update package ui version to 23.4.11
  centreon/packages/ui/package.json
Labels: automerge

#641 fix(web): update pending link on deprecated pages 22.10.x
  centreon/www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
Labels: area/backend

#657 fix(sql) remove intersect query in upgrade (#653)
  centreon/www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#670 fix(API) fix delete host category
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Domain/Model/HostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
Labels: area/backend

#678 feat(clapi): handle snmp community storage in vault
  centreon/lib/Centreon/Object/Host/Host.php
  centreon/www/class/centreon-clapi/centreonHost.class.php
Labels: area/backend

#682 chore(ui version): Update package ui version to 23.4.12
  centreon/packages/ui/package.json
Labels: automerge

#655 enh(media): Display available disk space in media upload page
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
Labels: area/backend

#652 enh(APIv2): possibility to return 409 Conflict HTTP response
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Core/Application/Common/UseCase/ConflictResponse.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategories/FindHostCategoriesPresenter.php
  centreon/src/Core/HostGroup/Application/Exceptions/HostGroupException.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroup.php
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/TimePeriod/Application/UseCase/AddTimePeriod/AddTimePeriod.php
  centreon/src/Core/TimePeriod/Application/UseCase/UpdateTimePeriod/UpdateTimePeriod.php
  centreon/tests/api/features/CloudHostGroup.feature
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/HostGroup.feature
  centreon/tests/api/features/TimePeriodConfiguration.feature
  centreon/tests/php/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryTest.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/AddTimePeriod/AddTimePeriodTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/UpdateTimePeriod/UpdateTimePeriodTest.php
Labels: area/backend

#167 feat(contact): Define a default page for new users
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/www/class/centreon-clapi/centreonContact.class.php
  centreon/www/class/centreon-clapi/centreonContactTemplate.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/help.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.ihtml
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
Labels: area/backend

#582 enh(Panel): display ba entire name
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Listing/ActionBar/index.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/MultiSelectEntries/index.tsx
  centreon/packages/ui/src/Panel/Section/index.stories.tsx
  centreon/packages/ui/src/Panel/Section/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-panel-section-with-custom-secondary-panel-1-snap.png
Labels: area/ui

#687 chore(ui version): Update package ui version to 23.4.13
  centreon/packages/ui/package.json
Labels: automerge

#690 chore(ui-context version): Update package ui-context version to 23.4.6
  centreon/packages/ui-context/package.json
Labels: automerge

#622 enh(php): use centreon-test-lib 22.10.x
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#621 enh(php): use centreon-test-lib dev-master
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#679 fix(oidc): role mapping issue when checking the attribute path
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#696 fix(oidc): role mapping issue when checking the attribute path
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#688 enh(APIv2): AddHostGroup miscellaneous fixes
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostGroup/Application/Exceptions/HostGroupException.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroup.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupController.php
  centreon/tests/api/features/CloudHostGroup.feature
  centreon/tests/api/features/HostGroup.feature
  centreon/tests/php/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupTest.php
Labels: area/backend

#651 enh(API): Management of the Symfony environment variables
  centreon/src/Utility/EnvironmentFileManager.php
  centreon/tests/php/Utility/EnvironmentFileManagerTest.php
Labels: area/backend

#693 fix(API) fix miscellaneous fixes
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryRequest.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategorySchema.json
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
Labels: area/backend

#158 chore(deps): bump smarty/smarty from 3.1.44 to 3.1.46 [single-metric] (develop)
  widgets/centreon-widget-single-metric/composer.lock
Labels: area/backend

#586 chore(CI): Publish NPM packages on dev-22.10.x
  .github/actions/check-package-version/action.yml
  .github/actions/clean-up-npm-tag/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config-merge.yml
  .github/workflows/js-config.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-context-automerge.yml
  .github/workflows/ui-context-merge.yml
  .github/workflows/ui-context.yml
  .github/workflows/ui-merge.yml
  .github/workflows/ui.yml
  centreon/package-lock.json
  centreon/packages/js-config/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
Labels: area/ui

#711 chore(js-config version): Update package js-config version to 22.4.7
  centreon/package-lock.json
  centreon/packages/js-config/package-lock.json
  centreon/packages/js-config/package.json
Labels: automerge

#710 chore(ui version): Update package ui version to 22.4.5
  centreon/package-lock.json
  centreon/packages/ui/package.json
Labels: automerge

#709 fix(npm): Fix NPM publish tag to publish on
  .github/workflows/js-config-merge.yml
  .github/workflows/ui-context-merge.yml
  .github/workflows/ui-merge.yml
Labels: area/ui

#640 fix(web): update pending link on deprecated pages 22.04.x
  centreon/www/front_src/src/Header/RessourceStatusCounter/Service/index.tsx
Labels: area/backend

#723 chore(ui-context version): Update package ui-context version to 23.4.7
  centreon/packages/ui-context/package.json
Labels: automerge

#724 chore(ui version): Update package ui version to 23.4.15
  centreon/packages/ui/package.json
Labels: automerge

#725 fix(npm): Fix npm version on js-config
  centreon/packages/js-config/package.json
Labels: area/ui

#726 chore(js-config version): Update package js-config version to 23.4.15
  centreon/packages/js-config/package.json
Labels: automerge

#715 enh(host): store macros into vault
  centreon/www/class/centreonHost.class.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#665 feat(API) add GET host severities endpoint
  centreon/config/routes/Centreon/host_severity.yaml
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostSeverity/Application/Exception/HostSeverityException.php
  centreon/src/Core/HostSeverity/Application/Repository/ReadHostSeverityRepositoryInterface.php
  centreon/src/Core/HostSeverity/Application/UseCase/FindHostSeverities/FindHostSeverities.php
  centreon/src/Core/HostSeverity/Application/UseCase/FindHostSeverities/FindHostSeveritiesResponse.php
  centreon/src/Core/HostSeverity/Domain/Model/HostSeverity.php
  centreon/src/Core/HostSeverity/Domain/Model/NewHostSeverity.php
  centreon/src/Core/HostSeverity/Infrastructure/API/FindHostSeverities/FindHostSeveritiesController.php
  centreon/src/Core/HostSeverity/Infrastructure/API/FindHostSeverities/FindHostSeveritiesPresenter.php
  centreon/src/Core/HostSeverity/Infrastructure/API/FindHostSeverities/FindHostSeveritiesRoute.yaml
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbReadHostSeverityRepository.php
  centreon/tests/api/features/HostSeverity.feature
  centreon/tests/php/Core/HostSeverity/Application/UseCase/FindHostSeverities/FindHostSeveritiesTest.php
  centreon/tests/php/Core/HostSeverity/Domain/Model/HostSeverityTest.php
  centreon/tests/php/Core/HostSeverity/Domain/Model/NewHostseverityTest.php
Labels: area/backend

#673 enh(API) remove old GET host severities
  centreon/config/routes/Centreon/host_severity.yaml
  centreon/src/Centreon/Application/Controller/HostSeverityController.php
  centreon/src/Centreon/Domain/HostConfiguration/HostSeverityService.php
  centreon/src/Centreon/Domain/HostConfiguration/Interfaces/HostSeverity/HostSeverityReadRepositoryInterface.php
  centreon/src/Centreon/Domain/HostConfiguration/Interfaces/HostSeverity/HostSeverityServiceInterface.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeverities.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesResponse.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostSeverity/HostSeverityV2110.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostSeverity/HostSeverityV2110Factory.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/Repository/HostSeverityRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesResponseTest.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/HostSeverity/FindHostSeveritiesTest.php
Labels: area/backend

#720 fix(conf) massive change in host and service
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service/serviceByHostGroup.php
Labels: area/backend

#732 fix(conf) massive change in host and service (#720)
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service/serviceByHostGroup.php
Labels: area/backend

#730 fix(conf) massive change in host and service (#720)
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service/serviceByHostGroup.php
Labels: area/backend

#278 fix(sso) remove subscriber and use a Symfony authenticator
  centreon/config/packages/security.yaml
  centreon/config/services.yaml
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Domain/Exception/SSOAuthenticationException.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
  centreon/src/EventSubscriber/WebSSOEventSubscriber.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/src/Security/WebSSOAuthenticator.php
  centreon/tests/php/EventSubscriber/WebSSOEventSubscriberTest.php
  centreon/www/front_src/src/Main/useUser.ts
Labels: area/backend

#735 chore(ui-context version): Update package ui-context version to 22.4.6
  centreon/package-lock.json
  centreon/packages/ui-context/package.json
Labels: automerge

#666 feat(APIv2): add a DELETE and POST endpoints for host severities
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Common/Domain/TrimmedString.php
  centreon/src/Core/HostSeverity/Application/Exception/HostSeverityException.php
  centreon/src/Core/HostSeverity/Application/Repository/ReadHostSeverityRepositoryInterface.php
  centreon/src/Core/HostSeverity/Application/Repository/WriteHostSeverityRepositoryInterface.php
  centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
  centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityRequest.php
  centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityResponse.php
  centreon/src/Core/HostSeverity/Application/UseCase/DeleteHostSeverity/DeleteHostSeverity.php
  centreon/src/Core/HostSeverity/Domain/Model/NewHostSeverity.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityController.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityPresenter.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityRoute.yaml
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeveritySchema.json
  centreon/src/Core/HostSeverity/Infrastructure/API/DeleteHostSeverity/DeleteHostSeverityController.php
  centreon/src/Core/HostSeverity/Infrastructure/API/DeleteHostSeverity/DeleteHostSeverityRoute.yaml
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbReadHostSeverityRepository.php
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbWriteHostSeverityRepository.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/HostSeverity.feature
  centreon/tests/php/Core/Common/Domain/TrimmedStringTest.php
  centreon/tests/php/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityTest.php
  centreon/tests/php/Core/HostSeverity/Application/UseCase/DeleteHostSeverity/DeleteHostSeverityTest.php
  centreon/tests/php/Core/HostSeverity/Domain/Model/HostSeverityTest.php
  centreon/tests/php/Core/HostSeverity/Domain/Model/NewHostseverityTest.php
Labels: area/backend

#713 fix: innodb_additional_mem_pool_size deprecated since MariaDB 10.2
  centreon/packaging/debian/extra/centreon-database/80-centreon.cnf
  centreon/packaging/src/centreon-mysql.cnf
Labels: area/backend

#731 fix(conf) massive change in host and service (#720)
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service/serviceByHostGroup.php
Labels: area/backend

#739 fix(upgrade): fix upgrade transaction
  centreon/www/install/php/Update-22.04.8.php
Labels: area/backend

#746 revert(npm): Revert changes about package build
  .github/actions/build-npm-package/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/actions/web-frontend-component-test/action.yml
  centreon/package.json
  centreon/packages/js-config/package.json
  centreon/packages/js-config/swc/base.json
  centreon/packages/js-config/webpack/base/index.js
  centreon/packages/ui-context/.npmignore
  centreon/packages/ui-context/package.json
  centreon/packages/ui-context/tsconfig.json
  centreon/packages/ui/.npmignore
  centreon/packages/ui/package.json
  centreon/pnpm-lock.yaml
  centreon/setupTest.js
Labels: area/ui

#749 chore(ui-context version): Update package ui-context version to 23.4.8
  centreon/packages/ui-context/package.json
Labels: automerge

#750 chore(js-config version): Update package js-config version to 23.4.16
  centreon/packages/js-config/package.json
Labels: automerge

#751 chore(ui version): Update package ui version to 23.4.16
  centreon/packages/ui/package.json
Labels: automerge

#733 fix(packages/Listing/hedaer):fix header table
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Listing/Header/index.tsx
Labels: area/ui

#761 fix(behat): Fix resource monitoring tests
  centreon/tests/api/features/ResourceMonitoring.feature
  centreon/tests/api/features/ServiceMonitoring.feature
Labels: area/backend

#729 enh(API) handle topology ACLs in config timeperiods APIs
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/TimePeriod/Application/Exception/TimePeriodException.php
  centreon/src/Core/TimePeriod/Application/Repository/ReadTimePeriodRepositoryInterface.php
  centreon/src/Core/TimePeriod/Application/UseCase/AddTimePeriod/AddTimePeriod.php
  centreon/src/Core/TimePeriod/Application/UseCase/AddTimePeriod/AddTimePeriodResponse.php
  centreon/src/Core/TimePeriod/Application/UseCase/DeleteTimePeriod/DeleteTimePeriod.php
  centreon/src/Core/TimePeriod/Application/UseCase/FindTimePeriod/FindTimePeriod.php
  centreon/src/Core/TimePeriod/Application/UseCase/FindTimePeriod/FindTimePeriodResponse.php
  centreon/src/Core/TimePeriod/Application/UseCase/FindTimePeriods/FindTimePeriods.php
  centreon/src/Core/TimePeriod/Application/UseCase/FindTimePeriods/FindTimePeriodsResponse.php
  centreon/src/Core/TimePeriod/Application/UseCase/UpdateTimePeriod/UpdateTimePeriod.php
  centreon/src/Core/TimePeriod/Application/UseCase/UpdateTimePeriod/UpdateTimePeriodRequest.php
  centreon/src/Core/TimePeriod/Infrastructure/API/AddTimePeriod/AddTimePeriodController.php
  centreon/src/Core/TimePeriod/Infrastructure/API/AddTimePeriod/AddTimePeriodsPresenter.php
  centreon/src/Core/TimePeriod/Infrastructure/API/DeleteTimePeriod/DeleteTimePeriodController.php
  centreon/src/Core/TimePeriod/Infrastructure/API/FindTimePeriod/FindTimePeriodController.php
  centreon/src/Core/TimePeriod/Infrastructure/API/FindTimePeriods/FindTimePeriodsController.php
  centreon/src/Core/TimePeriod/Infrastructure/API/UpdateTimePeriod/UpdateTimePeriodController.php
  centreon/src/Core/TimePeriod/Infrastructure/Repository/DbReadTimePeriodRepository.php
  centreon/src/Core/TimePeriod/Infrastructure/Repository/DbWriteTimePeriodRepository.php
  centreon/tests/api/features/TimePeriodConfiguration.feature
  centreon/tests/php/Core/TimePeriod/Application/UseCase/AddTimePeriod/AddTimePeriodTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/DeleteTimePeriod/DeleteTimePeriodTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/FindTimePeriod/FindTimePeriodTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/FindTimePeriods/FindTimePeriodsTest.php
  centreon/tests/php/Core/TimePeriod/Application/UseCase/UpdateTimePeriod/UpdateTimePeriodTest.php
Labels: area/backend

#744 feat(API) add FindServiceGroups endpoint
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Core/HostGroup/Infrastructure/API/FindHostGroups/FindHostGroupsRoute.yaml
  centreon/src/Core/ServiceGroup/Application/Exception/ServiceGroupException.php
  centreon/src/Core/ServiceGroup/Application/Repository/ReadServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Application/UseCase/FindServiceGroups/FindServiceGroups.php
  centreon/src/Core/ServiceGroup/Application/UseCase/FindServiceGroups/FindServiceGroupsResponse.php
  centreon/src/Core/ServiceGroup/Domain/Model/NewServiceGroup.php
  centreon/src/Core/ServiceGroup/Domain/Model/ServiceGroup.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/FindServiceGroups/FindServiceGroupsController.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/FindServiceGroups/FindServiceGroupsPresenter.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/FindServiceGroups/FindServiceGroupsRoute.yaml
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ServiceGroup.feature
  centreon/tests/php/Core/ServiceGroup/Application/FindServiceGroups/FindServiceGroupsTest.php
  centreon/tests/php/Core/ServiceGroup/Domain/Model/NewServiceGroupTest.php
  centreon/tests/php/Core/ServiceGroup/Domain/Model/ServiceGroupTest.php
Labels: area/backend

#714 fix(npm): Fix packages version
  centreon/package-lock.json
  centreon/packages/js-config/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
Labels: area/ui

#775 chore(ui-context version): Update package ui-context version to 22.10.7
  centreon/package-lock.json
  centreon/packages/ui-context/package.json
Labels: automerge

#777 chore(ui version): Update package ui version to 22.10.10
  centreon/package-lock.json
  centreon/packages/ui/package.json
Labels: automerge

#779 fix(APIv2): "is_activated" field was not saved for AddHostSeverity
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbWriteHostSeverityRepository.php
Labels: area/backend

#728 enh (RT): Optimisation of SQL queries to reduce callbacks on the legacy services monitoring page.
  centreon/www/class/centreonHost.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
  centreon/www/include/monitoring/status/Services/xsl/service.xsl
Labels: area/backend

#789 chore(js-config version): Update package js-config version to 23.4.17
  centreon/packages/js-config/package.json
Labels: automerge

#624 enh(php): use centreon-test-lib 21.10.x
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#271 [enh](ldap): add ldap connection timeout to avoid infinite connection
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/class/CentreonLDAPAdmin.class.php
  centreon/www/class/centreon-clapi/centreonLDAP.class.php
  centreon/www/class/centreonLDAP.class.php
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/ldap/DB-Func.php
  centreon/www/include/Administration/parameters/ldap/form.ihtml
  centreon/www/include/Administration/parameters/ldap/form.php
  centreon/www/include/Administration/parameters/ldap/help.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.0-beta.1.php
Labels: area/backend

#747 fix(packages/StatusChip):MON-15261-fix-colors-chips-RS
  centreon/packages/ui/package.json
  centreon/packages/ui/src/StatusChip/index.tsx
  centreon/packages/ui/src/ThemeProvider/palettes.ts
Labels: area/ui

#806 fix: correct html decoding in update for version 22.04.x
  centreon/www/install/php/Update-22.04.10.php
Labels: area/backend

#803 fix: correct html decoding in update for version 22.04.x
  centreon/www/install/php/Update-22.04.10.php
Labels: area/backend

#782 fix(e2e): Increase time out on waitUntil
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/web-frontend-component-test/action.yml
  .github/scripts/sql/standard.sql
  .gitignore
  centreon/cypress/support/commands.tsx
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Global -- displays resources of type anomaly-detection.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Global -- displays the Anomaly detection configuration modal when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Global -- displays the Anomaly detection criteria value on search proposition when user types type in the search bar.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Global -- displays the Anomaly detection criteria value when the type criteria chip is clicked and centreon-anomaly-detection is installed.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Global -- displays the wrench icon on graph actions when one row of a resource of anomaly-detection is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/Anomaly detection - Graph -- displays the modal of confirmation when clicking on save button of slider.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/displays the threshold in the modal - add button clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/displays the threshold in the modal - cancel button clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx/displays the threshold in the modal - delete button clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Listing/Listing.cypress.spec.tsx/Listing request -- executes a listing request with a limit param when the rows per page value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Listing/Listing.cypress.spec.tsx/Listing request -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/tests/e2e/cypress/e2e/Resources-status/01-listing/index.ts
  centreon/tests/e2e/cypress/e2e/Resources-status/02-actions/index.ts
  centreon/tests/e2e/cypress/support/e2e.ts
  centreon/webpack.config.js
  centreon/www/front_src/src/Header/UserMenu/UserMenu.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Save/FilterSave.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/Listing.cypress.spec.tsx
Labels: area/ui

#767 feat(API) add DeleteServiceGroup and AddServiceGroup endpoints
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/AccessGroup/Application/Repository/WriteAccessGroupRepositoryInterface.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbWriteAccessGroupRepository.php
  centreon/src/Core/ServiceGroup/Application/Exception/ServiceGroupException.php
  centreon/src/Core/ServiceGroup/Application/Repository/ReadServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Application/Repository/WriteServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Application/UseCase/AddServiceGroup/AddServiceGroup.php
  centreon/src/Core/ServiceGroup/Application/UseCase/AddServiceGroup/AddServiceGroupRequest.php
  centreon/src/Core/ServiceGroup/Application/UseCase/AddServiceGroup/AddServiceGroupResponse.php
  centreon/src/Core/ServiceGroup/Application/UseCase/DeleteServiceGroup/DeleteServiceGroup.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupController.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupPresenter.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupRoute.yaml
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupSchema.json
  centreon/src/Core/ServiceGroup/Infrastructure/API/DeleteServiceGroup/DeleteServiceGroupController.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/DeleteServiceGroup/DeleteServiceGroupRoute.yaml
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbWriteServiceGroupRepository.php
  centreon/tests/api/features/ServiceGroup.feature
  centreon/tests/php/Core/ServiceGroup/Application/AddServiceGroup/AddServiceGroupTest.php
  centreon/tests/php/Core/ServiceGroup/Application/DeleteServiceGroup/DeleteServiceGroupTest.php
Labels: area/backend

#721 enh(npm): Clean up and improve NPM package publication process
  .github/actions/get-latest-npm-beta-branch-version/action.yml
  .github/actions/get-latest-npm-beta-branch-version/index.js
  .github/actions/get-latest-npm-beta-branch-version/package.json
  .github/actions/get-latest-npm-beta-branch-version/pnpm-lock.yaml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-automerge.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  centreon/packages/ui/package.json
Labels: area/ui

#798 fix(behat): Fix resource monitoring tests (#761)
  centreon/tests/api/features/ResourceMonitoring.feature
  centreon/tests/api/features/ServiceMonitoring.feature
Labels: area/backend

#817 chore(lib): add Symfony UID Component
  centreon/composer.json
  centreon/composer.lock
  centreon/src/Utility/Interfaces/UUIDGeneratorInterface.php
  centreon/src/Utility/UUIDGenerator.php
Labels: area/backend

#805 fix: correct html decoding in update for version 22.04.x
  centreon/www/install/php/Update-22.04.10.php
Labels: area/backend

#795 fix(Resources/Grpah/AnomalyDetection): fix Wrong formula Anomaly Detection enveloppe computation causing threshold cross themselves
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/graph/AnomalyDetectionEstimatedEnvelopeThreshold.tsx
Labels: area/ui
