Repository centreon/centreon, pull requests merged in 2023-10, with the labels that each got.

#2258 Fix(UI): Fix gauge and single bar glitch
  centreon/packages/ui/src/Graph/Gauge/ResponsiveGauge.tsx
  centreon/packages/ui/src/Graph/SingleBar/ResponsiveSingleBar.tsx
Labels: area/ui

#2233 fix(duplication): correctly update ACL for duplicated host/services (…
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2269 Fix(UI): Fix dashboard description update
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateDashboard.ts
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/DashboardConfigModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/useDashboardsOverview.tsx
Labels: area/ui

#2272 Revert "enh(cloud notifications): remove the {{state}} macro from the email template"
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/Tests/PanelCreate.cypress.spec.tsx/Create Panel -- displays the Email Body field with the default initial value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/Tests/PanelCreate.cypress.spec.tsx/Create Panel -- displays the Email Subject field with the default initial value.snap.png
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/MacrosButton.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/Tests/PanelCreate.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/utils.tsx
Labels: area/ui

#2278 enh(monitoring): deletion of monitoring pages for next major message
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/monitoring/objectDetails/hostDetails.php
  centreon/www/include/monitoring/objectDetails/serviceDetails.php
  centreon/www/include/monitoring/status/Hosts/host.php
  centreon/www/include/monitoring/status/Services/service.php
Labels: area/backend

#2282 enh(send-statistics): add information regarding user filter usage
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#2219 Fix(Query): in getHostServicesName method
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2281 fix(UI): Fix thresholds sync on line charts
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Axes/index.tsx
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/RegularLines/index.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
Labels: area/ui

#2221 Fix(Query): get host services name method
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2284 enh(broker): add new version of BBDO protocol
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/install/createTables.sql
Labels: area/backend

#2290 enh(CI): Add notification to lighthouse
  centreon/lighthouse/src/fixtures/notification.js
  centreon/lighthouse/src/lighthouseReport.ts
  centreon/lighthouse/src/pages/notifications.ts
Labels: area/ui

#2279 fix(update) move sql update scripts to php file
  centreon/www/install/php/Update-23.10.0.php
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/backend

#2280 enh(UI): Display title and description
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- disables the Add button when metrics are removed from the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- displays the title and the description in the panel.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as critical when the critical threshold is customized.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value with the default color when thresholds are disabled.snap.png
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Graph/Gauge/ResponsiveGauge.tsx
  centreon/packages/ui/src/Graph/SingleBar/ResponsiveSingleBar.tsx
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/RichTextEditor/index.stories.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/usePanelStyles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.styles.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
Labels: area/ui

#2224 enh(UI): Add Refresh interval
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/packages/ui/src/Form/Inputs/Radio.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/components/Form/Dashboard/Dashboard.resource.ts
  centreon/packages/ui/src/components/Form/Dashboard/DashboardForm.styles.ts
  centreon/packages/ui/src/components/Form/Dashboard/DashboardForm.tsx
  centreon/packages/ui/src/components/Form/Dashboard/GlobalRefreshFieldOption.tsx
  centreon/packages/ui/src/components/Form/Dashboard/translatedLabels.ts
  centreon/packages/ui/src/utils/useRefreshInterval.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/useRefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useCreateDashboard.ts
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/DashboardConfigModal.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/index.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/index.tsx
  centreon/www/widgets/src/models.ts
Labels: area/ui

#2301 fix(UI): Avoid widget edition modal overlapping
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Navigation/Sidebar/index.tsx
  centreon/www/front_src/src/Navigation/navigationAtoms.ts
Labels: area/ui

#2228 enh(UI): Setup manual refresh
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Duplicate -- duplicates the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the refresh button when the more actions button is clicked.snap.png
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/packages/ui/src/components/Form/Dashboard/GlobalRefreshFieldOption.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/useRefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/usePanelStyles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateDashboard.ts
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/index.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
Labels: area/ui

#2293 fix(authentification) : The user can login using SAML/OpenID using condition only if all conditions are met
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/Conditions.php
Labels: area/backend

#2287 enh(UI): Global UI feedbacks on dashboard
  centreon/cypress/fixtures/Dashboards/emptyDashboards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Add widget -- adds a widget when a widget type is selected and the submission button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- deletes a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Duplicate -- duplicates the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the refresh button when the more actions button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- creates a dashboard when the corresponding button is clicked and the title is filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- displays a welcome label when the dashboard library is empty.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/packages/ui/src/Dashboard/Layout.tsx
  centreon/packages/ui/src/Graph/Gauge/Gauge.tsx
  centreon/packages/ui/src/Graph/LineChart/index.tsx
  centreon/packages/ui/src/ParentSize/ParentSize.tsx
  centreon/packages/ui/src/ParentSize/index.ts
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/packages/ui/src/TimePeriods/index.tsx
  centreon/packages/ui/src/components/DataTable/DataTable.styles.ts
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.styles.ts
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayoutActions.tsx
  centreon/packages/ui/src/components/Menu/Menu.styles.ts
  centreon/packages/ui/src/components/Modal/ModalHeader.tsx
  centreon/packages/ui/src/index.ts
  centreon/pnpm-lock.yaml
  centreon/tsconfig.json
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddWidgetButton.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/DashboardsPage.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/DashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsQuickAccess/DashboardsQuickAccessMenu.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/Extensions/Listing/ExtensionDetailsDialog/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/DetailsLine.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/index.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
Labels: area/ui

#2208 Fix(Query): Fix the method used to retrieve host and service names
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2207 Fix(Query): Fix the method used to retrieve host and service names
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2294 enh(UI): Wording adjustments
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/useThreshold.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetSelection.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/widgets/src/centreon-widget-generictext/properties.json
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/properties.json
  centreon/www/widgets/src/translatedLabels.ts
Labels: area/ui

#2289 enh(CI): Add dashboard and notification pages to lighthouse
  .github/actions/lighthouse-performance-testing/action.yml
  centreon/lighthouse/features.json
  centreon/lighthouse/package.json
  centreon/lighthouse/src/fixtures/dashboardPanels.js
  centreon/lighthouse/src/fixtures/notification.js
  centreon/lighthouse/src/lighthouseReport.ts
  centreon/lighthouse/src/pages/dashboards.ts
  centreon/lighthouse/src/pages/notifications.ts
  centreon/packages/ui/src/InputField/Select/index.tsx
  centreon/pnpm-lock.yaml
Labels: area/ui

#2295 enh(dashboards): Renaming legacy dashboard topology & translations
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/rest_api/rest_api.postman_collection.json
  centreon/www/install/insertTopology.sql
  centreon/www/install/menu_translation.php
  centreon/www/install/php/Update-23.10.0.php
Labels: area/backend

#2307 fix(authentification) : The user can login using SAML/OpenID using condition only if all conditions are met
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/Conditions.php
Labels: area/backend

#2311 enh(Resource Status) Implement a loading indicator in the listing component when switching between view
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
Labels: area/ui

#2314 enh(feature flag): Add Feature Flag Atom to the @centreon/ui-context to use it in different Centreon Modules
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/platformFeauresAtom.ts
  centreon/packages/ui-context/src/types.ts
  centreon/www/front_src/src/Main/usePlatformFeatures.ts
  centreon/www/front_src/src/Resources/Details/index.tsx
  centreon/www/front_src/src/Resources/Filter/SearchHelp.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/SearchHelp.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/index.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
  centreon/www/front_src/src/Resources/Listing/testUtils.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/front_src/src/api/models.ts
Labels: area/ui

#2309 enh(UI): Metrics graph feedback
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- disables the Add button when metrics are removed from the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/packages/ui/src/Graph/LineChart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/useLegend.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.tsx
  centreon/www/widgets/src/useThresholds.ts
Labels: area/ui

#2302 fix(UI): Fix cloned widgets
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as success and thresholds when thresholds are enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as success when thresholds are disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as warning when the warning threshold is customized.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value with the default color and thresholds when thresholds are enabled.snap.png
  centreon/packages/ui/src/utils/useRefreshInterval.ts
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/useDashboardConfig.tsx
Labels: area/ui

#2308 enh(UI): Add service group/category on dataset selection
  centreon/packages/ui/src/Graph/SingleBar/SingleBar.tsx
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/packages/ui/src/api/useGraphQuery/models.ts
  centreon/packages/ui/src/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/useMetricsOnly.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/models.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
Labels: area/ui

#2310 fix(UI): Add small padding in single bar
  centreon/packages/ui/src/Graph/SingleBar/ResponsiveSingleBar.tsx
Labels: area/ui

#2322 fix(recurrentDowntime): take correctly service template into account …
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#2336 fix(dashboards): Performance data doesn't display all metrics according to search
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
Labels: area/backend

#2316 enh(UI): Dashboard page feedbacks
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Add widget -- adds a widget when a widget type is selected and the submission button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- deletes a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Duplicate -- duplicates the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the refresh button when the more actions button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as warning when the warning threshold is customized.snap.png
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/packages/ui/src/components/Header/Header.styles.ts
  centreon/packages/ui/src/components/Header/PageHeader/PageHeader.styles.ts
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/widgets/src/centreon-widget-generictext/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
Labels: area/ui

#2318 fix(dashboards): performance endpoint doesn't send back result according to limit
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
Labels: area/backend

#2223 enh(ui): change wording from "Massive Change" to "Mass Change" (#2192)
  centreon/features/MassiveChangeHosts.feature
  centreon/features/MassiveChangeServices.feature
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/features/bootstrap/MassiveChangeServicesContext.php
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/class/centreonLogAction.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
  centreon/www/include/Administration/configChangelog/viewLogsDetails.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/listContact.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
  centreon/www/include/configuration/configObject/contact_template_model/listContactTemplateModel.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/service/listServiceByHost.php
  centreon/www/include/configuration/configObject/service/listServiceByHostGroup.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend

#2286 enh(broker): add new version of BBDO protocol (#2284)
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/install/createTables.sql
Labels: area/backend

#2342 fix(api/severity) Fixing SQL queries to retrieve the severity correctly in host and host template lists
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
Labels: area/backend

#2345 fix(recurrentDowntime): take correctly service template into account
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#2315 enh(UI): Add text alignment on the widget description
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Center when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Right when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Bullet List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 1 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 2 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 3 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 4 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 5 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 6 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Number List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/index.stories.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/AlignPicker.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ToolbarPlugin.styles.ts
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/index.tsx
  centreon/packages/ui/src/components/Menu/Button/MenuButton.tsx
Labels: area/ui

#1677 enh (real-time): Real-time SQL queries modified to distinguish them from configuration SQL queries
  centreon/src/Centreon/Infrastructure/Monitoring/HostGroup/HostGroupRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/MetaService/Repository/MetaServiceMetricRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/ServiceGroup/ServiceGroupRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbReadAcknowledgementRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Downtime/DbReadDowntimeRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/FindIndex/DbReadIndexDataRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Hostgroup/DbReadHostgroupRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/MetaService/DbReadMetaServiceRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbReadServiceRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Servicegroup/DbReadServicegroupRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Severity/RealTime/Infrastructure/Repository/DbReadSeverityRepository.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbReadTagRepository.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
  centreon/www/api/class/centreon_performance_service.class.php
  centreon/www/api/class/centreon_topcounter.class.php
  centreon/www/class/centreonGraphStatus.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/centreonMonitoring.class.php
  centreon/www/include/eventLogs/export/QueryGenerator.php
  centreon/www/include/eventLogs/xml/data.php
  centreon/www/include/monitoring/comments/listComment.php
  centreon/www/include/monitoring/downtime/listDowntime.php
  centreon/www/include/monitoring/status/Common/commonJS.php
  centreon/www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  centreon/www/include/monitoring/status/Hosts/xml/hostXML.php
  centreon/www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  centreon/www/include/monitoring/status/Services/xml/serviceGridXML.php
  centreon/www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  centreon/www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  centreon/www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
  widgets/centreon-widget-engine-status/engine-status/index.php
  widgets/centreon-widget-global-health/global-health/src/global_health.php
  widgets/centreon-widget-graph-monitoring/graph-monitoring/index.php
  widgets/centreon-widget-graph-monitoring/graph-monitoring/src/generateGraph.php
  widgets/centreon-widget-grid-map/grid-map/src/table.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/export.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/class/HostgroupMonitoring.class.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/index.php
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
  widgets/centreon-widget-service-monitoring/service-monitoring/src/export.php
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
  widgets/centreon-widget-single-metric/single-metric/index.php
  widgets/centreon-widget-tactical-overview/tactical-overview/src/hosts_status.php
  widgets/centreon-widget-tactical-overview/tactical-overview/src/services_status.php
Labels: area/backend

#2347 enh(UI): Add confirmation poppin + improve actions list
  centreon/packages/ui/src/ActionsList/ActionsList.styles.ts
  centreon/packages/ui/src/ActionsList/index.stories.tsx
  centreon/packages/ui/src/ActionsList/index.tsx
  centreon/packages/ui/src/ActionsList/models.ts
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/ConfirmationTooltip.stories.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/ConfirmationTooltip.styles.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/ConfirmationTooltip.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/TooltipContent.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/index.ts
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/models.ts
  centreon/packages/ui/src/components/Tooltip/Tooltip.styles.ts
  centreon/packages/ui/src/components/Tooltip/Tooltip.tsx
Labels: area/ui

#2331 feat(api) new endpoint: AddCommand
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Command/AddAndFindCommands.yaml
  centreon/doc/API/v23.10/Configuration/Command/Schema/AddCommandRequest.yaml
  centreon/doc/API/v23.10/Configuration/Command/Schema/AddCommandResponse.yaml
  centreon/doc/API/v23.10/Configuration/Command/Schema/FindCommandsResponse.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Command/Application/Exception/CommandException.php
  centreon/src/Core/Command/Application/Repository/ReadCommandRepositoryInterface.php
  centreon/src/Core/Command/Application/Repository/WriteCommandRepositoryInterface.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/AddCommand.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/AddCommandPresenterInterface.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/AddCommandRequest.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/AddCommandResponse.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/AddCommandValidation.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/ArgumentDto.php
  centreon/src/Core/Command/Application/UseCase/AddCommand/MacroDto.php
  centreon/src/Core/Command/Domain/Model/Argument.php
  centreon/src/Core/Command/Domain/Model/Command.php
  centreon/src/Core/Command/Domain/Model/NewCommand.php
  centreon/src/Core/Command/Infrastructure/API/AddCommand/AddCommandController.php
  centreon/src/Core/Command/Infrastructure/API/AddCommand/AddCommandPresenter.php
  centreon/src/Core/Command/Infrastructure/API/AddCommand/AddCommandRoute.yaml
  centreon/src/Core/Command/Infrastructure/API/AddCommand/AddCommandSchema.json
  centreon/src/Core/Command/Infrastructure/Repository/DbReadCommandRepository.php
  centreon/src/Core/Command/Infrastructure/Repository/DbWriteCommandRepository.php
  centreon/src/Core/CommandMacro/Domain/Model/NewCommandMacro.php
  centreon/src/Core/Common/Domain/SimpleEntity.php
  centreon/src/Core/Connector/Application/Repository/ReadConnectorRepositoryInterface.php
  centreon/src/Core/Connector/Infrastructure/Repository/DbReadConnectorRepository.php
  centreon/src/Core/GraphTemplate/Application/Repository/ReadGraphTemplateRepositoryInterface.php
  centreon/src/Core/GraphTemplate/Infrastructure/Repository/DbReadGraphTemplateRepository.php
  centreon/src/Core/Host/Domain/Model/TinyHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/Service/Domain/Model/ServiceLight.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/tests/php/Core/Command/Application/UseCase/AddCommand/AddCommandTest.php
  centreon/tests/php/Core/Command/Application/UseCase/AddCommand/AddCommandValidationTest.php
  centreon/tests/php/Core/Command/Application/UseCase/FindCommands/FindCommandsTest.php
  centreon/tests/php/Core/Command/Domain/Model/ArgumentTest.php
  centreon/tests/php/Core/Command/Domain/Model/CommandTest.php
  centreon/tests/php/Core/Command/Domain/Model/NewCommandTest.php
  centreon/tests/php/Core/Command/Infrastructure/API/AddCommand/AddCommandPresenterStub.php
  centreon/tests/php/Core/CommandMacro/Domain/Model/NewCommandMacroTest.php
  centreon/tests/php/Core/Host/Application/UseCase/FindHosts/FindHosts.php
  centreon/tests/php/Core/Host/Domain/Model/TinyHostTest.php
  centreon/tests/php/Core/Service/Domain/Model/ServiceLightTest.php
Labels: area/backend

#2357 fix(UI): Fix single bar crash
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/Gauge/AnimatedPie.tsx
  centreon/pnpm-lock.yaml
Labels: area/ui

#2350 enh (real-time): Real-time SQL queries modified to distinguish them from configuration SQL queries
  centreon/src/Centreon/Infrastructure/Monitoring/HostGroup/HostGroupRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/MetaService/Repository/MetaServiceMetricRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/ServiceGroup/ServiceGroupRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Monitoring/Timeline/TimelineRepositoryRDB.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbReadAcknowledgementRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Downtime/DbReadDowntimeRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/FindIndex/DbReadIndexDataRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Hostgroup/DbReadHostgroupRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/MetaService/DbReadMetaServiceRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbReadServiceRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Servicegroup/DbReadServicegroupRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Severity/RealTime/Infrastructure/Repository/DbReadSeverityRepository.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbReadTagRepository.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
  centreon/www/api/class/centreon_performance_service.class.php
  centreon/www/api/class/centreon_topcounter.class.php
  centreon/www/class/centreonGraphStatus.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/centreonMonitoring.class.php
  centreon/www/include/eventLogs/export/QueryGenerator.php
  centreon/www/include/eventLogs/xml/data.php
  centreon/www/include/monitoring/comments/listComment.php
  centreon/www/include/monitoring/downtime/listDowntime.php
  centreon/www/include/monitoring/status/Common/commonJS.php
  centreon/www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
  centreon/www/include/monitoring/status/Hosts/xml/hostXML.php
  centreon/www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
  centreon/www/include/monitoring/status/Services/xml/serviceGridXML.php
  centreon/www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
  centreon/www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
  centreon/www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
  widgets/centreon-widget-engine-status/engine-status/index.php
  widgets/centreon-widget-global-health/global-health/src/global_health.php
  widgets/centreon-widget-graph-monitoring/graph-monitoring/index.php
  widgets/centreon-widget-graph-monitoring/graph-monitoring/src/generateGraph.php
  widgets/centreon-widget-grid-map/grid-map/src/table.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/export.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/class/HostgroupMonitoring.class.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/index.php
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
  widgets/centreon-widget-service-monitoring/service-monitoring/src/export.php
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
  widgets/centreon-widget-single-metric/single-metric/index.php
  widgets/centreon-widget-tactical-overview/tactical-overview/src/hosts_status.php
  widgets/centreon-widget-tactical-overview/tactical-overview/src/services_status.php
Labels: area/backend

#2358 fix(UI): Fix edit dashboard initialization
  centreon/tests/e2e/cypress/e2e/Dashboards/05-dashboard-check-permissions/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.tsx
Labels: area/ui

#2009 feat(mobile): third party login form redirect
  centreon/phpstan.core.neon
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/ErrorAclConditionsResponse.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/LoginRequest.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/LoginResponse.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/PasswordExpiredResponse.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/ThirdPartyLoginForm.php
  centreon/src/Core/Security/Authentication/Application/UseCase/LogoutSession/LogoutSession.php
  centreon/src/Core/Security/Authentication/Domain/Exception/SSOAuthenticationException.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/Local/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/LoginPresenter.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/SLSController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/LogoutSession/LogoutSessionController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/ProviderAuthenticationFactory.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/SettingsFormatterInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/GroupsMapping.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LoginSession/LoginSessionTest.php
Labels: area/backend

#2356 enh(CEIP): Add dashboards statistics in CEIP cron
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#2343 enh(centreon-php): add service to the search of 'monitoring/hostgroups' endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#2382 enh(Permissions Rights): add missing rights sql permissions for centreon db user
  centreon/www/install/steps/process/createDbUser.php
Labels: area/backend

#2383 [release-23.10-next] fix(cloud-notifications): Contact group listing not accessible #2367
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Notification/FindNotifiableContactGroups.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Schema/NotifiableContactGroups.Listing.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableContactGroups/FindNotifiableContactGroups.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableContactGroups/FindNotifiableContactGroupsPresenterInterface.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableContactGroups/FindNotifiableContactGroupsResponse.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableContactGroups/Response/NotifiableContactGroupDto.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableContactGroups/FindNotifiableContactGroupsController.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableContactGroups/FindNotifiableContactGroupsPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableContactGroups/FindNotifiableContactGroupsRoute.yaml
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotifiableContactGroups/FindNotifiableContactGroupsTest.php
  centreon/tests/php/Core/Notification/Infrastructure/API/FindNotifiableContactGroups/FindNotifiableContactGroupsPresenterStub.php
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/api/endpoints.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx
Labels: area/ui, area/backend

#2403 fix(UI): Gauge thresholds are not displayed
  centreon/packages/ui/package.json
  centreon/pnpm-lock.yaml
Labels: area/ui

#2338 add ezv rest in register list
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/register.php
Labels: area/backend

#2417 fix(resources): h.alias filter fixed
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#2404 enh(cloud notifications) : remove id from default email template
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx/Create Panel -- displays the Email Body field with the default initial value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx/Create Panel -- displays the Email Subject field with the default initial value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx/Create Panel -- sends a request to add a new notification with the form values When the Confirm button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx/Create Panel -- sends a request to add a new notification with the form values when the Confirm button is clicked.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/testUtils.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/utils.tsx
Labels: area/ui

#2416 fix(resources): correctly handle new condition on monitoring server l…
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/RealTimeMonitoringServerRepositoryRDB.php
Labels: area/backend

#2413 fix(UI) : UI try to get resources even if /monitoring/resources is not allowed
  centreon/www/front_src/src/components/ReactRouter/index.tsx
Labels: area/ui

#2422 fix(resources): h.alias filter fixed (MON-23597)
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#2436 fix(UI): Ensure the data property is always defined
  centreon/www/front_src/src/Dashboards/Dashboard/hooks/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/Dashboard/hooks/useSaveDashboard.ts
Labels: area/ui

#2435 fix(top counters) : error when following top counter links from legacy pages
  centreon/www/front_src/src/Header/Resources/utils.ts
Labels: area/ui

#2439 fix(upgrade): handle correctly topology database update
  centreon/www/install/php/Update-23.04.1.php
  centreon/www/install/php/Update-23.04.8.php
  centreon/www/install/sql/centreon/Update-DB-23.04.1.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.8.sql
Labels: area/backend

#2450 enh (api): Removal of configuration-type ACLs for administrator and user endpoints
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/src/Centreon/Application/Controller/UserController.php
Labels: area/backend

#2431 fix(dashboards): list users of same contactgroups for dashboard sharing as non admin
  centreon/src/Core/Application/Configuration/User/Repository/ReadUserRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-check-permissions.json
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-share.json
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsTest.php
Labels: area/backend

#2459 Fix(UI): Fix save existing filters
  centreon/www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/actions/Save.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#2462 Fix(CI): Fix Resources listing tests
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
Labels: area/ui

#2467 fix(UI): Disable the save button when the selected filter is not edited
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx/Filter storage -- populates filter with values from localStorage if available.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/InputField/Search/PersistentTooltip.tsx
  centreon/src/Core/Resources/Application/Repository/ReadResourceRepositoryInterface.php
  centreon/src/Core/Resources/Application/UseCase/FindResourcesByParent/FindResourcesByParent.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/front_src/src/Resources/Filter/Criterias/index.tsx
  centreon/www/front_src/src/Resources/Filter/Criterias/models.ts
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/EditFilterButton.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/index.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/useActionFilter.ts
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Save/CreateFilterDialog.tsx
  centreon/www/front_src/src/Resources/Filter/Save/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/actions/Save.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/useCheckBox.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/translatedLabels.ts
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/front_src/src/Resources/Listing/useLoadResources/index.ts
Labels: area/ui
