Repository centreon/centreon, pull requests merged in 2023-09, with the labels that each got.

#2121 enh(web): Add feature flag for Anomaly Detection exclusion of periods
  centreon/config/features.json
Labels: area/backend

#2124 fix(gorgone): pull modules stop responding
  centreon-gorgone/gorgone/modules/core/pull/class.pm
  centreon-gorgone/gorgone/modules/core/pullwss/class.pm
Labels: bug

#1989 fix(resources status): fix query for hostgroups and categories filter
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/tests/api/features/ResourceMonitoring.feature
Labels: area/backend

#2131 fix(api) additive inheritance on service and service template
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
Labels: area/backend

#2127 enh (ACL): Added an ACL to manage authentication tokens
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/www/class/centreon-clapi/centreonACLAction.class.php
  centreon/www/include/options/accessLists/actionsACL/DB-Func.php
  centreon/www/include/options/accessLists/actionsACL/formActionsAccess.ihtml
  centreon/www/include/options/accessLists/actionsACL/formActionsAccess.php
  centreon/www/include/options/accessLists/actionsACL/help.php
  centreon/www/install/insertTopology.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/backend

#2117 feat(Resources Status Listing) : Implement "By Services" visualization
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sends a request with types service,metaservice.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- enables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sends a request to get all resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sets the column names to the default ones.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sorts columnns by newest duration.snap.png
  centreon/packages/ui/src/Button/Icon/index.tsx
  centreon/packages/ui/src/SortableItems/SortableItem.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/Action.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/Visualization.styles.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/Visualization.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/index.ts
  centreon/www/front_src/src/Resources/Actions/Visualization/useIconPath.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
  centreon/www/front_src/src/Resources/Filter/api/decoders.ts
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/front_src/src/Resources/Filter/useBackToVisualizationByAll.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/index.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
Labels: area/ui

#2152 Feat(dependency):upgrade symfony http kernel dependency on centreon web
  centreon/composer.lock
Labels: area/backend

#2125 enh(feature flag): backport of Feature Flag functionality to 23.04
  centreon/config/features.json
  centreon/config/packages/security.yaml
  centreon/config/routes/Centreon/platform.yaml
  centreon/config/services.yaml
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/doc/API/v23.04/Platform/Features.yaml
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/src/Centreon/Application/Controller/PlatformController.php
  centreon/src/Centreon/Application/DataRepresenter/Topology/NavigationList.php
  centreon/src/Centreon/Application/Webservice/TopologyWebservice.php
  centreon/src/Centreon/Domain/Entity/Topology.php
  centreon/src/Centreon/Domain/Log/LoggerTrait.php
  centreon/src/Centreon/Domain/Repository/TopologyRepository.php
  centreon/src/Core/Common/Application/FeatureFlagsInterface.php
  centreon/src/Core/Common/Infrastructure/FeatureFlags.php
  centreon/src/Core/Platform/Application/UseCase/FindFeatures/FindFeatures.php
  centreon/src/Core/Platform/Application/UseCase/FindFeatures/FindFeaturesPresenterInterface.php
  centreon/src/Core/Platform/Application/UseCase/FindFeatures/FindFeaturesResponse.php
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
  centreon/src/Core/Platform/Infrastructure/API/FindFeatures/FindFeaturesController.php
  centreon/src/Core/Platform/Infrastructure/API/FindFeatures/FindFeaturesPresenter.php
  centreon/src/Core/Platform/Infrastructure/API/FindFeatures/FindFeaturesRoute.yaml
  centreon/src/Core/Platform/Infrastructure/API/UpdateVersions/UpdateVersionsController.php
  centreon/src/Core/Platform/Infrastructure/API/UpdateVersions/UpdateVersionsPresenter.php
  centreon/src/Core/Platform/Infrastructure/API/UpdateVersions/UpdateVersionsRoute.yaml
  centreon/src/Core/Platform/Infrastructure/API/UpdateVersions/UpdateVersionsSchema.json
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/src/EventSubscriber/FeatureFlagEventSubscriber.php
  centreon/tests/api/Context/FeatureFlagContext.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/PlatformFeatures.feature
  centreon/tests/api/features/PlatformVersions.feature
  centreon/tests/php/Core/Common/Infrastructure/FeatureFlagsTest.php
  centreon/tests/php/Core/Platform/Application/UseCase/FindFeatures/FindFeaturesPresenterStub.php
  centreon/tests/php/Core/Platform/Application/UseCase/FindFeatures/FindFeaturesTest.php
  centreon/www/front_src/src/Main/atoms/platformFeaturesAtom.ts
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/usePlatformFeatures.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/front_src/src/api/endpoint.ts
  centreon/www/front_src/src/api/models.ts
  centreon/www/include/common/common-Func.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.04.8.php
  centreon/www/install/sql/centreon/Update-DB-23.04.8.sql
  centreon/www/main.get.php
Labels: area/ui, area/backend

#2156 [23.04] enh(vault): Add feature flag to vault configuration endpoints (#2026)
  centreon/config/features.json
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/DeleteVaultConfiguration/DeleteVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfiguration/FindVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfigurations/FindVaultConfigurationsRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationRoute.yaml
  centreon/tests/api/features/VaultConfiguration.feature
Labels: area/backend

#2158 [23.04] enh(web): Add feature flag for Anomaly Detection exclusion of periods (#2121)
  centreon/config/features.json
Labels: area/backend

#2160 Feat(Dependency):Upgrade symfony/http-kernel
  centreon/composer.lock
Labels: area/backend

#2148 enh(api) add notify property in centreon_application_monitoring_getoneservice
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Centreon/Domain/Monitoring/Service.php
Labels: area/backend

#2167 Feat(dependency):upgrade symfony/http-kernel
  centreon/composer.lock
Labels: area/backend

#2168 Feat(Dependency) : Upgrade enshrined/svg-sanitize
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#2171 fix(dashboard): add limit to resources and metrics listing query
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#2174 Feat(Dependency):Upgrade enshrined/svg-sanitize
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#2164 feat(api) new endpoints DeleteToken / DeleteTokenByUserId
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Administration/Token/DeleteToken.yaml
  centreon/doc/API/v23.10/Administration/Token/DeleteTokenByUser.yaml
  centreon/doc/API/v23.10/Administration/Token/QueryParameter/TokenName.yaml
  centreon/doc/API/v23.10/Administration/Token/QueryParameter/UserId.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Token/Application/Exception/TokenException.php
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Application/Repository/WriteTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Application/UseCase/DeleteToken/DeleteToken.php
  centreon/src/Core/Security/Token/Infrastructure/API/DeleteToken/DeleteTokenController.php
  centreon/src/Core/Security/Token/Infrastructure/API/DeleteToken/DeleteTokenRoute.yaml
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/tests/api/features/Token.feature
  centreon/tests/php/Core/Security/Token/Application/UseCase/DeleteToken/DeleteTokenTest.php
Labels: area/backend

#2173 enh(CEIP) add ApiTokens stats to cron
  centreon/cron/centreon-send-stats.php
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#2176 Feat(Dependency):Upgrade enshrined/svg-sanitize
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#2179 Feat(Dependency):Upgrade enshrined/svg-sanitize
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#2180 Upgrade enshrined/svg-sanitize from 0.14.1 to 0.15.0
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#2053 Do not select deleted pollers
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/RealTimeMonitoringServerRepositoryRDB.php
Labels: area/backend

#2195 fix(notification): bugfix for corner cases in API for Notifiable Resources
  centreon/src/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactory.php
  centreon/src/Core/Notification/Infrastructure/Repository/MetaServiceRequestProvider.php
Labels: area/backend

#2204 enh(UI): Integrate widgets from different repos (MAP)
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Main/usePlatformVersions.ts
Labels: area/ui

#2203 Fix(Query): in getHostServicesName method
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2206 fix(tests): rename feature flag in API test
  centreon/tests/api/features/ResourcesByParentMonitoring.feature
Labels: area/backend

#2140 fix(Poller configuration): Runtime error during remote server creation
  centreon/packages/ui/src/utils/centreonBaseURL.ts
  centreon/packages/ui/src/utils/index.ts
  centreon/src/CentreonRemote/Domain/Value/ServerWizardIdentity.php
  centreon/www/front_src/src/PollerWizard/pollerStep2/index.tsx
  centreon/www/front_src/src/PollerWizard/remoteServerStep2/index.tsx
  centreon/www/front_src/src/PollerWizard/remoteServerStep3/index.tsx
Labels: area/ui

#2213 fix(duplication): correctly update ACL for duplicated host/services
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2239 enh(UI): Improve dashboard in order to integrate external widgets
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
Labels: area/ui

#2184 enh(UI): Add optional label to the navigation menu and breadcrumb
  centreon/cypress/fixtures/menuDataWithAdditionalLabel.json
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/tests/api/features/ConfigurationUsersWithOpenApi.feature
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/dashboard-check-permissions.json
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/dashboard-configuration-creator.json
  centreon/tests/e2e/cypress/fixtures/resources/clapi/config-ACL/dashboard-share.json
  centreon/www/front_src/src/BreadcrumbTrail/Breadcrumb.tsx
  centreon/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx
  centreon/www/front_src/src/BreadcrumbTrail/getBreadcrumbsByPath/index.test.tsx
  centreon/www/front_src/src/BreadcrumbTrail/getBreadcrumbsByPath/index.ts
  centreon/www/front_src/src/BreadcrumbTrail/models.ts
  centreon/www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  centreon/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx
  centreon/www/install/insertTopology.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/ui

#2249 enh(config): disable engine notifications in cloud/notification context
  centreon/www/class/config-generate/engine.class.php
Labels: area/backend

#2205 enh(api) handle resources ACLs in DeleteHost and DeleteService
  centreon/doc/API/v23.10/Configuration/Host/Schema/AddHostResponse.yaml
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/tests/api/features/Host.feature
  centreon/tests/api/features/ServiceOnPrem.feature
  centreon/tests/api/features/Token.feature
Labels: area/backend

#2256 Fix(UI): Fix single bar + gauge glitch
  centreon/packages/ui/src/Graph/Gauge/ResponsiveGauge.tsx
  centreon/packages/ui/src/Graph/SingleBar/ResponsiveSingleBar.tsx
Labels: area/ui

#2232 fix(duplication): correctly update ACL for duplicated host/services (…
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#2212 enh(dashboard): change API graph to query by metric_name
  centreon/doc/API/v23.10/Configuration/Dashboard/Dashboard.MetricsPerformances.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Dashboard.MetricsPerformancesData.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/QueryParameter/MetricNames.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsPerformances.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsData.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataRequest.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataController.php
  centreon/src/Core/Metric/Application/Repository/ReadMetricRepositoryInterface.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataTest.php
Labels: area/backend

#2216 fix(export): SQL request fixed on graph data CSV export (#2185)
  centreon/src/Core/Infrastructure/RealTime/Repository/DataBin/DbReadPerformanceDataRepository.php
Labels: area/backend

#2217 enh(ui): change wording from "Massive Change" to "Mass Change"
  centreon/features/MassiveChangeHosts.feature
  centreon/features/MassiveChangeServices.feature
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/features/bootstrap/MassiveChangeServicesContext.php
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/class/centreonLogAction.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
  centreon/www/include/Administration/configChangelog/viewLogsDetails.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/listContact.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
  centreon/www/include/configuration/configObject/contact_template_model/listContactTemplateModel.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/service/listServiceByHost.php
  centreon/www/include/configuration/configObject/service/listServiceByHostGroup.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
Labels: area/backend
