Repository centreon/centreon, pull requests merged in 2023-07, with the labels that each got.

#1697 fix(upgrade): add missing upgrade for new about page topology
  centreon/www/install/php/Update-23.04.5.php
  centreon/www/install/sql/centreon/Update-DB-23.04.5.sql
Labels: area/backend

#1807 enh(notification): handle contactgroup for POST endpoint
  centreon/doc/API/v23.10/Configuration/Notification/Schema/Notification.Add.yaml
  centreon/src/Core/Contact/Application/Repository/ReadContactGroupRepositoryInterface.php
  centreon/src/Core/Contact/Infrastructure/Repository/DbReadContactGroupRepository.php
  centreon/src/Core/Notification/Application/Repository/ReadNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotification.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationRequest.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationResponse.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NewNotificationFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NotificationMessageFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NotificationResourceFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Validator/NotificationUserValidator.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Validator/NotificationValidator.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationSchema.json
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/AddNotification/AddNotificationTest.php
  centreon/www/install/createTables.sql
Labels: area/backend

#1815 enh(notifications): handle contactgroup in user count for listing
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
  centreon/tests/api/features/Notification.feature
  centreon/www/install/php/Update-22.10.11.php
  centreon/www/install/php/Update-23.04.6.php
Labels: area/backend

#1764 fix(packages/connectedAutoComplete): fix search in select boxes
  centreon/packages/ui/cypress/fixtures/inputField/listOptions.json
  centreon/packages/ui/cypress/fixtures/inputField/searchedOption.json
  centreon/packages/ui/cypress/support/commands.tsx
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/Multi connected autocomplete -- displays all options on the list when the user searches for and selects an option.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/Multi connected autocomplete -- displays exactly one option on the list when the user types that option.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/displays the list when the user clicks on the input.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/hide the list when the user clicks on the input.snap.png
  centreon/packages/ui/public/mockServiceWorker.js
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/utils/index.ts
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx
Labels: area/ui

#1825 fix(clapi) add missing broker parameters support (command_file, log_directory, log_filename)
  centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Labels: area/backend

#1784 feat(APIv2): add 2 dashboard endpoints for searching contact + contactgroups
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/ContactGroups.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Contacts.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/Response/ContactGroupsResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/Response/ContactsResponseDto.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsRoute.yaml
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsTest.php
Labels: area/backend

#1814 fix(editPanel/cypress/test)ensure that elements are visible
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Host Groups field is empty, all event checkboxes are unchecked and the Include Services field is not visible.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Service Groups field is empty, all associated events are disabled and unchecked.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/index.tsx
Labels: area/ui

#1839 enh(clapi) ignore empty and commented lines in file import
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1771 feat(dashboard): Implement-E2E-tests-from-delete-an-existing-dashboard
  centreon/tests/e2e/cypress/e2e/Dashboards/01-dashboard-creation/index.ts
  centreon/tests/e2e/cypress/e2e/Dashboards/02-dashboard-navigation/index.ts
  centreon/tests/e2e/cypress/e2e/Dashboards/04-dashboard-deletion.feature
  centreon/tests/e2e/cypress/e2e/Dashboards/04-dashboard-deletion/index.ts
  centreon/tests/e2e/cypress/fixtures/dashboards/navigation/01-onepage.json
  centreon/tests/e2e/cypress/fixtures/dashboards/navigation/dashboards-more-than-a-single-page.json
  centreon/tests/e2e/cypress/fixtures/dashboards/navigation/dashboards-single-page.json
Labels: area/ui

#1842 fix(SAML): remove is_active and is_forced from custom_configuration
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
Labels: area/backend

#1858 fix(popup): add missing id for gorgone central popup configuration
  centreon/www/include/configuration/configServers/popup/central.yaml
Labels: area/backend

#1829 fix(clapi) add missing broker parameters support (command_file, log_directory, log_filename) (#1825)
  centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Labels: area/backend

#1857 feat(notifications) : add contact groups field to the notification panel
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Close button triggers the display of a confirmation dialog if the user has made some changes to the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Save button is correctly activated when all required fields are filled, and the form is error-free, allowing the user to save the form data.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Save button triggers the display of a confirmation dialog, providing the user with an additional confirmation step before proceeding with the action.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- displays the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- tests that the form is sent when the confirm button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Confirm button triggers the sending of a PUT request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Save button triggers the display of a confirmation dialog, providing the user with an additional confirmation step before proceeding with the action.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the ExpandCollapse button triggers the desired expansion or collapse of the panel, providing users with the ability to control its visibility and size.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Include Services checkbox controls the enabling and checking status of all host group services checkboxes.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Save button responds to field changes correctly, becoming enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Subject field is properly rendered with the edited notification subject.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the notification name is properly rendered with the edited value and supports the capability for users to modify the name by interacting with the Edit icon.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the three icons for notification channels are appropriately presented, with the email icon initially selected and the other icons disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays host group resources and events with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays service groups and events fields with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Contact Groups field with edited notification contact groups.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Contacts field with edited notification contacts.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Users field with edited notification users.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Include Services field presents the value of the edited notification.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Save button's initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the header section displays all the expected actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the time period checkbox is checked and disabled, indicating its pre-selected status.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Host Groups field is empty, all event checkboxes are unchecked and the Include Services field is not visible.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Service Groups field is empty, all associated events are disabled and unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when both resource fields are empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Contacts and Contact Groups fields are both empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Message field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Subject field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Users field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays an error message upon failed deletion.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/api/adapters.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/api/decoders.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/api/endpoints.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/initialValues.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/models.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/testUtils.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/useFormInitialValues.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/utils.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/validationSchema.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/translatedLabels.ts
Labels: area/ui

#1826 fix(EditPanel/FormInputs): [Cloud notification] Fix font size in creation/edition form
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Close button triggers the display of a confirmation dialog if the user has made some changes to the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Save button is correctly activated when all required fields are filled, and the form is error-free, allowing the user to save the form data.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- confirms that the Save button triggers the display of a confirmation dialog, providing the user with an additional confirmation step before proceeding with the action.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- displays the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx/Panel Creation mode -- tests that the form is sent when the confirm button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Confirm button triggers the sending of a PUT request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Save button triggers the display of a confirmation dialog, providing the user with an additional confirmation step before proceeding with the action.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the ExpandCollapse button triggers the desired expansion or collapse of the panel, providing users with the ability to control its visibility and size.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Include Services checkbox controls the enabling and checking status of all host group services checkboxes.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Message field is properly rendered with the edited notification message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Save button responds to field changes correctly, becoming enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Subject field is properly rendered with the edited notification subject.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the notification name is properly rendered with the edited value and supports the capability for users to modify the name by interacting with the Edit icon.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the three icons for notification channels are appropriately presented, with the email icon initially selected and the other icons disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays host group resources and events with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays service groups and events fields with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Contact Groups field with edited notification contact groups.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Contacts field with edited notification contacts.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Include Services field presents the value of the edited notification.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Save button's initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the header section displays all the expected actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the time period checkbox is checked and disabled, indicating its pre-selected status.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Host Groups field is empty, all event checkboxes are unchecked and the Include Services field is not visible.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Service Groups field is empty, all associated events are disabled and unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when both resource fields are empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Contacts and Contact Groups fields are both empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Message field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Subject field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays an error message upon failed deletion.snap.png
  centreon/packages/ui/src/Form/CollapsibleGroup.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/ThemeProvider/index.tsx
  centreon/www/class/centreon-clapi/centreonAPI.class.php
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/Form.styles.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/FormInputs/Inputs.styles.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx
Labels: area/ui

#1871 enh(templates): remove possibility to enable/disable the object
  centreon/composer.lock
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/features/bootstrap/HostTemplateBasicsOperationsContext.php
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/features/bootstrap/ServiceTemplateConfigurationContext.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.ihtml
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/formService.ihtml
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php
  centreon/www/install/php/Update-23.10.0.php
Labels: area/backend

#1840 enh(packages/wizard): [UX]Remove "Exit wizard" popin after having added token or view license
  centreon/packages/ui/src/Wizard/index.tsx
  centreon/packages/ui/src/Wizard/models.ts
Labels: area/ui

#1878 enh(Listing): Add support for "expand/collapse" rows in the Listing component
  centreon/.veracode-exclusions
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx/Notifications Listing -- displays the first page of the notifications listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a get notifications request after updating limit param.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/package.json
  centreon/packages/js-config/cypress/component/enableVisualTesting.ts
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- collapses the row when the corresponding icon si clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- expands the row when the corresponding icon si clicked.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Listing/Cell/DataCell.tsx
  centreon/packages/ui/src/Listing/Cell/index.tsx
  centreon/packages/ui/src/Listing/Listing.cypress.spec.tsx
  centreon/packages/ui/src/Listing/Listing.styles.ts
  centreon/packages/ui/src/Listing/ListingDocs.mdx
  centreon/packages/ui/src/Listing/Row/Row.tsx
  centreon/packages/ui/src/Listing/index.stories.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/Listing/models.ts
  centreon/packages/ui/src/Listing/tableAtoms.ts
  centreon/packages/ui/src/Panel/index.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx
Labels: area/ui

#1895 fix(api) FindHostGroup, FindHostGroups, FindServiceGroups with non-admin user
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
Labels: area/backend

#1908 fix(php-cs-fixer): wrong syntax fixed
  centreon/src/Core/Application/RealTime/UseCase/FindMetaService/FindMetaServiceResponse.php
  centreon/src/Core/Application/RealTime/UseCase/FindService/FindService.php
  centreon/src/Core/Domain/Configuration/User/Model/User.php
  centreon/src/Core/Domain/RealTime/Model/MetaService.php
  centreon/src/Core/Notification/Domain/Model/ConfigurationResource.php
  centreon/src/Core/Notification/Domain/Model/ConfigurationTimePeriod.php
  centreon/src/Core/Notification/Domain/Model/ConfigurationUser.php
  centreon/src/Core/Notification/Domain/Model/NotificationMessage.php
  centreon/src/Core/Notification/Infrastructure/API/DeleteNotifications/DeleteNotificationsPresenter.php
  centreon/src/Core/Security/AccessGroup/Domain/Model/AccessGroup.php
  centreon/src/Core/Timezone/Domain/Model/Timezone.php
Labels: area/backend

#1621 fix(administration) - fix pagination of perfdata page
  centreon/www/include/Administration/performance/viewData.php
Labels: area/backend

#1913 fix(administration) - fix pagination of perfdata page (dev-22.10.x)
  centreon/www/include/Administration/performance/viewData.php
Labels: area/backend

#1918 enh(packaging): add perl dependency and ship perl script
  centreon-gorgone/packaging/centreon-gorgone.spectemplate
Labels: area/backend

#1882 fix(gorgone): mbi module is stuck after internal key rotate
  centreon-gorgone/gorgone/modules/centreon/mbi/etlworkers/hooks.pm
  centreon-gorgone/gorgone/modules/plugins/newtest/hooks.pm
  centreon-gorgone/gorgone/modules/plugins/scom/hooks.pm
Labels: bug

#1881 fix(gorgone): external communication crash after 24h
  centreon-gorgone/gorgone/class/core.pm
Labels: bug

#1928 fix: add hasEditPermission on dashboard detail
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardUserPermissions/useDashboardUserPermissions.ts
Labels: area/ui

#1886 enh (api/service template): Handle all properties on the PATCH API endpoint
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/NewServiceTemplate.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/Macro/Domain/Model/MacroDifference.php
  centreon/src/Core/ServiceTemplate/Application/Repository/WriteServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Domain/Model/NewServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Domain/Model/ServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateSaasSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateRepository.php
  centreon/tests/api/features/ServiceTemplatesCloud.feature
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidationTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#1929 fix(auth): update user ACL with roles provided by the provider
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Local.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
Labels: area/backend

#1930 feat(bin): add script to remove duplicates host service relations
  centreon/bin/centreon-remove-duplicate-host-service-relations.php
  centreon/packaging/centreon.spectemplate
Labels: area/backend

#1934 fix(clapi/stpl): fix addhosttemplate which removes objects
  centreon/lib/Centreon/Object/Relation/Service/Template/Host.php
  centreon/tests/api/Context/ClapiContext.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/Clapi.feature
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/backend

#1903 feat(api) new endpoint DeleteService
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Service/DeleteService.yaml
  centreon/doc/API/v23.10/Configuration/Service/QueryParameter/ServiceId.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Service/Application/Exception/ServiceException.php
  centreon/src/Core/Service/Application/Repository/ReadServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/Repository/WriteServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/DeleteService/DeleteService.php
  centreon/src/Core/Service/Infrastructure/API/DeleteService/DeleteServiceController.php
  centreon/src/Core/Service/Infrastructure/API/DeleteService/DeleteServiceRoute.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceRepository.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ServiceCloud.feature
  centreon/tests/api/features/ServiceOnPrem.feature
  centreon/tests/php/Core/Service/Application/UseCase/DeleteService/DeleteServiceTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/DeleteServiceTemplate/DeleteServiceTemplatePresenterStub.php
Labels: area/backend

#1944 fix(auth): update user contactgroups with groups provided by IDP
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Local.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
Labels: area/backend

#1946 enh(arch): move metrics related code into more suitable folders
  centreon/config/packages/Centreon.yaml
  centreon/config/routes/Centreon/monitoring/metric.yaml
  centreon/src/Core/Application/RealTime/Repository/ReadPerformanceDataRepositoryInterface.php
  centreon/src/Core/Infrastructure/RealTime/Repository/DataBin/DbReadPerformanceDataRepository.php
  centreon/src/Core/Metric/Application/Repository/ReadMetricRepositoryInterface.php
  centreon/src/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricPresenterInterface.php
  centreon/src/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricRequest.php
  centreon/src/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricResponse.php
  centreon/src/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetrics.php
  centreon/src/Core/Metric/Domain/Model/Metric.php
  centreon/src/Core/Metric/Domain/Model/MetricValue.php
  centreon/src/Core/Metric/Domain/Model/PerformanceMetric.php
  centreon/src/Core/Metric/Infrastructure/API/DownloadPerformanceMetrics/DownloadPerformanceMetricsController.php
  centreon/src/Core/Metric/Infrastructure/API/DownloadPerformanceMetrics/DownloadPerformanceMetricsPresenter.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/tests/php/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricResponseTest.php
  centreon/tests/php/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricsTest.php
Labels: area/backend

#1935 fix(graph): [Resources status] The export graph icon is not visible
  centreon/www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/index.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
Labels: area/ui

#1938 fix(auth): update user ACL with roles provided by the provider (#1929)
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Local.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
Labels: area/backend

#1948 fix(auth): update user contactgroups with groups provided by IDP
  centreon/src/Core/Security/Authentication/Application/Provider/ProviderAuthenticationInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Local.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
Labels: area/backend

#1942 feat(bin): add script to remove duplicates host service relations [22.10]
  centreon/bin/centreon-remove-duplicate-host-service-relations.php
  centreon/packaging/centreon.spectemplate
Labels: area/backend

#1941 feat(bin): add script to remove duplicates host service relations [23.04]
  centreon/bin/centreon-remove-duplicate-host-service-relations.php
  centreon/packaging/centreon.spectemplate
Labels: area/backend

#1964 fix(clapi/stpl): fix addhosttemplate which removes object [22.10]
  centreon/lib/Centreon/Object/Relation/Service/Template/Host.php
  centreon/tests/api/Context/ClapiContext.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/Clapi.feature
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/backend
