Repository centreon/centreon, pull requests merged in 2023-06, with the labels that each got.

#1553 enh(openid): Handle url parameters in authorization endpoint
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenterTest.php
Labels: area/backend

#1568 fix(openid): Fixed headers not being set when custom endpoint is called
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Repository/HttpReadAttributePathRepository.php
Labels: area/backend

#1521 feat(UI): Cancel Dashboard changes
  centreon/cypress.config.ts
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/fixtures/Dashboards/Dashboard/updatedLayout.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- cancels the dashboard changes when the Cancel button is clicked in the confirmation modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- closes the cancel confirmation modal when the modal backdrop is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- displays the cancel confirmation modal when the user tries to navigate away from the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- does not display the cancel confirmation modal when the Exit button is clicked and the dashboard is not updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- does not display the cancel confirmation modal when the user tries to navigate away from the dashboard and the dashboard is not updated.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/js-config/cypress/component/configuration.js
  centreon/packages/js-config/webpack/base/globalConfig.js
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Dashboard/Grid.tsx
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/packages/ui/src/components/Button/Button.tsx
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/packages/ui/src/components/Header/Header.tsx
  centreon/packages/ui/src/components/Modal/ModalActions.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/.gitignore
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/HeaderActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Toolbar/AddWidgetDialog.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Toolbar/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/api/decoders.ts
  centreon/www/front_src/src/Dashboards/Dashboard/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDirty.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardSaveBlocker.ts
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/FallbackPages/AuthenticationDenied/index.tsx
  centreon/www/front_src/src/Main/Provider.tsx
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/index.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
  centreon/www/front_src/src/Resources/Actions/index.test.tsx
  centreon/www/front_src/src/bootstrap.tsx
  centreon/www/front_src/src/components/ReactRouter/index.tsx
Labels: area/ui

#1550 feat(UI): Save dashboard changes
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- saves the dashboard when the corresponding button is clicked and the dashboard is changed.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Button/Save/index.stories.tsx
  centreon/packages/ui/src/components/Button/Button.tsx
  centreon/packages/ui/src/components/Form/Dashboard/Dashboard.resource.ts
  centreon/packages/ui/src/components/Form/Dashboard/DashboardForm.tsx
  centreon/packages/ui/src/components/Form/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Authentication/WebSSO/index.test.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/HeaderActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/Dashboards.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/components/FederatedComponents/index.tsx
Labels: area/ui

#1537 fix(resource status): Display the last acknowledgement into the details panel (#1533)
  centreon/src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbReadAcknowledgementRepository.php
Labels: area/backend

#1579 fix(database): reduce verbosity of error messages on legacy pages
  centreon/www/class/centreonDB.class.php
Labels: area/backend

#1569 (ui/legacy): fix spacing between buttons
  centreon/www/include/configuration/configNagios/listNagios.ihtml
  centreon/www/include/monitoring/downtime/template/listDowntime.ihtml
  centreon/www/include/options/accessLists/resourcesACL/listsResourcesAccess.ihtml
Labels: area/ui

#1571 fix(openid): Fixed headers not being set when custom endpoint is called - develop
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Repository/HttpReadAttributePathRepository.php
Labels: area/backend

#1582 feat(UI): Show actions based on user roles
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/fixtures/Dashboards/dashboards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays the dashboard actions on the corresponding dashboard when the user has editor roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays the dashboard actions on the corresponding dashboard when the user has viewer roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays the dashboards actions on all dashboards when the user has administrator global roles.snap.png
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/components/DataTable/EmptyState/DataTableEmptyState.tsx
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/api/decoders.ts
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardSaveBlocker.ts
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Listing.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/models.ts
  centreon/www/front_src/src/Dashboards/useUserDashboardPermissions.ts
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui

#1585 fix(clapi): exclude ldap user from password expiration
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1584 fix(gorgone): proxy module is stuck after internal key rotate (MON-19742)
  centreon-gorgone/gorgone/class/core.pm
  centreon-gorgone/gorgone/modules/core/proxy/hooks.pm
  centreon-gorgone/gorgone/modules/plugins/newtest/hooks.pm
  centreon-gorgone/gorgone/modules/plugins/scom/hooks.pm
Labels: bug, area/backend

#1516 feat(ui): dashboard pages layout component
  centreon/packages/ui/src/Dashboard/DashboardLayout.stories.tsx
  centreon/packages/ui/src/Dashboard/Layout.tsx
  centreon/packages/ui/src/Dashboard/utils.ts
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/packages/ui/src/components/Header/Header.styles.ts
  centreon/packages/ui/src/components/Layout/AreaIndicator.styles.ts
  centreon/packages/ui/src/components/Layout/AreaIndicator.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.stories.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayoutActions.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayoutBody.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayoutHeader.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/index.ts
  centreon/packages/ui/src/components/Layout/index.ts
  centreon/packages/ui/src/components/index.ts
  centreon/packages/ui/src/index.ts
  centreon/packages/ui/src/layout/TiledListingPage/TiledListingActions.tsx
  centreon/packages/ui/src/layout/TiledListingPage/TiledListingContent.tsx
  centreon/packages/ui/src/layout/TiledListingPage/TiledListingList.tsx
  centreon/packages/ui/src/layout/TiledListingPage/TiledListingPage.styles.ts
  centreon/packages/ui/src/layout/TiledListingPage/TiledListingPage.tsx
  centreon/packages/ui/src/layout/TiledListingPage/index.ts
  centreon/packages/ui/src/screens/dashboard/DashboardsOverview.stories.tsx
  centreon/www/front_src/src/Dashboards/Dashboards.tsx
  centreon/www/front_src/src/Dashboards/Listing.tsx
  centreon/www/front_src/src/Dashboards/ListingSkeleton.tsx
Labels: area/ui

#1574 Change the type of check_attempt and max_check_attempts columns from table resources
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-23.10.0.php
Labels: area/backend

#1581 fix(modules): block install if module already installed (#1567)
  centreon/src/CentreonModule/Infrastructure/Source/ModuleSource.php
Labels: area/backend

#1538 fix(backup) fix Debian issues and improve the script (#1373)
  centreon/cron/centreon-backup-mysql.sh
  centreon/cron/centreon-backup.pl
Labels: area/backend

#1536 fix(resource status): Display the last acknowledgement into the details panel (#1533)
  centreon/src/Core/Infrastructure/RealTime/Repository/Acknowledgement/DbReadAcknowledgementRepository.php
Labels: area/backend

#1607 enh(SAML): log user information (#1604)
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
Labels: area/backend

#1583 (ui/legacy): fix spacing between buttons
  centreon/www/include/configuration/configNagios/listNagios.ihtml
  centreon/www/include/monitoring/downtime/template/listDowntime.ihtml
  centreon/www/include/options/accessLists/resourcesACL/listsResourcesAccess.ihtml
Labels: area/ui

#1619 feat(api): PartialUpdateHostTemplate endpoint: handle macros (#1551)
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/AddAndFindHostTemplates.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/HostTemplate.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/QueryParameter/HostTemplateId.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PostHostTemplateRequest.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/CommandMacro/Application/Repository/ReadCommandMacroRepositoryInterface.php
  centreon/src/Core/CommandMacro/Domain/Model/CommandMacro.php
  centreon/src/Core/CommandMacro/Domain/Model/CommandMacroType.php
  centreon/src/Core/CommandMacro/Infrastructure/Repository/DbReadCommandMacroRepository.php
  centreon/src/Core/Common/Application/Type/NoValue.php
  centreon/src/Core/Host/Domain/Model/HostInheritance.php
  centreon/src/Core/HostMacro/Application/Repository/ReadHostMacroRepositoryInterface.php
  centreon/src/Core/HostMacro/Application/Repository/WriteHostMacroRepositoryInterface.php
  centreon/src/Core/HostMacro/Domain/Model/HostMacro.php
  centreon/src/Core/HostMacro/Domain/Model/HostMacroDifference.php
  centreon/src/Core/HostMacro/Infrastructure/Repository/DbReadHostMacroRepository.php
  centreon/src/Core/HostMacro/Infrastructure/Repository/DbWriteHostMacroRepository.php
  centreon/src/Core/HostTemplate/Application/Exception/HostTemplateException.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateRoute.yaml
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/HostTemplate.feature
  centreon/tests/php/Core/CommandMacro/Domain/Model/CommandMacroTest.php
  centreon/tests/php/Core/Common/Application/Type/NoValueTest.php
  centreon/tests/php/Core/HostMacro/Domain/Model/HostMacroDifferenceTest.php
  centreon/tests/php/Core/HostMacro/Domain/Model/HostMacroTest.php
  centreon/tests/php/Core/HostTemplate/Application/PatchHostTemplate/PatchHostTemplateTest.php
Labels: area/backend

#1618 enh (service): Create new API endpoint to link host templates to the service template
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/DeleteServiceTemplate.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/PartialUpdateAndDeleteServiceTemplate.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Centreon/Application/Controller/AbstractController.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Application/Exception/ServiceTemplateException.php
  centreon/src/Core/ServiceTemplate/Application/Repository/WriteServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRoute.yaml
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateSaasSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateRepository.php
  centreon/tests/api/features/ServiceTemplatesCloud.feature
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#1610 enh(api/conf) handle templates in AddHostTemplate endpoint
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/AddHostTemplateResponse.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PostHostTemplateRequest.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostTemplate/Application/Exception/HostTemplateException.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/Repository/WriteHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateFactory.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateResponse.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateOnPremPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateOnPremSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateSaasPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateSaasSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateRepository.php
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/HostTemplate.feature
Labels: area/backend

#1617 (ui/legacy): fix size of images
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.ihtml
  centreon/www/include/configuration/configObject/service/formService.ihtml
Labels: area/ui

#1628 fix(APIv2): JSON validation failed with empty objects or arrays
  centreon/src/Centreon/Application/Controller/AbstractController.php
  centreon/tests/php/Centreon/Application/Controller/AbstractControllerTest.php
Labels: area/backend

#1596 feat(api/conf): dashboard new field own role
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.Listing.yaml
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardRelationRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/Repository/WriteDashboardRelationRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardFactory.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/DeleteDashboard/DeleteDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardFactory.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboards.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsFactory.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/Response/DashboardResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/PartialUpdateDashboard/PartialUpdateDashboard.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardContactGroupShare.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardContactShare.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardRights.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardSharingRole.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardSharingRoles.php
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRelationRepository.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbWriteDashboardRelationRepository.php
  centreon/tests/api/features/Dashboard.OpenApiDoc.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/DeleteDashboard/DeleteDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/PartialUpdateDashboard/PartialUpdateDashboardTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/DashboardContactGroupShareTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/DashboardContactShareTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/DashboardRightsTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/DashboardSharingRolesTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertTopology.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0-beta.1.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.1.sql
Labels: area/backend

#1632 enh(api/conf): PartialUpdateHostTemplate handle categories
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/DeleteAndPartialUpdateHostTemplate.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/src/Core/HostCategory/Application/Repository/WriteHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryRepository.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateRepository.php
  centreon/src/Utility/Difference/BasicDifference.php
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/HostTemplate.feature
  centreon/tests/php/Core/HostTemplate/Application/PartialUpdateHostTemplate/PartialUpdateHostTemplateTest.php
Labels: area/backend

#1634 feat(notification): DELETE one notification endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Notification.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Notifications.yaml
  centreon/doc/API/v23.10/Configuration/Notification/QueryParameter/NotificationId.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Notification/Application/Exception/NotificationException.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/DeleteNotification/DeleteNotification.php
  centreon/src/Core/Notification/Application/UseCase/DeleteNotification/DeleteNotificationPresenterInterface.php
  centreon/src/Core/Notification/Infrastructure/API/DeleteNotification/DeleteNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/DeleteNotification/DeleteNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/DeleteNotification/DeleteNotificationRoute.yaml
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/DeleteNotification/DeleteNotificationPresenterStub.php
  centreon/tests/php/Core/Notification/Application/UseCase/DeleteNotification/DeleteNotificationTest.php
Labels: area/backend

#1626 feat(header/Poller): integrate cloud extension to centreon
  centreon/webpack.config.dev.js
  centreon/www/front_src/src/Header/Poller/PollerSubMenu/PollerSubMenu.tsx
  centreon/www/front_src/src/Header/specs/Header.Poller.ts
Labels: area/ui

#1512 [style]: Add css in global style files to fix Mbi widget visibility (dev-23.04.x)
  centreon/www/Themes/Centreon-Dark/variables.css
  centreon/www/Themes/Generic-theme/Variables-css/variables.css
  centreon/www/Themes/Generic-theme/style.css
Labels: area/backend

#1636 Fix: override index.html base with the correct custom uri
  centreon/www/index.php
Labels: area/backend

#1635 enh (api/conf): Updated the API for creating service template with the link to host templates
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/NewServiceTemplate.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateResponse.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/NewServiceTemplateFactory.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/ServiceTemplateDto.php
  centreon/src/Core/ServiceTemplate/Domain/Model/NewServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Domain/Model/ServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateSaasSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/FindServiceTemplates/FindServiceTemplatesOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/FindServiceTemplates/FindServiceTemplatesSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateRepository.php
  centreon/tests/api/features/ServiceTemplatesCloud.feature
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
Labels: area/backend

#1601 enh(UX) : extend Snackbar Message functionality to support HTML Strings
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Snackbar/index.tsx
  centreon/packages/ui/src/Snackbar/useSnackbar.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/sanitizedHTML.ts
  centreon/pnpm-lock.yaml
Labels: area/ui

#1645 fix(CI): Fix notifications listing tests
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Confirm button triggers the sending of a PUT request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- Confirms that the Save button triggers the display of a confirmation dialog, providing the user with an additional confirmation step before proceeding with the action.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the ExpandCollapse button triggers the desired expansion or collapse of the panel, providing users with the ability to control its visibility and size.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Include Services checkbox controls the enabling and checking status of all host group services checkboxes.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Message field is properly rendered with the edited notification message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Save button responds to field changes correctly, becoming enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the Subject field is properly rendered with the edited notification subject.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the notification name is properly rendered with the edited value and supports the capability for users to modify the name by interacting with the Edit icon.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Confirms that the three icons for notification channels are appropriately presented, with the email icon initially selected and the other icons disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays host group resources and events with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays service groups and events fields with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Displays the Users field with edited notification users.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Include Services field presents the value of the edited notification.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the Save button's initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the header section displays all the expected actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that the time period checkbox is checked and disabled, indicating its pre-selected status.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Host Groups field is empty, all event checkboxes are unchecked and the Include Services field is not visible.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Ensures that when the Service Groups field is empty, all associated events are disabled and unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when both resource fields are empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Message field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Subject field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx/Edit Panel -- Validates that when the Users field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelCreate.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/NotificationsListing.cypress.spec.tsx
Labels: area/ui

#1661 Fix: override index.html base with the correct custom uri
  centreon/www/index.php
Labels: area/backend

#1663 Fix: override index.html base with the correct custom uri
  centreon/www/index.php
Labels: area/backend

#1664 Fix: override index.html base with the correct custom uri
  centreon/www/index.php
Labels: area/backend

#1638 feat(notification): GET Notification details endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Notification.yaml
  centreon/doc/API/v23.10/Configuration/Notification/QueryParameter/NotificationId.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Schema/Notification.Details.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Notification/Application/Exception/NotificationException.php
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotification.php
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotificationPresenterInterface.php
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotificationResponse.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotification/FindNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotification/FindNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotification/FindNotificationRoute.yaml
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotification/FindNotificationTest.php
  centreon/tests/php/Core/Notification/Infrastructure/API/FindNotification/FindNotificationPresenterStub.php
Labels: area/backend

#1655 enh(extensions): add more information regarding licenses in extension…
  centreon/src/CentreonModule/Infrastructure/Source/ModuleSource.php
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend

#1670 Fix: Error messages for APIv1 endpoints not being displayed
  centreon/packages/ui/src/api/useRequest/index.ts
Labels: area/ui

#1640 enh(api) refactor host macros in PartialUpdateHostTemplate
  centreon/src/Core/Host/Domain/Model/HostInheritance.php
  centreon/src/Core/HostMacro/Domain/Model/HostMacro.php
  centreon/src/Core/HostMacro/Domain/Model/HostMacroDifference.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/HostMacroFactory.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Domain/Model/MacroManager.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/tests/php/Core/Host/Domain/Model/HostInheritanceTest.php
  centreon/tests/php/Core/HostMacro/Domain/Model/HostMacroDifferenceTest.php
  centreon/tests/php/Core/HostTemplate/Domain/Model/MacroManagerTest.php
Labels: area/backend

#1646 feat(APIv2): add dashboard permissions in the current parameters api endpoint
  centreon/composer.lock
  centreon/config/packages/Centreon.yaml
  centreon/config/routes/Centreon/user.yaml
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Users/CurrentParameters.yaml
  centreon/doc/API/v23.10/Configuration/Users/Schema/CurrentParameters.Get.yaml
  centreon/doc/API/v23.10/Configuration/Users/Schema/CurrentParameters.Patch.yaml
  centreon/doc/API/v23.10/Configuration/Users/Schema/User.Listing.yaml
  centreon/doc/API/v23.10/Configuration/Users/Users.yaml
  centreon/src/Centreon/Application/Controller/UserController.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardGlobalRole.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardRights.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParameters.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersPresenterInterface.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersResponse.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/Response/DashboardPermissionsResponseDto.php
  centreon/src/Core/User/Domain/Model/UserInterfaceDensity.php
  centreon/src/Core/User/Domain/Model/UserTheme.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersController.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersRoute.yaml
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ConfigurationUsers.JsonSchema.feature
  centreon/tests/api/features/ConfigurationUsers.OpenApiDoc.feature
  centreon/tests/api/features/ConfigurationUsers.feature
  centreon/tests/api/features/UserParameters.feature
  centreon/tests/php/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersPresenterStub.php
  centreon/tests/php/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersTest.php
Labels: area/backend

#1666 Fix: override index.html base with the correct custom uri
  centreon/www/index.php
Labels: area/backend

#1686 fix(upgrade): add missing column topology_url_substitute if not exists
  centreon/www/install/php/Update-23.04.4.php
Labels: area/backend

#1708 fix(upgrade): add missing column
  centreon/www/install/php/Update-23.04.4.php
Labels: area/backend

#1688 enh(api) PartialUpdateHostTemplate: handle parent templates update
  centreon/doc/API/v23.10/Configuration/HostTemplate/DeleteAndPartialUpdateHostTemplate.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/src/Core/Host/Application/InheritanceManager.php
  centreon/src/Core/HostTemplate/Application/Repository/WriteHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateRepository.php
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/HostTemplate.feature
  centreon/tests/php/Core/Host/Application/InheritanceManagerTest.php
  centreon/tests/php/Core/Host/Domain/Model/HostInheritanceTest.php
  centreon/tests/php/Core/HostTemplate/Application/PartialUpdateHostTemplate/PartialUpdateHostTemplateTest.php
Labels: area/backend

#1711 fix(gorgone): external communication crash every 24h
  centreon-gorgone/gorgone/class/core.pm
  centreon-gorgone/gorgone/modules/core/proxy/class.pm
  centreon-gorgone/gorgone/modules/core/proxy/hooks.pm
Labels: bug

#1714 Mon 20091 dev 23 04 x ux incorrect tooltip on configuration pollers engine configuration log options tab service check timeout option
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/www/include/configuration/configNagios/help.php
Labels: area/ui

#1506 fix(open-tickets): Fix SQL join on Custom Variables
  centreon-open-tickets/widgets/open-tickets/src/index.php
Labels: bug, area/backend

#1709 fix(resources): correctly handle "group" filters in Resource Status
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#1748 fix tooltip description issue (#1676)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/www/include/configuration/configNagios/help.php
Labels: area/ui

#1743 fix(resources): correctly handle "group" filters in Resource Status (…
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#1744 fix(resources): correctly handle "group" filters in Resource Status (…
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#1672 feat(ui): dashboard section navigation
  centreon/packages/ui/package.json
  centreon/packages/ui/src/api/TestQueryProvider.tsx
  centreon/packages/ui/src/api/useFetchQuery/index.ts
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/packages/ui/src/components/Button/Button.styles.ts
  centreon/packages/ui/src/components/Button/Icon/IconButton.styles.ts
  centreon/packages/ui/src/components/DataTable/DataTable.stories.tsx
  centreon/packages/ui/src/components/DataTable/DataTable.styles.ts
  centreon/packages/ui/src/components/DataTable/DataTable.tsx
  centreon/packages/ui/src/components/DataTable/EmptyState/DataTableEmptyState.tsx
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.styles.ts
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/packages/ui/src/components/Header/PageHeader/PageHeaderTitle.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
  centreon/packages/ui/src/components/Menu/MenuDivider.tsx
  centreon/packages/ui/src/components/Menu/MenuItem.tsx
  centreon/packages/ui/src/components/Modal/index.ts
  centreon/packages/ui/src/screens/dashboard/DashboardsDetail.stories.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/sanitizedHTML.ts
  centreon/tests/e2e/cypress/e2e/Dashboards/01-dashboard-creation.feature
  centreon/tests/e2e/cypress/e2e/Dashboards/01-dashboard-creation/index.ts
  centreon/tests/e2e/cypress/e2e/Dashboards/02-dashboard-navigation.feature
  centreon/tests/e2e/cypress/e2e/Dashboards/02-dashboard-navigation/index.ts
  centreon/tests/e2e/cypress/fixtures/dashboards/creation/dashboards.json
  centreon/www/front_src/src/App/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/HeaderActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/Dashboards.tsx
  centreon/www/front_src/src/Dashboards/DashboardsPage.tsx
  centreon/www/front_src/src/Dashboards/Listing.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useCreateDashboard.ts
  centreon/www/front_src/src/Dashboards/api/useDeleteDashboard.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateDashboard.ts
  centreon/www/front_src/src/Dashboards/atoms.ts
  centreon/www/front_src/src/Dashboards/components/DashboardAccessRights/DashboardAccessRightsModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardAccessRights/useDashboardAccessRights.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/DashboardConfigModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardDelete/DashboardDeleteConfirmationModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardDelete/useDashboardDelete.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/DashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/DashboardsOverviewSkeleton.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/useDashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsQuickAccess/DashboardsQuickAccessMenu.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsQuickAccess/useDashboardsQuickAccess.ts
  centreon/www/front_src/src/Dashboards/index.tsx
  centreon/www/front_src/src/Dashboards/models.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/Dashboards/useDashboards.ts
  centreon/www/front_src/src/Dashboards/useRemoveDashboard.ts
  centreon/www/front_src/src/Dashboards/useSubmitDashboard.ts
Labels: area/ui

#1741 feat(notification): Enable/Disable Endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Notification/PartialUpdateNotification.yaml
  centreon/doc/API/v23.10/Configuration/Notification/QueryParameter/NotificationId.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Schema/PartialUpdateNotificationRequest.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Notification/Application/Exception/NotificationException.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/PartialUpdateNotification/PartialUpdateNotification.php
  centreon/src/Core/Notification/Application/UseCase/PartialUpdateNotification/PartialUpdateNotificationPresenterInterface.php
  centreon/src/Core/Notification/Application/UseCase/PartialUpdateNotification/PartialUpdateNotificationRequest.php
  centreon/src/Core/Notification/Domain/Model/Notification.php
  centreon/src/Core/Notification/Infrastructure/API/PartialUpdateNotification/PartialUpdateNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/PartialUpdateNotification/PartialUpdateNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/PartialUpdateNotification/PartialUpdateNotificationRoute.yaml
  centreon/src/Core/Notification/Infrastructure/API/PartialUpdateNotification/PartialUpdateNotificationSchema.json
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/PartialUpdateNotification/PartialUpdateNotificationPresenterStub.php
  centreon/tests/php/Core/Notification/Application/UseCase/PartialUpdateNotification/PartialUpdateNotificationTest.php
Labels: area/backend

#1738 enh (api/service template): Update service categories from the PATCH API endpoint
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/ServiceCategory/Application/Repository/ReadServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbWriteServiceCategoryRepository.php
  centreon/src/Core/ServiceTemplate/Application/Repository/WriteServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/FindServiceTemplates/FindServiceTemplatesOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateRepository.php
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
  centreon/tests/php/Core/ServiceTemplate/Domain/ServiceTemplateTest.php
Labels: area/backend

#1705 enh(Header/getServicePropsAdapter): Service type "anomaly detection" or Meta-Services aren't filtered correctly from top counter links
  centreon/www/front_src/src/Header/Resources/Service/getServicePropsAdapter.ts
  centreon/www/front_src/src/Header/Resources/getResourcesUrl.ts
  centreon/www/front_src/src/Header/specs/Header.Services.tsx
Labels: area/ui

#1691 feat(notifications) : Implement frontend functionalities for the action button (enable/disable)
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Actions/RowActions/Activate.tsx
Labels: area/ui

#1755 fix[BAM]: The columns name are transparent for ack in light mode (dev-22.10.x)
  centreon/www/Themes/Centreon-Dark/variables.css
  centreon/www/Themes/Generic-theme/Variables-css/variables.css
  centreon/www/Themes/Generic-theme/style.css
Labels: area/ui

#1749 enh(Header/getServicePropsAdapter):backport Service type "anomaly detection" or Meta-Services aren't filtered correctly from top counter links
  centreon/www/front_src/src/Header/Resources/Service/getServicePropsAdapter.ts
  centreon/www/front_src/src/Header/Resources/getResourcesUrl.ts
  centreon/www/front_src/src/Header/specs/Header.Services.tsx
Labels: area/ui

#1754 fix[BAM]: The columns name are transparent for ack in light mode (dev-23.04.x)
  centreon/www/Themes/Centreon-Dark/variables.css
  centreon/www/Themes/Generic-theme/Variables-css/variables.css
  centreon/www/Themes/Generic-theme/style.css
Labels: area/ui

#1766 fix(SAML): contact groups mapping in SAML
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfiguration.php
Labels: area/backend

#1768 fix(Autocomplete): [backport] -Resources Status- Search don't work in filter
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
Labels: area/ui

#1767 fix(SAML): contact groups mapping in SAML (#1766)
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/AclUpdater.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfiguration.php
Labels: area/backend

#1769 fix(Autocomplete): Backport [dev-23.04.x] - [Resources Status] Search don't work in filter
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
Labels: area/ui

#1763 feat: is_cloud_platform flag on versions endpoint
  centreon/config/packages/Centreon.yaml
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Platform/Schema/Version.yaml
  centreon/doc/API/v23.10/Platform/Versions.yaml
  centreon/src/Centreon/Application/Controller/PlatformController.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/PlatformVersions.feature
Labels: area/backend

#1627 feat(UI): Update dashboard rights
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- AccessRights -- removes a user from the list when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Shares -- changes a user role when a new role is selected for a user and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Shares -- does not display the share button when the user has only the viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Shares -- removes a user from the list when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Shares -- removes a user from the list when when the corresponding button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/packages/ui/src/components/List/List.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/HeaderActions/HeaderActions.tsx
  centreon/www/front_src/src/Dashboards/Shares/Shares.tsx
  centreon/www/front_src/src/Dashboards/Shares/SharesList.tsx
  centreon/www/front_src/src/Dashboards/Shares/UserRoleItem.tsx
  centreon/www/front_src/src/Dashboards/Shares/models.ts
  centreon/www/front_src/src/Dashboards/Shares/translatedLabels.tsx
  centreon/www/front_src/src/Dashboards/Shares/useShareForm.ts
  centreon/www/front_src/src/Dashboards/Shares/useShareUpdate.ts
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
Labels: area/ui

#1786 fix(api) fix and check location header in add endpoints
  centreon/composer.lock
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryPresenter.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupPresenterOnPrem.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupPresenterSaas.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityPresenter.php
  centreon/src/Core/TimePeriod/Infrastructure/API/AddTimePeriod/AddTimePeriodsPresenter.php
  centreon/tests/api/features/CloudHostGroup.feature
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/HostGroup.feature
  centreon/tests/api/features/HostSeverity.feature
Labels: area/backend
