Repository centreon/centreon, pull requests merged in 2023-05, with the labels that each got.

#1289 feat(technical): create difference tooling
  centreon/src/Utility/Difference/BasicDifference.php
  centreon/src/Utility/Difference/DifferenceInterface.php
  centreon/src/Utility/Difference/TupleDifference.php
  centreon/tests/php/Utility/Difference/BasicDifferenceTest.php
  centreon/tests/php/Utility/Difference/TupleDifferenceTest.php
Labels: area/backend

#1243 feat: implement a simple feature flag system
  centreon/config/features.json
  centreon/config/packages/Centreon.yaml
  centreon/config/services.yaml
  centreon/src/Centreon/Application/DataRepresenter/Topology/NavigationList.php
  centreon/src/Centreon/Application/Webservice/TopologyWebservice.php
  centreon/src/Centreon/Domain/Entity/Topology.php
  centreon/src/Centreon/Domain/Log/LoggerTrait.php
  centreon/src/Centreon/Domain/Repository/TopologyRepository.php
  centreon/src/Core/Common/Infrastructure/FeatureFlags.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/src/EventSubscriber/FeatureFlagEventSubscriber.php
  centreon/tests/api/Context/FeatureFlagContext.php
  centreon/tests/php/Core/Common/Infrastructure/FeatureFlagsTest.php
  centreon/www/include/common/common-Func.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.1.sql
  centreon/www/main.get.php
Labels: area/backend

#1345 Centreon UI integrate cypress and add rich text editor test
  .github/actions/web-frontend-component-test/action.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/ui-beta.yml
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx/Navigation menu -- displays the direct child items and highlights the item when hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx/Navigation menu -- expands the menu when the logo is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx/Navigation menu -- highlights the menu item when double clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx/Navigation menu -- highlights the parent item when the item is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx/Navigation menu -- matches the current snapshot initial menu.snap.png
  centreon/packages/js-config/jest/index.js
  centreon/packages/ui/.gitignore
  centreon/packages/ui/cypress.config.ts
  centreon/packages/ui/cypress/support/commands.ts
  centreon/packages/ui/cypress/support/component-index.html
  centreon/packages/ui/cypress/support/component.tsx
  centreon/packages/ui/package.json
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/FloatingLinkEditorPlugin.tsx
  centreon/pnpm-lock.yaml
Labels: area/ui

#1186 refactor(conf/api): phpstan type check
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroup.php
  centreon/src/Core/HostGroup/Domain/Model/HostGroup.php
  centreon/src/Core/HostGroup/Domain/Model/NewHostGroup.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupController.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityRequest.php
  centreon/src/Core/HostSeverity/Domain/Model/HostSeverity.php
  centreon/src/Core/HostSeverity/Domain/Model/NewHostSeverity.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityController.php
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbReadHostSeverityRepository.php
  centreon/src/Core/ServiceGroup/Domain/Model/ServiceGroup.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/AddServiceSeverity/AddServiceSeverityRequest.php
  centreon/src/Core/ServiceSeverity/Domain/Model/NewServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Domain/Model/ServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/AddServiceSeverity/AddServiceSeverityController.php
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbReadServiceSeverityRepository.php
Labels: area/backend

#1408 fix(ACL): adjust reload icon display (dev-23.04.x)
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: area/backend

#1409 fix(ACL): adjust reload icon display (dev-22.10.x)
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: area/backend

#1367 fix: Listing component spacing
  centreon/packages/ui/src/Listing/Cell/index.tsx
  centreon/packages/ui/src/Listing/EmptyResult/EmptyResult.tsx
  centreon/packages/ui/src/Listing/Header/SortableCell/Content.tsx
  centreon/packages/ui/src/Listing/Header/index.tsx
  centreon/packages/ui/src/Listing/Listing.styles.ts
  centreon/packages/ui/src/Listing/Row/EmptyRow.styles.ts
  centreon/packages/ui/src/Listing/Row/EmptyRow.tsx
  centreon/packages/ui/src/Listing/Row/Row.tsx
  centreon/packages/ui/src/Listing/Row/SkeletonLoaderRows.tsx
  centreon/packages/ui/src/Listing/Skeleton.tsx
  centreon/packages/ui/src/Listing/index.stories.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-as-empty-state-1-snap.png
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-listing-loading-with-no-data-1-snap.png
Labels: area/ui

#1411 feat(ui): remove persistent option acknowledgment
  centreon/www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
Labels: area/ui

#1410 feat(core): Add Dashboard to topology and create React pages
  centreon/config/features.json
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboards.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/index.tsx
  centreon/www/front_src/src/Dashboards/models.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/components/ReactRouter/index.tsx
  centreon/www/front_src/src/reactRoutes/index.ts
  centreon/www/front_src/src/reactRoutes/routeMap.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/ui, area/backend

#1354 chore(arch): rename LegacyLogger to Logger
  centreon/config/packages/Centreon.yaml
  centreon/src/Centreon/Domain/Log/Logger.php
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/vault.class.php
Labels: area/backend

#1385 fix(tech): Update namespaces to be PSR-4 compliant
  centreon/src/Centreon/Tests/Application/DataRepresenter/Topology/NavigationListTest.php
  centreon/src/Centreon/Tests/Application/Validation/CentreonValidatorFactoryTest.php
  centreon/src/Centreon/Tests/Application/Validation/CentreonValidatorTranslatorTest.php
  centreon/src/Centreon/Tests/Infrastructure/Webservice/WebServiceAbstractTest.php
  centreon/src/CentreonLegacy/Core/Install/Step/StepInterface.php
  centreon/tests/php/Centreon/Application/Controller/AcknowledgementControllerTest.php
  centreon/tests/php/Centreon/Application/Controller/FilterControllerTest.php
  centreon/tests/php/Centreon/Application/Controller/Monitoring/MetricControllerTest.php
  centreon/tests/php/Centreon/Domain/Filter/FilterServiceTest.php
  centreon/tests/php/Centreon/Domain/MetaServiceConfiguration/UseCase/V21/FindOneMetaServiceConfigurationResponseTest.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LogoutSession/LogoutSessionTest.php
  centreon/tests/php/Utility/StringConverterTest.php
Labels: area/backend

#1366 fix(auth): correctly set auth type on login for ldap user
  centreon/src/Security/Domain/Authentication/Model/LocalProvider.php
  centreon/www/api/class/centreon_topcounter.class.php
Labels: area/backend

#1333 fix(api): correctly display errors when failure on password renew
  centreon/src/Core/Security/User/Application/UseCase/RenewPassword/RenewPassword.php
  centreon/src/Core/Security/User/Domain/Model/UserPasswordFactory.php
Labels: area/backend

#1356 enh(database): log database connection errors properly
  centreon/config/packages/Centreon.yaml
  centreon/src/Centreon/Infrastructure/DatabaseConnection.php
Labels: area/backend

#1098 feat(api/conf): add findHostCategory endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategory/FindHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategory/FindHostCategoryResponse.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategory/FindHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategory/FindHostCategoryPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategory/FindHostCategoryRoute.yaml
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/php/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindHostCategory/FindHostCategoryTest.php
Labels: area/backend

#1424 enh(database): log database connection errors properly
  centreon/config/packages/Centreon.yaml
  centreon/src/Centreon/Domain/Log/Logger.php
  centreon/src/Centreon/Infrastructure/DatabaseConnection.php
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/vault.class.php
Labels: area/backend

#1100 feat(api/conf): add FindHostGroup endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostGroup/Application/Exceptions/HostGroupException.php
  centreon/src/Core/HostGroup/Application/UseCase/FindHostGroup/FindHostGroup.php
  centreon/src/Core/HostGroup/Application/UseCase/FindHostGroup/FindHostGroupPresenterInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/FindHostGroup/FindHostGroupResponse.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupPresenterOnPrem.php
  centreon/src/Core/HostGroup/Infrastructure/API/FindHostGroup/FindHostGroupController.php
  centreon/src/Core/HostGroup/Infrastructure/API/FindHostGroup/FindHostGroupPresenterOnPrem.php
  centreon/src/Core/HostGroup/Infrastructure/API/FindHostGroup/FindHostGroupPresenterSaas.php
  centreon/src/Core/HostGroup/Infrastructure/API/FindHostGroup/FindHostGroupRoute.yaml
  centreon/tests/api/features/CloudHostGroup.feature
  centreon/tests/api/features/HostGroup.feature
  centreon/tests/php/Core/HostGroup/Application/UseCase/FindHostGroup/FindHostGroupTest.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/FindHostGroup/FindHostGroupTestPresenterStub.php
Labels: area/backend

#1427 fix(install): Fixed PHP Warning during install wizard on gorgone config file - 23.04
  centreon/www/install/steps/process/configFileSetup.php
Labels: area/backend

#1436 enh(pendo): Do not launch Pendo when browser not connected to Internet (dev-23.04.x)
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend

#1437 enh(pendo): Do not launch Pendo when browser not connected to Internet (dev-22.10.x)
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend

#1438 enh(pendo): Do not launch Pendo when browser not connected to Internet (dev-22.04.x)
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend

#1326 use select2 in opt popup
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Abstract/templates/group.ihtml
Labels: area/backend

#1160 fix(web): users should not be able to add LDAP groups to a contact (2204)
  centreon/www/api/class/centreon_configuration_contactgroup.class.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: area/backend

#1335 fix(resource): correctly handle the PENDING status filtering
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#1394 fix(export/rs): recreate the deleted map images not linked to resources (22.04)
  centreon/www/class/config-generate-remote/Host.php
Labels: area/backend

#1395 fix(export/rs): recreate the deleted map images not linked to resources (22.10)
  centreon/www/class/config-generate-remote/Host.php
Labels: area/backend

#1330 enh (topology): Creation of a mechanism to include a replacement page in the topology
  centreon/www/class/centreonACL.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.1.sql
  centreon/www/main.get.php
Labels: area/backend

#1440 feat(api/conf): add FindDashboards
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Common/Infrastructure/Repository/RepositoryTrait.php
  centreon/src/Core/Dashboard/Application/Exception/DashboardException.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboards.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsResponse.php
  centreon/src/Core/Dashboard/Domain/Model/Dashboard.php
  centreon/src/Core/Dashboard/Domain/Model/DashboardModelTrait.php
  centreon/src/Core/Dashboard/Domain/Model/NewDashboard.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
  centreon/src/Core/Infrastructure/Common/Presenter/PresenterTrait.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/DashboardTest.php
  centreon/tests/php/Core/Dashboard/Domain/Model/NewDashboardTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/backend

#1350 fux(ui): Unify Button Size and Respect Spacing Between Them
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/Administration/parameters/ldap/list.ihtml
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.ihtml
  centreon/www/include/configuration/configObject/command/listCommand.ihtml
  centreon/www/include/configuration/configObject/connector/listConnector.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact_template_model/listContactTemplateModel.ihtml
  centreon/www/include/configuration/configObject/contactgroup/listContactGroup.ihtml
  centreon/www/include/configuration/configObject/escalation/listEscalation.ihtml
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.ihtml
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.ihtml
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.ihtml
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.ihtml
  centreon/www/include/configuration/configObject/hostgroup_dependency/listHostGroupDependency.ihtml
  centreon/www/include/configuration/configObject/meta_service/listMetaService.ihtml
  centreon/www/include/configuration/configObject/metaservice_dependency/listMetaServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service/listService.ihtml
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.ihtml
  centreon/www/include/configuration/configObject/service_dependency/listServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  centreon/www/include/configuration/configObject/servicegroup/listServiceGroup.ihtml
  centreon/www/include/configuration/configObject/servicegroup_dependency/listServiceGroupDependency.ihtml
  centreon/www/include/configuration/configObject/timeperiod/listTimeperiod.ihtml
  centreon/www/include/configuration/configObject/traps-groups/listGroups.ihtml
  centreon/www/include/configuration/configObject/traps-manufacturer/listMnftr.ihtml
  centreon/www/include/configuration/configObject/traps/listTraps.ihtml
  centreon/www/include/configuration/configResources/listResources.ihtml
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/monitoring/comments/template/comments.ihtml
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.html
  centreon/www/include/monitoring/status/Hosts/templates/host.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml
  centreon/www/include/options/accessLists/groupsACL/listGroupConfig.ihtml
  centreon/www/include/options/accessLists/menusACL/listsMenusAccess.ihtml
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/reporting/dashboard/initReport.php
  centreon/www/include/views/componentTemplates/listComponentTemplates.ihtml
  centreon/www/include/views/graphTemplates/listGraphTemplates.ihtml
  centreon/www/include/views/graphs/graphs.html
  centreon/www/include/views/virtualMetrics/listVirtualMetrics.ihtml
Labels: area/backend

#1457 fix(api) check argument type before use
  centreon/www/api/class/centreon_configuration_contactgroup.class.php
Labels: area/backend

#1443 feat(api/conf): add AddDashboard + FindDashboard
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Dashboard/Application/Exception/DashboardException.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/Repository/WriteDashboardRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardRequest.php
  centreon/src/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardResponse.php
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardController.php
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardSchema.json
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbWriteDashboardRepository.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/Dashboard.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/AddDashboard/AddDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardTest.php
Labels: area/backend

#1340 fix(resource): return host when searching with h.name
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#1454 Fix(ui): Unify Button Size and Respect Spacing Between Them (dev-23.04.x)
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/Administration/parameters/ldap/list.ihtml
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.ihtml
  centreon/www/include/configuration/configObject/command/listCommand.ihtml
  centreon/www/include/configuration/configObject/connector/listConnector.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact_template_model/listContactTemplateModel.ihtml
  centreon/www/include/configuration/configObject/contactgroup/listContactGroup.ihtml
  centreon/www/include/configuration/configObject/escalation/listEscalation.ihtml
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.ihtml
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.ihtml
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.ihtml
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.ihtml
  centreon/www/include/configuration/configObject/hostgroup_dependency/listHostGroupDependency.ihtml
  centreon/www/include/configuration/configObject/meta_service/listMetaService.ihtml
  centreon/www/include/configuration/configObject/metaservice_dependency/listMetaServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service/listService.ihtml
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.ihtml
  centreon/www/include/configuration/configObject/service_dependency/listServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  centreon/www/include/configuration/configObject/servicegroup/listServiceGroup.ihtml
  centreon/www/include/configuration/configObject/servicegroup_dependency/listServiceGroupDependency.ihtml
  centreon/www/include/configuration/configObject/timeperiod/listTimeperiod.ihtml
  centreon/www/include/configuration/configObject/traps-groups/listGroups.ihtml
  centreon/www/include/configuration/configObject/traps-manufacturer/listMnftr.ihtml
  centreon/www/include/configuration/configObject/traps/listTraps.ihtml
  centreon/www/include/configuration/configResources/listResources.ihtml
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/monitoring/comments/template/comments.ihtml
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.html
  centreon/www/include/monitoring/status/Hosts/templates/host.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml
  centreon/www/include/options/accessLists/groupsACL/listGroupConfig.ihtml
  centreon/www/include/options/accessLists/menusACL/listsMenusAccess.ihtml
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/reporting/dashboard/initReport.php
  centreon/www/include/views/componentTemplates/listComponentTemplates.ihtml
  centreon/www/include/views/graphTemplates/listGraphTemplates.ihtml
  centreon/www/include/views/graphs/graphs.html
  centreon/www/include/views/virtualMetrics/listVirtualMetrics.ihtml
Labels: area/backend

#1455 Fix(ui): Unify Button Size and Respect Spacing Between Them (dev-22.10.x)
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/Administration/parameters/ldap/list.ihtml
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.ihtml
  centreon/www/include/configuration/configObject/command/listCommand.ihtml
  centreon/www/include/configuration/configObject/connector/listConnector.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact_template_model/listContactTemplateModel.ihtml
  centreon/www/include/configuration/configObject/contactgroup/listContactGroup.ihtml
  centreon/www/include/configuration/configObject/escalation/listEscalation.ihtml
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.ihtml
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.ihtml
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.ihtml
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.ihtml
  centreon/www/include/configuration/configObject/hostgroup_dependency/listHostGroupDependency.ihtml
  centreon/www/include/configuration/configObject/meta_service/listMetaService.ihtml
  centreon/www/include/configuration/configObject/metaservice_dependency/listMetaServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service/listService.ihtml
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.ihtml
  centreon/www/include/configuration/configObject/service_dependency/listServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.ihtml
  centreon/www/include/configuration/configObject/servicegroup/listServiceGroup.ihtml
  centreon/www/include/configuration/configObject/servicegroup_dependency/listServiceGroupDependency.ihtml
  centreon/www/include/configuration/configObject/timeperiod/listTimeperiod.ihtml
  centreon/www/include/configuration/configObject/traps-groups/listGroups.ihtml
  centreon/www/include/configuration/configObject/traps-manufacturer/listMnftr.ihtml
  centreon/www/include/configuration/configObject/traps/listTraps.ihtml
  centreon/www/include/configuration/configResources/listResources.ihtml
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/monitoring/comments/template/comments.ihtml
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.html
  centreon/www/include/monitoring/status/Hosts/templates/host.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml
  centreon/www/include/options/accessLists/groupsACL/listGroupConfig.ihtml
  centreon/www/include/options/accessLists/menusACL/listsMenusAccess.ihtml
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/reporting/dashboard/initReport.php
  centreon/www/include/views/componentTemplates/listComponentTemplates.ihtml
  centreon/www/include/views/graphTemplates/listGraphTemplates.ihtml
  centreon/www/include/views/graphs/graphs.html
  centreon/www/include/views/virtualMetrics/listVirtualMetrics.ihtml
Labels: area/backend

#1299 fix(feature): Unblock users via GUI
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/contact.php
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend

#1467 fix(feature): Unblock users via GUI (dev-23.04.x)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/contact.php
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend

#1466 fix(feature): Unblock users via GUI (dev-22.10.x)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/contact.php
  centreon/www/include/configuration/configObject/contact/listContact.ihtml
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend

#1274 enh(api/conf) Remove previous endpoint for FindHostTemplates
  centreon/config/routes/Centreon/host_template.yaml
  centreon/src/Centreon/Application/Controller/HostTemplateController.php
  centreon/src/Centreon/Domain/HostConfiguration/Exception/HostTemplateException.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostTemplate/FindHostTemplates.php
  centreon/src/Centreon/Domain/HostConfiguration/UseCase/V2110/HostTemplate/FindHostTemplatesResponse.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostTemplateV2110.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/API/Model/HostTemplateV2110Factory.php
  centreon/tests/php/Centreon/Application/Controller/HostTemplateControllerTest.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplateResponseTest.php
  centreon/tests/php/Centreon/Domain/HostConfiguration/UseCase/V2110/FindHostTemplatesTest.php
Labels: area/backend

#1103 feat(api/conf) add UpdateHostCategory endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/Repository/WriteHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategory.php
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategoryRequest.php
  centreon/src/Core/HostCategory/Domain/Model/HostCategory.php
  centreon/src/Core/HostCategory/Domain/Model/NewHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/API/UpdateHostCategory/UpdateHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/UpdateHostCategory/UpdateHostCategoryRoute.yaml
  centreon/src/Core/HostCategory/Infrastructure/API/UpdateHostCategory/UpdateHostCategorySchema.json
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/php/Core/HostCategory/Application/UseCase/AddHostCategory/AddHostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Domain/Model/HostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Domain/Model/NewHostCategoryTest.php
Labels: area/backend

#1471 Fix(CI): Improve Chromatic
  .github/actions/chromatic/action.yml
  .github/workflows/ui-beta.yml
  centreon/packages/ui/.storybook/preview.tsx
Labels: area/ui

#1266 fix(web): do not erase relation with service by hostgroup
  centreon/www/class/centreonTraps.class.php
Labels: area/backend

#1268 fix(web): do not erase relation with service by hostgroup (22.04)
  centreon/www/class/centreonTraps.class.php
Labels: area/backend

#1267 fix(web): do not erase relation with service by hostgroup (22.10)
  centreon/www/class/centreonTraps.class.php
Labels: area/backend

#1425 feat(api/conf) new endpoint AddNotification
  centreon/config/features.json
  centreon/config/packages/Centreon.yaml
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactRepositoryInterface.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Notification/Application/Converter/NotificationHostEventConverter.php
  centreon/src/Core/Notification/Application/Converter/NotificationServiceEventConverter.php
  centreon/src/Core/Notification/Application/Exception/NotificationException.php
  centreon/src/Core/Notification/Application/Repository/NotificationResourceRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/NotificationResourceRepositoryProviderInterface.php
  centreon/src/Core/Notification/Application/Repository/ReadNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/ReadNotificationResourceRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationResourceRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotification.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationRequest.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationResponse.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NewNotificationFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NotificationMessageFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NotificationResourceFactory.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Validator/NotificationUserValidator.php
  centreon/src/Core/Notification/Domain/Model/NewNotification.php
  centreon/src/Core/Notification/Domain/Model/Notification.php
  centreon/src/Core/Notification/Domain/Model/NotificationChannel.php
  centreon/src/Core/Notification/Domain/Model/NotificationGenericObject.php
  centreon/src/Core/Notification/Domain/Model/NotificationHostEvent.php
  centreon/src/Core/Notification/Domain/Model/NotificationMessage.php
  centreon/src/Core/Notification/Domain/Model/NotificationResource.php
  centreon/src/Core/Notification/Domain/Model/NotificationServiceEvent.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationRoute.yaml
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationSchema.json
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/NotificationResourceRepositoryProvider.php
  centreon/tests/api/Context/CloudPlatformContext.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/AddNotification/AddNotificationTest.php
  centreon/tests/php/Core/Notification/Domain/Model/NewNotificationTest.php
  centreon/tests/php/Core/Notification/Domain/Model/NotificationGenericObjectTest.php
  centreon/tests/php/Core/Notification/Domain/Model/NotificationMessageTest.php
  centreon/tests/php/Core/Notification/Domain/Model/NotificationTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0-beta.1.sql
Labels: area/backend

#229 enh(open-tickets): add filter by poller preference to widget
  centreon-open-tickets/widgets/open-tickets/configs.xml
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
Labels: enhancement

#1482 enh(open-tickets): add filter by poller preference to widget - dev-23.04.x
  centreon-open-tickets/widgets/open-tickets/configs.xml
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
Labels: area/backend

#1476 enh(configuration): remove nagios_path_img option
  centreon/src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationReadRepositoryInterface.php
  centreon/src/Centreon/Infrastructure/HostConfiguration/Repository/HostConfigurationRepositoryRDB.php
  centreon/tests/rest_api/rest_api.postman_collection.json
  centreon/tests/rest_api/rest_api.postman_environment.json
  centreon/www/class/centreon-clapi/centreonSettings.class.php
  centreon/www/class/centreonMedia.class.php
  centreon/www/class/config-generate-remote/Media.php
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/engine/form.ihtml
  centreon/www/include/Administration/parameters/engine/form.php
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
  centreon/www/include/options/media/images/listImg.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.1.php
  centreon/www/install/php/Update-23.10.0.php
Labels: area/backend

#1337 fix(hostgroup): correct the query to get hostgroup info
  centreon/src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
Labels: area/backend

#1497 fix(openid): Authentication conditions not working when getting info from defined endpoints
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/Conditions.php
Labels: area/backend

#1508 fix(openid): Authentication conditions not working when getting info from defined endpoints - dev-23.04.x
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/Conditions.php
Labels: area/backend

#1513 [style]: Add css in global style files to fix Mbi widget visibility (dev-22.10.x)
  centreon/www/Themes/Centreon-Dark/variables.css
  centreon/www/Themes/Generic-theme/Variables-css/variables.css
  centreon/www/Themes/Generic-theme/style.css
Labels: area/backend

#1511 fix(openid): extractPayloadToken does not follow JWT standard
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#1523 fix(export/rs): recreate the deleted map images not linked to resources (23.04)
  centreon/www/class/config-generate-remote/Host.php
Labels: area/backend
