Repository centreon/centreon, pull requests merged in 2023-12, with the labels that each got.

#2761 enh(map): add map visx viewer feature flag
  centreon/config/features.json
Labels: area/ui

#2779 chore: composer update symfony/security-bundle [23.04]
  centreon/composer.lock
Labels: area/backend

#2777 chore: composer update symfony/security-bundle [22.04]
  centreon/composer.lock
Labels: area/backend

#2792 fix(notification): casting issue ignored service events
  centreon/src/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactory.php
Labels: area/backend

#2757 chore: composer update symfony/*
  centreon/composer.lock
Labels: area/backend

#2686 fix(legacy): unecessary code
  centreon/lib/Centreon/Object/Object.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  centreon/www/api/class/centreon_monitoring_externalcmd.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#2780 chore: composer update symfony/security-bundle [23.10]
  centreon/composer.lock
Labels: area/backend

#2715 Add authentication tests to API testing
  centreon/tests/api/features/LocalAuthentication.feature
  centreon/tests/api/features/LocalProviderConfiguration.feature
  centreon/tests/api/features/OpenIdProviderConfiguration.feature
  centreon/tests/api/features/Token.feature
  centreon/tests/api/features/WebSSOProviderConfiguration.feature
  centreon/tests/rest_api/collections/authentication/01 - Tokens.postman_collection.json
  centreon/tests/rest_api/collections/authentication/02 - Local Authentication.postman_collection.json
  centreon/tests/rest_api/collections/authentication/03 - Local Provider Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/04 - OpenID Provider Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/05 - WebSSO Provider Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/authentication.postman_environment.json
Labels: area/test

#2813 test(api): Rename the collection with no spaces
  centreon/tests/rest_api/collections/authentication/01-Tokens.postman_collection.json
  centreon/tests/rest_api/collections/authentication/02-Local-Authentication.postman_collection.json
  centreon/tests/rest_api/collections/authentication/03-Local-Provider-Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/04-OpenID-Provider-Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/05-WebSSO-Provider-Configuration.postman_collection.json
Labels: area/test

#2742 enh(dashboard) : Dataset: do not propose same resource type twice
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#2815 fix(cloud notifications): Remove contact groups from UI and fix tests [dev-23.10.x]
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx/Create Panel -- sends a request to add a new notification with the form values when the Confirm button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- validates that when the Contacts field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/Form/useValidationSchema.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/api/endpoints.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelCreate.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/testUtils.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/translatedLabels.ts
Labels: area/ui

#2827 enh(UI): Add support for multiple federated components
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/Dashboard/hooks/useDashboardDetails.ts
  centreon/www/front_src/src/components/FederatedComponents/index.tsx
  centreon/www/front_src/src/federatedModules/mocks.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-data/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-generictext/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-graph/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-input/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-singledata/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-singlemetric/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-statusgrid/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-text/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-topbottom/moduleFederation.json
Labels: area/ui

#2789 feat(UI): Allow to create or edit a playlist
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration creation -- displays a modal when the form is updated and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration creation -- displays the creation form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration creation -- does not send the playlist configuration when the name is missing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration creation -- does not send the playlist configuration when the rotation time is outside the boundary.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration creation -- sends the playlist configuration when required fields are fullfilled and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration edition -- displays a modal when the form is updated and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration edition -- displays a modal when the form is updated with errors and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration edition -- displays the form with prefilled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx/Playlist Configuration edition -- sends the updated playlist configuration when some fields are changed.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Form/Form.cypress.spec.tsx/Form list -- adds an element to the list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Form/Form.cypress.spec.tsx/Form list -- removes an element from the list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Form/Form.cypress.spec.tsx/Form list -- sorts elements in the list.snap.png
  centreon/packages/ui/src/Form/Form.cypress.spec.tsx
  centreon/packages/ui/src/Form/Inputs/List/Content.tsx
  centreon/packages/ui/src/Form/Inputs/List/List.styles.ts
  centreon/packages/ui/src/Form/Inputs/List/List.tsx
  centreon/packages/ui/src/Form/Inputs/List/useList.ts
  centreon/packages/ui/src/Form/Inputs/index.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/Typography/Subtitle.tsx
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/packages/ui/src/components/Modal/ModalActions.tsx
  centreon/packages/ui/src/index.ts
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/usePluralizedTranslation.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/DashboardPlaylists.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/DashboardPlaylistsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/DasbhoardSort/SortContent.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/DashboardsSelection/DashboardsSelection.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/DashboardsSelection/SelectDashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/DashboardsSelection/useSelectDashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/FormActions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.styles.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/PlaylistConfig.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/RotationTime.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/inputs.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/useSaveConfig.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/utils.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/PlaylistConfig/validationSchema.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/atoms.ts
  centreon/www/front_src/src/Dashboards/components/DashboardPlaylists/models.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/Navigation/Sidebar/Menu/index.tsx
Labels: area/ui

#2825 fix(api) include hours and minutes in expiration_date
  centreon/src/Core/Security/Token/Application/UseCase/AddToken/AddToken.php
  centreon/tests/rest_api/collections/authentication/01-Tokens.postman_collection.json
Labels: area/backend

#2823 fix(administration) : Make the users not created on centreon plateform unenabled to edit their profile information
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#2758 fix(openid): reflect real value of username
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
Labels: area/backend

#2843 fix(configuration): Export configuration failing due to method call by reference after upgrade
  centreon/www/class/config-generate/escalation.class.php
Labels: area/backend

#2868 enh(map): export pagination components
  centreon/packages/ui/src/index.ts
Labels: area/ui

#2491 Tests(notifications) : Add cloud notification files
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Cloud-notifications/02-notification-duplicate.feature
  centreon/tests/e2e/features/Cloud-notifications/03-notification-delete.feature
  centreon/tests/e2e/features/Cloud-notifications/04-notification-edit.feature
  centreon/tests/e2e/features/Cloud-notifications/05-notification-listing.feature
  centreon/tests/e2e/package.json
Labels: area/test

#2840 revert(playlist): remove install / upgrade scripts for playlist
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.10.3.php
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#2850 fix (clapi): decode HTML entities when exporting command configuration with CLAPI
  centreon/www/class/centreon-clapi/centreonCommand.class.php
Labels: area/backend

#2878 revert(playlists): remove playlist tables creation
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-23.10.3.php
Labels: backport

#2863 chore(phpstan): add phpstan to CI on Core with level 7
  .github/workflows/web.yml
  centreon/src/Core/Application/Common/UseCase/CreatedResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsData.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
  centreon/src/Core/Domain/Engine/Model/EngineCommandGenerator.php
  centreon/src/Core/HostSeverity/Infrastructure/API/UpdateHostSeverity/UpdateHostSeverityController.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Icon/DbIconFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbReadServiceRepository.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbServiceFactory.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/src/Core/Notification/Application/Repository/NotificationResourceRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotificationResponse.php
  centreon/src/Core/Notification/Domain/Model/NotificationResource.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotification/FindNotificationPresenter.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
  centreon/src/Core/Resources/Application/UseCase/FindResourcesByParent/FindResourcesByParent.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbAccessGroupFactory.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbReadAccessGroupRepository.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/Local/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Model/ACLConditions.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Model/Endpoint.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbReadOpenIdConfigurationRepository.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Repository/DbReadConfigurationRepository.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbReadSAMLConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultConfigurationRepository.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateService.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidation.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupPresenter.php
  centreon/tests/php/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidationTest.php
  centreon/tests/php/Core/ServiceGroup/Application/AddServiceGroup/AddServiceGroupTest.php
Labels: area/backend

#2894 feat(api) Add read repository for Proxy configuration
  centreon/src/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsCommand.php
  centreon/src/Core/Common/Infrastructure/Command/AbstractMigrationCommand.php
  centreon/src/Core/Media/Infrastructure/Command/MigrateAllMedias/MigrateAllMediasCommand.php
  centreon/src/Core/Proxy/Application/Repository/ReadProxyRepositoryInterface.php
  centreon/src/Core/Proxy/Infrastructure/Repository/DbReadProxyRepository.php
Labels: area/backend

#2907 fix(install): correctly check user rights on step7
  centreon/www/install/steps/process/createDbUser.php
Labels: area/backend

#2860 fix(api/monitoring) fix centreon_application_monitoring_gethosts endpoint (criticality retrieval)
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#2852 fix(clapi) fix ldap configuration creation, handle ldap_auto_sync and ldap_sync_interval parameters
  centreon/www/class/centreon-clapi/centreonLDAP.class.php
Labels: area/backend

#2838 fix(legacy): prepare insteadof queries [22.10]
  centreon/lib/Centreon/Object/Object.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  centreon/www/api/class/centreon_monitoring_externalcmd.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#2918 fix(configuration): make host mandatory for service config in cloud context
  centreon/www/include/configuration/configObject/service/formService.php
Labels: area/backend

#2922 enh(map): export pagination components (#2868)
  centreon/packages/ui/src/index.ts
Labels: area/ui

#2620 feat(Api Tokens):[Api token] List tokens (basics) - Front
  centreon/cypress/fixtures/apiTokens/list.json
  centreon/cypress/fixtures/apiTokens/listPage2.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/TokenListing/TokenListing.cypress.spec.tsx/Api-token listing -- displays all tokens when the page loads.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/TokenListing/TokenListing.cypress.spec.tsx/Api-token listing -- enables the addition and removal of columns in the table listing when the user selects or deselects options in the Add Columns menu.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/packages/ui/src/Button/Save/Content.tsx
  centreon/packages/ui/src/Button/Save/index.tsx
  centreon/packages/ui/src/Checkbox/Checkbox.tsx
  centreon/packages/ui/src/Checkbox/CheckboxGroup/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationButton.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Actions.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Refresh/Refresh.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Refresh/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/Filter/Filter.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/Filter/atoms.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/Filter/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/Filter/models.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/Search.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Search/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/actions.styles.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/index.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/ActionsColumn.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/models.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/useColumns.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Listing.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Title.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/TokenListing.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/atoms.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/models.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/tokenListing.styles.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/useTokenListing.ts
  centreon/www/front_src/src/ApiTokens/api/decoder.ts
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
  centreon/www/front_src/src/ApiTokens/index.tsx
  centreon/www/front_src/src/ApiTokens/storage.ts
  centreon/www/front_src/src/ApiTokens/translatedLabels.ts
  centreon/www/front_src/src/Authentication/Local/LocalAuthentication.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/WebSSO/WebSSO.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/front_src/src/reactRoutes/index.ts
  centreon/www/front_src/src/reactRoutes/routeMap.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.04.0.php
Labels: area/ui

#2908 fix(api/notification): correction of contact and contact group inheritance
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/host.class.php
  centreon/www/class/config-generate/service.class.php
Labels: area/backend

#2925 enh(map): export pagination components (#2868) (#2922)
  centreon/packages/ui/src/index.ts
Labels: area/ui

#2928 enh(dashboard): add method to retrieve dashboards from given list by user
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardRepositoryInterface.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
Labels: area/backend

#2869 fix(smarty) : refactor deprecated {php}
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
Labels: area/backend

#2837 fix(legacy): prepare insteadof queries [22.04]
  centreon/lib/Centreon/Object/Object.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  centreon/www/api/class/centreon_monitoring_externalcmd.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#2934 fix(image): Centreon updateDirectory update function
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#2935 fix(Query) : Update the query on updateContactServiceCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#2995 fix(Query) : Update the query on updateContactHostCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#2993 fix(Query) : Update the query on updateGroups
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: area/backend

#2958 fix(updateDirectory): Centreon updateDirectory update function v23-04
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#2996 fix(updateLCARelation): Update updateLCARelation function v22-04
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: backport

#2998 fix(updateLCARelation): Update updateLCARelation function v22-10
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: backport

#3008 fix(Query) : Update the query on updateGroups
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: area/backend, backport

#3006 fix(Query) : Update the query on updateGroups
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: area/backend, backport

#3005 fix(Query) : Update the query on updateGroups
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: area/backend, backport

#3004 fix(Query) : Update the query on updateGroups
  centreon/www/include/options/accessLists/menusACL/DB-Func.php
Labels: area/backend, backport

#3003 fix(Query) : Update the query on updateContactHostCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2999 fix(Query) : Update the query on updateContactHostCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2997 fix(Query) : Update the query on updateContactHostCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2979 fix(Query) : Update the query on updateContactServiceCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2978 fix(Query) : Update the query on updateContactServiceCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2976 fix(Query) : Update the query on updateContactServiceCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#2975 fix(Query) : Update the query on updateContactServiceCommands
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport
