Repository centreon/centreon, pull requests merged in 2023-08, with the labels that each got.

#1907 feat(notifications): Endpoint to get all resources for configured notification
  centreon/config/packages/Centreon.yaml
  centreon/doc/API/Common/Response/NotModified.yaml
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Common/Response/NotModified.yaml
  centreon/doc/API/v23.10/Configuration/Notification/FindNotifiableResources.yaml
  centreon/doc/API/v23.10/Configuration/Notification/Schema/NotifiableResources.Listing.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Application/Common/UseCase/NotModifiedResponse.php
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/Notification/Application/Exception/NotificationException.php
  centreon/src/Core/Notification/Application/Repository/NotifiableResourceRequestProviderInterface.php
  centreon/src/Core/Notification/Application/Repository/ReadNotifiableResourceRepositoryInterface.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/FindNotifiableResources.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/FindNotifiableResourcesPresenterInterface.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/FindNotifiableResourcesResponse.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/NotifiableHostDto.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/NotifiableResourceDto.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifiableResources/NotifiableServiceDto.php
  centreon/src/Core/Notification/Domain/Model/NotifiableHost.php
  centreon/src/Core/Notification/Domain/Model/NotifiableResource.php
  centreon/src/Core/Notification/Domain/Model/NotifiableService.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableResources/FindNotifiableResourcesController.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableResources/FindNotifiableResourcesPresenter.php
  centreon/src/Core/Notification/Infrastructure/API/FindNotifiableResources/FindNotifiableResourcesRoute.yaml
  centreon/src/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactory.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotifiableResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/HostGroupRequestProvider.php
  centreon/src/Core/Notification/Infrastructure/Repository/ServiceGroupRequestProvider.php
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotifiableResources/FindNotifiableResourcesTest.php
  centreon/tests/php/Core/Notification/Infrastructure/API/FindNotifiableResources/FindNotifiableResourcesPresenterStub.php
  centreon/tests/php/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactoryTest.php
Labels: area/backend

#1992 [dev-23.04.x] fix(downtimes): Removed author_id property from POST requests in downtime endpoints (#1982)
  centreon/config/json_validator/latest/Centreon/Downtime/Downtime.json
  centreon/config/json_validator/latest/Centreon/Downtime/DowntimeResources.json
  centreon/config/json_validator/latest/Centreon/Downtime/Downtimes.json
  centreon/doc/API/centreon-api-v23.04.yaml
Labels: area/backend

#1993 [dev-22.10.x] fix(downtimes): Removed author_id property from POST requests in downtime endpoints (#1982)
  centreon/config/json_validator/latest/Centreon/Downtime/Downtime.json
  centreon/config/json_validator/latest/Centreon/Downtime/DowntimeResources.json
  centreon/config/json_validator/latest/Centreon/Downtime/Downtimes.json
  centreon/doc/API/centreon-api-v22.10.yaml
Labels: area/backend

#1912 fix(administration) - fix pagination of perfdata page (dev-23.04.x)
  centreon/www/include/Administration/performance/viewData.php
Labels: area/backend

#1994 [dev-22.04.x] fix(downtimes): Removed author_id property from POST requests in downtime endpoints (#1982)
  centreon/config/json_validator/latest/Centreon/Downtime/Downtime.json
  centreon/config/json_validator/latest/Centreon/Downtime/DowntimeResources.json
  centreon/config/json_validator/latest/Centreon/Downtime/Downtimes.json
  centreon/doc/API/centreon-api-v22.04.yaml
Labels: area/backend

#1996 enh(packages/wizard):[UX] Remove "Exit wizard" popin after having added token or view license
  centreon/packages/ui/src/Wizard/WizardContent.tsx
  centreon/packages/ui/src/Wizard/index.tsx
  centreon/packages/ui/src/Wizard/models.ts
Labels: area/ui

#1991 enh(api): handle host groups in AddHost endpoint
  centreon/doc/API/v23.10/Configuration/Host/Schema/AddHostRequest.yaml
  centreon/doc/API/v23.10/Configuration/Host/Schema/AddHostResponse.yaml
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostFactory.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostRequest.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostResponse.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/src/Core/Host/Application/UseCase/DeleteHost/DeleteHost.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostController.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostOnPremSchema.json
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostSaasPresenter.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostSaasSchema.json
  centreon/src/Core/Host/Infrastructure/API/DeleteHost/DeleteHostController.php
  centreon/src/Core/HostGroup/Application/Repository/ReadHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Application/Repository/WriteHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
  centreon/tests/api/features/CloudHost.feature
  centreon/tests/api/features/Host.feature
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostValidationTest.php
  centreon/tests/php/Core/Host/Application/UseCase/DeleteHost/DeleteHost.php
  centreon/tests/php/Core/Host/Infrastructure/API/DeleteHost/DeleteHostPresenterStub.php
Labels: area/backend

#1951 feat(UI): Add Generic text widget
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Add widget -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/FloatingLinkEditorPlugin.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/addWidget.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/Dashboard/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/Dashboard/utils.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-generictext/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-generictext/properties.json
  centreon/www/widgets/src/centreon-widget-generictext/src/index.tsx
Labels: area/ui

#1674 fix(centreontrapd): carriage return entreprise args
  centreon/lib/perl/centreon/trapd/lib.pm
Labels: bug

#2010 Fix(Test): Fix login Cypress test
  centreon/packages/ui/src/Image/Image.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/EditPanel/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Login/Login.cypress.spec.tsx
Labels: area/ui

#2024 feat(notification) - Implement backend support for adding BV in cloud notifications
  centreon/src/Core/Notification/Application/UseCase/FindNotifications/FindNotifications.php
  centreon/src/Core/Notification/Application/UseCase/FindNotifications/NotificationCounts.php
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotifications/FindNotificationsTest.php
Labels: area/backend

#2026 enh(vault): Add feature flag to vault configuration endpoints
  centreon/config/features.json
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/DeleteVaultConfiguration/DeleteVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfiguration/FindVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/FindVaultConfigurations/FindVaultConfigurationsRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationRoute.yaml
  centreon/tests/api/features/VaultConfiguration.feature
Labels: area/backend

#2023 enh(Edit Profile): My account form should not display Password fields
  centreon/www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#2013 enh(UI): Improve generic properties
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- disables the Add button when metrics are removed from the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/package.json
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/AutoLinkPlugin/index.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/FloatingLinkEditorPlugin.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/BlockButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/FormatButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/MacrosButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ToolbarPlugin.styles.ts
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/UndoRedoButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/index.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Switch.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useValidationSchema.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
Labels: area/ui

#2034 [WIP] enh(notifications): add a new formatted_message property
  centreon/doc/API/v23.10/Configuration/Notification/Schema/Notification.Message.yaml
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotification.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationRequest.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotificationResponse.php
  centreon/src/Core/Notification/Application/UseCase/AddNotification/Factory/NotificationMessageFactory.php
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotification.php
  centreon/src/Core/Notification/Application/UseCase/UpdateNotification/Factory/NotificationMessageFactory.php
  centreon/src/Core/Notification/Application/UseCase/UpdateNotification/UpdateNotificationRequest.php
  centreon/src/Core/Notification/Domain/Model/NotificationMessage.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/AddNotification/AddNotificationSchema.json
  centreon/src/Core/Notification/Infrastructure/API/UpdateNotification/UpdateNotificationController.php
  centreon/src/Core/Notification/Infrastructure/API/UpdateNotification/UpdateNotificationSchema.json
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/tests/api/features/Notification.feature
  centreon/tests/php/Core/Notification/Application/UseCase/AddNotification/AddNotificationTest.php
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotification/FindNotificationTest.php
  centreon/tests/php/Core/Notification/Application/UseCase/UpdateNotification/UpdateNotificationTest.php
  centreon/tests/php/Core/Notification/Domain/Model/NotificationMessageTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.10.0.sql
Labels: area/backend

#2035 enh(Edit Profile): My account form should not display Password fields
  centreon/www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#2025 feat(UI): Implement threshold and refresh interval properties
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetrics.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- disables the Add button when metrics are removed from the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx/Refresh interval -- changes the second label to seconds when the value is greater than 1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx/Refresh interval -- changes the seconds label to second when the value is 1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx/Refresh interval -- displays the refresh interval fields.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx/Refresh interval -- enables the Interval field when the Custom radio button is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx/Thresold -- displays the threshold with no selected metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx/Thresold -- displays the threshold with selected metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx/Thresold -- does not reset the threshold value when the Show Thresholds checkbox is unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx/Thresold -- enables the threshold fields when the Show Thresholds checkbox is checked and the Custom option is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx/Thresold -- unchecks the Show thresholds switch when different units are selected.snap.png
  centreon/doc/API/openapi.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/useRefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TextField.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/useThreshold.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/addWidget.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/api/decoders.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-data/properties.json
  centreon/www/widgets/src/centreon-widget-input/properties.json
Labels: area/ui

#1990 enh(Licenses) : Implement a method that calculates the number of days remaining until the license expiration date
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/packages/ui/cypress/visual-testing-snapshots/src/utils/useLicenseExpirationWarning.cypress.spec.tsx/License -- displays a warning message when the license expires within 15 days.snap.png
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/translatedLabel.ts
  centreon/packages/ui/src/utils/useLicenseExpirationWarning.cypress.spec.tsx
  centreon/packages/ui/src/utils/useLicenseExpirationWarning.ts
Labels: area/ui

#2029 enh(UI): Improve widget modal
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- disables the Add button when metrics are removed from the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/components/Avatar/Avatar.stories.tsx
  centreon/packages/ui/src/components/Avatar/Avatar.styles.ts
  centreon/packages/ui/src/components/Avatar/Avatar.tsx
  centreon/packages/ui/src/components/Avatar/index.ts
  centreon/packages/ui/src/components/CollapsibleItem/CollapsibleItem.stories.tsx
  centreon/packages/ui/src/components/CollapsibleItem/CollapsibleItem.tsx
  centreon/packages/ui/src/components/CollapsibleItem/index.ts
  centreon/packages/ui/src/components/CollapsibleItem/useCollapsibleItemStyles.ts
  centreon/packages/ui/src/components/ItemComposition/Item.tsx
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.tsx
  centreon/packages/ui/src/components/Modal/Modal.stories.tsx
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/packages/ui/src/components/Modal/Modal.tsx
  centreon/packages/ui/src/components/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/UnsavedChanges.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/useResources.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetData.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetSelection.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/addWidget.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/components/Title.tsx
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-singledata/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-singledata/properties.json
  centreon/www/widgets/src/centreon-widget-singledata/src/index.tsx
Labels: area/ui

#2044 fix(performance): take account of AD exclusion while getting virtual services
  centreon/www/api/class/centreon_performance_service.class.php
Labels: area/backend

#2027 enh(Widget): Use description field for text widget
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/index.tsx
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useValidationSchema.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/models.ts
  centreon/www/widgets/src/centreon-widget-generictext/properties.json
Labels: area/ui

#2062 enh(dashboard): remove unused properties from metrics data endpoint
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Dashboard.MetricsPerformancesData.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/QueryParameter/End.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/QueryParameter/MetricIds.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/QueryParameter/Start.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsPerformancesData.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataPresenter.php
Labels: area/backend

#2052 enh(notifications): Add formatted_message property to GET notification endpoint
  centreon/src/Core/Notification/Application/UseCase/FindNotification/FindNotification.php
  centreon/tests/api/features/Notification.feature
Labels: area/backend

#2064 fix (clapi): Add setseverity command when exporting configuration with CLAPI
  centreon/www/class/centreon-clapi/centreonHostCategory.class.php
Labels: area/backend

#2059 enh (api): Update of the service template API endpoint (PATCH) for managing service groups
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/ServiceGroup/Application/Repository/WriteServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Domain/Model/ServiceGroupRelation.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbWriteServiceGroupRepository.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ServiceGroupDto.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateSaasSchema.json
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidationTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#2050 enh(api): remove is_activate property from hostTemplate and serviceTemplate endpoints
  centreon/doc/API/v23.10/Configuration/HostTemplate/AddAndFindHostTemplates.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/AddHostTemplateRequest.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/AddHostTemplateResponse.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/HostTemplate.yaml
  centreon/doc/API/v23.10/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/AddOneAndFindServiceTemplates.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/AddServiceTemplateResponse.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/NewServiceTemplate.yaml
  centreon/doc/API/v23.10/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateFactory.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateResponse.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/NewHostTemplateFactory.php
  centreon/src/Core/HostTemplate/Application/UseCase/FindHostTemplates/FindHostTemplates.php
  centreon/src/Core/HostTemplate/Application/UseCase/FindHostTemplates/FindHostTemplatesResponse.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplateRequest.php
  centreon/src/Core/HostTemplate/Domain/Model/HostTemplate.php
  centreon/src/Core/HostTemplate/Domain/Model/NewHostTemplate.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateOnPremPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateOnPremSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateSaasSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/FindHostTemplates/FindHostTemplatesOnPremPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/FindHostTemplates/FindHostTemplatesSaasPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateController.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateOnPremSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSaasSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateResponse.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/NewServiceTemplateFactory.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/ServiceTemplateDto.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateRequest.php
  centreon/src/Core/ServiceTemplate/Domain/Model/NewServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Domain/Model/ServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/API/FindServiceTemplates/FindServiceTemplatesOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateController.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateOnPremSchema.json
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateRepository.php
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/HostTemplate.feature
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/HostTemplate/Application/AddHostTemplate/AddHostTemplateTest.php
  centreon/tests/php/Core/HostTemplate/Application/FindHostTemplates/FindHostTemplatesTest.php
  centreon/tests/php/Core/HostTemplate/Application/PartialUpdateHostTemplate/PartialUpdateHostTemplateTest.php
  centreon/tests/php/Core/HostTemplate/Domain/Model/HostTemplateTest.php
  centreon/tests/php/Core/HostTemplate/Domain/Model/NewHostTemplateTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#2066 fix(authentication): fix redirection for OpenID & SAML for legacy pages
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/LoginResponse.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LoginSession/LoginSessionTest.php
  centreon/www/front_src/src/Login/useLogin.ts
Labels: area/ui, area/backend

#2065 Fix(MON-21040): ‎centreon/www/class/centreonLogAction.class.php
  centreon/www/class/centreonLogAction.class.php
Labels: area/backend

#2089 FIX(Mon 21268): in ‎centreon/www/class/centreonLogAction.class.php
  centreon/www/class/centreonLogAction.class.php
Labels: area/backend

#2076 fix(api) Host, HostTemplate, Service, ServiceTemplate endpoints
  centreon/src/Core/Common/Infrastructure/Repository/RepositoryTrait.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostRepository.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateRepository.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#2101 Fix(MON-21270) : in ‎centreon/www/class/centreonLogAction.class.php
  centreon/www/class/centreonLogAction.class.php
Labels: area/backend

#2085 fix(authentication): fix redirection for OpenID & SAML for legacy pages #2066
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/LoginResponse.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
  centreon/www/front_src/src/Login/useLogin.ts
Labels: area/ui, area/backend

#2078 fix(cli): Avoids using the host template name instead of the host name when you want to bind a service to an additional host
  centreon/www/class/centreon-clapi/centreonService.class.php
Labels: area/backend

#2071 fix (clapi): Add setseverity command when exporting configuration with CLAPI
  centreon/www/class/centreon-clapi/centreonHostCategory.class.php
Labels: area/backend

#2103 fix(resource status): resource status filtering
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesController.php
  centreon/tests/api/features/ResourceMonitoring.feature
Labels: area/backend
