Repository centreon/centreon, pull requests merged in 2023-11, with the labels that each got.

#2468 fix(dashboard): Error 500 while no search parameters on top metrics listing
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
Labels: area/backend

#2476 enh(graphs): increase curves thickness
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/RegularLines/index.tsx
Labels: area/ui

#2486 fix(cloud notifications): Double display of configured resources and resources' count
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
Labels: area/backend

#2445 fix(update): correctly handle topology table update
  centreon/www/install/php/Update-23.04.1.php
  centreon/www/install/php/Update-23.04.8.php
  centreon/www/install/sql/centreon/Update-DB-23.04.1.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.8.sql
Labels: area/backend

#2420 fix(authentication): auto imported user can reach frontend
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Domain/Configuration/User/Model/User.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/tests/php/Core/Application/Configuration/User/UseCase/PatchUser/PatchUserTest.php
  centreon/tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
Labels: area/backend

#2448 fix(event-logs) : issue with pagination displayed without results fixed
  centreon/www/include/eventLogs/Paginator.php
  centreon/www/include/eventLogs/xml/PaginationRenderer.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#2497 fix(authentication): auto imported user can reach frontend (#2420)
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Domain/Configuration/User/Model/User.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/tests/php/Core/Application/Configuration/User/UseCase/PatchUser/PatchUserTest.php
  centreon/tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
Labels: area/backend

#2496 fix(authentication): auto imported user can reach frontend (#2420)
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Domain/Configuration/User/Model/User.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/tests/php/Core/Application/Configuration/User/UseCase/PatchUser/PatchUserTest.php
  centreon/tests/php/Core/Domain/Configuration/User/Model/UserTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Api/FindUsers/FindUsersPresenterTest.php
  centreon/tests/php/Core/Infrastructure/Configuration/User/Repository/DbUserFactoryTest.php
Labels: area/backend

#2517 chore(API): Bump latest version to 24.04
  centreon/config/packages/Centreon.yaml
Labels: area/backend

#2511 fix(legacy): escape fields (2310)
  centreon/www/include/configuration/configObject/host/listHost.ihtml
Labels: area/backend

#2518 fix(legacy): escape field revert
  centreon/www/include/configuration/configObject/host/listHost.ihtml
Labels: area/backend

#2514 fix(event-logs) : issue with pagination displayed without results fixed (23.10)
  centreon/www/include/eventLogs/Paginator.php
  centreon/www/include/eventLogs/xml/PaginationRenderer.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#2510 fix(event-logs) : issue with pagination displayed without results fixed (23.04)
  centreon/www/include/eventLogs/Paginator.php
  centreon/www/include/eventLogs/xml/PaginationRenderer.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#2438 fix(api): hide passwords macros in command_line when getting a monitored service detail
  centreon/src/Centreon/Application/Controller/MonitoringHostsController.php
Labels: area/backend

#2446 fix(api/monitoring): move filter on resources with graph data in the request
  centreon/src/Core/Resources/Application/Repository/ReadResourceRepositoryInterface.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend

#2519 feat(API): Add endpoint to find metrics of a service
  centreon/src/Core/Metric/Application/Repository/ReadMetricRepositoryInterface.php
  centreon/src/Core/Metric/Application/UseCase/FindMetricsByService/FindMetricsByService.php
  centreon/src/Core/Metric/Application/UseCase/FindMetricsByService/FindMetricsByServicePresenterInterface.php
  centreon/src/Core/Metric/Application/UseCase/FindMetricsByService/FindMetricsByServiceResponse.php
  centreon/src/Core/Metric/Application/UseCase/FindMetricsByService/MetricDto.php
  centreon/src/Core/Metric/Domain/Model/Metric.php
  centreon/src/Core/Metric/Infrastructure/API/FindMetricsByService/FindMetricsByServiceController.php
  centreon/src/Core/Metric/Infrastructure/API/FindMetricsByService/FindMetricsByServicePresenter.php
  centreon/src/Core/Metric/Infrastructure/API/FindMetricsByService/FindMetricsByServiceRoute.yaml
  centreon/src/Core/Metric/Infrastructure/Repository/DbMetricFactory.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/tests/php/Core/Metric/Application/UseCase/FindMetricsByService/FindMetricsByServicePresenterStub.php
  centreon/tests/php/Core/Metric/Application/UseCase/FindMetricsByService/FindMetricsByServiceTest.php
Labels: area/backend

#2533 fix(dashboard): URI encode special characters in metrics name
  centreon/packages/ui/src/api/useGraphQuery/index.ts
Labels: area/ui

#2538 enh(api): Add Documentation for metrics by service listing endpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Realtime/Metrics/FindMetricsByService.yaml
  centreon/doc/API/v24.04/Realtime/Metrics/Schema/HostId.yaml
  centreon/doc/API/v24.04/Realtime/Metrics/Schema/Metric.yaml
  centreon/doc/API/v24.04/Realtime/Metrics/Schema/ServiceId.yaml
Labels: area/backend

#2475 (fix:cloud notification) : fix Selector Hostgroups and service groups displays multiple same values on the list options
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/FormInputs/useFormInputs.tsx
Labels: area/ui

#2542 [dev-23.10.x] fix(cloud notifications): Double display of configured resources and resources' count (#2486)
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
Labels: area/backend

#2537 enh(configuration): include cloud specifics to host configuration
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/formHostCloud.ihtml
  centreon/www/include/configuration/configObject/host/formHostOnPrem.ihtml
  centreon/www/include/configuration/configObject/host/help.php
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#2509 enh(centreon cloud): Allow to manage groups and contacts
  centreon/www/class/centreonACL.class.php
  centreon/www/include/configuration/configObject/contactgroup/DB-Func.php
  centreon/www/include/configuration/configObject/contactgroup/formContactGroup.ihtml
  centreon/www/include/configuration/configObject/contactgroup/formContactGroup.php
Labels: area/backend

#2389 feat(api) new endpoint: FindConnectors
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Connector/FindConnectors.yaml
  centreon/doc/API/v24.04/Configuration/Connector/Schema/FindConnectorsResponse.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Command/Application/Repository/ReadCommandRepositoryInterface.php
  centreon/src/Core/Command/Infrastructure/Repository/DbReadCommandRepository.php
  centreon/src/Core/Connector/Application/Exception/ConnectorException.php
  centreon/src/Core/Connector/Application/Repository/ReadConnectorRepositoryInterface.php
  centreon/src/Core/Connector/Application/UseCase/FindConnectors/ConnectorDto.php
  centreon/src/Core/Connector/Application/UseCase/FindConnectors/FindConnectors.php
  centreon/src/Core/Connector/Application/UseCase/FindConnectors/FindConnectorsPresenterInterface.php
  centreon/src/Core/Connector/Application/UseCase/FindConnectors/FindConnectorsResponse.php
  centreon/src/Core/Connector/Domain/Model/Connector.php
  centreon/src/Core/Connector/Infrastructure/API/FindConnectors/FindConnectorsController.php
  centreon/src/Core/Connector/Infrastructure/API/FindConnectors/FindConnectorsPresenter.php
  centreon/src/Core/Connector/Infrastructure/API/FindConnectors/FindConnectorsRoute.yaml
  centreon/src/Core/Connector/Infrastructure/Repository/DbReadConnectorRepository.php
  centreon/tests/php/Core/Connector/Application/UseCase/FindConnectors/FindConnectorsTest.php
  centreon/tests/php/Core/Connector/Domain/Model/ConnectorTest.php
  centreon/tests/php/Core/Connector/Infrastructure/API/FindConnectors/FindConnectorsPresenterStub.php
Labels: area/backend

#2484 enh(dashboards) : Update global refresh icon
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
Labels: area/ui

#2548 enh(resource status): add metrics by service endpoint to hypermedia
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/Infrastructure/RealTime/Api/FindService/FindServicePresenter.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
  centreon/src/Core/Resources/Infrastructure/API/FindResourcesByParent/FindResourcesByParentPresenter.php
Labels: area/backend

#2551 enh(configuration): merge cloud/onPrem form for host templates
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/configuration/configObject/host_template_model/hostTemplateModel.php
Labels: area/backend

#2544 feat(api): new endpoint PartialUpdateHost
  centreon/composer.lock
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Host/DeleteAndPartialUpdateHost.yaml
  centreon/doc/API/v24.04/Configuration/Host/DeleteHost.yaml
  centreon/doc/API/v24.04/Configuration/Host/Schema/PartialUpdateHostRequest.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Host/Application/Exception/HostException.php
  centreon/src/Core/Host/Application/Repository/WriteHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/HostMacroFactory.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHost.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostRequest.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostController.php
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostOnPremSchema.json
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostRoute.yaml
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostSaasSchema.json
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostRepository.php
  centreon/src/Core/HostGroup/Application/Repository/WriteHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/DeleteHost/DeleteHostTest.php
  centreon/tests/php/Core/Host/Application/UseCase/FindHosts/FindHostsTest.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostTest.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidationTest.php
  centreon/tests/php/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostPresenterStub.php
Labels: area/backend

#2558 fix(sql): queries not supported on Mysql 8.0
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
Labels: area/backend

#2525 chore(phpstan): add phpstan to CI with level 3
  .github/workflows/web.yml
  centreon/phpstan.core.neon
  centreon/phpstan.neon
  centreon/phpstan.test.neon
  centreon/src/Centreon/Domain/Repository/DowntimeRepository.php
  centreon/src/Centreon/Infrastructure/CentreonLegacyDB/CentreonDBAdapter.php
  centreon/src/Centreon/Infrastructure/Service/UploadFileService.php
  centreon/src/Centreon/Tests/Application/Webservice/CentreonFrontendComponentTest.php
  centreon/src/Centreon/Tests/Infrastructure/Provider/AutoloadServiceProviderTest.php
  centreon/src/Centreon/Tests/Resources/CheckPoint.php
  centreon/src/Centreon/Tests/Resources/Mock/RepositoryMock.php
  centreon/src/Centreon/Tests/Resources/Traits/WebServiceExecuteTestTrait.php
  centreon/src/CentreonLegacy/Core/Module/Healthcheck.php
  centreon/src/CentreonLegacy/Core/Module/Upgrader.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataController.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Exception/AttributePathFetcherNotFoundException.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Exception/Http/InvalidContentException.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Local/Model/Configuration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/Configuration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Exception/MissingLogoutUrlException.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/Configuration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/WebSSO/Model/Configuration.php
Labels: area/backend

#2573 fix(sql): queries not supported on Mysql 8.0 [23.10]
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
Labels: area/backend

#2579 feat(resource access management): Added feature flag entry in features.json
  centreon/config/features.json
Labels: area/backend

#2578 feat(resource access management): Add topology for new page
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-23.10.0.php
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#2584 enh(configuration): merge cloud/onPrem forms for services
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/service/formServiceCloud.ihtml
  centreon/www/include/configuration/configObject/service/formServiceOnPrem.ihtml
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service/serviceByHostGroup.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend

#2563 fix(recurrentDowntime): take correctly service template into account (#2322)
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#2572 fix(Extension) : Issue of modules dependencies on install/update
  centreon/src/CentreonModule/Infrastructure/Source/ModuleSource.php
Labels: area/backend

#2598 enh(configuration): merge cloud/onPrem forms for service templates
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
  centreon/www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Labels: area/backend

#2589 feat(log): Add possibility to enable application debug through UI
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/debug/form.ihtml
  centreon/www/include/Administration/parameters/debug/form.php
  centreon/www/include/Administration/parameters/debug/help.php
Labels: area/backend

#2604 fix(UI): Fix cannot-load-module message on widgets
  centreon/packages/js-config/webpack/base/index.js
Labels: area/ui

#2581 chore(phpstan): add phpstan to CI with level 4
  .github/workflows/web.yml
  centreon/phpstan.neon
  centreon/src/Centreon/Application/Controller/FilterController.php
  centreon/src/Centreon/Application/Validation/Validator/RepositoryCallbackValidator.php
  centreon/src/Centreon/Application/Validation/Validator/UniqueEntityValidator.php
  centreon/src/Centreon/Domain/Authentication/UseCase/AuthenticateApi.php
  centreon/src/Centreon/Domain/Entity/EntityValidator.php
  centreon/src/Centreon/Domain/Gorgone/GorgoneService.php
  centreon/src/Centreon/Domain/Repository/ImagesRepository.php
  centreon/src/Centreon/Domain/Service/JsonValidator/Validator.php
  centreon/src/Centreon/Infrastructure/Filter/FilterRepositoryRDB.php
  centreon/src/Centreon/Infrastructure/Proxy/ProxyRepositoryRDB.php
  centreon/src/Centreon/ServiceProvider.php
  centreon/src/Centreon/Tests/Application/Validation/Validator/UniqueEntityValidatorTest.php
  centreon/src/CentreonLegacy/Core/Menu/Menu.php
  centreon/src/CentreonLegacy/Core/Module/Healthcheck.php
  centreon/src/CentreonLegacy/Core/Module/License.php
  centreon/src/CentreonLegacy/Core/Utils/Utils.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataController.php
  centreon/src/Core/Dashboard/Infrastructure/API/PartialUpdateDashboard/PartialUpdateDashboardController.php
  centreon/src/Core/Host/Application/Converter/HostEventConverter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateController.php
  centreon/src/Core/Infrastructure/Common/Presenter/DownloadPresenter.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbReadAccessGroupRepository.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/Conditions.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/GroupsMapping.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/RolesMapping.php
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbReadServiceSeverityRepository.php
  centreon/src/Security/Encryption.php
  centreon/tests/php/Core/Host/Application/Converter/HostEventConverterTest.php
Labels: area/backend

#2619 fix (clapi): Fixed the configuration of broker created by CLAPI
  centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: area/backend

#2616 feat(cloud): add new endpoint for resource access management listing
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/ResourceAccess/Application/Exception/RuleException.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadRuleRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRules.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesPresenterInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesResponse.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/RuleDto.php
  centreon/src/Core/ResourceAccess/Domain/Model/Rule.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/FindRules/FindRulesController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/FindRules/FindRulesPresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/FindRules/FindRulesRoute.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadRuleRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesTest.php
  centreon/tests/php/Core/ResourceAccess/Domain/Model/RuleTest.php
  centreon/tests/php/Core/ResourceAccess/Infrastructure/API/FindRules/FindRulesPresenterStub.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#2613 fix(dashboard) : Resource/Metric selection: chip removal
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- removes metrics item when the delete icon is clicked.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/useMetricsOnly.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#2608 enh(UX) : Widget edition: replace "add resource" by "refine filter"
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
Labels: area/ui

#2614 enh(Design System): Implement heatmap component
  centreon/packages/ui/src/Graph/Gauge/Gauge.stories.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMap.stories.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMap.styles.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMap.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMapData.json
  centreon/packages/ui/src/Graph/HeatMap/ResponsiveHeatMap.tsx
  centreon/packages/ui/src/Graph/HeatMap/index.ts
  centreon/packages/ui/src/Graph/HeatMap/model.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/packages/ui/src/Typography/EllipsisTypography.tsx
  centreon/packages/ui/src/index.ts
Labels: area/ui

#2626 fix(dashboard) : Widget quick edition: fix cursors issues
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.tsx
Labels: area/ui

#2536 enh(UI) : refacto the Rich Text Editor
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Center when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Center when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Left when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Right when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Right when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Bullet List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 1 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 2 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 3 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 4 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 5 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 6 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Huge when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Large when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Normal when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Number List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Small when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Editable Rich Text Editor -- displays all elements when RichTextEditor is called with required props.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Editable Rich Text Editor -- displays all format actions when the format button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- List type -- displays Ordered List when the corresponding list type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- List type -- displays Unordered List when the corresponding list type button is selected.snap.png
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/AlignPicker.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/BlockButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/FormatButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/LinkButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ListButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/MacrosButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ToolbarPlugin.styles.ts
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/UndoRedoButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/index.tsx
  centreon/packages/ui/src/RichTextEditor/translatedLabels.ts
  centreon/packages/ui/src/components/Menu/Button/MenuButton.tsx
  centreon/packages/ui/src/components/Menu/MenuItem.tsx
  centreon/packages/ui/src/components/Menu/MenuItems.tsx
Labels: area/ui

#2667 fix(test) : Fix component test for rich text editor
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel  Confirm Dialog -- confirms that the Confirm button triggers the sending of a PUT request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the Expand/Collapse button triggers the desired expansion or collapse of the panel, providing users with the ability to control its visibility and size.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the ExpandCollapse button triggers the desired expansion or collapse of the panel, providing users with the ability to control its visibility and size.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the Include Services checkbox controls the enabling and checking of all host group services checkboxes.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the Message field is properly rendered with the edited notification message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the Save button responds to field changes correctly, becoming enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the Subject field is properly rendered with the edited notification subject.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the notification name is properly rendered with the edited value and supports the capability for users to modify the name by interacting with the Edit icon.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- confirms that the three icons for notification channels are appropriately presented, with the email icon initially selected and the other icons disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- displays host group resources and events with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- displays service groups and events fields with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- displays the Contact Groups field with edited notification contact groups.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- displays the Contacts field with edited notification contacts.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the Include Services field presents the value of the edited notification.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the Save button's initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the header section displays all the expected actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that the time period checkbox is checked and disabled, indicating its pre-selected status.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that when the Host Groups field is empty, all event checkboxes are unchecked and the Include Services field is not visible.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- ensures that when the Service Groups field is empty, all associated events are disabled and unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- validates that when both resource fields are empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- validates that when the Contacts and Contact Groups fields are both empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- validates that when the Message field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel -- validates that when the Subject field is empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Business Views -- displays Business Views and their events with the edited notification values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Business Views -- ensures that when the BA field is empty, all associated events are disabled and unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Business Views -- validates that when all resource fields are empty, the user interface responds by displaying an error message and disabling the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Delete button -- displays an error message upon failed deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- disables the Confirm button if the name is empty or already exists.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- disables the Duplicate button when changes are made.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- displays a success message upon successful duplication.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- displays an error message upon failed duplication request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- displays confirmation dialog with new notification name field on Duplicate button click.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx/Edit Panel Duplicate button -- validates that name field is not empty and not already taken.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/testUtils.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
Labels: area/ui

#2628 feat(api): new endpoint PartialUpdateService
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Service/DeleteService.yaml
  centreon/doc/API/v24.04/Configuration/Service/PartialUpdateAndDeleteService.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/PartialUpdateServiceRequest.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostRepository.php
  centreon/src/Core/Service/Application/Exception/ServiceException.php
  centreon/src/Core/Service/Application/Repository/WriteServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/MacroDto.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/MacroFactory.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateService.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceRequest.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidation.php
  centreon/src/Core/Service/Domain/Model/Service.php
  centreon/src/Core/Service/Infrastructure/API/AddService/AddServiceController.php
  centreon/src/Core/Service/Infrastructure/API/PartialUpdateService/PartialUpdateServiceController.php
  centreon/src/Core/Service/Infrastructure/API/PartialUpdateService/PartialUpdateServiceOnPremSchema.json
  centreon/src/Core/Service/Infrastructure/API/PartialUpdateService/PartialUpdateServiceRoute.yaml
  centreon/src/Core/Service/Infrastructure/API/PartialUpdateService/PartialUpdateServiceSaasSchema.json
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceRepository.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Application/Repository/WriteServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbWriteServiceGroupRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostTest.php
  centreon/tests/php/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceTest.php
  centreon/tests/php/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidationTest.php
  centreon/tests/php/Core/Service/Domain/Model/ServiceLightTest.php
Labels: area/backend

#2636 enh(command): add command migration script
  centreon/config/packages/Centreon.yaml
  centreon/phpstan.core.neon
  centreon/src/Core/Command/Application/Repository/ReadCommandRepositoryInterface.php
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/CommandRecordedDto.php
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/MigrateAllCommands.php
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/MigrateAllCommandsPresenterInterface.php
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/MigrateAllCommandsResponse.php
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/MigrationErrorDto.php
  centreon/src/Core/Command/Domain/Model/NewCommand.php
  centreon/src/Core/Command/Infrastructure/Command/Exception/CommandMigrationCommandException.php
  centreon/src/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsCommand.php
  centreon/src/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsPresenter.php
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/ApiWriteCommandRepository.php
  centreon/src/Core/Command/Infrastructure/Repository/DbReadCommandRepository.php
  centreon/src/Core/CommandMacro/Domain/Model/NewCommandMacro.php
  centreon/src/Core/Media/Infrastructure/Repository/DbReadMediaRepository.php
  centreon/tests/php/Core/Command/Application/UseCase/MigrateAllCommands/MigrateAllCommandsTest.php
  centreon/tests/php/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsPresenterStub.php
Labels: area/backend

#2645 fix(UI): Fix cropped horizontal axis tick display
  centreon/packages/ui/src/Graph/LineChart/LineChart.tsx
Labels: area/ui

#2643 fix(api): service group update on PartialUpdateServiceTemplate
  centreon/src/Core/ServiceGroup/Application/Repository/WriteServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbWriteServiceGroupRepository.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#2674 fix(api): service group update on PartialUpdateServiceTemplate (#2643)
  centreon/src/Core/ServiceGroup/Application/Repository/WriteServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbWriteServiceGroupRepository.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#2606 enh (media): Creating API to list medias
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Media/AddAndFindMedia.yaml
  centreon/doc/API/v24.04/Configuration/Media/AddMedia.yaml
  centreon/doc/API/v24.04/Configuration/Media/Schema/FindMediasResponse.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Media/Application/Exception/MediaException.php
  centreon/src/Core/Media/Application/Repository/ReadMediaRepositoryInterface.php
  centreon/src/Core/Media/Application/UseCase/AddMedia/AddMedia.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMedias.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMediasPresenterInterface.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMediasResponse.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/MediaDto.php
  centreon/src/Core/Media/Domain/Model/Media.php
  centreon/src/Core/Media/Domain/Model/NewMedia.php
  centreon/src/Core/Media/Infrastructure/API/FindMedias/FindMediasController.php
  centreon/src/Core/Media/Infrastructure/API/FindMedias/FindMediasPresenter.php
  centreon/src/Core/Media/Infrastructure/API/FindMedias/FindMediasRoute.yaml
  centreon/src/Core/Media/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Media/Infrastructure/Repository/DbReadMediaRepository.php
  centreon/src/Core/Media/Infrastructure/Repository/FileProxyReadMediaRepository.php
  centreon/tests/php/Core/Media/Application/UseCase/MigrateAllMedias/MigrateAllMediasTest.php
  centreon/tests/php/Core/Media/Domain/MediaTest.php
  centreon/tests/php/Core/Media/Domain/NewMediaTest.php
Labels: area/backend

#2685 enh(dashboard): remove version column from dashboard_widgets table
  centreon/src/Centreon/Infrastructure/Platform/PlatformRepositoryRDB.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.2.php
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#2600 fix(Extension) : Issue of modules dependencies on install/update
  centreon/src/CentreonModule/Infrastructure/Source/ModuleSource.php
Labels: area/backend

#2599 fix(Extension) : Issue of modules dependencies on install/update
  centreon/src/CentreonModule/Infrastructure/Source/ModuleSource.php
Labels: area/backend

#2666 enh(Dashboard) : Edit widget: stick dataset header
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/addWidget.styles.ts
Labels: area/ui

#2681 fix(api): suppress duplicates host groups returned by the API
  centreon/src/Centreon/Infrastructure/HostConfiguration/Repository/HostGroupRepositoryRDB.php
Labels: area/backend

#2680 [Backport] enh(dashboard) : resource metric selection chip removal
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- removes metrics item when the delete icon is clicked.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/useMetricsOnly.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#2693 [Backport] fix(dashboard) : Widget quick edition: fix cursors issues (#2626)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/components/DashboardEdit/DashboardEditActions.tsx
Labels: area/ui

#2694 [Backport] enh(dashboard) : widget edition replace add resource by refine filter
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
Labels: area/ui

#2695 [Backport]: enh(UI) : Rich text menu reorganization
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Center when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Center when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Left when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Right when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Aligns -- aligns the text to the Right when the corresponding button was clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Bullet List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 1 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 2 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 3 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 4 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 5 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Heading 6 when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Huge when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Large when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Normal when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Number List when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Block type -- displays Small when the corresponding block type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Editable Rich Text Editor -- displays all elements when RichTextEditor is called with required props.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- Editable Rich Text Editor -- displays all format actions when the format button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- List type -- displays Ordered List when the corresponding list type button is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/RichTextEditor/RichTextEditor.cypress.spec.tsx/Rich Text Editor -- List type -- displays Unordered List when the corresponding list type button is selected.snap.png
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.cypress.spec.tsx
  centreon/packages/ui/src/RichTextEditor/RichTextEditor.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/AlignPicker.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/BlockButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/FormatButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/LinkButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ListButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/MacrosButton.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/ToolbarPlugin.styles.ts
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/UndoRedoButtons.tsx
  centreon/packages/ui/src/RichTextEditor/plugins/ToolbarPlugin/index.tsx
  centreon/packages/ui/src/RichTextEditor/translatedLabels.ts
  centreon/packages/ui/src/components/Menu/Button/MenuButton.tsx
  centreon/packages/ui/src/components/Menu/MenuItem.tsx
  centreon/packages/ui/src/components/Menu/MenuItems.tsx
Labels: area/ui

#2682 enh(UI): Improve legend UI
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/useFilterLines.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/InteractiveValue.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendContent.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/Marker.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/models.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/useLegend.ts
  centreon/packages/ui/src/Graph/LineChart/LineChart.tsx
Labels: area/ui

#2714 fix(upgrade): add missing upgrade for cloud notification
  centreon/www/install/php/Update-23.10.2.php
  centreon/www/install/php/Update-23.10.3.php
Labels: area/backend

#2713 chore(phpstan): add phpstan to CI on Core with level 6
  .github/workflows/web.yml
  centreon/src/Centreon/Domain/Monitoring/Metric/Interfaces/MetricRepositoryInterface.php
  centreon/src/Centreon/Infrastructure/Monitoring/Metric/MetricRepositoryLegacy.php
  centreon/src/Core/Application/Common/UseCase/CreatedResponse.php
  centreon/src/Core/Application/Common/UseCase/MultiStatusResponse.php
  centreon/src/Core/Common/Infrastructure/CommandInitializer.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardPerformanceMetricRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetrics.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/MetaServiceHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
  centreon/src/Core/Metric/Application/UseCase/DownloadPerformanceMetrics/DownloadPerformanceMetricResponse.php
  centreon/src/Core/Metric/Infrastructure/Repository/DbReadMetricRepository.php
  centreon/src/Core/Resources/Application/UseCase/FindResourcesByParent/FindResourcesByParent.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/LoginLoggerInterface.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Model/GroupsMapping.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/Repository/ReadAttributePathRepositoryInterface.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/AttributePath/AttributePathFetcher.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/GroupsMapping.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SecurityAccess/RolesMapping.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Repository/HttpReadAttributePathRepository.php
  centreon/src/Core/ServiceGroup/Infrastructure/API/AddServiceGroup/AddServiceGroupPresenter.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetricsTest.php
Labels: area/backend

#2722 fix(upgrade): add missing upgrade for cloud notification
  centreon/www/install/php/Update-23.10.2.php
Labels: area/backend

#2719 fix(cloud notification): Edit a duplicated rule erase properties of the original
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
Labels: area/backend

#2723 fix(api): fix PATCH /configuration/users/current/parameters
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
Labels: area/backend

#2736 fix(api): fix PATCH /configuration/users/current/parameters [23.04]
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
Labels: area/backend

#2730 fix(cloud notification): Edit a duplicated rule erase properties of the original (#2719)
  centreon/src/Core/Notification/Infrastructure/Repository/DbHostGroupResourceRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbServiceGroupResourceRepository.php
Labels: area/backend

#2735 fix(api): fix PATCH /configuration/users/current/parameters [23.10]
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbReadUserRepository.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbUserFactory.php
Labels: area/backend

#2574 feat(lighthouse): Add Filters (basic/extended) to lighthouse
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays acknowledgement details when an acknowledged state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding action_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding checks menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding fqdn menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding monitoring_server_name menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notes_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notification menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding parent_alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding severity menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays downtime details when the downtime state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with a limit param when the rows per page value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- displays notification column if the cloud notification feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- hides notification column if the cloud notification feature is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays a highlighted row when a resource is in a critical state.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays first part of information when multiple (split by ) are available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in compact mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in extended mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- reoders columns when a drag handle is focused and an arrow is pressed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- reorders columns when a drag handle is focused and an arrow is pressed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- displays the services when the Expand button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sends a request to retrieve all sevices and their parents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sends a request with types service,metaservice.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- enables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sends a request to get all resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sets the column names to the default ones.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sorts columnns by newest duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Tree view  Feature Flag -- displays the tree view icons if the feature is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Tree view  Feature Flag -- hides the tree view icons if the feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Duration column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Last check column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Parent column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Resource column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Tries column is clicked.snap.png
  centreon/lighthouse/package-lock.json
  centreon/lighthouse/package.json
  centreon/lighthouse/src/lighthouseReport.ts
  centreon/lighthouse/src/pages/interactions/resourceStatus/filters.ts
  centreon/pnpm-lock.yaml
Labels: area/ui

#2718 enh(UI): Change dashboard route
  centreon/tests/e2e/features/Dashboards/01-dashboard-creation/index.ts
  centreon/tests/e2e/features/Dashboards/06-dashboard-sharing/index.ts
  centreon/tests/e2e/features/Dashboards/07-dashboard-manage-permissions/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsOverview/DashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardsQuickAccess/DashboardsQuickAccessMenu.tsx
  centreon/www/front_src/src/Dashboards/models.ts
  centreon/www/front_src/src/components/ReactRouter/DeprecatedRoute.tsx
  centreon/www/front_src/src/components/ReactRouter/index.tsx
  centreon/www/front_src/src/reactRoutes/deprecatedRoutes.ts
  centreon/www/front_src/src/reactRoutes/routeMap.ts
Labels: area/ui

#2647 enh(UI): Uniformize metric selection
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a single autocomplete when the corresponding atom is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a warning message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays an error message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays the selected metric when resources are fulfilled and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- removes metrics item when the delete icon is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoWidgets.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/singleMetricPayloadPl.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/singleMetricPayloadRta.json
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/useMetricsOnly.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/addWidget.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/atoms.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-singledata/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/properties.json
Labels: area/ui

#2720 [BACKPORT] enh(UI): Improve legend UI (#2682)
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/useFilterLines.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/InteractiveValue.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendContent.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/Marker.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/models.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/useLegend.ts
  centreon/packages/ui/src/Graph/LineChart/LineChart.tsx
Labels: backport

#2770 enh(dashboards): add uuid to dashboard metrics listing and top bottom widget (#2752)
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsPerformances.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsTop.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindMetricsTop/FindMetricsTop.php
  centreon/src/Core/Dashboard/Application/UseCase/FindMetricsTop/Response/MetricInformationDto.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetrics.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/ResourceMetricDto.php
  centreon/src/Core/Dashboard/Domain/Model/Metric/ResourceMetric.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetrics/FindPerformanceMetricsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindMetricsTop/FindMetricsTopTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetricsTest.php
Labels: backport
