Repository centreon/centreon, pull requests merged in 2023-04, with the labels that each got.

#1238 fix(firewall): add login_page to free firewall
  centreon/config/packages/security.yaml
Labels: area/backend

#1241 FIX(UI): fix dark theme color on menu with the correct color
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in dark theme -- displays the direct child items and highlights the item when hovered in dark theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in dark theme -- expands the menu when the logo is clicked in dark theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in dark theme -- highlights the menu item when double clicked in dark theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in dark theme -- highlights the parent item when the item is clicked in dark theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in dark theme -- matches the current snapshot initial menu in dark theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in light theme -- displays the direct child items and highlights the item when hovered in light theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in light theme -- expands the menu when the logo is clicked in light theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in light theme -- highlights the menu item when double clicked in light theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in light theme -- highlights the parent item when the item is clicked in light theme.snap.png
  centreon/cypress/visual-testing-snapshots/Sidebar.cypress.spec.tsx/Navigation menu in light theme -- matches the current snapshot initial menu in light theme.snap.png
  centreon/www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
  centreon/www/front_src/src/Navigation/Sidebar/Sidebar.cypress.spec.tsx
Labels: area/ui

#1253 fix(myAccount): remove theme selection from my account form
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend

#1244 fix(user) update translation in Centreon Authentication page
  centreon/www/include/configuration/configObject/contact/help.php
Labels: area/backend

#1254 Fix[Installation]: error when accessing to installation wizard (dev-22.10.x)
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/useMain.ts
Labels: area/backend

#1255 Fix[Installation]: error when accessing to installation wizard (dev-22.04.x)
  centreon/www/front_src/src/Main/index.test.tsx
  centreon/www/front_src/src/Main/useMain.ts
Labels: area/backend

#1249 fix(Resources/Check):update behavior of button
  centreon/www/front_src/src/Resources/Actions/Resource/Check/Check.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/Check/IconArrow.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/ResourceActionButton.tsx
Labels: area/ui

#1273 fix(gorgone): getlog ctime filter
  centreon-gorgone/gorgone/modules/core/proxy/hooks.pm
Labels: bug

#1270 fix (monitoring): Improving the response time of real-time service monitoring
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
Labels: area/backend

#1276 enh(openid): Add custom redirect_url - 22.10
  centreon/doc/API/centreon-api-v22.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Application/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenterTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  centreon/www/class/centreonStatistics.class.php
  centreon/www/front_src/src/Authentication/Openid/Form/inputs.ts
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/models.ts
  centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx
  centreon/www/front_src/src/Authentication/Openid/useValidationSchema.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-22.10.8.php
Labels: area/backend

#1283 fix(update): fix update provider_configuration table
  centreon/www/install/php/Update-23.04.0.php
Labels: area/backend

#1280 revert(utf8mb4): rollback of the utf8mb4 changes
  centreon/bin/convert_db_charset_to_utfmb4.php
  centreon/libinstall/CentWeb.sh
  centreon/packaging/centreon.spectemplate
  centreon/packaging/debian/centreon-web.install
  centreon/src/Centreon/Infrastructure/DatabaseConnection.php
  centreon/www/class/centreonDB.class.php
  centreon/www/install/createTables.sql
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/installBroker.sql
Labels: area/backend

#1288 fix (monitoring): Improving the response time of real-time service monitoring
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
Labels: area/backend

#1282 enh(openid): Extend PUT API to save redirect uri
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilder.php
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  centreon/src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/Configuration.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  centreon/tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-22.04.13.php
Labels: area/backend

#1287 fix (monitoring): Improving the response time of real-time service monitoring
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
Labels: area/backend

#1284 fix(autodiscovery) : Fix TextField while debouncing value
  centreon/packages/ui/src/InputField/Text/index.tsx
Labels: area/ui

#1290 fix(UI): Fix row color condition memoization
  .github/actions/npm-publish-package-beta/action.yml
  centreon/packages/ui/src/Listing/Cell/DataCell.tsx
  centreon/packages/ui/src/Listing/Row.tsx
Labels: area/ui

#1279 enh(openid): Add custom redirect_url - 22.10 (#1276)
  centreon/doc/API/centreon-api-v22.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Application/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Domain/OpenId/Model/CustomConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenterTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Infrastructure/OpenId/Builder/DbConfigurationBuilderTest.php
  centreon/www/class/centreonStatistics.class.php
  centreon/www/front_src/src/Authentication/Openid/Form/inputs.ts
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/models.ts
  centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx
  centreon/www/front_src/src/Authentication/Openid/useValidationSchema.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-22.10.8.php
Labels: area/backend

#1294 fix(upgrade): fix SAML configuration and provider_configuration update
  centreon/www/install/php/Update-23.04.0.php
Labels: area/backend

#1295 fix(nagios): bypass metadata usage for nagios server repository
  centreon/src/Centreon/Domain/Entity/NagiosServer.php
  centreon/src/Centreon/Domain/Repository/NagiosServerRepository.php
Labels: area/backend

#1291 enh(openid): Extend GET API to save redirect uri
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/Application/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
  centreon/src/Core/Security/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  centreon/tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  centreon/tests/php/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  centreon/tests/php/Core/Security/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenterTest.php
  centreon/www/install/php/Update-22.04.13.php
Labels: area/backend

#1297 fix(upgrade): rename Update-DB-23.04.0 script
  centreon/www/install/sql/centreon/Update-DB-23.04.0.sql
Labels: area/backend

#1296 enh(openid): Extend CEIP/telemetry to mesure redirect uri usage
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#1304 fix(sql): fix services ACLs request for MYSQL8
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#1303 Fix (export): Fixed export of CSV graphics in the resource status page
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Application/RealTime/UseCase/FindPerformanceMetrics/FindPerformanceMetricPresenterInterface.php
  centreon/src/Core/Application/RealTime/UseCase/FindPerformanceMetrics/FindPerformanceMetricResponse.php
  centreon/src/Core/Application/RealTime/UseCase/FindPerformanceMetrics/FindPerformanceMetrics.php
  centreon/src/Core/Infrastructure/Common/Presenter/DownloadPresenter.php
  centreon/src/Core/Infrastructure/RealTime/Api/DownloadPerformanceMetrics/DownloadPerformanceMetricsController.php
  centreon/src/Core/Infrastructure/RealTime/Api/DownloadPerformanceMetrics/DownloadPerformanceMetricsPresenter.php
  centreon/tests/php/Core/Application/RealTime/UseCase/FindPerformanceMetrics/FindPerformanceMetricResponseTest.php
  centreon/tests/php/Core/Application/RealTime/UseCase/FindPerformanceMetrics/FindPerformanceMetricsTest.php
Labels: area/backend

#1300 enh(openid): Extend UI to add possibility to define redirect uri
  .github/docker/Dockerfile.centreon-web-centos7
  centreon/www/front_src/src/Authentication/Openid/Form/inputs.ts
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/models.ts
  centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx
  centreon/www/front_src/src/Authentication/Openid/useValidationSchema.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
Labels: area/ui

#1306 enh(install): update unattended.sh for 23.04
  centreon/unattended.sh
Labels: area/backend

#1315 fix(open-ticket) ticket creation from widget when priority is left empty
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
Labels: area/backend

#1314 enh(openid): add custom redirect URL - 22.04
  .github/docker/Dockerfile.centreon-web-centos7
  centreon/doc/API/centreon-api-v22.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/Builder/ConfigurationBuilder.php
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfiguration.php
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationResponse.php
  centreon/src/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationRequest.php
  centreon/src/Core/Security/Application/UseCase/FindProviderConfigurations/ProviderResponse/OpenIdProviderResponse.php
  centreon/src/Core/Security/Domain/ProviderConfiguration/OpenId/Model/Configuration.php
  centreon/src/Core/Security/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenter.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/FindOpenIdConfiguration/FindOpenIdConfigurationPresenter.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationController.php
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationSchema.json
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Repository/DbWriteOpenIdConfigurationRepository.php
  centreon/tests/php/Core/Security/Application/ProviderConfiguration/OpenId/UseCase/FindOpenIdConfiguration/FindOpenIdConfigurationTest.php
  centreon/tests/php/Core/Security/Application/UseCase/LoginOpenIdSession/LoginOpenIdSessionTest.php
  centreon/tests/php/Core/Security/Infrastructure/Api/FindProviderConfigurations/ProviderPresenter/OpenIdProviderPresenterTest.php
  centreon/tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Api/UpdateOpenIdConfiguration/UpdateOpenIdConfigurationControllerTest.php
  centreon/www/class/centreonStatistics.class.php
  centreon/www/front_src/src/Authentication/Openid/Form/inputs.ts
  centreon/www/front_src/src/Authentication/Openid/index.test.tsx
  centreon/www/front_src/src/Authentication/Openid/models.ts
  centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx
  centreon/www/front_src/src/Authentication/Openid/useValidationSchema.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-22.04.13.php
Labels: area/backend

#1316 fix[Open Ticket]: Icons not visible with the custom URI
  centreon-open-tickets/widgets/open-tickets/src/toolbar.php
Labels: area/backend

#1319 fix(openid): Fix redirect URL GET response
  centreon/src/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilder.php
  centreon/tests/php/Core/Security/Infrastructure/ProviderConfiguration/OpenId/Builder/DbConfigurationBuilderTest.php
Labels: area/backend

#1320 fix(ad/export): missing check_period_id field is optional
  centreon/www/class/config-generate/abstract/service.class.php
Labels: area/backend

#1317 Fix(UI): Fix OIDC decoder
  centreon/www/front_src/src/Authentication/api/decoders.ts
Labels: area/ui

#1321 fix (Authentication): add log when user is blocked
  centreon/src/Core/Security/ProviderConfiguration/Domain/LoginLoggerInterface.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Logger/LoginLogger.php
  centreon/src/Security/Domain/Authentication/Model/LocalProvider.php
Labels: area/backend

#1329 fix(upgrade): Error WebSSO during upgrade to 22.04
  centreon/src/Security/WebSSOAuthenticator.php
Labels: area/backend

#1334 enh(unattended): Remove Remi repo for EL9
  centreon/unattended.sh
Labels: area/backend

#1346 fix(upgrade): Error WebSSO during upgrade to 23.04
  centreon/src/Security/WebSSOAuthenticator.php
Labels: area/backend

#1349 fix(export/pollers): possibly missing 'proxy_url' array index
  centreon/www/class/config-generate/broker.class.php
Labels: area/backend

#1363 fix(upgrade): Fixed upgrade script 22.10
  centreon/www/install/php/Update-22.10.8.php
Labels: area/backend

#1364 fix(upgrade): Fixed upgrade script 22.04
  centreon/www/install/php/Update-22.04.13.php
Labels: area/backend

#1257 fix(gorgone): mbi unable to rebuild partial data with new scripts (#1…
  centreon-gorgone/gorgone/modules/centreon/mbi/etl/event/main.pm
  centreon-gorgone/gorgone/modules/centreon/mbi/etl/perfdata/main.pm
Labels: bug

#1342 fix(api): correctly display errors when failure on password renew (22.10)
  centreon/src/Centreon/Domain/Common/Assertion/Assertion.php
  centreon/src/Core/Security/User/Application/UseCase/RenewPassword/RenewPassword.php
  centreon/src/Core/Security/User/Domain/Model/UserPasswordFactory.php
Labels: area/backend

#1381 fix(upgrade): remove symfony cache folder before recreating it (Debian)
  centreon/packaging/debian/centreon-web.postinst
Labels: area/backend
