Repository centreon/centreon, pull requests merged in 2023-02, with the labels that each got.

#824 fix: reordering of eventually wrong indexed object keys
  centreon/www/class/config-generate/broker.class.php
Labels: area/backend

#783 Fix(secu): Sanitizing queries in serviceDetails.php
  centreon/www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#835 Fix(e2e): Fix random fail on e2e actions tests
  centreon/packages/ui/src/Listing/Row.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
Labels: area/ui

#821 enh(api): Remove possibility of updating Vault configuration and storage name
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lib/Centreon/Object/Host/Host.php
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/NewVaultConfigurationFactory.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationResponse.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurations.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurationsResponse.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Domain/Model/NewVaultConfiguration.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationSchema.json
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationSchema.json
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbReadVaultConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbVaultConfigurationFactory.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/DbWriteVaultConfigurationRepository.php
  centreon/src/Utility/Interfaces/UUIDGeneratorInterface.php
  centreon/src/Utility/UUIDGenerator.php
  centreon/tests/api/features/VaultConfiguration.feature
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/NewVaultConfigurationFactoryTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfigurations/FindVaultConfigurationsTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Domain/Model/NewVaultConfigurationTest.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/install/createTables.sql
  centreon/www/install/sql/centreon/Update-DB-23.04.0-beta.1.sql
Labels: area/backend

#787 feat(API) add FindServiceCategories endpoint
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/ServiceCategory/Application/Exception/ServiceCategoryException.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindServiceCategories/FindServiceCategories.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindServiceCategories/FindServiceCategoriesResponse.php
  centreon/src/Core/ServiceCategory/Domain/Model/NewServiceCategory.php
  centreon/src/Core/ServiceCategory/Domain/Model/ServiceCategory.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindServiceCategories/FindServiceCategoriesController.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindServiceCategories/FindServiceCategoriesPresenter.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindServiceCategories/FindServiceCategoriesRoute.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ServiceCategory.feature
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/FindServiceCategories/FindServiceCategoriesTest.php
  centreon/tests/php/Core/ServiceCategory/Domain/Model/NewServiceCategoryTest.php
  centreon/tests/php/Core/ServiceCategory/Domain/Model/ServiceCategoryTest.php
Labels: area/backend

#846 enh(core): Use alma9 on e2e
  centreon/tests/e2e/cypress/README.md
  centreon/tests/e2e/package.json
Labels: area/ui

#850 enh (RT): Optimisation of SQL queries to reduce callbacks on the legacy service grid monitoring page
  centreon/www/class/centreonMonitoring.class.php
  centreon/www/include/monitoring/status/Services/xml/serviceGridXML.php
Labels: area/backend

#822 feat(API) add FindServiceSeverities endpoint
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/ServiceSeverity/Application/Exception/ServiceSeverityException.php
  centreon/src/Core/ServiceSeverity/Application/Repository/ReadServiceSeverityRepositoryInterface.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/FindServiceSeverities/FindServiceSeverities.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/FindServiceSeverities/FindServiceSeveritiesResponse.php
  centreon/src/Core/ServiceSeverity/Domain/Model/NewServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Domain/Model/ServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/FindServiceSeverities/FindServiceSeveritiesController.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/FindServiceSeverities/FindServiceSeveritiesPresenter.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/FindServiceSeverities/FindServiceSeveritiesRoute.yaml
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbReadServiceSeverityRepository.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/ServiceSeverity.feature
  centreon/tests/php/Core/ServiceSeverity/Application/UseCase/FindServiceSeverities/FindServiceSeveritiesTest.php
  centreon/tests/php/Core/ServiceSeverity/Domain/Model/NewServiceSeverityTest.php
  centreon/tests/php/Core/ServiceSeverity/Domain/Model/ServiceSeverityTest.php
Labels: area/backend

#605 fix(api): check password only for local user
  centreon/www/class/centreon-clapi/centreonContact.class.php
Labels: area/backend

#872 enh(ui) : add a new component for the menu list
  centreon/packages/ui/src/ActionsList/index.stories.tsx
  centreon/packages/ui/src/ActionsList/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-actions-list-playground-1-snap.png
  centreon/packages/ui/src/index.ts
Labels: area/ui

#877 fix: remove sanitizing in serviceDetails
  centreon/www/include/monitoring/objectDetails/serviceDetails.php
Labels: area/backend

#854 fix(clapi): remove string encoding
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#882 fix(upgrade): Fix Upgrade 22.04.0-beta.1 MySQL8 Compatibility
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-22.04.0-beta.1.php
Labels: area/backend

#794 feat(API) add DeleteServiceCategory and AddServiceCategory
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/ServiceCategory/Application/Exception/ServiceCategoryException.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/AddServiceCategory/AddServiceCategory.php
  centreon/src/Core/ServiceCategory/Application/UseCase/AddServiceCategory/AddServiceCategoryRequest.php
  centreon/src/Core/ServiceCategory/Application/UseCase/AddServiceCategory/AddServiceCategoryResponse.php
  centreon/src/Core/ServiceCategory/Application/UseCase/DeleteServiceCategory/DeleteServiceCategory.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/AddServiceCategory/AddServiceCategoryController.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/AddServiceCategory/AddServiceCategoryPresenter.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/AddServiceCategory/AddServiceCategoryRoute.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/API/AddServiceCategory/AddServiceCategorySchema.json
  centreon/src/Core/ServiceCategory/Infrastructure/API/DeleteServiceCategory/DeleteServiceCategoryController.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/DeleteServiceCategory/DeleteServiceCategoryRoute.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbWriteServiceCategoryRepository.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/ServiceCategory.feature
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/AddServiceCategory/AddServiceCategoryTest.php
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/DeleteServiceCategory/DeleteServiceCategoryTest.php
Labels: area/backend

#827 fix: reordering of eventually wrong indexed object keys
  centreon/www/class/config-generate/broker.class.php
Labels: area/backend

#870 enh(API) change comments for comment in HostCategory and HostSeverity APIs
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryController.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategoryPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/AddHostCategory/AddHostCategorySchema.json
  centreon/src/Core/HostCategory/Infrastructure/API/FindHostCategories/FindHostCategoriesPresenter.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityController.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeverityPresenter.php
  centreon/src/Core/HostSeverity/Infrastructure/API/AddHostSeverity/AddHostSeveritySchema.json
  centreon/src/Core/HostSeverity/Infrastructure/API/FindHostSeverities/FindHostSeveritiesPresenter.php
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/HostSeverity.feature
Labels: area/backend

#788 enh (RT): Optimisation of SQL queries to reduce callbacks on the legacy hosts monitoring page
  centreon/www/class/centreonHost.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/class/centreonXMLBGRequest.class.php
  centreon/www/include/monitoring/status/Hosts/xml/hostXML.php
Labels: area/backend

#832 feat(API) add DeleteServiceSeverity and AddServiceSeverity endpoints
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/ServiceSeverity/Application/Exception/ServiceSeverityException.php
  centreon/src/Core/ServiceSeverity/Application/Repository/ReadServiceSeverityRepositoryInterface.php
  centreon/src/Core/ServiceSeverity/Application/Repository/WriteServiceSeverityRepositoryInterface.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/AddServiceSeverity/AddServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/AddServiceSeverity/AddServiceSeverityRequest.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/AddServiceSeverity/AddServiceSeverityResponse.php
  centreon/src/Core/ServiceSeverity/Application/UseCase/DeleteServiceSeverity/DeleteServiceSeverity.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/AddServiceSeverity/AddServiceSeverityController.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/AddServiceSeverity/AddServiceSeverityPresenter.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/AddServiceSeverity/AddServiceSeverityRoute.yaml
  centreon/src/Core/ServiceSeverity/Infrastructure/API/AddServiceSeverity/AddServiceSeveritySchema.json
  centreon/src/Core/ServiceSeverity/Infrastructure/API/DeleteServiceSeverity/DeleteServiceSeverityController.php
  centreon/src/Core/ServiceSeverity/Infrastructure/API/DeleteServiceSeverity/DeleteServiceSeverityRoute.yaml
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbReadServiceSeverityRepository.php
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbWriteServiceSeverityRepository.php
  centreon/tests/api/features/HostSeverity.feature
  centreon/tests/api/features/ServiceSeverity.feature
  centreon/tests/php/Core/ServiceSeverity/Application/UseCase/AddServiceSeverity/AddServiceSeverityTest.php
  centreon/tests/php/Core/ServiceSeverity/Application/UseCase/DeleteServiceSeverity/DeleteServiceSeverityTest.php
Labels: area/backend

#844 fix(packaging): add missing symfony cache clear
  centreon/packaging/centreon.spectemplate
Labels: area/backend

#816 enh (RT): Optimisation of SQL queries to reduce callbacks on the legacy services monitoring page
  centreon/www/class/centreonHost.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/monitoring/status/Services/xml/serviceXML.php
  centreon/www/include/monitoring/status/Services/xsl/service.xsl
Labels: area/backend

#781 fix(Resource/listing):Some title of columns header are displayed on several lines when no space left
  centreon/tests/e2e/cypress/integration/Resources-status/01-listing/index.ts
  centreon/www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui

#894 fix(ui) : disable confirm action of the duplicate dialog if the input field is empty
  centreon/packages/ui/src/Dialog/Duplicate/index.stories.tsx
  centreon/packages/ui/src/Dialog/Duplicate/index.tsx
  centreon/packages/ui/src/__image_snapshots__/storyshots-test-js-image-story-shots-dialog-duplicate-confirm-disabled-1-snap.png
Labels: area/ui

#828 fix: reordering of eventually wrong indexed object keys
  centreon/www/class/config-generate/broker.class.php
Labels: area/backend

#866 enh (RT): Optimisation of SQL queries to reduce callbacks on the legacy service grid monitoring page
  centreon/package-lock.json
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Listing/Row.tsx
  centreon/www/class/centreonMonitoring.class.php
  centreon/www/include/monitoring/status/Services/xml/serviceGridXML.php
Labels: area/backend

#901 chore(ui version): Update package ui version to 22.10.11
  centreon/package-lock.json
  centreon/packages/ui/package.json
Labels: automerge

#865 fix(eslint): Fix eslint exit code and align eslint format to junit
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/web.yml
  centreon/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
Labels: area/ui

#902 enh(NPM): Clean up and improve NPM publication process (22.10.x)
  .github/actions/get-latest-npm-beta-branch-version/action.yml
  .github/actions/get-latest-npm-beta-branch-version/index.js
  .github/actions/get-latest-npm-beta-branch-version/package-lock.json
  .github/actions/get-latest-npm-beta-branch-version/package.json
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-automerge.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
Labels: area/ui

#905 enh(NPM): Clean up and improve NPM publication process (22.04.x)
  .github/actions/get-latest-npm-beta-branch-version/action.yml
  .github/actions/get-latest-npm-beta-branch-version/index.js
  .github/actions/get-latest-npm-beta-branch-version/package-lock.json
  .github/actions/get-latest-npm-beta-branch-version/package.json
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/npm-publish-package/action.yml
  .github/workflows/js-config-automerge.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/ui-automerge.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-automerge.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
Labels: area/ui

#907 enh(openid): retrieve conditions and groups / roles mapping from token (#890)
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#892 enh(CI/UI): Add publication of storybook
  .github/actions/publish-storybook/action.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-stable.yml
  centreon/packages/ui/src/Home.stories.mdx
Labels: area/ui

#920 fix(CI): Fix Lighthouse report generation
  .github/actions/lighthouse-performance-testing/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/docker/Dockerfile.lighthouse
  .github/scripts/lighthouse-performance-testing.sh
  .github/workflows/docker-builder-test-lighthouse.yml
  .github/workflows/web.yml
  centreon/lighthouse/.swcrc
  centreon/lighthouse/defaults.ts
  centreon/lighthouse/lighthouseReport.ts
  centreon/lighthouse/package-lock.json
  centreon/lighthouse/package.json
  centreon/lighthouse/pages/authentication.ts
  centreon/lighthouse/pages/login.ts
  centreon/lighthouse/pages/resourceStatus.ts
  centreon/lighthouse/src/defaults.ts
  centreon/lighthouse/src/lighthouseReport.ts
  centreon/lighthouse/src/models.ts
  centreon/lighthouse/src/pages/authentication.ts
  centreon/lighthouse/src/pages/login.ts
  centreon/lighthouse/src/pages/resourceStatus.ts
  centreon/lighthouse/tsconfig.json
  centreon/package-lock.json
  centreon/packages/ui/src/Listing/Row.tsx
  centreon/tests/e2e/cypress/integration/Resources-status/02-actions/index.ts
  centreon/tests/e2e/package.json
Labels: area/ui

#922 enh(macros): get formatted macro for services
  centreon/www/class/centreonService.class.php
Labels: area/backend

#928 enh(centreon-ui): Fix map build 2204
  centreon/packages/ui/src/Button/Save/StartIcon.tsx
  centreon/packages/ui/src/ListingPage/index.tsx
Labels: area/ui

#914 fix(upgrade): add missing semicolon
  centreon/www/install/php/Update-22.10.0-beta.1.php
Labels: area/backend

#460 feat(UI): Add e2e Tests on openid connect feature
  .github/actions/cypress-e2e-testing/action.yml
  .github/docker/Dockerfile.openid
  .github/docker/configs/openidrealm.json
  .github/scripts/centreon-web-sso.sh
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-builder-test-openid.yml
  centreon/cypress/visual-testing-snapshots/Header/UserMenu/index.cypress.spec.tsx/User Menu -- expands the popper when the user icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/Header/UserMenu/index.cypress.spec.tsx/User Menu -- using the dark mode.snap.png
  centreon/cypress/visual-testing-snapshots/Header/UserMenu/index.cypress.spec.tsx/User Menu -- using the light mode.snap.png
  centreon/cypress/visual-testing-snapshots/Resources/Graph/Performance/AnomalyDetection/index.cypress.spec.tsx/Anomaly detection - Graph -- displays the threshold when add or minus buttons are clicked on Anomaly detection configuration modal slider.snap.png
  centreon/tests/e2e/cypress.config.ts
  centreon/tests/e2e/cypress.dev.config.ts
  centreon/tests/e2e/cypress/commons.ts
  centreon/tests/e2e/cypress/e2e/Autologin/01-autologin/index.ts
  centreon/tests/e2e/cypress/e2e/Autologin/common.ts
  centreon/tests/e2e/cypress/e2e/Local-authentication/common.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/01-oidc-authentication.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/01-oidc-authentication/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/02-oidc-authentication-only.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/02-oidc-authentication-only/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/03-oidc-authentication-restrictions.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/03-oidc-authentication-restrictions/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/04-oidc-authentication-auto-import.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/04-oidc-authentication-auto-import/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/05-oidc-authentication-acl-groups.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/05-oidc-authentication-acl-groups/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/06-oidc-authentication-contact-groups.feature
  centreon/tests/e2e/cypress/e2e/OpenID-connect/06-oidc-authentication-contact-groups/index.ts
  centreon/tests/e2e/cypress/e2e/OpenID-connect/common.ts
  centreon/tests/e2e/cypress/e2e/Resources-status/01-listing/index.ts
  centreon/tests/e2e/cypress/e2e/Resources-status/02-actions/index.ts
  centreon/tests/e2e/cypress/e2e/Resources-status/common.ts
  centreon/tests/e2e/cypress/e2e/Web-SSO/01-web-sso-authentication.feature
  centreon/tests/e2e/cypress/e2e/Web-SSO/01-web-sso-authentication/index.ts
  centreon/tests/e2e/cypress/e2e/Web-SSO/02-web-sso-authentication-enabled.feature
  centreon/tests/e2e/cypress/e2e/Web-SSO/02-web-sso-authentication-enabled/index.ts
  centreon/tests/e2e/cypress/e2e/Web-SSO/03-web-sso-authentication-only.feature
  centreon/tests/e2e/cypress/e2e/Web-SSO/03-web-sso-authentication-only/index.ts
  centreon/tests/e2e/cypress/e2e/Web-SSO/common.ts
  centreon/tests/e2e/cypress/fixtures/resources/clapi/contact-OIDC/OIDC-authentication-user.json
  centreon/tests/e2e/cypress/fixtures/resources/clapi/contact-web-sso/web-sso-authentication-user.json
  centreon/tests/e2e/cypress/fixtures/users/user-for-web-sso-authentication.json
  centreon/tests/e2e/cypress/fixtures/users/user-non-admin-for-OIDC-authentication.json
  centreon/tests/e2e/cypress/scripts/web-sso-commands.sh
  centreon/tests/e2e/cypress/support/Commands.ts
  centreon/tsconfig.json
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetection.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/TimePeriods/TimePeriods.cypress.spec.tsx
Labels: area/ui

#741 fix[style]: Refacto display of forms centreon web
  centreon/www/Themes/Generic-theme/style.css
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/parameters/backup/formBackup.html
  centreon/www/include/Administration/parameters/centstorage/form.ihtml
  centreon/www/include/Administration/parameters/debug/form.ihtml
  centreon/www/include/Administration/parameters/engine/form.ihtml
  centreon/www/include/Administration/parameters/general/form.ihtml
  centreon/www/include/Administration/parameters/gorgone/gorgone.ihtml
  centreon/www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.html
  centreon/www/include/Administration/parameters/ldap/form.ihtml
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.ihtml
  centreon/www/include/configuration/configNagios/formNagios.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/escalation/formEscalation.ihtml
  centreon/www/include/configuration/configObject/host/formHost.ihtml
  centreon/www/include/configuration/configObject/hostgroup_dependency/formHostGroupDependency.ihtml
  centreon/www/include/configuration/configObject/metaservice_dependency/formMetaServiceDependency.ihtml
  centreon/www/include/configuration/configObject/service/formService.ihtml
  centreon/www/include/monitoring/comments/template/AddComment.html
  centreon/www/include/options/accessLists/actionsACL/formActionsAccess.ihtml
  centreon/www/include/views/componentTemplates/formComponentTemplate.ihtml
  centreon/www/include/views/graphTemplates/formGraphTemplate.ihtml
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.ihtml
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/ui, area/backend

#947 [enh](ldap): add ldap connection timeout to avoid infinite connection (dev-21.10.x)
  centreon/www/class/CentreonLDAPAdmin.class.php
  centreon/www/class/centreonLDAP.class.php
Labels: area/backend

#906 fix(oidc) call the legacy generateFile api through OIDC
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#954 fix(Resource/Anomaly-detection):fix wrong formula of ad variation envelope threshold
  centreon/www/front_src/src/Resources/Graph/Performance/AnomalyDetection/AnomalyDetectionEstimatedEnvelopeThreshold.tsx
Labels: area/ui

#936 fix(downtime): Fix downtimes requests
  centreon/www/class/centreonExternalCommand.class.php
  centreon/www/include/monitoring/downtime/common-Func.php
  centreon/www/include/monitoring/downtime/downtime.php
Labels: area/backend

#953 fix(oidc) call the legacy generateFile api through OIDC
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#941 fix(core): prevent concurrent writes in index.html file
  centreon/www/index.php
Labels: area/backend

#973 enh(export) update key name to tag_name and severity_name in export files (tags.cfg and severities.cfg)
  centreon/www/class/config-generate/hostcategory.class.php
  centreon/www/class/config-generate/hostgroup.class.php
  centreon/www/class/config-generate/servicecategory.class.php
  centreon/www/class/config-generate/servicegroup.class.php
  centreon/www/class/config-generate/severity.class.php
Labels: area/backend

#965 fix(downtime): Fix downtimes requests (#936)
  centreon/www/class/centreonExternalCommand.class.php
  centreon/www/include/monitoring/downtime/common-Func.php
  centreon/www/include/monitoring/downtime/downtime.php
Labels: area/backend

#966 fix(downtime): Fix downtimes requests (#936)
  centreon/www/class/centreonExternalCommand.class.php
  centreon/www/include/monitoring/downtime/common-Func.php
  centreon/www/include/monitoring/downtime/downtime.php
Labels: area/backend

#958 fix(recurrentDowntime): unable to edit a recurrent downtime
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend

#960 fix(recurrentDowntime): unable to edit a recurrent downtime (dev-22.10.x)
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend

#961 fix(recurrentDowntime): unable to edit a recurrent downtime (dev-22.04.x)
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend

#964 fix(downtime): Fix downtimes requests (#936)
  centreon/www/class/centreonExternalCommand.class.php
  centreon/www/include/monitoring/downtime/common-Func.php
  centreon/www/include/monitoring/downtime/downtime.php
Labels: area/backend

#968 fix(addDowntime): fix SQL requests when adding downtime
  centreon/www/class/centreonService.class.php
Labels: area/backend

#999 fix(addDowntime): fix SQL requests when adding downtime (#968)
  centreon/www/class/centreonService.class.php
Labels: area/backend

#1005 fix(UI): popup on services page (#836)
  centreon/www/include/monitoring/status/Services/xsl/service.xsl
Labels: area/backend

#1004 fix(UI): popup on services page (#836)
  centreon/www/include/monitoring/status/Services/xsl/service.xsl
Labels: area/backend

#998 fix(addDowntime): fix SQL requests when adding downtime (#968)
  centreon/www/class/centreonService.class.php
Labels: area/backend

#952 fix(oidc) call the legacy generateFile api through OIDC
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#992 fix(massive-downtime): issue fixed with GET entry
  centreon/www/include/monitoring/external_cmd/popup/massive_downtime.php
  centreon/www/include/monitoring/external_cmd/popup/popup.php
Labels: area/backend

#997 fix(addDowntime): fix SQL requests when adding downtime (#968)
  centreon/www/class/centreonService.class.php
Labels: area/backend

#986 fix(centreon): Fix list host categories with database contains hyphen
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend

#974 fix(conf) allow to update service group without name change
  centreon/www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#975 fix(conf) allow to update escalation without name change
  centreon/www/include/configuration/configObject/escalation/DB-Func.php
Labels: area/backend

#1007 fix(massive-downtime): issue fixed with GET entry (#992)
  centreon/www/include/monitoring/external_cmd/popup/massive_downtime.php
  centreon/www/include/monitoring/external_cmd/popup/popup.php
Labels: area/backend

#993 fix(downtimes): SQL request fixed on downtime action
  centreon/www/include/monitoring/external_cmd/cmdPopup.php
  centreon/www/include/monitoring/external_cmd/functionsPopup.php
Labels: area/backend

#1008 fix(massive-downtime): issue fixed with GET entry (#992)
  centreon/www/include/monitoring/external_cmd/popup/massive_downtime.php
  centreon/www/include/monitoring/external_cmd/popup/popup.php
Labels: area/backend

#1011 fix(downtimes): SQL request fixed on downtime action (#993)
  centreon/www/include/monitoring/external_cmd/cmdPopup.php
  centreon/www/include/monitoring/external_cmd/functionsPopup.php
Labels: area/backend

#1012 fix(downtimes): SQL request fixed on downtime action (#993)
  centreon/www/include/monitoring/external_cmd/cmdPopup.php
  centreon/www/include/monitoring/external_cmd/functionsPopup.php
Labels: area/backend

#1010 fix(downtimes): SQL request fixed on downtime action (#993)
  centreon/www/include/monitoring/external_cmd/cmdPopup.php
  centreon/www/include/monitoring/external_cmd/functionsPopup.php
Labels: area/backend

#1013 fix(conf) allow to update escalation without name change (#975)
  centreon/www/include/configuration/configObject/escalation/DB-Func.php
Labels: area/backend

#988 fix(core): prevent concurrent writes in index.html file
  centreon/www/index.php
Labels: area/backend

#989 fix(core): prevent concurrent writes in index.html file
  centreon/www/index.php
Labels: area/backend

#990 fix(core): prevent concurrent writes in index.html file
  centreon/www/index.php
Labels: area/backend

#959 fix(clapi): don't check expiration for excluded users
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1018 fix(clapi): don't check expiration for excluded users (#959)
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1017 fix(clapi): don't check expiration for excluded users (#959)
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#1014 fix(conf) allow to update service group without name change (#974)
  centreon/www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#1025 fix(popup): use htmlspecialchar instead of HtmlAnalyzer
  centreon/www/include/monitoring/external_cmd/popup/popup.php
Labels: area/backend

#1024 fix(popup): use htmlspecialchar instead of HtmlAnalyzer
  centreon/www/include/monitoring/external_cmd/popup/popup.php
Labels: area/backend

#644 fix(web): update query to get right acl groups and generate graph
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#924 fix(clapi) update the updated column when poller reload/restart
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: area/backend

#994 fix(conf): improve performance querying service group relations with ACL
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#991 [enh]: configure mariadb with utf8mb4 by default
  centreon/src/Centreon/Infrastructure/DatabaseConnection.php
  centreon/tools/convert_db_charset_to_utfmb4.php
  centreon/www/class/centreonDB.class.php
  centreon/www/install/createTables.sql
  centreon/www/install/createTablesCentstorage.sql
Labels: area/backend

#1019 docs(host): change the host template field form description
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/img/misc/multiple-templates2.png
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/help.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#809 fix(web): fix force check in host/service details tab
  centreon/www/include/monitoring/objectDetails/xml/hostSendCommand.php
  centreon/www/include/monitoring/objectDetails/xml/serviceSendCommand.php
Labels: area/backend
