Repository centreon/centreon, pull requests merged in 2024-01, with the labels that each got.

#2678 Add gherkin command migration script
  centreon/tests/e2e/features/Migration-scripts/01-command.feature
Labels: area/test

#2851 fix(configuration): Export configuration failing due to method call by reference after upgrade (#2843) [dev-23.10.x]
  centreon/www/class/config-generate/escalation.class.php
Labels: area/backend

#2853 fix(configuration): Export configuration failing due to method call by reference after upgrade (#2843) [dev-23.04.x]
  centreon/www/class/config-generate/escalation.class.php
Labels: area/backend

#2895 fix(resource status): Bad redirection in Host's Services tab (#2861) [dev-23.10.x]
  centreon/www/front_src/src/Resources/Details/tabs/Services/List.tsx
Labels: area/ui

#2896 fix(resource status): Bad redirection in Host's Services tab (#2861) [dev-23.04.x]
  centreon/www/front_src/src/Resources/Details/tabs/Services/List.tsx
Labels: area/ui

#2910 fix(Event Logs): csv extract not working with "log period" (#2905) [dev-23.04.x]
  centreon/www/include/eventLogs/export/Request.php
Labels: area/backend

#2911 fix(Event Logs): csv extract not working with "log period" (#2905) [dev-23.10.x]
  centreon/www/include/eventLogs/export/Request.php
Labels: area/backend

#2914 fix(install): correctly check user rights on step7 (#2907)
  centreon/www/install/steps/process/createDbUser.php
Labels: area/backend

#2913 fix(install): correctly check user rights on step7 (#2907)
  centreon/www/install/steps/process/createDbUser.php
Labels: area/backend

#3025 fix(access groups) : Remove access to groups for contact management
  centreon/www/class/centreonACL.class.php
  centreon/www/include/configuration/configObject/contactgroup/DB-Func.php
  centreon/www/include/configuration/configObject/contactgroup/formContactGroup.ihtml
  centreon/www/include/configuration/configObject/contactgroup/formContactGroup.php
Labels: area/backend

#2846 fix(openid): reflect real value of username [23.04]
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
Labels: area/backend

#3017 fix(api/notification): correction of contact and contact group inheritance
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/host.class.php
  centreon/www/class/config-generate/service.class.php
Labels: area/backend

#3018 fix(api/notification): correction of contact and contact group inheri…
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/host.class.php
  centreon/www/class/config-generate/service.class.php
Labels: area/backend

#3035 enh(dashboard): add shares to dashboard listing and details (#3026)
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardShareRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardFactory.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboard/FindDashboardResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboards.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/FindDashboardsFactory.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboards/Response/DashboardResponseDto.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
Labels: backport

#2857 fix(administration) : Make the users not created on centreon plateform unenabled to edit their profile information
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
Labels: area/backend, backport

#2924 enh(UI): Refactor access rights form
  centreon/packages/ui/.storybook/preview.tsx
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- adds the contact as viewer when a contact is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- adds the contact group as editor when a contact group is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- clears the autocomplete when a contact is selected and the contact type is changed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays a removed chip when the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays statistics when a contact is added, a contact is updated and a contact is removed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights in loading state.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights with an empty list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights without link.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- removes the contact from the list when the contact has been to the list and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- removes the updated chip when the contact role is updated and its initial role is assigned back.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- restores the contact when the contact is removed and the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- retrieves contact groups when the contact group radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- retrieves contacts when the contact radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list with the updated contact.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list without the removed contact.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/public/mockServiceWorker.js
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/Module/LicensedModule/LicenseCheck/index.tsx
  centreon/packages/ui/src/Module/LicensedModule/index.tsx
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.stories.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/Actions.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/Actions.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/useActions.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/Item.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/List.styles.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/List.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/ListItemSkeleton.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/ListSkeleton.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/RemoveAccessRight.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/StateChip.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/useItem.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/Provider.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ContactSwitch.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ShareInput.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ShareInput.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/useShareInput.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Stats/Stats.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/atoms.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/common/RoleSelectField.styles.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/common/RoleSelectField.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/models.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/storiesData.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/useAccessRightsInitValues.ts
  centreon/packages/ui/src/components/Form/index.ts
  centreon/packages/ui/src/components/List/Item/ListItem.styles.ts
  centreon/packages/ui/src/components/List/Item/ListItem.tsx
  centreon/packages/ui/src/components/List/Item/Text.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/components/FederatedComponents/index.tsx
Labels: area/ui

#3024 fix(Cloud notifications): Absence of cloud notification entry in topology upon upgrade
  centreon/www/install/php/Update-23.10.4.php
  centreon/www/install/php/Update-23.10.5.php
Labels: area/backend

#2965 fix(install): fixed superfluous id addition in 40-gorgoned.yaml
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: bug

#3039 enh(UI): Refactor access rights form
  centreon/packages/ui/.storybook/preview.tsx
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- adds the contact as viewer when a contact is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- adds the contact group as editor when a contact group is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- clears the autocomplete when a contact is selected and the contact type is changed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays a removed chip when the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays statistics when a contact is added, a contact is updated and a contact is removed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights in loading state.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights with an empty list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights without link.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- removes the contact from the list when the contact has been to the list and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- removes the updated chip when the contact role is updated and its initial role is assigned back.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- restores the contact when the contact is removed and the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- retrieves contact groups when the contact group radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- retrieves contacts when the contact radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list with the updated contact.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list without the removed contact.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/public/mockServiceWorker.js
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/Module/LicensedModule/LicenseCheck/index.tsx
  centreon/packages/ui/src/Module/LicensedModule/index.tsx
  centreon/packages/ui/src/Typography/Subtitle.tsx
  centreon/packages/ui/src/api/useMutationQuery/index.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.stories.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/AccessRights.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/Actions.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/Actions.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Actions/useActions.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/Item.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/List.styles.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/List.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/ListItemSkeleton.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/ListSkeleton.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/RemoveAccessRight.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/StateChip.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/List/useItem.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/Provider.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ContactSwitch.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ShareInput.styles.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/ShareInput.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/ShareInput/useShareInput.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/Stats/Stats.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/atoms.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/common/RoleSelectField.styles.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/common/RoleSelectField.tsx
  centreon/packages/ui/src/components/Form/AccessRightsV2/models.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/storiesData.ts
  centreon/packages/ui/src/components/Form/AccessRightsV2/useAccessRightsInitValues.ts
  centreon/packages/ui/src/components/Form/index.ts
  centreon/packages/ui/src/components/List/Item/ListItem.styles.ts
  centreon/packages/ui/src/components/List/Item/ListItem.tsx
  centreon/packages/ui/src/components/List/Item/Text.tsx
  centreon/packages/ui/src/index.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/components/FederatedComponents/index.tsx
Labels: backport

#3034 chore(phpstan): fix a few phpdoc issues
  centreon/www/api/class/webService.class.php
  centreon/www/class/centreonCommand.class.php
  centreon/www/class/centreonHost.class.php
Labels: area/backend

#3022 fix(Dashboards) : change sort order to desc in Status Grid widget
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
Labels: area/ui

#3023 enh(Dashboards) : add unhandled problems filter to Status Grid widget
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
Labels: area/ui

#2845 fix(openid): reflect real value of username [23.10]
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Security/Domain/Authentication/Interfaces/OpenIdProviderInterface.php
Labels: area/backend

#3048 feat([App token]): Create a basic token
  centreon/cypress/fixtures/apiTokens/creation/configuredUsers.json
  centreon/cypress/fixtures/apiTokens/creation/generatedTokenWithDefaultDuration.json
  centreon/cypress/fixtures/apiTokens/list.json
  centreon/cypress/fixtures/apiTokens/listPage2.json
  centreon/cypress/fixtures/apiTokens/listing/list.json
  centreon/cypress/fixtures/apiTokens/listing/listPage2.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/TokenListing/TokenListing.cypress.spec.tsx/Api-token listing -- displays all tokens when the page loads.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/TokenListing/TokenListing.cypress.spec.tsx/Api-token listing -- enables the addition and removal of columns in the table listing when the user selects or deselects options in the Add Columns menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- displays all tokens when the page loads.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- displays an updated Create token button that becomes enabled when the required inputs are filled in.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- displays an updated modal when generating a token.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- displays the modal when clicking on token creation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- displays the token creation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/Api-token -- enables the addition and removal of columns in the table listing when the user selects or deselects options in the Add Columns menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/token input with displayed password.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx/token input with encrypted password.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/Button/Save/index.tsx
  centreon/packages/ui/src/Dialog/index.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/index.tsx
  centreon/packages/ui/src/InputField/Text/index.tsx
  centreon/packages/ui/src/TimePeriods/DateTimePickerInput.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/CustomTimePeriod/ActionsList.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/CustomTimePeriod/CustomTimePeriod.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/CustomTimePeriod/InvisibleField.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/EndAdornment.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/Title.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationButton.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationDialog.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenInput.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/atoms.ts
  centreon/www/front_src/src/ApiTokens/TokenCreation/models.ts
  centreon/www/front_src/src/ApiTokens/TokenCreation/tokenCreation.styles.ts
  centreon/www/front_src/src/ApiTokens/TokenCreation/useCreateToken.ts
  centreon/www/front_src/src/ApiTokens/TokenCreation/useTokenFormValues.ts
  centreon/www/front_src/src/ApiTokens/TokenCreation/utils.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Actions.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/TokenListing.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/models.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/tokenListing.styles.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/useTokenListing.ts
  centreon/www/front_src/src/ApiTokens/api/decoder.ts
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
  centreon/www/front_src/src/ApiTokens/apiTokens.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/index.tsx
  centreon/www/front_src/src/ApiTokens/translatedLabels.ts
  centreon/www/front_src/src/ApiTokens/useRefetch.ts
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui

#3054 chore(phpstan): setup phpstan on centreon-dsm
  .github/workflows/dsm.yml
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-dsm/phpstan.neon
  centreon-dsm/www/modules/centreon-dsm/statistics/centreonDSMStats.class.php
Labels: area/backend

#3082 fix(component tests) : fix top bottom widget component tests
  centreon/cypress/fixtures/Widgets/Graph/topBottom.json
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/TopBottom -- displays the widget.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/TopBottom -- does not display the labels when the corresponding setting is disabled.snap.png
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
Labels: area/ui

#3112 fix(clapi): exclude ldap user from password expiration [22.10]
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#3108 fix(legacy): escape fields (2204)
  centreon/www/include/configuration/configObject/host/listHost.ihtml
Labels: area/backend

#3129 enh(api): add ezv rest api provider [2210]
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/EasyVistaRestProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/templates/conf_container1extra.ihtml
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/templates/handle_ci.ihtml
Labels: area/backend

#3133 fix(configuration/cloud): various issues fixed
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/listServiceByHost.php
Labels: area/backend

#2839 fix(legacy): prepare insteadof queries [23.04]
  centreon/lib/Centreon/Object/Object.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  centreon/www/api/class/centreon_monitoring_externalcmd.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#3142 Fix(UI): Fix cancelled API calls
  centreon/packages/ui/src/api/useFetchQuery/index.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboardsContactGroups.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboardsContacts.ts
Labels: area/ui

#3144 Fix(UI): Remove cancelled API calls
  centreon/packages/ui/src/api/useFetchQuery/index.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboardsContactGroups.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboardsContacts.ts
Labels: backport

#3145 enh(map): don't delete widgets php and ts files
  .github/workflows/web.yml
Labels: area/ui

#3147 enh(UI): Add feature flag for playlist
  centreon/config/features.json
  centreon/packages/ui-context/src/types.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/front_src/src/components/ReactRouter/index.tsx
  centreon/www/front_src/src/federatedModules/models.ts
Labels: area/ui, area/backend

#3074 fix(api) Fix FindUsers for non admin users (#2786) (#2830) (#3055)
  centreon/config/routes/Centreon/user.yaml
  centreon/config/routes/centreon.yaml
  centreon/doc/API/centreon-api-v22.04.yaml
  centreon/doc/API/v22.04/Configuration/Users/Schema/User.Listing.yaml
  centreon/doc/API/v22.04/Configuration/Users/Users.yaml
  centreon/src/Core/User/Application/Exception/UserException.php
  centreon/src/Core/User/Application/Repository/ReadUserRepositoryInterface.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsers.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsersPresenterInterface.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsersResponse.php
  centreon/src/Core/User/Application/UseCase/FindUsers/UserDto.php
  centreon/src/Core/User/Domain/Model/User.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersController.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersPresenter.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersRoute.yaml
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
  centreon/tests/api/features/ConfigurationUsers.feature
  centreon/tests/php/Core/User/Application/UseCase/FindUsers/FindUsersTest.php
  centreon/tests/php/Core/User/Domain/Model/UserTest.php
  centreon/tests/php/Core/User/Infrastructure/API/FindUsers/FindUsersPresenterStub.php
Labels: area/backend

#3058 fix(api) Fix FindUsers for non admin users (#2786) (#2830) (#3055)
  centreon/config/routes/Centreon/user.yaml
  centreon/doc/API/centreon-api-v22.10.yaml
  centreon/doc/API/v22.10/Configuration/Users/Schema/User.Listing.yaml
  centreon/doc/API/v22.10/Configuration/Users/Users.yaml
  centreon/src/Core/User/Application/Exception/UserException.php
  centreon/src/Core/User/Application/Repository/ReadUserRepositoryInterface.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsers.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsersPresenterInterface.php
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsersResponse.php
  centreon/src/Core/User/Application/UseCase/FindUsers/UserDto.php
  centreon/src/Core/User/Domain/Model/User.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersController.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersPresenter.php
  centreon/src/Core/User/Infrastructure/API/FindUsers/FindUsersRoute.yaml
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
  centreon/tests/api/features/ConfigurationUsers.feature
  centreon/tests/php/Core/User/Application/UseCase/FindUsers/FindUsersTest.php
  centreon/tests/php/Core/User/Domain/Model/UserTest.php
  centreon/tests/php/Core/User/Infrastructure/API/FindUsers/FindUsersPresenterStub.php
Labels: area/backend

#3072 enh(dashboards): split resource name in parent name and name (#3066)
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsPerformances.yaml
  centreon/doc/API/v23.10/Configuration/Dashboard/Schema/Dashboard.MetricsTop.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindMetricsTop/FindMetricsTop.php
  centreon/src/Core/Dashboard/Application/UseCase/FindMetricsTop/Response/MetricInformationDto.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetrics.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/ResourceMetricDto.php
  centreon/src/Core/Dashboard/Domain/Model/Metric/ResourceMetric.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetrics/FindPerformanceMetricsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
  centreon/tests/api/features/DashboardWithOpenApi.feature
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindMetricsTop/FindMetricsTopTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetricsTest.php
  centreon/www/widgets/src/centreon-widget-topbottom/src/MetricTop.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/api/decoder.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/models.ts
Labels: backport

#3075 chore(phpstan): setup phpstan on centreon-open-tickets
  .github/workflows/open-tickets.yml
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon-open-tickets/phpstan.neon
  centreon-open-tickets/phpstan.stub
  centreon-open-tickets/widgets/open-tickets/index.php
  centreon-open-tickets/widgets/open-tickets/src/action.php
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/toolbar.php
  centreon-open-tickets/www/modules/centreon-open-tickets/class/automatic.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/class/centreonDBManager.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/class/request.php
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Abstract/AbstractProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/BmcFootprints11/BmcFootprints11Provider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/BmcItsm/BmcItsmProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/EasyVistaRestProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyvistaSoap/EasyvistaSoapProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Glpi/GlpiProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Itop/ItopProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Itop/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Jira/JiraProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Mail/MailProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Otrs/OtrsProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/RequestTracker2/RequestTracker2Provider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Serena/SerenaProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/ServiceNow/ServiceNowProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Simple/SimpleProvider.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/logs/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/closeTicket.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/scheduleCheck.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/serviceAck.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/webServices/rest/centreon_openticket.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/webServices/rest/centreon_openticket_history.class.php
  centreon-open-tickets/www/modules/centreon-open-tickets/widgets/Params/Connector/OpenTicketsRule.class.php
Labels: area/backend

#3141 fix: feature_flags were not taken into account
  centreon/www/include/options/accessLists/menusACL/formMenusAccess.php
Labels: area/backend

#3090 chore(smarty): remove smarty deprecated tags
  centreon/www/include/configuration/configKnowledge/display-hostTemplates.php
  centreon/www/include/configuration/configKnowledge/display-hosts.php
  centreon/www/include/configuration/configKnowledge/display-serviceTemplates.php
  centreon/www/include/configuration/configKnowledge/display-services.php
  centreon/www/include/configuration/configKnowledge/functions.php
  centreon/www/include/configuration/configKnowledge/templates/display.ihtml
Labels: area/backend

#3070 chore(phpstan): setup phpstan on centreon-awie
  .github/workflows/awie.yml
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-awie/phpstan.neon
  centreon-awie/phpstan.stub
  centreon-awie/www/modules/centreon-awie/class/ClapiObject.class.php
  centreon-awie/www/modules/centreon-awie/class/Export.class.php
  centreon-awie/www/modules/centreon-awie/class/ZipAndDownload.class.php
  centreon-awie/www/modules/centreon-awie/core/generateExport.php
  centreon-awie/www/modules/centreon-awie/core/launchImport.php
Labels: area/backend

#2836 fix(legacy): prepare insteadof queries [23.10]
  centreon/lib/Centreon/Object/Object.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php
  centreon/www/api/class/centreon_monitoring_externalcmd.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#2624 enh(event logs): add possibility to display ack dt comments notifications event handler
  centreon/www/include/eventLogs/export/Formatter.php
  centreon/www/include/eventLogs/export/QueryGenerator.php
  centreon/www/include/eventLogs/export/Request.php
  centreon/www/include/eventLogs/export/data.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#3170 enh(resource-access): handle dynamicaly the datasetfilters
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ResourceAccess/Application/Exception/RuleException.php
  centreon/src/Core/ResourceAccess/Application/Providers/DatasetProviderInterface.php
  centreon/src/Core/ResourceAccess/Application/Providers/HostCategoryProvider.php
  centreon/src/Core/ResourceAccess/Application/Providers/HostGroupProvider.php
  centreon/src/Core/ResourceAccess/Application/Providers/HostProvider.php
  centreon/src/Core/ResourceAccess/Application/Providers/MetaServiceProvider.php
  centreon/src/Core/ResourceAccess/Application/Providers/ServiceCategoryProvider.php
  centreon/src/Core/ResourceAccess/Application/Providers/ServiceGroupProvider.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteDatasetRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleValidation.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRules.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/AbstractDatasetFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilter.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterTypeInterface.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterValidator.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/HostCategoryFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/HostFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/HostGroupFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/MetaServiceFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/ServiceCategoryFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/ServiceFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/ServiceGroupFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilterTypeConverter.php
  centreon/src/Core/ResourceAccess/Domain/Model/NewRule.php
  centreon/src/Core/ResourceAccess/Domain/Model/Rule.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRuleSchema.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostCategoryRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostGroupRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteMetaServiceRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteServiceCategoryRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteServiceGroupRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbDatasetFilterFactory.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbRuleFactory.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteRuleRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesTest.php
  centreon/tests/php/Core/ResourceAccess/Domain/Model/Dataset/DatasetFilterValidatorTest.php
  centreon/tests/php/Core/ResourceAccess/Domain/Model/DatasetFilterTest.php
  centreon/tests/php/Core/ResourceAccess/Domain/Model/RuleTest.php
Labels: area/backend

#3050 enh(UI-: Refactor children props on ConfirmationTooltip
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/ConfirmationTooltip.stories.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/ConfirmationTooltip.tsx
  centreon/packages/ui/src/components/Tooltip/ConfirmationTooltip/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/MorePanelActions.tsx
Labels: area/ui

#3099 fix(api) fix downtime recuperation when getting a service resource detail
  centreon/src/Core/Infrastructure/RealTime/Repository/Service/DbServiceFactory.php
Labels: area/backend

#3109 chore(smarty): remove the support of the deprecated tag {php}
  centreon/GPL_LIB/smarty-plugins/compiler.displaysvg.php
  centreon/GPL_LIB/smarty-plugins/compiler.pagination.php
  centreon/GPL_LIB/smarty-plugins/compiler.php.php
  centreon/composer.json
Labels: area/backend

#3057 fix(UI): Cannot clear number inputs
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the default value as placeholder when the field as default value.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the fallback value as placeholder when the field as no default value.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the fallback value when the field is cleared out.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the field using auto size.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the placeholder when the field has no default or fallback values.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- sets the value to the minimum value configured when a value less than the minimum value is typed in the field.snap.png
  centreon/packages/ui/src/InputField/Number/Number.cypress.spec.tsx
  centreon/packages/ui/src/InputField/Number/Number.stories.tsx
  centreon/packages/ui/src/InputField/Number/Number.tsx
  centreon/packages/ui/src/InputField/Search/index.tsx
  centreon/packages/ui/src/InputField/Text/index.tsx
  centreon/packages/ui/src/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/useRefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.tsx
Labels: area/ui

#3078 enh(UI): Add support for shares in dashboard list
  centreon/cypress/fixtures/Dashboards/dashboards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays all dashboard columns in the View as list when the user has editor global roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- does not display actions in the View as list when the user has viewer global role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- displays shares when a row is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- revokes the acces right when a row is expanded and.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays column configuration button only in View as list.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays the dashboards in View as list when the corresponding button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useCreateAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useCreateAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/api/useDeleteAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useDeleteAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/Actions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/useActions.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Share.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/useColumns.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Listing.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/atom.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/useListing.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/utils.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
Labels: area/ui

#3189 fix(UI): Cannot clear number inputs
  centreon/cypress/fixtures/Widgets/Graph/topBottom.json
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the default value as placeholder when the field as default value.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the fallback value as placeholder when the field as no default value.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the fallback value when the field is cleared out.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the field using auto size.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- displays the placeholder when the field has no default or fallback values.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Number/Number.cypress.spec.tsx/Number field -- sets the value to the minimum value configured when a value less than the minimum value is typed in the field.snap.png
  centreon/packages/ui/src/InputField/Number/Number.cypress.spec.tsx
  centreon/packages/ui/src/InputField/Number/Number.stories.tsx
  centreon/packages/ui/src/InputField/Number/Number.tsx
  centreon/packages/ui/src/InputField/Search/index.tsx
  centreon/packages/ui/src/InputField/Text/index.tsx
  centreon/packages/ui/src/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/useRefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
Labels: backport

#2877 feat(dashboard) : add link to RS page from widgets
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetric.json
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetrics.json
  centreon/cypress/fixtures/Widgets/Graph/topBottom.json
  centreon/tests/e2e/features/Dashboards/09-widget-single-metric-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/12-status-grid-widget-configuration/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/api/decoders.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGrid.styles.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/Tile.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/models.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/testUtils.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/utils.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/MetricTop.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.styles.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/api/decoder.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/models.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#3062 fix(UI): Ignore 404 responses when retrieving metrics endpoint
  centreon/www/widgets/src/centreon-widget-statusgrid/src/Tooltip/useServiceTooltipContent.ts
Labels: area/ui

#3195 enh(UI): Add support for shares in dashboard list (#3078)
  centreon/cypress/fixtures/Dashboards/dashboards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays all dashboard columns in the View as list when the user has editor global roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- does not display actions in the View as list when the user has viewer global role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- displays shares when a row is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- revokes the acces right when a row is expanded and.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays column configuration button only in View as list.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays the dashboards in View as list when the corresponding button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Listing/Listing.cypress.spec.tsx
  centreon/packages/ui/src/Listing/index.stories.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/packages/ui/src/components/Modal/ModalActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useCreateAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useCreateAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/api/useDeleteAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useDeleteAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateAccessRightsContact.ts
  centreon/www/front_src/src/Dashboards/api/useUpdateAccessRightsContactGroup.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/Actions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/useActions.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Share.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/useColumns.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Listing.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/atom.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/useListing.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/utils.ts
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
Labels: backport

#3102 fix(traps) fix shell commands
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/backend

#3103 fix(export) fix shell command
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#3196 fix(dashboards) : error when deleting a dashboard
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/DeleteDashboard.tsx
Labels: area/ui

#3089 enh(UI): Add pictogram on widgets
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time period disabled -- displays the time period field as disabled when the user is not allowed to edit field.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Checboxes/Checkboxes.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Checboxes/Chekboxes.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Radio/Radio.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Radio/Radio.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/SingleMetricGraphType/OptionCard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/SingleMetricGraphType/SingleMetricGraphType.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Switch.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TextField.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/ValueFormat/ValueFormat.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetSelection.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useCanEditDashboard.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-generictext/properties.json
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
  centreon/www/widgets/src/centreon-widget-topbottom/properties.json
Labels: area/ui

#3175 fix(Resource Status): bad redirection to Reporting > Availability > Services
  centreon/www/include/reporting/dashboard/viewServicesLog.php
Labels: area/backend

#3200 enh(UI): Add pictogram on widgets (#3089)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time period disabled -- displays the time period field as disabled when the user is not allowed to edit field.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Checboxes/Checkboxes.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Checboxes/Chekboxes.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Radio/Radio.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Radio/Radio.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RefreshInterval/RefreshInterval.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/SingleMetricGraphType/OptionCard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/SingleMetricGraphType/SingleMetricGraphType.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Switch.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TextField.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Threshold/Threshold.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/Tiles.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/ValueFormat/ValueFormat.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetSelection.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/hooks/useCanEditDashboard.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-generictext/properties.json
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
  centreon/www/widgets/src/centreon-widget-topbottom/properties.json
Labels: backport

#2916 fix(gorgone): backport 22.10 - Gorgone stops responding every 24-48 hrs with pull mode
  centreon-gorgone/gorgone/modules/core/pull/class.pm
  centreon-gorgone/gorgone/modules/core/pullwss/class.pm
Labels: backport

#3197 fix(traps) fix shell commands (#3102)
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/backend, backport

#3198 fix(export) fix shell command (#3103)
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend, backport

#3091 enh(UI): Move "Show description" slider
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetricRenderer.tsx
  centreon/www/widgets/src/translatedLabels.ts
Labels: area/ui

#3201 fix(monitoring): fix GROUP BY Condition compatibility on MySQL8 (#3137)
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: backport

#3191 enh (service): new API-type repositories for services
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Common/Infrastructure/Repository/ApiRepositoryTrait.php
  centreon/src/Core/Service/Application/Repository/ReadServiceRepositoryInterface.php
  centreon/src/Core/Service/Domain/Model/TinyService.php
  centreon/src/Core/Service/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Service/Infrastructure/Repository/ApiReadServiceRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/TinyServiceFactory.php
Labels: area/backend

#3206 enh(UI): Move "Show description" slider (#3091)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Dashboard.cypress.spec.tsx
Labels: backport

#3101 enh(UI): Add sortable columns on dashboards list (creator, date of creation and date of last update)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- revokes the access right when a row is expanded and the corresponding action is clicked.snap.png
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/useColumns.tsx
Labels: area/ui

#3213 enh(UI): Add sortable columns on dashboards list (creator, date of creation and date of last update)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- revokes the access right when a row is expanded and the corresponding action is clicked.snap.png
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/useColumns.tsx
Labels: backport

#3114 enh(UI): Remove "worst status" tooltip on status grid
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
Labels: area/ui

#3215 enh(UI): Remove "worst status" tooltip on status grid (#3114)
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
Labels: backport

#3214 [Backport] feat(dashboards) : add link to resource status page to the resources based widgets
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetric.json
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetrics.json
  centreon/cypress/fixtures/Widgets/Graph/topBottom.json
  centreon/tests/e2e/features/Dashboards/09-widget-single-metric-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/12-status-grid-widget-configuration/index.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/api/decoders.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGrid.styles.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/Tile.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/models.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/testUtils.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/utils.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/MetricTop.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.styles.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/api/decoder.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/models.ts
  centreon/www/widgets/src/utils.ts
Labels: backport

#3098 feat(AddComment):[Resource Status] Add action button in Timeline panel of resources
  centreon/cypress/fixtures/resources/details/tabs/timeLine/timeLine.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- Submit the comment by typing in the comment area and clicking the Save button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- displays the comment area when clicking on Add a comment button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- displays the timeLine tab when clicking on TimeLine title.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- hides the comment area when clicking on Cancel button.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/Addcomment/AddCommentArea.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/Addcomment/addComment.styles.ts
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/Addcomment/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/ExportToCsv.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#3154 fix(monitoring) fix severities listing when user non-admin
  centreon/src/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategory.php
  centreon/src/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategory.php
  centreon/src/Core/Severity/RealTime/Application/Repository/ReadSeverityRepositoryInterface.php
  centreon/src/Core/Severity/RealTime/Application/UseCase/FindSeverity/FindSeverity.php
  centreon/src/Core/Severity/RealTime/Infrastructure/Repository/DbReadSeverityRepository.php
  centreon/src/Core/Tag/RealTime/Application/Repository/ReadTagRepositoryInterface.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbReadTagRepository.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbTagFactory.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryTest.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryTest.php
  centreon/tests/php/Core/Severity/RealTime/Application/UseCase/FindSeverity/FindSeverityTest.php
Labels: area/backend

#3188 enh (host): new API-type repositories for hosts
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Common/Infrastructure/Repository/AbstractRepositoryRDB.php
  centreon/src/Core/Host/Application/Repository/ReadHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/FindHosts/FindHosts.php
  centreon/src/Core/Host/Domain/Model/SmallHost.php
  centreon/src/Core/Host/Domain/Model/TinyHost.php
  centreon/src/Core/Host/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Host/Infrastructure/Repository/ApiReadHostRepository.php
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/Host/Infrastructure/Repository/SmallHostFactory.php
  centreon/src/Core/Host/Infrastructure/Repository/TinyHostFactory.php
  centreon/tests/php/Core/Host/Application/UseCase/FindHosts/FindHostsTest.php
  centreon/tests/php/Core/Host/Domain/Model/SmallHostTest.php
Labels: area/backend

#3224 fix(UI): Fix cannot display dashboard in playlist
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/DashboardLayout.cypress.spec.tsx/DashboardLayout -- displays the dashboard from a standalone component.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/DashboardLayout.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/index.tsx
Labels: area/ui

#3209 enh (media): new API-type repositories for medias
  centreon/src/Core/Media/Application/Repository/ReadMediaRepositoryInterface.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMedias.php
  centreon/src/Core/Media/Application/UseCase/MigrateAllMedias/MigrateAllMedias.php
  centreon/src/Core/Media/Application/UseCase/MigrateAllMedias/MigrationAllMediasResponse.php
  centreon/src/Core/Media/Domain/Model/Media.php
  centreon/src/Core/Media/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Media/Infrastructure/Repository/ApiReadMediaRepository.php
  centreon/src/Core/Media/Infrastructure/Repository/ApiWriteMediaRepository.php
  centreon/src/Core/Media/Infrastructure/Repository/DbReadMediaRepository.php
  centreon/src/Core/Media/Infrastructure/Repository/FileProxyReadMediaRepository.php
  centreon/tests/php/Core/Media/Application/UseCase/MigrateAllMedias/MigrateAllMediasTest.php
Labels: area/backend

#3097 enh(UI): Add message about thresholds
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a single autocomplete when the corresponding atom is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a warning message when metrics with different units are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a warning message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays an error message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays the selected metric when resources are fulfilled and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- removes metrics item when the delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- displays the selected metric when resources are fulfilled and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- removes metrics item when the delete icon is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
Labels: area/ui

#3211 enh (host group): new API-type repositories for host groups
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostGroup/Application/Repository/ReadHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/FindHostGroups/FindHostGroups.php
  centreon/src/Core/HostGroup/Domain/Model/HostGroup.php
  centreon/src/Core/HostGroup/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostGroup/Infrastructure/Repository/ApiReadHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/HostGroupFactory.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/FindHostGroups/FindHostGroupsTest.php
Labels: area/backend

#3226 enh(UI): Add message about thresholds (#3097)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a single autocomplete when the corresponding atom is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a warning message when metrics with different units are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays a warning message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays an error message when the corresponding atom is set and the selected metric is available on several resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays the selected metric when resources are fulfilled and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- removes metrics item when the delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- displays the selected metric when resources are fulfilled and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/MetricsOnly/MetricsOnly.cypress.spec.tsx/MetricsOnly -- removes metrics item when the delete icon is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
Labels: backport

#3221 fix(monitoring) fix severities listing when user non-admin (#3154)
  centreon/src/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategory.php
  centreon/src/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategory.php
  centreon/src/Core/Severity/RealTime/Application/Repository/ReadSeverityRepositoryInterface.php
  centreon/src/Core/Severity/RealTime/Application/UseCase/FindSeverity/FindSeverity.php
  centreon/src/Core/Severity/RealTime/Infrastructure/Repository/DbReadSeverityRepository.php
  centreon/src/Core/Tag/RealTime/Application/Repository/ReadTagRepositoryInterface.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbReadTagRepository.php
  centreon/src/Core/Tag/RealTime/Infrastructure/Repository/Tag/DbTagFactory.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryTest.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryTest.php
  centreon/tests/php/Core/Severity/RealTime/Application/UseCase/FindSeverity/FindSeverityTest.php
Labels: area/backend, backport
