Repository centreon/centreon, pull requests merged in 2024-12, with the labels that each got.

#5926 [Test][Web] Add Tags to tests not exported to Xray
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing.feature
Labels: area/test

#5935 Revert "feat(ci): manage external contributions using env (#5740)"
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/check-status.yml
  .github/workflows/chromatic.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/get-environment.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/newman.yml
  .github/workflows/nightly-cod-platform-deploy.yml
  .github/workflows/nightly-cod-platform-destroy.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/release.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web-analysis.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#5925 fix(ACC): split the URL field into scheme and main URL
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/adapters.ts
Labels: area/ui, skip-workflow-web

#5924 fix(acc): handle scheme separatly from the rest of URL
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/Schema/VmWareV6Schema.json
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6ParametersTest.php
Labels: area/backend, skip-workflow-web

#5664 chore(ci): updated upload/download-artifact actions to offset v3 deprecation
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/package/action.yml
  .github/actions/web-frontend-component-test/action.yml
  .github/workflows/behat-test.yml
Labels: ci

#5890 fix(cloud): save ARGn in service configuration for cloud
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend, skip-workflow-web

#5889 Enh(UI): Enhance the design of the reset password form
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx/Reset Password -- displays errors when the form is not correctly filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx/Reset Password -- displays the reset password form.snap.png
  centreon/www/front_src/src/ResetPassword/Form.tsx
  centreon/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx
  centreon/www/front_src/src/ResetPassword/index.tsx
Labels: area/ui, skip-workflow-web

#5912 fix(Dashboards): Passive host are not taken into account on status chart/grid
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
Labels: area/backend, skip-workflow-web

#5939 Fix(Poller/Agent Configuration): The listing page disappears when searching for a name that doesn't exist.
  centreon/www/front_src/src/AgentConfiguration/Page.tsx
Labels: area/ui, skip-workflow-web

#5605 fix(logs): add action logs on host category APIv2 write operations
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryActionLogRepository.php
  centreon/tests/rest_api/collections/configuration/Host_Category.postman_collection.json
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend, skip-workflow-web

#5878 fix(graph): modernise queries
  centreon/www/class/centreonGraph.class.php
Labels: area/backend, skip-workflow-web

#5951 fix(open-tickets): issue when opening a ticket as non admin user
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: skip-workflow-open-tickets

#5984 fix(open-tickets): issue when opening a ticket as non admin user (#5951)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: area/backend, backport

#5983 fix(open-tickets): issue when opening a ticket as non admin user (#5951)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: area/backend, backport

#5982 fix(open-tickets): issue when opening a ticket as non admin user (#5951)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: area/backend, backport

#5980 fix(open-tickets): issue when opening a ticket as non admin user (#5951)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: area/backend, backport

#5977 fix(open-tickets): issue when opening a ticket as non admin user (#5951)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
Labels: area/backend, backport

#5942 fix(ACC): Update POST/PUT endpoints payload to split scheme
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/Schema/VmWareV6Schema.json
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6ParametersTest.php
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/adapters.ts
Labels: skip-workflow-web

#5867 fix(RS) FindServiceNotificationPolicy endpoint
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
Labels: area/backend, skip-workflow-web

#5981 Automated E2E - Agent Configuration Search Filter
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing.feature
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
Labels: area/test

#5985 Automated E2E -Actions Logs
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log/index.ts
  centreon/tests/e2e/fixtures/host-categories/category.json
Labels: area/test

#5948 fix(widgets): fix query for Live Top 10 Memory usage (#5532)
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
Labels: backport

#5947 fix(widgets): fix query for Live Top 10 Memory usage (#5532)
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
Labels: backport

#5967 enh(ci): do not fetch unnecessary plugins repo metadata
  .github/actions/package-nfpm/action.yml
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma9/Dockerfile
  centreon-awie/packaging/centreon-awie.yaml
  centreon-dsm/packaging/centreon-dsm-client.yaml
  centreon-dsm/packaging/centreon-dsm-server.yaml
  centreon-dsm/packaging/centreon-dsm.yaml
  centreon-open-tickets/packaging/centreon-open-tickets.yaml
  centreon/packaging/centreon-central.yaml
  centreon/packaging/centreon-mariadb.yaml
  centreon/packaging/centreon-mysql.yaml
  centreon/packaging/centreon-perl-libs.yaml
  centreon/packaging/centreon-poller.yaml
  centreon/packaging/centreon-trap.yaml
  centreon/packaging/centreon-web.yaml
  centreon/packaging/centreon.yaml
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#5915 fix (media): fix SQL query during synchronisation files
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: area/backend, skip-workflow-web

#5999 fix (media): fix SQL query during synchronisation files (#5915)
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: backport

#5978 fix(administration): add rules for len_storage_downtimes
  centreon/www/include/Administration/parameters/centstorage/form.php
Labels: area/backend

#6006 fix(cloud-Notification): fix database name in query
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
Labels: area/backend, skip-workflow-web

#6015 MON-154769 Sync hotfix 23.10
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/23.10.2/.gitignore
Labels: skip-workflow-open-tickets

#6014 MON-154770 Sync hotfix 24.04
  .github/actions/promote-to-stable/action.yml
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.04.3/.gitignore
Labels: skip-workflow-open-tickets

#6013 MON-154771 Sync hotfix 24.10
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.10.1/.gitignore
Labels: skip-workflow-open-tickets

#5787 chore(E2E): Adding E2E test to cover open ticket functionality
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/open-tickets.yml
  centreon-open-tickets/tests/e2e/.eslintrc.js
  centreon-open-tickets/tests/e2e/.gitignore
  centreon-open-tickets/tests/e2e/common.ts
  centreon-open-tickets/tests/e2e/configuration.ts
  centreon-open-tickets/tests/e2e/cypress.config.ts
  centreon-open-tickets/tests/e2e/cypress.dev.config.ts
  centreon-open-tickets/tests/e2e/esbuild-preprocessor.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration.feature
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/dashboards/check-permissions/dashboards.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/dashboards.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithResourceTableWidget.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/widgets/genericText.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/navigation/dashboards-more-than-a-single-page.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/navigation/dashboards-single-page.json
  centreon-open-tickets/tests/e2e/fixtures/users/admin.json
  centreon-open-tickets/tests/e2e/package.json
  centreon-open-tickets/tests/e2e/plugins.ts
  centreon-open-tickets/tests/e2e/plugins/index.ts
  centreon-open-tickets/tests/e2e/pnpm-lock.yaml
  centreon-open-tickets/tests/e2e/reporter-config.js
  centreon-open-tickets/tests/e2e/support/commands.ts
  centreon-open-tickets/tests/e2e/support/e2e.ts
  centreon-open-tickets/tests/e2e/tasks.ts
  centreon-open-tickets/tests/e2e/tsconfig.json
Labels: area/test, skip-workflow-open-tickets

#6021 fix(cloud-Notification): fix database name in query (#6006)
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
Labels: backport

#5802 enh(openid): log errors and improve logging message
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend, skip-workflow-web

#6030 MON-154771 Sync release branch 24.10
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.10.1/.gitignore
Labels: skip-workflow-open-tickets

#6029 MON-154770 Sync release branch 24.04
  .github/actions/promote-to-stable/action.yml
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.04.3/.gitignore
Labels: skip-workflow-open-tickets

#6027 MON-154768 Sync release branche 23.04
  centreon-open-tickets/.version
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/23.04.5/.gitignore
Labels: skip-workflow-open-tickets

#6011 Fix(API token): Improper Access Control allowing a user with ACL to create and use a valid Admin token
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
Labels: area/ui, skip-workflow-web

#5958 Fix((UI): Fix dataset resources search issue
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/api/buildListingEndpoint/getSearchQueryParameterValue.ts
  centreon/packages/ui/src/api/buildListingEndpoint/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
Labels: area/ui, skip-workflow-web

#6018 enh(resource status): improve wording for filter manage order
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/EditFilterButton.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/index.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, skip-workflow-web

#5872 enh(resources status): Add Flapping state in RS page, resource table and status grid widget
  centreon/cypress/fixtures/resources/listing/listingWithStates.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on dark theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Icon/FlappingIcon.tsx
  centreon/packages/ui/src/Icon/index.ts
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/Chip/Flapping.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/State.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/colors.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/State.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
  centreon/www/front_src/src/Resources/Chip/Flapping.tsx
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/PercentStateChangeCard.tsx
  centreon/www/front_src/src/Resources/Filter/Criterias/models.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/FilterSearchQuery.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/State/index.tsx
  centreon/www/front_src/src/Resources/colors.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, skip-workflow-web

#5895 enh(UI): Add standard size on widgets
  centreon/cypress/fixtures/Dashboards/Dashboard/complexLayout.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dashboard global properties -- displays the dashboard global properties form when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dataset -- displays header link to Business activity when the widget has only business activities.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard with complex layout -- displays a new widget in the correct position when a widget is added.snap.png
  centreon/package.json
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays ranged thresholds.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays the gauge as critical when corresponding thresholds are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays the gauge as success when corresponding thresholds are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays the gauge as warning when corresponding thresholds are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays the threshold tooltip when a threshold is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Gauge/Gauge.cypress.spec.tsx/Gauge -- displays the value as raw when the prop is set.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/Gauge/PieData.tsx
  centreon/packages/ui/src/Graph/Gauge/Thresholds.tsx
  centreon/packages/ui/src/Graph/Gauge/utils.ts
  centreon/pnpm-lock.yaml
  centreon/tests/e2e/features/Dashboards/13-dashboard-all-widgets/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/models.ts
  centreon/www/front_src/src/federatedModules/models.ts
Labels: area/ui, skip-workflow-web

#5959 feat(ci): automate ticket creation on scheduled build failure (#5587)
  .github/actions/changes-trigger-checks/action.yml
  .github/actions/create-jira-ticket/action.yml
  .github/actions/create-jira-ticket/nightly-ticket-template.json
  .github/actions/create-jira-ticket/veracode-ticket-template.json
  .github/actions/veracode-create-jira-ticket/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/newman.yml
  .github/workflows/ui-beta.yml
  .github/workflows/web.yml
Labels: backport, ci

#6045 fix(nightly): resolve codestyle issue
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: skip-workflow-web

#6049 fix (media): fix SQL query during synchronisation files (#5915)
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: backport, skip-workflow-web

#6050 fix (media): fix SQL query during synchronisation files (#5915)
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: backport, skip-workflow-web

#6051 fix (media): fix SQL query during synchronisation files (#5915)
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: backport, skip-workflow-web

#6052 fix (media): fix SQL query during synchronisation files (#5915)
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
Labels: backport, skip-workflow-web

#6055 fix(graph): modernise queries (#5878)
  centreon/www/class/centreonGraph.class.php
Labels: backport, skip-workflow-web

#6054 fix(graph): modernise queries (#5878)
  centreon/www/class/centreonGraph.class.php
Labels: backport, skip-workflow-web

#6053 fix(graph): modernise queries (#5878)
  centreon/www/class/centreonGraph.class.php
Labels: backport, skip-workflow-web

#5870 MON-106121-move-perl-library-to-collect
  centreon/lib/perl/centreon/common/db.pm
  centreon/lib/perl/centreon/common/lock.pm
  centreon/lib/perl/centreon/common/logger.pm
  centreon/lib/perl/centreon/common/misc.pm
  centreon/lib/perl/centreon/health/checkbroker.pm
  centreon/lib/perl/centreon/health/checkdb.pm
  centreon/lib/perl/centreon/health/checklogs.pm
  centreon/lib/perl/centreon/health/checkmodules.pm
  centreon/lib/perl/centreon/health/checkrrd.pm
  centreon/lib/perl/centreon/health/checkservers.pm
  centreon/lib/perl/centreon/health/checksystems.pm
  centreon/lib/perl/centreon/health/misc.pm
  centreon/lib/perl/centreon/health/output.pm
  centreon/lib/perl/centreon/health/ssh.pm
  centreon/lib/perl/centreon/reporting/CentreonAck.pm
  centreon/lib/perl/centreon/reporting/CentreonDashboard.pm
  centreon/lib/perl/centreon/reporting/CentreonDownTime.pm
  centreon/lib/perl/centreon/reporting/CentreonHost.pm
  centreon/lib/perl/centreon/reporting/CentreonHostStateEvents.pm
  centreon/lib/perl/centreon/reporting/CentreonLog.pm
  centreon/lib/perl/centreon/reporting/CentreonProcessStateEvents.pm
  centreon/lib/perl/centreon/reporting/CentreonService.pm
  centreon/lib/perl/centreon/reporting/CentreonServiceStateEvents.pm
  centreon/lib/perl/centreon/script.pm
  centreon/lib/perl/centreon/script/centFillTrapDB.pm
  centreon/lib/perl/centreon/script/centreonSyncArchives.pm
  centreon/lib/perl/centreon/script/centreonSyncPlugins.pm
  centreon/lib/perl/centreon/script/centreon_health.pm
  centreon/lib/perl/centreon/script/centreon_trap_send.pm
  centreon/lib/perl/centreon/script/centreontrapd.pm
  centreon/lib/perl/centreon/script/centreontrapdforward.pm
  centreon/lib/perl/centreon/script/dashboardBuilder.pm
  centreon/lib/perl/centreon/script/eventReportBuilder.pm
  centreon/lib/perl/centreon/script/logAnalyserBroker.pm
  centreon/lib/perl/centreon/trapd/Log.pm
  centreon/lib/perl/centreon/trapd/lib.pm
  centreon/packaging/centreon-perl-libs.yaml
  centreon/packaging/centreon-trap.yaml
  centreon/packaging/centreon-web.yaml
Labels: skip-workflow-web

#6060 enh(composer) : align composer for december minor
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
Labels: area/backend, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#6062 enh(composer) : align composer for december minor
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
Labels: area/backend, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#6038 enh(SQL): Enhance query in export of widget service monitoring
  centreon/www/widgets/service-monitoring/src/export.php
Labels: area/backend, skip-workflow-web

#6057 Enhance query in export of widget serviceGroup monitoring
  centreon/www/widgets/servicegroup-monitoring/src/export.php
Labels: area/backend, skip-workflow-web

#6020 enh(Dashboards): added health calculation in Status grid widget for Impact BAs
  centreon/cypress/fixtures/Widgets/StatusGrid/criticalImpactBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/criticalRatioBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/impactBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/ratioBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/worstStatusBA.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/BATooltipContent.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/useBATooltipContent.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/api/decoders.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx
Labels: area/ui, skip-workflow-web

#5663 chore(ci): updated upload/download-artifact actions to offset v3 deprecation
  .github/actions/package/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/ui-beta.yml
  .github/workflows/web.yml
  .github/workflows/widget-package.yml
Labels: ci

#5662 chore(ci): updated upload/download-artifact actions to offset v3 deprecation
  .github/actions/get-test-plan-key/action.yml
  .github/actions/merge-artifacts/action.yml
  .github/actions/package/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
  .github/workflows/widget-package.yml
Labels: ci

#6037 feat(tests): add scenarios
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration.feature
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
Labels: area/test

#6056 enh(UI): Make the reset password form customizable
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx/Custom Reset Password page -- displays the Reset Password page when it is customized.snap.png
  centreon/www/front_src/src/Login/index.tsx
  centreon/www/front_src/src/Login/useGetLoginCustomData.ts
  centreon/www/front_src/src/Login/useLogin.ts
  centreon/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx
  centreon/www/front_src/src/ResetPassword/index.tsx
Labels: area/ui, skip-workflow-web

#6087 enh(ci): move veracode analysis out of base workflows (#5888)
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  centreon-awie/veracode.json
  centreon-dsm/veracode.json
  centreon-ha/veracode.json
  centreon-open-tickets/veracode.json
Labels: skip-workflow-awie

#6088 enh(ci): move veracode analysis out of base workflows (#5888)
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  centreon-awie/veracode.json
  centreon-dsm/veracode.json
  centreon-ha/veracode.json
  centreon-open-tickets/veracode.json
Labels: skip-workflow-awie

#6108 fix(packaging): set centreon env files as config files
  centreon/packaging/centreon-web.yaml
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: skip-workflow-web

#5969 fix(graph): modernise queries (#5878)
  centreon/www/class/centreonGraph.class.php
Labels: area/backend, backport, skip-workflow-web

#6116 chore(core): Update frontend deps
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays metrics with other units as disabled when the maximum of units are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metric as completly selected when all the related resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- excludes a resource when a metric is selected and a resource is unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects all the resources related to the selected metric when a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects only the resource when a resource is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- selects a metrics when the options list is expanded and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with single resource -- displays the retrieved metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/package.json
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Form/Form.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRights/storiesData.ts
  centreon/packages/ui/test/setupTests.js
  centreon/pnpm-lock.yaml
  centreon/setupTest.js
  centreon/tests/e2e/features/Dashboards/17-clock-timer-widget-configuration/index.ts
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/BreadcrumbTrail/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/BATooltipContent.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardAccessRights/useDashboardAccessRights.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/useListing.ts
  centreon/www/front_src/src/Dashboards/routerHooks.ts
  centreon/www/front_src/src/components/ReactRouter/DeprecatedRoute.tsx
  centreon/www/front_src/src/components/ReactRouter/index.test.tsx
Labels: area/ui, skip-workflow-web

#6067 enh(UI): Sync widget options with available widgets
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
Labels: area/ui, skip-workflow-web

#6089 enh(ci): move veracode analysis out of base workflows (#5888)
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  centreon-awie/veracode.json
  centreon-dsm/veracode.json
  centreon-ha/veracode.json
  centreon-open-tickets/veracode.json
Labels: skip-workflow-awie

#6001 enh(ci): run push and publish jobs only on centreon/centreon
  .github/workflows/awie.yml
  .github/workflows/chromatic.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/nightly-cod-platform-deploy.yml
  .github/workflows/nightly-cod-platform-destroy.yml
  .github/workflows/open-tickets.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6075 enh(SQL): Enh sql in index of widget serviceGroup monitoring
  centreon/www/widgets/servicegroup-monitoring/src/index.php
Labels: area/backend, skip-workflow-web

#6074 enh(SQL): Enh sql in index of widget host monitoring
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend, skip-workflow-web

#6126 fix(Custom View): fix index/export of widget grouphost monitoring
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend, skip-workflow-web

#6076 enh(SQL): Enh sql in export of widget host monitoring
  centreon/www/widgets/host-monitoring/src/export.php
Labels: area/backend, skip-workflow-web

#6188 fix(packaging): add cron dependency for debian packages
  centreon/packaging/centreon-web.yaml
Labels: area/backend, skip-workflow-web

#6190 fix(packaging): add cron dependency for debian packages (#6188)
  centreon/packaging/centreon-web.yaml
Labels: backport, skip-workflow-web

#6191 fix(packaging): add cron dependency for debian packages (#6188)
  centreon/packaging/centreon-web.yaml
Labels: backport, skip-workflow-web

#6146 fix(Custom View): fix index/export of widget grouphost monitoring (#6…
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web

#6143 enh(SQL): Enh sql in index of widget host monitoring (#6074)
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web

#5592 fix(logs): add Action Logs on add command endpoint
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/DbWriteCommandActionLogRepository.php
Labels: area/backend, skip-workflow-web

#6081 enh(ACC) remove FindAvailablePollers endpoint
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/FindPollers.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/Schema/FindPollersResponse.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/ReadAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollers.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersResponse.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersController.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersPresenter.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersRoute.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbReadAccRepository.php
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions.feature
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterStub.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersTest.php
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
Labels: area/backend, skip-workflow-web

#6194 MON-154337 Sync Centreon release 24.10
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/.version
  centreon/composer.lock
  centreon/packaging/centreon-web.yaml
  centreon/www/class/centreon-clapi/centreonAPI.class.php
  centreon/www/class/centreonGraph.class.php
  centreon/www/include/common/csvFunctions.php
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/widgets/host-monitoring/src/index.php
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#6195 MON-154336 Sync centreon 24.04 release
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
  centreon/packaging/centreon-web.yaml
  centreon/www/class/centreonGraph.class.php
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
  centreon/www/widgets/host-monitoring/src/index.php
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#5922 enh(ceip): add agent configuration to ceip stats (#5237)
  centreon/cron/centreon-send-stats.php
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend, skip-workflow-web

#5879 feat(Service Categories): Add Action Logs (#5712)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateActionLogRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbWriteServiceCategoryActionLogRepository.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateActionLogRepository.php
  centreon/www/class/centreonHost.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_categories/DB-Func.php
  centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
Labels: area/backend, skip-workflow-web

#5818 feat(Service Categories): Add Action Logs (#5712)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateActionLogRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbWriteServiceCategoryActionLogRepository.php
  centreon/www/class/centreonHost.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_categories/DB-Func.php
  centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
Labels: area/backend, skip-workflow-web

#5914 Backport([Metrics Graph legend]): Fix display when many metrics are selected
  centreon/cypress/fixtures/Widgets/Graph/legend/lineChartForScrollableLegend.json
  centreon/cypress/fixtures/Widgets/Graph/legend/serviceMetricsForScrollableLegend.json
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement bottom and mode grid.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement bottom and mode list.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement left and mode grid.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement left and mode list.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement right and mode grid.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/legend with a scrollbar for placement right and mode list.snap.png
  centreon/packages/ui/src/Graph/Chart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/Chart/Legend/index.tsx
  centreon/packages/ui/src/Graph/common/BaseChart/BaseChart.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
Labels: area/ui, skip-workflow-web

#5918 Backport([dev-24.10.x]): Status grid display issue when reducing screen size
  centreon/packages/ui/src/Graph/HeatMap/ResponsiveHeatMap.tsx
  centreon/packages/ui/src/Graph/HeatMap/model.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.styles.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
Labels: area/ui, skip-workflow-web

#5950 [E2E backport] Rewrite ContactGroupConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/ContactGroupConfiguration.feature
  centreon/features/bootstrap/ContactGroupConfigurationContext.php
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration.feature
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport, skip-workflow-web

#6112 [E2E backport] Migrate SaveSearchFilter.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/SaveSearchFilter.feature
  centreon/features/bootstrap/SaveSearchFilterContext.php
  centreon/tests/e2e/features/Hosts/04-save-search-filter.feature
  centreon/tests/e2e/features/Hosts/04-save-search-filter/index.ts
Labels: area/test, backport, skip-workflow-web

#6032 Fix(API token): Improper Access Control allowing a user with ACL to c…
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
Labels: backport, skip-workflow-web

#6113 [E2E backport] Migrate SaveSearchFilter.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/SaveSearchFilter.feature
  centreon/features/bootstrap/SaveSearchFilterContext.php
  centreon/tests/e2e/features/Hosts/04-save-search-filter.feature
  centreon/tests/e2e/features/Hosts/04-save-search-filter/index.ts
Labels: area/test, backport, skip-workflow-web

#6035 enh(resource status): improve wording for filter manage order (#6018)
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/EditFilterButton.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/index.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: backport, skip-workflow-web

#6114 [E2E backport] Migrate MassiveChangeHosts.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/MassiveChangeHosts.feature
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/tests/e2e/features/Hosts/05-massive-change-hosts.feature
  centreon/tests/e2e/features/Hosts/05-massive-change-hosts/index.ts
Labels: area/test, backport, skip-workflow-web

#6036 enh(resource status): improve wording for filter manage order
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/EditFilterButton.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/EditButton/index.tsx
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: backport, skip-workflow-web

#5993 fix(resource status): add possibility to save custom filters order (…
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
Labels: backport, skip-workflow-web

#5992 fix(resource status): add possibility to save custom filters order (…
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
Labels: backport, skip-workflow-web

#6124 [E2E backport] Migrate TrapsSNMPGroupConfiguration.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/TrapsSNMPGroupConfiguration.feature
  centreon/features/bootstrap/TrapsSNMPGroupConfigurationContext.php
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration.feature
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration/index.ts
  centreon/tests/e2e/features/Snmp-Traps/common.ts
  centreon/tests/e2e/fixtures/snmp-traps/snmp-trap.json
Labels: area/test, backport, skip-workflow-web

#5996 fix(DSM): White page when creating a pool (#5497)
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/DB-Func.php
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/formSlot.php
Labels: backport, skip-workflow-dsm

#5940 enh(acc vmware): parameters UI enhancements
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- clears filters and the search bar, and sends a listing request with empty search parameter when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the advanced filters component when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- deletes an ACC when the Delete button is clicked and the confirmation button is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- displays the first page of the ACC listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends a Post request when the Modal is in Creation Mode and the Create Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends an Update request when the Modal is in Edition Mode and the Update Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Ask Before quit popup -- displays a modal when the form is updated and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Ask Before quit popup -- displays a modal when the form is updated with errors and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter password field is required in Creation Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter username is required in Creation Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- displays listing, filters and action buttons.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creation date column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creator column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Last update column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Name column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Type column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Updated by column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays a welcome label when the listing is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- discards the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resolves the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/CloseModalConfirmation.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/Form.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Parameter.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Port.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/useParametersStyles.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Page.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/AddButton.tsx
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: skip-workflow-web

#5994 Enh(UI): Enhance the design of the reset password form (#5889)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx/Reset Password -- displays errors when the form is not correctly filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx/Reset Password -- displays the reset password form.snap.png
  centreon/www/front_src/src/ResetPassword/Form.tsx
  centreon/www/front_src/src/ResetPassword/ResetPassword.cypress.spec.tsx
  centreon/www/front_src/src/ResetPassword/index.tsx
Labels: backport, skip-workflow-web

#6196 [E2E backport] Automated tests - Actions Logs
  centreon/tests/e2e/features/Logs/01-time-period-changes-log.feature
  centreon/tests/e2e/features/Logs/01-time-period-changes-log/index.ts
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log.feature
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log/index.ts
  centreon/tests/e2e/features/Logs/03-services-severities-changes-log.feature
  centreon/tests/e2e/features/Logs/03-services-severities-changes-log/index.ts
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log/index.ts
  centreon/tests/e2e/features/Logs/commands.ts
  centreon/tests/e2e/fixtures/host-categories/severity.json
  centreon/tests/e2e/fixtures/services/category.json
  centreon/tests/e2e/fixtures/services/severity.json
  centreon/tests/e2e/fixtures/time-periods/time-period.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#6033 Fix(API token): Improper Access Control allowing a user with ACL to c…
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
Labels: backport, skip-workflow-web

#5919 fix(Dashboard): Error on Adding Second Service via Character-by-Character Input (#5722) [dev-24.10.x]
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/ui, area/backend, backport, skip-workflow-web

#5954 fix(Dashboards): Passive host are not taken into account on status chart/grid (#5912) [dev-24.10.x]
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
Labels: area/backend, backport, skip-workflow-web

#5921 fix(Dashboard): Error on Adding Second Service via Character-by-Character Input (#5722) [dev-24.04.x]
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/ui, area/backend, backport, skip-workflow-web

#5955 fix(Dashboards): Passive host are not taken into account on status chart/grid (#5912) [dev-24.04.x]
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
Labels: area/backend, backport, skip-workflow-web

#5988 fix(RS) FindServiceNotificationPolicy endpoint (#5867)
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
Labels: area/backend, skip-workflow-web

#5987 fix(RS) FindServiceNotificationPolicy endpoint (#5867)
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
Labels: area/backend, skip-workflow-web

#5979 feat(ci): Implement e2e tests for R.A.M - Listing rules (#3953)
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing.feature
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing/index.ts
  centreon/tests/e2e/features/Resources-Access-Management/commands.ts
  centreon/tests/e2e/support/e2e.ts
Labels: area/test

#5916 [E2E backport] Automated tests - Actions Logs
  centreon/tests/e2e/features/Logs/01-time-period-changes-log.feature
  centreon/tests/e2e/features/Logs/01-time-period-changes-log/index.ts
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log.feature
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log/index.ts
  centreon/tests/e2e/features/Logs/03-services-severities-changes-log.feature
  centreon/tests/e2e/features/Logs/03-services-severities-changes-log/index.ts
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log/index.ts
  centreon/tests/e2e/features/Logs/commands.ts
  centreon/tests/e2e/fixtures/host-categories/severity.json
  centreon/tests/e2e/fixtures/services/category.json
  centreon/tests/e2e/fixtures/services/severity.json
  centreon/tests/e2e/fixtures/time-periods/time-period.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5976 [Test][Web] Add Tags to tests not exported to Xray (#5926)
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing.feature
Labels: area/test

#6140 enh(SQL): Enh sql in index of widget host monitoring (#6074)
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#6144 enh(SQL): Enh sql in index of widget host monitoring (#6074)
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#6145 fix(Custom View): fix index/export of widget grouphost monitoring (#6…
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport

#6147 fix(Custom View): fix index/export of widget grouphost monitoring (#6…
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport

#5989 [E2E backport] Automated E2E - Poller Agent Configuration
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/tests/e2e/fixtures/agents-configuration/agent-config.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#6201 Fix: flacky test
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
Labels: skip-workflow-web

#6142 enh(SQL): Enh sql in index of widget host monitoring (#6074)
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#6148 fix(Custom View): fix index/export of widget grouphost monitoring (#6…
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport

#6058 enh(UI): Unexpected array when using public playlists using an "old" browser
  centreon/www/front_src/src/publicPages/usePageResolver.ts
Labels: area/ui, skip-workflow-web

#6122 [E2E backport] Migrate MassiveChangeServices.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/MassiveChangeServices.feature
  centreon/features/bootstrap/MassiveChangeServicesContext.php
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/tests/e2e/features/Services-configuration/08-massive-change-services.feature
  centreon/tests/e2e/features/Services-configuration/08-massive-change-services/index.ts
Labels: area/test, backport, skip-workflow-web

#5949 [E2E backport] Rewrite ContactGroupConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/ContactGroupConfiguration.feature
  centreon/features/bootstrap/ContactGroupConfigurationContext.php
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration.feature
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport, skip-workflow-web

#5952 [E2E backport] Rewrite MetaServiceConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/MetaServiceConfiguration.feature
  centreon/features/bootstrap/MetaServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration/index.ts
  centreon/tests/e2e/fixtures/services/meta_service.json
Labels: area/test, backport, skip-workflow-web

#6125 [E2E backport] Migrate TrapsSNMPGroupConfiguration.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/TrapsSNMPGroupConfiguration.feature
  centreon/features/bootstrap/TrapsSNMPGroupConfigurationContext.php
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration.feature
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration/index.ts
  centreon/tests/e2e/features/Snmp-Traps/common.ts
  centreon/tests/e2e/fixtures/snmp-traps/snmp-trap.json
Labels: area/test, backport

#6084 [E2E backport] Rewrite GenerateServiceContact.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/GenerateServiceContact.feature
  centreon/features/bootstrap/GenerateServiceContactContext.php
  centreon/tests/e2e/features/Services-configuration/06-generate-service-contact.feature
  centreon/tests/e2e/features/Services-configuration/06-generate-service-contact/index.ts
Labels: area/test, backport, skip-workflow-web

#6103 Fix((UI): Fix dataset resources search issue
  .github/workflows/chromatic.yml
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/api/buildListingEndpoint/getSearchQueryParameterValue.ts
  centreon/packages/ui/src/api/buildListingEndpoint/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
Labels: backport, skip-workflow-web

#6082 [E2E backport] Rewrite ContactTemplateConfiguration.feature Behat test to Cypress test
  centreon/behat.yml
  centreon/features/ContactTemplateConfiguration.feature
  centreon/features/bootstrap/ContactTemplateConfigurationContext.php
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration.feature
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration/index.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport, skip-workflow-web

#6104 Fix((UI): Fix dataset resources search issue
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/packages/ui/cypress/support/commands.tsx
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/1024px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/200px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/500px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 150px and the max is 80px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 150px and the min is 30px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 150px and the pref is 10.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 300px and the max is 80px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 300px and the min is 30px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 300px and the pref is 10.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 500px and the max is 80px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 500px and the min is 30px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Typography/FluidTypography/FluidTypography.cypress.spec.tsx/FluidTypography -- displays the text when the viewport is 500px and the pref is 10.snap.png
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/api/buildListingEndpoint/getSearchQueryParameterValue.ts
  centreon/packages/ui/src/api/buildListingEndpoint/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
Labels: backport, skip-workflow-web

#6083 [E2E backport] Rewrite ContactTemplateConfiguration.feature Behat test to Cypress test
  centreon/behat.yml
  centreon/features/ContactTemplateConfiguration.feature
  centreon/features/bootstrap/ContactTemplateConfigurationContext.php
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration.feature
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration/index.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport, skip-workflow-web

#5920 Backport([dev-24.04.x]): Status grid display issue when reducing screen size
  centreon/packages/ui/src/Graph/HeatMap/ResponsiveHeatMap.tsx
  centreon/packages/ui/src/Graph/HeatMap/model.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.styles.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
Labels: area/ui

#6123 [E2E backport] Migrate MassiveChangeServices.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/MassiveChangeServices.feature
  centreon/features/bootstrap/MassiveChangeServicesContext.php
  centreon/tests/e2e/features/Services-configuration/08-massive-change-services.feature
  centreon/tests/e2e/features/Services-configuration/08-massive-change-services/index.ts
Labels: area/test, backport, skip-workflow-web

#6128 [E2E backport] Migrate SpecialCharactersInContact.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/SpecialCharactersInContact.feature
  centreon/features/bootstrap/SpecialCharactersInContactContext.php
  centreon/tests/e2e/features/Contacts/04-non-admin-contact-creation/index.ts
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact.feature
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport, skip-workflow-web

#6100 fix(Top counters): use statistics refresh interval instead of monitoring refresh
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/statisticsRefreshIntervalAtom.ts
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
Labels: area/ui

#6008 fix(administration): add rules for len_storage_downtimes (#5978)
  centreon/www/include/Administration/parameters/centstorage/form.php
Labels: backport, skip-workflow-web

#6129 [E2E backport] Migrate SpecialCharactersInContact.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/SpecialCharactersInContact.feature
  centreon/features/bootstrap/SpecialCharactersInContactContext.php
  centreon/tests/e2e/features/Contacts/04-non-admin-contact-creation/index.ts
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact.feature
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test, backport

#6213 Automated E2E - Agent Configuration Search Filter
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing.feature
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
Labels: area/test, backport

#6212 [backport] Automated E2E - Additional Connector Configuration
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation.feature
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
Labels: area/test, backport

#6131 [E2E backport] Migrate LdapConfiguration.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/LdapConfiguration.feature
  centreon/features/bootstrap/LdapConfigurationContext.php
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration.feature
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration/index.ts
  centreon/tests/e2e/features/Ldaps/commands.ts
  centreon/tests/e2e/fixtures/ldaps/ldap.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web

#6079 fix(configuration): improve input sanitization for contact form (#6017)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: backport, skip-workflow-web

#6132 [E2E backport] Migrate LdapConfiguration.feature behat test to cypress test
  centreon/behat.yml
  centreon/features/LdapConfiguration.feature
  centreon/features/bootstrap/LdapConfigurationContext.php
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration.feature
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration/index.ts
  centreon/tests/e2e/features/Ldaps/commands.ts
  centreon/tests/e2e/fixtures/ldaps/ldap.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#6199 Enh(ACC): harmonize the poller filter to align with the one used in the PAC
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/FindPollers.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/Schema/FindPollersResponse.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/ReadAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollers.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersResponse.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersController.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersPresenter.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersRoute.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbReadAccRepository.php
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions.feature
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterStub.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersTest.php
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useFormInputs.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/useModal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/endpoints.ts
Labels: area/ui, area/backend, skip-workflow-web

#6009 fix(administration): add rules for len_storage_downtimes (#5978)
  centreon/www/include/Administration/parameters/centstorage/form.php
Labels: backport, skip-workflow-web

#6080 fix(configuration): improve input sanitization for contact form (#6017)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: backport, skip-workflow-web

#6187 enh(ci): run push and publish jobs only on centreon/centreon (#6001)
  .github/workflows/awie.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-openid.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/open-tickets.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6184 enh(ci): run push and publish jobs only on centreon/centreon (#6001)
  .github/workflows/awie.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/open-tickets.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6172 enh(ci): run push and publish jobs only on centreon/centreon (#6001)
  .github/workflows/awie.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/nightly-cod-platform-deploy.yml
  .github/workflows/nightly-cod-platform-destroy.yml
  .github/workflows/open-tickets.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6221 Enh(ACC): harmonize the poller filter to align with the one used in t…
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/FindPollers.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/Schema/FindPollersResponse.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/ReadAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollers.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersResponse.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersController.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersPresenter.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersRoute.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbReadAccRepository.php
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions.feature
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterStub.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersTest.php
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useFormInputs.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/useModal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/endpoints.ts
Labels: skip-workflow-web

#6220 enh(UI) resources status export button style is confused
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Resources/Graph/Performance/GraphActions.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: skip-workflow-web

#6178 enh(ci): run push and publish jobs only on centreon/centreon (#6001)
  .github/workflows/awie.yml
  .github/workflows/chromatic-nightly.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/open-tickets.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/web.yml
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/1024px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/200px.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/TimePeriods/ResolutionTimePeriod.cypress.spec.tsx/500px.snap.png
Labels: skip-workflow-create-repo-yum

#6162 enh(SQL): Enh sql in export of widget host monitoring (#6076)
  centreon/www/widgets/host-monitoring/src/export.php
Labels: area/backend, backport, skip-workflow-web
