Repository centreon/centreon, pull requests merged in 2024-02, with the labels that each got.

#3230 enh(UI): Clarify resource selection
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/ItemComposition/ItemComposition.cypress.spec.tsx/ItemComposition -- displays items as linked when the prop is set to true.snap.png
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.cypress.spec.tsx
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.stories.tsx
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.styles.ts
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: area/ui

#3236 enh(UI): Clarify resource selection (#3230)
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/ItemComposition/ItemComposition.cypress.spec.tsx/ItemComposition -- displays items as linked when the prop is set to true.snap.png
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.cypress.spec.tsx
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.stories.tsx
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.styles.ts
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
Labels: backport

#3254 Fix(UI): Fix alignment on resources composition
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metric as completly selected when all the related resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- excludes a resource when a metric is selected and a resource is unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects all the resources related to the selected metric when a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects only the resource when a resource is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
Labels: area/ui

#3258 Fix(UI): Fix item composition spacing
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
Labels: area/ui

#3259 [Backport] Fix(UI): Fix item composition spacing
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
Labels: backport

#3163 fix(anomaly detection) : Fix Issue on SQL Violation when selecting a host while creating a new anomaly detection on MySQL8
  centreon/www/api/class/centreon_performance_service.class.php
Labels: area/backend

#3235 fix(backport of #3141): feature_flags were not taken into account
  centreon/www/include/options/accessLists/menusACL/formMenusAccess.php
Labels: backport

#3257 fix(Cloud Notifications): Add database commit in update script
  centreon/www/install/php/Update-23.10.5.php
Labels: area/backend

#3262 fix: feature_flags were not taken into account (#3141)
  centreon/www/include/options/accessLists/menusACL/formMenusAccess.php
Labels: backport

#3256 Fix(UI): Fix alignment on resources composition (#3254)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metric as completly selected when all the related resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- excludes a resource when a metric is selected and a resource is unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects all the resources related to the selected metric when a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects only the resource when a resource is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
Labels: backport

#3268 fix(conf gorgone) YAML templates need actions enabled by default for …
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon-gorgone/gorgone/modules/core/action/hooks.pm
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3266 fix(conf gorgone backport) YAML templates need actions enabled by default for …
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon-gorgone/gorgone/modules/core/action/hooks.pm
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3110 enh(UI): Add new time periods + fix wording/translations
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/useTimePeriod.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
Labels: area/ui

#3269 fix(conf gorgone backport) YAML templates need actions enabled by default for …
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon-gorgone/gorgone/modules/core/action/hooks.pm
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3267 fix(conf gorgone backport) YAML templates need actions enabled by default for …
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon-gorgone/gorgone/modules/core/action/hooks.pm
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3288 enh(cloud/configuration): restore command / args configuration
  centreon/www/include/configuration/configObject/command/command.php
  centreon/www/include/configuration/configObject/command/formCommand.ihtml
  centreon/www/include/configuration/configObject/command/formCommand.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/formHostCloud.ihtml
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/service/formServiceCloud.ihtml
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend

#3282 enh(dashboards) : wording fix and optimizations
  .github/workflows/get-version.yml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/DashboardsPage.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Share.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsQuickAccess/DashboardsQuickAccessMenu.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardNavbar/DashboardNavbar.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
Labels: area/ui

#3313 fix(configuration): add missing args for command configuration in HT …
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#3323 Fix(UI): Fix animation error on metrics graph
  .github/actions/lighthouse-performance-testing/action.yml
  centreon/packages/ui/src/Graph/LineChart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/useInteractiveValues.ts
  centreon/packages/ui/src/Graph/LineChart/index.tsx
Labels: area/ui

#3294 enh(API): Allow access to Realtime API if user has access to Centreon Frontend
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/www/class/centreonAuth.LDAP.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#3223 feat(Resource Access Management): Edit Resource Access Rule implementation
  .github/actions/lighthouse-performance-testing/action.yml
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset filters button when two dataset filters are selected, the button disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset filters button when two dataset filters are setup, the button disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset icon when two datasets are selected, the icon disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset icon when two datasets are setup, the icon dissappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset filters button is visible when at least two dataset filters are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset filters button is visible when at least two dataset filters are setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset icon is visible when at least two datasets are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset icon is visible when at least two datasets are setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are disabled when resource type and/or resources in dataset are not selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are enabled when a dataset is filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are enabled when a dataset is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons is disabled when resource type and/or resources in dataset are not selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and Add new dataset button is enabled when a dataset for metaservice is setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and Add new dataset button is enabled when a dataset for service is setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and the Add new dataset button is enabled when a dataset for a service is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Save button is activated when the form is filled and error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- displays the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- sends a request to add a new Resource Access Rule with the form values when the Save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- confirms that the Save button becomes enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays configured contacts and contact groups for the Resource Access Rule.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays configured resources for the Resource Access Rule.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays the edit resource access rule modal and control actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the Save's button initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- sends a request to edit a Resource Access Rule when a configured value is changed and the Save button is clicked.snap.png
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useFormSubmit.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/initialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/useFormInitialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/FormInputs.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/AddDatasetButton.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilterDivider.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilters.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/ResourceSelection.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/AddDatasetButton.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilter.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilterDivider.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilters.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DeleteDatasetButton.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/api/decoders.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/useResourceAccessRuleModal.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Listing.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/useListing.ts
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
  centreon/www/install/php/Update-23.10.5.php
Labels: area/ui, area/backend

#3338 fix(cloud/configuration): issue when creating a command fixed
  centreon/www/include/configuration/configObject/command/DB-Func.php
Labels: area/backend

#3347 fix(cloud/service): command id not saved when creating / updating a s…
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3287 enh(dashboards) : Additional menu optimizations
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Share.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardNavbar/DashboardNavbar.styles.ts
  centreon/www/front_src/src/Dashboards/components/DashboardNavbar/DashboardNavbar.tsx
Labels: area/ui

#3366 fix (clapi): decode HTML entities when exporting command configuration with CLAPI (#2850)
  centreon/www/class/centreon-clapi/centreonCommand.class.php
Labels: area/backend, backport

#3367 fix (clapi): decode HTML entities when exporting command configuration with CLAPI (#2850)
  centreon/www/class/centreon-clapi/centreonCommand.class.php
Labels: area/backend, backport

#3368 fix (clapi): decode HTML entities when exporting command configuration with CLAPI (#2850)
  centreon/www/class/centreon-clapi/centreonCommand.class.php
Labels: area/backend, backport

#3370 fix(Notifications): contacts from dropdone are not accessible for Editor role
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsers.php
  centreon/tests/php/Core/User/Application/UseCase/FindUsers/FindUsersTest.php
Labels: area/backend

#3380 fix(Notification): Duplicate users in dropdone menu
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
Labels: area/backend

#3389 Fix(UI): Fix contact and contact group switch
  centreon/packages/ui/src/components/Form/AccessRights/ShareInput/ContactSwitch.tsx
  centreon/packages/ui/src/components/Form/AccessRights/ShareInput/ShareInput.tsx
Labels: area/ui

#3296 enh(ci): modify dependabot configuration
  .github/dependabot.yml
Labels: dependencies, javascript, php

#3233 fix(clapi) remove duplicate when exporting service/host templates
  centreon/www/class/centreon-clapi/centreonExported.class.php
  centreon/www/class/centreon-clapi/centreonHostTemplate.class.php
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: area/backend

#3388 enh(UI): Change navigation to the dashboard page onto the row
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Navigation to dashboard -- does not navigate to the dashboard page when the listing mode is activated and a row is clicked on the actions cell.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Navigation to dashboard -- navigates to the dashboard page when the listing mode is activated and a row is clicked.snap.png
  centreon/packages/ui/src/Listing/Cell/DataCell.styles.ts
  centreon/packages/ui/src/Listing/Cell/DataCell.tsx
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Name.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/useColumns.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Listing.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/atom.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/useListing.ts
  centreon/www/front_src/src/Dashboards/routerHooks.ts
Labels: area/ui

#3306 feat(UI): implement the Pie/Donut & Barstack component
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- adjusts size based on the provided width and height.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- conditionally displays values on rects based on displayValues prop.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- displays Legend component based on displayLegend prop.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- displays a message No Data Available when all values are null.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- displays the title when the title is giving.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- displays tooltip with correct information on hover.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- displays values on rects in percentage unit when displayValues is set to true and unit to percentage.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- renders Bar stack correctly with provided data.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- renders as a horizontal bar when variant is set to horizontal.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarStack/BarStack.cypress.spec.tsx/Bar stack -- renders as a vertical bar when variant is set to vertical.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- adjusts outer radius when chart dimensions are too small.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- adjusts size based on the provided width and height.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- conditionally displays values on arcs based on displayValues prop.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- displays Legend component based on displayLegend prop.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- displays a message No Data Available when all values are null.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- displays the title when the title is giving.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- displays tooltip with correct information on hover.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- displays values on arcs in percentage unit when displayValues is set to true and unit to percentage.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- renders as a donut when variant is set to donut.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- renders as a pie when variant is set to pie.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/PieChart/PieChart.cypress.spec.tsx/Pie chart -- renders pie chart correctly with provided data.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/BarStack/BarStack.cypress.spec.tsx
  centreon/packages/ui/src/Graph/BarStack/BarStack.stories.tsx
  centreon/packages/ui/src/Graph/BarStack/BarStack.styles.ts
  centreon/packages/ui/src/Graph/BarStack/BarStack.tsx
  centreon/packages/ui/src/Graph/BarStack/ResponsiveBarStack.tsx
  centreon/packages/ui/src/Graph/BarStack/index.ts
  centreon/packages/ui/src/Graph/BarStack/models.ts
  centreon/packages/ui/src/Graph/BarStack/useResponsiveBarStack.ts
  centreon/packages/ui/src/Graph/Legend/Legend.tsx
  centreon/packages/ui/src/Graph/Legend/index.ts
  centreon/packages/ui/src/Graph/Legend/models.ts
  centreon/packages/ui/src/Graph/PieChart/PieChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/PieChart/PieChart.stories.tsx
  centreon/packages/ui/src/Graph/PieChart/PieChart.styles.ts
  centreon/packages/ui/src/Graph/PieChart/PieChart.tsx
  centreon/packages/ui/src/Graph/PieChart/ResponsivePie.tsx
  centreon/packages/ui/src/Graph/PieChart/index.ts
  centreon/packages/ui/src/Graph/PieChart/models.ts
  centreon/packages/ui/src/Graph/PieChart/useResponsivePie.ts
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/packages/ui/src/Graph/translatedLabels.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
Labels: area/ui

#3424 fix(legacy): fix sql request and method parameters
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: area/backend

#3335 enh(api): return error when token is_revoked is true
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbReadTokenRepositoryInterface.php
  centreon/www/api/external.php
Labels: area/backend

#3429 fix (web): SSO Bug (#3330)
  centreon/src/Security/WebSSOAuthenticator.php
Labels: backport

#3434 fix (web): SSO Bug (#3330)
  centreon/src/Security/WebSSOAuthenticator.php
Labels: backport

#3277 feat(resource-access): add new endpoint to update a resource access rule
  centreon/doc/API/centreon-cloud-api-v24.04.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/AddAndFindRules.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/FindAndUpdateRule.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/Schema/AddOrUpdateRuleRequest.yaml
  centreon/src/Core/ResourceAccess/Application/Exception/RuleException.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRulePresenterInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleRequest.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleValidation.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRulePresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleRoute.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleSchema.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRulePresenterStub.php
Labels: area/backend

#3428 sync: cloud-gaps code sync on develop
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset filters button when two dataset filters are selected, the button disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset filters button when two dataset filters are setup, the button disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset icon when two datasets are selected, the icon disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset icon when two datasets are setup, the icon dissappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset filters button is visible when at least two dataset filters are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset filters button is visible when at least two dataset filters are setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset icon is visible when at least two datasets are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Delete dataset icon is visible when at least two datasets are setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are disabled when resource type and/or resources in dataset are not selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are enabled when a dataset is filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are enabled when a dataset is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons is disabled when resource type and/or resources in dataset are not selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and Add new dataset button is enabled when a dataset for metaservice is setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and Add new dataset button is enabled when a dataset for service is setup.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter button is disabled and the Add new dataset button is enabled when a dataset for a service is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Save button is activated when the form is filled and error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- displays the form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- sends a request to add a new Resource Access Rule with the form values when the Save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- confirms that the Save button becomes enabled when a modification occurs and the form is error-free.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays configured contacts and contact groups for the Resource Access Rule.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays configured resources for the Resource Access Rule.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays the edit resource access rule modal and control actions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the Save's button initial state is set to disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the form handles an empty name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- ensures that the form handles an existing name field correctly by showing an error message and disabling the Save button as a validation measure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- sends a request to edit a Resource Access Rule when a configured value is changed and the Save button is clicked.snap.png
  centreon/doc/API/v24.04/Configuration/Service/AddServiceAndFindServices.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useFormSubmit.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/initialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/useFormInitialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/FormInputs.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/AddDatasetButton.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilterDivider.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilters.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/ResourceSelection.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/AddDatasetButton.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilter.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilterDivider.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilters.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DeleteDatasetButton.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/useFormInputs.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/api/decoders.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/useResourceAccessRuleModal.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Listing.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/useListing.ts
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
  centreon/www/install/php/Update-23.10.5.php
Labels: area/backend

#3441 fix(clapi) remove duplicate when exporting service/host templates (#3233)
  centreon/www/class/centreon-clapi/centreonExported.class.php
  centreon/www/class/centreon-clapi/centreonHostTemplate.class.php
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: backport

#3442 fix(legacy): fix sql request and method parameters (#3424)
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: backport

#2677 Create first feature file for Api Token
  centreon/tests/e2e/features/Api-Token/01-api-token-create.feature
  centreon/tests/e2e/features/Api-Token/02-api-token-listing.feature
  centreon/tests/e2e/features/Api-Token/03-api-token-sorting.feature
  centreon/tests/e2e/features/Api-Token/04-api-token-delete.feature
  centreon/tests/e2e/features/Api-Token/05-api-token-acl-rights.feature
  centreon/tests/e2e/features/Api-Token/06-api-token-filter.feature
Labels: area/test

#3418 enh(UI): Make fullscreen great again
  .github/workflows/cypress-component-parallelization.yml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
  centreon/packages/ui/src/utils/useFullscreen/atoms.ts
  centreon/packages/ui/src/utils/useFullscreen/index.ts
  centreon/packages/ui/src/utils/useFullscreen/translatedLabels.ts
  centreon/packages/ui/src/utils/useFullscreen/useFullscreen.ts
  centreon/packages/ui/src/utils/useFullscreen/useFullscreenListener.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/App/index.tsx
  centreon/www/front_src/src/Header/UserMenu/index.tsx
  centreon/www/front_src/src/Header/UserMenu/translatedLabels.ts
  centreon/www/front_src/src/Header/index.tsx
  centreon/www/front_src/src/Header/specs/Header.UserMenu.tsx
Labels: area/ui

#3444 fix(legacy): fix sql request and method parameters (#3424)
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
Labels: backport

#3446 Fix(UI): Change internal panel options update (#3322)
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
Labels: backport

#3447 enh(UI): Make fullscreen great again (#3418)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
  centreon/packages/ui/src/utils/useFullscreen/atoms.ts
  centreon/packages/ui/src/utils/useFullscreen/index.ts
  centreon/packages/ui/src/utils/useFullscreen/translatedLabels.ts
  centreon/packages/ui/src/utils/useFullscreen/useFullscreen.ts
  centreon/packages/ui/src/utils/useFullscreen/useFullscreenListener.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/App/index.tsx
  centreon/www/front_src/src/Header/UserMenu/index.tsx
  centreon/www/front_src/src/Header/UserMenu/translatedLabels.ts
  centreon/www/front_src/src/Header/index.tsx
Labels: backport

#3358 fix(api) listing hosts withtout alias
  centreon/doc/API/v24.04/Configuration/Host/Schema/AddHostResponse.yaml
  centreon/src/Core/Host/Domain/Model/SmallHost.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/FindHosts/FindHostsOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/FindHosts/FindHostsSaasPresenter.php
  centreon/tests/php/Core/Host/Domain/Model/SmallHostTest.php
Labels: area/backend

#3443 fix(clapi) remove duplicate when exporting service/host templates (#3233)
  centreon/www/class/centreon-clapi/centreonExported.class.php
  centreon/www/class/centreon-clapi/centreonHostTemplate.class.php
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
Labels: backport

#3458 fix(api) listing hosts withtout alias (#3358)
  centreon/doc/API/v23.10/Configuration/Host/Schema/AddHostResponse.yaml
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/FindHosts/FindHostsOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/FindHosts/FindHostsSaasPresenter.php
  centreon/tests/php/Core/Host/Domain/Model/TinyHostTest.php
Labels: backport

#3426 enh(UI): Improve dashboard responsiveness
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- No widgets -- does not display widgets when any widgets are registered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Unrecognized widget property -- does not display the widget property when it is not recognized.snap.png
  centreon/packages/ui/src/InputField/Select/Autocomplete/index.tsx
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/addWidget.styles.ts
Labels: area/ui

#3449 fix(export) remove warning when exporting broker bbdo server cfg
  centreon/www/class/config-generate/broker.class.php
Labels: area/backend

#3346 fix(api) fix downtime recuperation when getting a host resource detail
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbHostFactory.php
  centreon/src/Core/Infrastructure/RealTime/Repository/Host/DbReadHostRepository.php
Labels: area/backend

#3348 fix(api): addHostTemplate and addHost mixing severities and categories in response
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
Labels: area/backend

#3466 Fix(Widget): Fix link to resources status
  centreon/tests/e2e/features/Resources-status/03-downtime.feature
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/Columns/Columns.styles.ts
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/Columns/Name.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/Columns/Statuses/Status.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/GroupMonitoring.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/utils.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/Tile.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/MetricTop.tsx
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#3450 enh(UI): Use modal for delete actions on Dashboard
  centreon/cypress/fixtures/Dashboards/Dashboard/details.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Add widget -- adds a widget when a widget type is selected and the submission button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- deletes a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not displays the name of the widget a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Duplicate -- duplicates the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the refresh button when the more actions button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- displays a warning message indicating unsaved changes in the dashboard when updating it.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- displays the title and the description in the panel.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- sends a shares update request when the shares are update and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/DashboardLayout.cypress.spec.tsx/DashboardLayout -- displays the dashboard from a standalone component.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/tests/e2e/features/Dashboards/04-dashboard-deletion/index.ts
  centreon/tests/e2e/features/Dashboards/05-dashboard-check-permissions/index.ts
  centreon/tests/e2e/features/Dashboards/09-widget-single-metric-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/12-status-grid-widget-configuration/index.ts
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/DashboardsPage.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/components/DeleteWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/atoms.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/Actions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/DeleteDashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DeleteDashboardModal.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
Labels: area/ui

#3086 fix(api) check user rights and pageName validity in userFilter endpoints
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Application/Controller/FilterController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/tests/api/features/UserFilter.feature
Labels: area/backend
