Repository centreon/centreon, pull requests merged in 2024-05, with the labels that each got.

#3985 enh(NPM): Adapt NPM publication according to cloud versioning
  .github/actions/get-latest-npm-branch-version/index.js
  .github/actions/npm-publish-package-stable/action.yml
  centreon/packages/js-config/package.json
  centreon/packages/ui-context/package.json
  centreon/packages/ui/package.json
  centreon/packages/ui/src/TopCounterElements/useCloseOnLegacyPage.tsx
Labels: area/ui

#3966 enh(Administration): Remove autofill for credentials in forms (#3963) [dev-24.04.x]
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/Administration/parameters/gorgone/gorgone.php
  centreon/www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.php
Labels: area/backend

#3885 fix(contact): added API access based on ACLs
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Contact/Application/Exception/ContactTemplateException.php
  centreon/src/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplates.php
  centreon/tests/api/features/ConfigurationContactTemplates.feature
  centreon/tests/php/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplatesTest.php
Labels: area/backend

#3954 fix(config): avoid request parameters overwrite issues (#3931)
  centreon/config/packages/Centreon.yaml
Labels: area/backend

#4015 fix(ceip): correctly handle widgets with no metric data
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#3990 enh(dashboard): refactor the dataset section to support resource tree
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- confirms that the 'Add Filter' button is disabled when the 'Service' type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- ensures that all resource types are available in the first line item of the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- removes all subsequent resource lines, if a resource type line in the middle of the tree is updated.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#4020 fix(ceip): correctly handle widgets with no metric data (#4015)
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#4024 fix(contact): added API access based on ACLs
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Contact/Application/Exception/ContactTemplateException.php
  centreon/src/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplates.php
  centreon/tests/api/features/ConfigurationContactTemplates.feature
  centreon/tests/php/Core/Contact/Application/UseCase/FindContactTemplates/FindContactTemplatesTest.php
Labels: area/backend

#4025 fix(services): fix an issue on service massive change
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3953 feat(ci): Implement e2e tests for R.A.M - Listing rules
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing.feature
  centreon/tests/e2e/features/Resources-Access-Management/01-rules-listing/index.ts
  centreon/tests/e2e/features/Resources-Access-Management/commands.ts
  centreon/tests/e2e/support/e2e.ts
Labels: area/test

#4004 enh(dashboard) : update wording in some widgets
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/DisplayType/DisplayType.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/DisplayType/DisplayType.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
Labels: area/ui

#4041 fix(host_group): fix host group listing query
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#4032 feat(ci): Gherkin for Resource Access Management feature
  centreon/tests/e2e/features/Resources-Access-Management/02-rules-management.feature
  centreon/tests/e2e/features/Resources-Access-Management/02-rules-management/index.ts
Labels: area/test

#4018 fix([Resource Status]): Add possibility to filter by type of resources
  centreon/cypress/fixtures/resources/filter/hostCategory.json
  centreon/cypress/fixtures/resources/filter/hostGroups.json
  centreon/cypress/fixtures/resources/filter/hostSeverity.json
  centreon/cypress/fixtures/resources/filter/pollers.json
  centreon/cypress/fixtures/resources/filter/resourcesByHostType.json
  centreon/cypress/fixtures/resources/filter/resourcesByServiceType.json
  centreon/cypress/fixtures/resources/filter/webAccessServiceGroup.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays more criterias interface when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays the basic criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- does not display the host select and host statuses when the view by host is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host category criteria value when Extended criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host group criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host severity criteria value when Extended criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Monitoring server criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Service criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Service group criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected State criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Status criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Type criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx/Filter storage -- populates filter with values from localStorage if available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx/Filter storage -- stores filter values in localStorage when updated.snap.png
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/index.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/CheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/MemoizedCheckBox.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/MemoizedPoller.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/actions/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/checkBox.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/useCheckBox.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/useSynchronizeSearchBarWithCheckBoxInterface.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedInputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedSelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedStatus.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/sections.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/criterias.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedCheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedInputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedSelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/model.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/useInputsData.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/utils.ts
Labels: area/ui

#4027 Enh(UI): Display a message when the dashboard belongs to any playlist
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that on click of Delete dataset filters button when two dataset filters are selected, the button disappears.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- confirms that the Refine filter and Add new dataset buttons are disabled when resource type and/or resources in dataset are not selected.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/js-config/rspack/base/index.js
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DeleteDashboardModal.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
Labels: area/ui

#4043 enh(UI): Improves curves reading by changing their shade
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/src/Dashboard/utils.ts
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/RegularLines/index.tsx
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/StackedLines/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/LineChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/LineChart/index.stories.tsx
  centreon/packages/ui/src/Graph/LineChart/mockedData/curvesWithSameColor.json
  centreon/packages/ui/src/Graph/LineChart/useLineChartData.ts
  centreon/packages/ui/src/Graph/common/utils.ts
Labels: area/ui

#4059 enh(dashboards): remove option to open link in new window
  centreon/cypress/fixtures/Dashboards/Dashboard/detailsWithData.json
  centreon/lighthouse/src/fixtures/dashboardPanels.js
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithGroupMonitoringWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithResourceTableWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithStatusChartWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTopBottomWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoGroupMonitoringWidgets.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoStatusChartWidgets.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoTopBottomWidgets.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoWidgets.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwometricsGraphWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwostatusGrid.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/metricsGraphWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/singleMetricPayloadPl.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/singleMetricPayloadRta.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/status-grid-widget.json
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/RichTextEditor.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useValidationSchema.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
Labels: area/ui

#4095 Fix(UI): Sanitize preload script URL for Cloud
  centreon/www/front_src/src/federatedModules/utils.ts
Labels: area/ui

#4100 Fix(UI): Sanitize preload script URL for Cloud (#4095)
  centreon/www/front_src/src/federatedModules/utils.ts
Labels: area/ui, backport

#4076 chore(deps): absorb May-24 dependabot dependencies
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-gorgone-testing.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/get-version.yml
  .github/workflows/gorgone.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#4102 enh(dashboard): move WidgetDataProviderInterface from module to Core
  centreon/config/packages/Centreon.yaml
  centreon/config/packages/security.yaml
  centreon/src/Core/Dashboard/Application/Repository/WidgetDataProviderInterface.php
Labels: area/backend

#4162 chore: Cut off public routes manager
  centreon/www/front_src/src/Main/Main.cypress.spec.tsx
  centreon/www/front_src/src/Main/Provider.tsx
Labels: area/ui

#4086 enh(dashboard) : resources table widget: move display type from properties to the widget content
  centreon/packages/ui/src/Listing/ActionBar/index.tsx
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/DisplayType.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/Option.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/displayType.styles.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_all_actif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_all_inactif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_host_actif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_host_inactif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_service_actif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/icons/view_service_inactif.svg
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/index.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
Labels: area/ui

#4144 enh(dashboards): widget dataset : use RS endpoint for host filtering
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#4090 enh(UI): Add refresh indicator on panel
  centreon/packages/ui/src/Module/index.tsx
  centreon/packages/ui/src/api/QueryProvider.tsx
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/index.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/GroupMonitoring.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/index.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/useGroupMonitoring.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useLoadResources.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/ResourcesTable.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/index.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/index.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/StatusChart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/index.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/models.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/useLoadResources.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/StatusGridCondensed.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/useStatusGridCondensed.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/index.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
  centreon/www/widgets/src/models.ts
Labels: area/ui

#4084 fix(api) Fix check non-admin user action rights on post and delete platform/topology endpoint
  centreon/config/routes/Centreon/platform.yaml
  centreon/src/Centreon/Application/Controller/PlatformTopologyController.php
  centreon/src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyReadRepositoryInterface.php
  centreon/src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  centreon/src/Centreon/Infrastructure/PlatformTopology/Repository/PlatformTopologyRepositoryRDB.php
  centreon/tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
Labels: area/backend

#4072 feat(App token): Enable / disable token in listing
  centreon/cypress/fixtures/apiTokens/listing/listAfterRevoke.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx/Api-token -- displays an error message upon failed revoking of a token.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx/Api-token -- revokes an API token when Activate/ Revoke token is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Api-Token/02-api-token-listing.feature
  centreon/tests/e2e/features/Api-Token/02-api-token-listing/index.ts
  centreon/tests/e2e/features/Api-Token/03-api-token-sorting.feature
  centreon/tests/e2e/features/Api-Token/common.ts
  centreon/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/Actions/Deletion/ConfirmationDeletionModal.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/Activate.tsx
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/models.ts
  centreon/www/front_src/src/ApiTokens/TokenListing/ComponentsColumn/useColumns.tsx
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
  centreon/www/front_src/src/ApiTokens/translatedLabels.ts
Labels: documentation, area/ui

#4117 fix (graph template): Fixed SQL query for creating or updating a graph template
  centreon/www/include/views/graphTemplates/DB-Func.php
Labels: area/backend

#4161 fix (downtime): SQL query fixed when adding recurring downtime
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#4128 fix (update_centreon_storage_logs): Rename $path variable
  centreon/tools/update_centreon_storage_logs.php
Labels: area/backend

#4136 enh(dashboards): reduce the payload when a widget handles resources
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
Labels: area/ui

#4172 Fix(UI): Fix public endpoints
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#4171 enh(host_categories): add search capabilities to host categories endp…
  centreon/config/routes/Centreon/monitoring/category.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/src/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategory.php
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/Repository/ReadRealTimeHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenterInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesResponse.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesController.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesRoute.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryPresenterStub.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenterStub.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesTest.php
Labels: area/backend

#4176 enh(service_categories): add search capabilities to monitoring endpoint
  centreon/config/routes/Centreon/monitoring/category.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/src/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategory.php
  centreon/src/Core/ServiceCategory/Application/Exception/ServiceCategoryException.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadRealTimeServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategories.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenterInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesResponse.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesController.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenter.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesRoute.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadRealTimeServiceCategoryRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryPresenterStub.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryTest.php
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenterStub.php
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesTest.php
Labels: area/backend

#4164 chore: Cut off public routes manager (#4162)
  centreon/www/front_src/src/Main/Main.cypress.spec.tsx
  centreon/www/front_src/src/Main/Provider.tsx
Labels: area/ui

#4189 Fix(test): Fix column sorting tests
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays acknowledgement details when an acknowledged state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding action_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding checks menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding fqdn menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding monitoring_server_name menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notes_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notification menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding parent_alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding severity menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays downtime details when the downtime state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with a limit param when the rows per page value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- displays notification column if the cloud notification feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- hides notification column if the cloud notification feature is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays a highlighted row when a resource is in a critical state.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays first part of information when multiple (split by ) are available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in compact mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in extended mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- reorders columns when a drag handle is focused and an arrow is pressed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- displays the services when the Expand button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sends a request to retrieve all sevices and their parents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sends a request with types service,metaservice.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- enables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sends a request to get all resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sets the column names to the default ones.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sorts columnns by newest duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Tree view  Feature Flag -- hides the tree view icons if the feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Duration column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Last check column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Parent column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Resource column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Tries column is clicked.snap.png
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
Labels: area/ui

#4181 enh(service_groups): add search capabilities to host categories endpoint
  centreon/doc/API/centreon-api.yaml
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#4192 enh(API): added ACL check on host severities
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbReadHostSeverityRepository.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateValidation.php
Labels: area/backend

#4156 fix(clapi/APIv1): Output fixes
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/class/centreon-clapi/centreonCommand.class.php
  centreon/www/class/centreon-clapi/centreonHost.class.php
  centreon/www/class/centreon-clapi/centreonHostGroup.class.php
  centreon/www/class/centreon-clapi/centreonHostGroupService.class.php
  centreon/www/class/centreon-clapi/centreonObject.class.php
  centreon/www/class/centreon-clapi/centreonService.class.php
  centreon/www/class/centreon-clapi/centreonServiceGroup.class.php
  centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#4203 enh(API): added ACL checks on host severities for PATCH endpoint
  centreon/src/Core/HostCategory/Infrastructure/Repository/HostCategoryRepositoryTrait.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/tests/php/Core/HostTemplate/Application/PartialUpdateHostTemplate/PartialUpdateHostTemplateTest.php
Labels: area/backend

#4151 enh(UI): Improves curves reading by changing their shade (#4043)
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/src/Dashboard/utils.ts
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/RegularLines/index.tsx
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/Lines/StackedLines/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/LineChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/LineChart/index.stories.tsx
  centreon/packages/ui/src/Graph/LineChart/mockedData/curvesWithSameColor.json
  centreon/packages/ui/src/Graph/LineChart/useLineChartData.ts
  centreon/packages/ui/src/Graph/common/utils.ts
Labels: backport

#4206 enh(dashboard): add more curve information for performance endpoint
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/Schema/Dashboard.MetricsPerformancesData.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataPresenter.php
  centreon/src/Core/Metric/Domain/Model/MetricInformation/DataSource.php
Labels: area/backend

#4200 fix(config-generate): service categories fix the export configuration
  centreon/www/class/config-generate/severity.class.php
Labels: area/backend

#3960 fix (host): fix host listing query (#3937)
  centreon/www/include/configuration/configObject/host/listHost.php
Labels: area/backend, backport

#3969 enh (connector): update SQL queries of centreon connector form (#3847)
  centreon/www/class/centreonConnector.class.php
  centreon/www/include/configuration/configObject/connector/connector.php
  centreon/www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend, backport

#3964 enh (connector): update SQL queries of centreon connector form (#3847)
  centreon/www/class/centreonConnector.class.php
  centreon/www/include/configuration/configObject/connector/connector.php
  centreon/www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend, backport

#3967 fix(host_group): fix host group listing query (#3945)
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend, backport

#3972 fix(host_group): fix host group listing query (#3945)
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend, backport

#4003 enh(API): added ACLs check on serverities for service and service templates endpoints
  centreon/src/Core/Service/Application/UseCase/AddService/AddServiceValidation.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/ServiceCategoryRepositoryTrait.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
  centreon/tests/rest_api/collections/api-configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Template.postman_collection.json
Labels: area/backend

#4234 fix(config-generate): service categories fix the export configuration
  centreon/www/class/config-generate/severity.class.php
Labels: area/backend

#4232 fix(config-generate): service categories fix the export configuration
  centreon/www/class/config-generate/severity.class.php
Labels: area/backend

#4145 Backport([dev-24.04.x]) - [Resource Status] Add possibility to filter by type of resources
  centreon/cypress/fixtures/resources/filter/hostCategory.json
  centreon/cypress/fixtures/resources/filter/hostGroups.json
  centreon/cypress/fixtures/resources/filter/hostSeverity.json
  centreon/cypress/fixtures/resources/filter/pollers.json
  centreon/cypress/fixtures/resources/filter/resourcesByHostType.json
  centreon/cypress/fixtures/resources/filter/resourcesByServiceType.json
  centreon/cypress/fixtures/resources/filter/webAccessServiceGroup.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays more criterias interface when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays the basic criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- does not display the host select and host statuses when the view by host is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host category criteria value when Extended criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host group criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Host severity criteria value when Extended criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Monitoring server criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Service criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Service group criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected State criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- executes a listing request with current search and selected Status criteria value when Basic criterias has changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Type criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx/Filter storage -- populates filter with values from localStorage if available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx/Filter storage -- stores filter values in localStorage when updated.snap.png
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/index.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/FilterStorage.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/CheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/MemoizedCheckBox.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/MemoizedPoller.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/actions/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/checkBox.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/useCheckBox.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/useSynchronizeSearchBarWithCheckBoxInterface.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedInputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedSelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/MemoizedStatus.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/sections.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/criterias.style.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedCheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedInputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/MemoizedSelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/extendedFilter/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/model.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/useInputsData.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/utils.ts
Labels: area/ui

#4238 fix (update_centreon_storage_logs): Rename $path variable #4128
  centreon/tools/update_centreon_storage_logs.php
Labels: area/backend, backport

#4240 fix (update_centreon_storage_logs): Rename $path variable (#4128)
  centreon/tools/update_centreon_storage_logs.php
Labels: area/backend, backport

#4239 fix (update_centreon_storage_logs): Rename $path variable (#4128)
  centreon/tools/update_centreon_storage_logs.php
Labels: area/backend, backport

#4241 fix (update_centreon_storage_logs): Rename $path variable (#4128)
  centreon/tools/update_centreon_storage_logs.php
Labels: area/backend, backport

#4207 enh(hostgroups): added search capabilities for hostgroup monitoring endpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport

#4251 fix(config-generate): service categories fix the export configuration
  centreon/www/class/config-generate/severity.class.php
Labels: area/backend

#4245 fix (graph template): Fixed SQL query for creating or updating a graph template (#4117)
  centreon/www/include/views/graphTemplates/DB-Func.php
Labels: area/backend, backport

#4208 enh(service_groups): add search capabilities to host categories endpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport

#4258 update Acl endpoint
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#4261 fix (graph template): Fixed SQL query for creating or updating a graph template (#4117)
  centreon/www/include/views/graphTemplates/DB-Func.php
Labels: area/backend, backport

#4266 fix(UI): Not allowed to apply actions
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Resources/icons/Downtime.tsx
  centreon/www/front_src/src/Resources/icons/downtime.icon.svg
Labels: area/ui

#4262 fix (graph template): Fixed SQL query for creating or updating a graph template (#4117)
  centreon/www/include/views/graphTemplates/DB-Func.php
Labels: area/backend, backport

#4269 fix (downtimes): update SQL query
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#4263 fix (graph template): Fixed SQL query for creating or updating a graph template (#4117)
  centreon/www/include/views/graphTemplates/DB-Func.php
Labels: area/backend, backport

#4271 fix (downtime): SQL query fixed when adding recurring downtime (#4161)
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend, backport

#4260 fix (downtime): SQL query fixed when adding recurring downtime (#4161)
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend, backport

#4270 fix (downtime): SQL query fixed when adding recurring downtime (#4161)
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend, backport

#4265 fix (downtime): SQL query fixed when adding recurring downtime (#4161)
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend, backport

#4243 feat(services): add endpoint to list unique service names from real time
  centreon/doc/API/centreon-api.yaml
  centreon/src/Core/Service/Application/Repository/ReadRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNames.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesResponse.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesController.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenter.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesRoute.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterStub.php
Labels: area/backend

#4220 enh(API): Added ACL check on severities for FindHostTemplates endpoint
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/FindHostTemplates/FindHostTemplates.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/tests/php/Core/HostTemplate/Application/FindHostTemplates/FindHostTemplatesTest.php
Labels: area/backend

#4276 fix (downtimes): update SQL query
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#4209 enh(host_categories): add search capabilities to host categories endpoint
  centreon/config/routes/Centreon/monitoring/category.yaml
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategory.php
  centreon/src/Core/HostCategory/Application/Exception/HostCategoryException.php
  centreon/src/Core/HostCategory/Application/Repository/ReadRealTimeHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenterInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesResponse.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesController.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenter.php
  centreon/src/Core/HostCategory/Infrastructure/API/FindRealTimeHostCategories/FindRealTimeHostCategoriesRoute.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryPresenterStub.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindHostCategory/FindHostCategoryTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesPresenterStub.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesTest.php
Labels: area/backend, backport

#4275 fix (downtimes): update SQL query
  centreon/www/class/centreonDowntime.class.php
Labels: area/backend

#4224 fix(RAM): Cannot link hostgroup to a host
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#4282 fix(RAM): Cannot duplicate rule
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/adapters.ts
Labels: area/ui

#4210 enh(service_categories): add search capabilities to monitoring endpoint
  centreon/config/routes/Centreon/monitoring/category.yaml
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategory.php
  centreon/src/Core/ServiceCategory/Application/Exception/ServiceCategoryException.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadRealTimeServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/Repository/ReadServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategories.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenterInterface.php
  centreon/src/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesResponse.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesController.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenter.php
  centreon/src/Core/ServiceCategory/Infrastructure/API/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesRoute.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadRealTimeServiceCategoryRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryPresenterStub.php
  centreon/tests/php/Core/Category/RealTime/Application/UseCase/FindServiceCategory/FindServiceCategoryTest.php
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesPresenterStub.php
  centreon/tests/php/Core/ServiceCategory/Application/UseCase/FindRealTimeServiceCategories/FindRealTimeServiceCategoriesTest.php
Labels: area/backend, backport

#4284 fix(RAM): Cannot link hostgroup to a host (#4224)
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#4231 enh(UI): Handle Meta service on dashboard
  centreon/cypress/fixtures/Widgets/ResourcesTable/resourcesStatus.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides metrics field when the Meta service resource type is selected and the Meta service is chosen.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- No widgets -- does not display widgets when any widgets are registered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays general properties when a widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- hides a property when an option value matches the condition.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Unrecognized widget property -- does not display the widget property when it is not recognized.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- adds a new filter line when the first resource line is fullfilled add the button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding is clicked and corresponding prop are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- displays host and service type when the corresponding atom is set to true.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- displays only the restricted resource types when the propety is defined.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- does not displays resource types when they are excluded fromn selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- confirms that the 'Add Filter' button is disabled when the 'Service' type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- disables the Add filter button when a meta service is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- ensures that all resource types are available in the first line item of the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- removes all subsequent resource lines, if a resource type line in the middle of the tree is updated.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/GroupMonitoring.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/DisplayType.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/DisplayType/Option.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/testUtils.ts
  centreon/www/widgets/src/centreon-widget-statuschart/properties.json
  centreon/www/widgets/src/centreon-widget-statusgrid/properties.json
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/testUtils.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#4228 enh(dashboard): add more curve information for performance endpoint (#4206)
  centreon/doc/API/v24.04/Configuration/Dashboard/Schema/Dashboard.MetricsPerformancesData.yaml
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataPresenter.php
  centreon/src/Core/Metric/Domain/Model/MetricInformation/DataSource.php
Labels: area/backend, backport

#4281 feat(services): add endpoint to list unique service names from real time (#4243)
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/Service/Application/Repository/ReadRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNames.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesResponse.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesController.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenter.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesRoute.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterStub.php
Labels: area/backend, backport

#4150 Fix(UI): Resolve cannot load module error
  centreon/www/front_src/src/federatedModules/useFederatedModules.ts
  centreon/www/front_src/src/federatedModules/useFederatedWidgets.ts
Labels: area/ui, backport
