Repository centreon/centreon, pull requests merged in 2024-10, with the labels that each got.

#4979 enh(Change Logs): Insert change logs for /configuration/hosts/groups endpoints (#4952) [dev-24.04.x]
  centreon/src/Core/Host/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
Labels: area/backend, backport

#5117 fix(Resource Status): Anomaly detection services (#4975) [dev-23.10.x]
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/front_src/src/Resources/Details/tabs/Services/index.tsx
Labels: area/ui, area/backend, backport

#5170 fix(Configuration): Notification time period defined upon host creation gets copied to deployed services (#5031) [dev-23.10.x]
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend, backport

#5069 fix(API): Creation of resources (hosts and services) are not visible by a non administrator (#5050) [dev-23.10.x]
  centreon/src/Core/Host/Application/Repository/WriteRealTimeHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteRealTimeHostRepository.php
  centreon/src/Core/Service/Application/Repository/WriteRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteRealTimeServiceRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/Service/Application/UseCase/AddService/AddServiceTest.php
Labels: area/backend, backport

#5191 fix(eventLogs): wording
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/eventLogs/viewLog.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend

#5068 fix(API): Creation of resources (hosts and services) are not visible by a non administrator (#5050) [dev-24.04.x]
  centreon/src/Core/Host/Application/Repository/WriteRealTimeHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteRealTimeHostRepository.php
  centreon/src/Core/Service/Application/Repository/WriteRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteRealTimeServiceRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/Service/Application/UseCase/AddService/AddServiceTest.php
Labels: area/backend, backport

#5168 fix(Configuration): Notification time period defined upon host creation gets copied to deployed services (#5031) [dev-24.04.x]
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend, backport

#5046 fix(Resource Status): Anomaly detection services (#4975) [dev-24.04.x]
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/front_src/src/Resources/Details/tabs/Services/index.tsx
Labels: area/ui, area/backend, backport

#5137 chore(E2E) : Fix update e2e test on dev-24.04.x
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
Labels: area/test

#5217 enh(dashboard): resources table open ticket UX and wording enhancements
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/widgets/src/centreon-widget-clock/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Actions/DisplayType/Icons.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Actions/DisplayType/Option.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/CloseTicket/CloseTicket.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/CloseTicket/Modal.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/models.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
Labels: area/ui

#5193 fix (translation): fix upper case in all translations for Graph/logs periods (#4941)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/eventLogs/viewLog.php
  centreon/www/include/reporting/dashboard/common-Func.php
  centreon/www/include/views/graphTemplates/formGraphTemplate.php
  centreon/www/include/views/graphs/graph-split.php
  centreon/www/include/views/graphs/graphs.php
Labels: area/backend

#5194 fix (translation): fix upper case in all translations for Graph/logs periods (#4941)
  centreon/composer.lock
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/eventLogs/viewLog.php
  centreon/www/include/reporting/dashboard/common-Func.php
  centreon/www/include/views/graphTemplates/formGraphTemplate.php
  centreon/www/include/views/graphs/graph-split.php
  centreon/www/include/views/graphs/graphs.php
Labels: area/backend

#5155 fix : backport problems fixed for CentreonDB and CentreonLog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
Labels: area/backend, backport

#5156 fix : backport problems fixed for CentreonDB and CentreonLog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
Labels: area/backend, backport

#5157 fix : backport problems fixed for CentreonDB and CentreonLog
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/packages/js-config/cypress/e2e/commands/monitoring.ts
  centreon/tests/e2e/commons.ts
  centreon/tests/e2e/features/Dashboards/09-widget-single-metric-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/11-widget-top-bottom-configuration/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/support/commands.ts
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
Labels: area/backend, backport

#5158 fix : backport problems fixed for CentreonDB and CentreonLog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
Labels: area/backend, backport

#5136 fix (open-ticket): fix sql request (#5048)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
Labels: backport

#5138 fix (open-ticket): fix sql request (#5048)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
Labels: backport

#5139 fix (open-ticket): fix sql request (#5048)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
Labels: backport

#5054 fix(admin) display actual meta_service name (#4954)
  centreon/www/include/Administration/performance/viewData.php
Labels: backport

#5222 Fix(UI): Fix bottom axis dates
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bottom axis correctly when data starts from several days ago.snap.png
  centreon/packages/ui/src/Graph/BarChart/BarChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/common/Axes/index.tsx
Labels: area/ui

#5221 test(api): cleaning folder not used and rewrited on API Testing
  centreon/tests/api/features/ConfigurationUsersWithOpenApi.feature
  centreon/tests/api/features/Notification.feature
Labels: area/test

#5077 fix(macros): Correctly set all host macros in on_demand_macro_host.infile (#4937)
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/config-generate-remote/Abstracts/AbstractHost.php
  centreon/www/class/config-generate-remote/Relations/MacroHost.php
Labels: backport

#5134 feat(UI) : implement the timeline graph
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Timeline/Timeline.cypress.spec.tsx/Timeline -- checks that the correct number of bars are rendered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Timeline/Timeline.cypress.spec.tsx/Timeline -- displays tooltip with correct information when hovered over a bar.snap.png
  centreon/packages/ui/src/Graph/Timeline/ResponsiveTimeline.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.stories.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.tsx
  centreon/packages/ui/src/Graph/Timeline/index.ts
  centreon/packages/ui/src/Graph/Timeline/models.ts
  centreon/packages/ui/src/Graph/Timeline/timeline.styles.ts
  centreon/packages/ui/src/Graph/Timeline/translatedLabel.ts
  centreon/packages/ui/src/Graph/Timeline/useTimeline.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/pnpm-lock.yaml
Labels: area/ui

#5227 fix(Security): fix the fields on loggerDetailview
  centreon/www/include/Administration/configChangelog/viewLogsDetails.ihtml
Labels: area/backend

#5076 fix(macros): Correctly set all host macros in on_demand_macro_host.infile (#4937)
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/config-generate-remote/Abstracts/AbstractHost.php
  centreon/www/class/config-generate-remote/Relations/MacroHost.php
Labels: backport

#5187 fix(configuration): remove deprecated macros & add new ones
  centreon/www/install/insertMacros.sql
  centreon/www/install/php/Update-24.10.1.php
Labels: area/backend

#5189 fix(configuration): manage the visibility of log options
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configNagios/formNagios.ihtml
Labels: area/backend

#5273 Fix(UI): Fix clickable links on custom login page
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/www/front_src/src/Login/CustomText.tsx
Labels: area/ui

#5284 Fix(UI): Fix clickable links on custom login page (#5273)
  centreon/packages/ui/src/RichTextEditor/ContentEditable.tsx
  centreon/www/front_src/src/Login/CustomText.tsx
Labels: area/ui, backport

#5231 feat(AC): Add An Endpoint to find AC Detail
  centreon/config/symfony_serializer/AgentConfiguration/AgentConfiguration.yaml
  centreon/config/symfony_serializer/AgentConfiguration/FindAgentConfigurationResponse.yaml
  centreon/config/symfony_serializer/AgentConfiguration/Poller.yaml
  centreon/config/symfony_serializer/AgentConfiguration/TelegrafConfigurationParameters.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/DeleteAndUpdateAndFindDetailAc.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/GetAcResponse.yaml
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationResponse.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/FindAgentConfiguration/FindAgentConfigurationController.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/FindAgentConfiguration/FindAgentConfigurationRoute.yaml
  centreon/src/Core/AgentConfiguration/Infrastructure/Serializer/FindAgentConfigurationResponseNormalizer.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Serializer/TelegrafConfigurationParametersNormalizer.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Voters/AgentConfigurationVoter.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurationsTest.php
Labels: area/backend

#5289 enh(map): Change window size lime in cypress config
  centreon/packages/js-config/cypress/component/configuration.js
Labels: area/ui

#5230 feat(dashboards): Add federated component for BA timeline widget
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/widgets/src/NoResources.tsx
  centreon/www/widgets/src/centreon-widget-batimeline/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-batimeline/properties.json
  centreon/www/widgets/src/centreon-widget-batimeline/src/index.tsx
  centreon/www/widgets/src/centreon-widget-batimeline/src/models.ts
  centreon/www/widgets/src/centreon-widget-batimeline/src/translatedLabels.ts
Labels: area/ui

#5293 fix (update): merge the 24.10.1 update script into 24.10.0
  centreon/www/install/php/Update-24.10.0.php
  centreon/www/install/php/Update-24.10.1.php
Labels: area/backend

#5256 fix(graph): fix blank page when user adds & updates a curve on mysql
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
Labels: area/backend

#5291 enh(sql) move AC sql to Update-24.10.1 script
  centreon/www/install/php/Update-24.10.1.php
Labels: area/backend

#5303 fix(acc) fix menu order for display for ACC (#5288)
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.10.0.php
Labels: area/backend

#4793 feat(test): Add automated tests for ACC
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation.feature
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing.feature
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion.feature
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update.feature
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions.feature
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/acc-acl-user.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-1.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-2.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-3.json
  centreon/tests/e2e/fixtures/users/user-non-admin-for-ACC.json
  centreon/tests/e2e/support/e2e.ts
Labels: area/test

#5243 [E2E] Rewrite HostConfiguration.feature
  centreon/behat.yml
  centreon/features/HostConfiguration.feature
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/tests/e2e/features/Hosts/01-host-configuration.feature
  centreon/tests/e2e/features/Hosts/01-host-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5313 backport(test): Add automated tests for ACC in 24.10
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation.feature
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing.feature
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion.feature
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update.feature
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions.feature
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/acc-acl-user.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-1.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-2.json
  centreon/tests/e2e/fixtures/resources/clapi/pollers/poller-3.json
  centreon/tests/e2e/fixtures/users/user-non-admin-for-ACC.json
  centreon/tests/e2e/support/e2e.ts
Labels: area/test, backport

#5235 enh(AC) handle type CMA
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/AddAcRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/UpdateAcRequest.yaml
  centreon/src/Core/AgentConfiguration/Application/Factory/AgentConfigurationFactory.php
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/Type.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/AddAgentConfiguration/AddAgentConfigurationController.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/AddAgentConfiguration/AddAgentConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/API/UpdateAgentConfiguration/UpdateAgentConfigurationController.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/UpdateAgentConfiguration/UpdateAgentConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbReadAgentConfigurationRepository.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/ValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/ValidatorTest.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-24.10.0.php
Labels: area/backend

#5314 fix(dashboards): Fix Cypress test failure in nightly build
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Add widget -- adds a widget when a widget type is selected and the submission button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dataset -- displays header link to Business activity when the widget has only business activities.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- deletes a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not display the name of the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Duplicate -- duplicates the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- resizes the widget to its minimum size when the handle is dragged.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- does not save changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- saves changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the refresh button when the more actions button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- sends a shares update request when the shares are update and the corresponding button is clicked.snap.png
Labels: area/ui

#5300 enh(vault): Manage Gorgone Credential file on fresh install and migration
  centreon/bin/migrateCredentials.php
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/www/include/common/vault-functions.php
  centreon/www/install/steps/process/process_step9.php
Labels: area/backend

#5305 ENH([Resource Status]): status_type filter doesn't work in capital letters
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/suggestion for state static filter.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/suggestion for status static filter.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/suggestion for status_type static filter.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/suggestion for type static filter.snap.png
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
Labels: area/ui

#5321 fix(packaging): move plugins from suggests to recommends (#5318)
  centreon/packaging/centreon-poller.yaml
Labels: backport

#5320 enh(AC): replace class serializer by an interface serializer to handle all the ConfigurationParameters
  centreon/src/Core/AgentConfiguration/Infrastructure/Serializer/ConfigurationParametersInterfaceNormalizer.php
Labels: area/backend

#5261 chore(deps): absorb 24.10 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/clean-up-npm-tag/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/clean-cache.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/get-version.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/newman.yml
  .github/workflows/nightly-cod-platform-deploy.yml
  .github/workflows/nightly-cod-platform-destroy.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/release.yml
  .github/workflows/synchronize-branches.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/synchronize-next-major-branches.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#5309 fix(dashboard): Listing action bar and colomn actions should not be visible in public playlist
  centreon/packages/ui/src/Listing/index.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/Status.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/useColumns.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
Labels: area/ui

#5324 enh(tests): Rewrite ServiceCategoryConfiguration.feature
  centreon/behat.yml
  centreon/features/ServiceCategoryConfiguration.feature
  centreon/features/bootstrap/ServiceCategoryConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration.feature
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration/index.ts
Labels: area/test

#5308 fix(dashboards): Playlist Disappears After Search Input and Navigation
  centreon/tests/e2e/features/Dashboards/07-dashboard-manage-permissions/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/DashboardsFilter.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/Filter.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/translatedLabels.ts
Labels: area/ui

#5310 fix(dashboard): error display when setting display to 0 in top bottom widget
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx/TopBottomSettings -- displays the number of values when the value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx/TopBottomSettings -- enforces the value to be 1 when the user manually enters 0.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/useTopBottomSettings.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
Labels: area/ui

#5343 fix(test): serviceCategory.feature
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration/index.ts
Labels: area/test

#5338 enh(cma): update endpoints for type CMA
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/www/install/php/Update-24.11.0.php
Labels: area/backend

#5132 fix(graph): dashboard invalid metric format fixed (#5119)
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
Labels: area/backend, backport

#5131 fix(graph): dashboard invalid metric format fixed (#5119)
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
Labels: area/backend, backport

#5344 Fix(UI): Apply backend changes on CMA
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfigurations.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
Labels: area/ui

#5285 enh(tests): Rewrite ConfigurationWarnings.feature
  centreon/behat.yml
  centreon/features/ConfigurationWarnings.feature
  centreon/features/bootstrap/ConfigurationWarningsContext.php
  centreon/tests/e2e/features/Services-configuration/02-configurationWarnings.feature
  centreon/tests/e2e/features/Services-configuration/02-configurationWarnings/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5302 Fix(UI); Change tooltips placement on status rows
  centreon/www/front_src/src/Resources/Listing/columns/Status.tsx
Labels: area/ui

#5299 Fix(UI): Fix group chips
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/GroupChip.tsx
Labels: area/ui

#5174 enh(dashboards): Handle meta services on metrics widgets
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- adds a new filter line when the first resource line is fullfilled add the button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding is clicked and corresponding prop are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- displays host and service type when the corresponding atom is set to true.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- displays only the restricted resource types when the propety is defined.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- does not display the Add filter button when the corresponding property is set to true.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- does not displays resource types when they are excluded fromn selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- selects a resource type and a resource when the data value does not exist.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources disabled -- displays fields as disabled when rights are not sufficient.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources disabled -- displays fields as disabled when the edition mode is not activated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- allows to select a meta-service or host as resource type when corresponding props and restricted resoource types are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- confirms that the 'Add Filter' button is disabled when the 'Service' type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- disables the Add filter button when a meta service is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- ensures that all resource types are available in the first line item of the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- removes all subsequent resource lines, if a resource type line in the middle of the tree is updated.snap.png
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/packages/ui/src/api/useGraphQuery/models.ts
  centreon/packages/ui/src/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useListMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
  centreon/www/widgets/src/centreon-widget-webpage/src/Webpage.cypress.spec.tsx
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#5352 Fix(UI): Fix group chips (#5299)
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/GroupChip.tsx
Labels: backport

#5348 Fix(UI); Change tooltips placement on status rows (#5302)
  centreon/www/front_src/src/Resources/Listing/columns/Status.tsx
Labels: backport

#5351 Fix(UI): Fix group chips (#5299)
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/GroupChip.tsx
Labels: backport

#5255 fix(pollers, hosts, logs) : fix displayed name of object
  centreon/tests/php/www/class/service/HtmlSanitizerTest.php
  centreon/www/class/HtmlAnalyzer.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/service/HtmlSanitizer.php
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/listNagios.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend

#5340 fix(dashboard): Listing action bar and colomn actions should not be v…
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/Status.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/useColumns.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
Labels: area/ui

#5330 fix (host): fix hosts listing
  centreon/www/class/utils/HtmlSanitizer.php
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/core/pathway/pathway.php
Labels: area/backend

#5363 Backport([Resource Status]): status_type filter doesn't work in capital letters
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/search barignores case sensitivity when searching static filters -- displays the corresponding suggestoins when searching state static filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/search barignores case sensitivity when searching static filters -- displays the corresponding suggestoins when searching status static filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/search barignores case sensitivity when searching static filters -- displays the corresponding suggestoins when searching status_type static filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/search barignores case sensitivity when searching static filters -- displays the corresponding suggestoins when searching type static filters.snap.png
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/index.ts
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
Labels: backport

#5274 fix(configuration): remove deprecated macros & add new ones (#5187)
  centreon/www/install/insertMacros.sql
  centreon/www/install/php/Update-24.04.8.php
Labels: backport

#5342 fix(api): fix returned value for is_notifications_enabled on resources
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
Labels: area/backend

#5364 fix(pollers, hosts, logs) : fix displayed name of object
  centreon/www/class/HtmlAnalyzer.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/utils/HtmlSanitizer.php
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/listNagios.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend, backport

#5365 fix(pollers, hosts, logs) : fix displayed name of object
  centreon/www/class/HtmlAnalyzer.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/utils/HtmlSanitizer.php
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/listNagios.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend, backport

#5366 fix(pollers, hosts, logs) : fix displayed name of object
  centreon/www/class/HtmlAnalyzer.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/utils/HtmlSanitizer.php
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/listNagios.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend, backport

#5368 fix(export): fix generation of VMWare export file
  centreon/packaging/centreon-common.yaml
  centreon/packaging/scripts/centreon-common-postinstall.sh
  centreon/www/class/config-generate-remote/Generate.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend

#5372 fix(api): fix returned value for is_notifications_enabled on resources
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
Labels: backport

#5379 Backport([Core]): Issue with topology_id in Pollers menus
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/configuration/configServers/listServers.php
Labels: backport

#5377 Backport([Core]): Issue with topology_id in Pollers menus
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/configuration/configServers/listServers.php
Labels: backport

#5378 Backport([Core]): Issue with topology_id in Pollers menus
  centreon/tests/e2e/cypress/e2e/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/configuration/configServers/listServers.php
Labels: backport

#5371 fix(api): fix returned value for is_notifications_enabled on resources
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
Labels: backport

#5383 fix(graph): fix blank page when user adds & updates a curve on mysql
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
Labels: backport

#5362 fix(pac) allow pac menu display on central only
  centreon/src/Centreon/Infrastructure/Menu/MenuRepositoryRDB.php
  centreon/www/install/php/Update-24.11.0.php
Labels: area/backend

#5388 fix(test): 1-poller-configuration.feature
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
Labels: area/test

#5345 enh(tests): Rewrite ServiceConfiguration.feature
  centreon/behat.yml
  centreon/features/ServiceConfiguration.feature
  centreon/features/bootstrap/ServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/03-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5349 [E2E] Rewrite HostCategoryConfiguration.feature
  centreon/behat.yml
  centreon/features/HostCategoryConfiguration.feature
  centreon/features/bootstrap/HostCategoryConfigurationContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/Hosts/01-host-configuration/index.ts
  centreon/tests/e2e/features/Hosts/02-host-category-configuration.feature
  centreon/tests/e2e/features/Hosts/02-host-category-configuration/index.ts
  centreon/tests/e2e/fixtures/host-categories/category.json
Labels: area/test

#5375 fix(export): fix generation of VMWare export file
  centreon/packaging/centreon-common.yaml
  centreon/packaging/scripts/centreon-common-postinstall.sh
  centreon/www/class/config-generate-remote/Generate.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend

#5393 enh(Change Logs): Insert change logs for /configuration/hosts/templates endpoints (#5356) [dev-24.04.x]
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostTemplate/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateActionLogRepository.php
Labels: area/backend, backport

#5359 fix(acc) fix menu display of acc on remote server
  centreon/src/Centreon/Infrastructure/Menu/MenuRepositoryRDB.php
  centreon/www/install/php/Update-24.10.0.php
Labels: area/backend

#5404 Backport([Resource Status]): DT and ACK icon are not visible enought in dark mode
  centreon/cypress/fixtures/resources/listing/listingWithInDowntimeAndAck.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on dark theme -- displays listing when some resources are in downtime/acknowledged.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays listing when some resources are in downtime/acknowledged.snap.png
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
Labels: backport

#5387 enh(tests): Rewrite ServiceGroupConfiguration.feature
  centreon/behat.yml
  centreon/features/ServiceGroupConfiguration.feature
  centreon/tests/e2e/features/Services-configuration/04-service-group-configuration.feature
  centreon/tests/e2e/features/Services-configuration/04-service-group-configuration/index.ts
  centreon/tests/e2e/fixtures/services/service.json
Labels: area/test

#5403 fix(metrics): fix on repository identified using public playlists
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
Labels: area/backend

#5406 fix(acc) fix menu display of acc on remote server (#5359)
  centreon/src/Centreon/Infrastructure/Menu/MenuRepositoryRDB.php
  centreon/www/install/php/Update-24.10.0.php
Labels: area/backend

#5409 Backport([Resource Status]): DT and ACK icon are not visible enought in dark mode
  centreon/cypress/fixtures/resources/listing/listingWithInDowntimeAndAck.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on dark theme -- displays listing when some resources are in downtimeacknowledged.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays listing when some resources are in downtimeacknowledged.snap.png
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
Labels: backport

#5410 fix(metrics): fix on repository identified using public playlists (#5403)
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
Labels: area/backend, backport

#5389 [E2E] Rewrite HostTemplateBasicsOperations.feature
  centreon/behat.yml
  centreon/features/HostTemplateBasicsOperations.feature
  centreon/features/bootstrap/HostTemplateBasicsOperationsContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/Hosts/03-host-template-basics-operations.feature
  centreon/tests/e2e/features/Hosts/03-host-template-basics-operations/index.ts
  centreon/tests/e2e/fixtures/host-groups/host-group.json
  centreon/tests/e2e/fixtures/host-templates/host-template.json
Labels: area/test

#5358 fix(api-token): fix expiration date updates on each call for manual token
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/TokenAPIAuthenticatorTest.php
Labels: area/backend

#5296 Fix(UI): Fix event log redirections to Resources Status
  centreon/src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: area/backend

#5415 Fix([Resource Status]): Last notification set as 1970 in service/host details
  centreon/cypress/fixtures/resources/details/tabs/details/cards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_check when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_notification when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_status_change when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_time_with_no_issue when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for next_check when the returned value is 0.snap.png
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/models.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  centreon/www/front_src/src/Resources/Listing/useLoadResources/index.ts
  centreon/www/front_src/src/Resources/Listing/useLoadResources/useLoadDetails.ts
  centreon/www/front_src/src/Resources/decoders.ts
Labels: area/ui

#5422 Fix(UI): Fix event log redirections to Resources Status (#5296)
  centreon/src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: backport

#5402 fix(change logs): map new fields names on legacy fields form names
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#5426 fix(api-token): fix expiration date updates on each call for manual token
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/TokenAPIAuthenticatorTest.php
Labels: backport

#5427 Fix(UI): Fix Resources Status listing selection
  centreon/packages/ui/src/Listing/Header/ListingHeader.tsx
  centreon/packages/ui/src/Listing/index.tsx
Labels: area/ui

#5265 fix : dead code removed or possible bugs fixed post migration php 8.2
  centreon/composer.json
  centreon/www/api/class/centreon_configuration_service.class.php
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
  centreon/www/class/centreon-clapi/centreonACLResources.class.php
  centreon/www/class/centreon-clapi/centreonAPI.class.php
  centreon/www/class/centreon-clapi/centreonObject.class.php
  centreon/www/class/centreon-clapi/centreonResourceCfg.class.php
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreon-partition/config.class.php
  centreon/www/class/centreon-partition/mysqlTable.class.php
  centreon/www/class/centreonAuth.class.php
  centreon/www/class/centreonConnector.class.php
  centreon/www/class/centreonGraphNg.class.php
  centreon/www/class/centreonHost.class.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonNotification.class.php
  centreon/www/class/centreonServicegroups.class.php
  centreon/www/class/centreonTraps.class.php
  centreon/www/class/centreonUser.class.php
  centreon/www/class/centreonUtils.class.php
  centreon/www/class/centreonXMLBGRequest.class.php
Labels: area/backend

#5431 fix(change logs): map new fields names on legacy fields form names
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
Labels: backport

#5438 Backport([Resource Status]): Last notification set as 1970 in service/host details
  centreon/cypress/fixtures/resources/details/tabs/details/cards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_check when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_notification when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_status_change when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_time_with_no_issue when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for next_check when the returned value is 0.snap.png
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/models.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  centreon/www/front_src/src/Resources/decoders.ts
Labels: backport

#5428 fix(api-token): fix expiration date updates on each call for manual token
  .github/actions/cypress-e2e-testing/action.yml
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/TokenAPIAuthenticatorTest.php
Labels: backport

#5434 fix(Traps): fix shell commands
  .github/actions/cypress-e2e-testing/action.yml
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/tests/e2e/cypress/e2e/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/backend

#5442 Backport([Resource Status]):Last notification set as 1970 in service/host details
  centreon/www/front_src/src/Resources/Details/models.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: backport

#5441 Backport([Resource Status]): Last notification set as 1970 in service/host details
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/front_src/src/Resources/Details/models.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: backport

#5416 fix(cron): fix misdirected log when calling cron outdated-token
  centreon/cron/outdated-token-removal.php
Labels: area/backend

#5439 fix(Traps): fix shell commands
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
Labels: area/backend

#5456 Fix(UI): Fix crash when editing back a widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-groupmonitoring/src/utils.ts
Labels: area/ui

#5457 Fix(UI): Fix some UI issues on ACC
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- clears filters and the search bar, and sends a listing request with empty search parameter when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the advanced filters component when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the search bar component.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- updates the search bar with the value from the filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- deletes an ACC when the Delete button is clicked and the confirmation button is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- displays the first page of the ACC listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends a Post request when the Modal is in Creation Mode and the Create Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends an Update request when the Modal is in Edition Mode and the Update Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that at least one poller is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that name length must be between 3 and 50 characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that port field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be a valid integer.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be between 0 and 65535.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter URL field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name must be unique for its own ACC.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter password field is not required in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter username is not required Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- adds a new parameter group when Add vCenter ESX button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- disables the update button when no change has been made to the modal form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- displays form fields with the selected ACC values when the Modal is opened in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- enables the create button when all mandatory fields are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- displays listing, filters and action buttons.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Creation Mode when Add button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Edition Mode when a row of the listing is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creation date column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creator column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Last update column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Name column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Type column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Updated by column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_2.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_2.snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Listing/ActionsBar/Filters/AdvancedFilters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Listing/ActionsBar/Filters/useUpdateSearchBarBasedOnFilters.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/CloseModalConfirmation.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.filters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/translatedLabels.ts
Labels: area/ui

#5459 feat(tests): Add Postman test
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
Labels: area/test

#5451 fix(status-chart): remove limit on status calculation, and group results
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend

#5447 [E2E] Rewrite ContactGroupConfiguration.feature
  centreon/behat.yml
  centreon/features/ContactGroupConfiguration.feature
  centreon/features/bootstrap/ContactGroupConfigurationContext.php
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration.feature
  centreon/tests/e2e/features/Contacts/02-contact-group-configuration/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test

#5461 Fix(UI): Fix crash when editing back a widget (#5456)
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useWidgetModal.ts
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/utils.ts
Labels: backport

#5440 enh(test): rewrite TimePeriodConfiguration.feature
  centreon/behat.yml
  centreon/features/TimePeriodConfiguration.feature
  centreon/features/bootstrap/TimePeriodConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/02-configurationWarnings/index.ts
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration.feature
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration/index.ts
  centreon/tests/e2e/features/Time-Period/common.ts
Labels: area/test

#5382 enh(Change Logs): Insert change logs for service configuration endpoints
  centreon/src/Core/Service/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
Labels: area/backend

#5423 Fix(UI): Fix event log redirections to Resources Status (#5296)
  centreon/src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: backport

#5463 Fix(UI): Fix some UI issues on ACC (#5457)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- clears filters and the search bar, and sends a listing request with empty search parameter when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the advanced filters component when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the search bar component.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- updates the search bar with the value from the filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- deletes an ACC when the Delete button is clicked and the confirmation button is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- displays the first page of the ACC listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends a Post request when the Modal is in Creation Mode and the Create Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends an Update request when the Modal is in Edition Mode and the Update Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that at least one poller is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that name length must be between 3 and 50 characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that port field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be a valid integer.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be between 0 and 65535.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter URL field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name must be unique for its own ACC.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter password field is not required in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter username is not required Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- adds a new parameter group when Add vCenter ESX button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- disables the update button when no change has been made to the modal form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- displays form fields with the selected ACC values when the Modal is opened in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- enables the create button when all mandatory fields are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- displays listing, filters and action buttons.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Creation Mode when Add button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Edition Mode when a row of the listing is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creation date column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creator column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Last update column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Name column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Type column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Updated by column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_2.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_2.snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Listing/ActionsBar/Filters/AdvancedFilters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Listing/ActionsBar/Filters/useUpdateSearchBarBasedOnFilters.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/CloseModalConfirmation.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.filters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/translatedLabels.ts
Labels: backport

#5466 enh(Change Logs): Insert change logs for service configuration endpoints (#5382) [dev-24.04.x]
  centreon/src/Core/Service/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
Labels: area/backend, backport

#5370 fix(API): Time periods exceptions (issue on 00:00-00:00 range)
  centreon/src/Core/TimePeriod/Domain/Model/TimeRange.php
  centreon/tests/php/Core/TimePeriod/Domain/Model/TimeRangeTest.php
Labels: area/backend

#5453 fix(cron): fix misdirected log when calling cron outdated-token (#5416)
  centreon/cron/outdated-token-removal.php
Labels: backport

#5436 fix (host): fix hosts listing (#5330)
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/core/pathway/pathway.php
Labels: area/backend

#5458 enh(tests): Rewrite GenerateServiceContact.feature
  centreon/behat.yml
  centreon/features/GenerateServiceContact.feature
  centreon/features/bootstrap/GenerateServiceContactContext.php
  centreon/tests/e2e/features/Services-configuration/06-generate-service-contact.feature
  centreon/tests/e2e/features/Services-configuration/06-generate-service-contact/index.ts
Labels: area/test

#5395 enh(tests): Rewrite ServiceTemplateConfiguration.feature
  centreon/behat.yml
  centreon/features/ServiceTemplateConfiguration.feature
  centreon/features/bootstrap/ServiceGroupConfigurationContext.php
  centreon/features/bootstrap/ServiceTemplateConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/05-service-template-configuration.feature
  centreon/tests/e2e/features/Services-configuration/05-service-template-configuration/index.ts
Labels: area/test

#5449 fix: reset array keys in common-Func
  centreon/www/include/common/common-Func.php
Labels: area/backend

#5488 Fix(snapshots): Fix NotificationsListing snapshots
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- disables the Delete button when no rows are selected, and displays it when one or more rows are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a confirmation dialog upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a success message after a successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a warning message containing the names of the notifications that failed to be deleted if the deletion of some notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays an error message if the deletion of all notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays an error message upon failed deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- disables the Confirm button if the name is empty or already exists.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a confirmation dialog with a text field for the new notification name when the Duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a success message after a successful duplication.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays an error message upon failed duplication request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- validates that the name field is not empty and the name does not already exist.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- displays the first page of the notifications listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a get notifications request after updating limit param.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Resources column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Users column is clicked.snap.png
Labels: area/ui

#5493 [E2E] Rewrite ModifyDefaultPageConnection.feature
  centreon/behat.yml
  centreon/features/ModifyDefaultPageConnection.feature
  centreon/features/bootstrap/ModifyDefaultPageConnectionContext.php
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection.feature
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection/index.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/non-admin-with-access-to-allmodules.json
  centreon/tests/e2e/fixtures/users/user-with-access-to-allmodules.json
Labels: area/test

#5464 [E2E] Rewrite ContactTemplateConfiguration.feature
  centreon/behat.yml
  centreon/features/ContactTemplateConfiguration.feature
  centreon/features/bootstrap/ContactTemplateConfigurationContext.php
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration.feature
  centreon/tests/e2e/features/Contacts/03-contact-template-configuration/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test

#5492 fix(ui): remove theme field from user account form (#5484)
  centreon/www/include/Administration/myAccount/DB-Func.php
Labels: backport

#5496 fix: reset array keys in common-Func (#5449)
  centreon/www/include/common/common-Func.php
Labels: backport

#5495 fix: reset array keys in common-Func (#5449)
  centreon/www/include/common/common-Func.php
Labels: backport

#5355 Fix(UI): Fix columns reset
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays acknowledgement details when an acknowledged state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding action_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding checks menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding fqdn menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding monitoring_server_name menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notes_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notification menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding parent_alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding severity menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays downtime details when the downtime state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with a limit param when the rows per page value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- displays notification column if the cloud notification feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- hides notification column if the cloud notification feature is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays a highlighted row when a resource is in a critical state.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays first part of information when multiple (split by ) are available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in compact mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in extended mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- reorders columns when a drag handle is focused and an arrow is pressed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- displays the services when the Expand button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sends a request to retrieve all sevices and their parents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sends a request with types service,metaservice.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- enables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sends a request to get all resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sets the column names to the default ones.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sorts columnns by newest duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Duration column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Last check column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Parent column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Resource column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Tries column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is medium.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is small.snap.png
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
  centreon/www/front_src/src/Resources/Listing/listingAtoms.ts
Labels: area/ui

#5503 fix(DSM): White page when creating a pool (#5497) [release-24.10-next]
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/DB-Func.php
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/formSlot.php
Labels: area/backend, backport

#5501 Fix(UI): Fix columns reset (#5355)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays acknowledgement details when an acknowledged state chip is hovered.snap.png
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/listingAtoms.ts
Labels: backport

#5504 Fix(UI): Fix columns reset (#5355)
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/listingAtoms.ts
Labels: backport

#5485 enh(tests): Rewrite MetaServiceConfiguration.feature
  centreon/behat.yml
  centreon/features/MetaServiceConfiguration.feature
  centreon/features/bootstrap/MetaServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration/index.ts
  centreon/tests/e2e/fixtures/services/meta_service.json
Labels: area/test

#5479 fix(Sevice): rework service repository method 'existsByAccessGroups'
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidation.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
Labels: area/backend

#5460 fix(Graphs): User with ACLs download an empty csv via Performance > Graph page. (#5437) [dev-23.10.x]
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/tests/api/features/ServiceOnPrem.feature
Labels: area/backend, backport

#5517 fix(Dashboards): Cannot load module issue in metrics graph widget
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/tests/e2e/features/Dashboards/17-clock-timer-widget-configuration/index.ts
  centreon/www/front_src/src/Resources/Graph/Performance/Lines/RegularLine.tsx
Labels: area/ui

#5525 fix(Dashboards): Cannot load module issue in metrics graph widget (#…
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/tests/e2e/features/Dashboards/17-clock-timer-widget-configuration/index.ts
  centreon/www/front_src/src/Resources/Graph/Performance/Lines/RegularLine.tsx
Labels: area/ui, backport

#5505 MON-19102-new
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/displays the acknowledgment modal when the Acknowledge button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Resources-status/02-acknowledgments/index.ts
  centreon/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui

#5480 fix(configuration): improve field label & tooltip in Broker configuration
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.1.php
Labels: area/backend

#5450 enh(Change Logs): insert log changes into ServiceTemplate actions
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ServiceTemplate/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateActionLogRepository.php
Labels: area/backend

#5535 Fix([API Token]) User list incomplete for API token creation
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
Labels: area/ui

#5526 Fix([Cloud Notification]):Checkbox not reflects changes correctly
  centreon/packages/ui/src/Form/Form.tsx
Labels: area/ui

#5518 fix(dashboards): Issue with the Save button activation in the group monitoring widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
Labels: area/ui

#5542 Backport([release-24.04-next]): [API Token] User list incomplete for API token creation
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
Labels: backport

#5531 fix(Discovery): Hosts discovery can't export/reload centengine via automatic analysis
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
Labels: area/backend

#5544 enh(dashboad): fix and enhance the condensed status grid tooltip
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/ResourcesTooltip.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx
Labels: area/ui
