Repository centreon/centreon, pull requests merged in 2024-07, with the labels that each got.

#4508 fix(CI): Attempt to fix dashboard test
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useFormSubmit.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
Labels: area/test

#4520 fix (pendo): replace cdn.eu.pendo.io by guide.centreon.com for snippet (#4474)
  centreon/www/front_src/src/App/initPendo.js
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend, backport

#4509 chore(ci): upgrade composer to latest v2 (#4502)
  .github/actions/lighthouse-performance-testing/action.yml
Labels: backport

#4536 fix(packaging): set 31-centreon-api.yaml as config file (#4525)
  centreon-gorgone/packaging/centreon-gorgone-centreon-config.yaml
  centreon-gorgone/packaging/scripts/centreon-gorgone-centreon-config-postinstall.sh
Labels: backport

#4511 chore(ci): upgrade composer to latest v2 (#4502)
  .github/actions/lighthouse-performance-testing/action.yml
Labels: backport

#4464 enh(API): enhanced host configuration endpoints (#4423)
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadHostNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/HostCategoryRepositoryTrait.php
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbReadHostSeverityRepository.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplateValidation.php
  centreon/src/Core/HostTemplate/Application/UseCase/FindHostTemplates/FindHostTemplates.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplateValidation.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadHostNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
  centreon/src/Core/MonitoringServer/Application/Repository/ReadMonitoringServerRepositoryInterface.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/DbReadMonitoringServerRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicyTest.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/HostTemplate/Application/FindHostTemplates/FindHostTemplatesTest.php
  centreon/tests/php/Core/HostTemplate/Application/PartialUpdateHostTemplate/PartialUpdateHostTemplateTest.php
Labels: area/backend

#4514 fix (pendo): replace cdn.eu.pendo.io by guide.centreon.com for snippet (#4474)
  centreon/tests/e2e/features/ACLs/01-acl-access-groups/index.ts
  centreon/www/front_src/src/App/initPendo.js
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend, backport

#4435 enh(dashboards): clarify display type in status grid and status chart
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwostatusGrid.json
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/useStatusGridCondensed.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
Labels: backport

#4527 enh(UI): Implement bars and stacked bars charts on Graph widget
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays custom stacked bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the bar chart when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the customised bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the stacked bar chart when the corresponding prop is set.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays bar chart horizontally with a custom style.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays bar chart vertically with a custom style.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays bar chart vertically with a mix of stacked and non-stacked data centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays bar chart vertically with a mix of stacked and non-stacked data.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/BarChart/BarChart.tsx
  centreon/packages/ui/src/Graph/BarChart/BarGroup.tsx
  centreon/packages/ui/src/Graph/BarChart/BarStack.tsx
  centreon/packages/ui/src/Graph/BarChart/ResponsiveBarChart.tsx
  centreon/packages/ui/src/Graph/common/Axes/index.tsx
  centreon/packages/ui/src/Graph/common/Axes/useAxisY.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/models.ts
Labels: area/ui

#4537 fix (pendo): replace cdn.eu.pendo.io by guide.centreon.com for snippet (#4474)
  centreon/www/front_src/src/App/initPendo.js
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend, backport

#4512 chore(ci): upgrade composer to latest v2 (#4502)
  .github/actions/lighthouse-performance-testing/action.yml
Labels: backport

#4535 enh(API): Added ACL check on topology, actions & monitoring server in Generate Conf All Servers Endpoint
  centreon/doc/API/centreon-api.yaml
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
Labels: area/backend

#4494 enh([Resource Status]): Add host filter for "View by host"
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays more criterias interface when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- displays the basic criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- does not display the host select and host statuses when the view by host is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Type criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/packages/js-config/cypress/component/commands.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/CheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/index.tsx
  centreon/www/front_src/src/Resources/Filter/useBackToVisualizationByAll.tsx
Labels: area/ui

#4538 fix (pendo): replace cdn.eu.pendo.io by guide.centreon.com for snippet (#4474)
  centreon/www/front_src/src/App/initPendo.js
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend, backport

#4491 fix(graph): do not parse title to get the hostname (#4484)
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataTest.php
  centreon/www/class/centreonGraphNg.class.php
Labels: area/backend, backport

#4541 enh(API): Added ACL checks on topology, actions & monitoring server in Reload monitoring servers Conf Endpoint
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
Labels: area/backend

#4574 fix(ci): upgrade pnpm/action-setup to v4.0.0 (#4573)
  .github/actions/chromatic/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
Labels: backport

#4575 fix(ci): upgrade pnpm/action-setup to v4.0.0 (#4573)
  .github/actions/chromatic/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
Labels: backport

#4566 fix(packaging): fix selinux dependencies (#4559)
  .github/workflows/web.yml
  centreon/packaging/centreon-common-selinux.yaml
  centreon/packaging/centreon-web-selinux.yaml
  centreon/packaging/scripts/centreon-common-selinux-postinstall.sh
  centreon/packaging/scripts/centreon-common-selinux-preremove.sh
  centreon/packaging/scripts/centreon-web-selinux-postinstall.sh
  centreon/packaging/scripts/centreon-web-selinux-preremove.sh
Labels: backport

#4475 fix(dashboard): exclude disabled resources from status grid/chart widget
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend, backport

#4398 fix(dashboards): correctly check admin rights on contact/contactgroup listing (#3887)
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsTest.php
Labels: area/backend, backport

#4490 fix(dashboard): update dashboard name with empty description (#4476)
  centreon/src/Core/Dashboard/Application/UseCase/PartialUpdateDashboard/PartialUpdateDashboard.php
Labels: area/backend, backport

#4397 fix(dashboard): add consistent information regarding playlist statistics (#4317)
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend, backport

#4560 feat(open-tickets): add endpoint to list providers
  .github/workflows/open-tickets.yml
  centreon-open-tickets/.php-cs-fixer.dist.php
  centreon-open-tickets/.php-cs-fixer.unstrict.php
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon-open-tickets/config/packages/dev/CentreonOpenTickets.yaml
  centreon-open-tickets/config/packages/prod/CentreonOpenTickets.yaml
  centreon-open-tickets/config/routes/CentreonOpenTickets.yaml
  centreon-open-tickets/doc/API/centreon-logo.png
  centreon-open-tickets/doc/API/centreon-open-tickets-api.yaml
  centreon-open-tickets/doc/API/latest/Common/QueryParameter/Limit.yaml
  centreon-open-tickets/doc/API/latest/Common/QueryParameter/Page.yaml
  centreon-open-tickets/doc/API/latest/Common/QueryParameter/Search.yaml
  centreon-open-tickets/doc/API/latest/Common/QueryParameter/SortBy.yaml
  centreon-open-tickets/doc/API/latest/Common/Response/BadRequest.yaml
  centreon-open-tickets/doc/API/latest/Common/Response/Forbidden.yaml
  centreon-open-tickets/doc/API/latest/Common/Response/InternalServerError.yaml
  centreon-open-tickets/doc/API/latest/Common/Response/Unauthorized.yaml
  centreon-open-tickets/doc/API/latest/Common/Schema/Meta.yaml
  centreon-open-tickets/doc/API/latest/Configuration/Providers.yaml
  centreon-open-tickets/doc/API/latest/Configuration/Schema/FindProvidersResponse.yaml
  centreon-open-tickets/packaging/centreon-open-tickets.yaml
  centreon-open-tickets/packaging/scripts/centreon-open-tickets-postinstall.sh
  centreon-open-tickets/phpstan.core.neon
  centreon-open-tickets/phpunit.xml
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Exception/ProviderException.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersPresenterInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/ProviderDto.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Domain/Model/Provider.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Domain/Model/ProviderType.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenterStub.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/clear_cache.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/generate_routes.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/install.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/uninstall.php
  centreon-open-tickets/www/modules/centreon-open-tickets/routes/CentreonOpenTickets.yaml
  centreon-open-tickets/www/modules/centreon-open-tickets/routes/CentreonOpenTickets.yaml.wait
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.08.0/php/upgrade.php
Labels: area/backend

#4501 feat(vault): add a script to wrap all migration
  centreon/bin/centreon
  centreon/bin/migrateCredentials.php
  centreon/packaging/centreon-web.yaml
  centreon/src/CentreonLegacy/Core/Configuration/Configuration.php
  centreon/src/Core/Security/Vault/Infrastructure/Command/MigrateAllCredentials/MigrateAllCredentialsCommand.php
  centreon/www/api/class/centreon_topcounter.class.php
  centreon/www/class/centreonGraphNg.class.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configServers/DB-Func.php
Labels: area/backend

#4534 feat(unattended): manage vault in unattended
  centreon/unattended.sh
  centreon/www/install/steps/process/process_step5.php
Labels: area/backend

#4487 enh(conf/broker) handle vault in inputs/outputs broker configuration
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/AddBrokerInputOutput.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputResponse.yaml
  centreon/src/Core/Broker/Application/Repository/ReadBrokerInputOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutput.php
  centreon/src/Core/Broker/Domain/Model/BrokerInputOutput.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbReadBrokerInputOutputRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
  centreon/src/Core/Security/Vault/Application/Repository/ReadVaultConfigurationRepositoryInterface.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigrator.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialTypeEnum.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Security/Vault/Infrastructure/Command/MigrateAllCredentials/MigrateAllCredentialsPresenter.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/FsReadVaultConfigurationRepository.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputTest.php
  centreon/tests/php/Core/Broker/Domain/Model/BrokerInputOutputTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigratorTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentialsTest.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/config-generate/broker.class.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configCentreonBroker/DB-Func.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.07.0.php
Labels: area/backend

#4585 [WIP] enh(vault): suffix vault path with credential vault key for hosts
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Common/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Common/Application/Repository/WriteVaultRepositoryInterface.php
  centreon/src/Core/Common/Application/UseCase/VaultTrait.php
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/ReadVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/WriteVaultRepository.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Application/UseCase/DeleteHost/DeleteHost.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHost.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigrator.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/src/Core/Security/Vault/Infrastructure/Command/MigrateAllCredentials/MigrateAllCredentialsPresenter.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateService.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigratorTest.php
  centreon/www/class/config-generate/abstract/host.class.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#4586 Fix(UI): Encode metric name
  centreon/www/widgets/src/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
Labels: area/ui

#4606 fix (host category): fix SQL query and ACL
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategories.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategoriesTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesTest.php
Labels: area/backend

#4551 fix([Resource Status]): Fix the display by views responsivity and visibility
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is medium.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is small.snap.png
  centreon/packages/ui/src/Listing/ActionBar/index.tsx
  centreon/www/front_src/src/Resources/Actions/Refresh/index.tsx
  centreon/www/front_src/src/Resources/Actions/Refresh/refresh.styles.ts
  centreon/www/front_src/src/Resources/Actions/Resource/Check/Check.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/Check/check.styles.ts
  centreon/www/front_src/src/Resources/Actions/Resource/index.tsx
  centreon/www/front_src/src/Resources/Actions/Resource/useMediaQueryListing.ts
  centreon/www/front_src/src/Resources/Actions/Visualization/Visualization.styles.tsx
  centreon/www/front_src/src/Resources/Actions/Visualization/Visualization.tsx
  centreon/www/front_src/src/Resources/Actions/WrapperResourceActions.tsx
  centreon/www/front_src/src/Resources/Actions/index.tsx
  centreon/www/front_src/src/Resources/Actions/model.ts
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
Labels: area/ui

#4513 enh(API): Added ACL checks on Monitoring servers endpoints
  centreon/doc/API/centreon-api.yaml
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/MonitoringServerRepositoryTrait.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/api/features/MonitoringServerConfiguration.feature
  centreon/tests/php/Centreon/Domain/MonitoringServer/MonitoringServerServiceTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadConfigurationTest.php
Labels: area/backend

#4561 enh(api): update Vault configuration endpoints
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Administration/Vault/Schema/GetVaultConfiguration.yaml
  centreon/doc/API/latest/onPremise/Administration/Vault/Schema/UpdateVaultConfiguration.yaml
  centreon/doc/API/latest/onPremise/Administration/Vault/VaultConfiguration.yaml
  centreon/src/Core/Common/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Common/Infrastructure/Repository/ReadVaultRepository.php
  centreon/src/Core/Security/Vault/Application/Exceptions/VaultConfigurationException.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationResponse.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/NewVaultConfigurationFactory.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfiguration.php
  centreon/src/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationRequest.php
  centreon/src/Core/Security/Vault/Domain/Model/NewVaultConfiguration.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationRoute.yaml
  centreon/src/Core/Security/Vault/Infrastructure/API/CreateVaultConfiguration/CreateVaultConfigurationSchema.json
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationController.php
  centreon/src/Core/Security/Vault/Infrastructure/API/UpdateVaultConfiguration/UpdateVaultConfigurationSchema.json
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/CreateVaultConfiguration/CreateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/DeleteVaultConfiguration/DeleteVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/FindVaultConfiguration/FindVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/NewVaultConfigurationFactoryTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/UpdateVaultConfiguration/UpdateVaultConfigurationTest.php
  centreon/tests/php/Core/Security/Vault/Domain/Model/NewVaultConfigurationTest.php
Labels: area/backend

#4609 enh(vault): manage suffix vault path with credential key for services
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateService.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/www/class/config-generate/macro.class.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#4622 fix(api): total result found fixed for service names API
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesController.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend

#4619 [22.10] enh(ci): add .coderabbit config file (#4607)
  .coderabbit.yml
  .github/CODEOWNERS
Labels: backport

#4618 enh(vault): manage suffix vault path with credential key for openid
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/PartialUpdateOpenIdConfiguration/PartialUpdateOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/Factory/OpenIdProviderDtoFactory.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigrator.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
Labels: area/backend

#4626 fix(api): total result found fixed for service names API (#4622)
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesController.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend, backport

#4627 fix(api): total result found fixed for service names API
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend, backport

#4636 [22.10] fix(coderabbit): remove high level summary from coderabbit configuration
  .coderabbit.yml
Labels: backport

#4628 enh(vault): manage suffix vault path with credential key for kb
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigrator.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/www/class/centreon-knowledge/wiki.class.php
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/common/vault-functions.php
Labels: area/backend

#4599 enh(broker): create vault_broker flag
  centreon/config/features.json
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutput.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbReadBrokerInputOutputRepository.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputTest.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentialsTest.php
  centreon/tests/rest_api/collections/platform/Platform_Features.postman_collection.json
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configCentreonBroker/DB-Func.php
  centreon/www/install/steps/process/migrateCredentialsToVault.php
Labels: area/backend

#4645 fix(doc): fix example display in doc API
  centreon/doc/API/latest/onPremise/Configuration/Broker/AddBrokerInputOutput.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputResponse.yaml
Labels: area/backend

#4644 fix(test): check versions during update
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: area/test

#4587 fix(test): check minor version during update-24.04
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: area/test

#4646 feat(tests): add broker input output test script
  centreon/tests/rest_api/collections/configuration/Broker_Input_Output.postman_collection.json
Labels: area/test

#4647 enh(vault): manage suffix in vault path with credential key for poller macros
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configResources/DB-Func.php
Labels: area/backend

#4608 feat(APIv2): Added endpoint to deploy servcies
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/centreon-cloud-api.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServiceDto.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServices.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesResponse.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesController.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesOnPremPresenter.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesRoute.yaml
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/DeploySevices/DeployServicesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/DeployServices/DeployServicesPresenterStub.php
Labels: area/backend

#4652 enh(vault): manage suffix in vault path with credential key for broker input/output
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputRequest.yaml
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutput.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputController.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configCentreonBroker/DB-Func.php
Labels: area/backend

#4654 feat(APIv2): Added endpoint to deploy servcies (#4608) [release-24.07-next]
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/centreon-cloud-api.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServiceDto.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServices.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesResponse.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesController.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesOnPremPresenter.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesRoute.yaml
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/DeploySevices/DeployServicesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/DeployServices/DeployServicesPresenterStub.php
Labels: area/backend, backport

#4655 enh(vault): manage suffix vault path with credential keys for already stored credentials
  centreon/bin/migrateCredentials.php
  centreon/config/centreon.config.php.template
  centreon/config/packages/Centreon.yaml
  centreon/doc/API/latest/onPremise/Configuration/Broker/Schema/AddBrokerInputOutputRequest.yaml
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutput.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputController.php
  centreon/src/Core/Common/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Common/Application/Repository/WriteVaultRepositoryInterface.php
  centreon/src/Core/Common/Application/UseCase/VaultTrait.php
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/ReadVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/WriteVaultRepository.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Application/UseCase/DeleteHost/DeleteHost.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHost.php
  centreon/src/Core/HostTemplate/Application/UseCase/AddHostTemplate/AddHostTemplate.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/PartialUpdateOpenIdConfiguration/PartialUpdateOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/OpenId/UseCase/UpdateOpenIdConfiguration/UpdateOpenIdConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/Api/FindProviderConfigurations/Factory/OpenIdProviderDtoFactory.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigrator.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/MigrateAllCredentials.php
  centreon/src/Core/Security/Vault/Domain/Model/VaultConfiguration.php
  centreon/src/Core/Security/Vault/Infrastructure/Command/MigrateAllCredentials/MigrateAllCredentialsPresenter.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateService.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/tests/php/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/CredentialMigratorTest.php
  centreon/www/class/centreon-knowledge/wiki.class.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/config-generate/abstract/host.class.php
  centreon/www/class/config-generate/macro.class.php
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/common/vault-functions.php
  centreon/www/include/configuration/configCentreonBroker/DB-Func.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/install/steps/process/migrateCredentialsToVault.php
  centreon/www/install/steps/process/process_step9.php
  centreon/www/install/steps/process/process_step_vault.php
Labels: area/backend

#4657 fix(doc): apply suggestions from TW team
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/centreon-cloud-api.yaml
Labels: area/backend

#4659 fix(dashboards): service search is not working in dataset section
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#4681 fix(update): forces postUpdate regardless of the updates to be performed
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
Labels: area/backend

#4687 fix(update): forces postUpdate regardless of the updates to be performed (#4681)
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
Labels: area/backend, backport

#4689 fix(update): forces postUpdate regardless of the updates to be performed (#4681)
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
Labels: area/backend, backport

#4672 fix(Resource Status): Fixed listing Real Time Service Category with a SC filter
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadRealTimeServiceCategoryRepository.php
Labels: area/backend

#4695 MON-139732 Sync Centreon OSS next 23.10
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/web-frontend-component-test/action.yml
  .github/workflows/awie.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/web.yml
  centreon-gorgone/.version
  centreon-gorgone/packaging/centreon-gorgone.spectemplate
  centreon/.version
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.14.php
Labels: sync-release

#4670 fix(Graph,Virtual Metrics) : List of metrics is empty in curve configuration form fixed
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend

#4693 MON-139734 Sync Centreon OSS next 23.04
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/web-frontend-component-test/action.yml
  .github/workflows/awie.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/ui-beta.yml
  .github/workflows/web.yml
  centreon/.version
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.20.php
Labels: sync-release

#4682 fix(API Token): Button is disabled with the correct permissions
  centreon/doc/API/latest/onPremise/Configuration/Users/Schema/CurrentParameters.Get.yaml
  centreon/doc/API/latest/onPremise/Configuration/Users/Users.yaml
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/types.ts
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParameters.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersResponse.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
  centreon/tests/rest_api/collections/configuration/Contact_with_Open_API.postman_collection.json
  centreon/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationButton.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationDialog.tsx
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui, area/backend

#4697 fix(API Token): Button is disabled with the correct permissions (#4682) [release-24.07-next]
  centreon/doc/API/latest/onPremise/Configuration/Users/Schema/CurrentParameters.Get.yaml
  centreon/doc/API/latest/onPremise/Configuration/Users/Users.yaml
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/types.ts
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParameters.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersResponse.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
  centreon/tests/api/features/ConfigurationUsersWithOpenApi.feature
  centreon/tests/rest_api/collections/authentication/05-WebSSO-Provider-Configuration.postman_collection.json
  centreon/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationButton.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationDialog.tsx
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui, area/backend, backport

#4696 MON-139730 Sync Centreon OSS next 24.04
  .github/workflows/awie.yml
  .github/workflows/web.yml
  centreon-gorgone/.version
  centreon/.version
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.5.php
Labels: sync-release

#4613 [24.04] enh(ci): add .coderabbit config file (#4607)
  .coderabbit.yml
  .github/CODEOWNERS
Labels: backport

#4615 [23.10] enh(ci): add .coderabbit config file (#4607)
  .coderabbit.yml
  .github/CODEOWNERS
Labels: backport

#4617 [23.04] enh(ci): add .coderabbit config file (#4607)
  .coderabbit.yml
  .github/CODEOWNERS
Labels: backport

#4605 [24.04] fix(ci): use github.event.inputs.is_nightly instead of inputs.is_nightly
  .github/workflows/web.yml
Labels: backport

#4593 [Backport] : [Resource Status] Add host filter for "View by host"
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Basic criterias interface when selecting Type criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by All -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- displays the criterias interface.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Host criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Monitoring server criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Service criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Service group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting State criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Status criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Extended criterias interface when selecting Host category criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Extended criterias interface when selecting Host severity criteria value.snap.png
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/CheckBoxWrapper.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/checkBox/index.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/sections/index.tsx
  centreon/www/front_src/src/Resources/Filter/useBackToVisualizationByAll.tsx
  centreon/www/front_src/src/Resources/testUtils/index.ts
Labels: area/ui

#4673 [dev-24.04.x] fix(Graph): modify curves definition doesnt work fixed
  centreon/www/include/views/componentTemplates/DB-Func.php
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
Labels: area/backend, backport

#4612 enh(API): Added ACL checks on Monitoring servers endpoints (#4513) [dev-24.04.x]
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/MonitoringServerRepositoryTrait.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/api/features/MonitoringServerConfiguration.feature
  centreon/tests/php/Centreon/Domain/MonitoringServer/MonitoringServerServiceTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadConfigurationTest.php
Labels: area/backend, backport

#4706 enh(APIv2): added ACL checks on metaservices endpoints (#4653) [dev-24.04.x]
  centreon/src/Centreon/Domain/MetaServiceConfiguration/UseCase/V2110/FindMetaServicesConfigurations.php
  centreon/src/Centreon/Domain/MetaServiceConfiguration/UseCase/V2110/FindOneMetaServiceConfiguration.php
  centreon/src/Centreon/Infrastructure/MetaServiceConfiguration/Repository/MetaServiceConfigurationRepositoryRDB.php
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadMetaServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindMetaServiceNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbReadMetaServiceNotificationRepository.php
  centreon/tests/php/Centreon/Domain/MetaServiceConfiguration/UseCase/V21/FindMetaServicesConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MetaServiceConfiguration/UseCase/V21/FindOneMetaServiceConfigurationTest.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindMetaServiceNotificationPolicyTest.php
Labels: area/backend, backport

#4690 fix (host category): fix SQL query and ACL (#4606)
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategories.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategoriesTest.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindRealTimeHostCategories/FindRealTimeHostCategoriesTest.php
Labels: area/backend, backport

#4688 fix(update): forces postUpdate regardless of the updates to be performed (#4681)
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
Labels: area/backend, backport

#4698 fix(API Token): Button is disabled with the correct permissions (#4682) [dev-24.04.x]
  centreon/doc/API/v24.04/Configuration/Users/Schema/CurrentParameters.Get.yaml
  centreon/doc/API/v24.04/Configuration/Users/Users.yaml
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/types.ts
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParameters.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersResponse.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
  centreon/tests/api/features/ConfigurationUsersWithOpenApi.feature
  centreon/tests/rest_api/collections/authentication/05-WebSSO-Provider-Configuration.postman_collection.json
  centreon/www/front_src/src/ApiTokens/ApiTokens.cypress.spec.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationButton.tsx
  centreon/www/front_src/src/ApiTokens/TokenCreation/TokenCreationDialog.tsx
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui, area/backend, backport

#4614 enh(API): Added ACL checks on Monitoring servers endpoints (#4513) [dev-23.10.x]
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/MonitoringServerRepositoryTrait.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/api/features/MonitoringServerConfiguration.feature
  centreon/tests/php/Centreon/Domain/MonitoringServer/MonitoringServerServiceTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadConfigurationTest.php
Labels: area/backend, backport

#4656 feat(APIv2): Added endpoint to deploy servcies (#4608) [dev-24.04.x]
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/centreon-cloud-api-v24.04.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/Cloud/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/doc/API/v24.04/Configuration/Service/DeployServices.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/DeployServiceResponse.yaml
  centreon/src/Core/Infrastructure/Common/Presenter/JsonFormatter.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServiceDto.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServices.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServicesResponse.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesController.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesOnPremPresenter.php
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesRoute.yaml
  centreon/src/Core/Service/Infrastructure/API/DeployServices/DeployServicesSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/DeploySevices/DeployServicesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/DeployServices/DeployServicesPresenterStub.php
Labels: area/backend, backport

#4582 enh(UI): Add state banner on status grid
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Graph/Performance/Graph/AddCommentForm/AddCommentForm.cypress.spec.tsx/Add comment form -- sends a comment request with the given date and the typed comment.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- With resources -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Link to resource status page -- displays a see more tile when not all resources are displayed.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- With Resources -- displays host informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- With Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- Without Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a critical service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a service in downtime tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a warning service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an acknowledged service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an ok service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an unknown service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- Without Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Impact-critical displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Impact-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Ratio-critical displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Ratio-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Worst Status-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the problem card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the success card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the problem card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the success card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Indicators -- displays boolean rule informations when the mouse is over boolean rule tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Indicators -- displays tiles.snap.png
  centreon/package.json
  centreon/packages/ui/package.json
  centreon/packages/ui/src/@assets/icons/downtime.icon.svg
  centreon/packages/ui/src/Dashboard/Dashboard.cypress.spec.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMap.stories.tsx
  centreon/packages/ui/src/Graph/HeatMap/HeatMap.styles.tsx
  centreon/packages/ui/src/Graph/LineChart/Icons/Downtime.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/Annotations/Area/Downtime.tsx
  centreon/packages/ui/src/Graph/LineChart/LineChart.cypress.spec.tsx
  centreon/packages/ui/src/Icon/AcnowledgementIcon.tsx
  centreon/packages/ui/src/Icon/BaseIcon.tsx
  centreon/packages/ui/src/Icon/DowntimeIcon.tsx
  centreon/packages/ui/src/Icon/HostIcon.tsx
  centreon/packages/ui/src/Icon/ServiceIcon.tsx
  centreon/packages/ui/src/Icon/index.ts
  centreon/packages/ui/src/index.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/Resources/Actions/Resource/index.tsx
  centreon/www/front_src/src/Resources/Chip/Downtime.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/Annotations/Area/Downtime.tsx
  centreon/www/front_src/src/Resources/Listing/columns/Status.tsx
  centreon/www/front_src/src/Resources/icons/Downtime.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/State.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.styles.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/testUtils.ts
Labels: area/ui

#4616 enh(API): Added ACL checks on Monitoring servers endpoints (#4513) [dev-23.04.x]
  centreon/doc/API/centreon-api-v23.04.yaml
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/MonitoringServerRepositoryTrait.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/api/features/MonitoringServerConfiguration.feature
  centreon/tests/php/Centreon/Domain/MonitoringServer/MonitoringServerServiceTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadConfigurationTest.php
Labels: area/backend, backport

#4604 [23.04] fix(ci): use github.event.inputs.is_nightly instead of inputs.is_nightly
  .github/workflows/web.yml
Labels: backport

#4601 fix(ci): use github.event.inputs.is_nightly instead of inputs is_nightly
  .github/workflows/web.yml
Labels: backport

#4708 fix(Graph,Virtual Metrics) : List of metrics is empty in curve configuration form fixed
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend, backport

#4674 fix(Graph): modify curves definition doesnt work fixed
  centreon/www/include/views/componentTemplates/DB-Func.php
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
Labels: area/backend, backport

#4718 fix(UI): Fix resources listing when hovering status chart
  .github/workflows/web.yml
  centreon/packages/ui/src/Graph/BarStack/ResponsiveBarStack.tsx
  centreon/packages/ui/src/Graph/BarStack/models.ts
  centreon/packages/ui/src/Graph/PieChart/ResponsivePie.tsx
  centreon/packages/ui/src/Graph/PieChart/models.ts
  centreon/packages/ui/src/utils/useInfiniteScrollListing.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Tooltip/Tooltip.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Tooltip/useTooltip.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/spec/StatusChart.cypress.spec.tsx
  centreon/www/widgets/src/utils.ts
Labels: area/ui

#4669 fix(doc): apply suggestions from TW team (#4657)
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/centreon-cloud-api-v24.04.yaml
Labels: area/backend

#4735 fix(Graph,Virtual Metrics) : List of metrics is empty in curve configuration fixed
  centreon/www/include/views/componentTemplates/formComponentTemplate.php
  centreon/www/include/views/virtualMetrics/formVirtualMetrics.php
Labels: area/backend, backport

#4725 fix(UI): Fix resources listing when hovering status chart
  .github/workflows/web.yml
  centreon/packages/ui/src/Graph/BarStack/ResponsiveBarStack.tsx
  centreon/packages/ui/src/Graph/BarStack/models.ts
  centreon/packages/ui/src/Graph/PieChart/ResponsivePie.tsx
  centreon/packages/ui/src/Graph/PieChart/models.ts
  centreon/packages/ui/src/utils/useInfiniteScrollListing.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Tooltip/Tooltip.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Tooltip/useTooltip.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/spec/StatusChart.cypress.spec.tsx
  centreon/www/widgets/src/utils.ts
Labels: backport

#4714 enh(UI): Invert horizontal and vertical
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays custom stacked bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the customised bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart when the widget has metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a lot of custom style settings when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a natural curve when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a step curve when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with customized critical threshold.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with customized warning threshold.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart without thresholds when thresholds are disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the stacked bar chart when the corresponding prop is set.snap.png
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-graph/src/LineChart.tsx
Labels: area/ui

#4732 fix (ACL): fix require path (#4729)
  centreon/www/class/centreonACL.class.php
  centreon/www/include/common/sqlCommonFunction.php
Labels: area/backend, backport

#4749 fix (notification): fixed use of feature flag for engine notification (#4346)
  centreon/www/class/config-generate/engine.class.php
Labels: area/backend, backport

#2321 handle both deprecated and new status details page
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/templates/table.ihtml
Labels: area/backend

#4750 fix(open-tickets): correctly save ticket subject for GlpiRestApiProvider
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
Labels: area/backend, backport

#4751 fix(open-tickets): handle both deprecated and new status details page redirections (#2321)
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/templates/table.ihtml
Labels: area/backend, backport

#4729 fix (ACL): fix require path
  centreon/www/class/centreonACL.class.php
  centreon/www/include/common/sqlCommonFunction.php
Labels: area/backend

#4753 enh(ci): enable shellcheck in actionlint (#4726)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/veracode-analysis.yml
Labels: backport

#4754 enh(ci): enable shellcheck in actionlint (#4726) (#4753)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/veracode-analysis.yml
Labels: backport

#4755 enh(ci): enable shellcheck in actionlint (#4726) (#4753) (#4754)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  .github/workflows/veracode-analysis.yml
Labels: backport

#4756 enh(ci): enable shellcheck in actionlint (#4726) (#4753) (#4754) (#4755)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  .github/workflows/veracode-analysis.yml
Labels: backport

#4757 fix(ci): enable shellcheck
  .github/workflows/actionlint.yml
Labels: backport

#4758 fix(ci): enable shellcheck
  .github/workflows/actionlint.yml
Labels: backport

#4716 fix(UI): Fix services search on single metric widget
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- confirms that the 'Add Filter' button is disabled when the 'Service' type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Host.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Category.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- displays only the available resource types depending on the previous dataset  Service Group.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- ensures that all resource types are available in the first line item of the dataset selection.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources tree -- removes all subsequent resource lines, if a resource type line in the middle of the tree is updated.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
Labels: area/ui

#4747 Fix(UI): Fix graph widget dynamic properties
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
Labels: area/ui

#4765 fix(openid): specific cloud behaviour added for auto-import
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#4766 fix(openid): specific cloud behaviour added for auto-import (#4765)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Domain/Configuration/User/Model/NewUser.php
  centreon/src/Core/Infrastructure/Configuration/User/Repository/DbWriteUserRepository.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend, backport

#4776 test(E2E): fix linter on dashboard widget metric graph
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration.feature
Labels: area/test

#4770 enh(Change Logs): Insert change logs in /configuration/hosts endpoints
  centreon/src/Core/ActionLog/Application/Repository/WriteActionLogRepositoryInterface.php
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/ActionLog/Infrastructure/Repository/DbWriteActionLogRepository.php
  centreon/src/Core/Host/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostLogRepository.php
Labels: area/backend

#4493 fix(graph): do not parse title to get the hostname (#4484)
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataTest.php
  centreon/www/class/centreonGraphNg.class.php
Labels: area/backend, backport

#4760 enh(resource-table): add possibility to create a ticket from the widget
  centreon-open-tickets/phpstan.neon
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.08.0/php/upgrade.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.09.0/php/upgrade.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/submitTicket/action.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/submitTicket/submitTicket.ihtml
  centreon/www/front_src/src/Header/OpenTicket/Modal.tsx
  centreon/www/front_src/src/Header/index.tsx
Labels: area/backend

#4775 fix(auth): do not delete cloud acl_groups user relations on mapping
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbWriteAccessGroupRepository.php
Labels: area/backend

#4779 fix(auth): do not delete cloud acl_groups user relations on mapping (#4775)
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbWriteAccessGroupRepository.php
Labels: area/backend, backport

#4774 fix(Authentication): OIDC auth, issue with redirect URL's protocol
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend

#4783 fix(Authentication): OIDC auth, issue with redirect URL's protocol (#4774) [dev-23.04.x]
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend, backport

#4777 enh(Change Logs): Insert change logs in /configuration/hosts endpoints (#4770) [dev-24.04.x]
  centreon/src/Core/ActionLog/Application/Repository/WriteActionLogRepositoryInterface.php
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/ActionLog/Infrastructure/Repository/DbWriteActionLogRepository.php
  centreon/src/Core/Host/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostLogRepository.php
Labels: area/backend, backport

#4780 fix(tests): flaky e2e test in for widget metric graph configuration
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
Labels: area/test

#4785 enh(Authentification): Reschedule cron to delete expired token to execute every minute
  centreon/cron/outdated-token-removal.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend
