Repository centreon/centreon, pull requests merged in 2024-03, with the labels that each got.

#3472 fix(api) check user rights and pageName validity in userFilter endpoints (#3086)
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Application/Controller/FilterController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/tests/api/features/UserFilter.feature
Labels: backport

#3462 feat(resource-access): add endpoint to delete resource access rule
  centreon/doc/API/centreon-cloud-api-v24.04.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/FindUpdateAndDeleteRule.yaml
  centreon/src/Core/ResourceAccess/Application/Exception/RuleException.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRule/DeleteRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRule/FindRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRules.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRule.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRule/DeleteRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRule/DeleteRuleRoute.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/DeleteRule/DeleteRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRule/FindRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesTest.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleTest.php
  centreon/tests/php/Core/ResourceAccess/Infrastructure/API/DeleteRule/DeleteRulePresenterStub.php
Labels: area/backend

#3171 feat(test): e2e tests for cloud notifications
  .github/docker/centreon-web/alma8/slim-configuration/include-path.txt
  .github/docker/centreon-web/alma9/slim-configuration/include-path.txt
  .github/docker/centreon-web/bullseye/slim-configuration/include-path.txt
  centreon/packages/js-config/cypress/e2e/commands/configuration.ts
  centreon/tests/e2e/commons.ts
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create/index.ts
  centreon/tests/e2e/features/Cloud-notifications/02-notification-duplicate.feature
  centreon/tests/e2e/features/Cloud-notifications/02-notification-duplicate/index.ts
  centreon/tests/e2e/features/Cloud-notifications/03-notification-delete.feature
  centreon/tests/e2e/features/Cloud-notifications/03-notification-delete/index.ts
  centreon/tests/e2e/features/Cloud-notifications/04-notification-edit.feature
  centreon/tests/e2e/features/Cloud-notifications/04-notification-edit/Index.ts
  centreon/tests/e2e/features/Cloud-notifications/05-notification-listing.feature
  centreon/tests/e2e/features/Cloud-notifications/05-notification-listing/index.ts
  centreon/tests/e2e/features/Cloud-notifications/common.ts
  centreon/tests/e2e/fixtures/notifications/data-for-notification.json
  centreon/tests/e2e/fixtures/notifications/notification-creation.json
Labels: area/test

#3483 fix (gorgone): Gorgone fix backport (#3473)
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/client_server_zmq.md
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3484 fix (gorgone): Gorgone fix backport (#3473)
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/client_server_zmq.md
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3485 fix (gorgone): Gorgone fix backport (#3473)
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/client_server_zmq.md
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: backport

#3467 fix(api) fix request filters on centreon_realtime_hosts
  centreon/www/api/class/centreon_realtime_hosts.class.php
Labels: area/backend

#3471 enh(migration) change api url construction
  centreon/src/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsCommand.php
  centreon/src/Core/Command/Infrastructure/Repository/ApiWriteCommandRepository.php
Labels: area/backend

#3524 feat(resource-access): add mass delete endpoint
  centreon/doc/API/centreon-cloud-api-v24.04.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/DeleteRules.yaml
  centreon/doc/API/latest/Cloud/ResourceAccessManagement/Schema/DeleteRulesRequest.yaml
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRules.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRulesPresenterInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRulesRequest.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRulesResponse.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRulesStatusResponse.php
  centreon/src/Core/ResourceAccess/Domain/Model/ResponseCode.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRule/DeleteRuleRoute.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesPresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesRoute.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesSchema.json
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRulesTest.php
  centreon/tests/php/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesPresenterStub.php
Labels: area/backend

#3407 enh(API): Added search by host, host group & host category for FindServiceCategories endpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
  centreon/src/Utility/SqlConcatenator.php
Labels: area/backend

#3113 test(notification): Add scenario to test 1000+ services notification
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
Labels: area/test

#3469 feat(Resource Access) - Delete rule from Listing
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions Delete button -- closes a delete confirmation dialog when Cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions Delete button -- displays a confirmation dialog containing the resource access rule's name upon clicking on Delete button in rule listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions Delete button -- displays an error message upon failed deletion.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/DeleteButton.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/DeleteConfirmationDialog.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/DeleteConfirmationDialog.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/index.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/useDelete.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/endpoints.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/useDeleteRequest.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Actions.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Actions.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/index.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/columns.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Page.tsx
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: documentation, area/ui

#3345 enh(authentication): move the removal of old tokens to a cron
  centreon/cron/outdated-token-removal.php
  centreon/src/Centreon/Domain/Authentication/UseCase/AuthenticateApi.php
  centreon/src/Centreon/Domain/Authentication/UseCase/Logout.php
  centreon/src/Core/Security/Authentication/Application/Repository/WriteTokenRepositoryInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/src/Security/Domain/Authentication/AuthenticationService.php
  centreon/src/Security/Domain/Authentication/Interfaces/AuthenticationServiceInterface.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/tests/php/Centreon/Domain/Authentication/UseCase/AuthenticateApiTest.php
  centreon/tests/php/Centreon/Domain/Authentication/UseCase/LogoutTest.php
  centreon/tests/php/Security/Domain/Authentication/AuthenticationServiceTest.php
  centreon/tmpl/install/centreon.cron
  centreon/www/api/index.php
Labels: area/backend

#3572 fix(autodiscovery): fix regex for gorgone to execute run_save_discovered_host script for discovered hosts
  centreon-gorgone/config/gorgoned-central-ssh.yml
  centreon-gorgone/config/gorgoned-central-zmq.yml
  centreon-gorgone/config/gorgoned-poller.yml
  centreon-gorgone/config/gorgoned-remote-ssh.yml
  centreon-gorgone/config/gorgoned-remote-zmq.yml
  centreon-gorgone/contrib/gorgone_config_init.pl
  centreon-gorgone/docs/migration.md
  centreon-gorgone/docs/modules/core/action.md
  centreon-gorgone/docs/poller_pull_configuration.md
  centreon-gorgone/docs/rebound_configuration.md
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: area/backend

#3327 feat(brokercfg) new endpoint: AddBrokerOutput
  centreon/config/packages/Centreon.yaml
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Broker/AddBrokerOutput.yaml
  centreon/doc/API/v24.04/Configuration/Broker/QueryParameter/BrokerId.yaml
  centreon/doc/API/v24.04/Configuration/Broker/Schema/AddBrokerOutputRequest.yaml
  centreon/doc/API/v24.04/Configuration/Broker/Schema/AddBrokerOutputResponse.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Broker/Application/Exception/BrokerException.php
  centreon/src/Core/Broker/Application/Repository/ReadBrokerOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/Repository/ReadBrokerRepositoryInterface.php
  centreon/src/Core/Broker/Application/Repository/WriteBrokerOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/AddBrokerOutput.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/AddBrokerOutputPresenterInterface.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/AddBrokerOutputRequest.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/AddBrokerOutputResponse.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/BrokerOutputValidator.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerOutput/TypeDto.php
  centreon/src/Core/Broker/Domain/Model/BrokerOutput.php
  centreon/src/Core/Broker/Domain/Model/BrokerOutputField.php
  centreon/src/Core/Broker/Domain/Model/NewBrokerOutput.php
  centreon/src/Core/Broker/Domain/Model/Type.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputController.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputPresenter.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputRoute.yaml
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputSchema.json
  centreon/src/Core/Broker/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Broker/Infrastructure/Repository/DbReadBrokerOutputRepository.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbReadBrokerRepository.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbWriteBrokerOutputRepository.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerOutput/AddBrokerOutputTest.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerOutput/BrokerOutputValidatorTest.php
  centreon/tests/php/Core/Broker/Domain/Model/BrokerOutputTest.php
  centreon/tests/php/Core/Broker/Domain/Model/NewBrokerOutputTest.php
  centreon/tests/php/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputPresenterStub.php
Labels: area/backend

#3461 fix(api/conf) categories missing in service/service template creation response for non-admin
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
Labels: area/backend

#3568 enh(Resource Access): Enable/Disable rule
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions enable-disable action -- displays an error message upon failed disabling.snap.png
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Activate.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Activate.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/index.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/testUtils.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/columns.tsx
Labels: area/ui

#3560 Fix(UI): Fix unsynced statuses display on group monitoring
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/Columns/Statuses/Statuses.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/GroupMonitoring.tsx
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/atoms.ts
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/models.ts
  centreon/www/widgets/src/centreon-widget-groupmonitoring/src/useGroupMonitoring.ts
Labels: area/ui

#3598 Fix(UI): Fix listing with same sub item ids
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- Sub items -- collapses the row when the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- Sub items -- expands the row when the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- collapses the row when the corresponding icon si clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- displays the last column on several lines in extended mode when the isResponsive prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Listing/Listing.cypress.spec.tsx/Listing -- expands the row when the corresponding icon si clicked.snap.png
  centreon/packages/ui/src/Listing/Listing.cypress.spec.tsx
  centreon/packages/ui/src/Listing/Row/Row.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/Listing/useStyleTable.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/useStatusGridCondensed.ts
Labels: area/ui

#3585 feat(Resource Access): Mass delete rules
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing header actions mass delete -- confirms that multiple delete button is disabled when no resource access rule is selected and it becomes active once at least one row is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing header actions mass delete -- displays a confirmation dialog when multiple delete button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing header actions mass delete -- displays a success message when all selected rules are deleted.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing header actions mass delete -- displays a warning message containing the list of names that failed to delete.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing header actions mass delete -- displays an error message when the deletion of all rules fails.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/DeleteConfirmationDialog.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Delete/useDelete.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/endpoints.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/useDeleteRequest.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Header/Header.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Header/Header.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/testUtils.tsx
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: documentation, area/ui

#3610 enh(API): Added search by nost categories in FindHostGroups endpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
Labels: area/backend

#3577 enh(authentication): move the removal of old tokens to a cron (#3345)
  centreon/cron/outdated-token-removal.php
  centreon/src/Centreon/Domain/Authentication/UseCase/AuthenticateApi.php
  centreon/src/Centreon/Domain/Authentication/UseCase/Logout.php
  centreon/src/Core/Security/Authentication/Application/Repository/WriteTokenRepositoryInterface.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/src/Security/Domain/Authentication/AuthenticationService.php
  centreon/src/Security/Domain/Authentication/Interfaces/AuthenticationServiceInterface.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/tests/php/Centreon/Domain/Authentication/UseCase/AuthenticateApiTest.php
  centreon/tests/php/Centreon/Domain/Authentication/UseCase/LogoutTest.php
  centreon/tests/php/Security/Domain/Authentication/AuthenticationServiceTest.php
  centreon/tmpl/install/centreon.cron
  centreon/www/api/index.php
Labels: area/backend

#3574 fix(php): avoid chmod warning on poller config generation
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
  centreon/www/class/config-generate-remote/Abstracts/AbstractObject.php
  centreon/www/class/config-generate-remote/Backend.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: backport

#3592 Fix(UI): Fix fullscreen shortcut and labels (#3489)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
  centreon/packages/ui/src/utils/useFullscreen/useFullscreenListener.ts
  centreon/www/front_src/src/Header/UserMenu/translatedLabels.ts
Labels: backport

#3613 enh(dashboards) : adapt the frontend to status chart endpoint
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.0.php
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
Labels: area/ui, area/backend

#3565 Fix(UI): Do not redirect to the forced provider when an authentication occured (MON-37875)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui, backport

#3573 enh(ci): remove useless legacy behat tests (#3564)
  centreon/behat.yml
  centreon/features/Broker.feature
  centreon/features/BrokerConfiguration.feature
  centreon/features/LanguageSelection.feature
  centreon/features/PaginationSelect2.feature
  centreon/features/SaveSearchSelect2.feature
  centreon/features/SelectAllSelect2.feature
  centreon/features/TimezoneInMonitoring.feature
  centreon/features/bootstrap/BrokerConfigurationContext.php
  centreon/features/bootstrap/BrokerContext.php
  centreon/features/bootstrap/LanguageSelectionContext.php
  centreon/features/bootstrap/PaginationSelect2Context.php
  centreon/features/bootstrap/SaveSearchSelect2Context.php
  centreon/features/bootstrap/SelectAllSelect2Context.php
  centreon/features/bootstrap/TimezoneInMonitoringContext.php
Labels: backport

#3612 fix(UI): Graph metrics widget can select more than 2 metric units
  centreon/cypress/fixtures/Dashboards/Dashboard/serviceMetrics.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays metrics with other units as disabled when the maximum of units are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metric as completly selected when all the related resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- excludes a resource when a metric is selected and a resource is unchecked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects all the resources related to the selected metric when a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Multiple metrics selection with several resources -- selects only the resource when a resource is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- displays the metrics and their own resources when the selector is clicked and metrics option are clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with several resources -- selects a metrics when the options list is expanded and a metric is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- Single metric selection with single resource -- displays the retrieved metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useRenderOptions.tsx
Labels: area/ui

#3566 Fix(UI): Do not redirect to the forced provider when an authentication occured (MON-37876)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui, backport

#3627 enh(api): add hostgroup filter to the FindHostCategoriesEndpoint
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/HostCategory/Application/Repository/ReadHostCategoryRepositoryInterface.php
  centreon/src/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategories.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/tests/php/Core/HostCategory/Application/UseCase/FindHostCategories/FindHostCategoriesTest.php
Labels: area/backend

#3384 enh (platform): added new API-type repository interface
  centreon/src/Core/Common/Application/Repository/ApiRepositoryInterface.php
Labels: area/backend

#3570 fix(api) fix request filters on centreon_realtime_hosts (#3467)
  centreon/www/api/class/centreon_realtime_hosts.class.php
Labels: area/backend, backport

#3588 enh(UI): Fix error keep showing up + fix up validation schema generation
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not display the name of the widget when the corresponding button is clicked.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/atoms.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useValidationSchema.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/useWidgetModal.ts
Labels: area/ui

#3563 fix(api) fix request filters on centreon_realtime_hosts (#3467)
  centreon/www/api/class/centreon_realtime_hosts.class.php
Labels: area/backend, backport

#3628 fix(dashboards) : the save button does not become disabled upon widget creation
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/Actions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
Labels: area/ui

#3632 enh(UI): Block navigation when a dashboard is being edited
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not display the name of the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- blocks the redirection when a dashboard is being edited, a dashboard is updated, the user goes to another page and the close button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- does not save changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- saves changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- closes the modal when the cancel button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- closes the modal when the close button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- closes the modal when the confirm button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- displays the confirm button as danger when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- displays the confirm button as disabled when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- displays the modal with dynamic labels.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- displays the modal with static labels.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx/Confirmation modal -- displays the modal without the close button when a prop is set.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Dialog/UnsavedChanges/index.tsx
  centreon/packages/ui/src/Dialog/UnsavedChanges/translatedLabels.ts
  centreon/packages/ui/src/InputField/Select/index.tsx
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRights/storiesData.ts
  centreon/packages/ui/src/components/ItemComposition/ItemComposition.styles.ts
  centreon/packages/ui/src/components/Modal/ConfirmationModal/ConfirmationModal.cypress.spec.tsx
  centreon/packages/ui/src/components/Modal/ConfirmationModal/ConfirmationModal.stories.tsx
  centreon/packages/ui/src/components/Modal/ConfirmationModal/ConfirmationModal.tsx
  centreon/packages/ui/src/components/Modal/index.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/atoms.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/components/DashboardSaveBlockerModal.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useDashboardSaveBlocker.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useUnsavedChangesWarning.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
Labels: area/ui

#3562 fix(api) fix request filters on centreon_realtime_hosts (#3467)
  centreon/www/api/class/centreon_realtime_hosts.class.php
Labels: area/backend, backport

#3626 feat(Resource Access): Duplicate rule
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing action duplicate a rule -- creates a duplicated rule.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing action duplicate a rule -- displays an error message when an already existing rule name is entered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing action duplicate a rule -- displays an error message when duplication of a rule fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing action duplicate a rule -- displays required error message when the name remains empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing action duplicate a rule -- opens a duplication form when a duplicate button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/DuplicateButton.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/DuplicateConfirmationDialog.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/DuplicationForm.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/index.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/useDuplicate.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/Duplicate/useValidateName.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/adapters.ts
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/useDuplicateRequest.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Actions.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Actions/Actions.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Page.tsx
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: documentation, area/ui

#3639 fix(api/conf) categories missing in service/service template creation response for non-admin (#3461)
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbReadServiceCategoryRepository.php
Labels: area/backend, backport

#3633 enh(dashboads) : widgets : display warning message when no resource is matching the filters selected
  centreon/packages/ui/src/Graph/BarStack/BarStack.cypress.spec.tsx
  centreon/packages/ui/src/Graph/BarStack/ResponsiveBarStack.tsx
  centreon/packages/ui/src/Graph/BarStack/models.ts
  centreon/packages/ui/src/Graph/BarStack/useResponsiveBarStack.ts
  centreon/packages/ui/src/Graph/PieChart/PieChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/PieChart/ResponsivePie.tsx
  centreon/packages/ui/src/Graph/PieChart/models.ts
  centreon/packages/ui/src/Graph/PieChart/useResponsivePie.ts
  centreon/packages/ui/src/Graph/translatedLabels.ts
  centreon/www/widgets/src/NoResourcesFound/NoResourcesFound.styles.ts
  centreon/www/widgets/src/NoResourcesFound/NoResourcesFound.tsx
  centreon/www/widgets/src/NoResourcesFound/index.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/StatusChart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/models.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/translatedLabels.ts
Labels: area/ui

#3656 fix(login): remove loop when connect through OpenID connect (forced)
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
Labels: area/backend

#3653 Fix(UI): Fix dashboards decoder
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
Labels: area/ui

#3652 feat(Resource Access): Selection of all resource in datasets
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- sends a request to add a new Resource Access Rule when All resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- sends a request to edit a Resource Access Rule when a configured resources are changed to All resources in datasets.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useValidationSchema.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: documentation, area/ui

#3663 fix(api) fix user rights check on FindMedias and AddMedias endpoints
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMedias.php
Labels: area/backend

#3651 Fix(UI): Fix fullscreen on legacy page
  centreon/packages/ui/src/ThemeProvider/index.tsx
  centreon/packages/ui/src/utils/useFullscreen/useFullscreen.ts
  centreon/www/front_src/src/route-components/legacyRoute/index.tsx
Labels: area/ui

#3643 Fix(UI): Service retrieves resources without perfomance data for non-metric based widgets
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx/Metrics -- displays metrics with included hosts when resources are fulfilled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx/Resources -- deletes a resource when the corresponding is clicked and corresponding prop are set.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/atoms.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/widgets/src/centreon-widget-graph/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
  centreon/www/widgets/src/centreon-widget-singlemetric/properties.json
Labels: area/ui

#3675 Fix(UI): Fix fullscreen on legacy page (#3651)
  centreon/packages/ui/src/ThemeProvider/index.tsx
  centreon/packages/ui/src/utils/useFullscreen/useFullscreen.ts
  centreon/www/front_src/src/route-components/legacyRoute/index.tsx
Labels: backport

#3676 Fix(UI): Fix dashboards decoder (#3653)
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
Labels: backport

#3406 feat(api/conf) new endpoint: UpdateStreamConnectorFile
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/v24.04/Configuration/Broker/QueryParameter/OutputId.yaml
  centreon/doc/API/v24.04/Configuration/Broker/UpdateStreamConnectorFile.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Broker/Application/Exception/BrokerException.php
  centreon/src/Core/Broker/Application/Repository/WriteBrokerOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/Repository/WriteBrokerRepositoryInterface.php
  centreon/src/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFile.php
  centreon/src/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFilePresenterInterface.php
  centreon/src/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFileRequest.php
  centreon/src/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFileResponse.php
  centreon/src/Core/Broker/Domain/Model/BrokerOutput.php
  centreon/src/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFileController.php
  centreon/src/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFilePresenter.php
  centreon/src/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFileRoute.yaml
  centreon/src/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFileSchema.json
  centreon/src/Core/Broker/Infrastructure/Repository/DbWriteBrokerOutputRepository.php
  centreon/src/Core/Broker/Infrastructure/Repository/FileBrokerRepository.php
  centreon/tests/php/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFileTest.php
  centreon/tests/php/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFilePresenterStub.php
Labels: area/backend

#3666 fix(login): remove loop when connect through OpenID connect (forced) …
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php
Labels: area/backend

#3664 Fix(Dashboards) : error when filtring by service groups on display by host
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
Labels: area/ui

#3640 enh(topology): Remove beta mention on Dashboards
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.04.0.php
Labels: area/ui

#3665 fix(api) hide macros of type password in response
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostOnPremPresenter.php
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostSaasPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateOnPremPresenter.php
  centreon/src/Core/HostTemplate/Infrastructure/API/AddHostTemplate/AddHostTemplateSaasPresenter.php
  centreon/src/Core/Service/Infrastructure/API/AddService/AddServiceOnPremPresenter.php
  centreon/src/Core/Service/Infrastructure/API/AddService/AddServiceSaasPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateOnPremPresenter.php
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateSaasPresenter.php
Labels: area/backend

#3716 enh(resource-access): handle the ALL resources filter type
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/Schema/DatasetFilter.yaml
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/Schema/DatasetFilterWithNames.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/FindAndUpdateHostGroup.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/Schema/FindAndUpdateHostGroup.yaml
  centreon/doc/API/v24.04/Configuration/Host/Schema/FindHostsResponse.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/AddServiceRequest.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/AddServiceResponse.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/FindServicesResponse.yaml
  centreon/doc/API/v24.04/Configuration/Service/Schema/PartialUpdateServiceRequest.yaml
  centreon/doc/API/v24.04/Configuration/ServiceTemplate/Schema/AddServiceTemplateResponse.yaml
  centreon/doc/API/v24.04/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleValidation.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRule/DeleteRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/DeleteRules/DeleteRules.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRule/FindRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRules.php
  centreon/src/Core/ResourceAccess/Application/UseCase/PartialRuleUpdate/PartialRuleUpdate.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRule.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilter.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterValidator.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRuleSchema.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleSchema.yaml
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#2571 feat(test): Init the full Postman API V2 collection
  .github/workflows/newman.yml
  centreon/tests/rest_api/README.md
  centreon/tests/rest_api/collections/api-administration/.env
  centreon/tests/rest_api/collections/api-administration/Media.postman_collection.json
  centreon/tests/rest_api/collections/api-administration/administration.postman_environment.json
  centreon/tests/rest_api/collections/api-administration/images/Carapuce.png
  centreon/tests/rest_api/collections/api-administration/images/Herbizarre.png
  centreon/tests/rest_api/collections/api-administration/setup-web.sh
  centreon/tests/rest_api/collections/api-administration/setup.sh
  centreon/tests/rest_api/collections/api-configuration/.env
  centreon/tests/rest_api/collections/api-configuration/0 - Add needed users.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Command.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Connectors.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/GraphTemplate.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host Category.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host Group.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host Severity.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host Template.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service Category.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service Group.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service Severity.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service Template.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Timeperiod.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/configuration.postman_environment.json
  centreon/tests/rest_api/collections/api-configuration/setup-web.sh
  centreon/tests/rest_api/collections/contact/21-Contact-management-Centreon-Web-Refactored-API-Test-Collection.postman_collection.json
Labels: area/test

#3668 enh(UI): Refactor value display using a tooltip
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values whent the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/src/Graph/LineChart/Header/index.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/AnchorPoint/TooltipAnchorPoint.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/AnchorPoint/useTickGraph.ts
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/AnchorPoint/useTooltipAnchorPoint.ts
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/GraphValueTooltip/GraphValueTooltip.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/GraphValueTooltip/useGraphValueTooltip.ts
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/GraphValueTooltip/useGraphValueTooltipStyles.ts
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/index.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/interactionWithGraphAtoms.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/InteractiveValue.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/useInteractiveValues.ts
  centreon/packages/ui/src/Graph/LineChart/LineChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/LineChart/LineChart.styles.ts
  centreon/packages/ui/src/Graph/LineChart/LineChart.tsx
  centreon/packages/ui/src/Graph/LineChart/mockedData/lastDayWithIncompleteValues.json
  centreon/packages/ui/src/Graph/LineChart/mockedData/lastDayWithNullValues.json
  centreon/packages/ui/src/Graph/LineChart/models.ts
  centreon/packages/ui/src/Graph/common/timeSeries/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/Panel.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/usePanelStyles.ts
Labels: area/ui

#3734 feat(test): Remove space in Postman collections names
  centreon/tests/rest_api/collections/api-configuration/Add_needed_users.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host_Category.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host_Group.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host_Severity.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Host_Template.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Category.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Group.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Severity.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Template.postman_collection.json
Labels: area/test

#3670 fix(api) fix search by dates in FindApiTokens
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
Labels: area/backend

#3708 fix(clapi) fix downtime creation on services linked to a service group
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend

#3649 enh(CEIP): update metadata roles 4 cloud
  centreon/src/Core/User/Application/UseCase/FindUsers/FindUsers.php
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/class/centreonUUID.class.php
Labels: area/backend

#3737 Fix(dashboards) : fix the search query in status grid endpoint
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
Labels: area/ui

#3736 feat(test): Add enhanced version of Postman script for Services
  centreon/tests/rest_api/collections/api-configuration/Service.postman_collection.json
Labels: area/test
