Repository centreon/centreon, pull requests merged in 2024-08, with the labels that each got.

#4787 enh(Authentification): Reschedule cron to delete expired token to execute every minute (#4785) [dev-24.04.x]
  centreon/cron/outdated-token-removal.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend, backport

#4788 enh(Authentification): Reschedule cron to delete expired token to execute every minute (#4785) [dev-23.10.x]
  centreon/cron/outdated-token-removal.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend, backport

#4789 enh(Authentification): Reschedule cron to delete expired token to execute every minute (#4785) [dev-23.04.x]
  centreon/cron/outdated-token-removal.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend, backport

#4791 fix(host/broker): Use correct headers to connect to APIv2 through legacy
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: area/backend

#4795 fix(Authentication): OIDC auth, issue with redirect URL's protocol (#4774) [dev-23.10.x]
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: area/backend, backport

#4803 Fix typing issue leading to strange snackbar error message
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend

#4805 fix(web): Prevent some weird snackbar error message in some case
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
Labels: area/backend, backport

#4804 fix(top-counter): make sure that access groups are up to date before fetch
  centreon/www/class/centreonACL.class.php
Labels: area/backend

#4806 fix(Notifications): Host events are set to 1 when updating notification
  centreon/src/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactory.php
Labels: area/backend

#4809 fix(Notifications): Host events are set to 1 when updating notification (#4806) [release-24.07-next]
  centreon/src/Core/Notification/Infrastructure/Repository/DbNotifiableResourceFactory.php
Labels: area/backend, backport

#4807 fix(top-counter): make sure that access groups are up to date before fetch (#4804)
  centreon/www/class/centreonACL.class.php
Labels: area/backend, backport

#4320 fix MC service activate
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#4728 fix(saml): Accept a RequestedAuthnContext that is stronger than the default (MON-24158)
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
Labels: area/backend

#4745 Update clapi version query
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: area/backend

#4701 feat(acc) new endpoint DeleteAcc
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/DeleteAcc.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/QueryParameter/AccId.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/WriteAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/WriteVaultAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/DeleteAcc/DeleteAcc.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/DeleteAcc/DeleteAccController.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/DeleteAcc/DeleteAccRoute.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbWriteAccRepository.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/Vault/VmWareV6WriteVaultAccRepository.php
  centreon/src/Core/MonitoringServer/Application/Repository/ReadMonitoringServerRepositoryInterface.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/DbReadMonitoringServerRepository.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/DeleteAcc/DeleteAccTest.php
Labels: area/backend

#4819 Update clapi version query (#4745)
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: backport

#4818 Update clapi version query (#4745)
  centreon/www/class/centreon-clapi/centreonAPI.class.php
Labels: backport

#4821 fix MC service activate (#4320)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: backport

#4808 fix(graph) : prepared query fixed
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#4771 fix(Contact) : prepared queries in contacts form fixed
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend

#4832 fix(anomalydetection): some unneeded logs are removed (#4731)
  centreon/lua/centreon-cloud-notifications.lua
Labels: backport

#4831 Fixed a broken join leading to endless sql query
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend

#4769 feat(ACC) new enpdoint FindPollers
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/FindPollers.yaml
  centreon/doc/API/latest/onPremise/Configuration/AdditionalConnectorConfiguration/Schema/FindPollersResponse.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/ReadAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollers.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersResponse.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersController.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersPresenter.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/API/FindPollers/FindPollersRoute.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbReadAccRepository.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersPresenterStub.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/FindPollers/FindPollersTest.php
Labels: area/backend

#4833 [dev-24.04.x] fix(performance): Fixed a query on Resource Status causing unavailable interface
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: backport

#4834 [dev-23.10.x] fix(performance): Fixed a query on Resource Status causing unavailable interface
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: backport

#4829 doc(api): Remove part of New and Updated feature & add 24.07 version
  centreon/doc/API/centreon-cloud-api.yaml
Labels: documentation, area/backend

#4849 enh(ci): manage multiple release baseline files (#4848)
  .github/workflows/veracode-analysis.yml
Labels: backport, ci

#4857 enh(ci): manage multiple release baseline files (#4848)
  .github/workflows/veracode-analysis.yml
Labels: backport, ci

#4856 enh(ci): manage multiple release baseline files (#4848)
  .github/workflows/veracode-analysis.yml
Labels: backport, ci

#4855 enh(ci): manage multiple release baseline files (#4848)
  .github/workflows/veracode-analysis.yml
Labels: backport, ci

#4853 fix(ci): adding forward slash replacement step in behat testing (#4846)
  .github/workflows/behat-test.yml
Labels: backport

#4854 enh(ci): manage multiple release baseline files (#4848)
  .github/workflows/veracode-analysis.yml
Labels: backport, ci

#4835 [Dashboard] Link tests merged with JIRA feature file
  centreon/tests/e2e/features/Dashboards/01-dashboard-creation.feature
  centreon/tests/e2e/features/Dashboards/01-dashboard-creation/index.ts
  centreon/tests/e2e/features/Dashboards/08-widget-generic-text-configuration.feature
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration.feature
Labels: area/test

#4844 Mon 146773 24.04
  centreon/tests/e2e/features/Dashboards/01-dashboard-creation.feature
  centreon/tests/e2e/features/Dashboards/01-dashboard-creation/index.ts
  centreon/tests/e2e/features/Dashboards/08-widget-generic-text-configuration.feature
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration.feature
Labels: area/test

#4845 [E2E] Uncomment the ACK TC
  centreon/tests/e2e/features/Resources-status/02-acknowledgments.feature
  centreon/tests/e2e/features/Resources-status/02-acknowledgments/index.ts
Labels: area/test

#4852 [E2E] Uncomment the ACK TC on dev-24.04.x
  centreon/tests/e2e/features/Resources-status/02-acknowledgments/index.ts
Labels: area/test

#4828 fix(CustomView) : prepared query for host monitoring fixed
  centreon/www/class/centreonLog.class.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend

#4859 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4843 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4858 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4839 chore(deps): Update JQuery to 3.7.1 and JQuery UI to 1.14.0
  centreon/www/include/common/javascript/jquery/jquery-ui-tabs-rotate.js
  centreon/www/include/common/javascript/jquery/jquery-ui.js
  centreon/www/include/common/javascript/jquery/jquery.min.js
  centreon/www/include/common/javascript/jquery/jquery.ui.widget.js
Labels: area/backend

#4874 chore(deps): Update JQuery to 3.7.1 and JQuery UI to 1.14.0 (#4839)
  centreon/www/include/common/javascript/jquery/jquery-ui-tabs-rotate.js
  centreon/www/include/common/javascript/jquery/jquery-ui.js
  centreon/www/include/common/javascript/jquery/jquery.min.js
  centreon/www/include/common/javascript/jquery/jquery.ui.widget.js
Labels: backport

#4867 fix(ack): take account of default ack configuration
  centreon/src/Centreon/Application/Controller/AcknowledgementController.php
Labels: area/backend

#4871 chore(core): Update frontend dependencies
  centreon/package.json
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/BarChart/BarChart.cypress.spec.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/utils.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
Labels: area/ui

#4762 enh(UI): Save and display dashboard thumbnails
  centreon/cypress/fixtures/Dashboards/dashboards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Navigation to dashboard -- does not navigate to the dashboard page when the listing mode is activated and a row is clicked on the actions cell.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Navigation to dashboard -- navigates to the dashboard page when the listing mode is activated and a row is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Overview -- creates a dashboard when the corresponding button is clicked and the title is filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Overview -- displays a welcome label when the dashboard library is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays all dashboard columns in the View as list when the user has editor global roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays the dashboard actions on the corresponding dashboard when the user has editor roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- displays the dashboards actions on all dashboards when the user has administrator global roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- does not display actions in the View as list when the user has viewer global role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Roles -- doesn't displays the dashboard actions when the user has viewer roles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- displays shares when a row is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- Shares -- revokes the access right when a row is expanded and the corresponding action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays column configuration button only in View as list.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays pagination in both view modes.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays the dashboards in View By lists by default.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- View mode -- displays the dashboards in View as card when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- creates a dashboard when the corresponding button is clicked and the title is filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards -- sends a shares update request when the shares are updated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards deletes a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards disables confirm duplication button when the new name is less than three characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards disables confirm update button when the new name is less than three characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards does not delete a dashboard upon clicking the corresponding icon button and cancelling the action by clicking the cancellation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards does not duplicate a dashboard upon clicking the corresponding icon button and cancelling the action by clicking the cancellation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards duplicates a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards edits a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as cards sends a shares update request when the shares are updated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list deletes a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list disables confirm duplication button when the new name is less than three characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list disables confirm update button when the new name is less than three characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list does not delete a dashboard upon clicking the corresponding icon button and cancelling the action by clicking the cancellation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list does not duplicate a dashboard upon clicking the corresponding icon button and cancelling the action by clicking the cancellation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list duplicates a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list edits a dashboard upon clicking the corresponding icon button and confirming the action by clicking the confirmation button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/View as list sends a shares update request when the shares are updated and the corresponding button is clicked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/ui/src/api/customFetch.ts
  centreon/packages/ui/src/components/DataTable/DataTable.styles.ts
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.styles.ts
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/api/decoders.ts
  centreon/www/front_src/src/Dashboards/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/api/models.ts
  centreon/www/front_src/src/Dashboards/api/useListDashboards.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.styles.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.tsx
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/Resources/Graph/Performance/ExportableGraphWithTimeline/exportToPng.ts
  centreon/www/front_src/src/assets/thumbnail-fallback-dark.svg
  centreon/www/front_src/src/assets/thumbnail-fallback-light.svg
Labels: area/ui

#4873 chore(deps): Update JQuery to 3.7.1 and JQuery UI to 1.14.0 (#4839)
  centreon/www/include/common/javascript/jquery/jquery-ui-tabs-rotate.js
  centreon/www/include/common/javascript/jquery/jquery-ui.js
  centreon/www/include/common/javascript/jquery/jquery.min.js
  centreon/www/include/common/javascript/jquery/jquery.ui.widget.js
Labels: backport

#4877 fix(CustomView) : prepared query for host monitoring fixed
  centreon/www/class/centreonLog.class.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#4876 fix(CustomView) : prepared query for host monitoring fixed
  centreon/www/class/centreonLog.class.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend, backport

#4869 chore(deps): absorb 24.08 dependabot GitHub Actions updates
  .github/workflows/actionlint.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/clean-cache.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/get-version.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/release.yml
  .github/workflows/synchronize-branches.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/synchronize-next-major-branches.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#4875 chore(deps): Update JQuery to 3.7.1 and JQuery UI to 1.14.0 (#4839)
  centreon/www/include/common/javascript/jquery/jquery-ui-tabs-rotate.js
  centreon/www/include/common/javascript/jquery/jquery-ui.js
  centreon/www/include/common/javascript/jquery/jquery.min.js
  centreon/www/include/common/javascript/jquery/jquery.ui.widget.js
Labels: backport

#4878 fix(ack): take account of default ack configuration
  centreon/src/Centreon/Application/Controller/AcknowledgementController.php
Labels: backport

#4880 fix(ack): take account of default ack configuration (#4878)
  centreon/src/Centreon/Application/Controller/AcknowledgementController.php
Labels: backport

#4862 enh(log) : improved logging with centreonlog
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend

#4886 fix(ACL): correctly remove invalid ids from filter
  centreon/www/class/centreonMsg.class.php
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: area/backend

#4889 fix(ACL): correctly remove invalid ids from filter (#4886)
  centreon/www/class/centreonMsg.class.php
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: backport

#4890 fix(ACL): correctly remove invalid ids from filter (#4886)
  centreon/www/class/centreonMsg.class.php
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: backport

#4888 fix(ACL): correctly remove invalid ids from filter (#4886)
  centreon/www/class/centreonMsg.class.php
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: backport

#4887 fix(ACL): correctly remove invalid ids from filter (#4886)
  centreon/www/class/centreonMsg.class.php
  centreon/www/include/options/accessLists/reloadACL/reloadACL.php
Labels: backport

#4892 fix(Configuration): Dynamicly generate Server ID in Gorgone configuration
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/popup.php
Labels: area/backend

#4895 fix(Configuration): Dynamicly generate Server ID in Gorgone configuration (#4892) [dev-23.10.x]
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/popup.php
Labels: area/backend, backport

#4894 fix(Configuration): Dynamicly generate Server ID in Gorgone configuration (#4892) [dev-24.04.x]
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/popup.php
Labels: area/backend, backport

#4896 fix(Configuration): Get metrics API call returns 500 in create meta service form
  centreon/www/api/class/centreon_monitoring_metric.class.php
Labels: area/backend

#4899 fix(Configuration): Get metrics API call returns 500 in create meta service form (#4896) [dev-24.04.x]
  centreon/www/api/class/centreon_monitoring_metric.class.php
Labels: area/backend, backport

#4906 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4905 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4907 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4904 fix(Contact) : prepared queries fixed in contact form
  centreon/config/centreon.config.php.template
  centreon/tests/php/www/class/CentreonDBTest.php
  centreon/tests/php/www/install/functionsTest.php
  centreon/www/class/CentreonDbConfig.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/exceptions/CentreonDbException.php
  centreon/www/class/exceptions/ExceptionAbstract.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: area/backend, backport

#4903 feat(broker configuration): Add new logs options
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgCentreonBrokerLog.php
  centreon/www/include/configuration/configCentreonBroker/centreon-broker.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configCentreonBroker/listCentreonBroker.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.09.0.php
  centreon/www/install/var/baseconf/centreon-broker.sql
Labels: area/backend

#4922 enh(log) : improved logging with centreonlog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend, backport

#4920 enh(log) : improved logging with centreonlog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#4921 enh(log) : improved logging with centreonlog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#4919 enh(log) : improved logging with centreonlog
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonDB.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/centreonService.class.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
Labels: area/backend, backport

#4910 fix(Install) - 24.04.0 update is not idempontent
  centreon/src/CentreonModule/Infrastructure/Service/CentreonModuleService.php
Labels: area/backend

#4925 fix(Install) - 24.04.0 update is not idempontent (#4910) [dev-24.04.x]
  centreon/src/CentreonModule/Infrastructure/Service/CentreonModuleService.php
  centreon/tests/rest_api/collections/authentication/01-Tokens.postman_collection.json
Labels: area/backend, backport

#4927 feat(test): Fix Tokens test
  centreon/tests/rest_api/collections/authentication/Tokens.postman_collection.json
Labels: area/test

#4861 fix(command) fix misc. errors and add debug in commands migration
  centreon/src/Core/Command/Application/UseCase/MigrateAllCommands/MigrateAllCommands.php
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/ApiWriteCommandRepository.php
  centreon/src/Core/Command/Infrastructure/Repository/DbReadCommandRepository.php
  centreon/src/Core/Proxy/Infrastructure/Repository/DbReadProxyRepository.php
Labels: area/backend

#4931 fix(CI): Add checks for incompatible resources on dataset
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
Labels: area/ui
