Repository centreon/centreon, pull requests merged in 2024-04, with the labels that each got.

#3753 Fix(dashboards) : Missing translation on groups monitoring widget
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: area/ui

#3772 enh(cloud): add required rule on host form for hg selection
  centreon/www/include/configuration/configObject/host/formHost.php
Labels: area/backend

#3694 feat(api): add host,hostgroup,hostcategory,servicecategory filters to…
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/src/Core/Host/Infrastructure/Repository/HostRepositoryTrait.php
  centreon/src/Core/HostCategory/Infrastructure/Repository/HostCategoryRepositoryTrait.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/HostGroupRepositoryTrait.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/ServiceCategoryRepositoryTrait.php
  centreon/src/Core/ServiceGroup/Application/Repository/ReadServiceGroupRepositoryInterface.php
  centreon/src/Core/ServiceGroup/Application/UseCase/FindServiceGroups/FindServiceGroups.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/ApiReadServiceGroupRepository.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
  centreon/src/Core/ServiceGroup/Infrastructure/Repository/ServiceGroupRepositoryTrait.php
  centreon/tests/php/Core/ServiceGroup/Application/FindServiceGroups/FindServiceGroupsTest.php
Labels: area/backend

#3693 feat(UI): Implement hierarchy tree + zoom components
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- cannot collapse a node when a node is not clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- collapses a node when a node is clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- cannot collapses a node when a leaf is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- collapses a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays customized links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays the whole tree.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands nodes by default when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- applies a scale down on the minimap when the content has negative translation values.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- applies a scale down on the minimap when the content is higher than the original height.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- clears the zoom when the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- displays the minimap in the bottom right when the prop to the corresponding value.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- displays the minimap when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- does not display the minimap when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- moves the view when the mouse is hover the content with the corresponding button pressed down.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms in when the content is scrolled down.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms in when the corresponding buttom is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms in when the minimap is scrolled up.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms out when the content is scrolled up.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms out when the corresponding buttom is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Zoom/Zoom.cypress.spec.tsx/Zoom -- zooms out when the minimap is scrolled down.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Graph/Tree/DescendantNodes.tsx
  centreon/packages/ui/src/Graph/Tree/Links.tsx
  centreon/packages/ui/src/Graph/Tree/StandaloneTree.tsx
  centreon/packages/ui/src/Graph/Tree/Tree.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Tree/Tree.stories.tsx
  centreon/packages/ui/src/Graph/Tree/Tree.tsx
  centreon/packages/ui/src/Graph/Tree/constants.ts
  centreon/packages/ui/src/Graph/Tree/index.ts
  centreon/packages/ui/src/Graph/Tree/models.ts
  centreon/packages/ui/src/Graph/Tree/stories/contents.tsx
  centreon/packages/ui/src/Graph/Tree/stories/datas.ts
  centreon/packages/ui/src/Graph/Tree/utils.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/packages/ui/src/components/Zoom/Minimap.tsx
  centreon/packages/ui/src/components/Zoom/Zoom.cypress.spec.tsx
  centreon/packages/ui/src/components/Zoom/Zoom.stories.tsx
  centreon/packages/ui/src/components/Zoom/Zoom.styles.tsx
  centreon/packages/ui/src/components/Zoom/Zoom.tsx
  centreon/packages/ui/src/components/Zoom/ZoomContent.tsx
  centreon/packages/ui/src/components/Zoom/constants.ts
  centreon/packages/ui/src/components/Zoom/localPoint.ts
  centreon/packages/ui/src/components/Zoom/models.ts
  centreon/packages/ui/src/components/Zoom/useMinimap.ts
  centreon/packages/ui/src/components/Zoom/useZoom.ts
  centreon/packages/ui/src/components/Zoom/utils.ts
  centreon/packages/ui/src/components/index.ts
  centreon/pnpm-lock.yaml
Labels: area/ui

#3788 fix(hostgroup): update host group form Alias
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#3791 feat(test): Update OpenID Provider test script
  centreon/tests/rest_api/collections/authentication/04-OpenID-Provider-Configuration.postman_collection.json
Labels: area/test

#3813 fix(Resource Status): View report is not available for non admin users
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
Labels: area/backend

#3810 fix (resource status): Fixed warning message concerning metric parameter in resource status
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
Labels: area/backend

#3470 enh(Resource Access): Adapted resource access form to dynamicly generate search parameters
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilters.ts
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
Labels: area/ui

#3825 fix(conf) fix service category listing query with non admin user and no search parameters
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend

#3827 feat(test): Remove already migrated behat
  centreon/tests/api/Context/HostCategoryContext.php
  centreon/tests/api/Context/HostSeverityContext.php
  centreon/tests/api/Context/TimePeriodConfigurationContext.php
  centreon/tests/api/behat.yml
  centreon/tests/api/features/CloudHost.feature
  centreon/tests/api/features/CloudHostGroup.feature
  centreon/tests/api/features/CloudHostTemplate.feature
  centreon/tests/api/features/Command.feature
  centreon/tests/api/features/Host.feature
  centreon/tests/api/features/HostCategory.feature
  centreon/tests/api/features/HostGroup.feature
  centreon/tests/api/features/HostSeverity.feature
  centreon/tests/api/features/HostTemplate.feature
  centreon/tests/api/features/ServiceCategory.feature
  centreon/tests/api/features/ServiceCloud.feature
  centreon/tests/api/features/ServiceGroup.feature
  centreon/tests/api/features/ServiceOnPrem.feature
  centreon/tests/api/features/ServiceSeverity.feature
  centreon/tests/api/features/ServiceTemplatesCloud.feature
  centreon/tests/api/features/ServiceTemplatesOnPrem.feature
  centreon/tests/api/features/TimePeriodConfiguration.feature
Labels: area/backend, area/test

#3817 fix(Resource Status): View report is not available for non admin users (#3813)
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HostHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/ServiceHypermediaProvider.php
Labels: area/backend

#3824 enh(UI): Enhance hierarchical information on widgets
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values whent the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/LineChart/LineChart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/LoadingProgress.tsx
  centreon/packages/ui/src/Graph/LineChart/BasicComponents/ThresholdLine.tsx
  centreon/packages/ui/src/Graph/LineChart/InteractiveComponents/index.tsx
  centreon/packages/ui/src/Graph/LineChart/Legend/Legend.styles.ts
  centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
  centreon/packages/ui/src/Graph/LineChart/LineChart.tsx
  centreon/packages/ui/src/Graph/LineChart/LoadingSkeleton.tsx
  centreon/packages/ui/src/Graph/LineChart/index.tsx
  centreon/packages/ui/src/Graph/LineChart/models.ts
  centreon/packages/ui/src/Graph/Text/Text.styles.ts
  centreon/packages/ui/src/Graph/Text/Text.tsx
  centreon/tests/e2e/features/Dashboards/09-widget-single-metric-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/usePanelStyles.ts
Labels: area/ui

#3814 enh(cloud): make resource access rule mandatory to create a Hostgroup
  centreon/www/api/class/centreon_administration_aclgroup.class.php
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroupCloud.ihtml
  centreon/www/include/configuration/configObject/hostgroup/formHostGroupOnPrem.ihtml
  centreon/www/include/configuration/configObject/hostgroup/help.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/options/accessLists/groupsACL/listGroupConfig.php
  centreon/www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#3786 fix(service): updating SQL requests
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3784 fix(service): updating SQL requests
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3785 fix(service): updating SQL requests
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3856 fix(graphs): Update initCurveList funtion
  centreon/www/class/centreonGraph.class.php
Labels: area/backend

#3815 fix(hostgroup): update host group form Alias
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#3859 fix(graphs): Update initCurveList funtion
  centreon/www/class/centreonGraph.class.php
Labels: area/backend

#3863 fix(graphs): Update initCurveList funtion
  centreon/www/class/centreonGraph.class.php
Labels: area/backend

#3867 fix(ram): update type of the column for the fresh installation
  centreon/www/install/createTables.sql
Labels: area/backend

#3846 fix(api): search capabilities for host group endpoint patched
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/AddAndFindHostGroups.yaml
  centreon/src/Core/HostGroup/Application/Repository/ReadHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/FindHostGroups/FindHostGroups.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/ApiReadHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/FindHostGroups/FindHostGroupsTest.php
Labels: area/backend

#3738 fix(clapi) fix downtime creation on services linked to a service group (#3708)
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend, backport

#3787 fix(service): updating SQL requests
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3809 fix (symfony): disabled the log for deprecated warning messages in the prod environment
  centreon/config/packages/Centreon.yaml
  centreon/config/packages/monolog.yaml
  centreon/src/Centreon/Domain/Log/ErrorFileHandler.php
Labels: area/backend

#3823 fix(api) add missing user's rights verifications on platform endpoints
  centreon/src/Centreon/Application/Controller/PlatformController.php
  centreon/src/Centreon/Application/Controller/PlatformTopologyController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/PlatformInformation/Exception/PlatformInformationException.php
  centreon/src/Centreon/Domain/PlatformInformation/UseCase/V20/UpdatePartiallyPlatformInformation.php
  centreon/src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyReadRepositoryInterface.php
  centreon/src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
  centreon/src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
  centreon/src/Centreon/Infrastructure/PlatformTopology/Repository/Model/PlatformTopologyFactoryRDB.php
  centreon/src/Centreon/Infrastructure/PlatformTopology/Repository/PlatformTopologyRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/PlatformInformation/UseCase/UpdatePartiallyPlatformInformationTest.php
  centreon/tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Labels: area/backend

#3841 fix(api) add topology authorization verification on administration parameter endpoint
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
Labels: area/backend

#3832 fix(conf) fix service category listing query with non admin user and no search parameters (#3825)
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend, backport

#3739 fix(clapi) fix downtime creation on services linked to a service group (#3708)
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend, backport

#3834 fix(conf) fix service category listing query with non admin user and no search parameters (#3825)
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend, backport

#3740 fix(clapi) fix downtime creation on services linked to a service group (#3708)
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend, backport

#3742 fix(clapi) fix downtime creation on services linked to a service group (#3708)
  centreon/www/class/centreon-clapi/centreonRtDowntime.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend, backport

#3849 fix(api) fix user rights verifications
  centreon/src/Centreon/Application/Controller/AcknowledgementController.php
  centreon/src/Centreon/Application/Controller/CheckController.php
  centreon/src/Centreon/Application/Controller/Monitoring/CommentController.php
  centreon/src/Core/Security/AccessGroup/Application/Repository/ReadAccessGroupRepositoryInterface.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbReadAccessGroupRepository.php
  centreon/tests/php/Centreon/Application/Controller/CheckController/HostTest.php
  centreon/tests/php/Centreon/Application/Controller/CheckController/MetaServiceTest.php
  centreon/tests/php/Centreon/Application/Controller/CheckController/ResourcesTestCase.php
  centreon/tests/php/Centreon/Application/Controller/CheckController/ServiceTest.php
  centreon/tests/php/Centreon/Application/Controller/CheckController/TestCase.php
  centreon/tests/php/Centreon/Application/Controller/Monitoring/CommentControllerTest.php
Labels: area/backend

#3871 fix (symfony): disabled the log for deprecated warning messages in the prod environment (#3809)
  centreon/config/packages/Centreon.yaml
  centreon/config/packages/monolog.yaml
  centreon/src/Centreon/Domain/Log/ErrorFileHandler.php
Labels: area/backend

#3833 fix(conf) fix service category listing query with non admin user and no search parameters (#3825)
  centreon/www/include/configuration/configObject/service_categories/listServiceCategories.php
Labels: area/backend, backport

#3812 feat(test): Add postman script for broker output
  centreon/tests/rest_api/collections/api-configuration/Broker_Output.postman_collection.json
Labels: area/test

#3873 enh(servicegroup): add resource access rule configuration on cloud co…
  centreon/www/api/class/centreon_administration_aclgroup.class.php
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/servicegroup/DB-Func.php
  centreon/www/include/configuration/configObject/servicegroup/formServiceGroup.ihtml
  centreon/www/include/configuration/configObject/servicegroup/formServiceGroup.php
  centreon/www/include/configuration/configObject/servicegroup/help.php
  centreon/www/include/configuration/configObject/servicegroup/serviceGroup.php
Labels: area/backend

#3870 fix(hc): host categories GET endpoint search capabilities fixed
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
Labels: area/backend

#3842 feat(Resource Access): Select all for hostgroups, servicegroups and hosts
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- sends a request to add a new Resource Access Rule when all host groups are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- sends a request to edit a Resource Access Rule when a configured resources are changed to All host groups in datasets.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useValidationSchema.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/initialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/AllOfResourceTypeCheckbox.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilter.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/components/DatasetFilters.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useAllOfResourceTypeCheckbox.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilters.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/AllOfResourceTypeCheckbox.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/styles/DatasetFilter.styles.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: documentation, area/ui

#3884 enh(tech): Add a Facade for Symfony's ULID
  centreon/src/Utility/Interfaces/StringGeneratorInterface.php
  centreon/src/Utility/ULIDGenerator.php
Labels: area/backend

#3789 fix(administration): Update img query
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#3783 fix (service): Update SQL queries on legacy service pages.
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#3895 fix(administration): Update img query
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#3897 fix(administration): Update img query
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#3894 fix(acl): allow to link service with service group when all_servicegroups is set to 1
  centreon/www/api/class/centreon_configuration_hostgroup.class.php
  centreon/www/api/class/centreon_configuration_servicegroup.class.php
  centreon/www/class/centreonACL.class.php
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend

#3882 feat(api) new endpoint FindPublicWidgetData (prerequisite)
  centreon/config/packages/security.yaml
  centreon/src/Core/User/Application/Repository/ReadUserRepositoryInterface.php
  centreon/src/Core/User/Infrastructure/Repository/DbReadUserRepository.php
Labels: area/backend

#3905 fix(user) Assign properly action roles to user for poller edition/deletion
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Labels: area/backend

#3904 fix(administration): Update img query
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#3910 feat(resource-access): handle all contacts / contactgroups
  centreon/cron/centAcl-Func.php
  centreon/cron/centAcl.php
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/FindUpdatesAndDeleteRule.yaml
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/Schema/AddOrUpdateRuleRequest.yaml
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/Schema/AddRuleResponse.yaml
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleRequest.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleResponse.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRuleValidation.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRule/FindRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRule/FindRuleResponse.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleRequest.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRuleValidation.php
  centreon/src/Core/ResourceAccess/Domain/Model/NewRule.php
  centreon/src/Core/ResourceAccess/Domain/Model/Rule.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRulePresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/AddRule/AddRuleSchema.json
  centreon/src/Core/ResourceAccess/Infrastructure/API/FindRule/FindRulePresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleController.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/UpdateRule/UpdateRuleSchema.json
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbRuleFactory.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/www/class/centreonACL.class.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-24.04.0.php
Labels: area/backend

#3868 fix(contactGroups): correctly check users rights for cloud
  centreon/src/Core/Contact/Application/UseCase/FindContactGroups/FindContactGroups.php
  centreon/tests/php/Core/Contact/Application/UseCase/FindContactGroups/FindContactGroupsTest.php
Labels: area/backend

#3912 enh(UI): Adapt access rights and new Tabs component
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- adds the contact as viewer when a contact is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- adds the contact group as editor when a contact group is selected and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- clears the autocomplete when a contact is selected and the contact type is changed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- displays a removed chip when the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- displays statistics when a contact is added, a contact is updated and a contact is removed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights in loading state.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- displays the access rights with an empty list.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- removes the contact from the list when the contact has been to the list and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- removes the updated chip when the contact role is updated and its initial role is assigned back.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- resets the role to viewer when the editor role is selected and a contact with viewer right is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- restores the contact when the contact is removed and the corresponding icon is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- retrieves contact groups when the contact group radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- retrieves contacts when the contact radio is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list with the updated contact.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx/Access rights -- submits the new acces rights list without the removed contact.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Tabs/Tabs.cypress.spec.tsx/Tabs -- displays tabs and their content when a tab is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/Tabs/Tabs.cypress.spec.tsx/Tabs -- displays tabs when tabList props are set.snap.png
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.cypress.spec.tsx
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.stories.tsx
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.styles.ts
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.tsx
  centreon/packages/ui/src/components/Form/AccessRights/Actions/Actions.styles.ts
  centreon/packages/ui/src/components/Form/AccessRights/Actions/Actions.tsx
  centreon/packages/ui/src/components/Form/AccessRights/Actions/useActions.ts
  centreon/packages/ui/src/components/Form/AccessRights/models.ts
  centreon/packages/ui/src/components/Form/AccessRights/storiesData.ts
  centreon/packages/ui/src/components/Form/AccessRights/useAccessRightsChange.ts
  centreon/packages/ui/src/components/Form/AccessRights/utils.ts
  centreon/packages/ui/src/components/List/Item/ListItem.styles.ts
  centreon/packages/ui/src/components/Tabs/Tab.styles.ts
  centreon/packages/ui/src/components/Tabs/TabPanel.tsx
  centreon/packages/ui/src/components/Tabs/Tabs.cypress.spec.tsx
  centreon/packages/ui/src/components/Tabs/Tabs.stories.tsx
  centreon/packages/ui/src/components/Tabs/Tabs.tsx
  centreon/packages/ui/src/components/Tabs/index.ts
  centreon/packages/ui/src/components/index.ts
  centreon/www/front_src/src/federatedModules/useFederatedModules.ts
  centreon/www/front_src/src/federatedModules/useFederatedWidgets.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/spec/StatusChart.cypress.spec.tsx
Labels: area/ui

#3937 fix (host): fix host listing query
  centreon/www/include/configuration/configObject/host/listHost.php
Labels: area/backend

#3944 enh(Resource Access): Added confirmation dialog on exit form
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- dispalys a confirmation dialog when the form is filled and a click occurs outside the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- displays a confirmation dialog when the form is filled and the Close button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- displays a confirmation dialog when the form is filled and the Exit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx/Create modal -- displays the business view resource type when the BAM module is installed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays a confiramtion dialog when the form is edited and a click occurs outside the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays a confirmation dialog when the form is edited and the Close button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx/Edit modal -- displays a confirmation dialog when the form is edited and the Exit button is clicked.snap.png
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/AddEditResourceAccessRuleModal.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/CloseModalConfirmationDialog.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/ActionButtons.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/atom.ts
  centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts
Labels: area/ui

#3949 enh(resource-access): handle dynamically all_* filters
  centreon/src/Core/ResourceAccess/Application/Repository/WriteDatasetRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/AddRule/AddRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRule/FindRule.php
  centreon/src/Core/ResourceAccess/Application/UseCase/UpdateRule/UpdateRule.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/AbstractDatasetFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilter.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterTypeInterface.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterValidator.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/HostFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/HostGroupFilterType.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/Providers/ServiceGroupFilterType.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostCategoryRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostGroupRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteHostRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteMetaServiceRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteServiceCategoryRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/Dataset/DbWriteServiceGroupRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRule/FindRuleTest.php
Labels: area/backend

#3952 Fix(core): Build errors
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/widgets/build.js
Labels: area/ui

#3947 Fix(UI): Fix pluralized translation
  centreon/packages/ui/src/utils/usePluralizedTranslation.test.ts
  centreon/packages/ui/src/utils/usePluralizedTranslation.ts
Labels: area/ui

#3955 fix(config): avoid request parameters overwrite issues (#3931)
  centreon/config/packages/Centreon.yaml
Labels: area/backend

#3956 fix(config): avoid request parameters overwrite issues (#3931)
  centreon/config/packages/Centreon.yaml
Labels: area/backend

#3957 Fix(UI): Fix resources delete button
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/spec/StatusChart.cypress.spec.tsx
Labels: area/ui

#3942 feat(realtime): update hypermedia providers
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/AbstractHypermediaProvider.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HypermediaCreator.php
  centreon/src/Core/Infrastructure/RealTime/Hypermedia/HypermediaProviderInterface.php
Labels: area/backend

#3847 enh (connector): update SQL queries of centreon connector form
  centreon/www/class/centreonConnector.class.php
  centreon/www/include/configuration/configObject/connector/connector.php
  centreon/www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend

#3970 fix(host_group): fix host group listing query (#3945)
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#3973 fix(host_group): fix host group listing query (#3945)
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend

#3974 enh (connector): update SQL queries of centreon connector form (#3847)
  centreon/www/class/centreonConnector.class.php
  centreon/www/include/configuration/configObject/connector/connector.php
  centreon/www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend

#3971 enh (connector): update SQL queries of centreon connector form (#3847)
  centreon/www/class/centreonConnector.class.php
  centreon/www/include/configuration/configObject/connector/connector.php
  centreon/www/include/configuration/configObject/connector/formConnector.php
Labels: area/backend
