Repository centreon/centreon, pull requests merged in 2024-11, with the labels that each got.

#5532 fix(widgets): fix query for Live Top 10 Memory usage
  centreon/www/widgets/live-top10-memory-usage/index.php
Labels: area/backend

#5104 enh(UI): Graph Chart - callback to update mousePosition [x,y]
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/packages/ui/src/Graph/Chart/InteractiveComponents/AnchorPoint/useTickGraph.ts
  centreon/packages/ui/src/Graph/Chart/InteractiveComponents/index.tsx
  centreon/packages/ui/src/Graph/Chart/helpers/index.ts
  centreon/packages/ui/src/Graph/Chart/index.tsx
  centreon/packages/ui/src/components/Zoom/Zoom.tsx
  centreon/packages/ui/src/components/Zoom/ZoomContent.tsx
  centreon/packages/ui/src/components/index.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui

#5347 Fix(UI); Change tooltips placement on status rows (#5302)
  centreon/www/front_src/src/Resources/Listing/columns/Status.tsx
Labels: backport

#5585 [E2E] Rewrite TrapsSNMPGroupConfiguration.feature
  centreon/behat.yml
  centreon/features/TrapsSNMPGroupConfiguration.feature
  centreon/features/bootstrap/TrapsSNMPGroupConfigurationContext.php
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration.feature
  centreon/tests/e2e/features/Snmp-Traps/02-traps-snmp-group-configuration/index.ts
  centreon/tests/e2e/features/Snmp-Traps/common.ts
  centreon/tests/e2e/fixtures/snmp-traps/snmp-trap.json
Labels: area/test

#5350 Fix(UI): Fix group chips (#5299)
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/GroupChip.tsx
Labels: backport

#5376 Backport([Core]): Issue with topology_id in Pollers menus
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
  centreon/www/include/configuration/configServers/listServers.ihtml
  centreon/www/include/configuration/configServers/listServers.php
Labels: backport

#5435 Backport([Resource Status]): Last notification set as 1970 in service/host details
  centreon/cypress/fixtures/resources/details/tabs/details/cards.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_check when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_notification when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_status_change when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for last_time_with_no_issue when the returned value is 0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Details/Details.cypress.spec.tsx/Details -- masks the card for next_check when the returned value is 0.snap.png
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/models.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
  centreon/www/front_src/src/Resources/decoders.ts
Labels: backport

#5373 fix(pollers, hosts, logs) : fix displayed name of object
  centreon/www/class/HtmlAnalyzer.php
  centreon/www/class/centreonInstance.class.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/class/utils/HtmlSanitizer.php
  centreon/www/include/Administration/brokerPerformance/brokerPerformance.php
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/include/configuration/configGenerateTraps/formGenerateTraps.php
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/listNagios.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Labels: area/backend, backport

#5421 Fix(UI): Fix event log redirections to Resources Status (#5296)
  centreon/src/Centreon/Application/Controller/MonitoringResourceController.php
Labels: backport

#5500 Fix(UI): Fix columns reset (#5355)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays acknowledgement details when an acknowledged state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding action_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding checks menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding fqdn menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding monitoring_server_name menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notes_url menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding notification menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding parent_alias menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays additional columns when selected from the corresponding severity menu.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Display additional columns -- displays downtime details when the downtime state chip is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with a limit param when the rows per page value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Listing request -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- displays notification column if the cloud notification feature is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Notification column -- hides notification column if the cloud notification feature is enabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays a highlighted row when a resource is in a critical state.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays first part of information when multiple (split by ) are available.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in compact mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- displays the listing in extended mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing -- reorders columns when a drag handle is focused and an arrow is pressed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- displays the services when the Expand button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sends a request to retrieve all sevices and their parents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Hosts -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- disables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sends a request with types service,metaservice.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- sorts columnns by worst status and duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by Service -- updates column names.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- enables columns drag and drop feature.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sends a request to get all resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sets the column names to the default ones.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing Visualization by all resources -- sorts columnns by newest duration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Duration column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Last check column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Parent column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Resource column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/column sorting -- executes a listing request with sort_by param and stores the order parameter in the URL when Tries column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is medium.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/listing actions when the size is small.snap.png
  centreon/www/front_src/src/Resources/Actions/Visualization/useVisualization.tsx
  centreon/www/front_src/src/Resources/Listing/listingAtoms.ts
Labels: backport

#5467 fix(status-chart): remove limit on status calculation, and group results
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend, backport

#5545 Backport([dev-24.10-next]): [API Token] User list incomplete for API token creation
  centreon/www/front_src/src/ApiTokens/TokenCreation/Form.tsx
  centreon/www/front_src/src/ApiTokens/api/endpoints.ts
  centreon/www/front_src/src/ApiTokens/api/models.ts
Labels: backport

#5411 fix(dashboard): error display when setting display to 0 in top bottom…
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx/TopBottomSettings -- displays the number of values when the value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx/TopBottomSettings -- enforces the value to be 1 when the user manually enters 0.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/TopBottomSettings.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TopBottomSettings/useTopBottomSettings.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
Labels: backport

#5554 fix(acl) : missing acl columns fixed for 24.04.8
  centreon/www/install/php/Update-24.04.8.php
Labels: bug, area/backend

#5599 fix(public playlists): Fix an uncovered state when loading a federate…
  centreon/www/front_src/src/components/FederatedPage/FederatedPage.tsx
  centreon/www/front_src/src/publicPages/PublicPagesManager.cypress.spec.tsx
Labels: backport

#5237 enh(ceip): add agent configuration to ceip stats
  centreon/cron/centreon-send-stats.php
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#5432 enh(UI): Improve copy paste breadcrumb on React pages
  centreon/cypress/downloads/downloads.html
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- copies the breadcrumb when the breadcrumd is being hovered and an icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- displays the breadcrumb trail with an additional label.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- displays the breadcrumb trail.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx
  centreon/www/front_src/src/BreadcrumbTrail/index.tsx
  centreon/www/front_src/src/BreadcrumbTrail/translatedLabels.tsx
  centreon/www/front_src/src/components/ReactRouter/index.tsx
Labels: area/ui

#5615 enh(UI): Improve copy paste breadcrumb on React pages (#5432)
  centreon/cypress/downloads/downloads.html
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- copies the breadcrumb when the breadcrumd is being hovered and an icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- displays the breadcrumb trail with an additional label.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx/BreadcrumbTrail -- displays the breadcrumb trail.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/BreadcrumbTrail/BreadcrumbTrail.cypress.spec.tsx
  centreon/www/front_src/src/BreadcrumbTrail/index.tsx
  centreon/www/front_src/src/BreadcrumbTrail/translatedLabels.tsx
  centreon/www/front_src/src/components/ReactRouter/index.tsx
Labels: backport

#5604 fix (authentication): fix SAML redirection
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
Labels: area/backend

#5610 fix(router): Correctly set host and scheme for router call in legacy
  centreon/src/Core/Infrastructure/Common/Api/Router.php
Labels: area/backend

#5595 fix(composer) : packages reference fixed
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
Labels: bug, area/backend

#5596 fix(composer) : packages reference fixed
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-open-tickets/composer.json
  centreon/composer.json
Labels: bug, area/backend

#5597 fix(composer) : packages reference fixed
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-open-tickets/composer.json
  centreon/composer.json
Labels: bug, area/backend

#5612 fix(composer) : packages reference fixed
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: area/backend

#5468 fix(status-chart): remove limit on status calculation, and group results
  centreon/src/Core/Host/Infrastructure/Repository/DbReadRealTimeHostRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend, backport

#5619 Fix([Cloud Notification]):Checkbox not reflects changes correctly (#5526) [release-24.11-next]
  centreon/packages/ui/src/Form/Form.tsx
Labels: area/ui, backport

#5618 fix(router): Correctly set host and scheme for router call in legacy
  centreon/src/Core/Infrastructure/Common/Api/Router.php
Labels: backport

#5628 fix (ACL): fix require path (#4729)
  centreon/www/class/centreonACL.class.php
  centreon/www/include/common/sqlCommonFunction.php
Labels: area/backend

#5617 fix (apiv1): fix CSV parsing
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#5631 fix(widgets): fix query for Live Top 10 Memory usage (#5532)
  centreon/www/widgets/live-top10-memory-usage/index.php
Labels: backport

#5529 fix(widgets): fix query for Live Top 10 CPU usage
  centreon/www/widgets/live-top10-cpu-usage/index.php
Labels: area/backend

#5640 fix(BAM): The BA tree widget is not displaying its content.
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batree/src/index.tsx
Labels: area/ui

#5646 fix(doc): update version in centreon-web api documentation
  centreon/doc/API/centreon-api.yaml
Labels: area/backend

#5534 fix(widgets): fix query for create hostgroups-monitoring
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend

#5533 fix(widgets): fix query for export hostgroups-monitoring
  centreon/www/widgets/hostgroup-monitoring/src/export.php
Labels: area/backend

#5494 fix: reset array keys in common-Func (#5449)
  centreon/www/include/common/common-Func.php
Labels: backport

#5425 fix(api-token): fix expiration date updates on each call for manual token
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/TokenAPIAuthenticatorTest.php
Labels: backport

#5491 fix(ui): remove theme field from user account form (#5484)
  centreon/www/include/Administration/myAccount/DB-Func.php
Labels: backport

#5647 fix(widgets): fix query for Live Top 10 CPU usage (#5529)
  centreon/www/widgets/live-top10-cpu-usage/index.php
Labels: backport

#5620 enh(composer) : packages reference fixed and review of the structure
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: enhancement, area/backend

#5430 fix(change logs): map new fields names on legacy fields form names
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: backport

#5676 enh(ui): forwardRef in EllipsisTypography
  centreon/packages/ui/src/Typography/EllipsisTypography.tsx
Labels: area/ui

#5369 fix(api): fix returned value for is_notifications_enabled on resources
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
Labels: backport

#5452 fix(cron): fix misdirected log when calling cron outdated-token (#5416)
  centreon/cron/outdated-token-removal.php
Labels: backport

#5588 enh(UI): Adapt bulk endpoints
  centreon/www/front_src/src/CloudNotificationsConfiguration/Actions/api/useDeleteRequest.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Panel/specs/PanelEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/useDeleteRequest.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
Labels: area/ui

#5652 fix (authentication): fix SAML redirection (#5604)
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
Labels: area/backend

#5659 fix (apiv1): fix CSV parsing (#5617)
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#5665 fix(widgets): fix query for create hostgroups-monitoring (#5534)
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: backport

#5593 [E2E] Rewrite SpecialCharactersInContact.feature
  centreon/behat.yml
  centreon/features/SpecialCharactersInContact.feature
  centreon/features/bootstrap/SpecialCharactersInContactContext.php
  centreon/tests/e2e/features/Contacts/04-non-admin-contact-creation/index.ts
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact.feature
  centreon/tests/e2e/features/Contacts/05-special-characters-in-contact/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
Labels: area/test

#5568 fix(acl) : fix missing acl columns for 24.10.1
  centreon/www/install/php/Update-24.10.1.php
Labels: bug, area/backend

#5611 Update cypress with enhancements
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
  centreon/tests/e2e/features/Agent-configuration/03-agent-configuration-deletion/index.ts
  centreon/tests/e2e/features/Agent-configuration/04-agent-configuration-update/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
Labels: area/test

#5569 fix(Custom View): fix edit mode in costum view
  centreon/www/include/home/customViews/index.ihtml
  centreon/www/include/home/customViews/index.php
Labels: area/backend

#5603 enh(SQL): enhance sql redo sql query
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/www/include/common/sqlCommonFunction.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#5696 fix(test): fix component tests on release branch
  centreon/www/front_src/src/VaultConfiguration/Form/Form.tsx
Labels: area/ui

#5658 fix (apiv1): fix CSV parsing (#5617)
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#5699 fix(ui): add to packages html-react-parser
  centreon/packages/ui/package.json
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
  centreon/packages/ui/src/utils/sanitizedHTML.ts
  centreon/pnpm-lock.yaml
Labels: area/ui

#5601 enh(UI): Enhancements on Agent Configurations
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays a welcome label when the listing is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- discards the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resolves the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/package.json
  centreon/packages/ui/src/Dialog/UnsavedChanges/index.tsx
  centreon/packages/ui/src/Dialog/UnsavedChanges/translatedLabels.ts
  centreon/packages/ui/src/Form/Inputs/Switch.tsx
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
  centreon/tests/e2e/features/Agent-configuration/03-agent-configuration-deletion/index.ts
  centreon/tests/e2e/features/Agent-configuration/04-agent-configuration-update/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/AddButton.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Columns/useColumns.ts
  centreon/www/front_src/src/AgentConfiguration/Page.tsx
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: area/ui

#5702 fix(Cloud): Mass change on Services make "Host" mandatory
  centreon/www/include/configuration/configObject/service/formService.php
Labels: area/backend

#5598 fix(composer) : packages reference fixed
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-open-tickets/composer.json
  centreon/composer.json
Labels: bug, area/backend

#5380 enh(api): change batch endpoints return status to 200
  centreon/doc/API/latest/Cloud/Administration/ResourceAccessManagement/DeleteRules.yaml
  centreon/doc/API/latest/Cloud/Configuration/Notification/DeleteNotifications.yaml
  centreon/doc/API/latest/Common/Response/MultiStatus.yaml
  centreon/src/Core/Notification/Infrastructure/API/DeleteNotifications/DeleteNotificationsPresenter.php
  centreon/src/Core/ResourceAccess/Infrastructure/API/DeleteRules/DeleteRulesPresenter.php
  centreon/tests/rest_api/collections/configuration/Notifications.postman_collection.json
Labels: area/backend

#5693 [E2E] Rewrite ShowDisabledHostsServices.feature
  centreon/behat.yml
  centreon/features/ShowDisabledHostsServices.feature
  centreon/features/bootstrap/ShowDisabledHostsServicesContext.php
  centreon/tests/e2e/features/Hosts/06-show-disabled-hosts-services.feature
  centreon/tests/e2e/features/Hosts/06-show-disabled-hosts-services/index.ts
Labels: area/test

#5641 [E2E] Rewrite LdapConfiguration.feature
  centreon/behat.yml
  centreon/features/LdapConfiguration.feature
  centreon/features/bootstrap/LdapConfigurationContext.php
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration.feature
  centreon/tests/e2e/features/Ldaps/01-ldap-configuration/index.ts
  centreon/tests/e2e/features/Ldaps/commands.ts
  centreon/tests/e2e/fixtures/ldaps/ldap.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5711 fix(composer) : packages reference fixed
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
Labels: area/backend

#5655 chore(E2E) :Adding E2E tests to evaluate the status chart behavior with more than 20 hosts
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration.feature
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
Labels: area/test

#5616 enh(composer) : packages reference fixed and review of the structure
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: enhancement, area/backend

#5587 feat(ci): automate ticket creation on scheduled build failure
  .github/actions/create-jira-ticket/action.yml
  .github/actions/create-jira-ticket/nightly-ticket-template.json
  .github/actions/create-jira-ticket/veracode-ticket-template.json
  .github/actions/veracode-create-jira-ticket/action.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/newman.yml
  .github/workflows/ui-beta.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: ci

#5692 [E2E] Rewrite VirtualMetricHandle.feature
  centreon/behat.yml
  centreon/features/VirtualMetricHandle.feature
  centreon/features/bootstrap/VirtualMetricHandleContext.php
  centreon/tests/e2e/features/Services-configuration/09-virtual-metric-handle.feature
  centreon/tests/e2e/features/Services-configuration/09-virtual-metric-handle/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/virtual-metric.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5630 enh(UI): Fix logarithmic scale on bar chart + small enhancements on condensed status grid
  centreon/cypress/downloads/downloads.html
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- With resources -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- With resources -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- With resources -- displays the tooltip when the problem card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- With resources -- displays the tooltip when the success card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Condensed view -- Without resources -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/Link to resource status page -- displays a see more tile when not all resources are displayed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- With Resources -- displays host informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- With Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by host -- Without Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a critical service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a service in downtime tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when a warning service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an acknowledged service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an ok service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays service informations when an unknown service tile is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- With Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx/View by service -- Without Resources -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Impact-critical displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Impact-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Ratio-critical displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Ratio-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- Worst Status-ok displays business activity informations when the mouse is over a tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Business activities -- displays tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the problem card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- Business activities -- displays the tooltip when the success card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays status tiles.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the pending card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the problem card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Condensed view -- KPIs -- displays the tooltip when the success card is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Indicators -- displays boolean rule informations when the mouse is over boolean rule tile.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx/Indicators -- displays tiles.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a stacked bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/src/Graph/BarChart/BarGroup.tsx
  centreon/packages/ui/src/Graph/BarChart/BarStack.tsx
  centreon/packages/ui/src/Graph/BarChart/ResponsiveBarChart.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/StatusCard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/StatusGridCondensed.styles.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx
Labels: area/ui

#5701 enh(ACC VMWare ): Parameters UI enhancements & fix unsaved changes popup
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- clears filters and the search bar, and sends a listing request with empty search parameter when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- displays the advanced filters component when the corresponding icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Filters -- updates the search bar with the value from the filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- deletes an ACC when the Delete button is clicked and the confirmation button is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Listing -- displays the first page of the ACC listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends a Post request when the Modal is in Creation Mode and the Create Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- API requests -- sends an Update request when the Modal is in Edition Mode and the Update Button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Ask Before quit popup -- displays a modal when the form is updated and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Ask Before quit popup -- displays a modal when the form is updated with errors and the cancel button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that at least one poller is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that name length must be between 3 and 50 characters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that port field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be a valid integer.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that the port should be between 0 and 65535.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter URL field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name field is required.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter name must be unique for its own ACC.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter password field is not required in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter password field is required in Creation Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter username is not required Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- Form validation -- validates that vCenter username is required in Creation Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- adds a new parameter group when Add vCenter ESX button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- disables the update button when no change has been made to the modal form.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- displays form fields with the selected ACC values when the Modal is opened in Edition Mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Modal -- enables the create button when all mandatory fields are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- displays listing, filters and action buttons.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Creation Mode when Add button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/Additional Connctor Configuration -- Page -- opens the modal in Edition Mode when a row of the listing is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creation date column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Creator column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Last update column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Name column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Type column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/column sorting --  executes a listing request when the Updated by column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/invalide_url_2.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_0.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_1.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AdditionalConnectorConfiguration/Specs/ACC.cypress.spec.tsx/valide_url_2.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/CloseModalConfirmation.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/Form.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Parameter.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Port.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/useParametersStyles.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Page.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/AddButton.tsx
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui

#5547 fix(Discovery): Hosts discovery can't export/reload centengine via automatic analysis (#5531) [dev-24.04.x]
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
Labels: area/backend, backport

#5548 fix(Discovery): Hosts discovery can't export/reload centengine via automatic analysis (#5531) [dev-23.10.x]
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
Labels: area/backend, backport

#5546 fix(Discovery): Hosts discovery can't export/reload centengine via automatic analysis (#5531) [dev-24.10.x]
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadConfiguration.php
  centreon/tests/e2e/features/Poller-configuration/01-poller-configuration/index.ts
Labels: area/backend, backport

#5719 feat(tests): Add Cypress test for Agent Configuration
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/tests/e2e/fixtures/agents-configuration/agent-config.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5761 enh(ui): Add Icons and fix linting
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Dashboard/Grid.tsx
  centreon/packages/ui/src/Dashboard/Layout.tsx
  centreon/packages/ui/src/Form/Inputs/Autocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/Radio.tsx
  centreon/packages/ui/src/Form/Inputs/Text.tsx
  centreon/packages/ui/src/Graph/BarChart/BarChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/packages/ui/src/Graph/Chart/InteractiveComponents/index.tsx
  centreon/packages/ui/src/Graph/Chart/index.tsx
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/packages/ui/src/Icon/AcknowledgementIcon.tsx
  centreon/packages/ui/src/Icon/BusinessActivityIcon.tsx
  centreon/packages/ui/src/Icon/ContainerIcon.tsx
  centreon/packages/ui/src/Icon/DowntimeIcon.tsx
  centreon/packages/ui/src/Icon/HostGroupIcon.tsx
  centreon/packages/ui/src/Icon/MetaServiceIcon.tsx
  centreon/packages/ui/src/Icon/ServiceGroupIcon.tsx
  centreon/packages/ui/src/Icon/index.ts
  centreon/packages/ui/src/Listing/index.tsx
  centreon/packages/ui/src/Typography/EllipsisTypography.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.styles.ts
Labels: area/ui

#5752 fix(symfony) : symfony security-http fixed
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
Labels: area/backend

#5736 fix(clapi): rename method to avoid conflict with php extension
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#5771 Fix(UI): Fix frontend-components input
  .github/workflows/web.yml
Labels: ci

#5773 fix(clapi): rename method to avoid conflict with php extension (#5736)
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend, backport

#5762 fix(packaging): Fix broken syntax in sudoers file
  centreon/packaging/src/sudoersCentreon
Labels: backport

#5772 fix(clapi): rename method to avoid conflict with php extension (#5736)
  centreon/www/api/class/centreon_clapi.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend, backport

#5691 fix(cloud): remove host-group requirement in mass changes
  centreon/www/include/configuration/configObject/host/formHost.php
Labels: area/backend

#5720 enh(logs): insert change logs for /configuration/hosts/severities
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/HostSeverity/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbWriteHostSeverityActionLogRepository.php
Labels: area/backend

#5727 enh(logs): insert change logs for /configuration/services/severities
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/ServiceSeverity/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbWriteServiceSeverityActionLogRepository.php
Labels: area/backend

#5779 Automated E2E - Administration Logs on changes
  centreon/tests/e2e/features/Logs/01-time-period-changes-log.feature
  centreon/tests/e2e/features/Logs/01-time-period-changes-log/index.ts
  centreon/tests/e2e/features/Logs/commands.ts
  centreon/tests/e2e/fixtures/time-periods/time-period.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#5755 fix : problems with closeQuery in fetchColumn of CentreonDB fixed
  centreon/www/class/centreonDB.class.php
Labels: area/backend, backport

#5754 fix : problems with closeQuery in fetchColumn of CentreonDB fixed
  centreon/www/class/centreonDB.class.php
Labels: area/backend, backport

#5757 fix : problems with closeQuery in fetchColumn of CentreonDB fixed
  centreon/www/class/centreonDB.class.php
Labels: area/backend, backport

#5724 [E2E backport] Rewrite HostGroupConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/HostGroupConfiguration.feature
  centreon/features/bootstrap/HostGroupConfigurationContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration.feature
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/HostGroups/commands.ts
  centreon/tests/e2e/fixtures/hostGroups/hostGroup.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5650 fix(widgets): fix query for Live Top 10 CPU usage (#5529)
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/index.php
Labels: backport

#5651 fix(widgets): fix query for Live Top 10 CPU usage (#5529)
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/index.php
Labels: backport

#5633 fix(widgets): fix query for Live Top 10 Memory usage (#5532)
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
Labels: backport

#5672 fix(widgets): fix query for export hostgroups-monitoring (#5533)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
Labels: backport

#5673 fix(widgets): fix query for export hostgroups-monitoring (#5533)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
Labels: backport

#5674 fix(widgets): fix query for export hostgroups-monitoring (#5533)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
Labels: backport

#5669 fix(widgets): fix query for create hostgroups-monitoring (#5534)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: backport

#5667 fix(widgets): fix query for create hostgroups-monitoring (#5534)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: backport

#5747 fix(vmware): Correctly copy centreon_vmware conf file on Central when export
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: area/backend

#5634 fix(cron): fix misdirected log when calling cron outdated-token (#5416)
  centreon/cron/outdated-token-removal.php
Labels: backport

#5796 Automated E2E - Administration Logs on changes
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log.feature
  centreon/tests/e2e/features/Logs/02-hosts-severities-changes-log/index.ts
  centreon/tests/e2e/features/Logs/commands.ts
  centreon/tests/e2e/fixtures/host-categories/severity.json
Labels: area/test

#5776 [E2E backport] Rewrite ServiceConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/ServiceConfiguration.feature
  centreon/features/bootstrap/ServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/03-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5730 [E2E backport] Rewrite HostConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/HostConfiguration.feature
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/tests/e2e/features/Hosts/01-host-configuration.feature
  centreon/tests/e2e/features/Hosts/01-host-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5774 [E2E backport] Rewrite HostCategoryConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/HostCategoryConfiguration.feature
  centreon/features/bootstrap/HostCategoryConfigurationContext.php
  centreon/tests/e2e/features/Hosts/02-host-category-configuration.feature
  centreon/tests/e2e/features/Hosts/02-host-category-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/fixtures/host-categories/category.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5763 [E2E backport] Rewrite ConfigurationWarnings.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/ConfigurationWarnings.feature
  centreon/features/bootstrap/ConfigurationWarningsContext.php
  centreon/tests/e2e/features/Services-configuration/02-configuration-warnings.feature
  centreon/tests/e2e/features/Services-configuration/02-configuration-warnings/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5810 Fix(UI): Fix incorrect status types
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/useStatusGridCondensed.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
  centreon/www/widgets/src/utils.ts
Labels: backport

#5806 [E2E backport] Rewrite ContactConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/ContactConfiguration.feature
  centreon/features/bootstrap/ContactConfigurationContext.php
  centreon/tests/e2e/features/Contacts/01-contact-configuration.feature
  centreon/tests/e2e/features/Contacts/01-contact-configuration/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
  centreon/tests/e2e/fixtures/users/contact.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5811 [E2E backport] Rewrite TimePeriodConfiguration.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/TimePeriodConfiguration.feature
  centreon/features/bootstrap/TimePeriodConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/02-configuration-warnings/index.ts
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration.feature
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration/index.ts
  centreon/tests/e2e/features/Time-Period/common.ts
Labels: area/test, backport

#5622 enh(composer) : packages reference fixed and review of the structure
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: enhancement, area/backend

#5624 enh(composer) : packages reference fixed and review of the structure
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: enhancement, area/backend

#5790 fix(Downtimes/Widgets): fix wrong service groups field value
  centreon/www/class/centreonServicegroups.class.php
Labels: area/backend

#5623 enh(composer) : packages reference fixed and review of the structure
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon/composer.json
  centreon/composer.lock
Labels: enhancement, area/backend

#5632 fix(widgets): fix query for Live Top 10 Memory usage (#5532)
  centreon/www/widgets/live-top10-memory-usage/index.php
Labels: backport

#5666 fix(widgets): fix query for create hostgroups-monitoring (#5534)
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: backport

#5553 fix(Authentication): Unable to login if 2 mail addresses on LDAP
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend

#5734 enh(ci): install gorgone and collect in web dependencies container
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  .github/workflows/awie.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/get-environment.yml
  .github/workflows/web.yml
Labels: skip-workflow-docker-web-dependencies

#5571 fix(broker): fix lua parameters mixed up (#5511)
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: backport

#5749 fix(ci): fix elements about changes-trigger-checks and nightly
  .github/actions/changes-trigger-checks/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/create-nightly-incident-ticket.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/newman.yml
  .github/workflows/ui-beta.yml
  .github/workflows/web.yml
Labels: ci

#5816 fix(Downtimes/Widgets): fix wrong service groups field value (#5790)
  centreon/www/class/centreonServicegroups.class.php
Labels: backport

#5648 fix(widgets): fix query for Live Top 10 CPU usage (#5529)
  centreon/www/widgets/live-top10-cpu-usage/index.php
Labels: backport

#5821 fix(resource status): add possibility to save custom filters order
  centreon/www/front_src/src/Resources/Filter/Edit/index.tsx
Labels: area/ui

#5822 [E2E backport] Rewrite HostTemplateBasicsOperations.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/HostTemplateBasicsOperations.feature
  centreon/features/bootstrap/HostTemplateBasicsOperationsContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/Hosts/03-host-template-basics-operations.feature
  centreon/tests/e2e/features/Hosts/03-host-template-basics-operations/index.ts
  centreon/tests/e2e/fixtures/host-groups/host-group.json
  centreon/tests/e2e/fixtures/host-templates/host-template.json
Labels: area/test, backport

#5825 fix(symfony) : symfony security-http fixed
  centreon/composer.lock
Labels: bug, area/backend

#5700 fix (OpenID): fix random OpenID disconnection (#4068)
  centreon/cron/outdated-token-removal.php
  centreon/src/Core/Security/Authentication/Domain/Model/AuthenticationTokens.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Security/Domain/Authentication/Interfaces/AuthenticationRepositoryInterface.php
  centreon/src/Security/Infrastructure/Repository/AuthenticationRepository.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/SessionAPIAuthenticatorTest.php
Labels: area/backend, backport

#5654 fix (authentication): fix SAML redirection (#5604)
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
Labels: area/backend

#5656 fix (authentication): fix SAML redirection (#5604)
  centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/SAML/CallbackController.php
Labels: area/backend

#5538 fix(configuration): improve field label & tooltip in Broker configuration
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.9.php
Labels: backport

#5833 Automated E2E - Administration Logs
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/04-services-categories-changes-log/index.ts
  centreon/tests/e2e/fixtures/services/category.json
Labels: area/test

#5844 [E2E backport] Rewrite ModifyDefaultPageConnection.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/ModifyDefaultPageConnection.feature
  centreon/features/bootstrap/ModifyDefaultPageConnectionContext.php
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection.feature
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection/index.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/non-admin-with-access-to-allmodules.json
  centreon/tests/e2e/fixtures/users/user-with-access-to-allmodules.json
Labels: area/test, backport

#5780 fix(Dashboards): Error when selecting a service with special characters
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/utils.ts
Labels: area/ui

#5760 fix(conf) do no accept duplicate service name for a same host
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend

#5723 fix(PAC): json export file now has empty string value instead of null for ca_certificate property
  centreon/www/class/config-generate/AgentConfiguration.php
Labels: area/backend

#5562 enh(conf): use timeperiod endpoints in UI conf forms (create/update/delete)
  centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
  centreon/www/include/configuration/configObject/timeperiod/formTimeperiod.php
  centreon/www/include/configuration/configObject/timeperiod/timeperiod.php
Labels: area/backend

#5392 enh(Change Logs): Insert change logs for /configuration/hosts/templates endpoints (#5356) [dev-24.10.x]
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostTemplate/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateActionLogRepository.php
Labels: area/backend, backport

#5512 fix(Sevice): rework service repository method 'existsByAccessGroups' (#5479) [dev-24.10.x]
  centreon/src/Core/Service/Application/UseCase/PartialUpdateService/PartialUpdateServiceValidation.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
Labels: area/backend, backport

#5817 fix(dashboards): Issue with the Save button activation in the group m…
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
Labels: area/ui

#5874 fix(Dashboards): Error when selecting a service with special characters (#5780) [dev-24.04.x]
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui, backport

#5756 fix : problems with closeQuery in fetchColumn of CentreonDB fixed
  centreon/www/class/centreonDB.class.php
Labels: area/backend, backport

#5753 fix(symfony) : symfony security-http fixed
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon/composer.lock
Labels: area/backend

#5873 fix(Dashboards): Error when selecting a service with special characters (#5780) [dev-24.10.x]
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui, backport

#5858 [E2E backport] Rewrite NonAdminContactCreation.feature on dev-24.04.x
  centreon/behat.yml
  centreon/features/NonAdminContactCreation.feature
  centreon/features/bootstrap/NonAdminContactCreationContext.php
  centreon/tests/e2e/features/Contacts/04-non-admin-contact-creation.feature
  centreon/tests/e2e/features/Contacts/04-non-admin-contact-creation/index.ts
  centreon/tests/e2e/features/Contacts/commands.ts
Labels: area/test, backport

#5725 [E2E Backport] Rewrite HostGroupConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/HostGroupConfiguration.feature
  centreon/features/bootstrap/HostGroupConfigurationContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration.feature
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/HostGroups/commands.ts
  centreon/tests/e2e/fixtures/hostGroups/hostGroup.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5848 [E2E backport] Rewrite ModifyDefaultPageConnection.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/ModifyDefaultPageConnection.feature
  centreon/features/bootstrap/ModifyDefaultPageConnectionContext.php
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection.feature
  centreon/tests/e2e/features/Administration/01-modify-default-page-connection/index.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/non-admin-with-access-to-allmodules.json
  centreon/tests/e2e/fixtures/users/user-with-access-to-allmodules.json
Labels: area/test, backport

#5777 [E2E backport] Rewrite ServiceConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/ServiceConfiguration.feature
  centreon/features/bootstrap/ServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/03-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5768 [E2E backport] Rewrite ServiceCategoryConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/ServiceCategoryConfiguration.feature
  centreon/features/bootstrap/ServiceCategoryConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration.feature
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration/index.ts
Labels: area/test, backport

#5586 fix: update smarty version
  centreon/composer.json
  centreon/composer.lock
Labels: backport

#5731 [E2E backport] Rewrite HostConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/HostConfiguration.feature
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/tests/e2e/features/Hosts/01-host-configuration.feature
  centreon/tests/e2e/features/Hosts/01-host-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5792 fix (clapi): suppress the status response line when the CLAPI command is called from the APIv1
  centreon/www/class/centreon-clapi/centreonAPI.class.php
  centreon/www/include/common/csvFunctions.php
Labels: area/backend

#5830 fix(action logs): correctly set the field name column while displaying log details
  centreon/www/class/centreonLogAction.class.php
Labels: area/backend

#5812 [E2E backport] Rewrite TimePeriodConfiguration.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/TimePeriodConfiguration.feature
  centreon/features/bootstrap/TimePeriodConfigurationContext.php
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration.feature
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration/index.ts
  centreon/tests/e2e/features/Time-Period/common.ts
Labels: area/test, backport

#5764 [E2E backport] Rewrite ConfigurationWarnings.feature on dev-24.10.x
  centreon/behat.yml
  centreon/features/ConfigurationWarnings.feature
  centreon/features/bootstrap/ConfigurationWarningsContext.php
  centreon/tests/e2e/features/Services-configuration/02-configuration-warnings.feature
  centreon/tests/e2e/features/Services-configuration/02-configuration-warnings/index.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport

#5703 enh(SQL): enhance sql redo sql query (#5603)
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/www/include/common/sqlCommonFunction.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend
