Repository centreon/centreon, pull requests merged in 2024-09, with the labels that each got.

#4955 chore(deps): update test lib dependencies
  .github/workflows/behat-test.yml
  centreon/composer.lock
  centreon/tests/e2e/commons.ts
  centreon/tests/e2e/features/Dashboards/13-dashboard-all-widgets/index.ts
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
Labels: area/backend

#4936 enh(UI): Clean up feature flags
  centreon/config/features.json
  centreon/packages/ui-context/src/types.ts
  centreon/src/Core/Dashboard/Infrastructure/API/AddDashboard/AddDashboardRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/DeleteContactDashboardShare/DeleteContactDashboardShareRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/DeleteContactGroupDashboardShare/DeleteContactGroupDashboardShareRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/DeleteDashboard/DeleteDashboardRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboard/FindDashboardRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboards/FindDashboardsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetrics/FindPerformanceMetricsRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataRoute.yaml
  centreon/src/Core/Dashboard/Infrastructure/API/PartialUpdateDashboard/PartialUpdateDashboardRoute.yaml
  centreon/src/Core/Resources/Infrastructure/API/FindResourcesByParent/FindResourcesByParentRoute.yaml
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/tests/rest_api/collections/platform/Platform_Features.postman_collection.json
  centreon/www/front_src/src/Resources/Actions/index.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/testUtils.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.09.0.php
Labels: area/ui

#4951 feat(dashboard): add closing ticket feature
  centreon-open-tickets/src/CentreonOpenTickets/Resources/Infrastructure/Repository/OpenTicketExtraDataProvider.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/closeTicket/action.php
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/OpenTicket/Modal.tsx
Labels: area/backend

#4945 enh(UI): Handle close ticket on resources table
  centreon/cypress/fixtures/Widgets/ResourcesTable/resourcesStatus.json
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/Open tickets -- displays a confirmation modal when a close ticket button is clicked for a host.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/Open tickets -- displays a confirmation modal when a close ticket button is clicked for a service.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/Open tickets -- displays tickets actions when openticket switch is enabled and a rule is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/Open tickets -- displays tickets id,subject and open time when openticket switch is enabled, a rule is selected and display resources property is set to withTicket.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- displays acknowledge informations when the corresponding icon is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- displays downtime informations when the corresponding icon is hovered.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- displays listing with columns from widget selected columns properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with an status from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with downtime state defined in the widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with hostgroup_names filter defined in widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with limit from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with resources type filter defined in widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- executes a listing request with sort_by param from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- retrieves resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- verify that acknowledge resources row are correctly displayed with the right background color.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by all -- verify that downtime resources row are correctly displayed with the right background color.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by host -- displays listing with columns from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by host -- executes a listing request with limit from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by host -- retrieves resources.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by service -- displays listing with columns from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by service -- executes a listing request with limit from widget properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx/View by service -- retrieves resources.snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Listing/index.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/CloseTicket/CloseTicket.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/CloseTicket/Modal.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/Columns.styles.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/Icons/CloseTicket.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/OpenTicket/Modal.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/useColumns.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/atom.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
Labels: area/ui

#4954 fix(admin) display actual meta_service name
  centreon/www/include/Administration/performance/viewData.php
Labels: area/backend

#4986 enh(UI): remove colon blinking and fix days count
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/DatePicker/useDatePicker.ts
  centreon/www/widgets/src/centreon-widget-clock/src/Clock.tsx
  centreon/www/widgets/src/centreon-widget-clock/src/Timer.tsx
Labels: area/ui

#5005 feat(test): Fix token test script
  centreon/tests/rest_api/collections/authentication/01-Tokens.postman_collection.json
Labels: area/test

#4897 chore(E2E): Implement backup e2e test
  centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
  centreon/tests/e2e/features/Backup-configuration/01-backup-properties/index.ts
  centreon/tests/e2e/features/Backup-configuration/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#4937 fix(macros): Correctly set all host macros in on_demand_macro_host.infile
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonLog.class.php
  centreon/www/class/config-generate-remote/Abstracts/AbstractHost.php
  centreon/www/class/config-generate-remote/Relations/MacroHost.php
Labels: area/backend

#4972 feat(export): manager VMWare V6 config export
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Factory/AccFactory.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Repository/ReadAccRepositoryInterface.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Validation/VmWareV6DataValidator.php
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VSphereServer.php
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareConfig.php
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/DbReadAccRepository.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/Vault/VmWareV6ReadVaultAccRepository.php
  centreon/src/Core/AdditionalConnectorConfiguration/Infrastructure/Repository/Vault/VmWareV6WriteVaultAccRepository.php
  centreon/src/Core/Security/Vault/Application/UseCase/MigrateAllCredentials/Migrator/VmWareV6CredentialMigrator.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Application/UseCase/AddAcc/ValidatorTest.php
  centreon/tests/php/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6ParametersTest.php
  centreon/www/class/config-generate-remote/Generate.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend

#5032 feat(test): Add Export Conf Monitoring Servers script
  centreon/tests/rest_api/collections/configuration/Export_Conf_Monitoring_Servers.postman_collection.json
Labels: area/test

#4975 fix(Resource Status): Anomaly detection services
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/front_src/src/Resources/Details/tabs/Services/index.tsx
Labels: area/ui, area/backend

#4994 fix(UI): Change API endpoints on ACC
  centreon/doc/API/centreon-api.yaml
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/endpoints.ts
Labels: area/ui

#5051 Fix(UI): Remove id from ACC update
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/useModal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/api/adapters.ts
Labels: area/ui

#5050 fix(API): Creation of resources (hosts and services) are not visible by a non administrator
  centreon/src/Core/Host/Application/Repository/WriteRealTimeHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteRealTimeHostRepository.php
  centreon/src/Core/Service/Application/Repository/WriteRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteRealTimeServiceRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/Service/Application/UseCase/AddService/AddServiceTest.php
Labels: area/backend

#5067 fix(API): Creation of resources (hosts and services) are not visible by a non administrator (#5050) [release-24.09-next]
  centreon/src/Core/Host/Application/Repository/WriteRealTimeHostRepositoryInterface.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteRealTimeHostRepository.php
  centreon/src/Core/Service/Application/Repository/WriteRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/AddService/AddService.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteRealTimeServiceRepository.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
  centreon/tests/php/Core/Service/Application/UseCase/AddService/AddServiceTest.php
Labels: area/backend, backport

#4941 fix (translation): fix upper case in all translations for Graph/logs periods
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/eventLogs/viewLog.php
  centreon/www/include/reporting/dashboard/common-Func.php
  centreon/www/include/views/graphTemplates/formGraphTemplate.php
  centreon/www/include/views/graphs/graph-split.php
  centreon/www/include/views/graphs/graphs.php
Labels: area/backend

#4991 fix (monitoring): fix SQL query
  centreon/www/class/centreonMonitoring.class.php
  centreon/www/class/centreonXMLBGRequest.class.php
  centreon/www/include/monitoring/status/Services/xml/serviceGridXML.php
  centreon/www/include/monitoring/status/Services/xml/serviceSummaryXML.php
  centreon/www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
Labels: area/backend

#4915 feat(widgets): Implement web page widget
  centreon/cypress/fixtures/Dashboards/Dashboard/detailsWithWebPageWidget.json
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Dashboards/18-web-page-widget-configuration.feature
  centreon/tests/e2e/features/Dashboards/18-web-page-widget-configuration/index.ts
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwoWebPageWidget.json
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithWebPageWidget.json
  centreon/www/front_src/public/mockServiceWorker.js
  centreon/www/front_src/src/Dashboards/DashboardsPage.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TextField.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetMessage/WidgetMessage.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetMessage/WidgetMessage.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetSelection.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/widgetProperties.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/useRefreshWebPageWidget.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/index.tsx
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.0.php
  centreon/www/widgets/src/centreon-widget-resourcestable/src/models.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-webpage/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-webpage/properties.json
  centreon/www/widgets/src/centreon-widget-webpage/src/Preview.tsx
  centreon/www/widgets/src/centreon-widget-webpage/src/WebPage.tsx
  centreon/www/widgets/src/centreon-widget-webpage/src/Webpage.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-webpage/src/index.tsx
  centreon/www/widgets/src/centreon-widget-webpage/src/models.ts
  centreon/www/widgets/src/centreon-widget-webpage/src/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-webpage/src/useWebPage.styles.ts
Labels: area/ui, area/backend

#5096 fix(dashboard): Error encountered when selecting a custom time period on the Graph Widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.tsx
Labels: area/ui

#5030 feat(UI): Add vault configuration page
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- displays a modal when the vault configuration is valid and the button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- displays an error when the URL field is not correctly formatted.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- displays an error when the port field is greater than 65535.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- displays the retrieved Vault configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- resets the form when the configuration has changed and the reset button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- sanitizes URL and port field when URL field receives an URL and a port.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- sanitizes the URL when the field receives an URL that starts with a protocol.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx/Vault configuration -- sends the updated Vault configuration.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- copies the command to the clipboard when the button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- displays bash code when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- displays json code when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- displays php code when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- displays the highlighted code in dark mode when the theme is changed.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- displays yaml code when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/components/CopyCommand/CopyCommand.cypress.spec.tsx/CopyCommand -- does not display the copy button when the corresponding prop is not passed.snap.png
  centreon/packages/ui/package.json
  centreon/packages/ui/src/Form/Inputs/Text.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/Form/storiesData.tsx-E
  centreon/packages/ui/src/components/CopyCommand/CopyCommand.cypress.spec.tsx
  centreon/packages/ui/src/components/CopyCommand/CopyCommand.stories.tsx
  centreon/packages/ui/src/components/CopyCommand/CopyCommand.styles.tsx
  centreon/packages/ui/src/components/CopyCommand/CopyCommand.tsx
  centreon/packages/ui/src/components/CopyCommand/translatedLabels.ts
  centreon/packages/ui/src/components/index.ts
  centreon/pnpm-lock.yaml
  centreon/www/front_src/src/VaultConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/VaultConfiguration/Form/Form.tsx
  centreon/www/front_src/src/VaultConfiguration/Form/MigrationModal.tsx
  centreon/www/front_src/src/VaultConfiguration/Form/Skeletons.tsx
  centreon/www/front_src/src/VaultConfiguration/Form/useFormStyles.ts
  centreon/www/front_src/src/VaultConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/VaultConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/VaultConfiguration/VaultConfiguration.tsx
  centreon/www/front_src/src/VaultConfiguration/api/decoders.ts
  centreon/www/front_src/src/VaultConfiguration/api/endpoints.ts
  centreon/www/front_src/src/VaultConfiguration/atoms.ts
  centreon/www/front_src/src/VaultConfiguration/hooks/useGetVaultConfiguration.ts
  centreon/www/front_src/src/VaultConfiguration/hooks/useUpdateVaultConfiguration.ts
  centreon/www/front_src/src/VaultConfiguration/models.ts
  centreon/www/front_src/src/VaultConfiguration/translatedLabels.ts
  centreon/www/front_src/src/reactRoutes/index.ts
  centreon/www/front_src/src/reactRoutes/routeMap.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.09.0.php
  centreon/www/install/php/Update-24.10.0.php
Labels: area/ui

#5113 Fix(CI): Fix imports
  centreon/packages/ui/src/components/Form/index.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/Form.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useFormInitialValues.ts
Labels: area/ui

#5048 fix (open-ticket): fix sql request
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
Labels: area/backend

#5115 fix(API): Deployed services are not visible by a non-admin user
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServices.php
  centreon/tests/php/Core/Service/Application/UseCase/DeploySevices/DeployServicesTest.php
Labels: area/backend

#5049 fix(DSM): multiple SQL query
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/DB-Func.php
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/formSlot.php
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/slots.php
Labels: area/backend

#5119 fix(graph): dashboard invalid metric format fixed
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
Labels: area/backend

#5128 fix(API): Deployed services are not visible by a non-admin user (#5115) [release-24.09-next]
  centreon/src/Core/Service/Application/UseCase/DeployServices/DeployServices.php
  centreon/tests/php/Core/Service/Application/UseCase/DeploySevices/DeployServicesTest.php
Labels: area/backend, backport

#5101 fix(dashboard): Error encountered when selecting a custom time period on the Graph Widget
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration.feature
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.tsx
Labels: area/ui

#5141 fix(UI): fix ip address validation
  centreon/www/front_src/src/VaultConfiguration/Form/Form.tsx
  centreon/www/front_src/src/VaultConfiguration/Form/useValidationSchema.ts
Labels: area/ui

#5074 Fix(UI): Fix port type on ACC
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useValidationSchema.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Port.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
Labels: area/ui

#5140 fix (open-ticket): fix sql request (#5048)
  centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/submitTicket.php
Labels: backport

#5129 enh(ceip) add acc stats to ceip cron
  centreon/cron/centreon-send-stats.php
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#5163 fix (service): correction of ACLs when searching for the existence of a service
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
Labels: area/backend

#5033 enh(dashboads): enhancements for the open ticket widgets
  centreon-open-tickets/src/CentreonOpenTickets/Resources/Infrastructure/Repository/OpenTicketExtraDataProvider.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/closeTicket/action.php
  centreon/config/features.json
  centreon/cypress/fixtures/Widgets/ResourcesTable/resourcesStatus.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.cypress.spec.tsx/WidgetTextField -- displays the text field.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui-context/src/types.ts
  centreon/tests/rest_api/collections/platform/Platform_Features.postman_collection.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Autocomplete/ConnectedAutocomplete.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/WidgetProperties.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetInputs.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/front_src/src/federatedModules/models.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Actions/Actions.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Actions/DisplayType/DisplayType.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/CloseTicket/CloseTicket.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/OpenTicket/Modal.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/OpenTicket/OpenTicket.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/Tooltip/Tooltip.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/useColumns.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Listing.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useLoadResources.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
Labels: area/ui, area/backend

#5038 enh(poller) Handle vault in broker input/output broker config for wizard poller
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConnectionConfigurationService.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/RemoteConnectionConfigurationService.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
  centreon/src/CentreonRemote/ServiceProvider.php
  centreon/src/Core/Common/Infrastructure/FeatureFlags.php
Labels: area/backend

#5175 feat(Configuration): Add a "host_down_disable_service_checks" option
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
  centreon/tests/clapi_export/clapi-configuration.txt
  centreon/www/class/centreon-clapi/centreonEngineCfg.class.php
  centreon/www/class/centreon-config/centreonMainCfg.class.php
  centreon/www/class/config-generate-remote/Engine.php
  centreon/www/class/config-generate/engine.class.php
  centreon/www/include/configuration/configNagios/DB-Func.php
  centreon/www/include/configuration/configNagios/formNagios.ihtml
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/include/configuration/configNagios/help.php
  centreon/www/include/configuration/configServers/DB-Func.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-24.10.0.php
  centreon/www/install/var/baseconf/centreon-engine.sql
Labels: area/backend

#5188 fix(sql) fix update script to make it idempotent
  centreon/www/install/php/Update-24.07.0.php
Labels: area/backend

#5195 fix(Graph): PNG export gets 'Access denied' for non-admin user
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend

#5182 feat(test): Add ACC endpoint test
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
Labels: area/test

#5198 fix(Graph): PNG export gets 'Access denied' for non-admin user (#5195) [release-24.09-next]
  centreon/www/include/views/graphs/generateGraphs/generateImage.php
Labels: area/backend, backport

#5044 fix(command) set the right type according the context (cloud or not)
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/command/formCommand.ihtml
  centreon/www/include/configuration/configObject/command/formCommand.php
Labels: area/backend

#5201 fix(command) set the right type according the context (cloud or not)
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/command/formCommand.ihtml
  centreon/www/include/configuration/configObject/command/formCommand.php
Labels: backport

#5135 feat(Configuration): Add possibility to duplicate a locked command
  centreon/features/bootstrap/CommandConfigurationContext.php
  centreon/www/img/icons/content_copy.png
  centreon/www/img/icons/delete_new.png
  centreon/www/img/icons/visibility_off.png
  centreon/www/img/icons/visibility_on.png
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/command/command.php
  centreon/www/include/configuration/configObject/command/listCommand.ihtml
  centreon/www/include/configuration/configObject/command/listCommand.php
Labels: area/backend

#5209 enh(ACC): activate topology_show flag for ACC page
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-24.09.0.php
  centreon/www/install/php/Update-24.10.0.php
Labels: area/backend
