Repository centreon/centreon, pull requests merged in 2024-06, with the labels that each got.

#4205 Fix(UI): Fix pagination data
  centreon/tests/e2e/features/Dashboards/13-dashboard-all-widgets/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
Labels: area/ui

#4285 fix(RAM): Cannot duplicate rule (#4282)
  centreon/www/front_src/src/ResourceAccessManagement/Actions/api/adapters.ts
Labels: area/ui

#4179 feat(test): Add Authentication_Provider postman script
  centreon/tests/rest_api/collections/api-administration/Authentication_Provider.postman_collection.json
Labels: area/test

#4278 fix (acl): update access rights to monitoring APIs.
  centreon/src/Centreon/Application/Controller/DowntimeController.php
  centreon/src/Centreon/Application/Controller/Monitoring/TimelineController.php
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Monitoring/MonitoringService.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/RealTimeMonitoringServer/FindRealTimeMonitoringServers.php
  centreon/tests/php/Centreon/Application/Controller/Monitoring/TimelineControllerTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/FindRealTimeMonitoringServersTest.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/LogoutSession/LogoutSessionTest.php
Labels: area/backend

#4051 fix(services): fix an issue on service massive change (#4025)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: backport

#4302 fix (OpenID): fix random OpenID disconnection (#4068)
  centreon/cron/outdated-token-removal.php
  centreon/src/Core/Security/Authentication/Domain/Model/AuthenticationTokens.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/src/Security/Domain/Authentication/Interfaces/AuthenticationRepositoryInterface.php
  centreon/src/Security/Infrastructure/Repository/AuthenticationRepository.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/SessionAPIAuthenticatorTest.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend, backport

#4304 enh(API): added ACLs check on serverities for service and service templates endpoints (#4003) [dev-24.04.x]
  centreon/src/Core/Service/Application/UseCase/AddService/AddServiceValidation.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/ServiceCategoryRepositoryTrait.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
  centreon/tests/rest_api/collections/api-configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/api-configuration/Service_Template.postman_collection.json
Labels: area/backend

#4301 fix(RAM): Error when creating a rule with all hostgroups
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
Labels: area/backend

#4310 fix (OpenID): fix random OpenID disconnection (#4068) (#4302)
  centreon/cron/outdated-token-removal.php
  centreon/src/Core/Security/Authentication/Domain/Model/AuthenticationTokens.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Security/Domain/Authentication/Interfaces/AuthenticationRepositoryInterface.php
  centreon/src/Security/Infrastructure/Repository/AuthenticationRepository.php
  centreon/src/Security/SessionAPIAuthenticator.php
  centreon/src/Security/TokenAPIAuthenticator.php
  centreon/tests/php/Security/SessionAPIAuthenticatorTest.php
  centreon/tmpl/install/centreon.cron
Labels: area/backend, backport

#4315 Fix(UI): Fix pagination data
  centreon/tests/e2e/features/Dashboards/13-dashboard-all-widgets/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/utils.ts
Labels: area/ui, backport

#4305 enh (veracode): Exclude install php scripts from veracode analysis
  centreon/.veracode-exclusions
Labels: Veracode Dependency Scanning

#4330 enh (veracode): Exclude install php scripts from veracode analysis (#4305)
  centreon/.veracode-exclusions
Labels: area/backend, backport

#4331 enh (veracode): Exclude install php scripts from veracode analysis (#4305)
  centreon/.veracode-exclusions
Labels: area/backend, backport

#4336 enh (veracode): Exclude install php scripts from veracode analysis (#4305)
  centreon/.veracode-exclusions
Labels: area/backend, backport

#4329 enh (veracode): Exclude install php scripts from veracode analysis (#4305)
  centreon/.veracode-exclusions
Labels: area/backend, backport

#4273 feat(install): Add Step to configure vault storage
  centreon/config/packages/Centreon.yaml
  centreon/src/CentreonLegacy/Core/Install/Information.php
  centreon/src/CentreonLegacy/Core/Install/Step/AbstractStep.php
  centreon/src/CentreonLegacy/Core/Install/Step/Step6Vault.php
  centreon/www/install/steps/process/process_step6.php
  centreon/www/install/steps/process/process_step_vault.php
  centreon/www/install/steps/step.php
  centreon/www/install/steps/templates/step6.1.tpl
  centreon/www/install/steps/templates/step6.tpl
Labels: area/backend

#4188 enh(dashboards): clarify display type in status grid and status chart
  centreon/tests/e2e/features/Dashboards/12-status-grid-widget-configuration/index.ts
  centreon/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithTwostatusGrid.json
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/useStatusGridCondensed.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGrid.cypress.spec.tsx
Labels: area/ui

#4340 fix(RAM): Remove service filter from UI
  centreon/.veracode-exclusions
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalCreate.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/models.ts
Labels: area/ui

#4338 fix(cloud): remove limitation on all_servicegroups all_hostgroups for creation
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/servicegroup/formServiceGroup.php
Labels: area/backend

#4244 enh(conf): call API to save a new host template
  centreon/composer.lock
  centreon/config/services.yaml
  centreon/features/bootstrap/DisableFieldsOnBlockedObjectsContext.php
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/features/bootstrap/HostTemplateBasicsOperationsContext.php
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/src/Core/Infrastructure/Common/Api/Router.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHostOnPrem.ihtml
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: area/backend

#4377 fix(RAM): Error to get a service group or category
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/Form/useFormSubmit.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInputs/hooks/useDatasetFilter.ts
Labels: area/ui

#4371 fix(ram): force isCloudPlatform argument in class definition
  centreon/src/Core/ResourceAccess/Infrastructure/Configuration/symfony.yaml
Labels: area/backend

#4363 enh(API): Added ACL checks on monitoring server & host severity
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/src/Core/MonitoringServer/Application/Repository/ReadMonitoringServerRepositoryInterface.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/DbReadMonitoringServerRepository.php
Labels: area/backend

#4317 fix(dashboard): add consistent information regarding playlist statistics
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend

#4399 fix(servicegroup): error fixed in cloud context for servicegroup creation
  centreon/www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#4311 enh(map): Change window size lime in cypress config
  centreon/packages/js-config/cypress/component/configuration.js
Labels: area/ui

#4403 fix(servicegroups): error fixed during servicegroup creation on cloud it2
  centreon/www/include/configuration/configObject/servicegroup/DB-Func.php
Labels: area/backend

#4379 Fix(UI): Fix links generation to resource status
  centreon/tests/e2e/features/Dashboards/13-dashboard-all-widgets/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
Labels: area/ui

#4404 feat(Vault): Read Database credentials from vault
  centreon/config/centreon.config.php.template
  centreon/config/services.yaml
  centreon/src/Core/Security/Vault/Infrastructure/Repository/FsReadVaultConfigurationRepository.php
  centreon/src/Core/Security/Vault/Infrastructure/Repository/FsWriteVaultConfigurationRepository.php
Labels: area/backend

#4411 enh(ACL): Added ACL checks on monitoring server and host severity
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHost.php
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostTest.php
Labels: area/backend

#4264 enh(conf): call API to save a new host
  centreon/features/bootstrap/DowntimeRecurrentContext.php
  centreon/features/bootstrap/EscalationConfigurationContext.php
  centreon/features/bootstrap/HostCategoryConfigurationContext.php
  centreon/features/bootstrap/HostConfigurationContext.php
  centreon/features/bootstrap/HostDependencyConfigurationContext.php
  centreon/features/bootstrap/HostGroupConfigurationContext.php
  centreon/features/bootstrap/MassiveChangeHostsContext.php
  centreon/features/bootstrap/MassiveChangeServicesContext.php
  centreon/features/bootstrap/ServiceConfigurationContext.php
  centreon/features/bootstrap/ServiceDependencyConfigurationContext.php
  centreon/features/bootstrap/ServiceTemplateConfigurationContext.php
  centreon/features/bootstrap/TrapsSNMPConfigurationContext.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
Labels: area/backend

#4410 enh(install): improve vault steps style in wizard
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/install/steps/process/getFeatureFlags.php
  centreon/www/install/steps/process/process_step6.php
  centreon/www/install/steps/templates/step6.1.tpl
  centreon/www/install/steps/templates/step6.tpl
Labels: area/backend

#4407 enh(UI): Display widget last update time
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/usePanelStyles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLastRefresh.ts
Labels: area/ui

#4417 enh(API): Added filtering of contacts and contact groups by ACLs
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadHostNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadHostNotificationRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
Labels: area/backend

#4422 enh(API): Added filtering of contacts and contact groups by ACLs
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadServiceNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicy.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadServiceNotificationRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindServiceNotificationPolicyTest.php
Labels: area/backend

#4445 fix(servicegroups): error when creating a service with user cloud
  centreon/www/class/centreonServicegroups.class.php
  centreon/www/include/configuration/configObject/service/formService.php
Labels: area/backend

#4441 fix (Recurrent downtime): update SQL queries
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/downtime.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend, backport

#4312 enh(API): added ACLs check on serverities for service and service templates endpoints (#4003) [dev-23.10.x]
  centreon/src/Core/Service/Application/UseCase/AddService/AddServiceValidation.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/ServiceCategoryRepositoryTrait.php
  centreon/src/Core/ServiceTemplate/Application/Repository/ReadServiceTemplateRepositoryInterface.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/AddServiceTemplate/AddServiceTemplateValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplates.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbReadServiceTemplateRepository.php
  centreon/tests/api/features/ServiceOnPrem.feature
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/FindServiceTemplates/FindServiceTemplatesTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
Labels: area/backend

#4431 feat(install): write database credentials into vault
  centreon/config/centreon.config.php.template
  centreon/src/Core/Security/Vault/Infrastructure/Repository/FsReadVaultConfigurationRepository.php
  centreon/www/install/steps/process/migrateCredentialsToVault.php
  centreon/www/install/steps/process/process_step9.php
  centreon/www/install/steps/process/process_step_vault.php
Labels: area/backend

#4460 fix (Recurrent downtime): update SQL queries (#4441)
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/downtime.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend, backport

#4461 fix (Recurrent downtime): update SQL queries (#4441)
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/downtime.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend, backport

#4402 [24.04.x] fix(packaging): fix symfony cache rights issue
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: backport

#4466 fix (Recurrent downtime): update SQL queries (#4441)
  centreon/www/class/centreonDowntime.class.php
  centreon/www/include/monitoring/recurrentDowntime/downtime.php
  centreon/www/include/monitoring/recurrentDowntime/formDowntime.php
Labels: area/backend, backport

#4474 fix (pendo): replace cdn.eu.pendo.io by guide.centreon.com for snippet
  centreon/tests/e2e/features/ACLs/01-acl-access-groups/index.ts
  centreon/www/front_src/src/App/initPendo.js
  centreon/www/include/common/javascript/pendo.js
Labels: area/backend

#4476 fix(dashboard): update dashboard name with empty description
  centreon/src/Core/Dashboard/Application/UseCase/PartialUpdateDashboard/PartialUpdateDashboard.php
Labels: area/backend

#4443 enh(conf/broker) Extend AddBrokerOutput into AddBrokerInputOutput to handle inputs
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Broker/Application/Exception/BrokerException.php
  centreon/src/Core/Broker/Application/Repository/ReadBrokerInputOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/Repository/WriteBrokerInputOutputRepositoryInterface.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutput.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputPresenterInterface.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputRequest.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputResponse.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/BrokerInputOutputValidator.php
  centreon/src/Core/Broker/Application/UseCase/AddBrokerInputOutput/TypeDto.php
  centreon/src/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFile.php
  centreon/src/Core/Broker/Domain/Model/BrokerInputOutput.php
  centreon/src/Core/Broker/Domain/Model/BrokerInputOutputField.php
  centreon/src/Core/Broker/Domain/Model/NewBrokerInputOutput.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputController.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputPresenter.php
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputRoute.yaml
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputSchema.json
  centreon/src/Core/Broker/Infrastructure/API/AddBrokerOutput/AddBrokerOutputRoute.yaml
  centreon/src/Core/Broker/Infrastructure/API/UpdateStreamConnectorFile/UpdateStreamConnectorFileController.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbReadBrokerInputOutputRepository.php
  centreon/src/Core/Broker/Infrastructure/Repository/DbWriteBrokerInputOutputRepository.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerInputOutput/AddBrokerInputOutputTest.php
  centreon/tests/php/Core/Broker/Application/UseCase/AddBrokerInputOutput/BrokerInputOutputValidatorTest.php
  centreon/tests/php/Core/Broker/Application/UseCase/UpdateStreamConnectorFile/UpdateStreamConnectorFileTest.php
  centreon/tests/php/Core/Broker/Domain/Model/BrokerInputOutputTest.php
  centreon/tests/php/Core/Broker/Domain/Model/NewBrokerInputOutputTest.php
  centreon/tests/php/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputPresenterStub.php
Labels: area/backend

#4484 fix(graph): do not parse title to get the hostname
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataTest.php
  centreon/www/class/centreonGraphNg.class.php
Labels: area/backend

#4406 fix(RAM): Edit data modal not updated automatically
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/FormInitialValues/useFormInitialValues.ts
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/ModalEdit.cypress.spec.tsx
  centreon/www/front_src/src/ResourceAccessManagement/AddEditResourceAccessRule/specs/testUtils.ts
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Header/AddButton.tsx
  centreon/www/front_src/src/ResourceAccessManagement/Listing/useListing.ts
Labels: area/ui

#4510 chore(ci): upgrade composer to latest v2 (#4502)
  .github/actions/lighthouse-performance-testing/action.yml
Labels: backport

#4434 enh(API): Added ACL check on topology, actions & monitoring server in Generate Conf Endpoint
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/MonitoringServerRepositoryTrait.php
  centreon/tests/api/features/MonitoringServerConfiguration.feature
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateConfigurationTest.php
Labels: area/backend
