Repository centreon/centreon, pull requests merged in 2025-07, with the labels that each got.

#7714 enh(ci): check version consistency of open-tickets widget
  .github/workflows/open-tickets.yml
Labels: skip-workflow-open-tickets

#7707 feat(docker): register automatically authentication providers (#7545)
  .github/docker/centreon-web/alma8/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/72-authentication.sh
  .github/docker/docker-compose.yml
  .gitleaks.toml
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/packages/js-config/cypress/e2e/tasks.ts
  centreon/tests/e2e/cypress.config.ts
  centreon/tests/e2e/cypress.dev.config.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/01-oidc-authentication/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/04-oidc-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/05-oidc-authentication-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/06-oidc-authentication-contact-groups/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/common.ts
  centreon/tests/e2e/features/Authentication/SAML/01-saml-authentication/index.ts
  centreon/tests/e2e/features/Authentication/SAML/02-saml-authentication-only/index.ts
  centreon/tests/e2e/features/Authentication/SAML/03-saml-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/SAML/04-saml-authentication-contact-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/05-saml-authentication-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/06-saml-authentication-first-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/07-saml-authentication-restrictions/index.ts
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/provider-acl.json
  centreon/tests/e2e/support/commands.ts
Labels: skip-workflow-web-analysis

#6296 url[fix] update url
  centreon/install.sh
  centreon/libinstall/CentWeb.sh
  centreon/www/class/centreon-clapi/centreonAPI.class.php
  centreon/www/include/configuration/configKnowledge/functions.php
  centreon/www/install/step_upgrade/templates/content.tpl
  centreon/www/install/steps/templates/content.tpl
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7662 Enh(PAC) handle cma tokens in Agent configuration for reverse connection (#7533)
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/CMATokenField.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfigurations.ts
  centreon/www/front_src/src/AgentConfiguration/Form/RedirectToTokensPage.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/api/endpoints.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui, area/backend, backport, upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7742 fix(packaging): fix centreon-web packaging dependency to centreon-per…
  centreon/packaging/centreon-trap.yaml
  centreon/packaging/centreon-web.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7737 Enh(PAC) handle cma tokens in Agent configuration for reverse connect…
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/CMATokenField.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfigurations.ts
  centreon/www/front_src/src/AgentConfiguration/Form/RedirectToTokensPage.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/api/endpoints.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui, upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7729 fix(packaging): remove dependency between centreon-database and collect
  centreon/packaging/centreon-mariadb.yaml
  centreon/packaging/centreon-mysql.yaml
Labels: upload-artifacts, skip-workflow-web-analysis, qa-approved

#7717 test(e2e): Fix nightly E2E tests
  centreon/tests/e2e/features/ACLs/03-acl-menus-access/index.ts
  centreon/tests/e2e/features/ACLs/04-acl-resources-access/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/commands.ts
Labels: skip-workflow-web-analysis

#7752 test(e2e): Fix nightly E2E tests
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Resources-status/03-downtime/index.ts
Labels: skip-workflow-web-analysis

#7749 fix(resources): count all resources by ACL fixed (#7730)
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7430 CTOR-1656-plugin-apps-nmap-cli-add-test-and-move-centreon-plugins-sudoers-to-centreon-plugin-repository
  centreon/packaging/centreon-plugins-sudoers.yaml
  centreon/packaging/src/sudoersCentreonPlugins
Labels: skip-workflow-web, skip-workflow-web-analysis

#7738 enh(agent configuration): set certificate fields to optional (#7534)
  centreon/src/Core/AgentConfiguration/Application/Factory/AgentConfigurationFactory.php
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/TelegrafConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbReadAgentConfigurationRepository.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurationsTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/TelegrafConfigurationParametersTest.php
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
Labels: area/ui, area/backend, skip-workflow-web-analysis, qa-approved

#7736 MON-174563 Hotfix 25.03.1 web
  .version.centreon-web
  centreon/packaging/centreon-trap.yaml
  centreon/packaging/centreon-web.yaml
  centreon/www/include/monitoring/downtime/listDowntime.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-25.03.1.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#7667 enh(map): add Map Response structure to ConnectedAutocompleteField
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/api/models.ts
  centreon/packages/ui/src/index.ts
Labels: area/ui, skip-workflow-web-analysis, qa-approved

#7760 fix(release): fix release action to properly fetch tags for cloud versions
  .github/actions/release/action.yml
Labels: skip-cherry-pick

#7757 enh(agent configuration): set certificate fields to optional (#7534) …
  centreon/src/Core/AgentConfiguration/Application/Factory/AgentConfigurationFactory.php
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/TelegrafConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbReadAgentConfigurationRepository.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurationsTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/TelegrafConfigurationParametersTest.php
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7748 chore(deps): absorb 2025-07 dependabot GitHub Actions updates
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/lighthouse-performance-testing/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#7755 fix(CEIP): removed feature flag test in sending CEIP data for dashboards (#7670) [dev-24.10.x]
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7746 fix(LDAP): user with no mail cannot authenticate on Centreon with LDA… (#7668)
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7438 MON-150244-remove-whitelist-from-40-gorgoned-yaml-file-for-now-plateform
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis

#7756 fix(CEIP): removed feature flag test in sending CEIP data for dashboards (#7670) [dev-24.04.x]
  centreon/www/class/centreonStatistics.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7786 Fix(CI): update snapshots for Notification listing tests
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- disables the Delete button when no rows are selected, and displays it when one or more rows are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a confirmation dialog upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a success message after a successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a warning message containing the names of the notifications that failed to be deleted if the deletion of some notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays an error message if the deletion of all notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays an error message upon failed deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- disables the Confirm button if the name is empty or already exists.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a confirmation dialog with a text field for the new notification name when the Duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a success message after a successful duplication.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays an error message upon failed duplication request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- validates that the name field is not empty and the name does not already exist.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- displays the first page of the notifications listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a get notifications request after updating limit param.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a listing request with an updated page param when a change page action is clicked.snap.png
Labels: area/ui, skip-workflow-web-analysis, qa-approved

#7789 Enh(host groups) add at least one mandatory resource_access_rule in H…
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/Specs/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- Modal -- disables the save button when the platform is cloud and Resource Access Rules field is empty.snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/HostGroup/Application/Exceptions/HostGroupException.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupValidator.php
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupValidator.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupInput.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupInput.php
  centreon/www/front_src/src/Configuration/HostGroups/Form/useFormInputs.tsx
  centreon/www/front_src/src/Configuration/HostGroups/Form/useValidationSchema.ts
  centreon/www/front_src/src/Configuration/HostGroups/Specs/HostGroups.Modal.tsx
  centreon/www/front_src/src/Configuration/HostGroups/Specs/utils.ts
  centreon/www/front_src/src/Configuration/HostGroups/translatedLabels.ts
Labels: area/ui, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7783 Sync release 170629 trice
  README.md
Labels: skip-workflow-docker-web-dependencies, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-docker-vault, skip-workflow-web-analysis, skip-workflow-docker-translation, skip-workflow-docker-keycloak, skip-workflow-docker-glpi, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-docker-packaging, skip-workflow-open-tickets-analysis, skip-workflow-ha-analysis

#7792 Fix(CI): flacky component tests: Notification listing & AddEditWidget
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- disables the Delete button when no rows are selected, and displays it when one or more rows are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a confirmation dialog upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a success message after a successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays a warning message containing the names of the notifications that failed to be deleted if the deletion of some notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing header Delete button -- displays an error message if the deletion of all notifications fails.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a confirmation dialog containing the notification name upon clicking the Delete button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays a success message after successful deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Delete button -- displays an error message upon failed deletion.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- disables the Confirm button if the name is empty or already exists.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a confirmation dialog with a text field for the new notification name when the Duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays a success message after a successful duplication.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- displays an error message upon failed duplication request.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Listing row actions Duplicate button -- validates that the name field is not empty and the name does not already exist.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- displays the first page of the notifications listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a get notifications request after updating limit param.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/Notifications Listing -- executes a listing request with an updated page param when a change page action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- No widgets -- does not display widgets when any widgets are registered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/testUtils.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7739 Clean up French translations for centreon-web/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis

#7765 Enh([Rs widget]):Resizing of RS widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7766 fix(customViews): save select all in local storage for host monitoring widget
  centreon/www/widgets/host-monitoring/data.js
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7770 Update input validation on AddHostSaasSchema.json
  centreon/src/Core/Host/Infrastructure/API/AddHost/AddHostSaasSchema.json
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7802 chore(quality-tools): improve quality tools for centreon awie
  .github/workflows/awie.yml
  centreon-awie/.php-cs-fixer.legacy.php
  centreon-awie/composer-require-checker.json
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-awie/features/bootstrap/ImportExportContext.php
  centreon-awie/phpstan.legacy.neon
  centreon-awie/phpstan.neon
  centreon-awie/phpstan.stub
  centreon-awie/rector.legacy.php
  centreon-awie/rector.php
  centreon-awie/ruleset.xml
  centreon-awie/www/modules/centreon-awie/class/Export.class.php
  centreon-awie/www/modules/centreon-awie/core/launchImport.php
Labels: enhancement, area/backend, skip-workflow-awie, skip-workflow-awie-analysis, qa-approved

#7683 fix(ui): Display issue when changing graph type (#7593)
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays only one line with custom style when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays additional lines when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars when a line and a bar are customized.snap.png
  centreon/packages/ui/src/Graph/BarChart/BarChart.tsx
  centreon/packages/ui/src/Graph/Chart/index.tsx
  centreon/packages/ui/src/Graph/common/BaseChart/useComputeBaseChartDimensions.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Preview.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7784 fix(gorgone): remove action module from main gorgone configuration file
  centreon/www/include/configuration/configServers/popup/central.yaml
  centreon/www/include/configuration/configServers/popup/poller.yaml
  centreon/www/include/configuration/configServers/popup/remote.yaml
  centreon/www/install/var/gorgone/gorgoneCentralTemplate.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7773 fix(ui): bad redirection on see more tile
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/Tooltip.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/spec/testUtils.ts
Labels: area/ui, qa-approved

#7834 enh(API): Add a RouteLoader mechanism for APIv2 (#7601)
  centreon/config/routes/centreon.yaml
  centreon/phpstan.core.neon
  centreon/src/CentreonLegacy/Core/Module/Upgrader.php
  centreon/src/Core/Common/Infrastructure/Routing/ModuleRouteLoader.php
  centreon/src/Core/Module/Application/Repository/ModuleInformationRepositoryInterface.php
  centreon/src/Core/Module/Domain/Model/ModuleInformation.php
  centreon/src/Core/Module/Infrastructure/ModuleInstallationVerifier.php
  centreon/src/Core/Module/Infrastructure/Repository/DbReadModuleInformationRepository.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7806 fix(quality-tools): review of php quality tools jobs to be sure to stop it in case of error
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  centreon/phpstan.legacy.www.baseline.neon
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7800 Fix([Dashboard]): Save on dashboard leave buggy when heading to a legacy page
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- does not save changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- saves changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useDashboardSaveBlocker.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7838 fix(httploader): correctly use the website parameter (#7817)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/api/class/centreon_home_customview.class.php
  widgets/centreon-widget-httploader/httploader/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7840 fix(httploader): correctly use the website parameter (#7817)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/widgets/httploader/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7846 fix(eventLogs): service detection fixed (#7791)
  centreon/www/include/eventLogs/viewLog.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7826 test(e2e):openticket: Adding Biome (js) to the lint typescript
  .github/actions/gherkin-lint/action.yml
  .github/workflows/open-tickets.yml
  centreon-open-tickets/tests/e2e/biome.json
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/package.json
  centreon-open-tickets/tests/e2e/pnpm-lock.yaml
Labels: area/test, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis

#7849 enh(install/upgrade): manage creation of encryption ready column and writing in engine file
  .github/docker/centreon-web/alma8/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/15-installation.sh
  centreon/config/packages/Centreon.yaml
  centreon/config/services.yaml
  centreon/config/symfony_serializer/Engine/EngineSecrets.yaml
  centreon/src/Core/Engine/Application/Repository/EngineRepositoryInterface.php
  centreon/src/Core/Engine/Domain/Model/EngineKey.php
  centreon/src/Core/Engine/Domain/Model/EngineSecrets.php
  centreon/src/Core/Engine/Infrastructure/Repository/FsEngineRepository.php
  centreon/src/Core/Engine/Infrastructure/Serializer/EngineSecretsNormalizer.php
  centreon/src/Core/Installation/Infrastructure/InstallationHelper.php
  centreon/www/install/createTables.sql
  centreon/www/install/installBroker.sql
  centreon/www/install/php/Update-next.php
  centreon/www/install/step_upgrade/step4.php
  centreon/www/install/steps/process/createEngineContextConfiguration.php
  centreon/www/install/steps/process/process_step9.php
  centreon/www/widgets/httploader/index.php
Labels: skip-workflow-web

#7831 Mon 176587 openticket e2e linting biome js backport 2410
  .github/actions/frontend-lint/action.yml
  .github/actions/gherkin-lint/action.yml
  .github/workflows/open-tickets.yml
  centreon-open-tickets/tests/e2e/biome.json
  centreon-open-tickets/tests/e2e/commons.ts
  centreon-open-tickets/tests/e2e/configuration.ts
  centreon-open-tickets/tests/e2e/cypress.config.ts
  centreon-open-tickets/tests/e2e/cypress.dev.config.ts
  centreon-open-tickets/tests/e2e/esbuild-preprocessor.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/dashboards/check-permissions/dashboards.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/dashboards.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/widgets/dashboardWithResourceTableWidget.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/creation/widgets/genericText.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/navigation/dashboards-more-than-a-single-page.json
  centreon-open-tickets/tests/e2e/fixtures/dashboards/navigation/dashboards-single-page.json
  centreon-open-tickets/tests/e2e/fixtures/users/admin.json
  centreon-open-tickets/tests/e2e/package.json
  centreon-open-tickets/tests/e2e/plugins.ts
  centreon-open-tickets/tests/e2e/plugins/index.ts
  centreon-open-tickets/tests/e2e/pnpm-lock.yaml
  centreon-open-tickets/tests/e2e/reporter-config.js
  centreon-open-tickets/tests/e2e/support/commands.ts
  centreon-open-tickets/tests/e2e/support/e2e.ts
  centreon-open-tickets/tests/e2e/tasks.ts
  centreon-open-tickets/tests/e2e/tsconfig.json
Labels: area/test, backport, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis

#7839 fix(httploader): correctly use the website parameter (#7817)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/widgets/httploader/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7858 front(web):wigets: fix lint biomeJS errors
  centreon/www/widgets/src/centreon-widget-batimeline/moduleFederation.json
  centreon/www/widgets/src/centreon-widget-batimeline/properties.json
  centreon/www/widgets/src/centreon-widget-batimeline/src/index.tsx
  centreon/www/widgets/src/centreon-widget-batimeline/src/models.ts
  centreon/www/widgets/src/centreon-widget-batimeline/src/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/BATooltipContent.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
  centreon/www/widgets/src/utils.ts
Labels: area/ui, javascript, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7865 fix: lighthouse
  .github/actions/lighthouse-performance-testing/action.yml
  centreon/lighthouse/package-lock.json
  centreon/lighthouse/package.json
Labels: qa-approved

#7833 enh(centreon-test-lib) : update centreon-test-lib to clean packages
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.lock
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon/composer.lock
  php-tools/composer.json
Labels: enhancement, area/backend, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis, qa-approved

#7843 fix(eventLogs): service detection fixed (#7791)
  centreon/www/include/eventLogs/viewLog.php
Labels: backport, qa-approved

#7844 fix(eventLogs): service detection fixed (#7791)
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
  centreon/www/include/eventLogs/viewLog.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7868 fix(eventLogs): service detection fixed (#7791)
  centreon/www/include/eventLogs/viewLog.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7862 Backport([dev-24.04.x]) : [Resource Status] Wrong interpretation of "|" character
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.test.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7864 Fix(UI): Several French translations are missing from the interface
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/components/DashboardSaveBlockerModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7828 fix(dashboard): apply correct share behaviour regarding env (#6584)
  centreon/config/symfony_serializer/Dashboard/DashboardContact.yaml
  centreon/config/symfony_serializer/Dashboard/DashboardContactGroup.yaml
  centreon/src/Core/Dashboard/Application/Exception/DashboardException.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardShareRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/Response/ContactGroupsResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/Response/ContactsResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardRequest.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardValidator.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardController.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardInput.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardRequestTransformer.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardSchema.json
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
  centreon/src/Core/Dashboard/Infrastructure/Serializer/DashboardContactGroupsResponseNormalizer.php
  centreon/src/Core/Dashboard/Infrastructure/Serializer/DashboardContactResponseNormalizer.php
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardValidatorTest.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7836 fix(customViews): save select all in local storage for host monitoring widget (#7766)
  centreon/www/widgets/host-monitoring/data.js
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7835 fix(customViews): save select all in local storage for host monitoring widget (#7766)
  centreon/www/widgets/host-monitoring/data.js
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7848 fix(dashboard): duplicated contacts listed in shares
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7891 fix(web) : getting of depencyInjector in modules fixed
  centreon/container.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7888 fix(RS): fix notif contacts and cg doubled in list (#7863)
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7889 fix(RS): fix notif contacts and cg doubled in list (#7863)
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7877 fix(resource status): disabled notification icon is not displayed in associated column
  centreon/www/front_src/src/Resources/Listing/columns/Notification.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7695 feat(resource-status): add an option to disable some fields on free search
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/isResourceStatusFullSearchEnabledAtom.ts
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/tests/rest_api/collections/administration/Parameters.postman_collection.json
  centreon/www/front_src/src/App/models.ts
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Resources/Actions/exportToCsv/useExportCsv.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  centreon/www/front_src/src/Resources/Filter/SearchHelp.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/SearchHelp.tsx
  centreon/www/front_src/src/Resources/Listing/useLoadResources/index.ts
  centreon/www/front_src/src/Resources/Listing/useLoadResources/utils.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/general/form.ihtml
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/Administration/parameters/general/help.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7857 Backport([dev-24.10.x]):[Resource Status] Wrong interpretation of "|" character
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.test.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7874 Backport([dev-23.10.x]):[Resource Status] Wrong interpretation of "|" character
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/index.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.test.ts
  centreon/www/front_src/src/Resources/Details/tabs/Details/CommandLine/utils/index.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7867 fix(test): fix ram listing test
  centreon/cypress/visual-testing-snapshots/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx/Listing row actions Delete button -- closes a delete confirmation dialog when Cancel button is clicked.snap.png
  centreon/www/front_src/src/ResourceAccessManagement/Listing/Tests/ResourceAccessRulesListing.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7920 chore(E2E) : Fix resource table e2e test
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
Labels: skip-workflow-web-analysis

#7893 Enh(Dashboard): Single metric widget in dashboard does not show the same value as in ressource status
  centreon/cypress/fixtures/Widgets/Graph/metricWithBytUnit.json
  centreon/cypress/fixtures/Widgets/Graph/metrics.json
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useListMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/api/decoders.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/models.ts
Labels: area/ui

#7764 fix(Custom view): restrict access to views
  centreon/www/class/centreonCustomView.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7917 Prevent empty name on host & host group on creation via clapi
  centreon/www/class/centreon-clapi/centreonHost.class.php
  centreon/www/class/centreon-clapi/centreonHostGroup.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7903 Backport([release-25.07-next]) :Error When Setting Time Period to "Customized" in Metrics Graph Widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/useTimePeriod.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7926 enh(ENV)(OpenID): Add a proxy container for openid (#7900)
  .github/actions/cypress-e2e-testing/action.yml
  .github/docker/README.md
  .github/docker/docker-compose.yml
Labels: area/backend, backport

#7918 [dev-24.10.x] Prevent empty name on host & host group on creation via clapi
  centreon/www/class/centreon-clapi/centreonHost.class.php
  centreon/www/class/centreon-clapi/centreonHostGroup.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7929 fix(ci): upgrade gettext to handle php heredoc indent
  .github/docker/Dockerfile.translation
Labels: skip-workflow-web-analysis, skip-workflow-docker-translation

#7931 test(behat): web: Comment the Recurrent & DST Downtimes (dev-24.04)
  centreon/features/DowntimeDST/Realtime.feature.ignored
  centreon/features/DowntimeDST/Recurrent.feature.ignored
  centreon/features/DowntimeRecurrent.feature.ignored
Labels: area/backend, area/test, php, skip-workflow-web-analysis

#7932 test(behat): web: Comment the Recurrent & DST Downtimes (dev-23.10)
  centreon/features/DowntimeDST/Realtime.feature.ignored
  centreon/features/DowntimeDST/Recurrent.feature.ignored
  centreon/features/DowntimeRecurrent.feature.ignored
Labels: area/backend, area/test, php, skip-workflow-web-analysis, qa-approved
