Repository centreon/centreon, pull requests merged in 2025-03, with the labels that each got.

#6792 fix(Host Groups): remove sunset fields from bulk duplicate endpoint
  centreon/doc/API/latest/onPremise/Configuration/HostGroup/DuplicateHostGroups.yaml
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
Labels: area/backend, skip-workflow-web

#6815 fix(Widget): Users under ACLs can't see the servicegroups (#6770)
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6824 enh(rule): do not block Rule retrieval if not contact and contact groups
  centreon/src/Core/ResourceAccess/Domain/Model/NewRule.php
  centreon/tests/php/Core/ResourceAccess/Domain/Model/RuleTest.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6818 fix(Widget): Users under ACLs can't see the servicegroups (#6770)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#6817 fix(Widget): Users under ACLs can't see the servicegroups (#6770)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#6809 fix(Config): Handling of Read-Only to User Settings (#6715)
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6814 fix(Widget): Users under ACLs can't see the servicegroups (#6770)
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6808 fix(Config): Handling of Read-Only to User Settings (#6715)
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6807 fix(Config): Handling of Read-Only to User Settings (#6715)
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6806 fix(Config): Handling of Read-Only to User Settings (#6715)
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6766 enh(upgrade): add file update-next.php with php content for next release
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update-next.php.tpl
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6845 fix(ci): restore docker image cache properly in newman workflow
  .github/workflows/newman.yml
Labels: skip-workflow-web, skip-workflow-web-analysis

#6820 fix(configuration): fix notification period field in add/update service
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6798 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hostgroups (#6736)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport

#6801 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hostgroups (#6736)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport

#6802 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hostgroups (#6736)
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6800 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hostgroups (#6736)
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6804 fix(MAP): Service groups not available in BULK mode (#6755)
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6761 fix(API): Added handling of 401 Unauthorized Response
  centreon/src/Centreon/Application/Controller/AbstractController.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6805 fix(MAP): Service groups not available in BULK mode (#6755)
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6803 fix(MAP): Service groups not available in BULK mode (#6755)
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport, skip-workflow-web-analysis

#6813 enh (Knowledge): migrate the knowledge base configuration behat test to a cypress test
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/tests/e2e/features/Knowledges/01-knowledge-base.feature
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
  centreon/tests/e2e/features/Knowledges/common.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6782 fix(UI): Retrieve the correct iframe on legacy page (#6771)
  centreon/www/front_src/src/route-components/legacyRoute/index.tsx
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6810 feat(Configuration revamp): Adjust topology and redirections
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host clears all applied filters and sends a listing request with empty search parameters when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host displays and interacts with filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host displays the confirmation dialog when the inline delete button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host displays the confirmation dialog when the inline duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host displays the confirmation dialog when the massive delete button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host displays the confirmation dialog when the massive duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group clears all applied filters and sends a listing request with empty search parameters when the clear button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group displays and interacts with filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group displays the confirmation dialog when the inline delete button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group displays the confirmation dialog when the inline duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group displays the confirmation dialog when the massive delete button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group displays the confirmation dialog when the massive duplicate button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group hides the advanced filters icon when only the name field is filterable'.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group renders the layout with all components.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a delete request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a delete request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a disable request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a disbale request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a duplicate request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a duplicate request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a duplicate request for multiple resources with a custom number of duplications and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a listing request when fields are filled and the search button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends a listing request with name filter when the search bar is filled and enter key is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends an Enable request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host group sends an enable request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host hides the advanced filters icon when only the name field is filterable'.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host renders the layout with all components.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a delete request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a delete request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a disable request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a disbale request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a duplicate request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a duplicate request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a duplicate request for multiple resources with a custom number of duplications and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a listing request when fields are filled and the search button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends a listing request with name filter when the search bar is filled and enter key is triggered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends an Enable request for a single resource and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.cypress.spec.tsx/host sends an enable request for multiple resources and displays a success message.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- displays a 'Not found' message when hovering over the disabled host groups column with no hosts.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- displays a 'Not found' message when hovering over the enabled host groups column with no hosts.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- displays all hosts of the host group when hovering over the disabled host groups column.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- displays all hosts of the host group when hovering over the enabled host groups column.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- displays and interacts with filters.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx/Host groups configuration  -- renders the Host group page with the ConfigurationBase layout.snap.png
  centreon/features/bootstrap/DowntimeRecurrentContext.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/fixtures/host-groups/host-group.json
  centreon/www/front_src/src/Configuration/ConfigurationBase/Listing/ActionsBar/AddAction.tsx
  centreon/www/front_src/src/Configuration/ConfigurationBase/Listing/useListing.ts
  centreon/www/front_src/src/Configuration/ConfigurationBase/Specs/Configuration.Modal.tsx
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-next.php
Labels: area/ui, skip-workflow-web

#6783 fix(UI): Retrieve the correct iframe on legacy page (#6771)
  centreon/www/front_src/src/route-components/legacyRoute/index.tsx
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6836 [dev-24.04.x] - [MAP]when too many elements are selected in a Geoview the list is out of visibility
  centreon/packages/ui/package.json
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.stories.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
  centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
  centreon/pnpm-lock.yaml
Labels: area/ui

#6844 [dev-24.10.x] - [MAP]when too many elements are selected in a Geoview the list is out of visibility
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Add widget -- adds a widget when a widget type is selected and the submission button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dashboard global properties -- displays the dashboard global properties form when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dashboard global properties -- edits the dashboards when the refresh type and refresh are updated and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dataset -- displays header link to Business activity when the widget has only business activities.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- deletes a widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not display the name of the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Edit widget -- edits a widget when the corresponding button is clicked and the widget type is changed the edit button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Managment favorite dashboards -- add a dashboard to favorites when clicking on the corresponding icon in the details view.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Managment favorite dashboards -- remove a dashboard from favorites when clicking on the corresponding icon in the details view.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- does not save changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Route blocking -- saves changes when a dashboard is being edited, a dashboard is updated, the user goes to another page and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- saves an empty dashbord when widgets are removed and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- sends a shares update request when the shares are update and the corresponding button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a stacked bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/src/Form/Inputs/Autocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/Radio.tsx
  centreon/packages/ui/src/Form/Inputs/Text.tsx
  centreon/packages/ui/src/Graph/BarChart/BarChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.stories.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
  centreon/packages/ui/src/Listing/index.tsx
  centreon/www/front_src/public/mockServiceWorker.js
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6850 enh (Knowledge): migrate the knowledge base configuration behat test to a cypress test(24.10.x)
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/tests/e2e/features/Knowledges/01-knowledge-base.feature
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
  centreon/tests/e2e/features/Knowledges/common.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6853 enh (Knowledge): migrate the knowledge base configuration behat test to a cypress test(24.04.x)
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/tests/e2e/features/Knowledges/01-knowledge-base.feature
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
  centreon/tests/e2e/features/Knowledges/common.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6584 fix(dashboard): apply correct share behaviour regarding env
  centreon/config/symfony_serializer/Dashboard/DashboardContact.yaml
  centreon/config/symfony_serializer/Dashboard/DashboardContactGroup.yaml
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/phpstan.core.neon
  centreon/src/Core/Dashboard/Application/Exception/DashboardException.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardShareRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/Response/ContactGroupsResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsResponse.php
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/Response/ContactsResponseDto.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboard.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardPresenterInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardRequest.php
  centreon/src/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardValidator.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContactGroups/FindDashboardContactGroupsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsController.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindDashboardContacts/FindDashboardContactsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardController.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardInput.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardRequestTransformer.php
  centreon/src/Core/Dashboard/Infrastructure/API/ShareDashboard/ShareDashboardSchema.json
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
  centreon/src/Core/Dashboard/Infrastructure/Serializer/DashboardContactGroupsResponseNormalizer.php
  centreon/src/Core/Dashboard/Infrastructure/Serializer/DashboardContactResponseNormalizer.php
  centreon/src/Core/Dashboard/Infrastructure/Voters/DashboardVoter.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroupsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContactsTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardPresenterStub.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardTest.php
  centreon/tests/php/Core/Dashboard/Application/UseCase/ShareDashboard/ShareDashboardValidatorTest.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6858 test(behat): Remove AutoLogin feature missing content
  centreon/behat.yml
  centreon/features/bootstrap/AutologinContext.php
  centreon/features/bootstrap/AutologinOptionsContext.php
Labels: area/backend, area/test, php, skip-workflow-web, skip-workflow-web-analysis

#6846 fix(configuration): fix notification period field in add/update service (#6820)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6847 fix(configuration): fix notification period field in add/update service #6820
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6848 fix(configuration): fix notification period field in add/update service (#6820)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6852 chore(E2E): Notifications period on services/services by host group/ Templates forms (24.10.x)
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/05-service-template-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
Labels: area/test, backport

#6857 enh (Administration): migrate the DB Partitioning behat test to a cypress test
  centreon/behat.yml
  centreon/features/Partitioning.feature
  centreon/features/bootstrap/PartitioningContext.php
  centreon/tests/e2e/features/Administration/04-db-partitionning.feature
  centreon/tests/e2e/features/Administration/04-db-partitionning/index.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6862 enh (Administration): migrate the DB Partitioning behat test to a cypress test - 24.10
  centreon/behat.yml
  centreon/features/Partitioning.feature
  centreon/features/bootstrap/PartitioningContext.php
  centreon/tests/e2e/features/Administration/04-db-partitionning.feature
  centreon/tests/e2e/features/Administration/04-db-partitionning/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6864 chore(E2E): Notifications period on services/services by host group/ Templates forms - 24.04
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/05-service-template-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
Labels: area/test, backport

#6863 enh (Administration): migrate the DB Partitioning behat test to a cypress test -24.04
  centreon/behat.yml
  centreon/features/Partitioning.feature
  centreon/features/bootstrap/PartitioningContext.php
  centreon/tests/e2e/features/Administration/04-db-partitionning.feature
  centreon/tests/e2e/features/Administration/04-db-partitionning/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6789 Fix(Resource Status): Timeline period filter not properly applied
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6856 fix(configuration): add idempotence to db operations
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6854 fix(host): only update severity when severity is set
  centreon/src/Core/Host/Infrastructure/Repository/DbWriteHostRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6861 test(behat): Remove AutoLogin feature missing content (#6858) - 24.10
  centreon/behat.yml
  centreon/features/bootstrap/AutologinContext.php
  centreon/features/bootstrap/AutologinOptionsContext.php
Labels: area/backend, area/test, backport, php, skip-workflow-web, skip-workflow-web-analysis

#6860 test(behat): Remove AutoLogin feature missing content (#6858) - 24.04
  centreon/behat.yml
  centreon/features/bootstrap/AutologinContext.php
  centreon/features/bootstrap/AutologinOptionsContext.php
Labels: area/backend, area/test, backport, php, skip-workflow-web, skip-workflow-web-analysis

#6837 enh(database): add comments for hosts related tables
  centreon/www/install/createTables.sql
Labels: skip-workflow-web, skip-workflow-web-analysis

#6871 fix(ci): e2e tests with mysql 8.0
  .github/workflows/get-environment.yml
Labels: database, skip-workflow-web

#6859 chore(deps): absorb 2025-03 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/lighthouse-performance-testing/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/package/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/actions/veracode-generate-binary/action.yml
  .github/workflows/behat-test.yml
  .github/workflows/clean-npm-tags.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#6667 [Dashboards][Public Playlists] - Graph widget shows multiple graph where it only has one from the web UI.
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useListMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/useTopBottom.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6872 fix(Host Groups): restore icon field for duplicate
  centreon/doc/API/centreon-api.yaml
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
Labels: area/backend, skip-workflow-web

#6873 enh (Graph): migrate the LimitMetricInChart behat test to a cypress test
  centreon/behat.yml
  centreon/features/LimitMetricInChart.feature
  centreon/features/bootstrap/LimitMetricInChartContext.php
  centreon/tests/e2e/features/Services-configuration/09-virtual-metric-handle/index.ts
  centreon/tests/e2e/features/Services-configuration/14-limit-metric-in-chart.feature
  centreon/tests/e2e/features/Services-configuration/14-limit-metric-in-chart/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/virtual-metric.json
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6882 enh (Graph): migrate the LimitMetricInChart behat test to a cypress test - 24.10
  centreon/behat.yml
  centreon/features/LimitMetricInChart.feature
  centreon/features/bootstrap/LimitMetricInChartContext.php
  centreon/tests/e2e/features/Services-configuration/09-virtual-metric-handle/index.ts
  centreon/tests/e2e/features/Services-configuration/14-limit-metric-in-chart.feature
  centreon/tests/e2e/features/Services-configuration/14-limit-metric-in-chart/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/virtual-metric.json
Labels: area/test, backport, skip-workflow-web

#6777 enh(HostGroup) Update AddHostGroup Endpoint
  centreon/config/symfony_serializer/HostGroup/HostGroup.yaml
  centreon/config/symfony_serializer/ResourceAccess/Rule.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/Schema/AddHostGroupRequest.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/Schema/FindAndUpdateHostGroup.yaml
  centreon/src/Core/Common/Domain/PlatformType.php
  centreon/src/Core/Common/Infrastructure/Validator/Constraints/WhenPlatform.php
  centreon/src/Core/Common/Infrastructure/Validator/Constraints/WhenPlatformValidator.php
  centreon/src/Core/Host/Application/Repository/ReadHostRepositoryInterface.php
  centreon/src/Core/Host/Infrastructure/Repository/ApiReadHostRepository.php
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/src/Core/HostGroup/Application/Repository/WriteHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroup.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupRequest.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupResponse.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupValidator.php
  centreon/src/Core/HostGroup/Domain/Model/HostGroupRelation.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupController.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupInput.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupPresenterOnPrem.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupPresenterSaas.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupRequestTransformer.php
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupSchemaOnPrem.json
  centreon/src/Core/HostGroup/Infrastructure/API/AddHostGroup/AddHostGroupSchemaSaas.json
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Serializer/HostGroupRelationNormalizer.php
  centreon/src/Core/HostGroup/Infrastructure/Voters/HostGroupVoters.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration.feature
  centreon/tests/php/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupTest.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupTestPresenterStub.php
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Category.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Group.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Notifications.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Resources_By_Parent_Monitoring.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Resources_Monitoring.postman_collection.json
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
Labels: area/backend, skip-workflow-web

#6883 Enh(Agent configuration): Allow sub-directory in certificate configuration
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a poller when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/fixtures/agents-configuration/agent-config.json
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui

#6903 fix(tests): synchronize tests with jira xray
  centreon/tests/e2e/features/Services-configuration/01-service-category-configuration.feature
  centreon/tests/e2e/features/Services-configuration/02-configurationWarnings.feature
  centreon/tests/e2e/features/Services-configuration/03-service-configuration.feature
  centreon/tests/e2e/features/Services-configuration/04-service-group-configuration.feature
  centreon/tests/e2e/features/Services-configuration/05-service-template-configuration.feature
  centreon/tests/e2e/features/Services-configuration/06-generate-service-contact.feature
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration.feature
  centreon/tests/e2e/features/Snmp-Traps/01-traps-snmp-configuration.feature
  centreon/tests/e2e/features/Time-Period/01-time-period-configuration.feature
Labels: area/test

#6900 enh(Custom Views): migrate the public custom views configuration behat test to a cypress test - 24.10
  centreon/behat.yml
  centreon/features/CustomViews/Public.feature
  centreon/tests/e2e/features/Custom-views/01-public.feature
  centreon/tests/e2e/features/Custom-views/01-public/index.ts
  centreon/tests/e2e/features/Custom-views/common.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/custom-view-acl-user.json
  centreon/tests/e2e/fixtures/users/custom-view-acl-user.json
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6901 enh(Custom Views): migrate the public custom views configuration behat test to a cypress test - 24.04
  centreon/behat.yml
  centreon/features/CustomViews/Public.feature
  centreon/tests/e2e/features/Custom-views/01-public.feature
  centreon/tests/e2e/features/Custom-views/01-public/index.ts
  centreon/tests/e2e/features/Custom-views/common.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/custom-view-acl-user.json
  centreon/tests/e2e/fixtures/users/custom-view-acl-user.json
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6894 enh(Custom Views): migrate the public custom views configuration behat test to a cypress test
  centreon/behat.yml
  centreon/features/CustomViews/Public.feature
  centreon/tests/e2e/features/Custom-views/01-public.feature
  centreon/tests/e2e/features/Custom-views/01-public/index.ts
  centreon/tests/e2e/features/Custom-views/common.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/custom-view-acl-user.json
  centreon/tests/e2e/fixtures/users/custom-view-acl-user.json
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6905 fix(ci): centreon-broker-cbmod does not exist anymore
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  centreon/packaging/centreon-poller.yaml
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#6816 enh(hostgroup): update UpdateHostGroup Endpoint
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/Schema/AddHostGroupRequest.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostGroups/Schema/FindAndUpdateHostGroup.yaml
  centreon/src/Core/HostGroup/Application/Repository/WriteHostGroupRepositoryInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroup.php
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroup.php
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupPresenterInterface.php
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupRequest.php
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupValidator.php
  centreon/src/Core/HostGroup/Domain/Model/HostGroup.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupController.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupInput.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupPresenter.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupRequestTransformer.php
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupSchemaOnPrem.json
  centreon/src/Core/HostGroup/Infrastructure/API/UpdateHostGroup/UpdateHostGroupSchemaSaas.json
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupActionLogRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbWriteHostGroupRepository.php
  centreon/src/Core/HostGroup/Infrastructure/Voters/HostGroupVoters.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Domain/Model/DatasetFilter/DatasetFilterRelation.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbRuleFactory.php
  centreon/src/Core/Security/AccessGroup/Application/Repository/WriteAccessGroupRepositoryInterface.php
  centreon/src/Core/Security/AccessGroup/Infrastructure/Repository/DbWriteAccessGroupRepository.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/fixtures/host-groups/host-group.json
  centreon/tests/php/Core/HostGroup/Application/UseCase/AddHostGroup/AddHostGroupTest.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupTest.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroupTestPresenterStub.php
  centreon/tests/rest_api/collections/configuration/Host_Group.postman_collection.json
Labels: area/backend, skip-workflow-web

#6898 enh(DOC)(SQL): add comments for service tables and their columns
  centreon/www/install/createTables.sql
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6906 MON-161740 Sync release hotfix 25.01.1
  .version.centreon-web
  centreon/www/install/php/Update-25.01.1.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#6902 enh(agent configuration): add prefix & extensions on existing AC values
  centreon/www/install/php/Update-next.php
Labels: area/backend

#6704 enh(RS): improve resource status queries
  centreon/src/Core/Resources/Application/UseCase/FindResourcesByParent/FindResourcesByParent.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-next.php
Labels: area/backend, database, skip-workflow-web, skip-workflow-web-analysis

#6931 enh(RS): improve resource status queries (#6704)
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbResourceFactoryTest.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-24.04.12.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6928 fix(upgrade): restore log upgrade management
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6904 fix(cloud): fix poller not visible in list after creation
  centreon/src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
  centreon/www/class/centreonACL.class.php
  centreon/www/include/configuration/configServers/DB-Func.php
  centreon/www/include/configuration/configServers/servers.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6921 Fix(Resource Status): Timeline period filter not properly applied (#6…
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6922 Fix(Resource Status): Timeline period filter not properly applied (#6…
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#6935 enh(RS): improve resource status queries (#6704) (#6931)
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbReadResourceRepositoryTest.php
  centreon/tests/php/Core/Resources/Infrastructure/Repository/DbResourceFactoryTest.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-24.04.12.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6953 chore(ci): update tj-actions/changed-files to 46.0.1 for branch dev-23.10.x
  .github/workflows/get-environment.yml
Labels: gha

#6954 chore(ci): update tj-actions/changed-files to 46.0.1 for branch dev-23.04.x
  .github/workflows/get-environment.yml
Labels: gha

#6934 enh(RS): improve resource status queries (#6704)
  centreon/src/Core/Resources/Application/UseCase/FindResourcesByParent/FindResourcesByParent.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-24.10.6.php
Labels: area/backend, skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis

#6950 chore(ci): update tj-actions/changed-files to 46.0.1 for branch develop
  .github/workflows/get-environment.yml
Labels: gha

#6952 chore(ci): update tj-actions/changed-files to 46.0.1 for branch dev-24.04.x
  .github/workflows/get-environment.yml
Labels: gha

#6936 fix FindHostGroup for non-admin
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
Labels: skip-workflow-web

#6939 enh(Custom Views): migrate the unlocked custom views configuration behat test to a cypress test - 24.10
  centreon/behat.yml
  centreon/features/CustomViews/Unlocked.feature
  centreon/tests/e2e/features/Custom-views/01-public/index.ts
  centreon/tests/e2e/features/Custom-views/02-unlocked.feature
  centreon/tests/e2e/features/Custom-views/02-unlocked/index.ts
  centreon/tests/e2e/features/Custom-views/common.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6940 enh(Custom Views): migrate the unlocked custom views configuration behat test to a cypress test - 24.04
  centreon/behat.yml
  centreon/features/CustomViews/Unlocked.feature
  centreon/tests/e2e/features/Custom-views/01-public/index.ts
  centreon/tests/e2e/features/Custom-views/02-unlocked.feature
  centreon/tests/e2e/features/Custom-views/02-unlocked/index.ts
  centreon/tests/e2e/features/Custom-views/common.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6968 [Dashboards][Public Playlists] - Graph widget shows multiple graph where it only has one from the web UI.
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useListMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/centreon-widget-topbottom/src/useTopBottom.ts
  centreon/www/widgets/src/utils.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6967 fix(resource status): restore flapping and percent state change in view by host query
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6959 chore(ci): update tj-actions/changed-files to 46.0.1 for branch 23.10.x
  .github/workflows/get-environment.yml
Labels: gha

#6958 chore(ci): update tj-actions/changed-files to 46.0.1 for branch 24.04.x
  .github/workflows/get-environment.yml
Labels: gha

#6960 chore(ci): update tj-actions/changed-files to 46.0.1 for branch 23.04.x
  .github/workflows/get-environment.yml
Labels: gha

#6962 chore(ci): update tj-actions/changed-files to 46.0.1 for branch release-25.03-next
  .github/workflows/get-environment.yml
Labels: gha, skip-cherry-pick

#6972 fix(Upgrade): fix cypres test
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-25.01.1.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6963 chore(ci): update tj-actions/changed-files to 46.0.1 for branch release-24.10-next
  .github/workflows/get-environment.yml
Labels: gha, skip-cherry-pick

#6964 chore(ci): update tj-actions/changed-files to 46.0.1 for branch release-24.04-next
  .github/workflows/get-environment.yml
Labels: gha, skip-cherry-pick

#6965 chore(ci): update tj-actions/changed-files to 46.0.1 for branch release-23.10-next
  .github/workflows/get-environment.yml
Labels: gha, skip-cherry-pick

#6976 Enh(Agent configuration): update the wording of certificate fields
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a poller when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays a welcome label when the listing is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- backs to the form when the Stay button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- discards the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- leaves the form when the Leave button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- leaves to the form when the Leave button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resolves the form when the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
  centreon/tests/e2e/features/Agent-configuration/04-agent-configuration-update/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui, skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-docker-vault, skip-workflow-docker-translation, skip-workflow-docker-keycloak, skip-workflow-docker-glpi

#6989 chore(newman) : Fix newman issue
  centreon/pnpm-lock.yaml
  centreon/pnpm-workspace.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#6997 fix(tests): fix open ticket configration test
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/pnpm-lock.yaml
Labels: skip-workflow-open-tickets, skip-workflow-open-tickets-analysis

#6999 fix(Upgrade): fix cypres test (#6972)
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-25.01.1.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#4883 fix(widget): the query filtering on service description
  centreon/www/widgets/grid-map/src/table.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7007 test(fix) Fix an e2e test failed on nightly
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
Labels: area/test

#7005 fix(downtimes): fix downtimes listing for users under ACLs
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7006 chore(packaging): remove packaging of centreon-common (#5835)
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  centreon/packaging/centreon-common-selinux.yaml
  centreon/packaging/centreon-common.yaml
  centreon/packaging/centreon-perl-libs.yaml
  centreon/packaging/centreon-poller.yaml
  centreon/packaging/centreon-web-selinux.yaml
  centreon/packaging/centreon-web.yaml
  centreon/packaging/scripts/centreon-common-postinstall.sh
  centreon/packaging/scripts/centreon-common-postremove.sh
  centreon/packaging/scripts/centreon-common-preinstall.sh
  centreon/packaging/scripts/centreon-common-preremove.sh
  centreon/packaging/scripts/centreon-common-selinux-postinstall.sh
  centreon/packaging/scripts/centreon-common-selinux-preremove.sh
  centreon/selinux/centreon-common.fc
  centreon/selinux/centreon-common.if
  centreon/selinux/centreon-common.te
  centreon/tmpl/install/systemd/centreon.systemd
  centreon/www/install/var/config.yaml
Labels: skip-workflow-docker-web-dependencies

#7015 fix(downtimes): fix downtimes listing for users under ACLs (#7005)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7014 fix(downtimes): fix downtimes listing for users under ACLs (#7005)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7016 fix(downtimes): fix downtimes listing for users under ACLs (#7005)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7012 fix(downtimes): fix downtimes listing for users under ACLs (#7005)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis

#7011 fix(downtimes): fix downtimes listing for users under ACLs (#7005)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis

#7029 test(HostTemplate): migrate host templates configuration behat test to a cypress test - 24.04
  centreon/behat.yml
  centreon/features/HostTemplateConfiguration.feature
  centreon/features/bootstrap/HostTemplateConfigurationContext.php
  centreon/tests/e2e/features/Hosts/09-host-template-configuration.feature
  centreon/tests/e2e/features/Hosts/09-host-template-configuration/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#7027 test(HostTemplate): migrate host templates configuration behat test to a cypress test - 24.10
  centreon/behat.yml
  centreon/features/HostTemplateConfiguration.feature
  centreon/features/bootstrap/HostTemplateConfigurationContext.php
  centreon/tests/e2e/features/Hosts/09-host-template-configuration.feature
  centreon/tests/e2e/features/Hosts/09-host-template-configuration/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#7040 chore(release) bump web 25.03.0
  .version.centreon-web
Labels: skip-cherry-pick

#7033 fix(nightly) downtimes test
  centreon/www/include/common/userTimezone.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7001 [MON-164061] Enable Symfony profiler by enabling routes and autorizing them in firewall
  centreon/config/packages/security.yaml
  centreon/config/routes/dev/web_profiler.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7035 [MON-164238] Enable Symfony profiler by enabling routes and autorizing them in firewall
  centreon/config/packages/security.yaml
  centreon/config/routes/dev/web_profiler.yaml
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#7036 [MON-164239] Enable Symfony profiler by enabling routes and autorizing them in firewall
  centreon/config/packages/security.yaml
  centreon/config/routes/dev/web_profiler.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7034 [MON-164240] Enable Symfony profiler by enabling routes and autorizing them in firewall
  centreon/config/packages/security.yaml
  centreon/config/routes/dev/web_profiler.yaml
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6977 fix(resource status): restore flapping and percent state change in view by host query (#6967)
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6974 enh(open-tickets): change rights on providers listing and update submit ticket ACL
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersPresenterInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-notification-permissions.json
  centreon-open-tickets/tests/e2e/fixtures/users/user-dashboard-administrator.json
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/install.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.01.1/php/upgrade.php
Labels: area/backend, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis

#7018 fix(widget): the query filtering on service description (#4883)
  centreon/www/widgets/grid-map/src/table.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#6986 fix(host template): fix edit host/ht in cloud
  centreon/doc/API/latest/Cloud/Configuration/Host/Schema/PartialUpdateHostRequest.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostSaasSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSaasSchema.json
Labels: skip-workflow-web, skip-workflow-web-analysis

#6919 enh(conf): new endpoint GetToken
  centreon/config/symfony_serializer/Token/Token.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Administration/Token/DeleteToken.yaml
  centreon/doc/API/latest/onPremise/Administration/Token/GetAndDeleteToken.yaml
  centreon/doc/API/latest/onPremise/Administration/Token/GetAndPartialUpdateAndDeleteTokenByUser.yaml
  centreon/src/Core/Security/Token/Application/Exception/TokenException.php
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Application/UseCase/GetToken/GetToken.php
  centreon/src/Core/Security/Token/Application/UseCase/GetToken/GetTokenResponse.php
  centreon/src/Core/Security/Token/Infrastructure/API/GetToken/GetTokenController.php
  centreon/src/Core/Security/Token/Infrastructure/API/GetToken/GetTokenRoute.yaml
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Core/Security/Token/Infrastructure/Serializer/TokenResponseNormalizer.php
  centreon/src/Core/Security/Token/Infrastructure/Voters/TokenVoters.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/GetToken/GetTokenTest.php
Labels: skip-workflow-web

#7046 enh(agent configuration): update export file to allow no tls
  centreon/www/class/config-generate/AgentConfiguration.php
Labels: skip-workflow-web

#6971 fix(API): Added handling of 401 Unauthorized Response (#6761)
  centreon/src/Centreon/Application/Controller/AbstractController.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7051 comment 02-platform-upgrade test
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade.feature
Labels: area/test

#7052 fix(META SERVICE): remake bounded values
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
Labels: area/backend, skip-workflow-web

#6961 fix(purge): make regexp compatible with mysql and mariadb
  centreon/www/class/centreonPurgeEngine.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis
