Repository centreon/centreon, pull requests merged in 2025-09, with the labels that each got.

#8094 fix(ldap): contacts with special chars shouldn't be imported more than once
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#6661 chore(Test Perf) : Adding performance testing
  .github/workflows/actionlint.yml
  .github/workflows/performance-testing.yml
  centreon/tests/performance/.env
  centreon/tests/performance/analyze_results.py
  centreon/tests/performance/cleaningUpData.mjs
  centreon/tests/performance/cleaningUpUsers.mjs
  centreon/tests/performance/config.mjs
  centreon/tests/performance/dbConfig.mjs
  centreon/tests/performance/deleteAllAddedRessources.mjs
  centreon/tests/performance/hostGroup.mjs
  centreon/tests/performance/hosts.mjs
  centreon/tests/performance/injectData.mjs
  centreon/tests/performance/injectingUsers.mjs
  centreon/tests/performance/jmeterFolder/resourceStatus.jmx
  centreon/tests/performance/metaServices.mjs
  centreon/tests/performance/package-lock.json
  centreon/tests/performance/package.json
  centreon/tests/performance/reloadAclApplyConfig.mjs
  centreon/tests/performance/serviceCategories.mjs
  centreon/tests/performance/serviceGroups.mjs
  centreon/tests/performance/services.mjs
  centreon/tests/performance/users.csv
Labels: area/test, ci, skip-workflow-web-analysis, qa-approved

#8138 Fix the flacky test 13-uri-configuration on nightly
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: skip-workflow-web-analysis

#8141 Fix the flacky test 13-uri-configuration on nightly - 24.04
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: area/test, backport, skip-workflow-web-analysis, qa-approved

#8140 Fix the flacky test 13-uri-configuration on nightly - 24.10
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: area/test, backport, skip-workflow-web-analysis, qa-approved

#8120 fix(configuration): fix error msg in export (#8089)
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7949 Enh(authentications tokens): Add welcome page
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/tests/e2e/features/Api-Token/01-api-token-create/index.ts
  centreon/www/front_src/src/AuthenticationTokens/Filters/PopoverFilter.tsx
  centreon/www/front_src/src/AuthenticationTokens/Filters/useCountChangedFilters.ts
  centreon/www/front_src/src/AuthenticationTokens/Listing/Listing.tsx
  centreon/www/front_src/src/AuthenticationTokens/Page.styles.ts
  centreon/www/front_src/src/AuthenticationTokens/Page.tsx
  centreon/www/front_src/src/AuthenticationTokens/Specs/initialize.tsx
  centreon/www/front_src/src/AuthenticationTokens/atoms.ts
  centreon/www/front_src/src/AuthenticationTokens/translatedLabels.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8117 fix(media): remove non-relevant condition on topology for media listing
  centreon/src/Core/Media/Application/UseCase/FindMedias/FindMedias.php
  centreon/tests/rest_api/collections/administration/Media.postman_collection.json
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8157 release-24.04-next conflict resolution on .po files
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis

#8102 fix(unattended): fix mysql default-authentication-plugin to mysql_native_password on versions 24.10 and below
  centreon/unattended.sh
Labels: skip-workflow-web, skip-workflow-web-analysis

#8109 fix(hostgroup):correctly escape hg name characters
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8133 fix(ldap): contacts with special chars shouldn't be imported more than once (#8094)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/ldapsearch.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8126 fix(conf) fix alias field in form (#8076)
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/form.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
Labels: skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8125 fix(conf) fix alias field in form (#8076)
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/form.php
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.ihtml
Labels: skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8158 Backport(authentications tokens): Add welcome page (#7949)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AuthenticationTokens/Specs/AuthenticationTokens.cypress.spec.tsx/CMA token form (before).snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/tests/e2e/features/Api-Token/01-api-token-create/index.ts
  centreon/www/front_src/src/AuthenticationTokens/Filters/PopoverFilter.tsx
  centreon/www/front_src/src/AuthenticationTokens/Filters/useCountChangedFilters.ts
  centreon/www/front_src/src/AuthenticationTokens/Listing/Listing.tsx
  centreon/www/front_src/src/AuthenticationTokens/Page.tsx
  centreon/www/front_src/src/AuthenticationTokens/Specs/initialize.tsx
  centreon/www/front_src/src/AuthenticationTokens/atoms.ts
  centreon/www/front_src/src/AuthenticationTokens/translatedLabels.ts
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8176 fix(clapi): Do not override engine-context.json rights during cfgMove
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8164 fix(cron) remove info logs, add error logs (#8030)
  centreon/cron/outdated-token-removal.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8165 fix(cron) remove info logs, add error logs (#8030)
  centreon/cron/outdated-token-removal.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8096 Poller is seen as not enable, so we can't generate the configuration files
  centreon/www/include/configuration/configServers/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8135 feat: add meta service query for single bar widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/Graph.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/api/endpoints.ts
Labels: skip-workflow-web

#7703 fix(ci): do not use remi repos on el8 (docker + unattended)
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/unattended.sh
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#8167 fix(ui): metrics tab not loading (#7807)
  centreon/www/front_src/src/Resources/Details/tabs/Metrics/Metrics.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Metrics/api/decoders.ts
  centreon/www/front_src/src/Resources/Details/tabs/Metrics/models.ts
  centreon/www/front_src/src/Resources/decoders.ts
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7603 enh(configuration): IP address must be address in pollers/remote servers
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/help.pot
  centreon/lang/messages.pot
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/PollerWizard/translatedLabels.ts
  centreon/www/include/configuration/configServers/formServers.php
  centreon/www/include/configuration/configServers/help.php
  centreon/www/include/configuration/configServers/listServers.php
  centreon/www/install/react_translation.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8166 Fix(Dashboard): playlist rotation fail not found after dashboard edit…
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useDashboardDetails.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8099 chore: remove tailwind packages
  centreon/packages/ui/package.json
  centreon/pnpm-lock.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8172 MON-182415 fix 24.10.x width resourcetable (#8033)
  centreon/www/widgets/src/centreon-widget-resourcestable/moduleFederation.json
Labels: skip-workflow-web, skip-workflow-web-analysis

#8103 fix(conf) FindHostCategories when using search parameters
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8119 fix(tokens): remove bad version condition for route accessibility
  centreon/src/Core/Security/Token/Infrastructure/API/GetToken/GetTokenRoute.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8222 fix(docker): skip mariadb maxscale repo
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/bullseye/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
Labels: skip-workflow-docker-web-dependencies

#8207 MON-183555 fix: use correct api in public playlist for widget batree (#8189)
  centreon/www/widgets/src/centreon-widget-batree/src/index.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8252 fix(router): don't load modules router on fresh install
  centreon/src/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatus.php
  centreon/src/Core/Common/Infrastructure/Routing/ModuleRouteLoader.php
  centreon/src/Core/Module/Infrastructure/ModuleInstallationVerifier.php
  centreon/src/Core/Platform/Domain/InstallationVerifierInterface.php
  centreon/src/Core/Platform/Infrastructure/CentreonInstallationVerifier.php
  centreon/tests/php/Core/Application/Platform/UseCase/FindInstallationStatus/FindInstallationStatusTest.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#8218 fix(tokens): remove bad version condition for route accessibility
  centreon/src/Core/Security/Token/Infrastructure/API/GetToken/GetTokenRoute.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8235 fix(hosts): add validation on host name for add/patch
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostValidationTest.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidationTest.php
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json.ignored
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8261 enh(kernel): add ad compilerpass for bam indicators registration
  centreon/src/App/Kernel.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8259 feat(plugins): Add an Endpoint to list plugins
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/Option/Option.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/Option/OptionName.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/Option/OptionValue.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/Plugin/Plugin.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/Plugin/PluginName.php
  centreon/src/App/MonitoringConfiguration/Domain/Exception/OptionDoesNotExistException.php
  centreon/src/App/MonitoringConfiguration/Domain/Repository/OptionRepository.php
  centreon/src/App/MonitoringConfiguration/Domain/Repository/PluginRepository.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/Resource/PluginResource.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ListPluginsProvider.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ResourcePluginTransformer.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/Dbal/DbalOptionRepository.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/Dbal/DbalOptionTransformer.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/FileSystem/FileSystemPluginRepository.php
  centreon/src/App/Shared/Domain/Exception/AggregateDoesNotExistException.php
  centreon/tests/php/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ListPluginsProviderTest.php
  centreon/tests/php/App/MonitoringConfiguration/Infrastructure/Dbal/DbalOptionRepositoryTest.php
Labels: skip-workflow-web

#8190 enh(ceip) update api token stat report
  centreon/www/class/centreonStatistics.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8200 fix(cron) fix agent-configuration stats reports
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/class/centreonStatistics.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8272 enh(kernel): add ad compilerpass for bam indicators registration (#8261)
  centreon/src/App/Kernel.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8266 fix(dsm): Correctly package sql files
  centreon-dsm/packaging/centreon-dsm-server.yaml
Labels: skip-workflow-dsm, skip-workflow-dsm-analysis

#8282 fix(dsm): Correctly package sql files
  centreon-dsm/packaging/centreon-dsm-server.yaml
Labels: backport, skip-workflow-dsm, skip-workflow-dsm-analysis

#8248 fix(Open ticket): Improve GlpiApiRest ticket opening (#7063)
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
Labels: area/backend, backport, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8289 Chore(release) Fix bakend lint #8287
  centreon/www/install/php/Update-25.07.2.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#8292 fix(nightly): backend-lint job fixed (cs-fixer) (#8287)
  centreon/www/install/php/Update-25.07.2.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#8294 fix(authentication): fix authentication by providers because of missing show_deprecated_custom_views key (#7796)
  centreon/doc/API/latest/onPremise/Configuration/Users/Schema/CurrentParameters.Get.yaml
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/SAML.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/WebSSO.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParameters.php
  centreon/src/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersResponse.php
  centreon/src/Core/User/Infrastructure/API/FindCurrentUserParameters/FindCurrentUserParametersPresenter.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/php/Core/User/Application/UseCase/FindCurrentUserParameters/FindCurrentUserParametersTest.php
  centreon/tests/rest_api/collections/configuration/Contact_with_Open_API.postman_collection.json
Labels: skip-workflow-web, skip-workflow-web-analysis

#8210 fix(hostgroup): correctly check illegal characters when editing hostgroup name
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8293 fix(custom views): remove deprecation message (#8263)
  centreon/www/include/home/customViews/index.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8288 feat(macros): Add an Endpoint to list Standard Macros
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/StandardMacro/StandardMacro.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/StandardMacro/StandardMacroId.php
  centreon/src/App/MonitoringConfiguration/Domain/Aggregate/StandardMacro/StandardMacroName.php
  centreon/src/App/MonitoringConfiguration/Domain/Repository/Criteria/StandardMacroCriteria.php
  centreon/src/App/MonitoringConfiguration/Domain/Repository/StandardMacroRepository.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/Resource/StandardMacroResource.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ListStandardMacrosProvider.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ResourceStandardMacroTransformer.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/Dbal/DbalStandardMacroRepository.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/Dbal/DbalStandardMacroTransformer.php
  centreon/src/App/MonitoringConfiguration/Infrastructure/FileSystem/FileSystemPluginRepository.php
  centreon/tests/php/App/MonitoringConfiguration/Infrastructure/ApiPlatform/State/ListStandardMacrosProviderTest.php
  centreon/tests/php/App/MonitoringConfiguration/Infrastructure/Dbal/DbalOptionRepositoryTest.php
  centreon/tests/php/App/MonitoringConfiguration/Infrastructure/Dbal/DbalStandardMacroRepositoryTest.php
  centreon/www/install/insertMacros.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web

#8298 fix(ui): graph does not display
  centreon/packages/ui/src/Graph/Chart/index.tsx
Labels: area/ui, skip-workflow-web-analysis, qa-approved

#8290 fix(Open tickets): remove unnecessary condition in the query to get closable tickets (#7279)
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/ajax/actions/closeTicket.php
  centreon/src/Adaptation/Database/Connection/Trait/ConnectionTrait.php
Labels: backport, skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis, qa-approved

#8280 enh(ceip) update api token stat report (#8190)
  centreon/www/class/centreonStatistics.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8268 fix(host): signal config change while deploying services (#8121)
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8302 enh(contact): disable password fields if the user connected use an authentication provider
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8299 enh(contact): disable password fields if the user connected use an authentication provider
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8211 enh(logger/security): new logger from monolog added and password changes are monitored in a dedicated file
  .github/workflows/web.yml
  centreon/composer.json
  centreon/config.new/packages/monolog.yaml
  centreon/lib/Centreon/Object/Contact/Contact.php
  centreon/logrotate/centreon
  centreon/src/Adaptation/Log/Adapter/MonologAdapter.php
  centreon/src/Adaptation/Log/Enum/LogChannelEnum.php
  centreon/src/Adaptation/Log/Exception/LoggerException.php
  centreon/src/Adaptation/Log/Logger.php
  centreon/src/Adaptation/Log/LoggerPassword.php
  centreon/www/class/centreonContact.class.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8297 Remove not empty string assertion from TinyHost
  centreon/src/Core/Host/Domain/Model/TinyHost.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8321 enh(logger/security): new logger from monolog added and password changes are monitored in a dedicated file
  centreon/lib/Centreon/Object/Contact/Contact.php
  centreon/logrotate/centreon
  centreon/phpstan.core.neon
  centreon/src/Adaptation/Log/Adapter/MonologAdapter.php
  centreon/src/Adaptation/Log/Enum/LogChannelEnum.php
  centreon/src/Adaptation/Log/Exception/LoggerException.php
  centreon/src/Adaptation/Log/Logger.php
  centreon/src/Adaptation/Log/LoggerPassword.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8332 fix(Meta Service): cannot disable metaservice on forms
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8333 fix(Administration): display correct name for meta-services in Monito… (#8250)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8286 fix(hosts): add validation on host name for add/patch (#8235)
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostValidationTest.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidationTest.php
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json.ignored
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8347 MON-182400 Sync release 24.04 release onto dev-24.04.x
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/ApiTokens/index.tsx
  centreon/www/install/php/Update-24.04.17.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#8300 fix(hostgroup): correctly check illegal characters when editing hostgroup
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8244 fix(web): Prevent PHP warning when exporting poller configuration
  centreon/www/include/configuration/configGenerate/xml/generateFiles.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
  centreon/www/include/configuration/configGenerate/xml/restartPollers.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8340 enh(installer) handle delimiter in sql module installation
  centreon/src/CentreonLegacy/Core/Utils/Utils.php
  centreon/www/install/steps/process/createDbUser.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8329 enh(logger/security): new logger from monolog added and password changes are monitored in a dedicated file
  centreon/lib/Centreon/Object/Contact/Contact.php
  centreon/logrotate/centreon
  centreon/phpstan.core.neon
  centreon/src/Adaptation/Log/Adapter/MonologAdapter.php
  centreon/src/Adaptation/Log/Enum/LogChannelEnum.php
  centreon/src/Adaptation/Log/Exception/LoggerException.php
  centreon/src/Adaptation/Log/Logger.php
  centreon/src/Adaptation/Log/LoggerPassword.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8330 enh(logger/security): new logger from monolog added and password changes are monitored in a dedicated file
  centreon/lib/Centreon/Object/Contact/Contact.php
  centreon/logrotate/centreon
  centreon/phpstan.core.neon
  centreon/src/Adaptation/Log/Adapter/MonologAdapter.php
  centreon/src/Adaptation/Log/Enum/LogChannelEnum.php
  centreon/src/Adaptation/Log/Exception/LoggerException.php
  centreon/src/Adaptation/Log/Logger.php
  centreon/src/Adaptation/Log/LoggerPassword.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8255 fix(reccurentdowntime): Remove unneeded stripping of dangerous tags in listing
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8356 fix(Meta Service): cannot disable metaservice on forms (#8332)
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8363 fix(module) fix module install with delimiter use
  centreon/src/CentreonLegacy/Core/Utils/Utils.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8372 fix(dsm): Correctly escape properties for html in listing
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/listSlot.ihtml
Labels: backport, skip-workflow-dsm, skip-workflow-dsm-analysis, qa-approved

#8371 fix(dsm): Correctly escape properties for html in listing
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/listSlot.ihtml
Labels: backport, skip-workflow-dsm, skip-workflow-dsm-analysis, qa-approved

#8358 fix(downtime): correctly display 'services' for all kind of object (#8345)
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8386 fix(host): Do not escape the <a> tag(s) for the host template
  centreon/www/include/configuration/configObject/host/listHost.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8388 fix(cron): Do not trust web input in shell commands run from centreon-backup.pl
  centreon/cron/centreon-backup.pl
  centreon/packaging/centreon-web.yaml
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#8390 fix(cron): Do not trust web input in shell commands run from centreon-backup.pl
  centreon/cron/centreon-backup.pl
  centreon/packaging/centreon.spectemplate
  centreon/packaging/debian/control
Labels: backport, skip-workflow-web, skip-workflow-web-analysis
