Repository centreon/centreon, pull requests merged in 2025-06, with the labels that each got.

#7439 fix(cron): run outdated tokens removal cron with apache user
  centreon/packaging/centreon.spectemplate
  centreon/tmpl/install/centreon.cron
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis

#7465 fix(cron): run outdated tokens removal cron with apache user (#7439)
  centreon/packaging/centreon.spectemplate
  centreon/tmpl/install/centreon.cron
Labels: skip-workflow-web, skip-workflow-web-analysis

#7459 fix(UI): Fix detection by browser for a contact (#7402)
  centreon/packages/ui-context/src/browserLocaleAtom.ts
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/TimePeriods/CustomTimePeriod/PopoverCustomTimePeriod/PickersStartEndDate.tsx
  centreon/packages/ui/src/TimePeriods/DateTimePickerInput.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/useLocale/index.ts
  centreon/packages/ui/src/utils/useLocale/useLocale.cypress.spec.tsx
  centreon/packages/ui/src/utils/useLocaleDateTimeFormat/index.ts
  centreon/packages/ui/src/utils/usePluralizedTranslation.ts
  centreon/src/Centreon/Application/Webservice/CentreonI18n.php
  centreon/src/Centreon/Domain/Service/I18nService.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/e2e/features/Authentication/OpenID-connect/04-oidc-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/SAML/03-saml-authentication-auto-import/index.ts
  centreon/www/front_src/src/App/endpoint.ts
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/AuthenticationTokens/Modal/Form/TokenField/TokenField.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/front_src/src/Header/Clock/index.tsx
  centreon/www/front_src/src/Header/Poller/usePollerData.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
  centreon/www/front_src/src/Main/useInitializeTranslation.ts
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/Main/utils.ts
  centreon/www/front_src/src/api/decoders.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/Legend/Legend.tsx
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7460 fix(UI): Fix detection by browser for a contact (#7402)
  centreon/packages/ui-context/src/browserLocaleAtom.ts
  centreon/packages/ui-context/src/defaults.ts
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui/src/TimePeriods/CustomTimePeriod/PopoverCustomTimePeriod/PickersStartEndDate.tsx
  centreon/packages/ui/src/TimePeriods/DateTimePickerInput.tsx
  centreon/packages/ui/src/utils/index.ts
  centreon/packages/ui/src/utils/useLocale/index.ts
  centreon/packages/ui/src/utils/useLocale/useLocale.cypress.spec.tsx
  centreon/packages/ui/src/utils/useLocaleDateTimeFormat/index.ts
  centreon/packages/ui/src/utils/usePluralizedTranslation.ts
  centreon/src/Centreon/Application/Webservice/CentreonI18n.php
  centreon/src/Centreon/Domain/Service/I18nService.php
  centreon/src/EventSubscriber/CentreonEventSubscriber.php
  centreon/tests/e2e/features/Authentication/OpenID-connect/04-oidc-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/SAML/03-saml-authentication-auto-import/index.ts
  centreon/www/front_src/src/App/endpoint.ts
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/front_src/src/Header/Clock/index.tsx
  centreon/www/front_src/src/Header/Poller/usePollerData.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
  centreon/www/front_src/src/Main/useInitializeTranslation.ts
  centreon/www/front_src/src/Main/useUser.ts
  centreon/www/front_src/src/Main/utils.ts
  centreon/www/front_src/src/api/decoders.ts
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7458 fix: display down icon (#7394)
  centreon/cypress/fixtures/resources/listing/listingWithInDowntimeAndAck.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays a Down icon when the parent status is null.snap.png
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/Parent.tsx
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7450 fix(Host templates): fix error on mass change
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7454 fix(contacts): Add missing field (#7418)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7480 fix(Host templates): fix error on mass change (#7450)
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7481 fix(Host templates): fix error on mass change (#7450)
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7483 fix(ui): issues on unused component
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend in list mode when the corresponding props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays lines with a custom line width when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays only one line with custom style when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows points when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows the area when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- changes the unit on the left or right scales when a new unit is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays additional lines when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars when a line and a bar are customized.snap.png
  centreon/packages/ui/src/Button/Save/index.stories.tsx
  centreon/packages/ui/src/Colors/index.tsx
  centreon/packages/ui/src/Dialog/UnsavedChanges/index.stories.tsx
  centreon/packages/ui/src/ListingPage/index.stories.tsx
  centreon/packages/ui/src/MultiSelectEntries/index.stories.tsx
  centreon/packages/ui/src/MultiSelectEntries/index.tsx
  centreon/packages/ui/src/SortableItems/index.stories.tsx
  centreon/packages/ui/src/components/CrudPage/CrudPage.stories.tsx
  centreon/packages/ui/src/components/DataTable/DataTable.stories.tsx
  centreon/packages/ui/src/components/DataTable/EmptyState/DataTableEmptyState.stories.tsx
  centreon/packages/ui/src/components/DataTable/Item/DataTableItem.stories.tsx
  centreon/packages/ui/src/components/Form/AccessRights/AccessRights.stories.tsx
  centreon/packages/ui/src/components/Layout/AreaIndicator.tsx
  centreon/packages/ui/src/components/Layout/PageLayout/PageLayout.stories.tsx
  centreon/packages/ui/src/components/Modal/ConfirmationModal/ConfirmationModal.stories.tsx
  centreon/packages/ui/src/components/Modal/Modal.stories.tsx
  centreon/packages/ui/src/components/Tabs/Tabs.tsx
Labels: area/ui, skip-workflow-web-analysis, qa-approved

#7401 feat(tests): Adding E2E test form export csv feature
  centreon/packages/js-config/cypress/e2e/tasks.ts
  centreon/tests/e2e/features/Resources-status/07-csv-export.feature
  centreon/tests/e2e/features/Resources-status/07-csv-export/index.ts
  centreon/tests/e2e/features/Resources-status/commands.ts
  centreon/tests/e2e/fixtures/resources/csvFIleWithAllPagesAndColumns.json
  centreon/tests/e2e/fixtures/resources/csvFIleWithOnlyVisiblePagesAndColumns.json
Labels: area/test, skip-workflow-web-analysis

#7476 fix(HA): Update 10-centreon-ha.yaml to integrate token removal (#6219)
  centreon-ha/etc/centreon-gorgone/config.d/cron.d/10-centreon-ha.yaml
Labels: area/backend, qa-approved

#7475 fix(HA): Update 10-centreon-ha.yaml to integrate token removal (#6219)
  centreon-ha/etc/centreon-gorgone/config.d/cron.d/10-centreon-ha.yaml
Labels: area/backend, qa-approved

#7502 enh(cfg) change centengine export when poller version is < 25.05 (#7468)
  centreon/www/class/config-generate/engine.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7517 fix: lighthouse
  centreon/lighthouse/package.json
  centreon/pnpm-lock.yaml
Labels: skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis

#7518 fix: lighthouse
  centreon/lighthouse/package.json
  centreon/pnpm-lock.yaml
Labels: skip-workflow-web-analysis

#7306 enh(PAC) handle cma tokens in Agent configration for reverse connection
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
Labels: skip-workflow-docker-translation

#7531 Enh(Agent configuration): certificate fields are no more required
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
Labels: area/ui

#7445 fix(Host Categories): enh queries, and refactoring code (#7383)
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/www/include/common/sqlCommonFunction.php
  centreon/www/include/configuration/configObject/escalation/escalation.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
  centreon/www/include/configuration/configObject/host_categories/hostCategories.php
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7470 fix(Host Dependency): enh queries, and refactoring code (#7407)
  centreon/www/include/configuration/configObject/host_dependency/DB-Func.php
  centreon/www/include/configuration/configObject/host_dependency/formHostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/hostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7512 fix(Poller): rework access condition (#7404)
  centreon/www/include/configuration/configGenerate/xml/generateFiles.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7511 fix(Poller): rework access condition (#7404)
  centreon/www/include/configuration/configGenerate/xml/generateFiles.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7537 enh(ci): add sync-deletes option to debian delivery
  .github/actions/deb-delivery/action.yml
Labels: skip-workflow-awie, skip-workflow-awie-analysis

#7546 fix(chore): run lighthouse
  centreon/lighthouse/package.json
  centreon/pnpm-lock.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7551 fix(remote): correctly compute class name in config remote generation proccess (#7543) (#7553)
  centreon/www/class/config-generate-remote/Generate.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7572 chore(release) add php 23.10.24 and bump web 23.10.25
  .version.centreon-web
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.24.php
  centreon/www/install/php/Update-23.10.25.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7501 enh(PAC): save selected hosts (#7304)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- handle the form without certificate fields when setting encryption level to No TLS for CMA agent.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- send a Post request with certificate fields when connection mode is insecure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends an update request with certificate fields when connection mode is insecure.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AgentConfiguration/Application/Exception/AgentConfigurationException.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/Validator.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationResponse.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/Validator.php
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/Serializer/FindAgentConfigurationResponseNormalizer.php
  centreon/src/Core/Host/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/06-agent-configuration-tls-mode/index.ts
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/class/config-generate/generate.class.php
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfigurationsStyle.ts
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7524 fix(escalation): refactor escalation listing query (#7473)
  centreon/www/include/configuration/configObject/escalation/formEscalation.php
  centreon/www/include/configuration/configObject/escalation/listEscalation.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7554 fix: graph static margins
  centreon/www/front_src/src/Resources/Graph/Performance/Graph/index.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#7510 fix(ci): detect PR requested team from timeline
  .github/workflows/check-qa-validation.yml
Labels: skip-workflow-web-analysis

#7548 fix(widgets): Servicegroup monitoring no data returned for users (non…
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend

#7471 fix(Host Dependency): enh queries, and refactoring code (#7407)
  centreon/www/include/configuration/configObject/host_dependency/DB-Func.php
  centreon/www/include/configuration/configObject/host_dependency/formHostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/hostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7505 enh(pollers): set enable_flap_detection & host_down_disable_service_checks to true
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
  centreon/www/class/centreon-config/centreonMainCfg.class.php
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7581 MON-172467 Hotfix web 23.04
  .version.centreon-web
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/lighthouse/package.json
  centreon/pnpm-lock.yaml
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.29.php
  centreon/www/install/php/Update-23.04.30.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7575 MON-172468 Hotfix 23.10 WEB
  .version.centreon-web
  centreon/lighthouse/package.json
  centreon/pnpm-lock.yaml
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.24.php
  centreon/www/install/php/Update-23.10.25.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7434 Enh(ACC) Handle unique vCenter/ESX names
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useFormInitialValues.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Parameters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/useParameters.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/utils.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7525 fix(escalation): refactor escalation listing query (#7473)
  centreon/www/include/configuration/configObject/escalation/formEscalation.php
  centreon/www/include/configuration/configObject/escalation/listEscalation.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7493 fix(contact template): refactor contact template form queries
  centreon/www/include/configuration/configObject/contact_template_model/contact_template.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7536 fix(Resource Status): ACK & DT default options are not used for non-a…
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/tests/rest_api/collections/administration/Parameters.postman_collection.json
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7588 fix(conf) check if service has check command defined is now recursive on herited templates
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7611 fix(ci): avoid to remove translations and fix order
  .github/scripts/translation/make_translation.sh
  .github/workflows/web.yml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis, update-translations

#7607 fix(conf) check if service has check command defined is now recursive on herited templates (#7588)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7609 fix(conf) check if service has check command defined is now recursive on herited templates (#7588)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7606 fix(contact template): refactor contact template form queries (#7493)
  centreon/www/include/configuration/configObject/contact_template_model/contact_template.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7621 MON-172895 change warning color
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.cypress.spec.tsx/WidgetTextField -- displays the text field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard with complex layout -- displays a new widget in the correct position when a widget is added.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Acknowledgement -- sends an acknowledgement request when a host is selected and the Acknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Acknowledgement -- sends an acknowledgement request with updated parameters when a host is selected and the Acknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Check -- sends a check request when a resource is selected and the forced check actions is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Check -- sends a forced check request when a resource is selected and the forced check actions is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Disacknowledgement -- does not open the modal when the user has no ACL, a service is selected and the Disacknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Disacknowledgement -- sends a disacknowledgement request when a service is selected and the Disacknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Disacknowledgement -- sends a disacknowledgement request with services disacknowledgement when a host is selected and the Disacknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Disacknowledgement -- sends a disacknowledgement request without services disacknowledgement when a host is selected and the Disacknowledge action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Downtime -- cannot send a downtime request when Downtime action is clicked and start date is greater than end date.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Downtime -- sends a downtime request when Downtime action is clicked and the downtime form in saved.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- Downtime -- sends a downtime request when Downtime action is clicked and the downtime form is updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/Actions -- sends a submit status request when a Resource is selected and the Submit status action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/CSV export -- display the warning message when the number of resources exceeds 10,000.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/CSV export -- export resources with custom checks when clicking the CSV export button.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Actions/Actions.cypress.spec.tsx/CSV export -- export resources with default checks when clicking the CSV export button.snap.png
  centreon/package.json
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/packages/ui/src/ThemeProvider/tailwindcss.css
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Inputs.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/properties.json
  centreon/www/front_src/src/Resources/Actions/exportToCsv/Warning.tsx
  centreon/www/front_src/src/Resources/Actions/exportToCsv/exportCsv.styles.ts
  centreon/www/front_src/src/Resources/Listing/columns/Parent.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7605 fix(contact template): refactor contact template form queries (#7493)
  centreon/www/include/configuration/configObject/contact_template_model/contact_template.php
  centreon/www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7555 chore(Symfony): Remove deprecations and prepare to bump to symfony/console ^7.0
  centreon/src/Core/Command/Infrastructure/Command/MigrateAllCommands/MigrateAllCommandsCommand.php
  centreon/src/Core/Media/Infrastructure/Command/MigrateAllMedias/MigrateAllMediasCommand.php
  centreon/src/Core/Security/Vault/Infrastructure/Command/MigrateAllCredentials/MigrateAllCredentialsCommand.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7625 fix(ci): add default location to allow external tool usage
  .github/scripts/translation/make_translation.sh
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis, update-translations

#7612 fix(ci): avoid to remove translations and fix order
  .github/scripts/translation/make_translation.sh
  .github/workflows/web.yml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis, update-translations

#7598 fix(configuration): error on clicking check command help btn
  centreon/www/include/configuration/configObject/command/minHelpCommandFunctions.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7513 fix(ui): thresholds display on single metric
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays lines with a custom line width when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays only one line with custom style when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows points when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows the area when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- changes the unit on the left or right scales when a new unit is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays additional lines when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars when a line and a bar are customized.snap.png
  centreon/packages/ui/src/Graph/SingleBar/ResponsiveSingleBar.tsx
  centreon/packages/ui/src/Graph/Text/Text.styles.ts
  centreon/packages/ui/src/Graph/Text/Text.tsx
  centreon/packages/ui/src/Graph/index.ts
  centreon/packages/ui/src/components/Tabs/Tabs.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/SingleMetricRenderer.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7599 fix(UI): Clock widget is broken
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- displays the time in the corresponding timezone and time format when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- displays the widget when the user local is null.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- displays the widget with a custom background color and a description when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- displays the widget with default properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- displays the widget with small width.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Clock -- does not display the date and timezone when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Timer -- displays days when the ends date is far away.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Timer -- displays the widget with default properties.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Timer -- does not display remaining time when the countdown is invalid.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx/Clock-Timer -- Timer -- does not display the date and timezone when corresponding props are set.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/spec/Clock.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/useGetLocaleAndTimezone.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7535 feat(custom views): Deprecated Custom Views
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Domain/Contact/Interfaces/ContactInterface.php
  centreon/src/Centreon/Domain/Repository/TopologyRepository.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/www/class/centreonUser.class.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/home/customViews/index.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7610 fix(conf) check if service has check command defined is now recursive on herited templates (#7588)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7488 enh(cfg) bbdo version to 3.1 in engine cfg
  centreon/www/include/configuration/configCentreonBroker/formCentreonBroker.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7583 [Symfony 7][HttpKernel] Remove deprecation
  centreon/src/Core/Infrastructure/Common/Api/Router.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7560 [dev-24.04.x] Add missing idempotent migration on 23.10.4
  centreon/www/install/php/Update-23.10.8.php
Labels: skip-workflow-web-analysis, qa-approved

#7613 fix(conf) check if service has check command defined is now recursive on herited templates (#7588)
  centreon/www/include/configuration/configObject/service/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7582 [Symfony7][FrameworkExtraBundle] remove bundle
  centreon/composer.json
  centreon/composer.lock
  centreon/config/bundles.php
  centreon/config/packages/fos_rest.yaml
  centreon/config/packages/sensio_framework_extra.yaml
  centreon/config/services.yaml
  centreon/src/Core/Media/Infrastructure/API/AddMedia/AddMediaController.php
  centreon/src/Core/Media/Infrastructure/API/UpdateMedia/UpdateMediaController.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7532 fix(dashboard): regex with services to get performance metrics fixed
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/Dashboard.MetricsPerformances.yaml
  centreon/phpstan.core.neon
  centreon/src/Centreon/Domain/RequestParameters/Interfaces/RequestParametersInterface.php
  centreon/src/Centreon/Domain/RequestParameters/RequestParameters.php
  centreon/src/Core/Dashboard/Application/Repository/ReadDashboardPerformanceMetricRepositoryInterface.php
  centreon/src/Core/Dashboard/Application/UseCase/FindMetricsTop/FindMetricsTop.php
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetrics/FindPerformanceMetrics.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindMetricsTop/FindMetricsTopPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetrics/FindPerformanceMetricsPresenter.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardPerformanceMetricRepository.php
Labels: bug, area/backend, skip-workflow-web

#7533 enh(PAC) handle cma tokens in Agent configuration for reverse connection
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/Schema/CmaConfigurationSchema.json
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/CMATokenField.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfigurations.ts
  centreon/www/front_src/src/AgentConfiguration/Form/RedirectToTokensPage.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/api/endpoints.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui, area/backend, upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7651 fix(export) default centengine.cfg file version is legacy
  centreon/www/class/config-generate/engine.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7624 chore(release) bump oss 23.10 July 2025
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-web
  centreon-dsm/www/modules/centreon-dsm/conf.php
  centreon-dsm/www/modules/centreon-dsm/upgrade/23.10.4/.gitignore
  centreon-ha/.env
  centreon-ha/CHANGELOG.md
  centreon/www/install/insertBaseConf.sql
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/configs.xml
Labels: qa-approved

#7645 Backport([dev-24.04.x] - [Resource Status]): Can't select multiples Host group with the filter menu
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By host -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx/Criterias, view by By service -- synchronize the search bar with Basic criterias interface when selecting Host group criteria value.snap.png
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7636 fix(Resource Status): ACK & DT default options are not used for non-a… #7536
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/tests/rest_api/collections/authentication/02-Local-Authentication.postman_collection.json
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7674 fix(E2E): fix status chart E2E test
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
Labels: skip-workflow-web-analysis

#7637 fix(dashboard): contact search by name in sharing process
  centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContacts/FindDashboardContacts.php
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7679 fix(update): update files fixed
  centreon/www/install/php/Update-24.10.9.php
  centreon/www/install/php/Update-next.php
Labels: bug, area/backend, skip-workflow-web

#7676 chore(release) Bump oss 24.10 july2025
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-web
  centreon-dsm/www/modules/centreon-dsm/conf.php
  centreon-dsm/www/modules/centreon-dsm/upgrade/24.10.2/.gitignore
  centreon-ha/.env
  centreon-ha/CHANGELOG.md
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.9.php
  centreon/www/install/php/Update-next.php
Labels: qa-approved

#7648 Enh(ACC) Handle unique vCenter/ESX names (#7434)
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Form/useFormInitialValues.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/Parameters.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Modal/Parameters/useParameters.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/AdditionalConnectorConfiguration/utils.ts
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7680 enh(e2e) Fix Agent configuration flacky test on bookworm
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
Labels: skip-workflow-web-analysis

#7684 test(e2e): Ignore large volume Notification Rule scenario in Cloud no…
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
Labels: skip-workflow-web-analysis

#6256 enh(widgets): improve visibility of values in Global Health and Top 10 widgets
  centreon/www/widgets/global-health/src/global_health_host.ihtml
  centreon/www/widgets/global-health/src/global_health_service.ihtml
  centreon/www/widgets/live-top10-cpu-usage/index.php
  centreon/www/widgets/live-top10-cpu-usage/src/table_top10cpu.ihtml
  centreon/www/widgets/live-top10-memory-usage/index.php
  centreon/www/widgets/live-top10-memory-usage/src/table_top10memory.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7668 fix(LDAP): user with no mail cannot authenticate on Centreon with LDA…
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7692 enh(packaging): package console.new
  centreon/packaging/centreon-web.yaml
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#7681 Fix a HTTP 500 error on view by host when there are no metrics
  centreon/src/Core/Resources/Infrastructure/API/FindResourcesByParent/FindResourcesByParentPresenter.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7541 enh(conf) set is_service_account flag for centreon-gorgone user
  centreon/www/install/createTables.sql
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7700 fix(E2E): fix status chart & cloud notif E2E test
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
Labels: qa-approved

#7545 feat(docker): register automatically authentication providers
  .github/docker/README.md
  .github/docker/centreon-web/alma8/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/72-authentication.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/72-authentication.sh
  .github/docker/docker-compose.yml
  .gitleaks.toml
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/packages/js-config/cypress/e2e/tasks.ts
  centreon/tests/e2e/cypress.config.ts
  centreon/tests/e2e/cypress.dev.config.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/01-oidc-authentication/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/04-oidc-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/05-oidc-authentication-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/06-oidc-authentication-contact-groups/index.ts
  centreon/tests/e2e/features/Authentication/OpenID-connect/common.ts
  centreon/tests/e2e/features/Authentication/SAML/01-saml-authentication/index.ts
  centreon/tests/e2e/features/Authentication/SAML/02-saml-authentication-only/index.ts
  centreon/tests/e2e/features/Authentication/SAML/03-saml-authentication-auto-import/index.ts
  centreon/tests/e2e/features/Authentication/SAML/04-saml-authentication-contact-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/05-saml-authentication-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/06-saml-authentication-first-acl-groups/index.ts
  centreon/tests/e2e/features/Authentication/SAML/07-saml-authentication-restrictions/index.ts
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/e2e/fixtures/resources/clapi/config-ACL/provider-acl.json
  centreon/tests/e2e/support/commands.ts
Labels: system, skip-workflow-web, skip-workflow-web-analysis

#7699 Mark 23.04 API doc as deprecated as version is EOL
  centreon/doc/API/centreon-api-v23.04.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7469 chore(deps): absorb 2025-06 dependabot GitHub Actions updates
  .github/actions/cypress-e2e-testing/action.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: dependencies, gha
