Repository centreon/centreon, pull requests merged in 2025-02, with the labels that each got.

#5071 fix(dashboard): do not take into account UNDETERMINED days in calculation
  centreon/www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_HostLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Labels: area/backend, skip-workflow-web

#6340 enh(conf): call PUT endpoint to update hostgroup in form
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6451 Fix(UI): Retrieve services names on filter
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/api/endpoint.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
Labels: backport, skip-workflow-web

#6565 chore(deps): absorb 2025-02 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/lighthouse-to-s3/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/behat-test.yml
  .github/workflows/clean-npm-tags.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#6440 Fix(UI): Fix zoom button listeners
  centreon/packages/ui/src/components/Zoom/useMinimap.ts
  centreon/packages/ui/src/components/Zoom/useZoom.ts
Labels: area/ui

#6553 fix(cron): run outdated tokens removal cron with apache user (#6545)
  centreon/packaging/scripts/centreon-web-postinstall.sh
  centreon/tmpl/install/centreon.cron
Labels: skip-workflow-web, skip-workflow-web-analysis

#6528 fix(host categories): fix SQL Query to search host categories
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
Labels: area/backend, skip-workflow-web

#6552 fix(cron): run outdated tokens removal cron with apache user (#6545)
  centreon/packaging/scripts/centreon-web-postinstall.sh
  centreon/tmpl/install/centreon.cron
Labels: skip-workflow-web, skip-workflow-web-analysis

#6573 fix(Events Log): fix events logs refacto
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#5627 fix unprecise query when looking for lua password param value
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6578 fix(cron): run outdated tokens removal cron with apache user (#6545)
  centreon/packaging/scripts/centreon-web-postinstall.sh
  centreon/tmpl/install/centreon.cron
Labels: skip-workflow-web

#6490 enh(ceip): send agent information data to CEIP
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-25.03.0.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6530 fix(Configuration): ACL aren't affected to a hostgroup when it's created by a non-admin user (#6348) [dev-24.04.x]
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/hostgroup/listHostGroup.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6551 fix(update-24.10.x) : fix update files for 24.10
  centreon/www/install/php/Update-24.10.1.php
  centreon/www/install/php/Update-24.10.2.php
  centreon/www/install/php/Update-24.10.3.php
  centreon/www/install/php/Update-24.10.4.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis

#6314 enh(host groups): call API for hostGroup deletion in form
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/hostGroup.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6550 enh (command): migrate the command arguments behat test to a cypress test
  centreon/behat.yml
  centreon/features/CommandArguments.feature
  centreon/features/bootstrap/CommandArgumentsContext.php
  centreon/tests/e2e/features/Commands/01-commands-configuration.feature
  centreon/tests/e2e/features/Commands/01-commands-configuration/index.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6580 fix(Events Log): fix events logs refacto (#6573)
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6572 fix(top counter): refresh intervals for the top counters have no effect
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/statisticsRefreshIntervalAtom.ts
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#6459 Fix([Dashboard]): Double-clicking the "Favorites" button causes errors and inconsistent behavior
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardCardActions/DashboardCardActions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/favoriteAction/FavoriteAction.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/Actions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#6588 mon-156694 Sync hotfix 24.11.1 OSS to release branch
  centreon/www/install/php/Update-24.11.1.php
Labels: skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis

#6597 MON-156694 Sync develop after hotfix 24.11.1
  centreon/www/install/php/Update-24.11.1.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6570 fix(dashboard): do not take into account UNDETERMINED days in calcula…
  centreon/www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_HostLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6250 fix(cron) Remove duplicate function in the cron outdated-token-removal.php on Centreon 24.04
  centreon/cron/outdated-token-removal.php
Labels: skip-workflow-web

#6542 enh (command): migrate the configuration of the command behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/CommandConfiguration.feature
  centreon/features/bootstrap/CommandConfigurationContext.php
  centreon/tests/e2e/features/Commands/01-commands-configuration.feature
  centreon/tests/e2e/features/Commands/01-commands-configuration/index.ts
  centreon/tests/e2e/features/Commands/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6589 chore(E2E): Adding E2E test for the Refresh intervals of the top counters (24.04.x)
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics.feature
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics/index.ts
Labels: area/test, backport

#6590 fix(Events Log): fix events logs refacto (#6573) (#6580)
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6591 fix(Events Log): fix events logs refacto (#6573) (#6580)
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6544 fix(Resouces status): Host & Services columns don't contain the rights infos in the view by host
  centreon/www/front_src/src/Resources/Listing/columns/Parent.tsx
  centreon/www/front_src/src/Resources/Listing/columns/Resource.tsx
  centreon/www/front_src/src/Resources/Listing/columns/ServiceSubItemColumn/SubItem.styles.tsx
  centreon/www/front_src/src/Resources/Listing/columns/ServiceSubItemColumn/SubItem.tsx
  centreon/www/front_src/src/Resources/Listing/columns/colomuns.style.ts
  centreon/www/front_src/src/Resources/Listing/columns/index.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6592 fix(Events Log): fix events logs refacto (#6573) (#6580)
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6247 enh(conf): call API to delete host
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/host.php
  centreon/www/include/configuration/configObject/host_template_model/hostTemplateModel.php
  centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6585 fix(update-24.10.x) : fix update files for 24.10
  centreon/www/install/php/Update-24.10.0.php
  centreon/www/install/php/Update-24.10.1.php
  centreon/www/install/php/Update-24.10.2.php
  centreon/www/install/php/Update-24.10.3.php
  centreon/www/install/php/Update-24.10.4.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6435 fix(conf): update menu and breadcrumb
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Listing/index.tsx
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
  centreon/www/front_src/src/AdditionalConnectorConfiguration/translatedLabels.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/menu_translation.php
  centreon/www/install/php/Update-25.01.0.php
  centreon/www/install/php/Update-25.03.0.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6606 fix(host categories): fix SQL Query to search host categories (#6528)
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6607 fix(host categories): fix SQL Query to search host categories (#6528)
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6586 fix(update-24.10.x) : fix update files for 24.10
  centreon/www/install/php/Update-24.10.0.php
  centreon/www/install/php/Update-24.10.1.php
  centreon/www/install/php/Update-24.10.2.php
  centreon/www/install/php/Update-24.10.3.php
  centreon/www/install/php/Update-24.10.4.php
Labels: area/backend, backport, skip-workflow-web

#6358 fix(smarty) : install of smarty 3.1.48 fixed
  centreon-open-tickets/widgets/open-tickets/index.php
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/toolbar.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Itop/ajax/call.php
  centreon/GPL_LIB/smarty-plugins/SmartyCentreon.php
  centreon/composer.json
  centreon/composer.lock
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/include/core/header/header.php
Labels: area/backend, skip-workflow-web, skip-workflow-open-tickets

#6246 fix(acl) Fix missing servicegroups IDs and access groups IDs in queries
  centreon/www/class/centreonACL.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6602 fix(Resource Status): Unable to enable/disable compact mode (#6494)
  centreon/src/Core/Application/Configuration/User/UseCase/PatchUser/PatchUser.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6582 mon-159126 Centreon OSS 23.04 Hotfix
  centreon/.version
  centreon/www/include/eventLogs/xml/data.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.26.php
Labels: skip-workflow-web

#6621 mon-159126 sync hotfix 23.04
  centreon/.version
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.26.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6622 Mon-159127 Sync hotfix 23.10
  centreon/.version
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.21.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6627 fix(Events Log): fix events logs refacto (#6573) (#6580)
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport

#6634 poc(ci): test semgrep mono repo manual integration
  .github/workflows/awie-analysis.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  .github/workflows/semgrep-analysis.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web-analysis.yml
  .github/workflows/web.yml
Labels: external

#6413 enh(conf): call APIv2 for service template creation in form
  centreon/doc/API/latest/Cloud/Configuration/ServiceTemplate/Schema/NewServiceTemplate.yaml
  centreon/src/Core/ServiceTemplate/Infrastructure/API/AddServiceTemplate/AddServiceTemplateSaasSchema.json
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6624 enh (Centreon UI): migrate the proxy configuration behat test to a cypress test
  centreon/behat.yml
  centreon/features/TestProxyConfiguration.feature
  centreon/features/bootstrap/TestProxyConfigurationContext.php
  centreon/tests/e2e/features/Administration/03-proxy-configuration.feature
  centreon/tests/e2e/features/Administration/03-proxy-configuration/index.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6562 enh(ceip): add LACCESS in metadata
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6604 enh (SNMP Traps): migrate the vendor configuration behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/VendorConfiguration.feature
  centreon/features/bootstrap/VendorConfigurationContext.php
  centreon/tests/e2e/features/Resources-status/06-submit-result/index.ts
  centreon/tests/e2e/features/Resources-status/commands.ts
  centreon/tests/e2e/features/Snmp-Traps/03-vendor-configuration.feature
  centreon/tests/e2e/features/Snmp-Traps/03-vendor-configuration/index.ts
  centreon/tests/e2e/features/Snmp-Traps/common.ts
  centreon/tests/e2e/fixtures/snmp-traps/vendor.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6422 enh(conf): add telegraf & centreon monitoring agent connector configuration
  centreon/tests/rest_api/collections/configuration/Connectors.postman_collection.json
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-25.03.0.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6643 Mon-157164 Sync release 24.10 OSS january 2025
  centreon/www/install/php/Update-24.10.4.php
  centreon/www/install/php/Update-24.10.5.php
Labels: area/backend, skip-workflow-web-analysis

#6629 enh (Centreon UI): migrate the proxy configuration behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/TestProxyConfiguration.feature
  centreon/features/bootstrap/TestProxyConfigurationContext.php
  centreon/tests/e2e/features/Administration/03-proxy-configuration.feature
  centreon/tests/e2e/features/Administration/03-proxy-configuration/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6628 enh (Centreon UI): migrate the proxy configuration behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/TestProxyConfiguration.feature
  centreon/features/bootstrap/TestProxyConfigurationContext.php
  centreon/tests/e2e/features/Administration/03-proxy-configuration.feature
  centreon/tests/e2e/features/Administration/03-proxy-configuration/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6625 enh(UI): Get services using service names
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/src/Core/Service/Application/Repository/ReadRealTimeServiceRepositoryInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNames.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterInterface.php
  centreon/src/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesResponse.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesController.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenter.php
  centreon/src/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesRoute.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
  centreon/tests/php/Core/Service/Application/UseCase/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesTest.php
  centreon/tests/php/Core/Service/Infrastructure/API/FindRealTimeUniqueServiceNames/FindRealTimeUniqueServiceNamesPresenterStub.php
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/api/endpoint.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis

#6658 enh(ceip): add LACCESS in metadata (#6562)
  centreon/www/api/class/centreon_ceip.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6657 enh(ceip): add LACCESS in metadata (#6562)
  centreon/www/api/class/centreon_ceip.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6656 enh(ceip): add LACCESS in metadata (#6562)
  centreon/www/api/class/centreon_ceip.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6659 enh(ceip): add LACCESS in metadata (#6562)
  centreon/www/api/class/centreon_ceip.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6636 enh(ui): [MAP] 23.04 when too many elements are selected in a Geoview the list is out of visibility
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
Labels: area/ui

#6648 fix(contact): fix contact group deletion for contact on remote server (#6461)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6620 fix(smarty) : remove smarty from tests
  widgets/centreon-widget-engine-status/composer.json
  widgets/centreon-widget-global-health/composer.json
  widgets/centreon-widget-graph-monitoring/composer.json
  widgets/centreon-widget-grid-map/composer.json
  widgets/centreon-widget-host-monitoring/composer.json
  widgets/centreon-widget-hostgroup-monitoring/composer.json
  widgets/centreon-widget-httploader/composer.json
  widgets/centreon-widget-live-top10-cpu-usage/composer.json
  widgets/centreon-widget-live-top10-memory-usage/composer.json
  widgets/centreon-widget-ntopng-listing/composer.json
  widgets/centreon-widget-ntopng-listing/composer.lock
  widgets/centreon-widget-service-monitoring/composer.json
  widgets/centreon-widget-servicegroup-monitoring/composer.json
  widgets/centreon-widget-single-metric/composer.json
  widgets/centreon-widget-single-metric/composer.lock
  widgets/centreon-widget-tactical-overview/composer.json
Labels: bug, area/backend

#6655 fix(conf): update wording for monitoring connectors manager (#6435)
  centreon/www/install/menu_translation.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6571 fix(dashboard): do not take into account UNDETERMINED days in calcula…
  centreon/www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_HostLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php
  centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6646 fix(contact): fix contact group deletion for contact on remote server (#6461)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6484 feat(docker): adapt web container to centreon-poller docker image
  .github/docker/.env
  .github/docker/README.md
  .github/docker/centreon-web/alma8/entrypoint/container.d/70-gorgone.sh
  .github/docker/centreon-web/alma8/entrypoint/container.d/80-register_pollers_background.sh
  .github/docker/centreon-web/alma8/entrypoint/container.d/99-logs.sh
  .github/docker/centreon-web/alma8/entrypoint/container.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/70-gorgone.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/80-register_pollers_background.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/99-logs.sh
  .github/docker/centreon-web/alma9/entrypoint/container.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/70-gorgone.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/80-register_pollers_background.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/99-logs.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/70-gorgone.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/80-register_pollers_background.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/99-logs.sh
  .github/docker/centreon-web/jammy/entrypoint/container.sh
  .github/docker/docker-compose.yml
  .github/workflows/web.yml
Labels: system, skip-workflow-web, skip-workflow-web-analysis

#6676 enh(release): move all .version files to the root level of file tree …
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  .version.centreon-awie
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-open-tickets
  .version.centreon-web
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis

#6631 fix(Docker): Fix monitoring on docker images
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma8/entrypoint/container.d/61-snmpd.sh
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/entrypoint/container.d/61-snmpd.sh
  .github/docker/centreon-web/bookworm/Dockerfile
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/entrypoint/container.d/61-snmpd.sh
  .github/docker/centreon-web/jammy/Dockerfile
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/entrypoint/container.d/61-snmpd.sh
  .github/docker/centreon-web/sql/10-standard.sql
  .github/docker/docker-compose.yml
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/tests/e2e/commons.ts
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create/index.ts
  centreon/tests/e2e/features/Cloud-notifications/common.ts
  centreon/tests/e2e/features/Dashboards/14-resource-table-widget-configuration/index.ts
  centreon/tests/e2e/features/Dashboards/16-status-chart-widget-configuration/index.ts
  centreon/tests/e2e/features/Resources-status/05-filtre/index.ts
  centreon/tests/e2e/features/Resources-status/06-submit-result/index.ts
  centreon/tests/e2e/features/Services-configuration/03-service-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/08-massive-change-services/index.ts
  centreon/tests/e2e/features/Snmp-Traps/03-vendor-configuration/index.ts
  centreon/www/index.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis

#6672 enh(release): move all .version files to the root level of file tree …
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  .version.centreon-awie
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-open-tickets
  .version.centreon-web
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis

#6673 enh(release): move all .version files to the root level of file tree …
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  .version.centreon-awie
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-open-tickets
  .version.centreon-web
Labels: skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis

#6674 enh(release): move all .version files to the root level of file tree …
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  .version.centreon-awie
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-open-tickets
  .version.centreon-web
Labels: skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis

#6615 fix(acl) Fix missing servicegroups IDs and access groups IDs in queri…
  centreon/www/class/centreonACL.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6668 [E2E] fix test in 01-commands-configuration on bookworm (nightly)
  centreon/tests/e2e/features/Commands/01-commands-configuration/index.ts
  centreon/tests/e2e/features/Commands/commands.ts
  centreon/tests/e2e/fixtures/commands/command.json
Labels: area/test

#6670 enh (Host Template): migrate the DisableFieldsOnBlockedObjects behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/DisableFieldsOnBlockedObjects.feature
  centreon/features/bootstrap/DisableFieldsOnBlockedObjectsContext.php
  centreon/tests/e2e/features/Hosts/08-disable-fileds-on-blocked-hostTemplate.feature
  centreon/tests/e2e/features/Hosts/08-disable-fileds-on-blocked-hostTemplate/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6669 enh (Host Template): migrate the DisableFieldsOnBlockedObjects behat test to a cypress test(24.10.x)
  centreon/behat.yml
  centreon/features/DisableFieldsOnBlockedObjects.feature
  centreon/features/bootstrap/DisableFieldsOnBlockedObjectsContext.php
  centreon/tests/e2e/features/Hosts/08-disable-fileds-on-blocked-hostTemplate.feature
  centreon/tests/e2e/features/Hosts/08-disable-fileds-on-blocked-hostTemplate/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6612 fix unprecise query when looking for lua password param value (#5627) [dev-24.04.x]
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6611 fix unprecise query when looking for lua password param value (#5627) [dev-24.10.x]
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6546 feat(host group): Add an endpoint to delete HGs in bulk
  centreon/config/services.yaml
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Configuration/HostGroup/DeleteHostGroups.yaml
  centreon/src/Core/HostGroup/Application/UseCase/DeleteHostGroups/DeleteHostGroups.php
  centreon/src/Core/HostGroup/Application/UseCase/DeleteHostGroups/DeleteHostGroupsRequest.php
  centreon/src/Core/HostGroup/Application/UseCase/DeleteHostGroups/DeleteHostGroupsResponse.php
  centreon/src/Core/HostGroup/Application/UseCase/DeleteHostGroups/DeleteHostGroupsStatusResponse.php
  centreon/src/Core/HostGroup/Infrastructure/API/DeleteHostGroups/DeleteHostGroupsController.php
  centreon/src/Core/HostGroup/Infrastructure/API/DeleteHostGroups/DeleteHostGroupsInput.php
  centreon/src/Core/HostGroup/Infrastructure/API/DeleteHostGroups/DeleteHostGroupsRequestTransformer.php
  centreon/src/Core/HostGroup/Infrastructure/API/DeleteHostGroups/DeleteHostGroupsRoute.yaml
  centreon/src/Core/HostGroup/Infrastructure/Serializer/DeleteHostGroupsStatusResponseNormalizer.php
  centreon/src/Core/HostGroup/Infrastructure/Voters/HostGroupVoters.php
  centreon/src/Core/Notification/Application/Repository/ReadNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Application/Repository/WriteNotificationRepositoryInterface.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbReadNotificationRepository.php
  centreon/src/Core/Notification/Infrastructure/Repository/DbWriteNotificationRepository.php
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/Repository/WriteResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbWriteResourceAccessRepository.php
  centreon/src/Core/Service/Application/Repository/ReadServiceRepositoryInterface.php
  centreon/src/Core/Service/Domain/Model/ServiceRelation.php
  centreon/src/Core/Service/Infrastructure/Repository/ApiReadServiceRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbReadServiceRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/tests/php/Core/HostGroup/Application/UseCase/DeleteHostGroups/DeleteHostGroupsTest.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6691 test(e2e): remove case of minor version last stable -1
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade.feature
Labels: area/test

#6614 fix(acl) Fix missing servicegroups IDs and access groups IDs in queri…
  centreon/www/class/centreonACL.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6693 fix(CI): Fix notifications component test
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Resources column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Users column is clicked.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6697 fix(CI): Fix notifications component test (#6693)
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Resources column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Status column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting --  executes a listing request when the Users column is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting -- executes a listing request when a sortable column is clicked.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6699 Fix(CI): fix ACC component tests
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.listing.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6689 chore(tests): rewrite export manifest tests using Pest Syntax
  centreon/src/CentreonRemote/Tests/Infrastructure/Export/ExportCommitmentTest.php
  centreon/src/CentreonRemote/Tests/Infrastructure/Export/ExportManifestTest.php
  centreon/src/CentreonRemote/Tests/Infrastructure/Export/ExportParserJsonTest.php
  centreon/src/CentreonRemote/Tests/ServiceProviderTest.php
  centreon/tests/php/CentreonRemote/Infrastructure/Export/ExportManifestTest.php
  centreon/tests/php/CentreonRemote/Infrastructure/Export/ExportParserJsonTest.php
  centreon/tests/php/CentreonRemote/ServiceProviderTest.php
Labels: area/backend, skip-workflow-web

#6703 enh(composer) : realign composer on release-22.10-next
  centreon-awie/composer.lock
Labels: enhancement, area/backend

#6671 fix(update) move sql update content from Update-24.10.0.php to Update-25.01.0.php
  centreon/www/install/php/Update-24.11.0.php
  centreon/www/install/php/Update-25.01.0.php
  centreon/www/install/php/Update-25.03.0.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6618 fix(smarty) : install of smarty 3.1.48 fixed
  centreon-awie/composer.lock
  centreon-open-tickets/widgets/open-tickets/index.php
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/toolbar.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Itop/ajax/call.php
  centreon/GPL_LIB/smarty-plugins/SmartyCentreon.php
  centreon/composer.json
  centreon/composer.lock
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/include/core/header/header.php
  widgets/centreon-widget-engine-status/composer.json
  widgets/centreon-widget-engine-status/composer.lock
  widgets/centreon-widget-global-health/composer.json
  widgets/centreon-widget-graph-monitoring/composer.json
  widgets/centreon-widget-grid-map/composer.json
  widgets/centreon-widget-host-monitoring/composer.json
  widgets/centreon-widget-hostgroup-monitoring/composer.json
  widgets/centreon-widget-httploader/composer.json
  widgets/centreon-widget-live-top10-cpu-usage/composer.json
  widgets/centreon-widget-live-top10-memory-usage/composer.json
  widgets/centreon-widget-ntopng-listing/composer.json
  widgets/centreon-widget-ntopng-listing/composer.lock
  widgets/centreon-widget-service-monitoring/composer.json
  widgets/centreon-widget-servicegroup-monitoring/composer.json
  widgets/centreon-widget-single-metric/composer.json
  widgets/centreon-widget-single-metric/composer.lock
  widgets/centreon-widget-tactical-overview/composer.json
Labels: bug, area/backend, backport

#6644 chore(ci): update actions/cache action to v4.2.0 on branch release-25.01-next
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/package/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/actions/veracode-generate-binary/action.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: skip-cherry-pick

#6616 fix(smarty) : install of smarty 3.1.48 fixed
  centreon-open-tickets/widgets/open-tickets/index.php
  centreon-open-tickets/widgets/open-tickets/src/export.php
  centreon-open-tickets/widgets/open-tickets/src/index.php
  centreon-open-tickets/widgets/open-tickets/src/toolbar.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/EasyVistaRest/ajax/call.php
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/Itop/ajax/call.php
  centreon/GPL_LIB/smarty-plugins/SmartyCentreon.php
  centreon/composer.json
  centreon/composer.lock
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/include/core/header/header.php
  widgets/centreon-widget-engine-status/composer.json
  widgets/centreon-widget-global-health/composer.json
  widgets/centreon-widget-graph-monitoring/composer.json
  widgets/centreon-widget-grid-map/composer.json
  widgets/centreon-widget-host-monitoring/composer.json
  widgets/centreon-widget-hostgroup-monitoring/composer.json
  widgets/centreon-widget-httploader/composer.json
  widgets/centreon-widget-live-top10-cpu-usage/composer.json
  widgets/centreon-widget-live-top10-memory-usage/composer.json
  widgets/centreon-widget-ntopng-listing/composer.json
  widgets/centreon-widget-ntopng-listing/composer.lock
  widgets/centreon-widget-service-monitoring/composer.json
  widgets/centreon-widget-servicegroup-monitoring/composer.json
  widgets/centreon-widget-single-metric/composer.json
  widgets/centreon-widget-single-metric/composer.lock
  widgets/centreon-widget-tactical-overview/composer.json
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis

#6709 (Backport 24.04.x) Fix(rspack): Fix possible ids duplication (#6692)
  centreon/packages/js-config/rspack/base/globalConfig.js
Labels: backport

#6675 fix(update) move sql update content from Update-24.10.0.php to Update-25.01.0.php
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade.feature
  centreon/www/install/php/Update-24.11.0.php
  centreon/www/install/php/Update-25.01.0.php
Labels: skip-workflow-web

#6711 (Backport 23.10.x) Fix(rspack): Fix possible ids duplication (#6692)
  centreon/packages/js-config/webpack/base/globalConfig.js
Labels: backport

#6713 (Backport 24.04.x) Fix(rspack): Fix possible ids duplication (#6692)
  centreon/packages/js-config/webpack/base/index.js
Labels: backport

#6406 enh(UI): Implement dynamic Y axis width compute on graph
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a stacked bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend in list mode when the corresponding props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend on the left side of the graph when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend on the right side of the graph as list when the corresponding props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays lines with a custom line width when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows points when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows the area when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip a single metric when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- changes the unit on the left or right scales when a new unit is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart.snap.png
  centreon/packages/ui/src/Graph/BarChart/BarChart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/BarChart/ResponsiveBarChart.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/packages/ui/src/Graph/Chart/InteractiveComponents/AnchorPoint/GuidingLines.tsx
  centreon/packages/ui/src/Graph/Chart/InteractiveComponents/AnchorPoint/useTickGraph.ts
  centreon/packages/ui/src/Graph/common/Axes/index.tsx
  centreon/packages/ui/src/Graph/common/Axes/useAxisY.ts
  centreon/packages/ui/src/Graph/common/BaseChart/ChartSvgWrapper.tsx
  centreon/packages/ui/src/Graph/common/BaseChart/useComputeBaseChartDimensions.ts
  centreon/packages/ui/src/Graph/common/BaseChart/useComputeYAxisMaxCharacters.ts
  centreon/packages/ui/src/Graph/common/models.ts
  centreon/packages/ui/src/Graph/common/timeSeries/index.test.ts
  centreon/packages/ui/src/Graph/common/timeSeries/index.test.ts-E
  centreon/packages/ui/src/Graph/common/timeSeries/index.ts
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/packages/ui/src/Graph/mockedData/lastDayWithNullValues.json
Labels: area/ui

#6537 enh(conf) remove check_replication field in I/O broker configuration forms
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgCentreonBrokerInfo.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BamBrokerCfgInfo.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputStatus.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputUnifiedSql.php
  centreon/tests/clapi_export/clapi-configuration.txt
  centreon/tests/rest_api/behat-collections/rest_api.postman_collection.json
  centreon/tests/rest_api/behat-collections/rest_api.postman_environment.json
  centreon/tests/rest_api/collections/configuration/Broker_Input_Output.postman_collection.json
  centreon/www/install/centreon_broker_translation.php
  centreon/www/install/createTables.sql
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-25.03.0.php
  centreon/www/install/var/baseconf/centreon-broker.sql
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6714 (Backport 24.10) enh(UI): Optimize bar chart (#6433)
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend in list mode when the corresponding props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend on the left side of the graph when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend on the right side of the graph as list when the corresponding props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip a single metric when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart.snap.png
  centreon/packages/ui/src/Graph/BarChart/BarGroup.tsx
  centreon/packages/ui/src/Graph/BarChart/MemoizedGroup.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.stories.tsx
  centreon/packages/ui/src/Graph/mockedData/pingServiceLinesBars.json
  centreon/packages/ui/src/components/Zoom/Zoom.tsx
  centreon/packages/ui/src/components/Zoom/ZoomContent.tsx
  centreon/packages/ui/src/components/Zoom/models.ts
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Slider/useSlider.ts
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6700 enh(ci): upload logs of e2e upgrade tests + clear cypress network cache
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/packages/js-config/cypress/e2e/configuration.ts
  centreon/packages/js-config/cypress/e2e/tasks.ts
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade.feature
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6728 fix(CI): fix notification listing component test
  centreon/cypress/visual-testing-snapshots/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx/column sorting -- executes a listing request when a sortable column is clicked.snap.png
  centreon/www/front_src/src/CloudNotificationsConfiguration/Listing/Tests/NotificationsListing.cypress.spec.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#6623 fix(conf): update menu and breadcrumb (#6435)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Listing/index.tsx
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/AdditionalConnectorConfiguration/Application/Exception/AccException.php
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Additional-connectors/05-ACC-check-permissions/index.ts
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
  centreon/www/front_src/src/AdditionalConnectorConfiguration/translatedLabels.ts
  centreon/www/install/insertTopology.sql
  centreon/www/install/menu_translation.php
  centreon/www/install/php/Update-24.10.5.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis

#6609 Enh([Dashboards]):Improve spacing and responsiveness
  centreon/cypress/fixtures/Widgets/Graph/topMetricsWithLongRSname.json
  centreon/cypress/fixtures/Widgets/Graph/topMetricsWithUniqueRS.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/1024px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/350px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/600px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/TopBottom -- displays a message when the dataset is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/TopBottom -- displays the widget.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/TopBottom -- does not display the labels when the corresponding setting is disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/adapt the resource name area without exceeding the longest name when screen resolution is 1024px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/adapt the resource name area without exceeding the longest name when screen resolution is 350px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/adapt the resource name area without exceeding the longest name when screen resolution is 600px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/maintain a fixed 24px space between resource name and bar chart when screen resolution is1024px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/maintain a fixed 24px space between resource name and bar chart when screen resolution is350px.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx/maintain a fixed 24px space between resource name and bar chart when screen resolution is600px.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/Label.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/MetricContainer.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/MetricTop.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/TopBottom.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/src/useSingleBarCurrentWidth.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6375 fix(downtimes): improved reading performance
  centreon/www/include/monitoring/downtime/downtime.php
  centreon/www/include/monitoring/downtime/listDowntime.php
  centreon/www/install/installBroker.sql
  centreon/www/install/php/Update-25.03.0.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6731 enh (LDAP): migrate the LDAP Manual Import behat test to a cypress test
  centreon/behat.yml
  centreon/features/LdapManualImport.feature
  centreon/features/bootstrap/LdapManualImportContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
  centreon/tests/e2e/fixtures/users/ldap.json
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6729 enh(docker): add possibility to set default admin language
  .github/docker/README.md
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/alma8/entrypoint/container.d/61-snmpd_background.sh
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/alma9/entrypoint/container.d/61-snmpd_background.sh
  .github/docker/centreon-web/bookworm/Dockerfile
  .github/docker/centreon-web/bookworm/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/bookworm/entrypoint/container.d/61-snmpd_background.sh
  .github/docker/centreon-web/jammy/Dockerfile
  .github/docker/centreon-web/jammy/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/jammy/entrypoint/container.d/61-snmpd_background.sh
  .github/docker/docker-compose.yml
Labels: system, skip-workflow-web

#6737 enh (LDAP): migrate the LDAP Manual Import behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/LdapManualImport.feature
  centreon/features/bootstrap/LdapManualImportContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
  centreon/tests/e2e/fixtures/users/ldap.json
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6735 enh (LDAP): migrate the LDAP Manual Import behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/LdapManualImport.feature
  centreon/features/bootstrap/LdapManualImportContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
  centreon/tests/e2e/fixtures/users/ldap.json
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6653 [BACKPORT](Dashboard): Double-clicking the "Favorites" button causes errors and inconsistent behavior
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardCardActions/DashboardCardActions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/favoriteAction/FavoriteAction.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Columns/Actions/Actions.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#6645 enh(conf): add telegraf & centreon monitoring agent connector configuration (#6422)
  centreon/tests/rest_api/collections/configuration/Connectors.postman_collection.json
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.6.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6738 enh(docker): add possibility to set default admin language (#6729)
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/bookworm/Dockerfile
  .github/docker/centreon-web/bookworm/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/jammy/Dockerfile
  .github/docker/centreon-web/jammy/entrypoint/container.d/15-installation.sh
  .github/docker/docker-compose.yml
Labels: system, skip-workflow-web

#6754 fix(docker): align all ci docker images with mariadb 10.11
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bullseye/Dockerfile.dependencies
Labels: skip-workflow-docker-web-dependencies

#6633 fix(UI): Do not change option when panel is not from preview
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/useListing.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6748 enh(docker): add possibility to set default admin language (#6729)
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/bookworm/Dockerfile
  .github/docker/centreon-web/bookworm/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/bullseye/Dockerfile
  .github/docker/centreon-web/bullseye/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/jammy/Dockerfile
  .github/docker/centreon-web/jammy/entrypoint/container.d/15-installation.sh
  .github/docker/docker-compose.yml
Labels: skip-workflow-web

#6753 enh(docker): add possibility to set default admin language (#6729)
  .github/docker/Dockerfile.centreon-web-alma9
  .github/docker/Dockerfile.centreon-web-bullseye
  .github/docker/centreon-web-alma8/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web-alma9/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web-bullseye/entrypoint/container.d/15-installation.sh
  .github/docker/docker-compose.yml
Labels: skip-workflow-web

#6613 fix unprecise query when looking for lua password param value (#5627) [dev-23.10.x]
  centreon/www/class/centreonConfigCentreonBroker.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6769 fix(downtime): listing broken when BAM module was installed
  centreon/www/include/monitoring/downtime/listDowntime.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6739 enh (LDAP): migrate LDAP Connection to the Platform behat test to a cypress test
  centreon/behat.yml
  centreon/features/Ldap.feature
  centreon/features/bootstrap/LdapContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6764 enh (LDAP): migrate LDAP Connection to the Platform behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/Ldap.feature
  centreon/features/bootstrap/LdapContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6765 enh (LDAP): migrate LDAP Connection to the Platform behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/Ldap.feature
  centreon/features/bootstrap/LdapContext.php
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import.feature
  centreon/tests/e2e/features/Ldaps/02-ldap-manual-import/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6736 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hos…
  centreon/www/widgets/hostgroup-monitoring/src/index.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6774 chore(release) bump web to 24.04.12
  .version.centreon-web
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.12.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6715 fix(Config): Handling of Read-Only to User Settings
  centreon/www/include/configuration/configObject/contact/listContact.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6776 chore(release) bump web to 23.10.23
  .version.centreon-web
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.23.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6778 enh (connector): migrate the configuration of the connector behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/ConnectorConfiguration.feature
  centreon/features/bootstrap/ConnectorConfigurationContext.php
  centreon/tests/e2e/features/Commands/02-connectors-configuration.feature
  centreon/tests/e2e/features/Commands/02-connectors-configuration/index.ts
  centreon/tests/e2e/features/Commands/commands.ts
  centreon/tests/e2e/fixtures/commands/connector.json
Labels: area/test, backport, skip-workflow-web

#6751 fix(downtimes): improved reading performance (#6375)
  centreon/www/include/monitoring/downtime/downtime.php
  centreon/www/include/monitoring/downtime/listDowntime.php
  centreon/www/install/installBroker.sql
  centreon/www/install/php/Update-23.10.22.php
  centreon/www/install/php/Update-23.10.23.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6779 enh (connector): migrate the configuration of the connector behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/ConnectorConfiguration.feature
  centreon/features/bootstrap/ConnectorConfigurationContext.php
  centreon/tests/e2e/features/Commands/02-connectors-configuration.feature
  centreon/tests/e2e/features/Commands/02-connectors-configuration/index.ts
  centreon/tests/e2e/features/Commands/commands.ts
  centreon/tests/e2e/fixtures/commands/connector.json
Labels: area/test, backport, skip-workflow-web

#6755 fix(MAP): Service groups not available in BULK mode
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6768 enh (Services): migrate URI behat test to a cypress test
  centreon/behat.yml
  centreon/features/URI.feature
  centreon/features/bootstrap/URIContext.php
  centreon/tests/e2e/features/Resources-status/commands.ts
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration.feature
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: area/backend, area/test, skip-workflow-web, skip-workflow-web-analysis

#6772 fix(UI): Do not change option when panel is not from preview (#6633)
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/useListing.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6684 MON-160166 Centreon next 23.04 (Jira release #20398#)
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/package/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/actions/veracode-generate-binary/action.yml
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web-analysis.yml
  .github/workflows/web.yml
  .version.centreon-awie
  .version.centreon-dsm
  .version.centreon-ha
  .version.centreon-open-tickets
  .version.centreon-web
  centreon/.version
  centreon/GPL_LIB/smarty-plugins/SmartyCentreon.php
  centreon/composer.json
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/api/class/centreon_configuration_broker.class.php
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/class/centreonLog.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/common/templates/error.ihtml
  centreon/www/include/configuration/configObject/command/formArguments.php
  centreon/www/include/configuration/configObject/command/formMacros.php
  centreon/www/include/options/media/images/DB-Func.php
  centreon/www/include/options/media/images/formImg.php
  centreon/www/include/options/media/images/images.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.27.php
  centreon/www/install/steps/functions.php
Labels: skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis

#6775 Feat(BA): update redirection to the new ba monitoring page
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
Labels: skip-workflow-web

#6690 enh(ui): Autocomplete multi custom--renderTags
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/index.test.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.stories.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
  centreon/packages/ui/src/Listing/index.tsx
Labels: area/ui

#6770 fix(Widget): Users under ACLs can't see the servicegroups
  centreon/www/widgets/hostgroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/export.php
  centreon/www/widgets/servicegroup-monitoring/src/index.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#6767 enh(ci): group flaky tests summary
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-cypress-report/formatCypressReportToMarkdown.mjs
  .github/actions/publish-report/action.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  centreon-open-tickets/tests/e2e/plugins.ts
  centreon/packages/js-config/cypress/e2e/plugins.ts
Labels: skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis

#6795 enh(database): comment ACL tables to help ACL understanding (#6679)
  centreon/www/install/createTables.sql
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#6794 enh(ci): group flaky tests summary (#6767)
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-cypress-report/formatCypressReportToMarkdown.mjs
  .github/actions/publish-report/action.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  centreon/packages/js-config/cypress/e2e/plugins.ts
Labels: skip-workflow-web, skip-workflow-web-analysis

#6759 fix(docker): force ipv4 in docker snmpd configuration
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
Labels: system, skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#6786 enh (Services): migrate URI behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/URI.feature
  centreon/features/bootstrap/URIContext.php
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration.feature
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: area/test, backport, skip-workflow-web, skip-workflow-web-analysis

#6826 fix(conf) fix HG duplication endpoint
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#6812 fix(conf) host group add/edit fail on cloud platform
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis
