Repository centreon/centreon, pull requests merged in 2025-10, with the labels that each got.

#8382 fix(packaging): add logrotate dependency
  centreon-ha/packaging/centreon-ha.spectemplate
  centreon-ha/packaging/debian/control
  centreon/packaging/centreon-poller.yaml
  centreon/packaging/centreon-web.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, skip-workflow-ha-analysis

#8231 fix(web): Escape the command passed to shell_exec
  centreon/src/CentreonRemote/Infrastructure/Service/PollerInteractionService.php
  centreon/www/class/centreonBroker.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8395 fix(realtime services): Prevent GROUPBY clause to be called without associated field in SELECT
  centreon/www/api/class/centreon_realtime_services.class.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8414 fix(web): Escape the command passed to shell_exec
  centreon/src/CentreonRemote/Infrastructure/Service/PollerInteractionService.php
  centreon/www/class/centreonBroker.class.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8357 enh(ui): Graph tweaks and add support for legend contextual click
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend in list mode when the corresponding props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays lines with a custom line width when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays only one line with custom style when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows points when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows the area when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays additional lines when props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays graph according to min and max boundaries for a unit.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays graph according to min and max boundaries.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart.snap.png
  centreon/packages/ui/src/Form/Inputs/Grid.tsx
  centreon/packages/ui/src/Form/Section/navigateToSection.ts
  centreon/packages/ui/src/Graph/BarChart/BarChart.stories.tsx
  centreon/packages/ui/src/Graph/BarChart/BarChart.tsx
  centreon/packages/ui/src/Graph/BarChart/ResponsiveBarChart.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.stories.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/packages/ui/src/Graph/Chart/Legend/index.tsx
  centreon/packages/ui/src/Graph/Chart/models.ts
  centreon/packages/ui/src/Graph/Chart/useChartData.ts
  centreon/packages/ui/src/Graph/common/BaseChart/BaseChart.tsx
  centreon/packages/ui/src/Graph/common/timeSeries/index.ts
  centreon/packages/ui/src/Graph/common/utils.ts
  centreon/packages/ui/src/InputField/Select/index.tsx
  centreon/packages/ui/src/Module/index.tsx
  centreon/packages/ui/src/ThemeProvider/tailwindcss.css
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/packages/ui/src/components/Modal/Modal.styles.ts
  centreon/packages/ui/src/components/Modal/ModalHeader.tsx
Labels: area/ui, skip-workflow-web-analysis, qa-approved

#8384 fix(dsm): startup query for alarms in the mod_dsm_cache table (#7466)
  centreon-dsm/bin/dsmd.pl
Labels: skip-workflow-dsm, skip-workflow-dsm-analysis, qa-approved

#8343 enh(cfg) remove call to gorgone command SENDCBCFG
  centreon/src/CentreonRemote/Infrastructure/Service/PollerInteractionService.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8361 enh(install) improve db type detection
  centreon/www/class/centreon-partition/partEngine.class.php
  centreon/www/install/steps/process/createDbUser.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8418 fix(export) handle macros in indirect inheritance
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Macro/Application/Repository/ReadHostMacroRepositoryInterface.php
  centreon/src/Core/Macro/Infrastructure/Repository/DbReadHostMacroRepository.php
  centreon/www/class/config-generate/host.class.php
  centreon/www/class/config-generate/servicetemplate.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8379 fix(router): handle reverse proxy
  centreon/src/Core/Infrastructure/Common/Api/Router.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8380 enh(conf) call patch endpoints for host/hostTemplate update by form #6185
  centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8420 enh(open-tickets): move routes definition to RouteLoader mechanism
  centreon-open-tickets/config/packages/CentreonResourcesOpenTicket.php
  centreon-open-tickets/config/routes/CentreonOpenTickets.yaml
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Routing/RouteLoader.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/install.php
  centreon-open-tickets/www/modules/centreon-open-tickets/php/uninstall.php
  centreon-open-tickets/www/modules/centreon-open-tickets/routes/CentreonOpenTickets.yaml
  centreon-open-tickets/www/modules/centreon-open-tickets/routes/CentreonOpenTickets.yaml.wait
Labels: area/backend, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8436 fix(export) handle macros in indirect inheritance (#8418)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Macro/Application/Repository/ReadHostMacroRepositoryInterface.php
  centreon/src/Core/Macro/Infrastructure/Repository/DbReadHostMacroRepository.php
  centreon/www/class/config-generate/host.class.php
  centreon/www/class/config-generate/servicetemplate.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8421 fix(dsm): Correctly package sql files
  centreon-dsm/packaging/centreon-dsm-server.yaml
Labels: backport, skip-workflow-dsm, skip-workflow-dsm-analysis

#8367 fix(metaService): Users with ACLs cannot see their own duplicated met… (#8327)
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/metaService.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8348 enh(engine-cfg) add opentelemetry logger in engine conf
  centreon/www/class/config-generate/engine.class.php
  centreon/www/include/configuration/configNagios/DB-Func.php
  centreon/www/include/configuration/configNagios/formNagios.ihtml
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8411 fix(Custom Views): Select ALL + CSV Export will only download the displayed page of hosts in host monitoring widget
  centreon/www/widgets/host-monitoring/data.js
  centreon/www/widgets/host-monitoring/src/export.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8396 fix(host categories): allow acl user to add host templates to hc
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8359 enh(packaging): migrate ha to nfpm packaging
  .github/actions/package/action.yml
  .github/workflows/ha.yml
  .github/workflows/package.yml
  centreon-ha/packaging/centreon-ha-common.yaml
  centreon-ha/packaging/centreon-ha-web.yaml
  centreon-ha/packaging/centreon-ha.spectemplate
  centreon-ha/packaging/debian/centreon-ha-common.dirs
  centreon-ha/packaging/debian/centreon-ha-common.install
  centreon-ha/packaging/debian/centreon-ha-web.install
  centreon-ha/packaging/debian/centreon-ha-web.logrotate
  centreon-ha/packaging/debian/control
  centreon-ha/packaging/debian/copyright
  centreon-ha/packaging/debian/rules
  centreon-ha/packaging/debian/source/format
  centreon-ha/packaging/debian/substvars
  centreon-ha/packaging/scripts/centreon-ha-common-postinst.sh
  centreon-ha/packaging/scripts/centreon-ha-web-postinst.sh
Labels: upload-artifacts, skip-workflow-ha-analysis

#8469 fix(Custom Views): Select ALL + CSV Export will only download the displayed page of hosts in host monitoring widget (#8411) [dev-24.10.x]]
  centreon/www/widgets/host-monitoring/data.js
  centreon/www/widgets/host-monitoring/src/export.php
  centreon/www/widgets/host-monitoring/src/index.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8410 enh(export): Remove credentials_encryption from engine config file
  centreon/www/class/config-generate/engine.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8458 fix(Updates): Manage engine-context configuration through API update
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersionsException.php
  centreon/tests/php/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersionsTest.php
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8487 fix(Updates): Manage engine-context configuration through API update (#8458)
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersions.php
  centreon/src/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersionsException.php
  centreon/tests/php/Core/Platform/Application/UseCase/UpdateVersions/UpdateVersionsTest.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8462 enh(cfg) remove call to gorgone command SENDCBCFG (#8343)
  centreon/src/CentreonRemote/Infrastructure/Service/PollerInteractionService.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8374 fix(host): Correctly escape some properties in the listing
  centreon/www/include/configuration/configObject/host/listHost.ihtml
  centreon/www/include/configuration/configObject/host/listHost.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8451 enh(cfg) remove call to gorgone command SENDCBCFG (#8343)
  centreon/src/CentreonRemote/Infrastructure/Service/PollerInteractionService.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8450 fix(brokercfg) fix typo causing duplicate to fail (#8385)
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/InputBroker.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/InputRrd.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputCentral.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputForwardMaster.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputModuleMaster.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputRrdMaster.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/InputFlowOnePeerRetention.php
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8457 fix(api): Fix error 500 occuring on generate & reload configuration
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Exception/ConfigurationMonitoringServerException.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateConfiguration.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/Repository/MonitoringServerConfigurationRepositoryApi.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8503 enh(ci): alternate tested OS on each nightly
  .github/workflows/get-environment.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis

#8499 fix(Graphs): User disconnected from UI when making a CSV export (#8387) [dev-25.10.x]
  centreon/www/include/views/graphs/exportData/ExportCSVServiceData.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8472 fix(Resources Status): Services attached to a deleted host still appear in the menu filter (#8394) [dev-25.10.x]
  centreon/phpstan.core.baseline.neon
  centreon/src/Core/Service/Infrastructure/Repository/DbReadRealTimeServiceRepository.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8500 fix(web): Prevent PHP warning when exporting poller configuration (#8…
  centreon/www/include/configuration/configGenerate/xml/generateFiles.php
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
  centreon/www/include/configuration/configGenerate/xml/restartPollers.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8488 fix(Open ticket): Improve GlpiApiRest ticket opening (#7063) (#8247)
  centreon-open-tickets/www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
Labels: area/backend, backport, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8476 enh(contact): disable password fields if the user connected use an authentication provider
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8498 fix(LDAP): fixed function return types (#8021) [dev-25.10.x]
  centreon/www/class/centreonLDAP.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8456 (API): fix search parameters on dashboard listing
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardRepository.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8527 fix(quality_tools): fix rector and cs fixer on diff
  php-tools/php-cs-fixer/src/Command/RunCsFixerOnDiffCommandHandler.php
  php-tools/rector/src/Command/RunRectorOnDiffCommandHandler.php
Labels: bug, area/backend, skip-workflow-awie-analysis, qa-approved

#8440 fix(hosts): add validation on host name for add/patch (#8235)
  centreon/src/Core/Host/Application/UseCase/AddHost/AddHostValidation.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidation.php
  centreon/tests/php/Core/Host/Application/UseCase/AddHost/AddHostValidationTest.php
  centreon/tests/php/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHostValidationTest.php
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json.ignored
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8483 fix(host categories): allow acl user to add host templates to hc (#8396)
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8393 fix(ldap): make method public to be able to be called from outside of context
  centreon/www/class/centreonLDAP.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8508 fix(aclmenus): Escape search string in ACL menus listing (#8257)
  centreon/www/include/options/accessLists/menusACL/listsMenusAccess.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8506 fix(aclmenus): Escape search string in ACL menus listing (#8257)
  centreon/www/include/options/accessLists/menusACL/listsMenusAccess.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved
