Repository centreon/centreon, pull requests merged in 2025-05, with the labels that each got.

#7308 fix(timeperiods): maxlength should match the database columns size (#7219)
  centreon/www/include/configuration/configObject/timeperiod/formTimeperiod.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7305 Backport([Resources Status]): Graph - Filling and invert options are the inverse of the curve template
  centreon/packages/ui/src/Graph/LineChart/useLineChartData.ts
Labels: qa-approved

#7309 fix(timeperiods): maxlength should match the database columns size (#7219)
  centreon/www/include/configuration/configObject/timeperiod/formTimeperiod.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7303 enh(tests): improve version parsing and package distribution handling
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: system

#7253 fix(widgets): Fix warning when installing some widgets
  centreon/src/CentreonLegacy/Core/Widget/Information.php
  centreon/src/CentreonLegacy/Core/Widget/Installer.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7266 Backport(web): % unit is not correctly formatted on axis
  centreon/packages/ui/src/Graph/common/Axes/useAxisY.ts
Labels: qa-approved

#7327 fix(agent configuration) : mysql command denied fixed if the database name is not centreon_storage
  centreon/www/api/class/centreon_ceip.class.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7333 Feedbacks: timeline widget
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/src/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
Labels: skip-workflow-web

#7341 fix(agent configuration) : mysql command denied fixed if the database name is not centreon_storage
  centreon/www/api/class/centreon_ceip.class.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7342 fix(agent configuration) : mysql command denied fixed if the database name is not centreon_storage
  centreon/www/api/class/centreon_ceip.class.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7343 fix(agent configuration) : mysql command denied fixed if the database name is not centreon_storage
  centreon/www/api/class/centreon_ceip.class.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7328 fix(widgets): Fix warning when installing some widgets
  centreon/src/CentreonLegacy/Core/Widget/Information.php
  centreon/src/CentreonLegacy/Core/Widget/Installer.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7374 fix(ci): use technique-ci to push translations updates
  .github/scripts/translation/make_translation.sh
  .github/workflows/web.yml
Labels: skip-workflow-web, skip-workflow-web-analysis, update-translations

#7355 Typo edit centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7307 enh(test) : Add JSON schema validation : monitoring part 1
  centreon/tests/rest_api/collections/monitoring/Acknowledgement.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Check.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Comment.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Host_Monitoring.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Monitoring_Server_Configuration.postman_collection.json
Labels: area/test

#7361 enh(test) : Add JSON schema validation : monitoring part 2
  centreon/tests/rest_api/collections/monitoring/Monitoring_Servers.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Monitoring_Timeline.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Real_Time_Category.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Real_Time_Monitoring_Server.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Real_Time_Severity.postman_collection.json
Labels: area/test, qa-approved

#7268 fix(HostCategories)(DBfunc): DB func hardening
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
  centreon/www/include/configuration/configObject/host_categories/hostCategories.php
Labels: area/backend, skip-workflow-web

#7357 fix(HostCategories)(listing): List's page hardening
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/www/include/common/sqlCommonFunction.php
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend, skip-workflow-web

#7378 chore: correction of a translation typo
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis

#7285 feat(UI): modernize monitoring BA page
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Timeline/Timeline.cypress.spec.tsx/Timeline -- checks that the correct number of bars are rendered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Timeline/Timeline.cypress.spec.tsx/Timeline -- displays the default tooltip with correct information when hovered over a bar.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Timeline/Timeline.cypress.spec.tsx/Timeline -- displays tooltip with correct information when hovered over a bar.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- cannot collapse a node when a node is not clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- collapses a node when a node is clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- displays the tree with line links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- displays the tree with step links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- cannot collapses a node when a leaf is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- collapses a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays customized links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays the whole tree.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands nodes by default when a prop is set.snap.png
  centreon/packages/ui/src/Graph/Timeline/ResponsiveTimeline.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.stories.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.tsx
  centreon/packages/ui/src/Graph/Timeline/index.ts
  centreon/packages/ui/src/Graph/Timeline/models.ts
  centreon/packages/ui/src/Graph/Timeline/timeline.styles.ts
  centreon/packages/ui/src/Graph/Timeline/translatedLabel.ts
  centreon/packages/ui/src/Graph/Timeline/useTimeline.ts
  centreon/packages/ui/src/Graph/Tree/Links.tsx
  centreon/packages/ui/src/Graph/Tree/Tree.tsx
  centreon/packages/ui/src/Graph/Tree/constants.ts
  centreon/packages/ui/src/Graph/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7271 Fix([Resource Status]): Can't select multiples Host group with the filter menu
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7367 fix(CLOUD):
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration/index.ts
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.ihtml
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/meta_service/help.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7363 fix(HostCategories)(forms): form's page hardening
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
Labels: area/backend, skip-workflow-web

#7376 fix(translation): detect additional strings to translation in dashboard properties
  .github/scripts/translation/extractTranslationFromDashboardProperties.php
  .github/workflows/web.yml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/help.pot
  centreon/lang/messages.pot
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
Labels: skip-workflow-web, skip-workflow-web-analysis, update-translations

#7295 Agent configuration - Manage CMA Tokens - Agent-initiated connection
  centreon/cypress/support/commands.tsx
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- backs to the form when the Stay button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays a warning message when switching the encryption level to No TLS for Telegraf and CMA agents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the encryption level field with TLS preselected as the default value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- handle the form without certificate fields when setting encryption level to No TLS for CMA agent.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- handle the form without certificate fields when setting encryption level to No TLS for Telegraf agent.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/RedirectToTokensPage.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Specs/initialize.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/api/endpoints.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/InputGroup.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
Labels: skip-workflow-open-tickets

#7386 fix(database) : heredoc and nowdoc accepted with connection interface
  centreon/src/Adaptation/Database/Connection/Trait/ConnectionTrait.php
  centreon/tests/php/Centreon/Infrastructure/DatabaseConnectionTest.php
  centreon/tests/php/www/class/CentreonDBTest.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7395 do not use bookworm in get environment matrix
  .github/workflows/get-environment.yml
Labels: skip-workflow-web-analysis

#7389 fix(HostDependencies)(DB-Func): fix + refacto code
  centreon/www/include/configuration/configObject/host_dependency/DB-Func.php
  centreon/www/include/configuration/configObject/host_dependency/hostDependency.php
Labels: area/backend, skip-workflow-web

#7320 chore(deps): absorb 2025-05 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/lighthouse-performance-testing/action.yml
  .github/actions/lighthouse-to-s3/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/clean-npm-tags.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/get-environment.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#7391 fix(agent configuration): fix result formating when excluded central
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
Labels: skip-workflow-web

#7397 enh(test) : Add JSON schema validation : platform and users part
  centreon/tests/rest_api/collections/platform/Platform_Features.postman_collection.json
  centreon/tests/rest_api/collections/platform/Platform_Installation_Status.postman_collection.json
  centreon/tests/rest_api/collections/platform/Platform_Topology.postman_collection.json
  centreon/tests/rest_api/collections/platform/Platform_Version.postman_collection.json
  centreon/tests/rest_api/collections/users/UserFilter.postman_collection.json
Labels: area/test

#7385 enh(test) : Add JSON schema validation : monitoring part 3
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Category.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Group.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Notifications.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Resources_By_Parent_Monitoring.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Resources_Monitoring.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Service_Monitoring.postman_collection.json
  centreon/tests/rest_api/collections/monitoring/Submit_Result.postman_collection.json
Labels: area/test

#7213 enh(SAML): Improve SAML configuration by adding RequestedAuthnContext parameter (#7086) [dev-24.10.x]
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Activation.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Authentication conditions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Auto import users.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Groups mapping.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Identity provider.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Roles mapping.snap.png
  centreon/doc/API/centreon-api.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/RequestedAuthnContextEnum.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/FindSAMLConfiguration/FindSAMLConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationTest.php
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/SAML/defaults.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: area/ui, area/backend, area/test, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7398 fix(HostDependencies)(forms): fix + refacto code
  centreon/www/include/configuration/configObject/host_dependency/formHostDependency.php
Labels: area/backend, skip-workflow-web

#7396 fix(HostDependencies)(listing): fix + refacto code
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.php
Labels: area/backend, skip-workflow-web

#7375 fix(Resource Status): Multiple errors with Meta Services resources + MySQL 8 (#7265) [dev-24.04.x]
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7405 Fix wrong csv escaping in CLAPI
  centreon/www/class/centreon-clapi/centreonObject.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7231 enh(conf) remove cbmod broker module directive
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagios.php
  centreon/src/CentreonRemote/Domain/Resources/DefaultConfig/CfgNagiosBrokerModule.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagios.php
  centreon/src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagiosBrokerModule.php
  centreon/src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
  centreon/tests/clapi_export/clapi-configuration.txt
  centreon/www/class/config-generate/engine.class.php
  centreon/www/include/configuration/configNagios/formNagios.ihtml
  centreon/www/include/configuration/configNagios/formNagios.php
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-next.php
  centreon/www/install/var/baseconf/centreon-broker.sql
  centreon/www/install/var/baseconf/centreon-engine.sql
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis

#7417 chore(release) bump composer
  centreon-awie/composer.json
  centreon-dsm/composer.json
  centreon-open-tickets/composer.json
  centreon/composer.json
Labels: qa-approved

#7323 MON-168424 Centreon next 23.04 (Jira release #20815#)
  .github/CODEOWNERS
  .github/actions/create-jira-ticket/action.yml
  .github/actions/create-jira-ticket/nightly-ticket-template.json
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/get-pr-labels/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/package/action.yml
  .github/actions/publish-report/action.yml
  .github/actions/publish-unit-test-result/action.yml
  .github/actions/web-frontend-component-test/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/behat-test.yml
  .github/workflows/check-qa-validation.yml
  .github/workflows/check-status.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/gitleaks.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
  .gitleaks.toml
  .version.centreon-web
  centreon/composer.lock
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/webpack.config.js
  centreon/www/api/class/centreon_ceip.class.php
  centreon/www/include/Administration/corePerformance/nagiosStats.html
  centreon/www/include/common/javascript/index.html
  centreon/www/include/common/javascript/moment-with-locales.min.2.21.js
  centreon/www/include/common/javascript/moment-with-locales.min.2.29.4.js
  centreon/www/include/core/header/htmlHeader.php
  centreon/www/include/monitoring/objectDetails/template/hostDetails.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/views/graphs/graph-periods.html
  centreon/www/include/views/graphs/graph-split.html
  centreon/www/include/views/graphs/graphs.html
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update.next.php.tpl
  centreon/www/install/steps/process/configFileSetup.php
  widgets/centreon-widget-graph-monitoring/graph-monitoring/configs.xml
  widgets/centreon-widget-graph-monitoring/graph-monitoring/src/index.ihtml
  widgets/centreon-widget-host-monitoring/host-monitoring/configs.xml
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.ihtml
  widgets/centreon-widget-service-monitoring/service-monitoring/configs.xml
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7243 enh(SAML): Improve SAML configuration by adding RequestedAuthnContext parameter (#7086) [dev-24.04.x]
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Authentication conditions.snap.png
  centreon/doc/API/centreon-api-v24.04.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/RequestedAuthnContextEnum.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/FindSAMLConfiguration/FindSAMLConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationTest.php
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/SAML/defaults.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: area/ui, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7414 fix(CLAPI) : Better handling of csv escaping
  centreon/www/class/centreon-clapi/centreonObject.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7331 fix(ci): remove lockfiles and development files (composer.json, etc.) from packages
  .github/actions/package-nfpm/action.yml
  .github/workflows/web.yml
  centreon/packaging/centreon-web.yaml
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis

#7365 enh(agent configuration): hide central poller for cloud users
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/FindAcsResponse.yaml
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfiguration/DeleteAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfigurationPollerLink/DeleteAgentConfigurationPollerLink.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurations.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/PollerDto.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Domain/Model/Poller.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/FindAgentConfigurations/FindAgentConfigurationsPresenter.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbReadAgentConfigurationRepository.php
  centreon/src/Core/MonitoringServer/Application/Repository/ReadMonitoringServerRepositoryInterface.php
  centreon/src/Core/MonitoringServer/Infrastructure/Repository/DbReadMonitoringServerRepository.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfiguration/DeleteAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfigurationPollerLink/DeleteAgentConfigurationPollerLinkTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurationsTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfigurationTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Listing/Columns/Action.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Listing.tsx
  centreon/www/front_src/src/AgentConfiguration/Specs/initialize.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7426 fix(ci): remove lockfiles and development files (composer.json, etc.) from packages (#7331)
  .github/actions/package-nfpm/action.yml
  .github/workflows/web.yml
  centreon/packaging/centreon-web.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis

#7425 fix(ci): remove lockfiles and development files (composer.json, etc.) from packages (#7331)
  .github/actions/package-nfpm/action.yml
  .github/workflows/web.yml
  centreon/packaging/centreon-web.yaml
Labels: skip-workflow-web-analysis

#7272 feat(UI): Implement widget BA Timeline
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Graph/Timeline/ResponsiveTimeline.tsx
  centreon/packages/ui/src/Graph/Timeline/Timeline.tsx
  centreon/packages/ui/src/Graph/index.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/src/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/src/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batimeline/src/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7256 enh(SAML): Improve SAML configuration by adding RequestedAuthnContext parameter (#7086) [dev-23.10.x]
  centreon/doc/API/centreon-api-v23.10.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/RequestedAuthnContextEnum.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/FindSAMLConfiguration/FindSAMLConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationTest.php
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/SAML/defaults.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: area/ui, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7429 Fix(agent configuration): disable "TLS Insecure" option from UI
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7383 fix(Host Categories): enh queries, and refactoring code
  centreon/src/Core/Common/Infrastructure/Repository/SqlMultipleBindTrait.php
  centreon/www/include/common/sqlCommonFunction.php
  centreon/www/include/configuration/configObject/escalation/escalation.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/formHostCategories.php
  centreon/www/include/configuration/configObject/host_categories/hostCategories.php
  centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7427 fix(ci): remove lockfiles and development files (composer.json, etc.) from packages (#7331) (#7426)
  .github/actions/package/action.yml
  centreon/libinstall/CentWeb.sh
  centreon/libinstall/functions
  centreon/packaging/centreon.spectemplate
  centreon/packaging/debian/centreon-web.install
Labels: skip-workflow-web, skip-workflow-web-analysis

#7326 Fix: Fix auto-adjustment on line chart
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a stacked bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip with a single metric when a stacked bar is hovered and a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart horizontally.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays the stacked bar chart vertically.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- does not display a tooltip when a bar is hovered and a props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays as centered to zero when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only horizontal lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- displays only vertical lines when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display axis borders when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- does not display grids when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Axis -- rotates the tick label when the props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend in list mode when the corresponding props is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Legend -- displays the legend on the right side of the graph as list when the corresponding props are set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays lines with a custom line width when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a natural style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- displays the curve in a step style when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows points when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Line style -- shows the area when the prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a metric highlighted when the graph is hovered and the metric is the nearest point.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays a tooltip when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip a single metric when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- displays the tooltip with defined values when the graph is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when null values are hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- does not display the tooltip when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is ascending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- Tooltip -- sorts metrics by their value is descending when the corresponding prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Line chart -- displays the curves with different shades when curves have same color.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- changes the unit on the left or right scales when a new unit is selected.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays mixed lines and bars in the same chart.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart centered in zero.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Chart/Chart.cypress.spec.tsx/Lines and bars -- displays stacked lines and bars in the same chart.snap.png
  centreon/packages/ui/src/Graph/Chart/Chart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/common/timeSeries/index.ts
Labels: area/ui, backport, qa-approved

#7435 fix(cron): run outdated tokens removal cron with apache user (#6545)
  centreon/packaging/scripts/centreon-web-postinstall.sh
  centreon/tmpl/install/centreon.cron
Labels: skip-workflow-web, skip-workflow-web-analysis

#7407 fix(Host Dependency): enh queries, and refactoring code
  centreon/www/include/configuration/configObject/host_dependency/DB-Func.php
  centreon/www/include/configuration/configObject/host_dependency/formHostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/hostDependency.php
  centreon/www/include/configuration/configObject/host_dependency/listHostDependency.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#7404 fix(Poller): rework access condition
  centreon/www/include/configuration/configGenerate/xml/generateFiles.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7394 fix: display down icon
  centreon/cypress/fixtures/resources/listing/listingWithStates.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays a Down icon when the parent status is null.snap.png
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/Parent.tsx
Labels: area/ui, upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved
