Repository centreon/centreon, pull requests merged in 2025-04, with the labels that each got.

#7074 Fix(test): Fix flacky test
  centreon/www/front_src/src/Login/Login.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6996 Secu(deps): Update moment on legacy pages
  centreon/www/include/Administration/corePerformance/nagiosStats.html
  centreon/www/include/common/javascript/index.html
  centreon/www/include/common/javascript/moment-with-locales.min.2.21.js
  centreon/www/include/common/javascript/moment-with-locales.min.2.29.4.js
  centreon/www/include/core/header/htmlHeader.php
  centreon/www/include/monitoring/objectDetails/template/hostDetails.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/views/graphs/graph-periods.html
  centreon/www/include/views/graphs/graph-split.html
  centreon/www/include/views/graphs/graphs.html
  centreon/www/widgets/graph-monitoring/src/index.ihtml
  centreon/www/widgets/host-monitoring/src/index.ihtml
  centreon/www/widgets/service-monitoring/src/index.ihtml
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7058 fix(nightly) downtimes test (#7033)
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/www/include/common/userTimezone.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7057 fix(nightly) downtimes test (#7033)
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/www/include/common/userTimezone.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7061 enh(SAML): Added requested authentication context property in SAML configuration endplints
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/RequestedAuthnContextEnum.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/FindSAMLConfiguration/FindSAMLConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationTest.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: area/backend

#7045 enh(open-tickets): change rights on providers listing and update submit ticket ACL (#6974)
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersPresenterInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-notification-permissions.json
  centreon-open-tickets/tests/e2e/fixtures/users/user-dashboard-administrator.json
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/install.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.01.1/php/upgrade.php
  centreon/src/Core/Dashboard/Infrastructure/Voters/DashboardVoter.php
Labels: area/backend, backport, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis, qa-approved

#6970 [Resource Status] The filters in the History tab cannot be removed with the cross (previous fix doesn't work)
  centreon/www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#6819 fix(Widget): Users under ACLs can't see the servicegroups (#6770)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#6799 fix(Widget): hostgroupMonitoring - Users under ACLs can't see the hostgroups (#6736)
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
Labels: area/backend, backport, qa-approved

#7048 enh(open-tickets): change rights on providers listing and update subm…
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersPresenterInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-notification-permissions.json
  centreon-open-tickets/tests/e2e/fixtures/users/user-dashboard-administrator.json
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/install.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.03.0/.gitignore
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.03.0/php/upgrade.php
Labels: backport, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#7100 fix(ceip): Correctly check hosts limitation
  centreon/www/api/class/centreon_ceip.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7106 chore(composer): update composer reference for centreon-test-lib
  centreon/composer.lock
Labels: skip-workflow-web, skip-workflow-web-analysis

#7102 fix(composer): update composer reference for centreon-test-lib
  centreon/composer.lock
  centreon/features/bootstrap/DowntimeDSTContext.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7112 E2E(test) fix service-uri e2e cypress test on dev-24.10.x
  centreon/tests/e2e/features/Services-configuration/13-uri-configuration/index.ts
Labels: area/test

#7047 enh(SAML): Added selector Requested Authentication Context in SAML configuration form
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Activation.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Authentication conditions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Auto import users.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Groups mapping.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Identity provider.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Roles mapping.snap.png
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/SAML/defaults.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
Labels: skip-workflow-web

#7096 Fix(test): Fix login test
  centreon/www/front_src/src/Login/Login.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#6975 Fix(UI: Fix status chart filters
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/Legend/Legend.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/Tooltip/Tooltip.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7069 Fix(secu): upgrade axios
  centreon/package.json
  centreon/pnpm-lock.yaml
  centreon/webpack.config.js
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7068 Fix(secu): Upgrade axios
  centreon/package.json
  centreon/pnpm-lock.yaml
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7085 Secu(deps): Update moment on legacy pages (#6996)
  centreon/www/include/Administration/corePerformance/nagiosStats.html
  centreon/www/include/common/javascript/index.html
  centreon/www/include/common/javascript/moment-with-locales.min.2.21.js
  centreon/www/include/common/javascript/moment-with-locales.min.2.29.4.js
  centreon/www/include/core/header/htmlHeader.php
  centreon/www/include/monitoring/objectDetails/template/hostDetails.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/views/graphs/graph-periods.html
  centreon/www/include/views/graphs/graph-split.html
  centreon/www/include/views/graphs/graphs.html
  centreon/www/widgets/graph-monitoring/src/index.ihtml
  centreon/www/widgets/host-monitoring/src/index.ihtml
  centreon/www/widgets/service-monitoring/src/index.ihtml
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7109 chore(composer): update composer reference for centreon-test-lib
  centreon/composer.lock
Labels: skip-workflow-web, skip-workflow-web-analysis

#7121 fix(nightly) downtimes test (#7033) (#7056)
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/www/include/common/userTimezone.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7083 enh(tokens): Rename API Tokens to Authentication Tokens in topology
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Core/Security/Token/Application/UseCase/DeleteToken/DeleteToken.php
  centreon/src/Core/Security/Token/Application/UseCase/PartialUpdateToken/PartialUpdateToken.php
  centreon/src/Core/Security/Token/Infrastructure/Voters/TokenVoters.php
  centreon/tests/e2e/features/Api-Token/03-api-token-sorting.feature
  centreon/tests/e2e/features/Api-Token/04-api-token-delete.feature
  centreon/tests/e2e/features/Api-Token/05-api-token-acl-rights.feature
  centreon/tests/e2e/features/Api-Token/06-api-token-filter.feature
  centreon/tests/php/Core/Security/Token/Application/UseCase/FindTokens/FindTokensTest.php
  centreon/tests/rest_api/collections/authentication/Tokens.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Add_needed_users.postman_collection.json
  centreon/www/install/insertTopology.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web

#7128 fix(nightly): fix downtime test (#7055)
  centreon/features/bootstrap/DowntimeDSTContext.php
Labels: area/backend, area/test, backport

#7125 fix(WIDGET): back to deprecated method initSmartyTplForPopup for 22.10
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#7129 enh (Knowledge): migrate the knowledge base configuration behat test to a cypress test (#6813)
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/tests/e2e/features/Knowledges/01-knowledge-base.feature
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
  centreon/tests/e2e/features/Knowledges/common.ts
Labels: skip-workflow-web-analysis

#7126 fix(BEHAT): DOM not loaded
  centreon/features/bootstrap/GeneratePollerContext.php
  centreon/features/bootstrap/KnowledgeBaseContext.php
Labels: area/backend

#7072 fix(purge): make regexp compatible with mysql and mariadb (#6961)
  centreon/www/class/centreonPurgeEngine.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7114 chore(deps): absorb 2025-04 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/lighthouse-to-s3/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/package/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/actions/veracode-generate-binary/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/behat-test.yml
  .github/workflows/clean-npm-tags.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/get-environment.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#6927 enh(agent configuration): Allow sub-directories in certificate configuration
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a poller when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- backs to the form when the Stay button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- leaves the form when the Leave button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/AgentConfiguration/Application/Validation/CmaValidator.php
  centreon/src/Core/AgentConfiguration/Application/Validation/TelegrafValidator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/TelegrafConfigurationParameters.php
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/02-agent-configuration-listing/index.ts
  centreon/tests/e2e/features/Agent-configuration/03-agent-configuration-deletion/index.ts
  centreon/tests/e2e/features/Agent-configuration/04-agent-configuration-update/index.ts
  centreon/tests/e2e/features/Agent-configuration/05-agent-configuration-check-permissions/index.ts
  centreon/tests/e2e/features/Agent-configuration/commands.ts
  centreon/tests/e2e/fixtures/agents-configuration/agent-config.json
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/CmaValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/TelegrafValidatorTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/CmaConfigurationParametersTest.php
  centreon/tests/php/Core/AgentConfiguration/Domain/Model/TelegrafConfigurationParametersTest.php
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
  centreon/www/install/php/Update-next.php
Labels: area/ui, area/backend, skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-docker-vault, skip-workflow-web-analysis, skip-workflow-docker-translation, skip-workflow-docker-keycloak, skip-workflow-docker-glpi, skip-workflow-docker-packaging

#7131 fix(BEHAT): DOM not loaded (#7126)
  centreon/features/bootstrap/GeneratePollerContext.php
  centreon/features/bootstrap/KnowledgeBaseContext.php
Labels: area/backend, backport

#7136 fixes
  centreon/src/Core/HostGroup/Application/UseCase/UpdateHostGroup/UpdateHostGroup.php
  centreon/src/Core/HostGroup/Infrastructure/Serializer/HostGroupNormalizer.php
  centreon/src/Core/HostGroup/Infrastructure/Serializer/HostGroupRelationNormalizer.php
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Notifications.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
  centreon/www/install/insertTopology.sql
Labels: skip-workflow-web

#7123 enh(composer) : realign composer
  centreon-awie/composer.lock
  centreon/composer.lock
Labels: area/backend, skip-cherry-pick

#6979 MON-163222 Centreon next hotfix 25.01 OSS (Jira release #20550#)
  .github/workflows/veracode-analysis.yml
  .version.centreon-open-tickets
  .version.centreon-web
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-notification-permissions.json
  centreon-open-tickets/tests/e2e/fixtures/users/user-dashboard-administrator.json
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/install.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.01.1/.gitignore
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/25.01.1/php/upgrade.php
  centreon/behat.yml
  centreon/features/KnowledgeBase.feature
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/features/bootstrap/KnowledgeBaseContext.php
  centreon/src/Core/Dashboard/Infrastructure/Voters/DashboardVoter.php
  centreon/tests/e2e/features/Knowledges/01-knowledge-base.feature
  centreon/tests/e2e/features/Knowledges/01-knowledge-base/index.ts
  centreon/tests/e2e/features/Knowledges/common.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-25.01.2.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis

#7127 Fix([Resource Status]):Calculation type tile is displayed twice
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#7082 enh(conf): enhance rights for database config file
  centreon/www/install/steps/process/configFileSetup.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7103 fix(ceip): fix bad value in LACCESS in metadata
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#7042 fix(sql) Agent configuration topology update
  centreon/www/install/php/Update-24.10.3.php
  centreon/www/install/php/Update-25.01.0.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7067 Fix(secu): Upgrade axios
  centreon/package.json
  centreon/pnpm-lock.yaml
Labels: area/ui, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7142 Feat(configuration): host groups revamp, work on QA feedbacks
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/Multi connected autocomplete -- displays all options on the list when the user searches for and selects an option.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/Multi connected autocomplete -- displays exactly one option on the list when the user types that option.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/checks all options when Select all button is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/displays the list when the user clicks on the input.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/hides the list when the user clicks on the input.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx/unchecks all options when unSelect all button is clicked.snap.png
  centreon/packages/ui/src/Form/CollapsibleGroup.tsx
  centreon/packages/ui/src/Form/Inputs/ConnectedAutocomplete.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/MultiConnectedAutocompleteField.cypress.spec.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/index.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/Listbox.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/Multi.styles.ts
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/Multi.tsx
  centreon/packages/ui/src/InputField/Select/Autocomplete/Multi/index.tsx
  centreon/packages/ui/src/InputField/translatedLabels.ts
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/www/front_src/src/Configuration/HostGroups/Form/useFormInputs.tsx
  centreon/www/front_src/src/Configuration/HostGroups/Specs/HostGroups.Modal.tsx
  centreon/www/front_src/src/Configuration/HostGroups/translatedLabels.ts
Labels: area/ui, skip-workflow-web

#7115 fix(test): failing script upgrade for cloud
  centreon/packages/js-config/cypress/e2e/configuration.ts
  centreon/packages/js-config/cypress/e2e/tasks.ts
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade.feature
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
  centreon/tests/e2e/features/Platform-upgrade-update/commands.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/test

#7026 enh(test): Add JSON schema validation
  centreon/tests/rest_api/collections/configuration/Access_Group.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Additional_Connector_Configuration.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Agent_Configuration.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Broker_Input_Output.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Command.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Connectors.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Contact_Groups.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Contact_Templates.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Contact_with_Open_API.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Contact_without_Open_API.postman_collection.json
Labels: area/test

#7088 Secu(deps): Update moment on legacy pages (#6996)
  centreon/www/include/Administration/corePerformance/nagiosStats.html
  centreon/www/include/common/javascript/index.html
  centreon/www/include/common/javascript/moment-with-locales.min.2.21.js
  centreon/www/include/common/javascript/moment-with-locales.min.2.29.4.js
  centreon/www/include/core/header/htmlHeader.php
  centreon/www/include/monitoring/objectDetails/template/hostDetails.ihtml
  centreon/www/include/monitoring/status/Services/templates/service.ihtml
  centreon/www/include/views/graphs/graph-periods.html
  centreon/www/include/views/graphs/graph-split.html
  centreon/www/include/views/graphs/graphs.html
  widgets/centreon-widget-graph-monitoring/graph-monitoring/src/index.ihtml
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.ihtml
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.ihtml
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7162 Enh(Agent configuration) - Allow connection without TLS
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- cancels a poller deletion when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- clears filters when filters are populated and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a poller when the corresponding icon is clicked and the corresponding is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected agent type when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes a selected poller when the icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- deletes an agent when the corresponding action icon is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays a welcome label when the listing is empty.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- displays the listing.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when a column sort is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations -- sends a request when the search and filters are updated.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- backs to the form when the Stay button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- configures the host address and port when a host is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays a warning message when switching the encryption level to No TLS for Telegraf and CMA agents.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the CMA form when the CMA agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- displays the encryption level field with TLS preselected as the default value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when fields contain errors.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- does not validate the form when there is no host configuration.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- handle the form without certificate fields when setting encryption level to No TLS for CMA agent.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- handle the form without certificate fields when setting encryption level to No TLS for Telegraf agent.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- leaves the form when the Leave button of the popup is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- removes a host configuration when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- resets the form when a different agent type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the CMA agent type when the form is valid and the save button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when a listing row is clicked, fields are valid, the cancel button is clicked and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- sends the form when fields are valid and the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- splits the address and the port when a full address is pasted in the address field.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- validates the form when fields are filled and the reverse switch is unchecked.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Form/Inputs/Grid.tsx
  centreon/packages/ui/src/Form/Inputs/index.tsx
  centreon/packages/ui/src/Form/Inputs/models.ts
  centreon/www/front_src/src/AgentConfiguration/Form/AddModal.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Buttons.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Empty.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Form.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Form/Modal.styles.ts
  centreon/www/front_src/src/AgentConfiguration/Form/UpdateModal.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/Warning/Warning.styles.ts
  centreon/www/front_src/src/AgentConfiguration/Form/Warning/Warning.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/useInputs.ts
  centreon/www/front_src/src/AgentConfiguration/Form/useValidationSchema.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/Specs/initialize.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useGetAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
Labels: area/ui

#7031 feat(os): add Centreon support for Ubuntu 24.04/Noble Numbat
  .github/actions/deb-delivery/action.yml
  .github/actions/parse-distrib/action.yml
  .github/docker/Dockerfile.packaging-nfpm-noble
  .github/docker/centreon-web/noble/Dockerfile
  .github/docker/centreon-web/noble/Dockerfile.dependencies
  .github/docker/centreon-web/noble/configuration/admin.json
  .github/docker/centreon-web/noble/configuration/broker.json
  .github/docker/centreon-web/noble/configuration/configuration.json
  .github/docker/centreon-web/noble/configuration/database.json
  .github/docker/centreon-web/noble/configuration/engine.json
  .github/docker/centreon-web/noble/entrypoint/container.d/00-init.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/10-mysql.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/15-installation.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/20-configuration_files.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/30-broker.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/40-engine.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/50-php.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/60-apache.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/70-gorgone.sh
  .github/docker/centreon-web/noble/entrypoint/container.d/99-logs.sh
  .github/docker/centreon-web/noble/entrypoint/container.sh
  .github/workflows/awie.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis, skip-workflow-docker-packaging

#7156 fix(ceip): fix bad value in LACCESS in metadata (#7103)
  centreon/www/api/class/centreon_ceip.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7158 fix(ceip): fix bad value in LACCESS in metadata (#7103)
  centreon/www/api/class/centreon_ceip.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7043 fix(sql) agent configuration topology update
  centreon/www/install/php/Update-24.10.3.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7160 fix(ceip): fix bad value in LACCESS in metadata (#7103)
  centreon/www/api/class/centreon_ceip.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7161 enh(test): Add JSON schema validation part 2
  centreon/tests/rest_api/collections/configuration/Export_Conf_Monitoring_Servers.postman_collection.json
  centreon/tests/rest_api/collections/configuration/GraphTemplate.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Category.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Group.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Severity.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Host_Template.postman_collection.json
Labels: area/test

#7146 fix(BEHAT): DOM not loaded on KnowledgeBaseContext::iAddAProcedureCon…
  centreon/features/bootstrap/KnowledgeBaseContext.php
Labels: area/backend

#7181 fix(BEHAT): DOM not loaded on KnowledgeBaseContext::iAddAProcedureCon…
  centreon/features/bootstrap/KnowledgeBaseContext.php
Labels: area/backend, backport

#7163 enh(conf): enhance rights for database config file (#7082)
  centreon/www/install/steps/process/configFileSetup.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7164 enh(conf): enhance rights for database config file (#7082)
  centreon/www/install/steps/process/configFileSetup.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7165 enh(conf): enhance rights for database config file (#7082)
  centreon/www/install/steps/process/configFileSetup.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7144 enh(database) : a repository manager created to use transactions in use cases
  centreon/config/packages/Centreon.yaml
  centreon/phpstan.core.neon
  centreon/src/Centreon/Domain/Repository/Interfaces/DataStorageEngineInterface.php
  centreon/src/Centreon/Infrastructure/Repository/DataStorageEngineRdb.php
  centreon/src/Core/AgentConfiguration/Application/Repository/WriteAgentConfigurationRepositoryInterface.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfiguration/DeleteAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfigurationPollerLink/DeleteAgentConfigurationPollerLink.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurations.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbWriteAgentConfigurationRepository.php
  centreon/src/Core/Common/Application/Repository/RepositoryManagerInterface.php
  centreon/src/Core/Common/Infrastructure/Repository/DatabaseRepositoryManager.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfigurationTest.php
  centreon/tests/php/Core/Common/Infrastructure/Repository/DatabaseRepositoryManagerTest.php
Labels: enhancement, area/backend, database, skip-workflow-web, skip-workflow-web-analysis

#7086 enh(SAML): Improve SAML configuration by adding RequestedAuthnContext parameter
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Activation.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Authentication conditions.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Auto import users.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Groups mapping.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Identity provider.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx/displays the SAML configuration form - Roles mapping.snap.png
  centreon/doc/API/centreon-api.yaml
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/Settings/Formatter/OneLoginSettingsFormatter.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationResponse.php
  centreon/src/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationRequest.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/CustomConfiguration.php
  centreon/src/Core/Security/ProviderConfiguration/Domain/SAML/Model/RequestedAuthnContextEnum.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/FindSAMLConfiguration/FindSAMLConfigurationPresenter.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationController.php
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Api/UpdateSAMLConfiguration/UpdateSAMLConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/CustomConfigurationSchema.json
  centreon/src/Core/Security/ProviderConfiguration/Infrastructure/SAML/Repository/DbWriteSAMLConfigurationRepository.php
  centreon/tests/e2e/features/Authentication/SAML/common.ts
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/FindSAMLConfiguration/FindSAMLConfigurationTest.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationPresenterStub.php
  centreon/tests/php/Core/Security/ProviderConfiguration/Application/SAML/UseCase/UpdateSAMLConfiguration/UpdateSAMLConfigurationTest.php
  centreon/www/front_src/src/Authentication/SAML/Form/RequestedAuthnContextField.tsx
  centreon/www/front_src/src/Authentication/SAML/Form/inputs.ts
  centreon/www/front_src/src/Authentication/SAML/SAMLConfiguration.cypress.spec.tsx
  centreon/www/front_src/src/Authentication/SAML/defaults.ts
  centreon/www/front_src/src/Authentication/SAML/models.ts
  centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts
  centreon/www/front_src/src/Authentication/api/adapters.ts
  centreon/www/front_src/src/Authentication/api/decoders.ts
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-next.php
Labels: area/ui, area/backend, skip-workflow-web, skip-workflow-web-analysis

#7190 update RAM listing rules
  centreon/src/Core/ResourceAccess/Application/Repository/ReadResourceAccessRepositoryInterface.php
  centreon/src/Core/ResourceAccess/Application/UseCase/FindRules/FindRules.php
  centreon/src/Core/ResourceAccess/Infrastructure/Repository/DbReadResourceAccessRepository.php
  centreon/tests/php/Core/ResourceAccess/Application/UseCase/FindRules/FindRulesTest.php
Labels: skip-workflow-web

#7188 fix(CI): flaky test for host groups list
  centreon/www/front_src/src/Configuration/HostGroups/HostGroupsConfiguration.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#7191 fix(Update): Remove conflit artefact from update script
  centreon/www/install/php/Update-next.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis

#7050 enh(export): Retrieve data from vault before conf export
  centreon/composer.json
  centreon/composer.lock
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Common/Application/Repository/ReadVaultRepositoryInterface.php
  centreon/src/Core/Common/Infrastructure/Repository/AbstractVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/ReadVaultRepository.php
  centreon/src/Core/Common/Infrastructure/Repository/WriteVaultRepository.php
  centreon/src/Core/Host/Application/UseCase/PartialUpdateHost/PartialUpdateHost.php
  centreon/src/Core/HostTemplate/Application/UseCase/PartialUpdateHostTemplate/PartialUpdateHostTemplate.php
  centreon/www/class/centreonConfigCentreonBroker.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/abstract/host.class.php
  centreon/www/class/config-generate/abstract/object.class.php
  centreon/www/class/config-generate/abstract/objectJSON.class.php
  centreon/www/class/config-generate/broker.class.php
  centreon/www/class/config-generate/generate.class.php
  centreon/www/class/config-generate/macro.class.php
  centreon/www/class/config-generate/resource.class.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configResources/DB-Func.php
  centreon/www/include/configuration/configResources/formResources.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7197 Fix(Web):update payload
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/utils.ts
Labels: skip-workflow-web

#7174 enh(test): Add JSON schema validation part 3
  centreon/tests/rest_api/collections/configuration/Notifications.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service_Category.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service_Group.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service_Severity.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Service_Template.postman_collection.json
  centreon/tests/rest_api/collections/configuration/Timeperiod.postman_collection.json
Labels: area/test

#7200 enh(upgrade): add file update-next.php with php content for next release (#6766)
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update-next.php.tpl
Labels: skip-workflow-web-analysis

#7207 chore(release) bump hotfix web 24.10.7
  .version.centreon-web
  centreon/www/install/insertBaseConf.sql
Labels: skip-cherry-pick

#7199 fix(upgrade): Correctly Upsert connector
  centreon/www/install/php/Update-25.03.0.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7183 Fix(UI: Fix status chart filters
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Metrics/useListMetrics.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useSaveDashboard.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/utils.ts
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Legend/Legend.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Tooltip/Tooltip.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7212 FIx[CI]: Fix flacky component test
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Custom login page with data -- displays the login page when it is customized.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Default custom login page -- displays the login page with default custom login data when the IT edition extensions module is installed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- displays a fallback page when a provider is forced and an error occurred during authentication.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- displays errors when fields are cleared.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- displays the login page.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- displays the password when the corresponding action is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- does not submit the credentials when they are invalid and the Connect button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login Page -- stays on the login page when the login request returns a 500 error.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Login/Login.cypress.spec.tsx/Login page without module it edition extensions installed -- displays the login page when the IT edition extensions module is not installed.snap.png
  centreon/www/front_src/src/Login/Login.cypress.spec.tsx
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis

#7204 fix(upgrade): correctly upsert connector
  centreon/www/install/php/Update-25.03.0.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7205 fix(upgrade): correctly upsert connector
  centreon/www/install/php/Update-24.10.6.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7101 handle JWT token for CMA
  centreon/composer.json
  centreon/composer.lock
  centreon/src/Core/Security/Token/Application/Repository/ReadTokenRepositoryInterface.php
  centreon/src/Core/Security/Token/Application/UseCase/AddToken/AddToken.php
  centreon/src/Core/Security/Token/Application/UseCase/AddToken/AddTokenResponse.php
  centreon/src/Core/Security/Token/Application/UseCase/DeleteToken/DeleteToken.php
  centreon/src/Core/Security/Token/Application/UseCase/FindTokens/FindTokens.php
  centreon/src/Core/Security/Token/Application/UseCase/GetToken/GetToken.php
  centreon/src/Core/Security/Token/Application/UseCase/GetToken/GetTokenResponse.php
  centreon/src/Core/Security/Token/Application/UseCase/PartialUpdateToken/PartialUpdateToken.php
  centreon/src/Core/Security/Token/Domain/Model/ApiToken.php
  centreon/src/Core/Security/Token/Domain/Model/JwtToken.php
  centreon/src/Core/Security/Token/Domain/Model/NewApiToken.php
  centreon/src/Core/Security/Token/Domain/Model/NewJwtToken.php
  centreon/src/Core/Security/Token/Domain/Model/NewToken.php
  centreon/src/Core/Security/Token/Domain/Model/Token.php
  centreon/src/Core/Security/Token/Domain/Model/TokenFactory.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbReadTokenRepository.php
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbWriteTokenRepository.php
  centreon/src/Core/Security/Token/Infrastructure/Serializer/TokenResponseNormalizer.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/AddToken/AddTokenTest.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/DeleteToken/DeleteTokenTest.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/FindTokens/FindTokensTest.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/GetToken/GetTokenTest.php
  centreon/tests/php/Core/Security/Token/Application/UseCase/PartialUpdateToken/PartialUpdateTokenTest.php
  centreon/tests/php/Core/Security/Token/Domain/Model/ApiTokenTest.php
  centreon/tests/php/Core/Security/Token/Domain/Model/JwtTokenTest.php
  centreon/tests/php/Core/Security/Token/Domain/Model/NewApiTokenTest.php
  centreon/tests/php/Core/Security/Token/Domain/Model/NewJwtTokenTest.php
  centreon/tests/rest_api/collections/authentication/Tokens.postman_collection.json
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web

#7206 fix(upgrade): correctly upsert connector #7205
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/www/include/common/userTimezone.php
  centreon/www/install/php/Update-24.10.6.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7130 fix(resources status): search on resources status with '/' fixed
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/utils.ts
  centreon/www/front_src/src/Resources/Filter/index.tsx
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis

#7209 Fix(UI): Fix status chart filters
  centreon/www/widgets/src/centreon-widget-statuschart/src/Chart/Chart.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/Legend/Legend.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7230 enh(database) : a repository manager created to use transactions in use cases
  centreon/config/packages/Centreon.yaml
  centreon/phpstan.core.neon
  centreon/src/Centreon/Domain/Repository/Interfaces/DataStorageEngineInterface.php
  centreon/src/Centreon/Infrastructure/Repository/DataStorageEngineRdb.php
  centreon/src/Core/AgentConfiguration/Application/Repository/WriteAgentConfigurationRepositoryInterface.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfiguration/DeleteAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/DeleteAgentConfigurationPollerLink/DeleteAgentConfigurationPollerLink.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfiguration/FindAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/FindAgentConfigurations/FindAgentConfigurations.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfiguration.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbWriteAgentConfigurationRepository.php
  centreon/src/Core/Common/Application/Repository/RepositoryManagerInterface.php
  centreon/src/Core/Common/Infrastructure/Repository/DatabaseRepositoryManager.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/AddAgentConfigurationTest.php
  centreon/tests/php/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/UpdateAgentConfigurationTest.php
  centreon/tests/php/Core/Common/Infrastructure/Repository/DatabaseRepositoryManagerTest.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7227 MON-166601 Centreon next hotfix 24.10 OSS (Jira release #20717#)
  .github/workflows/veracode-analysis.yml
  .version.centreon-web
  centreon/features/bootstrap/DowntimeDSTContext.php
  centreon/www/include/common/userTimezone.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.6.php
  centreon/www/install/php/Update-24.10.7.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7236 Backport([dev-24.10.x] [Resource Status]): Calculation type tile is displayed twice
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis

#7237 Backport([dev-24.04.x] :[Resource Status]): Calculation type tile is displayed twice
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7233 fix(resources status): search on resources status with '/' fixed
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/utils.ts
Labels: bug, area/ui, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7234 fix(resources status): search on resources status with '/' fixed
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/www/front_src/src/Resources/Filter/index.tsx
  centreon/www/widgets/src/centreon-widget-statuschart/src/api/endpoint.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridCondensed/Tooltip/useLoadResources.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/api/endpoints.ts
  centreon/www/widgets/src/utils.ts
Labels: bug, area/ui, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7244 Feat(Authentication token): adjustment due to the listing no longer returning the user for cma tokens
  centreon/www/front_src/src/AuthenticationTokens/Dialogs/Delete/useDelete.ts
  centreon/www/front_src/src/AuthenticationTokens/Dialogs/Disable/useDisable.ts
  centreon/www/front_src/src/AuthenticationTokens/Dialogs/Enable/useEnable.ts
  centreon/www/front_src/src/AuthenticationTokens/Listing/Columns/ActionsColumn/Actions.tsx
  centreon/www/front_src/src/AuthenticationTokens/Listing/Columns/Columns.tsx
  centreon/www/front_src/src/AuthenticationTokens/api/decoder.ts
Labels: area/ui, skip-workflow-web

#7249 fix update and delete
  centreon/src/Core/Security/Token/Infrastructure/Repository/DbWriteTokenRepository.php
Labels: skip-workflow-web

#7217 fix(upgrade): edit update-next and tpl file + fix cypress tests
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-24.10.6.php
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update-next.php.tpl
Labels: skip-workflow-web, skip-workflow-web-analysis

#7202 enh(upgrade): add file update-next.php with php content for next release (#6766)
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-24.04.10.php
  centreon/www/install/php/Update-24.04.13.php
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update-next.php.tpl
Labels: skip-workflow-web, skip-workflow-web-analysis

#7203 enh(upgrade): add file update-next.php with php content for next release (#6766)
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-23.10.24.php
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update-next.php.tpl
Labels: skip-workflow-web, skip-workflow-web-analysis

#7210 enh(upgrade): add file update-next.php with php content for next release (#6766)
  centreon/www/install/php/Update-23.04.29.pnp
  centreon/www/install/php/Update-next.php
  centreon/www/install/php/Update.next.php.tpl
Labels: skip-workflow-web, skip-workflow-web-analysis

#7245 fix(host template): fix edit host/ht in cloud (#6986)
  centreon/doc/API/latest/Cloud/Configuration/Host/Schema/PartialUpdateHostRequest.yaml
  centreon/doc/API/latest/Cloud/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/src/Core/Host/Infrastructure/API/PartialUpdateHost/PartialUpdateHostSaasSchema.json
  centreon/src/Core/HostTemplate/Infrastructure/API/PartialUpdateHostTemplate/PartialUpdateHostTemplateSaasSchema.json
Labels: skip-workflow-web, skip-workflow-web-analysis

#7254 enh(test) : Add JSON schema validation : authentication part
  centreon/tests/rest_api/collections/authentication/Local_Authentication.postman_collection.json
  centreon/tests/rest_api/collections/authentication/Local_Provider_Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/OpenID_Provider_Configuration.postman_collection.json
  centreon/tests/rest_api/collections/authentication/Tokens.postman_collection.json
  centreon/tests/rest_api/collections/authentication/WebSSO_Provider_Configuration.postman_collection.json
Labels: area/test, qa-approved

#6787 Mon 146155 (WEB) modernize ba monitoring page
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/BarChart/BarChart.cypress.spec.tsx/Bar chart -- displays a tooltip when a single bar is hovered.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- cannot collapse a node when a node is not clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- collapses a node when a node is clickable.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- displays the tree with line links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Complex data tree -- displays the tree with step links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- cannot collapses a node when a leaf is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- collapses a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays customized links when a prop is set.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- displays the whole tree.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands a node's childrens when a node is clicked.snap.png
  centreon/packages/ui/cypress/visual-testing-snapshots/src/Graph/Tree/Tree.cypress.spec.tsx/Simple data tree -- expands nodes by default when a prop is set.snap.png
  centreon/packages/ui/src/Graph/Tree/Links.tsx
  centreon/packages/ui/src/Graph/Tree/Tree.tsx
  centreon/packages/ui/src/Graph/Tree/constants.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/hooks/useLinkToResourceStatus.ts
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7267 Enh(Agent configuration): Poller-initiated connection - display Host name
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/HostConfiguration.tsx
  centreon/www/front_src/src/AgentConfiguration/Form/HostConfigurations/useHostConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/api/decoders.ts
  centreon/www/front_src/src/AgentConfiguration/hooks/useAddUpdateAgentConfiguration.ts
  centreon/www/front_src/src/AgentConfiguration/models.ts
Labels: area/ui, skip-workflow-web

#7038 enh(symfony) : check of symfony configuration added on local and ci
  .github/workflows/web.yml
  centreon/composer.json
  centreon/composer.lock
  centreon/config/packages/Centreon.yaml
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginPresenterStub.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginTest.php
Labels: enhancement, area/backend, skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#7235 fix(resources status): search on resources status with '/' fixed
  centreon/src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
  centreon/www/front_src/src/Resources/Filter/index.tsx
Labels: bug, area/ui, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7278 enh(Agent Configuration): add insecure connection mode to api
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/AddAcRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/AddAcResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/FindAcsResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/GetAcResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/Schema/UpdateAcRequest.yaml
  centreon/src/Core/AgentConfiguration/Application/UseCase/AddAgentConfiguration/Validator.php
  centreon/src/Core/AgentConfiguration/Application/UseCase/UpdateAgentConfiguration/Validator.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/CmaConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConfigurationParameters/TelegrafConfigurationParameters.php
  centreon/src/Core/AgentConfiguration/Domain/Model/ConnectionModeEnum.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/AddAgentConfiguration/AddAgentConfigurationController.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/AddAgentConfiguration/AddAgentConfigurationPresenter.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/AddAgentConfiguration/AddAgentConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/API/UpdateAgentConfiguration/UpdateAgentConfigurationController.php
  centreon/src/Core/AgentConfiguration/Infrastructure/API/UpdateAgentConfiguration/UpdateAgentConfigurationSchema.json
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbReadAgentConfigurationRepository.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Repository/DbWriteAgentConfigurationRepository.php
  centreon/src/Core/AgentConfiguration/Infrastructure/Serializer/AgentConfigurationNormalizer.php
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web

#7260 Backport([dev-24.10.x][Resources Status]): Graph - Filling and invert options are the inverse of the curve template
  centreon/packages/ui/src/Graph/Chart/useChartData.ts
Labels: qa-approved

#7281 enh(symfony) : check of symfony configuration added on local and ci
  .github/workflows/web.yml
  centreon/composer.json
  centreon/composer.lock
  centreon/config/packages/Centreon.yaml
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginPresenterStub.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginTest.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7282 enh(symfony) : check of symfony configuration added on local and ci
  .github/workflows/web.yml
  centreon/composer.json
  centreon/composer.lock
  centreon/config/packages/Centreon.yaml
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginPresenterStub.php
  centreon/tests/php/Core/Security/Authentication/Application/UseCase/Login/LoginTest.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis

#7255 fix(services): Check that inherited templates has a check command
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/formService.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7286 apply ux/ui feedbacks
  centreon/packages/ui/src/Listing/ActionBar/index.tsx
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Actions/exportToCsv/RadioButtons.tsx
  centreon/www/front_src/src/Resources/Actions/exportToCsv/exportCsv.styles.ts
Labels: skip-workflow-web

#7289 fix(ldap): fix custom filter validation (#7171)
  centreon/www/class/centreonLDAP.class.php
  centreon/www/include/Administration/parameters/ldap/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7290 fix(ldap): fix custom filter validation (#7171)
  centreon/www/class/centreonLDAP.class.php
  centreon/www/include/Administration/parameters/ldap/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7296 fix(services): Check that inherited templates has a check command (#7255)
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/formService.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7297 fix(services): Check that inherited templates has a check command (#7255)
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/formService.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#7287 feat(tests): Automate the 'Allow connection without TLS' functionality in the agent configuration using Cypress
  centreon/tests/e2e/features/Agent-configuration/06-agent-configuration-tls-mode.feature
  centreon/tests/e2e/features/Agent-configuration/06-agent-configuration-tls-mode/index.ts
Labels: area/test

#7294 feat(tests): Automate the 'Allow connection without TLS' functionality in the agent configuration using Cypress - 24.10
  centreon/tests/e2e/features/Agent-configuration/06-agent-configuration-tls-mode.feature
  centreon/tests/e2e/features/Agent-configuration/06-agent-configuration-tls-mode/index.ts
Labels: area/test, backport, qa-approved

#7241 fix(SESSION): Improper Access Control on Sessions allowing a non-admi…
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/options/session/connected_user.php
Labels: area/backend, skip-workflow-web-analysis, qa-approved

#6937 fix(CLOUD): fix + rewrite/refactoring code
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration/index.ts
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.ihtml
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/meta_service/help.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7248 enh(open-tickets): change rights on providers listing and update submit ticket ACL (#6974) (#7045)
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/Repository/ReadProviderRepositoryInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProviders.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersPresenterInterface.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Application/UseCase/FindProvidersResponse.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersController.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/API/FindProviders/FindProvidersPresenter.php
  centreon-open-tickets/src/CentreonOpenTickets/Providers/Infrastructure/Repository/DbReadProviderRepository.php
  centreon-open-tickets/tests/e2e/features/Dashboards/01-open-ticket-configuration/index.ts
  centreon-open-tickets/tests/e2e/features/Dashboards/commands.ts
  centreon-open-tickets/tests/e2e/fixtures/resources/clapi/config-ACL/dashboard-notification-permissions.json
  centreon-open-tickets/tests/e2e/fixtures/users/user-dashboard-administrator.json
  centreon-open-tickets/tests/php/CentreonOpenTickets/Providers/Application/UseCase/FindProviders/FindProvidersTest.php
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/install.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/sql/uninstall.sql
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.10.3/php/upgrade.php
  centreon/src/Core/Dashboard/Infrastructure/Voters/DashboardVoter.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-open-tickets, skip-workflow-web-analysis, skip-workflow-open-tickets-analysis, qa-approved

#7214 ENH([Dashboards]):[Metrics Graph] Display any information to help identify the selected metric
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/graph.json
  centreon/cypress/fixtures/Widgets/Graph/legend/lineChartWithRedundantHostAndServiceName.json
  centreon/cypress/fixtures/Widgets/Graph/legend/lineChartWithRedundantHostName.json
  centreon/cypress/fixtures/Widgets/Graph/legend/lineChartWithRedundantServiceName.json
  centreon/cypress/fixtures/Widgets/Graph/lineChart.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays custom stacked bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the bar chart when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the customised bar chart when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart when the widget has metrics.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a lot of custom style settings when corresponding props are set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a natural curve when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with a step curve when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with customized critical threshold.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart with customized warning threshold.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the line chart without thresholds when thresholds are disabled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/Graph Widget -- displays the stacked bar chart when the corresponding prop is set.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/do not display the host and service name from the legend and tooltip when it's redundant.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/do not display the host name from the legend and tooltip when it's redundant.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx/do not display the service name from the legend and tooltip when it's redundant.snap.png
  centreon/packages/ui/src/Graph/common/timeSeries/models.ts
  centreon/packages/ui/src/api/useGraphQuery/index.ts
  centreon/src/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/PerformanceMetricsDataFactory.php
  centreon/src/Core/Dashboard/Domain/Model/Metric/PerformanceMetricsData.php
  centreon/src/Core/Dashboard/Infrastructure/API/FindPerformanceMetricsData/FindPerformanceMetricsDataPresenter.php
  centreon/src/Core/Metric/Domain/Model/MetricInformation/GeneralInformation.php
  centreon/tests/e2e/features/Dashboards/10-widget-metric-graph-configuration/index.ts
  centreon/tests/php/Core/Dashboard/Application/UseCase/FindPerformanceMetricsData/FindPerformanceMetricsDataTest.php
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7302 fix(database) : heredoc and nowdoc accepted with connection interface
  centreon/src/Adaptation/Database/Connection/Trait/ConnectionTrait.php
  centreon/tests/php/Adaptation/Database/Connection/Adapter/Dbal/DbalConnectionAdapterTest.php
  centreon/tests/php/Centreon/Infrastructure/DatabaseConnectionTest.php
  centreon/tests/php/www/class/CentreonDBTest.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis

#7219 fix(timeperiods): maxlength should match the database columns size
  centreon/www/include/configuration/configObject/timeperiod/formTimeperiod.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved
