Repository centreon/centreon, pull requests merged in 2025-08, with the labels that each got.

#7912 feat(resource-status): add an option to disable some fields on free search (#7695)
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/isResourceStatusFullSearchEnabledAtom.ts
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/www/front_src/src/App/models.ts
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/models.ts
  centreon/www/front_src/src/Resources/Filter/SearchHelp.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/SearchHelp.tsx
  centreon/www/front_src/src/Resources/Listing/useLoadResources/index.ts
  centreon/www/front_src/src/Resources/Listing/useLoadResources/useGetCriteriaName.ts
  centreon/www/front_src/src/Resources/Listing/useLoadResources/utils.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/general/form.ihtml
  centreon/www/include/Administration/parameters/general/form.php
  centreon/www/include/Administration/parameters/general/help.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.16.php
Labels: backport, skip-workflow-web-analysis, qa-approved

#7910 fix(cfg) prevent circular inheritance in service template (#7808)
  centreon/src/Core/ServiceTemplate/Application/Exception/ServiceTemplateException.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidation.php
  centreon/src/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplate.php
  centreon/src/Core/ServiceTemplate/Infrastructure/Configuration/symfony.yaml
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/ParametersValidationTest.php
  centreon/tests/php/Core/ServiceTemplate/Application/UseCase/PartialUpdateServiceTemplate/PartialUpdateServiceTemplateTest.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7876 Fix(UI): Several French translations are missing from the interface (…
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/components/DashboardSaveBlockerModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7941 fix(configuration): error 500 when geocoords are too long (#7829)
  centreon/src/Core/Domain/Common/GeoCoords.php
  centreon/tests/e2e/features/HostGroups/01-host-group-configuration/index.ts
  centreon/tests/e2e/features/HostGroups/commands.ts
  centreon/tests/e2e/features/Services-configuration/07-meta-service-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/hostGroups/hostGroup.json
  centreon/tests/e2e/fixtures/services/host_group.json
  centreon/tests/e2e/fixtures/services/meta_service.json
  centreon/tests/php/Core/Domain/GeoCoordsTest.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/hostgroup/formHostGroup.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/service/formService.php
  centreon/www/include/configuration/configObject/servicegroup/formServiceGroup.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7950 fix(routing): prefix base uri and api version for modules with only one route
  centreon/src/Core/Common/Infrastructure/Routing/ModuleRouteLoader.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7904 fix(web): host alias encoding fixed
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: bug, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7933 Fix([Dashboards]): MBI widget "Hostgroup Availability History"
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useDefaultSelectType.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-hgavailabilityhistory/properties.json
Labels: area/ui, skip-workflow-web

#7951 enh(MySQL): update default authentication plugin
  .github/docker/.env
  centreon/unattended.sh
  centreon/www/install/steps/process/createDbUser.php
Labels: database, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7959 fix(routing): prefix base uri and api version for modules with only one route (#7950)
  centreon/src/Core/Common/Infrastructure/Routing/ModuleRouteLoader.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7421 feat(ci): manage custom delivery to feature repositories
  .github/actions/rpm-delivery/action.yml
  .github/workflows/awie.yml
  .github/workflows/delete-feature-repositories.yml
  .github/workflows/dsm.yml
  .github/workflows/get-environment.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: skip-workflow-web-analysis, delivery-feature

#7948 fix(sql) make all foreign key unique
  centreon/www/install/createTables.sql
Labels: skip-workflow-web-analysis, qa-approved

#7928 fix(Custom view): restrict access to views (#7764)
  centreon/www/class/centreonCustomView.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7927 fix(Custom view): restrict access to views (#7764)
  centreon/www/class/centreonCustomView.class.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7793 enh(Authentication): OIDC End Session Endpoint parameter not taken in…
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/tests/e2e/features/Authentication/OpenID-connect/common.ts
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7911 Enh([Configuration]): Improve tooltip for "Enable shell" option
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/www/include/configuration/configObject/command/help.php
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7972 Fix(tranlsation): several french translations are missing from the interface
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/front_src/src/AgentConfiguration/Listing/DeleteModal.tsx
  centreon/www/front_src/src/AgentConfiguration/Specs/AgentConfigurations.cypress.spec.tsx
  centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/components/DashboardSaveBlockerModal.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Resources/Listing/index.tsx
  centreon/www/front_src/src/Resources/translatedLabels.ts
Labels: area/ui, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7961 fix(Cloud): Handle ACL on Meta Service
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/meta_service/listMetaService.php
  centreon/www/include/configuration/configObject/meta_service/metaService.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7967 enh(contact): increase centreon.contact.contact_pager size to 300
  centreon/www/install/createTables.sql
  centreon/www/install/php/Update-next.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7979 fix(commands): fix command_line field in connectors
  centreon/www/include/configuration/configObject/connector/formConnector.php
  centreon/www/include/configuration/configObject/connector/listConnector.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7973 fix(web): host alias encoding fixed
  centreon/www/include/configuration/configObject/host/DB-Func.php
Labels: bug, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7963 fix(CLAPI): Correctly reload ACLs after deploying services
  centreon/www/class/centreon-clapi/centreonHost.class.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7970 fix(ACL Action Access): update SQL Queries
  centreon/www/include/options/accessLists/actionsACL/DB-Func.php
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7945 MON-178723 - update swc deps
  centreon/package.json
  centreon/pnpm-lock.yaml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7944 Fix MON-37301 - Poller is seen as not enable, so we can't generate the configuration files
  centreon/www/include/configuration/configServers/DB-Func.php
  centreon/www/include/configuration/configServers/listServers.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7983 MON-179564 backport dev-24.10.x Enh([Configuration]): Improve tooltip for "Enable shell" option
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/help.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/help.po
  centreon/www/include/configuration/configObject/command/help.php
Labels: backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7994 enh(Authentication): OIDC End Session Endpoint parameter not taken in… (#7793)
  centreon/phpstan.core.neon
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/tests/e2e/features/Authentication/OpenID-connect/common.ts
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8001 fix(ACL Action Access): update SQL Queries (#7970)
  centreon/www/include/options/accessLists/actionsACL/DB-Func.php
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml
  centreon/www/include/options/accessLists/actionsACL/listsActionsAccess.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8009 feat(contact/profile) : add confirm current password field to change a user password
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Authentication/Login/02-local-authentication/index.ts
  centreon/www/class/centreonUser.class.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/formContactLight.ihtml
  centreon/www/include/configuration/configObject/contact/help.php
  centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8008 feat(contact/profile) : add confirm current password field to change a user password
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Authentication/Login/02-local-authentication/index.ts
  centreon/www/class/centreonUser.class.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/formContactLight.ihtml
  centreon/www/include/configuration/configObject/contact/help.php
  centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-cherry-pick, skip-workflow-web-analysis, qa-approved

#7992 MON-179824 Hotfix OSS 23.10 next
  .version.centreon-web
  centreon/features/DowntimeDST/Realtime.feature.ignored
  centreon/features/DowntimeDST/Recurrent.feature.ignored
  centreon/features/DowntimeRecurrent.feature.ignored
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/help.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/tests/e2e/features/Authentication/Login/02-local-authentication/index.ts
  centreon/www/class/centreonUser.class.php
  centreon/www/include/Administration/myAccount/DB-Func.php
  centreon/www/include/Administration/myAccount/formMyAccount.ihtml
  centreon/www/include/Administration/myAccount/formMyAccount.php
  centreon/www/include/configuration/configObject/contact/DB-Func.php
  centreon/www/include/configuration/configObject/contact/formContact.ihtml
  centreon/www/include/configuration/configObject/contact/formContact.php
  centreon/www/include/configuration/configObject/contact/formContactLight.ihtml
  centreon/www/include/configuration/configObject/contact/help.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.27.php
  centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#8031 fix(conf) fix otel_server.json file generation with cma tokens
  centreon/www/class/config-generate/AgentConfiguration.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7971 fix(host tempaltes): fix sql queries
  centreon/www/class/centreonHost.class.php
  centreon/www/include/configuration/configObject/host/formHost.php
  centreon/www/include/configuration/configObject/host/listHost.php
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.ihtml
  centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7982 fix(snmp): fix field name in form
  centreon/www/include/configuration/configObject/traps-groups/listGroups.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7990 fix(Cloud): Handle ACL on Meta Service (#7961)
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/meta_service/listMetaService.php
  centreon/www/include/configuration/configObject/meta_service/metaService.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7988 fix(Cloud): Handle ACL on Meta Service (#7961)
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
  centreon/www/include/configuration/configObject/meta_service/formMetaService.php
  centreon/www/include/configuration/configObject/meta_service/listMetaService.php
  centreon/www/include/configuration/configObject/meta_service/metaService.php
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8043 fix(RS): access to details page of a service which have a service group fixed
  centreon/www/front_src/src/Resources/decoders.ts
Labels: bug, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8047 fix(AC): Add an upgrade script to realign correctly CMA Configurations (#8041)
  centreon/www/install/php/Update-24.10.12.php
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis

#8044 enh(unit_test) : improvement of the organisation of PHP unit tests
  centreon-awie/composer.lock
  centreon-dsm/composer.lock
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon-open-tickets/phpunit.xml
  centreon/composer.json
  centreon/composer.lock
  centreon/symfony.lock
  centreon/tests/php/Core/Common/Infrastructure/ExceptionLogger/ExceptionLoggerTest.php
  centreon/tests/php/Core/Notification/Application/UseCase/FindNotifications/FindNotificationsTest.php
  centreon/tests/php/mock/Centreon.php
  centreon/tests/php/mock/CentreonDB.php
  centreon/tests/php/mock/CentreonDBAdapter.php
  centreon/tests/php/mock/CentreonDBManagerService.php
  centreon/tests/php/mock/CentreonDBResultSet.php
  centreon/tests/php/mock/CentreonDBStatement.php
  centreon/tests/php/mock/CentreonLog.php
  centreon/tests/php/mock/CentreonUser.php
  centreon/tests/php/mock/DependencyInjector/ConfigurationDBProvider.php
  centreon/tests/php/mock/DependencyInjector/FilesystemProvider.php
  centreon/tests/php/mock/DependencyInjector/FinderProvider.php
  centreon/tests/php/mock/DependencyInjector/ServiceContainer.php
  centreon/tests/php/mock/DependencyInjector/ServiceContainerInterface.php
  centreon/tests/php/mock/DependencyInjector/ServiceProviderInterface.php
  centreon/tests/php/mock/Mock.php
  centreon/tests/php/mock/Object/BaseObject.php
  centreon/tests/php/mock/Object/CentreonCommand.php
  centreon/tests/php/mock/Object/CentreonHost.php
  centreon/tests/php/mock/Object/CentreonHosttemplates.php
  centreon/tests/php/mock/Object/CentreonMedia.php
  centreon/tests/php/mock/Object/CentreonResources.php
  centreon/tests/php/mock/Object/CentreonRestHttp.php
  centreon/tests/php/mock/Object/CentreonService.php
  centreon/tests/php/mock/Object/CentreonServicetemplates.php
  centreon/tests/php/mock/Object/CentreonTimeperiod.php
  centreon/tests/php/mock/PEAR.php
  centreon/tests/php/mock/RestNotFoundException.php
  centreon/tests/php/www/class/CentreonLogTest.php
Labels: enhancement, area/backend, backport, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis, qa-approved

#8045 MON-179824 Sync 23.10 oss release
  .version.centreon-web
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.27.php
Labels: sync-release, skip-workflow-web, skip-workflow-awie, skip-workflow-web-analysis, skip-workflow-awie-analysis, skip-workflow-dsm-analysis, skip-workflow-open-tickets-analysis

#8090 enh(unit_tests) : php quality tools applied to mock directory
  centreon/.php-cs-fixer.legacy.php
  centreon/phpstan.legacy.test.neon
  centreon/tests/php/mock/Centreon.php
  centreon/tests/php/mock/CentreonDB.php
  centreon/tests/php/mock/CentreonDBAdapter.php
  centreon/tests/php/mock/CentreonDBManagerService.php
  centreon/tests/php/mock/CentreonDBResultSet.php
  centreon/tests/php/mock/CentreonDBStatement.php
  centreon/tests/php/mock/CentreonLog.php
  centreon/tests/php/mock/CentreonUser.php
  centreon/tests/php/mock/DependencyInjector/ConfigurationDBProvider.php
  centreon/tests/php/mock/DependencyInjector/FilesystemProvider.php
  centreon/tests/php/mock/DependencyInjector/FinderProvider.php
  centreon/tests/php/mock/DependencyInjector/ServiceContainer.php
  centreon/tests/php/mock/DependencyInjector/ServiceContainerInterface.php
  centreon/tests/php/mock/DependencyInjector/ServiceProviderInterface.php
  centreon/tests/php/mock/Mock.php
  centreon/tests/php/mock/Object/BaseObject.php
  centreon/tests/php/mock/Object/CentreonCommand.php
  centreon/tests/php/mock/Object/CentreonHost.php
  centreon/tests/php/mock/Object/CentreonHosttemplates.php
  centreon/tests/php/mock/Object/CentreonMedia.php
  centreon/tests/php/mock/Object/CentreonResources.php
  centreon/tests/php/mock/Object/CentreonRestHttp.php
  centreon/tests/php/mock/Object/CentreonService.php
  centreon/tests/php/mock/Object/CentreonServicetemplates.php
  centreon/tests/php/mock/Object/CentreonTimeperiod.php
  centreon/tests/php/mock/PEAR.php
  centreon/tests/php/mock/RestNotFoundException.php
Labels: enhancement, area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8055 fix(recurrent downtime): correctly escape characters (#7978)
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.html
Labels: skip-workflow-web-analysis, qa-approved

#8061 Remove useless condition (#7767)
  centreon/www/include/Administration/parameters/ldap/DB-Func.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8066 fix(acl): fix description field in resource access (#7977)
  centreon/www/include/options/accessLists/resourcesACL/listsResourcesAccess.ihtml
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8022 fix(Resources Status): Deleted Host/Service Groups in Configuration Persists in Resources Status Search Bar
  centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8100 fix(ci): do not send empty translations to frontend (#8095)
  .github/scripts/translation/make_translation.sh
  centreon/bin/centreon-translations.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8084 MON-181488 Hotfix OSS 25.05 next
  .version.centreon-web
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-25.05.2.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-web-analysis

#7768 fix(cron): fix centreon-token log file permissions
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8097 fix(META SERVICE): fix ACL on adding a Meta Service
  centreon/www/include/configuration/configObject/meta_service/DB-Func.php
Labels: area/backend, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7943 chore(deps): absorb 2025-08 dependabot GitHub Actions updates
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/lighthouse-performance-testing/action.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/dsm.yml
  .github/workflows/open-tickets.yml
  .github/workflows/php-tools.yml
  .github/workflows/web.yml
Labels: dependencies, gha

#8065 MON-181332 Hotfix OSS 24.10 next
  .version.centreon-web
  centreon/www/class/config-generate/AgentConfiguration.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.10.12.php
Labels: skip-workflow-web, skip-workflow-web-analysis

#8056 fix(recurrent downtime): correctly escape characters (#7978)
  centreon/www/include/monitoring/recurrentDowntime/listDowntime.html
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8074 fix(OPEN TICKET): enhance listing of opentickets rules
  centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/list.php
Labels: area/backend, skip-workflow-open-tickets, skip-workflow-open-tickets-analysis, qa-approved

#8079 fix(services): in cloud a command should be required for services
  centreon/www/include/configuration/configObject/service/formService.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8089 fix(configuration): fix error msg in export
  centreon/www/include/configuration/configGenerate/xml/moveFiles.php
Labels: skip-workflow-web, skip-workflow-web-analysis, qa-approved

#8105 fix(packaging): fix dsm purge file permissions (#7882)
  .github/workflows/dsm.yml
  centreon-dsm/cron/centreon-dsm
  centreon-dsm/packaging/centreon-dsm-server.yaml
  centreon-dsm/packaging/scripts/centreon-dsm-server-postinstall.sh
  centreon-dsm/packaging/src/centreon-macroreplacement.txt
Labels: upload-artifacts, skip-workflow-dsm, skip-workflow-dsm-analysis, qa-approved

#8104 fix(packaging): fix dsm purge file permissions (#7882)
  .github/workflows/dsm.yml
  centreon-dsm/cron/centreon-dsm
  centreon-dsm/packaging/centreon-dsm-server.yaml
  centreon-dsm/packaging/scripts/centreon-dsm-server-postinstall.sh
  centreon-dsm/packaging/src/centreon-macroreplacement.txt
Labels: upload-artifacts, skip-workflow-dsm, skip-workflow-dsm-analysis, qa-approved

#7827 feat(Dashboards): Hostgroups availability widget
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Graph/BarChart/BarChart.stories.tsx
  centreon/packages/ui/src/Graph/BarChart/BarChart.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.cypress.spec.tsx
  centreon/packages/ui/src/Graph/Chart/Chart.tsx
  centreon/packages/ui/src/Graph/Chart/models.ts
  centreon/packages/ui/src/Graph/common/timeSeries/index.ts
  centreon/packages/ui/src/InputField/Select/index.tsx
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadRealTimeHostCategoryRepository.php
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Boundaries.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Radio/Radio.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/Resources.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useDefaultSelectType.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Resources/useResources.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Select/Select.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/common/Tooltip.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/SubInputs.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/handleHiddenConditions.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/Graph.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-hgavailabilityhistory/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-hgavailabilityhistory/src/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-hgavailabilityhistory/src/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/widgets.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
  centreon/www/front_src/src/federatedModules/models.ts
Labels: upload-artifacts, skip-workflow-web, skip-workflow-web-analysis, qa-approved

#7993 enh(Authentication): OIDC End Session Endpoint parameter not taken in… (#7793)
  centreon/packages/js-config/cypress/e2e/commands.ts
  centreon/phpstan.core.neon
  centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
  centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php
  centreon/src/Core/Security/Authentication/Infrastructure/Repository/WriteSessionRepository.php
  centreon/tests/e2e/features/Authentication/OpenID-connect/common.ts
  centreon/tests/e2e/support/commands.ts
Labels: area/backend, backport, skip-workflow-web, skip-workflow-web-analysis, qa-approved
