Repository centreon/centreon, pull requests merged in 2025-01, with the labels that each got.

#6267 enh(UI): Unexpected array when using public playlists using an "old" browser
  centreon/www/front_src/src/publicPages/usePageResolver.ts
Labels: backport, skip-workflow-web

#6266 enh(UI): Sync widget options with available widgets
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/useWidgetSelection.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
Labels: backport, skip-workflow-web

#6274 fix(Tests): Fix browser date on Resources table tests
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
Labels: area/test, skip-workflow-web

#6248 enh(ACC & PAC): add lighthouse performance tests
  centreon/lighthouse/src/fixtures/additionalConnectors.js
  centreon/lighthouse/src/fixtures/agentConfiguration.js
  centreon/lighthouse/src/lighthouseReport.ts
  centreon/lighthouse/src/pages/additionalConnecters.ts
  centreon/lighthouse/src/pages/agentConfiguration.ts
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Listing/Listing.tsx
Labels: area/ui, skip-workflow-web

#6233 enh(Resource Status): Improve copy of executed command by adding "sudo -u centreon-engine"
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/CommandLineCard.tsx
Labels: area/ui, skip-workflow-web

#6048 enh(openid): log errors and improve logging message (#5802)
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: skip-workflow-web

#6047 enh(openid): log errors and improve logging message (#5802)
  centreon/src/Core/Security/Authentication/Domain/Provider/OpenIdProvider.php
Labels: skip-workflow-web

#6208 Sync release 152199
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  .github/workflows/dsm.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  centreon-awie/composer.json
  centreon-awie/composer.lock
  centreon-awie/www/modules/centreon-awie/conf.php
  centreon-awie/www/modules/centreon-awie/upgrade/24.11.0/.gitignore
  centreon-dsm/composer.json
  centreon-dsm/composer.lock
  centreon-dsm/www/modules/centreon-dsm/conf.php
  centreon-dsm/www/modules/centreon-dsm/upgrade/24.11.0/.gitignore
  centreon-ha/.env
  centreon-ha/CHANGELOG.md
  centreon-open-tickets/composer.json
  centreon-open-tickets/composer.lock
  centreon-open-tickets/www/modules/centreon-open-tickets/conf.php
  centreon-open-tickets/www/modules/centreon-open-tickets/upgrade/24.11.0/.gitignore
  centreon/composer.json
  centreon/composer.lock
  centreon/config/services.yaml
  centreon/packaging/centreon-trap.yaml
  centreon/tests/e2e/features/Additional-connectors/02-ACC-listing/index.ts
  centreon/tests/e2e/features/Additional-connectors/03-ACC-deletion/index.ts
  centreon/tests/e2e/features/Additional-connectors/04-ACC-update/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
  centreon/www/install/php/Update-24.10.2.php
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web, skip-workflow-awie, skip-workflow-open-tickets, skip-workflow-dsm

#6282 enh (service): migrate the configuration of the services dependencies behat test to a cypress test
  centreon/behat.yml
  centreon/features/ServiceDependencyConfiguration.feature
  centreon/features/bootstrap/ServiceDependencyConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration.feature
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/dependency.json
Labels: area/backend, area/test, skip-workflow-web

#6234 enh(CEIP): add new metadata to CEIP.
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport, skip-workflow-web

#6288 Fix(UI): Fix dashboard test
  centreon/cypress/fixtures/Dashboards/Dashboard/complexLayout.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dataset -- displays header link to Business activity when the widget has only business activities.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Delete widget -- does not display the name of the widget when the corresponding button is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard with complex layout -- displays a new widget in the correct position when a widget is added.snap.png
Labels: area/test

#6290 fix(packaging): retrieve centreon-perl-libs dependency without version
  centreon/packaging/centreon-trap.yaml
Labels: skip-workflow-web

#6243 enh (host): migrate the configuration of the hosts dependencies behat test to a cypress test
  centreon/behat.yml
  centreon/features/HostDependencyConfiguration.feature
  centreon/features/bootstrap/HostDependencyConfigurationContext.php
  centreon/tests/e2e/features/Hosts/07-host-dependency-configuration.feature
  centreon/tests/e2e/features/Hosts/07-host-dependency-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/features/Services-configuration/10-meta-service-dependency-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/hosts-dependency/host-dependency.json
  centreon/tests/e2e/support/e2e.ts
Labels: area/backend, area/test, skip-workflow-web

#5961 fix(logs): add action logs on host category APIv2 write operations (#5605)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryActionLogRepository.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend, backport, skip-workflow-web

#5960 fix(logs): add action logs on host category APIv2 write operations (#5605)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryActionLogRepository.php
  centreon/tests/rest_api/collections/configuration/Host_Category.postman_collection.json
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend, backport, skip-workflow-web

#6224 fix(logs): add Action Logs on add command endpoint (#5592)
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/DbWriteCommandActionLogRepository.php
Labels: area/backend, backport, skip-workflow-web

#6244 enh (host): migrate the configuration of the hosts dependencies behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/HostDependencyConfiguration.feature
  centreon/features/bootstrap/HostDependencyConfigurationContext.php
  centreon/tests/e2e/features/Hosts/07-host-dependency-configuration.feature
  centreon/tests/e2e/features/Hosts/07-host-dependency-configuration/index.ts
  centreon/tests/e2e/features/Hosts/commands.ts
  centreon/tests/e2e/features/Services-configuration/10-meta-service-dependency-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/hosts-dependency/host-dependency.json
  centreon/tests/e2e/support/e2e.ts
Labels: area/test, backport

#6222 fix(logs): add Action Logs on add command endpoint (#5592)
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/DbWriteCommandActionLogRepository.php
Labels: area/backend, backport, skip-workflow-web

#6249 fix(Top counter): add statistics_default_refresh_interval to /administration/parameters
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/tests/rest_api/collections/administration/Parameters.postman_collection.json
Labels: area/backend, skip-workflow-web

#5414 fix(dashboards): Playlist Disappears After Search Input and Navigation
  centreon/tests/e2e/features/Dashboards/07-dashboard-manage-permissions/index.ts
  centreon/tests/e2e/features/Dashboards/commands.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/DashboardsFilter.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/Filter.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/translatedLabels.ts
Labels: backport, skip-workflow-web

#6281 enh(ceip): Add email in CEIP for Trial Version
  centreon/www/api/class/centreon_ceip.class.php
Labels: skip-workflow-web

#6293 fix(test): fix web e2e update tests
  .github/workflows/web.yml
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update.feature
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: skip-workflow-web

#6235 fix(EventLog): Fix the display issues and PHP errors in the HostGroup…
  centreon/www/include/eventLogs/Paginator.php
  centreon/www/include/eventLogs/xml/PaginationRenderer.php
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend

#6301 fix(test): fix web e2e update tests (#6293)
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update.feature
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: database

#6304 fix(eventLogs): add missing status definition
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web

#6292 fix(exportCfg): GenerateAllConfiguration and ReloadAllConfiguration now handle more than 10 pollers (#6068)
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
Labels: area/backend, skip-workflow-web

#6291 fix(exportCfg): GenerateAllConfiguration and ReloadAllConfiguration now handle more than 10 pollers (#6068)
  centreon/src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurations.php
  centreon/src/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurations.php
  centreon/src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/GenerateAllConfigurationsTest.php
  centreon/tests/php/Centreon/Domain/MonitoringServer/UseCase/ReloadAllConfigurationsTest.php
Labels: area/backend, skip-workflow-web

#6133 enh(database): add description comments to dashboard tables
  centreon/www/install/createTables.sql
Labels: area/backend, skip-workflow-web

#6302 fix(dashboard): incompatibility with MySQL8 fixed
  centreon/src/Core/UserProfile/Infrastructure/Repository/DbReadUserProfileRepository.php
Labels: area/backend, skip-workflow-web

#6305 fix(eventLog): add missing status definition
  centreon/www/include/eventLogs/xml/data.php
Labels: area/backend, backport, skip-workflow-web

#6207 fix(dashboard): do not condition the rights validation on contact_ore…
  centreon/src/Core/Dashboard/Infrastructure/Repository/DbReadDashboardShareRepository.php
Labels: area/backend, skip-workflow-web

#6306 fix(test): fix web e2e update tests (#6293)
  .github/workflows/web.yml
  centreon/tests/e2e/features/Platform-upgrade-update/01-platform-update.feature
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: skip-workflow-web

#6300 enh(CEIP): add new metadata to CEIP. (#6234)
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport

#6200 enh(RS): add flapping and percent state change to find resources
  centreon/src/Centreon/Domain/Monitoring/Resource.php
  centreon/src/Centreon/Domain/Monitoring/ResourceFilter.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/Response/ResourceResponseDto.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesRequestValidator.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-25.01.0.php
Labels: area/backend

#6313 fix(ci): fix docker web dependencies dockerfile repo filename version
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/workflows/docker-web-dependencies.yml
Labels: skip-workflow-docker-web-dependencies

#6316 Fix(tests): Fix snapshots
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not hide metrics field when the Meta service resource type is selected and the Meta service is chosen.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- No widgets -- does not display widgets when any widgets are registered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays general properties when a widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays sub inputs when the corresponding field has the correct value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- hides a property when an option value matches the condition.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- keeps a sub-input value when a sub-input is displayed and its value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Unrecognized widget property -- does not display the widget property when it is not recognized.snap.png
Labels: area/ui, area/test

#6066 feat(tests) : Add tests for Group Monitoring widget Cypress
  centreon/tests/e2e/features/Dashboards/15-group-monitoring-widget-configuration.feature
  centreon/tests/e2e/features/Dashboards/15-group-monitoring-widget-configuration/index.ts
Labels: area/test

#6308 chore(E2E): Adding E2E test for hosts categories & commands actions logs (24.10.x)
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log/index.ts
  centreon/tests/e2e/features/Logs/06-commands-changes-log.feature
  centreon/tests/e2e/features/Logs/06-commands-changes-log/index.ts
  centreon/tests/e2e/fixtures/commands/command.json
  centreon/tests/e2e/fixtures/host-categories/category.json
Labels: area/test, backport

#6319 fix(test): get properly previous major version in e2e tests
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: skip-workflow-web

#6309 chore(E2E): Adding E2E test for hosts categories & commands actions logs (24.04.x)
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log.feature
  centreon/tests/e2e/features/Logs/05-hosts-categories-changes-log/index.ts
  centreon/tests/e2e/features/Logs/06-commands-changes-log.feature
  centreon/tests/e2e/features/Logs/06-commands-changes-log/index.ts
  centreon/tests/e2e/fixtures/commands/command.json
  centreon/tests/e2e/fixtures/host-categories/category.json
Labels: area/test, backport

#6280 fix(docs): openapi syntax & struct errors (#5107)
  centreon/doc/API/README.md
  centreon/doc/API/centreon-api.yaml
  centreon/doc/API/latest/onPremise/Administration/Update/updates.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/DeleteAcPollerLink.yaml
  centreon/doc/API/latest/onPremise/Configuration/AgentConfiguration/DeleteAndUpdateAndFindDetailAc.yaml
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/Dashboard.MetricsTop.yaml
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/DashboardShareContact.yaml
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/Schema/Dashboard.MetricsPerformancesData.yaml
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/Schema/Share/ShareDashboardRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Dashboard/ShareDashboard.yaml
  centreon/doc/API/latest/onPremise/Configuration/GraphTemplate/Schema/FindGraphTemplatesResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/Host/Schema/AddHostRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Host/Schema/AddHostResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/Host/Schema/PartialUpdateHostRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/HostTemplate/Schema/AddHostTemplateRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/HostTemplate/Schema/AddHostTemplateResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/HostTemplate/Schema/FindHostTemplateResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/HostTemplate/Schema/PartialUpdateHostTemplateRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Media/QueryParameter/mediaId.yaml
  centreon/doc/API/latest/onPremise/Configuration/Media/UpdateMedia.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/DeployServices.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/QueryParameter/HostId.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/Schema/AddServiceRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/Schema/FindServicesResponse.yaml
  centreon/doc/API/latest/onPremise/Configuration/Service/Schema/PartialUpdateServiceRequest.yaml
  centreon/doc/API/latest/onPremise/Configuration/ServiceTemplate/AddOneAndFindServiceTemplates.yaml
  centreon/doc/API/latest/onPremise/Configuration/ServiceTemplate/Schema/NewServiceTemplate.yaml
  centreon/doc/API/latest/onPremise/Configuration/ServiceTemplate/Schema/PartialUpdateServiceTemplate.yaml
  centreon/doc/API/latest/onPremise/Platform/Versions.yaml
  centreon/doc/API/latest/onPremise/Realtime/Metrics/Schema/Metric.yaml
  centreon/doc/API/latest/onPremise/Realtime/Resources/Schema/ResourceHostDetail.yaml
  centreon/doc/API/latest/onPremise/Realtime/Resources/Schema/ResourceServiceDetail.yaml
Labels: area/backend, skip-workflow-web

#6331 MON-154334 Sync Release Centreon OSS 23.04
  centreon/.version
  centreon/www/class/centreonGraph.class.php
  centreon/www/include/eventLogs/xml/data.php
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.04.24.php
  widgets/centreon-widget-host-monitoring/host-monitoring/configs.xml
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/configs.xml
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/configs.xml
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/configs.xml
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/index.php
Labels: skip-workflow-web

#6332 MON-154335 Sync release OSS 23.10
  centreon/.version
  centreon/www/class/centreonGraph.class.php
  centreon/www/include/eventLogs/xml/data.php
  centreon/www/include/options/media/images/listImg.ihtml
  centreon/www/include/options/media/images/listImg.php
  centreon/www/include/options/media/images/syncDir.php
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-23.10.19.php
  widgets/centreon-widget-host-monitoring/host-monitoring/configs.xml
  widgets/centreon-widget-host-monitoring/host-monitoring/src/index.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/configs.xml
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/export.php
  widgets/centreon-widget-hostgroup-monitoring/hostgroup-monitoring/src/index.php
  widgets/centreon-widget-live-top10-cpu-usage/live-top10-cpu-usage/configs.xml
  widgets/centreon-widget-live-top10-memory-usage/live-top10-memory-usage/configs.xml
Labels: skip-workflow-web

#5827 fix(symfony) : symfony security-http fixed
  centreon/composer.lock
Labels: bug, area/backend

#5828 fix(symfony) : symfony security-http fixed
  centreon/composer.lock
Labels: bug, area/backend

#5904 enh(logs): insert change logs for /configuration/hosts/severities (#5720)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/HostSeverity/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostSeverity/Infrastructure/Repository/DbWriteHostSeverityActionLogRepository.php
Labels: backport, skip-workflow-web

#6107 fix(configuration): improve input sanitization for contact form (#6017)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: backport

#6105 fix(configuration): improve input sanitization for contact form (#6017)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: backport, skip-workflow-web

#5893 fix(Authentication): Unable to login if 2 mail addresses on LDAP (#5553) [dev-23.10.x]
  centreon/www/class/centreonAuth.LDAP.class.php
Labels: area/backend, backport, skip-workflow-web

#6106 fix(configuration): improve input sanitization for contact form (#6017)
  centreon/www/include/configuration/configObject/contact/DB-Func.php
Labels: skip-workflow-web

#6318 enh(dashboard): add SQL upgrade to enable favorite management feature
  centreon/www/install/php/Update-25.01.0.php
Labels: area/backend, skip-workflow-web

#6135 enh(SQL): Enhance query in index of widget service monitoring (#6034)
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
Labels: area/backend, backport

#6137 enh(SQL): Enhance query in index of widget service monitoring (#6034)
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
Labels: area/backend, backport

#6138 enh(SQL): Enhance query in index of widget service monitoring (#6034)
  widgets/centreon-widget-service-monitoring/service-monitoring/src/index.php
Labels: area/backend, backport

#6152 enh(SQL): Enhance query in export of widget service monitoring (#6038)
  widgets/centreon-widget-service-monitoring/service-monitoring/src/export.php
Labels: area/backend, backport

#6151 enh(SQL): Enhance query in export of widget service monitoring (#6038)
  widgets/centreon-widget-service-monitoring/service-monitoring/src/export.php
Labels: area/backend, backport

#6154 Enhance query in export of widget serviceGroup monitoring (#6057)
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
Labels: area/backend, backport

#6155 Enhance query in export of widget serviceGroup monitoring (#6057)
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/export.php
Labels: area/backend, backport

#6165 enh(SQL): Enh sql in export of widget host monitoring (#6076)
  widgets/centreon-widget-host-monitoring/host-monitoring/src/export.php
Labels: area/backend, backport

#6160 enh(SQL): Enh sql in index of widget serviceGroup monitoring (#6075)
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#6159 enh(SQL): Enh sql in index of widget serviceGroup monitoring (#6075)
  widgets/centreon-widget-servicegroup-monitoring/servicegroup-monitoring/src/index.php
Labels: area/backend, backport

#6295 Enh([Dashboards]):[Metrics Graph] Add new time periods
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time Period -- selects the time period Last 12 hours when the corresponding option is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time Period -- selects the time period Last 14 days when the corresponding option is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time Period -- selects the time period Last 2 months when the corresponding option is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time Period -- selects the time period Last 3 hours when the corresponding option is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/TimePeriod.cypress.spec.tsx/Time Period -- selects the time period Last 6 hours when the corresponding option is clicked.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/TimePeriod/useTimePeriod.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts
Labels: skip-workflow-web

#6164 enh(SQL): Enh sql in export of widget host monitoring (#6076)
  widgets/centreon-widget-host-monitoring/host-monitoring/src/export.php
Labels: area/backend, backport

#6041 Fix(Poller/Agent configuration) Translation issues on dialogs
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Dialog/UnsavedChanges/index.tsx
Labels: area/ui, skip-workflow-web

#5934 enh(logs): insert change logs for /configuration/services/severities (#5727)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/ActionLog/Domain/Model/ActionLog.php
  centreon/src/Core/ServiceSeverity/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceSeverity/Infrastructure/Repository/DbWriteServiceSeverityActionLogRepository.php
Labels: backport, skip-workflow-web

#6134 Feat([Dashboards]): add an extend option on widgets
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/details.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/federatedWidgets.ts
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/federatedWidgetsProperties.ts
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/graph.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/groupmonitoring.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/resourcestable.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/statuschartHosts.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/statuschartServices.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/statusgrid.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/topbottom.json
  centreon/cypress/fixtures/Dashboards/Dashboard/ExpandReduce/version.ts
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-graph in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-graph with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-groupmonitoring in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-groupmonitoring with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-resourcestable in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-resourcestable with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statuschart in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statuschart with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statusgrid in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statusgrid with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-topbottom in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-topbottom with expand option.snap.png
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Dashboard/Dashboard.styles.ts
  centreon/packages/ui/src/Dashboard/Item.tsx
  centreon/packages/ui/src/components/ExpandableContainer/ExpandableContainer.tsx
  centreon/packages/ui/src/components/ExpandableContainer/expandableContainer.styles.ts
  centreon/packages/ui/src/components/ExpandableContainer/index.tsx
  centreon/packages/ui/src/components/ExpandableContainer/models.ts
  centreon/packages/ui/src/components/ExpandableContainer/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Layout.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/ExpandableButton.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/MorePanelActions.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/PanelHeader.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Layout/Panel/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-batree/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-groupmonitoring/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-topbottom/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-webpage/properties.json
  centreon/www/front_src/src/Dashboards/translatedLabels.tsx
  centreon/www/front_src/src/federatedModules/models.ts
Labels: skip-workflow-web

#5894 enh(Change Logs): Insert change logs for service configuration endpoints (#5382)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Service/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/www/class/centreonLogAction.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
Labels: area/backend, skip-workflow-web

#6120 enh(RS): fix contacts list in host detail pannel & get rid of call to legacy
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadHostNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindNotificationPolicyResponse.php
  centreon/src/Core/Domain/Configuration/Notification/Model/NotifiedContact.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbNotifiedContactFactory.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbReadHostNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadHostNotificationRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
Labels: area/backend

#6223 fix(DSM): White page when creating a pool (#5497)
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/DB-Func.php
  centreon-dsm/www/modules/centreon-dsm/core/configuration/services/formSlot.php
Labels: skip-workflow-dsm

#6328 fix(media): correctly sync / check directories and files
  centreon/www/include/options/media/images/syncDir.php
Labels: area/backend, skip-workflow-web

#6353 enh(legacy): Retrieving Symfony environment variables for legacy code (#6127)
  centreon/bootstrap.php
Labels: area/backend, backport

#6197 fix(packaging): set centreon env files as config files (#6108)
  centreon/packaging/centreon-web.yaml
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: skip-workflow-web

#6198 fix(packaging): set centreon env files as config files (#6108)
  centreon/packaging/centreon-web.yaml
  centreon/packaging/scripts/centreon-web-postinstall.sh
Labels: skip-workflow-web

#6322 enh(CEIP): add new metadata to CEIP (#6234)
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport, skip-workflow-web

#6323 enh(CEIP): add new metadata to CEIP. (#6234)
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport, skip-workflow-web

#6324 enh(CEIP): add new metadata to CEIP. (#6234)
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport, skip-workflow-web

#6325 enh(CEIP): add new metadata to CEIP. (#6234)
  centreon/tests/e2e/cypress/support/e2e.ts
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport, skip-workflow-web

#6327 enh(CEIP): add new metadata to CEIP. (#6234)
  centreon/www/api/class/centreon_ceip.class.php
Labels: area/backend, backport

#5974 fix(graph): modernise queries (#5878)
  centreon/www/class/centreonGraph.class.php
Labels: area/backend, backport

#6070 fix(media): Validate content for Binary files
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend, skip-workflow-web

#5834 fix (acl): indicates that ACLs need to be recalculated after services have been deployed
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/host.php
Labels: area/backend, skip-workflow-web

#6329 enh (service-group): migrate the configuration of the service groups dependencies behat test to a cypress test
  centreon/behat.yml
  centreon/features/ServiceGroupDependencyConfiguration.feature
  centreon/features/bootstrap/ServiceGroupDependencyConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration.feature
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/dependency.json
  centreon/tests/e2e/fixtures/services/service.json
Labels: area/backend, area/test, skip-workflow-web

#6339 enh (service-group): migrate the configuration of the service groups dependencies behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/ServiceGroupDependencyConfiguration.feature
  centreon/features/bootstrap/ServiceGroupDependencyConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration.feature
  centreon/tests/e2e/features/Services-configuration/11-service-dependency-configuration/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/dependency.json
  centreon/tests/e2e/fixtures/services/service.json
Labels: area/test, backport, skip-workflow-web

#6363 enh(RS): fix contacts list in host detail pannel & get rid of call to legacy (#6120)
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadHostNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindNotificationPolicyResponse.php
  centreon/src/Core/Domain/Configuration/Notification/Model/NotifiedContact.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbNotifiedContactFactory.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbReadHostNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadHostNotificationRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
Labels: backport, skip-workflow-web

#6364 enh(RS): fix contacts list in host detail pannel & get rid of call to legacy (#6120)
  centreon/src/Core/Application/Configuration/Notification/Repository/ReadHostNotificationRepositoryInterface.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicy.php
  centreon/src/Core/Application/Configuration/NotificationPolicy/UseCase/FindNotificationPolicyResponse.php
  centreon/src/Core/Domain/Configuration/Notification/Model/NotifiedContact.php
  centreon/src/Core/HostTemplate/Application/Repository/ReadHostTemplateRepositoryInterface.php
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbReadHostTemplateRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/AbstractDbReadNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbNotifiedContactFactory.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/DbReadHostNotificationRepository.php
  centreon/src/Core/Infrastructure/Configuration/NotificationPolicy/Repository/LegacyReadHostNotificationRepository.php
  centreon/tests/php/Core/Application/Configuration/NotificationPolicy/UseCase/FindHostNotificationPolicyTest.php
Labels: backport, skip-workflow-web

#6307 enh(map): Zoom Components enhancement to enable save perspective in the new VIEWER
  centreon/packages/ui/src/components/Zoom/Zoom.tsx
  centreon/packages/ui/src/components/Zoom/ZoomContent.tsx
  centreon/packages/ui/src/components/Zoom/models.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardConfig/useDashboardConfig.tsx
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/favoriteAction/FavoriteAction.tsx
  centreon/www/front_src/src/Navigation/Sidebar/Menu/MenuItems.tsx
Labels: area/ui, skip-workflow-web

#6297 fix(Top counter): add & use statistics refresh interval instead of monitoring refresh
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/statisticsRefreshIntervalAtom.ts
  centreon/src/Centreon/Application/Controller/Administration/ParametersController.php
  centreon/tests/rest_api/collections/administration/Parameters.postman_collection.json
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
Labels: area/ui, area/backend, skip-workflow-web

#6077 enh(Dashboards): added health calculation in Status grid widget for Impact BAs (#6020) [dev-24.10.x]
  centreon/cypress/fixtures/Widgets/StatusGrid/criticalImpactBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/criticalRatioBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/impactBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/ratioBA.json
  centreon/cypress/fixtures/Widgets/StatusGrid/worstStatusBA.json
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/BATooltipContent.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tooltip/useBATooltipContent.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/api/decoders.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/spec/StatusGridWithBam.cypress.spec.tsx
Labels: area/ui, backport, skip-workflow-web

#6355 fix(media): correctly sync / check directories and files (#6328)
  centreon/www/include/options/media/images/syncDir.php
Labels: area/backend, backport, skip-workflow-web

#6192 chore(deps): absorb 25.01 dependabot GitHub Actions updates
  .github/actions/chromatic/action.yml
  .github/actions/create-jira-ticket/action.yml
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/frontend-lint/action.yml
  .github/actions/lighthouse-performance-testing/action.yml
  .github/actions/lighthouse-to-s3/action.yml
  .github/actions/npm-publish-package-beta/action.yml
  .github/actions/npm-publish-package-stable/action.yml
  .github/actions/package/action.yml
  .github/actions/promote-to-stable/action.yml
  .github/actions/publish-cypress-report/action.yml
  .github/actions/publish-storybook/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/release/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/awie-analysis.yml
  .github/workflows/awie.yml
  .github/workflows/behat-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/clean-cache.yml
  .github/workflows/clean-npm-tags.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm-analysis.yml
  .github/workflows/dsm.yml
  .github/workflows/get-environment.yml
  .github/workflows/js-config-beta.yml
  .github/workflows/js-config-stable.yml
  .github/workflows/newman.yml
  .github/workflows/nightly-cod-platform-deploy.yml
  .github/workflows/nightly-cod-platform-destroy.yml
  .github/workflows/open-tickets-analysis.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/release-trigger-builds.yml
  .github/workflows/release.yml
  .github/workflows/synchronize-jira-xray.yml
  .github/workflows/ui-beta.yml
  .github/workflows/ui-context-beta.yml
  .github/workflows/ui-context-stable.yml
  .github/workflows/ui-stable.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web-analysis.yml
  .github/workflows/web.yml
Labels: dependencies, gha, skip-workflow-create-repo-yum

#6392 Chore(release) Bump dsm 24.04.4 web 24.04.10
  centreon-dsm/.version
  centreon-dsm/www/modules/centreon-dsm/conf.php
  centreon-dsm/www/modules/centreon-dsm/upgrade/24.04.4/.gitignore
  centreon/.version
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-24.04.10.php
Labels: skip-cherry-pick

#6395 chore(release) Bump web to 24.10.4
  centreon/.version
  centreon/www/install/insertBaseConf.sql
Labels: skip-cherry-pick

#6385 feat(Service Categories): Add Action Logs (#5712)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostTemplate/Infrastructure/Repository/DbWriteHostTemplateActionLogRepository.php
  centreon/src/Core/Service/Infrastructure/Repository/DbWriteServiceActionLogRepository.php
  centreon/src/Core/ServiceCategory/Application/Repository/WriteServiceCategoryRepositoryInterface.php
  centreon/src/Core/ServiceCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/ServiceCategory/Infrastructure/Repository/DbWriteServiceCategoryActionLogRepository.php
  centreon/www/class/centreonHost.class.php
  centreon/www/include/Administration/configChangelog/viewLogs.php
  centreon/www/include/configuration/configObject/command/DB-Func.php
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
  centreon/www/include/configuration/configObject/hostgroup/DB-Func.php
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service_categories/DB-Func.php
  centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
Labels: area/backend, backport, skip-workflow-web

#6399 chore(release) bump oss 22.10 january 2025
  centreon/.version
  centreon/www/install/insertBaseConf.sql
  centreon/www/install/php/Update-22.10.28.php
  widgets/centreon-widget-service-monitoring/service-monitoring/configs.xml
Labels: skip-cherry-pick

#5962 fix(logs): add action logs on host category APIv2 write operations (#5605)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/HostCategory/Application/UseCase/UpdateHostCategory/UpdateHostCategory.php
  centreon/src/Core/HostCategory/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/HostCategory/Infrastructure/Repository/DbWriteHostCategoryActionLogRepository.php
  centreon/www/include/configuration/configObject/host_categories/DB-Func.php
Labels: area/backend, backport, skip-workflow-web

#6369 fix(media): Validate content for Binary files (#6070)
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend

#6367 fix(media): Validate content for Binary files (#6070)
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend, skip-workflow-web

#6365 fix(media): Validate content for Binary files (#6070)
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend, skip-workflow-web

#6360 fix(media): Validate content for Binary files (#6070)
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend, skip-workflow-web

#6366 fix(media): Validate content for Binary files (#6070)
  centreon/www/include/common/getHiddenImage.php
  centreon/www/include/options/media/images/DB-Func.php
Labels: area/backend, skip-workflow-web

#6357 fix(media): correctly sync / check directories and files (#6328)
  centreon/www/include/options/media/images/syncDir.php
Labels: area/backend, backport, skip-workflow-web

#6380 enh(Resource status): adjust the size of the graphs to fit the available width
  centreon/www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
Labels: area/ui, skip-workflow-web

#6225 fix(logs): add Action Logs on add command endpoint (#5592)
  centreon/config/packages/Centreon.yaml
  centreon/src/Core/Command/Infrastructure/Configuration/symfony.yaml
  centreon/src/Core/Command/Infrastructure/Repository/DbWriteCommandActionLogRepository.php
Labels: area/backend, backport, skip-workflow-web

#6368 Fix([Dashboard]): reforce update of listing in case of adding/removing a favorit from details page
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
Labels: skip-workflow-web

#6315 enh(resources status): Add Flapping state to RS page, resource table and status grid widget
  centreon/cypress/fixtures/resources/listing/listingWithStates.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on dark theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Icon/FlappingIcon.tsx
  centreon/packages/ui/src/Icon/index.ts
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/src/Centreon/Domain/Monitoring/Resource.php
  centreon/src/Centreon/Domain/Monitoring/ResourceFilter.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/Response/ResourceResponseDto.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesRequestValidator.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/properties.json
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/Chip/Flapping.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/State.styles.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/Columns/State/index.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/colors.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/State.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
  centreon/www/front_src/src/Resources/Chip/Flapping.tsx
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/PercentStateChangeCard.tsx
  centreon/www/front_src/src/Resources/Filter/Criterias/models.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/FilterSearchQuery.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/State/index.tsx
  centreon/www/front_src/src/Resources/colors.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-25.01.0.php
Labels: area/ui, area/backend, skip-workflow-web

#6400 enh (escalation): migrate the configuration of the escalation behat test to a cypress test
  centreon/behat.yml
  centreon/features/EscalationConfiguration.feature
  centreon/features/bootstrap/EscalationConfigurationContext.php
  centreon/tests/e2e/features/Notifications/01-escalation-configuration.feature
  centreon/tests/e2e/features/Notifications/01-escalation-configuration/index.ts
  centreon/tests/e2e/features/Notifications/commands.ts
  centreon/tests/e2e/fixtures/notifications/escalation.json
  centreon/tests/e2e/support/commands.ts
Labels: area/backend, area/test, skip-workflow-web

#6403 enh (escalation): migrate the configuration of the escalation behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/EscalationConfiguration.feature
  centreon/features/bootstrap/EscalationConfigurationContext.php
  centreon/tests/e2e/features/Notifications/01-escalation-configuration.feature
  centreon/tests/e2e/features/Notifications/01-escalation-configuration/index.ts
  centreon/tests/e2e/features/Notifications/commands.ts
  centreon/tests/e2e/fixtures/notifications/escalation.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web

#6356 fix(media): correctly sync / check directories and files (#6328)
  centreon/www/include/options/media/images/syncDir.php
Labels: area/backend, backport, skip-workflow-web

#6343 enh(Top counter): improved top counter display management
  centreon/composer.lock
  centreon/config/symfony_serializer/Common/NotEmptyString.yaml
  centreon/config/symfony_serializer/User/FindUserPermissionsResponse.yaml
  centreon/config/symfony_serializer/User/Permission.yaml
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Header/specs/Header.cypress.spec.tsx/User Menu -- using the dark mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Header/specs/Header.cypress.spec.tsx/User Menu -- using the light mode.snap.png
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui-context/src/userPermissionsAtom.ts
  centreon/phpstan.core.neon
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
  centreon/src/Core/User/Application/UseCase/FindUserPermissions/FindUserPermissions.php
  centreon/src/Core/User/Application/UseCase/FindUserPermissions/FindUserPermissionsResponse.php
  centreon/src/Core/User/Domain/Model/Permission.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsResponseNormalizer.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsRoute.yaml
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/PermissionNormalizer.php
  centreon/www/front_src/src/App/endpoint.ts
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Header/Poller/usePollerData.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
  centreon/www/front_src/src/Header/specs/Header.utils.tsx
Labels: area/ui, area/backend, skip-workflow-web

#6341 fix(UI): Update the wording of the confirmation popups
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Dialog/UnsavedChanges/index.tsx
  centreon/packages/ui/src/Dialog/UnsavedChanges/translatedLabels.ts
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation.feature
  centreon/tests/e2e/features/Additional-connectors/01-ACC-creation/index.ts
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation.feature
  centreon/tests/e2e/features/Agent-configuration/01-agent-configuration-creation/index.ts
Labels: area/ui, skip-workflow-web

#6401 fix (acl): indicates that ACLs need to be recalculated after service have been deployed (#5834)
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/host.php
Labels: area/backend, backport, skip-workflow-web

#6414 enh(ci): trigger workflows on new major version
  .github/workflows/awie.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6415 enh(ci): trigger workflows on new major version (#6414)
  .github/workflows/awie.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6386 enh(UI): Use same background on the preview
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not hide metrics field when the Meta service resource type is selected and the Meta service is chosen.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- does not suggest a selected resource type when adding new resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- hides the delete button when there is only one resource.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- removes resource item when delete icon is clicked.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects metrics when resources are selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Data -- Resources and metrics -- selects one metric when the widget allows only one metric.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- No widgets -- does not display widgets when any widgets are registered.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the modal.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- displays the title and the description in the preview when corresponding fields are edited.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- enables the add button when a widget is selected and the properties are filled.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Add widget -- keeps the name when a widget is selected, properties are filled and the widget type is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- changes the widget type when another widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- Edit widget -- displays the modal with pre-filled values.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays general properties when a widget is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays sub inputs when the corresponding field has the correct value.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays the preview of the generic text widget when the generic text widget type is selected.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- displays widgets icon when widget type field is expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- does not display the content of the generic text widget in the preview the show description switch is off.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- hides a property when an option value matches the condition.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Properties -- keeps a sub-input value when a sub-input is displayed and its value is changed.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/AddEditWidgetModal.cypress.spec.tsx/AddEditWidgetModal -- Unrecognized widget property -- does not display the widget property when it is not recognized.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- Dataset -- displays header link to Business activity when the widget has only business activities.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in editor mode when the user has editor role and the user is not editing the dashboard.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard -- View mode -- displays the widget form in view mode when the user has viewer role.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/Dashboard with complex layout -- displays a new widget in the correct position when a widget is added.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-graph in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-graph with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-groupmonitoring in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-groupmonitoring with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-resourcestable in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-resourcestable with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statuschart in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statuschart with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statusgrid in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-statusgrid with expand option.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-topbottom in mode expanded.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx/centreon-widget-topbottom with expand option.snap.png
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/addWidget.styles.ts
Labels: area/ui, skip-workflow-web

#6426 enh(ci): manage stability in dependencies containers
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  .github/workflows/docker-web-dependencies.yml
Labels: skip-workflow-docker-web-dependencies

#6428 enh(ci): manage stability in dependencies containers (#6426)
  .github/docker/centreon-web/alma8/Dockerfile
  .github/docker/centreon-web/alma8/Dockerfile.dependencies
  .github/docker/centreon-web/alma9/Dockerfile
  .github/docker/centreon-web/alma9/Dockerfile.dependencies
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/docker/centreon-web/jammy/Dockerfile.dependencies
  .github/workflows/docker-web-dependencies.yml
Labels: skip-workflow-docker-web-dependencies

#6427 enh(Resource status): adjust the size of the graphs to fit the availa…
  centreon/www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
Labels: skip-workflow-web

#6046 fix(ACC): handle correctly folder and files permissions for ACC Vmware conf
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend, skip-workflow-web

#6429 enh(resources status): Add Flapping state to RS page, resource table and status grid widget (#6315)
  centreon/cypress/fixtures/resources/listing/listingWithStates.json
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on dark theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx/Resource Listing rows and picto colors on light theme -- displays the listing row in flapping color when the resource is in flapping state only.snap.png
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/packages/ui/src/Icon/DowntimeIcon.tsx
  centreon/packages/ui/src/Icon/FlappingIcon.tsx
  centreon/packages/ui/src/Icon/index.ts
  centreon/packages/ui/src/ThemeProvider/palettes.ts
  centreon/src/Centreon/Domain/Monitoring/Resource.php
  centreon/src/Centreon/Domain/Monitoring/ResourceFilter.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/FindResourcesFactory.php
  centreon/src/Core/Resources/Application/UseCase/FindResources/Response/ResourceResponseDto.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
  centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesRequestValidator.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
  centreon/src/Core/Resources/Infrastructure/Repository/DbResourceFactory.php
  centreon/www/front_src/src/Resources/Chip/Flapping.tsx
  centreon/www/front_src/src/Resources/Details/Details.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Details/tabs/Details/DetailsCard/PercentStateChangeCard.tsx
  centreon/www/front_src/src/Resources/Filter/Criterias/models.ts
  centreon/www/front_src/src/Resources/Filter/Criterias/searchQueryLanguage/FilterSearchQuery.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/ResourceListing.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Listing/columns/State/index.tsx
  centreon/www/front_src/src/Resources/colors.ts
  centreon/www/front_src/src/Resources/translatedLabels.ts
  centreon/www/install/createTablesCentstorage.sql
  centreon/www/install/php/Update-24.10.4.php
  centreon/www/widgets/src/centreon-widget-resourcestable/properties.json
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/State/Chip/Flapping.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/State/State.styles.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/Columns/State/index.tsx
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/colors.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
  centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/State.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/StatusGrid.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/Tile.tsx
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/models.ts
  centreon/www/widgets/src/centreon-widget-statusgrid/src/StatusGridStandard/utils.ts
Labels: area/backend, backport, skip-workflow-web

#6436 fix(ACC): handle correctly folder and files permissions for ACC Vmware conf (#6046)
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend, backport, skip-workflow-web

#6439 fix(ACC): handle correctly folder and files permissions for ACC Vmware conf (#6436)
  centreon/src/Core/AdditionalConnectorConfiguration/Domain/Model/VmWareV6/VmWareV6Parameters.php
  centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
  centreon/www/class/config-generate/AdditionalConnectorVmWareV6.class.php
  centreon/www/class/config-generate/backend.class.php
  centreon/www/class/config-generate/generate.class.php
Labels: area/backend, backport, skip-workflow-web

#6437 enh(ci): manage apt internal repository
  .github/actions/deb-delivery/action.yml
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
Labels: skip-workflow-docker-web-dependencies, skip-workflow-web

#6442 enh(ci): manage apt internal repository (#6437)
  .github/actions/deb-delivery/action.yml
  .github/docker/centreon-web/bookworm/Dockerfile.dependencies
  .github/workflows/awie.yml
  .github/workflows/dsm.yml
  .github/workflows/ha.yml
  .github/workflows/open-tickets.yml
  .github/workflows/web.yml
  centreon/tests/e2e/features/Platform-upgrade-update/02-platform-upgrade/index.ts
Labels: skip-workflow-docker-web-dependencies

#6421 Fix(UI): Retrieve services names on filter
  centreon/www/front_src/src/AdditionalConnectorConfiguration/Specs/Acc.modal.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/api/endpoint.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/model.ts-E
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/utils.ts-E
Labels: area/ui, skip-workflow-web

#6444 fix(test): use target stability in e2e upgrade tests (#6354)
  .github/actions/cypress-e2e-testing/action.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/web.yml
  centreon/packages/js-config/cypress/e2e/configuration.ts
  centreon/tests/e2e/features/Platform-upgrade-update/common.ts
Labels: skip-workflow-web

#6416 chore(E2E): Adding E2E test for the Refresh intervals of the top counters
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics.feature
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics/index.ts
Labels: area/test

#6404 enh (escalation): migrate the configuration of the escalations behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/EscalationConfiguration.feature
  centreon/features/bootstrap/EscalationConfigurationContext.php
  centreon/tests/e2e/features/Notifications/01-escalation-configuration.feature
  centreon/tests/e2e/features/Notifications/01-escalation-configuration/index.ts
  centreon/tests/e2e/features/Notifications/commands.ts
  centreon/tests/e2e/fixtures/notifications/escalation.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web

#6402 fix (acl): indicates that ACLs need to be recalculated after service have been deployed (#5834)
  centreon/www/include/configuration/configObject/host/DB-Func.php
  centreon/www/include/configuration/configObject/host/host.php
Labels: area/backend, backport, skip-workflow-web

#6069 fix (media): SVG clean-up after downloading
  centreon/www/include/options/media/images/formImg.php
  centreon/www/include/options/media/images/images.php
Labels: area/backend, skip-workflow-web

#6417 enh(Top counter): improved top counter display management (#6343)
  centreon/config/symfony_serializer/Common/NotEmptyString.yaml
  centreon/config/symfony_serializer/User/FindUserPermissionsResponse.yaml
  centreon/config/symfony_serializer/User/Permission.yaml
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Header/specs/Header.cypress.spec.tsx/User Menu -- using the dark mode.snap.png
  centreon/cypress/visual-testing-snapshots/www/front_src/src/Header/specs/Header.cypress.spec.tsx/User Menu -- using the light mode.snap.png
  centreon/packages/ui-context/src/index.ts
  centreon/packages/ui-context/src/types.ts
  centreon/packages/ui-context/src/userPermissionsAtom.ts
  centreon/phpstan.core.neon
  centreon/src/Centreon/Domain/Contact/Contact.php
  centreon/src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
  centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
  centreon/src/Core/User/Application/UseCase/FindUserPermissions/FindUserPermissions.php
  centreon/src/Core/User/Application/UseCase/FindUserPermissions/FindUserPermissionsResponse.php
  centreon/src/Core/User/Domain/Model/Permission.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsResponseNormalizer.php
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsRoute.yaml
  centreon/src/Core/User/Infrastructure/API/FindUserPermissions/PermissionNormalizer.php
  centreon/www/front_src/src/App/endpoint.ts
  centreon/www/front_src/src/App/useApp.ts
  centreon/www/front_src/src/Header/Poller/usePollerData.ts
  centreon/www/front_src/src/Header/Resources/useResourceCounters.tsx
  centreon/www/front_src/src/Header/specs/Header.utils.tsx
Labels: area/ui, area/backend, backport, skip-workflow-web

#6430 enh(Resource status): adjust the size of the graphs to fit the availa…
  centreon/www/front_src/src/Resources/Details/tabs/Services/Graphs.tsx
Labels: area/ui, skip-workflow-web

#6458 [E2E] Remove unecessary test combinaison on cloud notifications
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create/index.ts
Labels: area/test, skip-workflow-web

#6434 Enh: Get rid of JS errors in the console
  centreon/packages/ui/src/api/useMutationQuery/useOptimisticMutation.ts
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardConfig/DashboardConfigModal.tsx
Labels: skip-workflow-web

#6477 [E2E] Remove unecessary test combinaison on cloud notifications-dev-24.10.x
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create.feature
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create/index.ts
Labels: area/test

#6464 Backport([Dashboard]): reforce update of listing in case of adding/removing a favorit from details page
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
Labels: skip-workflow-web

#6447 Fix(UI): Retrieve services names on filter
  centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/Actions/favoriteAction/FavoriteAction.tsx
  centreon/www/front_src/src/Resources/Filter/Filter.cypress.spec.tsx
  centreon/www/front_src/src/Resources/Filter/api/endpoint.ts
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/basicFilter/SelectInput.tsx
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/model.ts-E
  centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/utils.ts-E
Labels: backport, skip-workflow-web

#6479 Revert "Backport([Dashboard]): reforce update of listing in case of adding/removing a favorit from details page"
  centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
Labels: skip-workflow-web

#6462 fix(PAC): Search field is empty after navigating to another page and returning
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/Search.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/useSearch.ts
Labels: area/ui, skip-workflow-web

#6321 enh(services): Use APIv2 while deleting service/template through the UI
  centreon/www/include/configuration/configObject/service/DB-Func.php
  centreon/www/include/configuration/configObject/service/serviceByHost.php
  centreon/www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Labels: area/backend, skip-workflow-web

#6441 enh (service by host group): migrate the configuration of the host group service behat test to a cypress test
  centreon/behat.yml
  centreon/features/HostGroupServiceConfiguration.feature
  centreon/features/bootstrap/HostGroupServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/12-host-group-service.feature
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/data.json
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/host_group.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, skip-workflow-web

#6488 chore(E2E): Adding E2E test for the Refresh intervals of the top counters (24.10.x)
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics.feature
  centreon/tests/e2e/features/Administration/02-refresh-interval-for-statistics/index.ts
Labels: area/test, backport

#6491 enh (service by host group): migrate the configuration of the host group service behat test to a cypress test (24.10.x)
  centreon/behat.yml
  centreon/features/HostGroupServiceConfiguration.feature
  centreon/features/bootstrap/HostGroupServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/12-host-group-service.feature
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/data.json
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/host_group.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web

#6381 fix(administration/parameters): refresh intervals for statistics field should not accepts numbers less than 10
  centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
  centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  centreon/www/include/Administration/parameters/DB-Func.php
  centreon/www/include/Administration/parameters/general/form.php
Labels: area/backend, skip-workflow-web

#6497 [E2E] fix cloud notification test on dev-24.04.x
  centreon/tests/e2e/features/Cloud-notifications/01-notification-create/index.ts
Labels: area/test

#6476 fix(CentreonLog) : displaying of previous exception in a log fixed
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonLog.class.php
Labels: bug, area/backend, skip-workflow-web

#6438 fix(smarty) : extends tag fixed and error handling added for the displaying of smarty templates
  centreon/GPL_LIB/smarty-plugins/SmartyCentreon.php
  centreon/composer.json
  centreon/www/api/class/centreon_configuration_broker.class.php
  centreon/www/api/class/centreon_home_customview.class.php
  centreon/www/include/common/common-Func.php
  centreon/www/include/common/templates/error.ihtml
  centreon/www/include/configuration/configObject/command/formArguments.php
  centreon/www/include/configuration/configObject/command/formMacros.php
  centreon/www/install/steps/functions.php
Labels: area/backend, backport, skip-workflow-web

#6500 fix(PAC): Search field is empty after navigating to another page and …
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/Search.tsx
  centreon/www/front_src/src/AgentConfiguration/Listing/Actions/useSearch.ts
Labels: skip-workflow-web

#6473 chore(deps): absorb 2025-01 dependabot GitHub Actions updates
  .github/actions/cypress-e2e-testing/action.yml
  .github/actions/deb-delivery/action.yml
  .github/actions/frontend-build/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/package/action.yml
  .github/actions/promote-to-stable/action.yml
  .github/actions/release-sources/action.yml
  .github/actions/rpm-delivery/action.yml
  .github/actions/veracode-generate-binary/action.yml
  .github/workflows/behat-test.yml
  .github/workflows/create-repo-yum.yml
  .github/workflows/cypress-component-parallelization.yml
  .github/workflows/cypress-e2e-parallelization.yml
  .github/workflows/docker-glpi.yml
  .github/workflows/docker-keycloak.yml
  .github/workflows/docker-packaging.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-translation.yml
  .github/workflows/docker-vault.yml
  .github/workflows/docker-web-dependencies.yml
  .github/workflows/ha.yml
  .github/workflows/newman.yml
  .github/workflows/open-tickets.yml
  .github/workflows/package.yml
  .github/workflows/veracode-analysis.yml
  .github/workflows/web.yml
Labels: skip-workflow-create-repo-yum

#6504 fix(CentreonLog) : displaying of previous exception in a log fixed
  centreon/tests/php/www/class/CentreonLogTest.php
  centreon/www/class/centreonLog.class.php
Labels: area/backend, backport, skip-workflow-web

#6492 enh (service by host group): migrate the configuration of the host group service behat test to a cypress test (24.04.x)
  centreon/behat.yml
  centreon/features/HostGroupServiceConfiguration.feature
  centreon/features/bootstrap/HostGroupServiceConfigurationContext.php
  centreon/tests/e2e/features/Services-configuration/12-host-group-service.feature
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/data.json
  centreon/tests/e2e/features/Services-configuration/12-host-group-service/index.ts
  centreon/tests/e2e/features/Services-configuration/commands.ts
  centreon/tests/e2e/fixtures/services/host_group.json
  centreon/tests/e2e/support/commands.ts
Labels: area/test, backport, skip-workflow-web
